import type { NeighborhoodStat } from '../types/geoforge.types';
import type { EquityIndexResult } from './equityIndex';
import type { MoransIResult } from './spatialStats';

interface MemoParams {
  taxYear: number;
  county: string;
  assessorName: string;
  generatedDate: string;
  neighborhoodStats: NeighborhoodStat[];
  eqi: EquityIndexResult | null;
  moransI: MoransIResult | null;
}

function iaaoPass(ns: NeighborhoodStat): boolean {
  const { medianRatio, cod, prd } = ns.stats;
  return medianRatio >= 0.90 && medianRatio <= 1.10 && cod <= 20 && prd >= 0.98 && prd <= 1.03;
}

function fmt3(n: number): string { return n.toFixed(3); }
function fmt1(n: number): string { return n.toFixed(1); }
function fmtPct(n: number): string { return `${n.toFixed(1)}%`; }

function padR(s: string, w: number): string { return s.padEnd(w, ' '); }
function padL(s: string, w: number): string { return s.padStart(w, ' '); }

export function generateDorMemo(params: MemoParams): string {
  const {
    taxYear, county, assessorName, generatedDate,
    neighborhoodStats, eqi, moransI,
  } = params;

  const qualified = neighborhoodStats.filter((ns) => ns.saleCount >= 5);
  const totalSales = neighborhoodStats.reduce((s, n) => s + n.saleCount, 0);
  const passing = qualified.filter(iaaoPass);
  const failing = qualified.filter((ns) => !iaaoPass(ns));
  const critical = failing.filter(
    (ns) => Math.abs(ns.stats.medianRatio - 1) > 0.10 || ns.stats.cod > 20
  );

  // County-wide weighted averages
  const wAvg = (fn: (ns: NeighborhoodStat) => number): number => {
    const tot = qualified.reduce((s, n) => s + n.saleCount, 0);
    if (tot === 0) return 0;
    return qualified.reduce((s, n) => s + fn(n) * n.saleCount, 0) / tot;
  };
  const cwMed = wAvg((n) => n.stats.medianRatio);
  const cwCod = wAvg((n) => n.stats.cod);
  const cwPrd = wAvg((n) => n.stats.prd);
  const passRate = qualified.length > 0 ? (passing.length / qualified.length) * 100 : 0;

  const countyPass =
    cwMed >= 0.90 && cwMed <= 1.10 && cwCod <= 20 && cwPrd >= 0.98 && cwPrd <= 1.03;

  const lines: string[] = [];

  // ── Title block ──────────────────────────────────────────────────────────
  lines.push('═'.repeat(72));
  lines.push(`WASHINGTON STATE DEPARTMENT OF REVENUE`);
  lines.push(`RATIO STUDY NARRATIVE — WAC 458-53A`);
  lines.push('─'.repeat(72));
  lines.push(`County:            ${county} County`);
  lines.push(`Tax Year:          ${taxYear}`);
  lines.push(`Classification:    Residential Real Property`);
  lines.push(`Assessor:          ${assessorName}`);
  lines.push(`Report Date:       ${generatedDate}`);
  lines.push(`DRAFT — Generated by TerraFusion GeoForge · Not a final certification`);
  lines.push('═'.repeat(72));
  lines.push('');

  // ── Executive Summary ─────────────────────────────────────────────────────
  lines.push('I. EXECUTIVE SUMMARY');
  lines.push('─'.repeat(40));
  const grade = eqi ? `${eqi.grade} (${eqi.score}/100)` : 'N/A';
  lines.push(`County Equity Index (EQI):  ${grade}`);
  lines.push(`County-wide IAAO Status:    ${countyPass ? 'COMPLIANT' : 'NON-COMPLIANT'}`);
  lines.push(`Neighborhoods analyzed:     ${qualified.length} (with ≥ 5 qualified sales)`);
  lines.push(`Neighborhoods passing IAAO: ${passing.length} of ${qualified.length} (${fmtPct(passRate)})`);
  lines.push(`Neighborhoods requiring     `);
  lines.push(`  corrective action:        ${failing.length}`);
  lines.push(`Total qualified sales:      ${totalSales.toLocaleString()}`);
  lines.push('');

  if (!countyPass) {
    lines.push('CORRECTIVE ACTION REQUIRED: County-wide statistics do not meet');
    lines.push('WAC 458-53A standards. See Section IV for recommended adjustments.');
  } else {
    lines.push('County-wide statistics meet WAC 458-53A IAAO standards.');
  }
  lines.push('');

  // ── County-wide Stats ─────────────────────────────────────────────────────
  lines.push('II. COUNTY-WIDE RATIO STUDY STATISTICS');
  lines.push('─'.repeat(40));
  lines.push(`  Statistic            Value       Standard        Status`);
  lines.push(`  ${'─'.repeat(60)}`);

  const medStatus = cwMed >= 0.90 && cwMed <= 1.10 ? 'PASS' : 'FAIL';
  const codStatus = cwCod <= 20 ? 'PASS' : 'FAIL';
  const prdStatus = cwPrd >= 0.98 && cwPrd <= 1.03 ? 'PASS' : 'FAIL';

  lines.push(`  Median Ratio         ${padL(fmt3(cwMed), 11)} 0.900 – 1.100   ${medStatus}`);
  lines.push(`  COD                  ${padL(fmt1(cwCod), 11)} ≤ 20.0          ${codStatus}`);
  lines.push(`  PRD                  ${padL(fmt3(cwPrd), 11)} 0.980 – 1.030   ${prdStatus}`);
  lines.push('');

  // ── Neighborhood Table ────────────────────────────────────────────────────
  lines.push('III. NEIGHBORHOOD RATIO STUDY RESULTS');
  lines.push('─'.repeat(40));
  lines.push(`  ${padR('Nbhd', 10)}${padL('n', 5)}${padL('Med Ratio', 11)}${padL('COD', 8)}${padL('PRD', 8)}  Status`);
  lines.push(`  ${'─'.repeat(58)}`);

  const sorted = [...qualified].sort((a, b) =>
    Math.abs(b.stats.medianRatio - 1) - Math.abs(a.stats.medianRatio - 1)
  );

  for (const ns of sorted) {
    const status = iaaoPass(ns) ? 'pass' : 'FAIL';
    lines.push(
      `  ${padR(ns.neighborhoodCode, 10)}` +
      `${padL(String(ns.saleCount), 5)}` +
      `${padL(fmt3(ns.stats.medianRatio), 11)}` +
      `${padL(fmt1(ns.stats.cod), 8)}` +
      `${padL(fmt3(ns.stats.prd), 8)}  ${status}`
    );
  }
  lines.push('');

  // ── Critical Neighborhoods ────────────────────────────────────────────────
  if (critical.length > 0) {
    lines.push('IV. CRITICAL NEIGHBORHOODS — CORRECTIVE ACTION REQUIRED');
    lines.push('─'.repeat(40));
    for (const ns of critical.sort(
      (a, b) => Math.abs(b.stats.medianRatio - 1) - Math.abs(a.stats.medianRatio - 1)
    )) {
      const deviation = ns.stats.medianRatio - 1.0;
      const direction = deviation > 0 ? 'OVER-ASSESSED' : 'UNDER-ASSESSED';
      const adjustPct = (-deviation * 100).toFixed(1);
      lines.push(`  Neighborhood: ${ns.neighborhoodCode} — ${ns.neighborhoodName}`);
      lines.push(`    Median Ratio: ${fmt3(ns.stats.medianRatio)} (${direction} by ${Math.abs(parseFloat(adjustPct)).toFixed(1)}%)`);
      lines.push(`    COD: ${fmt1(ns.stats.cod)} | PRD: ${fmt3(ns.stats.prd)} | n: ${ns.saleCount}`);
      lines.push(`    Recommended adjustment: ${adjustPct}% ${parseFloat(adjustPct) > 0 ? 'increase' : 'decrease'} in assessed values`);
      lines.push('');
    }
  }

  // ── Spatial Analysis ──────────────────────────────────────────────────────
  lines.push('V. SPATIAL AUTOCORRELATION ANALYSIS');
  lines.push('─'.repeat(40));
  if (moransI) {
    lines.push(`  Global Moran's I: ${moransI.I.toFixed(3)} (${moransI.interpretation})`);
    if (moransI.warning) {
      lines.push(`  WARNING: Significant spatial clustering detected (I > 0.45).`);
      lines.push(`  Geographic bias may indicate systematic assessment inequity`);
      lines.push(`  across neighborhoods. LISA analysis recommended for root cause.`);
    } else if (moransI.I > 0) {
      lines.push(`  Moderate spatial clustering present. Monitor for geographic bias.`);
    } else {
      lines.push(`  No significant spatial autocorrelation detected.`);
      lines.push(`  Assessment ratios appear geographically random — favorable finding.`);
    }
  } else {
    lines.push('  Insufficient neighborhood data for spatial analysis (need ≥ 5).');
  }
  lines.push('');

  // ── EQI Component Detail ──────────────────────────────────────────────────
  if (eqi) {
    lines.push('VI. COUNTY EQUITY INDEX COMPONENTS');
    lines.push('─'.repeat(40));
    const c = eqi.components;
    lines.push(`  Component          Score    Weight   Points`);
    lines.push(`  ${'─'.repeat(50)}`);
    lines.push(`  Ratio accuracy     ${padL(fmtPct(c.ratio * 100), 8)} 25       ${padL((c.ratio * 25).toFixed(1), 6)}`);
    lines.push(`  Uniformity (COD)   ${padL(fmtPct(c.cod * 100), 8)} 20       ${padL((c.cod * 20).toFixed(1), 6)}`);
    lines.push(`  Vertical equity    ${padL(fmtPct(c.prd * 100), 8)} 15       ${padL((c.prd * 15).toFixed(1), 6)}`);
    lines.push(`  IAAO pass rate     ${padL(fmtPct(c.passRate * 100), 8)} 25       ${padL((c.passRate * 25).toFixed(1), 6)}`);
    lines.push(`  Spatial equity     ${padL(fmtPct(c.spatial * 100), 8)} 10       ${padL((c.spatial * 10).toFixed(1), 6)}`);
    lines.push(`  Data adequacy      ${padL(fmtPct(c.adequacy * 100), 8)} 5        ${padL((c.adequacy * 5).toFixed(1), 6)}`);
    lines.push(`  ${'─'.repeat(50)}`);
    lines.push(`  TOTAL EQI SCORE    ${padL('', 8)}          ${padL(String(eqi.score), 6)} / 100   Grade ${eqi.grade}`);
    lines.push('');
  }

  // ── Attestation ───────────────────────────────────────────────────────────
  lines.push('VII. ATTESTATION');
  lines.push('─'.repeat(40));
  lines.push(`I hereby certify that the ratio study data presented in this report`);
  lines.push(`reflects the ${taxYear} assessment level for ${county} County as required`);
  lines.push(`under WAC 458-53A and RCW 84.41.030.`);
  lines.push('');
  lines.push(`Assessor: ${assessorName}`);
  lines.push(`Date:     ___________________________`);
  lines.push(`Signature: __________________________`);
  lines.push('');
  lines.push('─'.repeat(72));
  lines.push(`DRAFT — Generated ${generatedDate} by TerraFusion GeoForge`);
  lines.push(`TerraFusion OS · ${county} County Assessment Office`);
  lines.push(`WAC 458-53A · RCW 84.41.030 · IAAO Standard on Ratio Studies`);

  return lines.join('\n');
}
