import type { NeighborhoodStat, SalePoint } from '../types/geoforge.types';
import type { LevyParitySummary } from './levyParity';
import type { EquityIndexResult } from './equityIndex';

function iaaoPass(ns: NeighborhoodStat): boolean {
  const { medianRatio, cod, prd } = ns.stats;
  return medianRatio >= 0.90 && medianRatio <= 1.10 && cod <= 20 && prd >= 0.98 && prd <= 1.03;
}

function csvRow(cells: (string | number | boolean | null | undefined)[]): string {
  return cells
    .map((c) => {
      const s = c == null ? '' : String(c);
      return s.includes(',') || s.includes('"') || s.includes('\n')
        ? `"${s.replace(/"/g, '""')}"`
        : s;
    })
    .join(',');
}

export function exportNeighborhoodStats(
  stats: NeighborhoodStat[],
  taxYear: number,
  county: string,
): void {
  const header = csvRow([
    'NeighborhoodCode', 'NeighborhoodName', 'TaxYear', 'SaleCount',
    'MedianRatio', 'MeanRatio', 'COD', 'PRD', 'PRB', 'VEI',
    'StdDev', 'Min', 'Max', 'Q1Ratio', 'Q5Ratio',
    'Q1_Q5_Spread', 'IAO_Pass', 'MedDevFromParity',
  ]);

  const rows = stats.map((ns) => {
    const { medianRatio, cod, prd, prb, vei, mean, stdDev, min, max, q1Ratio, q5Ratio } = ns.stats;
    const spread = q5Ratio > 0 && q1Ratio > 0 ? (q5Ratio / q1Ratio).toFixed(4) : '';
    return csvRow([
      ns.neighborhoodCode,
      ns.neighborhoodName,
      taxYear,
      ns.saleCount,
      medianRatio.toFixed(4),
      mean.toFixed(4),
      cod.toFixed(2),
      prd.toFixed(4),
      prb.toFixed(4),
      vei.toFixed(4),
      stdDev.toFixed(4),
      min.toFixed(4),
      max.toFixed(4),
      q1Ratio.toFixed(4),
      q5Ratio.toFixed(4),
      spread,
      iaaoPass(ns) ? 'TRUE' : 'FALSE',
      (medianRatio - 1.0).toFixed(4),
    ]);
  });

  const csv = [
    `# ${county} County · ${taxYear} Ratio Study · Generated by TerraFusion GeoForge`,
    `# WAC 458-53A · IAAO Standard on Ratio Studies`,
    header,
    ...rows,
  ].join('\n');

  downloadBlob(csv, `${county}_County_RatioStudy_${taxYear}.csv`, 'text/csv;charset=utf-8');
}

export function exportSalePoints(
  sales: SalePoint[],
  taxYear: number,
  county: string,
): void {
  const qualified = sales.filter((s) => !s.isOutlier && s.ratio > 0);

  const header = csvRow([
    'SaleId', 'ParcelId', 'NeighborhoodCode', 'SaleDate', 'SalePrice',
    'AssessedValue', 'Ratio', 'PropertyClass', 'IsOutlier', 'QualDecision',
    'Lat', 'Lng',
  ]);

  const rows = sales.map((s) =>
    csvRow([
      s.saleId, s.parcelId, s.neighborhoodCode, s.saleDate,
      s.salePrice, s.assessedValue, s.ratio.toFixed(4),
      s.propertyClass, s.isOutlier ? 'TRUE' : 'FALSE',
      s.qualificationDecision, s.lat.toFixed(6), s.lng.toFixed(6),
    ])
  );

  const csv = [
    `# ${county} County · ${taxYear} Qualified Sales (${qualified.length} of ${sales.length})`,
    header,
    ...rows,
  ].join('\n');

  downloadBlob(csv, `${county}_County_Sales_${taxYear}.csv`, 'text/csv;charset=utf-8');
}

export function exportLevyParity(
  summary: LevyParitySummary,
  taxYear: number,
  county: string,
): void {
  const header = csvRow([
    'NeighborhoodCode', 'NeighborhoodName', 'MedianRatio', 'ParcelCount',
    'TotalAV', 'TotalTVEst', 'AVShare%', 'TVShare%',
    'BurdenShift%', 'BurdenShiftDollars',
  ]);

  const rows = summary.rows.map((r) =>
    csvRow([
      r.neighborhoodCode, r.neighborhoodName,
      r.medianRatio.toFixed(4), r.parcelCount,
      r.totalAV.toFixed(0), r.totalTVEst.toFixed(0),
      (r.avShare * 100).toFixed(4), (r.tvShare * 100).toFixed(4),
      r.burdenShiftPct.toFixed(4),
      r.burdenShiftDollars !== null ? r.burdenShiftDollars.toFixed(0) : '',
    ])
  );

  const csv = [
    `# ${county} County · ${taxYear} Levy Parity Analysis · TerraFusion GeoForge`,
    `# Total County AV: ${summary.totalAV.toFixed(0)} | Total Est. TV: ${summary.totalTVEst.toFixed(0)}`,
    header,
    ...rows,
  ].join('\n');

  downloadBlob(csv, `${county}_County_LevyParity_${taxYear}.csv`, 'text/csv;charset=utf-8');
}

export function exportEQIReport(
  eqi: EquityIndexResult,
  stats: NeighborhoodStat[],
  taxYear: number,
  county: string,
): void {
  const rows = [
    ['Report', `${county} County ${taxYear} County Equity Index`],
    ['EQI Score', String(eqi.score)],
    ['Grade', eqi.grade],
    [''],
    ['Component', 'Score (0-1)', 'Weight', 'Points'],
    ['Ratio accuracy', eqi.components.ratio.toFixed(4), '25', (eqi.components.ratio * 25).toFixed(2)],
    ['COD uniformity', eqi.components.cod.toFixed(4), '20', (eqi.components.cod * 20).toFixed(2)],
    ['PRD vertical equity', eqi.components.prd.toFixed(4), '15', (eqi.components.prd * 15).toFixed(2)],
    ['IAAO pass rate', eqi.components.passRate.toFixed(4), '25', (eqi.components.passRate * 25).toFixed(2)],
    ['Spatial equity', eqi.components.spatial.toFixed(4), '10', (eqi.components.spatial * 10).toFixed(2)],
    ['Data adequacy', eqi.components.adequacy.toFixed(4), '5', (eqi.components.adequacy * 5).toFixed(2)],
    [''],
    ['Neighborhoods analyzed', String(stats.length)],
    ['Neighborhoods IAAO compliant', String(stats.filter(iaaoPass).length)],
  ];

  const csv = rows.map((r) => csvRow(r)).join('\n');
  downloadBlob(csv, `${county}_County_EQI_${taxYear}.csv`, 'text/csv;charset=utf-8');
}

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const bom = '\uFEFF'; // UTF-8 BOM for Excel compatibility
  const blob = new Blob([bom + content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
