#!/usr/bin/env python3
"""
Atlas Summary Script
Generates markdown summary of Atlas contents
"""

import json
from pathlib import Path
from collections import defaultdict

ATLAS_ROOT = Path(__file__).parent.parent
REGISTRIES_DIR = ATLAS_ROOT / "registries"

def generate_summary():
    """Generate Atlas summary"""
    
    print("# 🗺️ TerraFusion Atlas Summary\n")
    print("**Comprehensive inventory of the TerraFusion ecosystem**\n")
    
    # Overall stats
    total_items = 0
    registry_stats = {}
    
    for registry_file in sorted(REGISTRIES_DIR.glob("*.json")):
        with open(registry_file) as f:
            data = json.load(f)
            count = len(data.get('items', []))
            total_items += count
            registry_stats[registry_file.stem] = {
                'count': count,
                'items': data.get('items', [])
            }
    
    print(f"**Total Items:** {total_items}\n")
    
    # Registry breakdown
    print("## 📊 Registry Breakdown\n")
    print("| Registry | Count | Status |")
    print("|----------|-------|--------|")
    
    for name, stats in sorted(registry_stats.items()):
        count = stats['count']
        status = "✅" if count > 0 else "⚠️ Empty"
        print(f"| {name.title()} | {count} | {status} |")
    
    print()
    
    # By owner
    print("## 👥 By Owner\n")
    owners = defaultdict(int)
    for name, stats in registry_stats.items():
        for item in stats['items']:
            owner = item.get('owner', 'unknown')
            owners[owner] += 1
    
    print("| Owner | Items |")
    print("|-------|-------|")
    for owner, count in sorted(owners.items(), key=lambda x: -x[1]):
        print(f"| {owner} | {count} |")
    
    print()
    
    # By lifecycle
    print("## 🔄 By Lifecycle\n")
    lifecycles = defaultdict(int)
    for name, stats in registry_stats.items():
        for item in stats['items']:
            lifecycle = item.get('lifecycle', 'unknown')
            lifecycles[lifecycle] += 1
    
    print("| Lifecycle | Count |")
    print("|-----------|-------|")
    for lifecycle, count in sorted(lifecycles.items(), key=lambda x: -x[1]):
        emoji = {'active': '✅', 'experimental': '🧪', 'deprecated': '⚠️', 'archived': '📦'}.get(lifecycle, '❓')
        print(f"| {emoji} {lifecycle.title()} | {count} |")
    
    print()
    
    # Top tags
    print("## 🏷️ Top Tags\n")
    tags = defaultdict(int)
    for name, stats in registry_stats.items():
        for item in stats['items']:
            for tag in item.get('tags', []):
                tags[tag] += 1
    
    print("| Tag | Usage |")
    print("|-----|-------|")
    for tag, count in sorted(tags.items(), key=lambda x: -x[1])[:15]:
        print(f"| `{tag}` | {count} |")
    
    print()
    
    # Health check
    print("## 🏥 Health Check\n")
    
    missing_owners = sum(1 for stats in registry_stats.values() 
                        for item in stats['items'] 
                        if not item.get('owner'))
    missing_tags = sum(1 for stats in registry_stats.values() 
                      for item in stats['items'] 
                      if not item.get('tags'))
    missing_paths = sum(1 for stats in registry_stats.values() 
                       for item in stats['items'] 
                       if not item.get('source_path'))
    
    print(f"- {'✅' if missing_owners == 0 else '❌'} **Ownership:** {total_items - missing_owners}/{total_items} items have owners")
    print(f"- {'✅' if missing_tags == 0 else '⚠️'} **Tagging:** {total_items - missing_tags}/{total_items} items have tags")
    print(f"- {'✅' if missing_paths == 0 else '⚠️'} **Paths:** {total_items - missing_paths}/{total_items} items have source paths")
    
    print()
    
    # Recent activity (if we have dates)
    print("---")
    print("\n*Generated by TerraFusion Atlas*")

if __name__ == '__main__':
    generate_summary()
