create view perm_crop_acres as

SELECT  id.prop_id,


max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	1	 '	,
max(case when ia.imprv_det_type_cd=	'V16-Merlot'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V16-Merlot	1	 '	,
max(case when ia.imprv_det_type_cd=	'V24-Cabern'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V24-Cabern	1	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	1	 '	,
max(case when ia.imprv_det_type_cd=	'V04-Hops  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V04-Hops  	1	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	1	 '	,
max(case when ia.imprv_det_type_cd=	'V01-Wine G'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V01-Wine G	1	 '	,
max(case when ia.imprv_det_type_cd=	'V02-Juice '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V02-Juice 	1	 '	,
max(case when ia.imprv_det_type_cd=	'V07-Pinot '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V07-Pinot 	1	 '	,
max(case when ia.imprv_det_type_cd=	'V08-Sauvig'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V08-Sauvig	1	 '	,
max(case when ia.imprv_det_type_cd=	'V13-Riesli'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V13-Riesli	1	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	1	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	1	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	1	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	1	 '	,
max(case when ia.imprv_det_type_cd=	'V31-Bluebe'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V31-Bluebe	1	 '	,
max(case when ia.imprv_det_type_cd=	'O12-Braebu'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O12-Braebu	1	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	1	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	1	 '	,
max(case when ia.imprv_det_type_cd=	'V23-Viogni'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V23-Viogni	1	 '	,
max(case when ia.imprv_det_type_cd=	'V25-Sangio'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V25-Sangio	1	 '	,
max(case when ia.imprv_det_type_cd=	'O46-Gala G'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O46-Gala G	1	 '	,
max(case when ia.imprv_det_type_cd=	'V11-Gewurz'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V11-Gewurz	1	 '	,
max(case when ia.imprv_det_type_cd=	'O18-Scarle'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O18-Scarle	1	 '	,
max(case when ia.imprv_det_type_cd=	'O24-Granny'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O24-Granny	1	 '	,
max(case when ia.imprv_det_type_cd=	'O89-Honeyc'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O89-Honeyc	1	 '	,
max(case when ia.imprv_det_type_cd=	'O03-Pears '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O03-Pears 	1	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	1	 '	,
max(case when ia.imprv_det_type_cd=	'O35-Top Re'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O35-Top Re	1	 '	,
max(case when ia.imprv_det_type_cd=	'V18-Pinot '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V18-Pinot 	1	 '	,
max(case when ia.imprv_det_type_cd=	'AG-Cannabs'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	AG-Cannabs	1	 '	,
max(case when ia.imprv_det_type_cd=	'V22-Niagar'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V22-Niagar	1	 '	,
max(case when ia.imprv_det_type_cd=	'V14-Other '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V14-Other 	1	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	1	 '	,
max(case when ia.imprv_det_type_cd=	'O53-Gala R'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O53-Gala R	1	 '	,
max(case when ia.imprv_det_type_cd=	'O61-Fuji S'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O61-Fuji S	1	 '	,
max(case when ia.imprv_det_type_cd=	'O66-Braebu'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O66-Braebu	1	 '	,
max(case when ia.imprv_det_type_cd=	'O22-Golden'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O22-Golden	1	 '	,
max(case when ia.imprv_det_type_cd=	'V26-Zinfan'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V26-Zinfan	1	 '	,
max(case when ia.imprv_det_type_cd=	'O40-Gala B'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O40-Gala B	1	 '	,
max(case when ia.imprv_det_type_cd=	'O49-Gala P'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O49-Gala P	1	 '	,
max(case when ia.imprv_det_type_cd=	'O65-Braebu'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O65-Braebu	1	 '	,
max(case when ia.imprv_det_type_cd=	'V12-Muscat'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V12-Muscat	1	 '	,
max(case when ia.imprv_det_type_cd=	'V27-Grenac'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V27-Grenac	1	 '	,
max(case when ia.imprv_det_type_cd=	'O39-Pink L'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O39-Pink L	1	 '	,
max(case when ia.imprv_det_type_cd=	'O42-Gala B'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O42-Gala B	1	 '	,
max(case when ia.imprv_det_type_cd=	'V28-Malbec'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V28-Malbec	1	 '	,
max(case when ia.imprv_det_type_cd=	'V09-Semill'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V09-Semill	1	 '	,
max(case when ia.imprv_det_type_cd=	'V10-Chenin'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V10-Chenin	1	 '	,
max(case when ia.imprv_det_type_cd=	'O36-Red De'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O36-Red De	1	 '	,
max(case when ia.imprv_det_type_cd=	'V03-Aspara'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V03-Aspara	1	 '	,
max(case when ia.imprv_det_type_cd=	'C02-Rainie'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	C02-Rainie	1	 '	,
max(case when ia.imprv_det_type_cd=	'O08-Prunes'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O08-Prunes	1	 '	,
max(case when ia.imprv_det_type_cd=	'O14-Red Ch'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O14-Red Ch	1	 '	,
max(case when ia.imprv_det_type_cd=	'O17-Oregon'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O17-Oregon	1	 '	,
max(case when ia.imprv_det_type_cd=	'O47-Gala G'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O47-Gala G	1	 '	,
max(case when ia.imprv_det_type_cd=	'O87-Red Va'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O87-Red Va	1	 '	,
max(case when ia.imprv_det_type_cd=	'O09-Nuts  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O09-Nuts  	1	 '	,
max(case when ia.imprv_det_type_cd=	'O06-Aprico'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O06-Aprico	1	 '	,
max(case when ia.imprv_det_type_cd=	'O07-Plums '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O07-Plums 	1	 '	,
max(case when ia.imprv_det_type_cd=	'C01-Bing  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	C01-Bing  	1	 '	,
max(case when ia.imprv_det_type_cd=	'O20-Cameo '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O20-Cameo 	1	 '	,
max(case when ia.imprv_det_type_cd=	'O25-Jonago'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O25-Jonago	1	 '	,
max(case when ia.imprv_det_type_cd=	'O34-Bisbee'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O34-Bisbee	1	 '	,
max(case when ia.imprv_det_type_cd=	'O32-Rome  '	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O32-Rome  	1	 '	,
max(case when ia.imprv_det_type_cd=	'O27-Washin'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O27-Washin	1	 '	,
max(case when ia.imprv_det_type_cd=	'O31-Winesa'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O31-Winesa	1	 '	,
max(case when ia.imprv_det_type_cd=	'V19-Limber'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V19-Limber	1	 '	,
max(case when ia.imprv_det_type_cd=	'O54-Gala U'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O54-Gala U	1	 '	,
max(case when ia.imprv_det_type_cd=	'O21-Spur R'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O21-Spur R	1	 '	,
max(case when ia.imprv_det_type_cd=	'O84-Golden'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O84-Golden	1	 '	,
max(case when ia.imprv_det_type_cd=	'O58-Fuji R'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O58-Fuji R	1	 '	,
max(case when ia.imprv_det_type_cd=	'O70-Pacifi'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O70-Pacifi	1	 '	,
max(case when ia.imprv_det_type_cd=	'O44-Gala C'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O44-Gala C	1	 '	,
max(case when ia.imprv_det_type_cd=	'C04-Chelan'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	C04-Chelan	1	 '	,
max(case when ia.imprv_det_type_cd=	'O59-Fuji R'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O59-Fuji R	1	 '	,
max(case when ia.imprv_det_type_cd=	'O05-Nectar'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O05-Nectar	1	 '	,
max(case when ia.imprv_det_type_cd=	'O41-Gala B'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O41-Gala B	1	 '	,
max(case when ia.imprv_det_type_cd=	'O45-Gala G'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O45-Gala G	1	 '	,
max(case when ia.imprv_det_type_cd=	'O48-Gala I'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O48-Gala I	1	 '	,
max(case when ia.imprv_det_type_cd=	'V29-Nebbio'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V29-Nebbio	1	 '	,
max(case when ia.imprv_det_type_cd=	'O56-Fuji N'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O56-Fuji N	1	 '	,
max(case when ia.imprv_det_type_cd=	'O57-Fuji T'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O57-Fuji T	1	 '	,
max(case when ia.imprv_det_type_cd=	'O50-Gala S'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O50-Gala S	1	 '	,
max(case when ia.imprv_det_type_cd=	'O83-Ginger'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	O83-Ginger	1	 '	,
max(case when ia.imprv_det_type_cd=	'V32-Raspbe'	and ia.order_id =	1	then	ia.imprv_pc_acres	else	null	end) as		 '	V32-Raspbe	1	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	2	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	2	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	2	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	2	 '	,
max(case when ia.imprv_det_type_cd=	'O24-Granny'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O24-Granny	2	 '	,
max(case when ia.imprv_det_type_cd=	'O40-Gala B'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O40-Gala B	2	 '	,
max(case when ia.imprv_det_type_cd=	'O46-Gala G'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O46-Gala G	2	 '	,
max(case when ia.imprv_det_type_cd=	'O89-Honeyc'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O89-Honeyc	2	 '	,
max(case when ia.imprv_det_type_cd=	'V01-Wine G'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V01-Wine G	2	 '	,
max(case when ia.imprv_det_type_cd=	'V04-Hops  '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V04-Hops  	2	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	2	 '	,
max(case when ia.imprv_det_type_cd=	'V08-Sauvig'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V08-Sauvig	2	 '	,
max(case when ia.imprv_det_type_cd=	'V11-Gewurz'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V11-Gewurz	2	 '	,
max(case when ia.imprv_det_type_cd=	'V13-Riesli'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V13-Riesli	2	 '	,
max(case when ia.imprv_det_type_cd=	'V14-Other '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V14-Other 	2	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	2	 '	,
max(case when ia.imprv_det_type_cd=	'V16-Merlot'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V16-Merlot	2	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	2	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	2	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	2	 '	,
max(case when ia.imprv_det_type_cd=	'V22-Niagar'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V22-Niagar	2	 '	,
max(case when ia.imprv_det_type_cd=	'V23-Viogni'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V23-Viogni	2	 '	,
max(case when ia.imprv_det_type_cd=	'V24-Cabern'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V24-Cabern	2	 '	,
max(case when ia.imprv_det_type_cd=	'V25-Sangio'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V25-Sangio	2	 '	,
max(case when ia.imprv_det_type_cd=	'V26-Zinfan'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V26-Zinfan	2	 '	,
max(case when ia.imprv_det_type_cd=	'V31-Bluebe'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V31-Bluebe	2	 '	,
max(case when ia.imprv_det_type_cd=	'V09-Semill'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V09-Semill	2	 '	,
max(case when ia.imprv_det_type_cd=	'V10-Chenin'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V10-Chenin	2	 '	,
max(case when ia.imprv_det_type_cd=	'O03-Pears '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O03-Pears 	2	 '	,
max(case when ia.imprv_det_type_cd=	'C02-Rainie'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	C02-Rainie	2	 '	,
max(case when ia.imprv_det_type_cd=	'V07-Pinot '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V07-Pinot 	2	 '	,
max(case when ia.imprv_det_type_cd=	'O14-Red Ch'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O14-Red Ch	2	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	2	 '	,
max(case when ia.imprv_det_type_cd=	'O36-Red De'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O36-Red De	2	 '	,
max(case when ia.imprv_det_type_cd=	'O87-Red Va'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O87-Red Va	2	 '	,
max(case when ia.imprv_det_type_cd=	'O39-Pink L'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O39-Pink L	2	 '	,
max(case when ia.imprv_det_type_cd=	'O12-Braebu'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O12-Braebu	2	 '	,
max(case when ia.imprv_det_type_cd=	'O32-Rome  '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O32-Rome  	2	 '	,
max(case when ia.imprv_det_type_cd=	'O54-Gala U'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O54-Gala U	2	 '	,
max(case when ia.imprv_det_type_cd=	'O58-Fuji R'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O58-Fuji R	2	 '	,
max(case when ia.imprv_det_type_cd=	'O22-Golden'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O22-Golden	2	 '	,
max(case when ia.imprv_det_type_cd=	'V18-Pinot '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V18-Pinot 	2	 '	,
max(case when ia.imprv_det_type_cd=	'C04-Chelan'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	C04-Chelan	2	 '	,
max(case when ia.imprv_det_type_cd=	'O18-Scarle'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O18-Scarle	2	 '	,
max(case when ia.imprv_det_type_cd=	'O05-Nectar'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O05-Nectar	2	 '	,
max(case when ia.imprv_det_type_cd=	'O49-Gala P'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O49-Gala P	2	 '	,
max(case when ia.imprv_det_type_cd=	'O42-Gala B'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O42-Gala B	2	 '	,
max(case when ia.imprv_det_type_cd=	'O41-Gala B'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O41-Gala B	2	 '	,
max(case when ia.imprv_det_type_cd=	'O45-Gala G'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O45-Gala G	2	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	2	 '	,
max(case when ia.imprv_det_type_cd=	'O65-Braebu'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O65-Braebu	2	 '	,
max(case when ia.imprv_det_type_cd=	'V28-Malbec'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V28-Malbec	2	 '	,
max(case when ia.imprv_det_type_cd=	'O07-Plums '	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O07-Plums 	2	 '	,
max(case when ia.imprv_det_type_cd=	'O44-Gala C'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O44-Gala C	2	 '	,
max(case when ia.imprv_det_type_cd=	'O48-Gala I'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O48-Gala I	2	 '	,
max(case when ia.imprv_det_type_cd=	'O53-Gala R'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O53-Gala R	2	 '	,
max(case when ia.imprv_det_type_cd=	'O59-Fuji R'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O59-Fuji R	2	 '	,
max(case when ia.imprv_det_type_cd=	'AG-Cannabs'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	AG-Cannabs	2	 '	,
max(case when ia.imprv_det_type_cd=	'O06-Aprico'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	O06-Aprico	2	 '	,
max(case when ia.imprv_det_type_cd=	'V19-Limber'	and ia.order_id =	2	then	ia.imprv_pc_acres	else	null	end) as		 '	V19-Limber	2	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	3	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	3	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	3	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	3	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	3	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	3	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	3	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	3	 '	,
max(case when ia.imprv_det_type_cd=	'V24-Cabern'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V24-Cabern	3	 '	,
max(case when ia.imprv_det_type_cd=	'V01-Wine G'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V01-Wine G	3	 '	,
max(case when ia.imprv_det_type_cd=	'V16-Merlot'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V16-Merlot	3	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	3	 '	,
max(case when ia.imprv_det_type_cd=	'V22-Niagar'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V22-Niagar	3	 '	,
max(case when ia.imprv_det_type_cd=	'V08-Sauvig'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V08-Sauvig	3	 '	,
max(case when ia.imprv_det_type_cd=	'O03-Pears '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O03-Pears 	3	 '	,
max(case when ia.imprv_det_type_cd=	'V31-Bluebe'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V31-Bluebe	3	 '	,
max(case when ia.imprv_det_type_cd=	'O24-Granny'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O24-Granny	3	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	3	 '	,
max(case when ia.imprv_det_type_cd=	'O36-Red De'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O36-Red De	3	 '	,
max(case when ia.imprv_det_type_cd=	'O14-Red Ch'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O14-Red Ch	3	 '	,
max(case when ia.imprv_det_type_cd=	'O58-Fuji R'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O58-Fuji R	3	 '	,
max(case when ia.imprv_det_type_cd=	'V07-Pinot '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V07-Pinot 	3	 '	,
max(case when ia.imprv_det_type_cd=	'V04-Hops  '	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V04-Hops  	3	 '	,
max(case when ia.imprv_det_type_cd=	'V13-Riesli'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V13-Riesli	3	 '	,
max(case when ia.imprv_det_type_cd=	'O39-Pink L'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O39-Pink L	3	 '	,
max(case when ia.imprv_det_type_cd=	'O89-Honeyc'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O89-Honeyc	3	 '	,
max(case when ia.imprv_det_type_cd=	'O05-Nectar'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O05-Nectar	3	 '	,
max(case when ia.imprv_det_type_cd=	'O49-Gala P'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O49-Gala P	3	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	3	 '	,
max(case when ia.imprv_det_type_cd=	'O65-Braebu'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O65-Braebu	3	 '	,
max(case when ia.imprv_det_type_cd=	'O44-Gala C'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O44-Gala C	3	 '	,
max(case when ia.imprv_det_type_cd=	'O59-Fuji R'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	O59-Fuji R	3	 '	,
max(case when ia.imprv_det_type_cd=	'V19-Limber'	and ia.order_id =	3	then	ia.imprv_pc_acres	else	null	end) as		 '	V19-Limber	3	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	4	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	4	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	4	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	4	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	4	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	4	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	4	 '	,
max(case when ia.imprv_det_type_cd=	'V01-Wine G'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V01-Wine G	4	 '	,
max(case when ia.imprv_det_type_cd=	'V16-Merlot'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V16-Merlot	4	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	4	 '	,
max(case when ia.imprv_det_type_cd=	'V08-Sauvig'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V08-Sauvig	4	 '	,
max(case when ia.imprv_det_type_cd=	'O14-Red Ch'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O14-Red Ch	4	 '	,
max(case when ia.imprv_det_type_cd=	'O24-Granny'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O24-Granny	4	 '	,
max(case when ia.imprv_det_type_cd=	'O03-Pears '	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O03-Pears 	4	 '	,
max(case when ia.imprv_det_type_cd=	'O58-Fuji R'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O58-Fuji R	4	 '	,
max(case when ia.imprv_det_type_cd=	'V24-Cabern'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V24-Cabern	4	 '	,
max(case when ia.imprv_det_type_cd=	'O39-Pink L'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O39-Pink L	4	 '	,
max(case when ia.imprv_det_type_cd=	'O89-Honeyc'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O89-Honeyc	4	 '	,
max(case when ia.imprv_det_type_cd=	'V13-Riesli'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V13-Riesli	4	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	4	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	4	 '	,
max(case when ia.imprv_det_type_cd=	'O65-Braebu'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O65-Braebu	4	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	4	 '	,
max(case when ia.imprv_det_type_cd=	'O59-Fuji R'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O59-Fuji R	4	 '	,
max(case when ia.imprv_det_type_cd=	'O05-Nectar'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	O05-Nectar	4	 '	,
max(case when ia.imprv_det_type_cd=	'V19-Limber'	and ia.order_id =	4	then	ia.imprv_pc_acres	else	null	end) as		 '	V19-Limber	4	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	5	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	5	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	5	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	5	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	5	 '	,
max(case when ia.imprv_det_type_cd=	'V01-Wine G'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V01-Wine G	5	 '	,
max(case when ia.imprv_det_type_cd=	'O24-Granny'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O24-Granny	5	 '	,
max(case when ia.imprv_det_type_cd=	'V16-Merlot'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V16-Merlot	5	 '	,
max(case when ia.imprv_det_type_cd=	'O58-Fuji R'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O58-Fuji R	5	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	5	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	5	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	5	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	5	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	5	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	5	 '	,
max(case when ia.imprv_det_type_cd=	'O65-Braebu'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O65-Braebu	5	 '	,
max(case when ia.imprv_det_type_cd=	'O05-Nectar'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	O05-Nectar	5	 '	,
max(case when ia.imprv_det_type_cd=	'V08-Sauvig'	and ia.order_id =	5	then	ia.imprv_pc_acres	else	null	end) as		 '	V08-Sauvig	5	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	6	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	6	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	6	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	6	 '	,
max(case when ia.imprv_det_type_cd=	'V21-Concor'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	V21-Concor	6	 '	,
max(case when ia.imprv_det_type_cd=	'O10-Gala  '	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O10-Gala  	6	 '	,
max(case when ia.imprv_det_type_cd=	'V20-Other '	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	V20-Other 	6	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	6	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	6	 '	,
max(case when ia.imprv_det_type_cd=	'O62-Fuji R'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	O62-Fuji R	6	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	6	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	6	 '	,
max(case when ia.imprv_det_type_cd=	'O01-Apples'	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	O01-Apples	7	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	7	 '	,
max(case when ia.imprv_det_type_cd=	'O11-Fuji  '	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	O11-Fuji  	7	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	7	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	7	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	7	 '	,
max(case when ia.imprv_det_type_cd=	'V06-Chardo'	and ia.order_id =	7	then	ia.imprv_pc_acres	else	null	end) as		 '	V06-Chardo	7	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	8	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	8	 '	,
max(case when ia.imprv_det_type_cd=	'V17-Syrah '	and ia.order_id =	8	then	ia.imprv_pc_acres	else	null	end) as		 '	V17-Syrah 	8	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	8	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	8	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	8	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	8	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	9	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	9	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	9	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	9	 '	,
max(case when ia.imprv_det_type_cd=	'V15-Cabern'	and ia.order_id =	9	then	ia.imprv_pc_acres	else	null	end) as		 '	V15-Cabern	9	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	10	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	10	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	10	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	10	 '	,
max(case when ia.imprv_det_type_cd=	'O04-Peache'	and ia.order_id =	11	then	ia.imprv_pc_acres	else	null	end) as		 '	O04-Peache	11	 '	,
max(case when ia.imprv_det_type_cd=	'O02-Cherri'	and ia.order_id =	11	then	ia.imprv_pc_acres	else	null	end) as		 '	O02-Cherri	11	 '	

 

 FROM           pacs_oltp.dbo.imprv_detail  id 
  
  
  INNER JOIN
                         pacs_oltp.dbo.imprv ON id.prop_val_yr = imprv.prop_val_yr AND id.sup_num = imprv.sup_num AND id.sale_id = imprv.sale_id AND id.prop_id = imprv.prop_id AND 
                         id.imprv_id = imprv.imprv_id
						 left join 
						 pacs_oltp.dbo.property_val pv on pv.prop_id=id.prop_id and pv.prop_val_yr=id.prop_val_yr and pv.sup_num=id.sup_num 

  inner join 
(select [Parcel_ID],ROW_NUMBER() over (partition by prop_id ORDER BY [Shape_Area] DESC) AS order_id,[Prop_ID],Geometry,[Geometry].STCentroid().STX as XCoord,
[Geometry].STCentroid().STY as YCoord ,[Shape],[CENTROID_X] as x ,[CENTROID_Y] as y

FROM 
[Benton_spatial_data].[dbo].[spatial_parcel])as sp on id.prop_id=sp.prop_id
inner join
(
SELECT distinct  id.prop_id,
ROW_NUMBER() over (partition by id.prop_id, id.imprv_det_type_cd ORDER BY ID.imprv_det_meth_cd desc)AS order_id, 
ID.imprv_det_meth_cd, id.imprv_det_type_cd,
Sum(case when   id.imprv_det_type_cd IS not null	
	then	( permanent_crop_acres  )	else	null	end) as	imprv_pc_acres 
	 
	
 FROM           pacs_oltp.dbo.imprv_detail  id 
  inner join
                         pacs_oltp.dbo.imprv ON id.prop_val_yr = imprv.prop_val_yr AND id.sup_num = imprv.sup_num AND id.sale_id = imprv.sale_id AND id.prop_id = imprv.prop_id AND 
                         id.imprv_id = imprv.imprv_id
						 left join 
						 pacs_oltp.dbo.property_val pv on pv.prop_id=id.prop_id and pv.prop_val_yr=id.prop_val_yr and pv.sup_num=id.sup_num 

where 
id.prop_val_yr=(select appr_yr from pacs_oltp.dbo.pacs_system)
and id.sale_id=0
and imprv.imprv_type_cd='permc'
and id.imprv_det_meth_cd not like 'irr'
and id.imprv_det_meth_cd not like 'trl'
--and id.prop_id=26521
--and imprv_det_type_cd like'AG-HAYSTOR '
--and imprv_det_type_cd like '%V16-Merlot'
and permanent_crop_acres is not null 
--and id.prop_id=21153

group by 
id.prop_id,id.imprv_det_id,id.imprv_det_type_cd,permanent_crop_acres,ID.imprv_det_meth_cd



) as ia on ia.prop_id=id.prop_id

group by id.prop_id

GO

