CREATE TABLE [dbo].[_backup_levy_cert_hl_limit_save_20230108] (
    [levy_cert_run_id]                             INT              NOT NULL,
    [year]                                         NUMERIC (4)      NOT NULL,
    [tax_district_id]                              INT              NOT NULL,
    [levy_cd]                                      VARCHAR (10)     NOT NULL,
    [status]                                       BIT              NOT NULL,
    [limit_factor]                                 NUMERIC (13, 10) NULL,
    [calc_method]                                  CHAR (10)        NULL,
    [calc_method_years]                            INT              NULL,
    [calc_method_levy_year]                        NUMERIC (4)      NULL,
    [prior_year_levy_rate]                         NUMERIC (13, 10) NULL,
    [lid_lift_levy]                                NUMERIC (14, 2)  NULL,
    [compare_budget]                               BIT              NOT NULL,
    [shift_to_levy_cd]                             VARCHAR (10)     NULL,
    [highest_lawful_levy]                          NUMERIC (14, 2)  NULL,
    [banking_capacity]                             NUMERIC (14, 2)  NULL,
    [use_refunded_amount]                          BIT              NOT NULL,
    [refunded_amount]                              NUMERIC (14, 2)  NULL,
    [use_recovered_amount]                         BIT              NOT NULL,
    [recovered_amount]                             NUMERIC (14, 2)  NULL,
    [use_prior_yr_corrections]                     BIT              NOT NULL,
    [corrections_year]                             NUMERIC (4)      NULL,
    [corrections_amount]                           NUMERIC (14, 2)  NULL,
    [calculated_levy]                              NUMERIC (14, 2)  NULL,
    [highest_lawful_levy_rate]                     NUMERIC (13, 10) NULL,
    [calc_method_levy_amount]                      NUMERIC (14, 2)  NULL,
    [lid_lift]                                     BIT              NOT NULL,
    [shift_to_tax_district_id]                     INT              NULL,
    [prior_year_levy_rate_override]                BIT              NULL,
    [prior_year_levy]                              NUMERIC (16, 2)  NULL,
    [prior_year_levy_override]                     BIT              NOT NULL,
    [levy_calc_limit_factor]                       NUMERIC (13, 10) NULL,
    [shift_diversion_flag]                         BIT              NOT NULL,
    [shift_diversion_amount]                       NUMERIC (14, 2)  NOT NULL,
    [shift_diversion_reason]                       VARCHAR (30)     NULL,
    [prior_levy_calc_limit_factor]                 NUMERIC (13, 9)  NULL,
    [prior_levy_calc_limit_factor_override]        BIT              NULL,
    [limit_amount_requested]                       NUMERIC (14, 2)  NULL,
    [senior_calculated_levy]                       NUMERIC (14, 2)  NULL,
    [senior_highest_lawful_levy_rate]              NUMERIC (13, 10) NULL,
    [prior_year_tif_levy_amount]                   NUMERIC (14, 2)  NULL,
    [tif_levy_amount]                              NUMERIC (14, 2)  NULL,
    [nolift_calc_method_levy_year]                 NUMERIC (4)      NULL,
    [nolift_calc_method_levy_amount]               NUMERIC (14, 2)  NULL,
    [senior_tif_levy_amount]                       NUMERIC (14, 2)  NULL,
    [non_senior_tif_levy_amount]                   NUMERIC (14, 2)  NULL,
    [nolift_tif_levy_amount]                       NUMERIC (14, 2)  NULL,
    [senior_prior_year_tif_levy_amount]            NUMERIC (14, 2)  NULL,
    [non_senior_prior_year_tif_levy_amount]        NUMERIC (14, 2)  NULL,
    [nolift_prior_year_tif_levy_amount]            NUMERIC (14, 2)  NULL,
    [senior_levy_calc_limit_factor]                NUMERIC (13, 10) NULL,
    [senior_prior_levy_calc_limit_factor]          NUMERIC (13, 9)  NULL,
    [senior_prior_levy_calc_limit_factor_override] BIT              NOT NULL,
    [senior_prior_year_levy_rate]                  NUMERIC (13, 10) NULL,
    [senior_prior_year_levy_rate_override]         BIT              NOT NULL,
    [senior_prior_year_levy]                       NUMERIC (16, 2)  NULL,
    [senior_prior_year_levy_override]              BIT              NOT NULL,
    [senior_highest_lawful_levy]                   NUMERIC (14, 2)  NULL,
    [senior_limit_factor]                          NUMERIC (13, 10) NULL,
    [limit_factor_override]                        BIT              NOT NULL,
    [senior_limit_factor_override]                 BIT              NOT NULL,
    [nolift_prior_year_levy_rate]                  NUMERIC (13, 10) NULL,
    [nolift_prior_year_levy]                       NUMERIC (16, 2)  NULL,
    [nolift_highest_lawful_levy]                   NUMERIC (14, 2)  NULL,
    [nolift_calculated_levy]                       NUMERIC (14, 2)  NULL,
    [nolift_highest_lawful_levy_rate]              NUMERIC (13, 10) NULL
);


GO

