CREATE TABLE [dbo].[installment_agreement_bill] (
    [bill_id]                INT             NOT NULL,
    [sup_tax_yr]             NUMERIC (4)     NOT NULL,
    [sup_num]                INT             NOT NULL,
    [entity_id]              INT             NOT NULL,
    [prop_id]                INT             NOT NULL,
    [owner_id]               INT             NOT NULL,
    [adjustment_code]        VARCHAR (10)    NULL,
    [adj_effective_dt]       DATETIME        NULL,
    [adj_expiration_dt]      DATETIME        NULL,
    [adj_comment]            VARCHAR (500)   NULL,
    [rollback_id]            INT             NULL,
    [coll_status_cd]         CHAR (5)        NULL,
    [bill_type]              CHAR (5)        NULL,
    [effective_due_dt]       DATETIME        NULL,
    [bill_m_n_o]             NUMERIC (14, 2) NULL,
    [bill_i_n_s]             NUMERIC (14, 2) NULL,
    [bill_prot_i_n_s]        NUMERIC (14, 2) NULL,
    [bill_late_ag_penalty]   NUMERIC (14, 2) NULL,
    [bill_m_n_o_pd]          NUMERIC (14, 2) NULL,
    [bill_i_n_s_pd]          NUMERIC (14, 2) NULL,
    [penalty_m_n_o_pd]       NUMERIC (14, 2) NULL,
    [penalty_i_n_s_pd]       NUMERIC (14, 2) NULL,
    [interest_m_n_o_pd]      NUMERIC (14, 2) NULL,
    [interest_i_n_s_pd]      NUMERIC (14, 2) NULL,
    [attorney_fees_pd]       NUMERIC (14, 2) NULL,
    [bill_assessed_value]    NUMERIC (14, 2) NULL,
    [bill_taxable_val]       NUMERIC (14, 2) NULL,
    [stmnt_id]               NUMERIC (18)    NULL,
    [discount_mno_pd]        NUMERIC (14, 2) NULL,
    [discount_ins_pd]        NUMERIC (14, 2) NULL,
    [prev_bill_id]           INT             NULL,
    [new_bill_id]            INT             NULL,
    [create_dt]              DATETIME        NULL,
    [ref_id1]                VARCHAR (20)    NULL,
    [ref_id2]                VARCHAR (20)    NULL,
    [ref_id3]                VARCHAR (20)    NULL,
    [ref_id4]                VARCHAR (20)    NULL,
    [ref_id5]                VARCHAR (20)    NULL,
    [discount_offered]       CHAR (1)        NULL,
    [levy_group_id]          INT             NULL,
    [levy_run_id]            INT             NULL,
    [active_bill]            CHAR (1)        NULL,
    [q1_amt]                 NUMERIC (14, 2) NULL,
    [q1_paid]                NUMERIC (14, 2) NULL,
    [q1_due_dt]              DATETIME        NULL,
    [q2_amt]                 NUMERIC (14, 2) NULL,
    [q2_paid]                NUMERIC (14, 2) NULL,
    [q2_due_dt]              DATETIME        NULL,
    [q3_amt]                 NUMERIC (14, 2) NULL,
    [q3_paid]                NUMERIC (14, 2) NULL,
    [q3_due_dt]              DATETIME        NULL,
    [q4_amt]                 NUMERIC (14, 2) NULL,
    [q4_paid]                NUMERIC (14, 2) NULL,
    [q4_due_dt]              DATETIME        NULL,
    [q_bill]                 CHAR (1)        NULL,
    [q_create_dt]            DATETIME        NULL,
    [q_remove_dt]            DATETIME        NULL,
    [q_created_by]           INT             NULL,
    [q_removed_by]           INT             NULL,
    [bill_adj_m_n_o]         NUMERIC (14, 2) NULL,
    [bill_adj_i_n_s]         NUMERIC (14, 2) NULL,
    [refund_m_n_o_pd]        NUMERIC (14, 2) NULL,
    [refund_i_n_s_pd]        NUMERIC (14, 2) NULL,
    [refund_pen_m_n_o_pd]    NUMERIC (14, 2) NULL,
    [refund_pen_i_n_s_pd]    NUMERIC (14, 2) NULL,
    [refund_int_m_n_o_pd]    NUMERIC (14, 2) NULL,
    [refund_int_i_n_s_pd]    NUMERIC (14, 2) NULL,
    [refund_atty_fee_pd]     NUMERIC (14, 2) NULL,
    [underage_mno_pd]        NUMERIC (14, 2) NULL,
    [underage_ins_pd]        NUMERIC (14, 2) NULL,
    [overage_mno_pd]         NUMERIC (14, 2) NULL,
    [overage_ins_pd]         NUMERIC (14, 2) NULL,
    [refund_disc_mno_pd]     NUMERIC (14, 2) NULL,
    [refund_disc_ins_pd]     NUMERIC (14, 2) NULL,
    [refund_underage_mno_pd] NUMERIC (14, 2) NULL,
    [refund_underage_ins_pd] NUMERIC (14, 2) NULL,
    [refund_overage_mno_pd]  NUMERIC (14, 2) NULL,
    [refund_overage_ins_pd]  NUMERIC (14, 2) NULL,
    CONSTRAINT [CPK_installment_agreement_bill] PRIMARY KEY CLUSTERED ([bill_id] ASC, [sup_tax_yr] ASC, [sup_num] ASC, [entity_id] ASC, [prop_id] ASC, [owner_id] ASC) WITH (FILLFACTOR = 100)
);


GO

