CREATE TABLE [dbo].[pacs_imprv_det_acc] (
    [prop_id]                               INT            NOT NULL,
    [prop_val_yr]                           INT            NOT NULL,
    [imprv_id]                              INT            NOT NULL,
    [imprv_det_id]                          INT            IDENTITY (3000, 1) NOT NULL,
    [sup_num]                               INT            NOT NULL,
    [sale_id]                               INT            NOT NULL,
    [imprv_det_class_cd]                    VARCHAR (1)    NOT NULL,
    [imprv_det_meth_cd]                     VARCHAR (3)    NOT NULL,
    [imprv_det_type_cd]                     VARCHAR (3)    NOT NULL,
    [seq_num]                               INT            NULL,
    [imprv_det_val]                         DECIMAL (8)    NOT NULL,
    [imprv_det_val_source]                  VARCHAR (1)    NOT NULL,
    [imprv_det_desc]                        CHAR (20)      NOT NULL,
    [imprv_det_area]                        DECIMAL (5)    NOT NULL,
    [imprv_det_area_type]                   VARCHAR (1)    NOT NULL,
    [condition_cd]                          INT            NULL,
    [cubic_area]                            INT            NOT NULL,
    [calc_area]                             INT            NOT NULL,
    [sketch_area]                           INT            NOT NULL,
    [override_area]                         VARCHAR (1)    NOT NULL,
    [override_cubic_area]                   VARCHAR (1)    NOT NULL,
    [override_perimeter]                    VARCHAR (1)    NOT NULL,
    [perimeter]                             INT            NULL,
    [length]                                INT            NOT NULL,
    [width]                                 INT            NOT NULL,
    [height]                                INT            NOT NULL,
    [unit_price]                            DECIMAL (6, 2) NOT NULL,
    [yr_new]                                INT            NULL,
    [yr_built]                              DECIMAL (5)    NOT NULL,
    [depreciation_yr]                       INT            NULL,
    [depreciation_yr_override]              VARCHAR (1)    NOT NULL,
    [imprv_det_orig_val]                    INT            NOT NULL,
    [imprv_det_orig_up]                     INT            NOT NULL,
    [effective_tax_yr]                      INT            NULL,
    [imprv_det_adj_factor]                  NUMERIC (2, 1) NOT NULL,
    [imprv_det_adj_amt]                     INT            NOT NULL,
    [imprv_det_calc_val]                    INT            NOT NULL,
    [imprv_det_adj_val]                     INT            NOT NULL,
    [imprv_det_flat_val]                    INT            NOT NULL,
    [economic_pct]                          INT            NOT NULL,
    [physical_pct]                          INT            NOT NULL,
    [physical_pct_source]                   INT            NULL,
    [functional_pct]                        INT            NOT NULL,
    [economic_pct_override]                 VARCHAR (1)    NOT NULL,
    [physical_pct_override]                 VARCHAR (1)    NOT NULL,
    [functional_pct_override]               VARCHAR (1)    NOT NULL,
    [economic_cmnt]                         INT            NULL,
    [physical_cmnt]                         INT            NULL,
    [functional_cmnt]                       INT            NULL,
    [percent_complete]                      INT            NOT NULL,
    [percent_complete_override]             VARCHAR (1)    NOT NULL,
    [percent_complete_cmnt]                 INT            NULL,
    [new_value_flag]                        VARCHAR (1)    NOT NULL,
    [new_value]                             INT            NOT NULL,
    [new_value_override]                    VARCHAR (1)    NOT NULL,
    [sketch_cmds]                           INT            NULL,
    [use_up_for_pct_base]                   INT            NULL,
    [ref_id1]                               VARCHAR (29)   NULL,
    [reserved1]                             INT            NULL,
    [can_close_sketch]                      INT            NULL,
    [dep_pct]                               INT            NOT NULL,
    [add_factor]                            INT            NOT NULL,
    [add_factor_override]                   INT            NULL,
    [size_adj_pct]                          INT            NOT NULL,
    [dep_pct_override]                      INT            NULL,
    [size_adj_pct_override]                 INT            NULL,
    [imprv_det_sub_class_cd]                INT            NULL,
    [num_units]                             INT            NOT NULL,
    [num_stories]                           INT            NOT NULL,
    [stories_multiplier]                    INT            NULL,
    [lease_class]                           INT            NULL,
    [actual_year_built_override]            INT            NOT NULL,
    [flat_value_comment]                    INT            NULL,
    [flat_value_user_id]                    INT            NULL,
    [flat_value_date]                       INT            NULL,
    [depreciated_replacement_cost_new]      INT            NOT NULL,
    [floor_number]                          INT            NULL,
    [load_factor]                           INT            NOT NULL,
    [actual_age]                            INT            NULL,
    [net_rentable_area]                     INT            NULL,
    [building_id]                           INT            NULL,
    [permanent_crop_acres]                  INT            NULL,
    [permanent_crop_irrigation_acres]       INT            NULL,
    [permanent_crop_age_group]              INT            NULL,
    [permanent_crop_trellis]                INT            NULL,
    [permanent_crop_irrigation_system_type] INT            NULL,
    [permanent_crop_irrigation_sub_class]   INT            NULL,
    [permanent_crop_density]                INT            NULL,
    [imprv_det_cost_unit_price]             INT            NOT NULL,
    [imprv_det_ms_val]                      INT            NOT NULL,
    [imprv_det_ms_unit_price]               INT            NOT NULL
);


GO

