CREATE TABLE [dbo].[sales_comp_search_criteria] (
    [search_id]            INT             NOT NULL,
    [pacs_user_id]         INT             NULL,
    [created_dt]           DATETIME        NULL,
    [comment]              VARCHAR (255)   NULL,
    [search_year]          NUMERIC (4)     NULL,
    [region]               VARCHAR (255)   NULL,
    [abs_subdv]            VARCHAR (255)   NULL,
    [neighborhood]         VARCHAR (255)   NULL,
    [subset]               VARCHAR (255)   NULL,
    [map_id]               VARCHAR (255)   NULL,
    [school]               VARCHAR (128)   NULL,
    [city]                 VARCHAR (128)   NULL,
    [state_cd]             VARCHAR (255)   NULL,
    [appr_val]             INT             NULL,
    [appr_val_from]        INT             NULL,
    [appr_val_to]          INT             NULL,
    [imprv_class]          VARCHAR (255)   NULL,
    [imprv_area]           INT             NULL,
    [imprv_area_from]      INT             NULL,
    [imprv_area_to]        INT             NULL,
    [imprv_year]           NUMERIC (4)     NULL,
    [imprv_year_from]      NUMERIC (4)     NULL,
    [imprv_year_to]        NUMERIC (4)     NULL,
    [imprv_price]          NUMERIC (14, 2) NULL,
    [imprv_price_from]     NUMERIC (14, 2) NULL,
    [imprv_price_to]       NUMERIC (14, 2) NULL,
    [imprv_add_val]        NUMERIC (14)    NULL,
    [imprv_add_val_from]   NUMERIC (14)    NULL,
    [imprv_add_val_to]     NUMERIC (14)    NULL,
    [land_type]            VARCHAR (255)   NULL,
    [land_area_acres]      NUMERIC (14, 4) NULL,
    [land_area_acres_from] NUMERIC (14, 4) NULL,
    [land_area_acres_to]   NUMERIC (14, 4) NULL,
    [land_area_sqft]       INT             NULL,
    [land_area_sqft_from]  INT             NULL,
    [land_area_sqft_to]    INT             NULL,
    [land_area_ff]         INT             NULL,
    [land_area_ff_from]    INT             NULL,
    [land_area_ff_to]      INT             NULL,
    [land_area_lot]        INT             NULL,
    [land_area_lot_from]   INT             NULL,
    [land_area_lot_to]     INT             NULL,
    [land_area_type]       VARCHAR (5)     NULL,
    [land_area]            VARCHAR (1)     NULL,
    [land_price]           INT             NULL,
    [land_price_from]      INT             NULL,
    [land_price_to]        INT             NULL,
    [sale_search]          VARCHAR (1)     NULL,
    [sale_type]            VARCHAR (255)   NULL,
    [sale_date]            DATETIME        NULL,
    [sale_date_from]       DATETIME        NULL,
    [sale_date_to]         DATETIME        NULL,
    [sale_date_option]     VARCHAR (5)     NULL,
    [sale_price]           INT             NULL,
    [sale_price_from]      INT             NULL,
    [sale_price_to]        INT             NULL,
    [return_sale_info]     VARCHAR (1)     NULL,
    [imprv_sub_class]      VARCHAR (255)   NULL,
    [imprv_type_cd]        VARCHAR (255)   NULL,
    CONSTRAINT [CPK_sales_comp_search_criteria] PRIMARY KEY CLUSTERED ([search_id] ASC) WITH (FILLFACTOR = 100)
);


GO

