CREATE TABLE [dbo].[sales_comp_print] (
    [print_id]               INT           IDENTITY (0, 1) NOT NULL,
    [pacs_user_id]           INT           NULL,
    [prop_id]                VARCHAR (50)  NULL,
    [year]                   VARCHAR (50)  NULL,
    [geo_id]                 VARCHAR (50)  NULL,
    [owner]                  VARCHAR (50)  NULL,
    [situs]                  VARCHAR (173) NULL,
    [school]                 VARCHAR (50)  NULL,
    [city]                   VARCHAR (50)  NULL,
    [state_cd]               VARCHAR (50)  NULL,
    [region]                 VARCHAR (50)  NULL,
    [abs_subdv]              VARCHAR (50)  NULL,
    [hood]                   VARCHAR (50)  NULL,
    [subset]                 VARCHAR (50)  NULL,
    [map_id]                 VARCHAR (50)  NULL,
    [imprv_class]            VARCHAR (50)  NULL,
    [living_area]            VARCHAR (50)  NULL,
    [year_built]             VARCHAR (50)  NULL,
    [imprv_up]               VARCHAR (50)  NULL,
    [imprv_val]              VARCHAR (50)  NULL,
    [imprv_add_val]          VARCHAR (50)  NULL,
    [land_type]              VARCHAR (50)  NULL,
    [land_sqft]              VARCHAR (50)  NULL,
    [land_front_feet]        VARCHAR (50)  NULL,
    [land_acres]             VARCHAR (50)  NULL,
    [land_lot]               VARCHAR (50)  NULL,
    [land_size]              VARCHAR (50)  NULL,
    [land_up]                VARCHAR (50)  NULL,
    [land_val]               VARCHAR (50)  NULL,
    [land_val_per_area]      VARCHAR (50)  NULL,
    [land_sale_val_per_area] VARCHAR (50)  NULL,
    [appraised_val]          VARCHAR (50)  NULL,
    [appraised_val_per_sqft] VARCHAR (50)  NULL,
    [sale_type]              VARCHAR (50)  NULL,
    [sale_date]              VARCHAR (50)  NULL,
    [sale_price]             VARCHAR (50)  NULL,
    [sale_price_per_sqft]    VARCHAR (50)  NULL,
    [sale_ratio]             VARCHAR (50)  NULL,
    [score]                  VARCHAR (50)  NULL,
    [print_flag]             VARCHAR (1)   NULL,
    [sequence_num]           INT           NULL,
    [situs_street]           VARCHAR (50)  NULL,
    [item_desc]              VARCHAR (20)  NULL,
    [improv_desc_two]        VARCHAR (50)  NULL,
    [improv_desc_three]      VARCHAR (50)  NULL,
    [report_id]              VARCHAR (20)  NULL,
    [imprv_sub_class]        VARCHAR (10)  NULL,
    [imprv_type_cd]          CHAR (5)      NULL,
    [udi_type]               VARCHAR (1)   NULL,
    CONSTRAINT [CPK_sales_comp_print] PRIMARY KEY CLUSTERED ([print_id] ASC) WITH (FILLFACTOR = 100)
);


GO

