CREATE TABLE [dbo].[sup_group_property_info] (
    [sup_group_id]          INT              NOT NULL,
    [sup_yr]                NUMERIC (4)      NOT NULL,
    [sup_num]               INT              NOT NULL,
    [data_flag]             BIT              NOT NULL,
    [prop_id]               INT              NOT NULL,
    [pacs_user_id]          INT              NOT NULL,
    [sup_action]            CHAR (1)         NOT NULL,
    [sup_cd]                VARCHAR (10)     NULL,
    [owner_id]              INT              NULL,
    [pct_ownership]         NUMERIC (13, 10) NULL,
    [prop_type_cd]          VARCHAR (5)      NULL,
    [property_identifier]   VARCHAR (70)     NULL,
    [ref_id2]               VARCHAR (50)     NULL,
    [geo_id]                VARCHAR (50)     NULL,
    [mineral_int_pct]       NUMERIC (13, 10) NULL,
    [type_of_int]           VARCHAR (5)      NULL,
    [acres]                 NUMERIC (14, 4)  NULL,
    [dba_name]              VARCHAR (50)     NULL,
    [imprv_hstd_val]        NUMERIC (14)     NULL,
    [market]                NUMERIC (14)     NULL,
    [file_as_name]          VARCHAR (70)     NULL,
    [legal_desc]            VARCHAR (255)    NULL,
    [imprv_non_hstd_val]    NUMERIC (14)     NULL,
    [prod_loss]             NUMERIC (14)     NULL,
    [addr_line1]            VARCHAR (60)     NULL,
    [land_hstd_val]         NUMERIC (14)     NULL,
    [appraised_val]         NUMERIC (14)     NULL,
    [addr_line2]            VARCHAR (60)     NULL,
    [appraiser_nm]          VARCHAR (51)     NULL,
    [operator]              VARCHAR (30)     NULL,
    [legal_acreage]         NUMERIC (14, 4)  NULL,
    [land_non_hstd_val]     NUMERIC (14)     NULL,
    [ten_percent_cap]       NUMERIC (14)     NULL,
    [addr_line3]            VARCHAR (60)     NULL,
    [state_codes]           VARCHAR (50)     NULL,
    [map_id]                VARCHAR (20)     NULL,
    [prod_use]              NUMERIC (14)     NULL,
    [assessed_val]          NUMERIC (14)     NULL,
    [addr_line4]            VARCHAR (128)    NULL,
    [situs_display]         VARCHAR (146)    NULL,
    [mortgage_cd]           VARCHAR (10)     NULL,
    [prod_mkt]              NUMERIC (14)     NULL,
    [agent_name]            VARCHAR (70)     NULL,
    [ref_id1]               VARCHAR (50)     NULL,
    [late_ag]               CHAR (1)         NULL,
    [sup_desc]              VARCHAR (500)    NULL,
    [ag_market]             NUMERIC (14)     NULL,
    [ag_use_val]            NUMERIC (14)     NULL,
    [ag_loss]               NUMERIC (14)     NULL,
    [timber_market]         NUMERIC (14)     NULL,
    [timber_use]            NUMERIC (14)     NULL,
    [timber_loss]           NUMERIC (14)     NULL,
    [addr_is_international] BIT              DEFAULT ((0)) NOT NULL,
    [country_name]          VARCHAR (50)     NULL,
    CONSTRAINT [CPK_sup_group_property_info] PRIMARY KEY CLUSTERED ([sup_group_id] ASC, [sup_yr] ASC, [sup_num] ASC, [data_flag] ASC, [prop_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CFK_sup_group_property_info_prop_id] FOREIGN KEY ([prop_id]) REFERENCES [dbo].[property] ([prop_id])
);


GO

