create view __aaComper_2020_Shape as
SELECT  [ParcelID]
      ,[MapNumber]
      ,cp.[prop_id]
      ,[situs_display]
      ,[abs_subdv_desc]
      ,[neighborhood]
      ,[subset]
      ,[reval]
      ,[tax_area_number]
      ,[tax_area_id]
      ,[property_use_cd]
      ,[prop_type_cd]
      ,[property_use_desc]
      ,[PrimaryImprovement]
      ,[imprv_state_cd]
      ,[stories]
      ,[num_imprv]
      ,[TotalArea]
      ,[finished_basement]
      ,[unfinished_basement]
      ,[Total_Basement]
      ,[YearBuilt]
      ,[Age]
      ,[class_cd]
      ,[class_subclass_cd]
      ,[Condition]
      ,[Style]
      ,[Roofing]
      ,[Heating]
      ,[ExtWall]
      ,[Bathrooms]
      ,[HalfBaths]
      ,[fireplace]
      ,[foundation]
      ,[fixture_count]
      ,[attached_garage]
      ,[detached_garage]
      ,[Carport]
      ,[Pole_building]
      ,[Yard_Imprv]
      ,[SPPSF]
      ,[Imprv_AdjVal]
      ,[Current_unit_price]
      ,[Land_UnitVal]
      ,[ag_use_val]
      ,[TotalMarketValue]
      ,[ImpVal]
      ,[LandVal]
      ,[totalacres]
      ,[land_sqft]
      ,[current_ratio]
      ,[excise_number]
      ,[deed_type_cd]
      ,[adjustedSaleprice]
      ,[OriginalSalePrice]
      ,[SaleDate]
      ,[class_cd_at_sale]
      ,[Imprv_unit_price_at_sale]
      ,[Land_unit_price_at_sale]
      ,[sl_ratio_type_cd]
      ,[sl_county_ratio_cd]
      ,[land_only_sale]
      ,[flood_zone]
      ,[school_district]
      ,[zoning]
      ,[img_path]
      ,coords.[XCoord]
      ,coords.[YCoord]
	  ,coords.shape
  FROM [pacs_oltp].[dbo].[__aaComper_2020] cp
  LEFT JOIN 
	(SELECT [Parcel_ID],ROW_NUMBER() over (partition by prop_id ORDER BY [OBJECTID] DESC) AS order_id,[Prop_ID],[Shape].STCentroid().STX as XCoord,	[Shape].STCentroid().STY as YCoord , shape
		FROM [Benton_spatial_data].[dbo].[PARCELSANDASSESS]
	) as coords ON cp.prop_id = coords.Prop_ID AND coords.order_id = 1

GO

