create view comm_Special_uses_pv as 
SELECT [lrsn]
      ,[extension]
      ,[bldg_section]
      ,[last_update]
      ,[status]
      ,[use_code]
      ,[area]
      ,[grade]
      ,[bsmt1]
      ,[bsmt1_area]
      ,[bsmt2]
      ,[bsmt2_area]
      ,[bsmt3]
      ,[bsmt3_area]
      ,[attcan_const]
      ,[attcan_area]
      ,[detcan_quality]
      ,[detcan_const]
      ,[detcan_area]
      ,[round_canopy]
      ,[rest_area]
      ,[cash_quality]
      ,[cash_area]
      ,[plumb_fixtures]
      ,[bullet_proof]
      ,[intercom]
      ,[reproduction_cost1]
      ,[specuse_int1]
      ,[specuse_int2]
      ,[specuse_code1]
      ,[specuse_code2]
      ,[eff_year]
      ,[reproduction_cost2]
      ,[reproduction_cost3]
      ,[specuse_text1]
  FROM [cnv_src_benton_2_14_2017].[dbo].[comm_special_use]
  where status='a'

GO

