create view COMPONENT_INPUT_DEFINITION_proval as
SELECT  [ID]
      ,[INPUT_REQUIREMENT_TYPE_ID]
      ,[UNIT_OF_MEASURE_ID]
      ,[CALCULATON_DEFAULT_ID]
      ,[COMPONENT_ID]
      ,[INPUT_DEFINITION_NUMBER]
      ,[INPUT_TIP_TEXT]
      ,[MIN_VALUE]
      ,[MAX_VALUE]
      ,[DECIMAL_ALLOWED]
      ,[DESCRIPTION]
      ,[DEFAULT_VALUE]
      ,[VARIABLE_MIN_MAX_FLAG]
  FROM [mvp_cost_3Q2016].[mvp].[COMPONENT_INPUT_DEFINITION]

GO

