

create view VerifyRecalcFlagOk_vw
as
select 
	[prop_id]  ,
	[prop_val_yr] as year,
	[prop_val] ,
	[chg_dt]  ,
	[notice_mail_dt]  ,
	[land_hstd_val] ,
	[land_non_hstd_val] ,
	[imprv_hstd_val] ,
	[imprv_non_hstd_val] ,
	[appraised_val] ,
	[assessed_val] ,
	[market] ,
	[ag_use_val] ,
	[ag_market] ,
	[freeze_ceiling]  ,
	[freeze_yr]  ,
	[ag_loss] ,
	[ag_late_loss] ,
	[timber_78] ,
	[timber_market] ,
	[timber_use] ,
	[timber_loss] ,
	[timber_late_loss] ,
	[rendered_val] ,
	[rendered_yr]  ,
	[new_val] ,
	[new_yr]  ,
	[mineral_int_pct]  ,
	[orig_appraised_val] ,
	[ten_percent_cap] ,
	[sup_num]  ,
	[legal_desc]  ,
	[legal_desc_2]  ,
	[abated_pct]  ,
	[abated_amt] ,
	[abated_yr]  ,
	[eff_size_acres]  ,
	[shared_prop_val] ,
	[shared_prop_cad_code]  ,
	[legal_acreage]  ,
	[vit_flag]  ,
	[recalc_flag]  ,
	[vit_declaration_filed_dt]  ,
	[prev_sup_num]  ,
	[sup_cd] [ ,
	[sup_desc]  ,
	[sup_dt]  ,
	[sup_action]  ,
	[appr_company_id]  ,
	[prop_inactive_dt]  ,
	[hscap_qualify_yr]  ,
	[hscap_override_prevhsval_flag]  ,
	[hscap_prevhsval] ,
	[hscap_prevhsval_pacsuser] ,
	[hscap_prevhsval_comment]  ,
	[hscap_prevhsval_date]  ,
	[hscap_override_newhsval_flag]  ,
	[hscap_newhsval] ,
	[hscap_newhsval_pacsuser] ,
	[hscap_newhsval_comment]  ,
	[hscap_newhsval_date]  ,
	[last_appraisal_yr]  ,
	[oil_wells] ,
	[irr_wells] ,
	[irr_acres]  ,
	[irr_capacity] ,
	[oil_well_apply_adjust]  ,
	[oil_wells_apply_adjust]  ,
	[tif_imprv_val] ,
	[tif_land_val] ,
	[tif_flag]  ,
	[accept_create_id]  ,
	[accept_create_dt]  ,
	[abs_subdv_cd]  ,
	[hood_cd]  ,
	[block]  ,
	[tract_or_lot]  ,
	[mbl_hm_park]  ,
	[mbl_hm_space]  ,
	[rgn_cd]  ,
	[subset_cd]  ,
	[map_id]  ,
	[auto_build_legal]  ,
	[image_path] [varchar]  ,
	[hscap_prev_reappr_yr]  ,
	[hscap_base_yr]  ,
	[hscap_base_yr_override]  ,
	[hscap_base_yr_pacsuser] ,
	[hscap_base_yr_comment]  ,
	[hscap_base_yr_date]  ,
	[mapsco]  ,
	[cost_value] ,
	[income_value] ,
	[shared_value] ,
	[appr_method]  ,
	[cost_land_hstd_val] ,
	[cost_land_non_hstd_val] ,
	[cost_imprv_hstd_val] ,
	[cost_imprv_non_hstd_val] ,
	[cost_market] ,
	[cost_ag_use_val] ,
	[cost_ag_market] ,
	[cost_ag_loss] ,
	[cost_timber_market] ,
	[cost_timber_use] ,
	[cost_timber_loss] ,
	[income_land_hstd_val] ,
	[income_land_non_hstd_val] ,
	[income_imprv_hstd_val] ,
	[income_imprv_non_hstd_val] ,
	[income_market] ,
	[income_ag_use_val] ,
	[income_ag_market] ,
	[income_ag_loss] ,
	[income_timber_market] ,
	[income_timber_use] ,
	[income_timber_loss] ,
	[shared_land_hstd_val] ,
	[shared_land_non_hstd_val] ,
	[shared_imprv_hstd_val] ,
	[shared_imprv_non_hstd_val] ,
	[shared_market] ,
	[shared_ag_use_val] ,
	[shared_ag_market] ,
	[shared_ag_loss] ,
	[shared_timber_market] ,
	[shared_timber_use] ,
	[shared_timber_loss] ,
	[last_appraiser_id]  ,
	[next_appraiser_id]  ,
	[last_appraisal_dt]  ,
	[next_appraisal_dt]  ,
	[next_appraisal_rsn]  ,
	[value_appraiser_id]  ,
	[land_appraiser_id]  ,
	[sub_market_cd]  ,
	[property_use_cd]  ,
	[visibility_access_cd]  ,
	[last_pacs_user_id]  ,
	[recalc_dt]  ,
	[new_val_hs] ,
	[new_val_nhs] ,
	[new_val_p] ,
	[owner_update_dt]  ,
	[agent_update_dt]  ,
	[penpad_comments]  ,
	[last_actual_appraisal_dt]  ,
	[last_owner_id]  ,
	[cad_value_option]  ,
	[condo_pct] ,
	[reviewed_dt]  ,
	[reviewed_appraiser]  ,
	[arb_land_hstd_val] ,
	[arb_land_non_hstd_val] ,
	[arb_imprv_hstd_val] ,
	[arb_imprv_non_hstd_val] ,
	[arb_market] ,
	[arb_ag_use_val] ,
	[arb_ag_market] ,
	[arb_timber_market] ,
	[arb_timber_use] ,
	[arb_timber_loss] ,
	[shared_other_val],
	[udi_parent] ,
	[udi_parent_prop_id]  ,
	[udi_status] ,
	[udi_child_legal_desc] ,
	[image_id]  ,
	[dist_land_hstd_val] ,
	[dist_land_non_hstd_val ] ,
	[dist_imprv_hstd_val] ,
	[dist_imprv_non_hstd_val] ,
	[dist_market] ,
	[dist_ag_use_val] ,
	[dist_ag_market] ,
	[dist_timber_market] ,
	[dist_timber_use] ,
	[dist_timber_loss],
	0 as owner_id,
	0 as entity_id,
	'PV_REC' as check_cd,
	0 as ic_ref_id
from property_val with(nolock)

where isnull(recalc_flag,'') <> 'C' 
and prop_inactive_dt is null 
and IsNull(udi_parent,'')=''

GO

