CREATE TABLE [import].[temptable__1277] (
    [PERMIT TYPE]        NVARCHAR (MAX) NULL,
    [PERMIT NUMBER]      NVARCHAR (MAX) NULL,
    [ISSUE DATE]         NVARCHAR (MAX) NULL,
    [MAIN ADDRESS LINE1] NVARCHAR (MAX) NULL,
    [DESCRIPTION]        NVARCHAR (MAX) NULL,
    [FIRST NAME]         NVARCHAR (MAX) NULL,
    [LAST NAME]          NVARCHAR (MAX) NULL,
    [BUSINESS PHONE]     NVARCHAR (MAX) NULL,
    [HOME PHONE]         NVARCHAR (MAX) NULL,
    [VALUATION]          NVARCHAR (MAX) NULL,
    [PARCEL NUMBER]      NVARCHAR (MAX) NULL,
    [Column1]            NVARCHAR (MAX) NULL
);


GO

