<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="GeoDatabaseExtensions.xsd"/>
	<xs:element name="GetDataElements">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="BrowseOptions" type="DEBrowseOptions"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetDataElementsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfDElement"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetDefaultWorkingVersion">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetDefaultWorkingVersionResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetWrappedWorkspaceType">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetWrappedWorkspaceTypeResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="esriWorkspaceType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetMaxRecordCount">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetMaxRecordCountResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetReplicas">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetReplicasResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfGPReplica"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetVersions">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetVersionsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfGPVersionInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompareReplicaSchema">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RelativeReplicaSchemaDoc" type="GDSData"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CompareReplicaSchemaResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateReplica">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ParentVersion" type="xs:string" minOccurs="0"/>
				<xs:element name="ReplicaName" type="xs:string"/>
				<xs:element name="ReplicaDescription" type="GPReplicaDescription"/>
				<xs:element name="ReplicaOptions" type="GPReplicaOptions"/>
				<xs:element name="ExportOptions" type="GDSExportOptions"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CreateReplicaResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExpandReplicaDatasets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaDatasets" type="ArrayOfGPReplicaDataset"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExpandReplicaDatasetsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfGPReplicaDataset"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportAcknowledgement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaName" type="xs:string"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportAcknowledgementResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportReplicaDataChanges">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaName" type="xs:string"/>
				<xs:element name="ExportOptions" type="GDSExportOptions"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
				<xs:element name="GenerationsToExport" type="esriExportGenerationsOption"/>
				<xs:element name="SwitchRole" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportReplicaDataChangesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportReplicaSchema">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaName" type="xs:string"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportReplicaSchemaResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExtractData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="VersionName" type="xs:string" minOccurs="0"/>
				<xs:element name="ReplicaDescription" type="GPReplicaDescription"/>
				<xs:element name="ExportOptions" type="GDSExportOptions"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExtractDataResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetNextResultPortion">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DesiredRange" type="ResultPortionInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetNextResultPortionResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSQueryResultPortion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportAcknowledgement">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Data" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportAcknowledgementResponse">
		<xs:complexType/>
	</xs:element>
	<xs:element name="ImportReplicaDataChanges">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SourceType" type="esriGDSReplicaImportSource"/>
				<xs:element name="ReconcilePolicy" type="esriReplicaReconcilePolicyType"/>
				<xs:element name="ColumnLevel" type="xs:boolean"/>
				<xs:element name="Data" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportReplicaDataChangesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportReplicaSchemaChanges">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SchemaChangesDoc" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportReplicaSchemaChangesResponse">
		<xs:complexType/>
	</xs:element>
	<xs:element name="ImportData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Data" type="GDSData"/>
				<xs:element name="ImportFormat" type="esriGDSImportFormat"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ImportDataResponse">
		<xs:complexType/>
	</xs:element>
	<xs:element name="ReExportReplicaDataChanges">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaName" type="xs:string"/>
				<xs:element name="ExportOptions" type="GDSExportOptions"/>
				<xs:element name="TransportType" type="esriGDSTransportType"/>
				<xs:element name="GenerationsToExport" type="esriExportGenerationsOption"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ReExportReplicaDataChangesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TableSearch">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="VersionName" type="xs:string"/>
				<xs:element name="TableName" type="xs:string"/>
				<xs:element name="QueryFilter" type="QueryFilter"/>
				<xs:element name="QueryRange" type="ResultPortionInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TableSearchResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="GDSQueryResultPortion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UnregisterReplica">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReplicaName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UnregisterReplicaResponse">
		<xs:complexType/>
	</xs:element>
    <xs:element name="GetReplica">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="ReplicaName" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    <xs:element name="GetReplicaResponse">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="Result" type="GPReplica"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>
