<?xml version="1.0"?>
<xs:schema xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="System.xsd" />
  <xs:include schemaLocation="Geometry.xsd" />
  <xs:include schemaLocation="Geodatabase.xsd" />
  <xs:include schemaLocation="Carto.xsd" />

  <!-- Enumerations  ================================================= -->
  <xs:simpleType name="esriSVCReplicaUpdateDirection">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSVCReplicaUpdateDirection_None" />
      <xs:enumeration value="esriSVCReplicaUpdateDirection_Up" />
      <xs:enumeration value="esriSVCReplicaUpdateDirection_Down" />
      <xs:enumeration value="esriSVCReplicaUpdateDirection_Both" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="esriServiceDefinitionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriServiceDefinitionType_New" />
      <xs:enumeration value="esriServiceDefinitionType_Replacement" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="esriServiceDefinitionState">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSDState_New" />
      <xs:enumeration value="esriSDState_Draft" />
      <xs:enumeration value="esriSDState_Staging" />
      <xs:enumeration value="esriSDState_Staged" />
      <xs:enumeration value="esriSDState_Publishing" />
      <xs:enumeration value="esriSDState_Published" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="esriSVCServerType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSVCServerType_Unknown" />
      <xs:enumeration value="esriSVCServerType_FullServer" />
      <xs:enumeration value="esriSVCServerType_LightweightOnline" />
      <xs:enumeration value="esriSVCServerType_SDS" />
      <xs:enumeration value="esriSVCServerType_Classic" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="esriSVCServiceType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSVCServiceType_Unknown" />
      <xs:enumeration value="esriSVCServiceType_GeocodeServer" />
      <xs:enumeration value="esriSVCServiceType_GeoDataServer" />
      <xs:enumeration value="esriSVCServiceType_GeometryServer" />
      <xs:enumeration value="esriSVCServiceType_GlobeServer" />
      <xs:enumeration value="esriSVCServiceType_GPServer" />
      <xs:enumeration value="esriSVCServiceType_ImageServer" />
      <xs:enumeration value="esriSVCServiceType_MapServer" />
      <xs:enumeration value="esriSVCServiceType_SearchServer" />
      <xs:enumeration value="esriSVCServiceType_FeatureServer" />
      <xs:enumeration value="esriSVCServiceType_WorkFlowManagerServer" />
      <xs:enumeration value="esriSVCServiceType_SceneServer" />
      <xs:enumeration value="esriSVCServiceType_VectorTileServer" />
      <xs:enumeration value="esriSVCServiceType_KMLServer" />
    </xs:restriction>
  </xs:simpleType>
    

  <!--<xs:simpleType name="esriMapCacheStorageFormat"> - Already declared elsewhere
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriMapCacheStorageFormat_Compact" />
      <xs:enumeration value="esriMapCacheStorageFormat_Exploded" />
    </xs:restriction>
  </xs:simpleType>-->

  <!-- SVCDataset & ArrayOfSVCDataset ===================================== -->
  <xs:complexType name="SVCDataset">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="OnServerName" type="xs:string" />
      <xs:element name="DatasetType" type="esriDatasetType" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="ArrayOfSVCDataset">
    <xs:sequence>
      <xs:element name="SVCDataset" type="SVCDataset" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCReplica & ArrayOfSVCReplica ============================= -->
  <xs:complexType name="SVCReplica">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="DatasetIDs" type="ArrayOfString" minOccurs="0"/>
      <xs:element name="UpdateDirection" type="esriSVCReplicaUpdateDirection" />
      <xs:element name="Definition" type="GPReplica" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCReplica">
    <xs:sequence>
      <xs:element name="SVCReplica" type="SVCReplica" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCDatabase & ArrayOfSVCDatabase ============================== -->
  <xs:complexType name="SVCDatabase">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="OnPremiseWorkspaceFactoryProgID" type="xs:string" />
      <xs:element name="OnPremiseConnectionString" type="xs:string" />
      <xs:element name="InPackageWorkspaceFactoryProgID" type="xs:string" />
      <xs:element name="Datasets" type="ArrayOfSVCDataset" />
      <xs:element name="Replicas" type="ArrayOfSVCReplica" />
      <xs:element name="SwizzledOnClient" type="xs:boolean" />
      <xs:element name="ByReference" type="xs:boolean" />
      <xs:element name="OnServerWorkspaceFactoryProgID" type="xs:string" />
      <xs:element name="OnServerConnectionString" type="xs:string" />
      <xs:element name="OnServerName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCDatabase">
    <xs:sequence>
      <xs:element name="SVCDatabase" type="SVCDatabase" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCConfiguration & ArrayOfSVCConfiguration ==================================== -->
  <xs:complexType name="SVCConfiguration">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="TypeName" type="xs:string" />
      <xs:element name="ResourceID" type="xs:string" />
      <xs:element name="ServiceFolder" type="xs:string" />
      <xs:element name="DataFolder" type="xs:string" />
      <xs:element name="Definition" type="SVCConfigurationDefinition" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCConfiguration">
    <xs:sequence>
      <xs:element name="SVCConfiguration" type="SVCConfiguration" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCConfigurationDefinition ======================================================== -->
  <xs:complexType name="SVCConfigurationDefinition">
    <xs:sequence>
      <xs:element name="Description" type="xs:string" />
      <xs:element name="ConfigurationProperties" type="PropertySet" minOccurs="0"/>
      <xs:element name="Info" type="PropertySet" minOccurs="0"/>
      <xs:element name="Props" type="PropertySet" minOccurs="0"/>
      <xs:element name="RecyclingInterval" type="xs:string" />
      <xs:element name="RecyclingStart" type="xs:integer" />
      <xs:element name="Extensions" type="ArrayOfSVCExtension" />
      <xs:element name="Cluster" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCExtension & ArrayOfSVCExtension ============================= -->
  <xs:complexType name="SVCExtension">
    <xs:sequence>
      <xs:element name="Enabled" type="xs:boolean" />
      <xs:element name="Info" type="PropertySet" minOccurs="0"/>
      <xs:element name="Props" type="PropertySet" minOccurs="0"/>
      <xs:element name="TypeName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCExtension">
    <xs:sequence>
      <xs:element name="SVCExtension" type="SVCExtension" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCFile & ArrayOfSVCFile =================================== -->
  <xs:complexType name="SVCFile">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="ByReference" type="xs:boolean" />
      <xs:element name="OnServerName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCFile">
    <xs:sequence>
      <xs:element name="SVCFile" type="SVCFile" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCFolder & ArrayOfSVCFolder ======================================= -->
  <xs:complexType name="SVCFolder">
    <xs:sequence>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="ByReference" type="xs:boolean" />
      <xs:element name="OnServerName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCFolder">
    <xs:sequence>
      <xs:element name="SVCFolder" type="SVCFolder" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- SVCInitialCache =================================================== -->
  <xs:complexType name="SVCInitialCache">
    <xs:sequence>
      <xs:element name="Extent" type="Envelope" minOccurs="0"/>
      <xs:element name="ExtentsSourceFeatureClass" type="xs:string" />
      <xs:element name="InitialCacheInfos" type="ArrayOfSVCInitialCacheInfo" />
      <xs:element name="CacheMethod" type="xs:integer" />
      <xs:element name="IsFullExtent" type="xs:boolean" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCInitialCacheInfo & ArrayOfSVCInitialCacheInfo =================== -->
  <xs:complexType name="SVCInitialCacheInfo">
    <xs:sequence>
      <xs:element name="LevelID" type="xs:integer" />
      <xs:element name="Scale" type="xs:double" />
      <xs:element name="Size" type="xs:double" />
      <xs:element name="IsStatisticalEstimate" type="xs:boolean" />
      <xs:element name="NumberOfTiles" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCInitialCacheInfo">
    <xs:sequence>
      <xs:element name="SVCInitialCacheInfo" type="SVCInitialCacheInfo" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- SVCManifest =================================================== -->
  <xs:complexType name="SVCManifest">
    <xs:sequence>
      <xs:element name="SplitManifest" type="xs:boolean" minOccurs="0"/>
      <xs:element name="Databases" type="ArrayOfSVCDatabase" />
      <xs:element name="Resources" type="ArrayOfSVCResource" />
      <xs:element name="Folders" type="ArrayOfSVCFolder" minOccurs="0"/>
      <xs:element name="Files" type="ArrayOfSVCFile" minOccurs="0"/>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="StagingPath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="ByReference" type="xs:boolean" />
      <xs:element name="Type" type="esriServiceDefinitionType" />
      <xs:element name="State" type="esriServiceDefinitionState" />
      <xs:element name="ServerType" type="esriSVCServerType" />
      <xs:element name="DataFolder" type="xs:string" />
      <xs:element name="StagingSettings" type="PropertySet" />
      <xs:element name="TemplateSettings" type="PropertySet" />
      <xs:element name="KeepExistingData" type="xs:boolean" />
      <xs:element name="KeepExistingMapCache" type="xs:boolean" />
      <xs:element name="ClientHostName" type="xs:string" />
      <xs:element name="OnServerName" type="xs:string" />
      <xs:element name="Configurations" type="ArrayOfSVCConfiguration" minOccurs="0"/>
      <xs:element name="CacheSchema" type="CacheInfo" minOccurs="0"/>             <!-- xs:anyType -->
      <xs:element name="ItemInfo" type="ItemInfo" minOccurs="0" nillable="true"/>
	  <xs:element name="Metadata" type="XmlPropertySet" minOccurs="0" nillable="true"/>
      <xs:element name="InitCacheLevels" type="SVCInitialCache" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- SVCResource & ArrayOfSVCResource =================== -->
  <xs:complexType name="SVCResource">
    <xs:sequence>
      <xs:element name="DatasetIDs" type="ArrayOfString" minOccurs="0"/>
      <xs:element name="ID" type="xs:string" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="ClientName" type="xs:string" />
      <xs:element name="OnPremisePath" type="xs:string" />
      <xs:element name="StagingPath" type="xs:string" />
      <xs:element name="ServerPath" type="xs:string" />
      <xs:element name="InPackagePath" type="xs:string" />
      <xs:element name="OnServerName" type="xs:string" />
      <xs:element name="CIMPath" type="xs:string" />
      <xs:element name="RepositoryID" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ArrayOfSVCResource">
    <xs:sequence>
      <xs:element name="SVCResource" type="SVCResource" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <!-- DocumentationInfo ===================================================== -->
  <xs:complexType name="DocumentationInfo">
    <xs:sequence>
      <xs:element name="URL" type="xs:string" />
      <xs:element name="EmbeddedData" type="xs:base64Binary" />
    </xs:sequence>
  </xs:complexType>

<!-- ThumbnailInfo ===================================================== -->
  <xs:complexType name="ThumbnailInfo">
    <xs:sequence>
      <xs:element name="URL" type="xs:string" />
      <xs:element name="EmbeddedData" type="xs:base64Binary" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- ItemInfo = Note this havs changed from 10.2 ============================== -->
  <xs:complexType name="ItemInfo">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="GUID" type="xs:string" />
      <xs:element name="Type" type="xs:string" />
      <xs:element name="TypeKeywords" type="ArrayOfString" nillable="true" minOccurs="0"/>
      <xs:element name="TypeInfo" type="ArrayOfString" nillable="true" minOccurs="0"/>
      <xs:element name="CatalogPath" type="xs:string" />
      <xs:element name="Title" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element name="Tags" type="ArrayOfString" nillable="true" minOccurs="0"/>
      <xs:element name="Snippet" type="xs:string" />
      <xs:element name="Url" type="xs:string" minOccurs="0"/>
      <xs:element name="DataLastModifiedTime" type="xs:anyType" nillable="true" minOccurs="0"/>
      <xs:element name="Extent" type="Envelope" nillable="true" minOccurs="0"/>
      <xs:element name="SpatialReference" type="SpatialReference" nillable="true" minOccurs="0"/>
      <xs:element name="ThumbnailInfo" type="ThumbnailInfo" nillable="true" minOccurs="0"/>
      <xs:element name="DocumentationInfo" type="DocumentationInfo" nillable="true" minOccurs="0"/>
      <xs:element name="AccessInformation" type="xs:string" />  		<!-- c_xml_element_Constraints --> 
      <xs:element name="ItemProperties" type="PropertySet" nillable="true" minOccurs="0"/>  <!-- Last 10.0 property--> 
      <xs:element name="MinScale" type="xs:double" />
      <xs:element name="MaxScale" type="xs:double" />
      <xs:element name="Credits" type="xs:string" />
      <xs:element name="spatialReference" type="xs:string" />         <!-- This is the string representation of the spatial reference ... -->
    </xs:sequence>
  </xs:complexType>

  <!-- TileCacheInfo ===================================================== / Defined elsewhere -->
  <!--<xs:complexType name="TileCacheInfo">
    <xs:sequence>
      <xs:element name="SpatialReference" type="SpatialReference" nillable="true" minOccurs="0"/>
      <xs:element name="Origin" type="Point" nillable="true" minOccurs="0"/>
      <xs:element name="TileCols" type="xs:integer" nillable="true" minOccurs="0"/>
      <xs:element name="TileRows" type="xs:integer" nillable="true" minOccurs="0"/>
      <xs:element name="DPI" type="xs:double"/>
      <xs:element name="LODInfos" type="ArrayOfLODInfo" nillable="true" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>-->

  <!-- TileImageInfo ===================================================== --><!--
  <xs:complexType name="TileImageInfo">
    <xs:sequence>
      <xs:element name="Format" type="xs:string" />
      <xs:element name="CompressionQuality" type="xs:integer" />
      <xs:element name="Antialiasing" type="xs:boolean" />
    </xs:sequence>
  </xs:complexType>-->

  <!-- CacheStorageInfo ===================================================== -->
  <!--
  <xs:complexType name="CacheStorageInfo">
    <xs:sequence>
      <xs:element name="CacheStorageFormat" type="esriMapCacheStorageFormat" />
      <xs:element name="PacketSize" type="xs:integer" />
    </xs:sequence>
  </xs:complexType>-->
  
  <!-- CacheInfo ===================================================== -->
  <xs:complexType name="CacheInfo">
    <xs:sequence>
      <xs:element name="TileCacheInfo" type="TileCacheInfo" nillable="true" minOccurs="0"/>
      <xs:element name="TileImageInfo" type="TileImageInfo" nillable="true" minOccurs="0"/>
      <xs:element name="CacheStorageInfo" type="CacheStorageInfo" nillable="true" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>  
