<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:include schemaLocation="Geoprocessing.xsd"/>
 <xs:element name="CancelJob">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobID" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
 </xs:element>
 <xs:element name="CancelJobResponse">
        <xs:complexType/>
 </xs:element>
 
<xs:element name="Execute">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="ToolName" type="xs:string"/>
	    <xs:element name="Values" type="GPValues"/>
	    <xs:element name="Options" type="GPResultOptions" minOccurs="0"/>
	    <xs:element name="EnvironmentValues" type="PropertySet" minOccurs="0"/>
	  </xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="ExecuteResponse">
	<xs:complexType>
	  <xs:sequence>
	    <xs:element name="Result" type="GPResult"/>
	  </xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="GetExecutionType">
<xs:complexType/>
</xs:element>
<xs:element name="GetExecutionTypeResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="esriExecutionType"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobMessages">
<xs:complexType>
  <xs:sequence>
    <xs:element name="JobID" type="xs:string"/>
  </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobMessagesResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="ArrayOfJobMessage"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobResult">
<xs:complexType>
  <xs:sequence>
    <xs:element name="JobID" type="xs:string"/>
    <xs:element name="ParameterNames" type="ArrayOfString" minOccurs="0"/>
    <xs:element name="Options" type="GPResultOptions" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobResultResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="GPResult"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobStatus">
<xs:complexType>
  <xs:sequence>
    <xs:element name="JobID" type="xs:string"/>
  </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobStatusResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="esriJobStatus"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetResultMapServerName">
<xs:complexType/>
</xs:element>
<xs:element name="GetResultMapServerNameResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="xs:string"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetTaskInfos">
	<xs:complexType/>
</xs:element>
<xs:element name="GetTaskInfosResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Result" type="ArrayOfGPToolInfo"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="GetTaskNames">
	<xs:complexType/>
</xs:element>
<xs:element name="GetTaskNamesResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Result" type="ArrayOfString"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="GetToolInfo">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="ToolName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:element name="GetToolInfoResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Result" type="GPToolInfo"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="GetToolInfos">
	<xs:complexType/>
</xs:element>
<xs:element name="GetToolInfosResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Result" type="ArrayOfGPToolInfo"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="GetToolNames">
	<xs:complexType/>
</xs:element>
<xs:element name="GetToolNamesResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="Result" type="ArrayOfString"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="SubmitJob">
<xs:complexType>
  <xs:sequence>
    <xs:element name="ToolName" type="xs:string"/>
    <xs:element name="Values" type="GPValues"/>
	  <xs:element name="Options" type="GPResultOptions" minOccurs="0"/>
	  <xs:element name="EnvironmentValues" type="PropertySet" minOccurs="0"/>
  </xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="SubmitJobResponse">
<xs:complexType>
  <xs:sequence>
    <xs:element name="Result" type="xs:string"/>
  </xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetResultWorkspace">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
		<xs:element name="TransportType" type="esriGDSTransportType"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetResultWorkspaceResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="GDSData"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobToolName">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobToolNameResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobInputValues">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
		<xs:element name="ParameterNames" type="ArrayOfString" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobInputValuesResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="GPValues"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobResultOptions">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobResultOptionsResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="GPResultOptions"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobEnvironmentValues">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobEnvironmentValuesResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="PropertySet"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="GetJobResultMapExtent">
<xs:complexType>
	<xs:sequence>
		<xs:element name="JobID" type="xs:string"/>
	</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="GetJobResultMapExtentResponse">
<xs:complexType>
	<xs:sequence>
		<xs:element name="Result" type="Envelope"/>
	</xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>
