<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="Carto.xsd"/>
	<xs:element name="GetDocumentInfo">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetDocumentInfoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="PropertySet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetMapCount">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetMapCountResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetMapName">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Index" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetMapNameResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetDefaultMapName">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetDefaultMapNameResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetServerInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetServerInfoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="MapServerInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportMapImage">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="ImageDescription" type="ImageDescription"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExportMapImageResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="MapImage"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  <xs:element name="ExportScaleBar">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ScaleBar" type="ScaleBar" minOccurs="0"/>
        <xs:element name="MapDescription" type="MapDescription"/>
        <xs:element name="MapDisplay" type="ImageDisplay"/>
        <xs:element name="BackGroundColor" type="Color" minOccurs ="0"/>
        <xs:element name="ImageDescription" type="ImageDescription"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  <xs:element name="ExportScaleBarResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ImageResult"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
	<xs:element name="Find">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
				<xs:element name="SearchString" type="xs:string"/>
				<xs:element name="Contains" type="xs:boolean"/>
				<xs:element name="SearchFields" type="xs:string"/>
				<xs:element name="FindOption" type="esriFindOption"/>
				<xs:element name="LayerIDs" type="ArrayOfInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FindResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfMapServerFindResult"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Identify">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
				<xs:element name="SearchShape" type="Geometry"/>
				<xs:element name="Tolerance" type="xs:int"/>
				<xs:element name="IdentifyOption" type="esriIdentifyOption"/>
				<xs:element name="LayerIDs" type="ArrayOfInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IdentifyResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfMapServerIdentifyResult"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureCount">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
				<xs:element name="QueryFilter" type="QueryFilter"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureCountResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureIDs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
				<xs:element name="QueryFilter" type="QueryFilter"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureIDsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="FIDSet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
				<xs:element name="QueryFilter" type="QueryFilter"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryFeatureDataResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="RecordSet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  <xs:element name="QueryFeatureCount2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="LayerDescription" type="LayerDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryFeatureCount2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryFeatureIDs2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="LayerDescription" type="LayerDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryFeatureIDs2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="FIDSet"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryFeatureData2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="LayerDescription" type="LayerDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
        <xs:element name="QueryResultOptions" type="QueryResultOptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryFeatureData2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="QueryResult"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
	<xs:element name="QueryHyperlinks">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
				<xs:element name="LayerIDs" type="ArrayOfInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="QueryHyperlinksResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfMapServerHyperlink"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ComputeScale">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ComputeScaleResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ComputeDistance">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="FromPoint" type="Point"/>
				<xs:element name="ToPoint" type="Point"/>
				<xs:element name="Units" type="esriUnits"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ComputeDistanceResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:double"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ToMapPoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
				<xs:element name="ScreenXValues" type="ArrayOfInt"/>
				<xs:element name="ScreenYValues" type="ArrayOfInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ToMapPointsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="Multipoint"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FromMapPoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapDescription" type="MapDescription"/>
				<xs:element name="MapImageDisplay" type="ImageDisplay"/>
				<xs:element name="MapPoints" type="Multipoint"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FromMapPointsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ScreenXValues" type="ArrayOfInt"/>
				<xs:element name="ScreenYValues" type="ArrayOfInt"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  <xs:element name="GetLegendInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="LayerIDs" type="ArrayOfInt"/>
        <xs:element name="LegendPatch" type="MapServerLegendPatch"/>
        <xs:element name="ImageType" type="ImageType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetLegendInfoResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfMapServerLegendInfo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
	<xs:element name="GetLegendInfo2">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="MapDescription" type="MapDescription" />
        <xs:element name="MapImageDisplay" type="ImageDisplay" />
        <xs:element name="LayerIDs" type="ArrayOfInt"/>
				<xs:element name="LegendPatch" type="MapServerLegendPatch"/>
				<xs:element name="ImageType" type="ImageType"/>
      </xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetLegendInfo2Response">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfMapServerLegendInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSQLSyntaxInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSQLSyntaxInfoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="SQLSyntaxInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSupportedImageReturnTypes">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetSupportedImageReturnTypesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="esriImageReturnType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsFixedScaleMap">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IsFixedScaleMapResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="HasSingleFusedMapCache">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="HasSingleFusedMapCacheResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  <xs:element name="GetTileCacheInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetTileCacheInfoResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="TileCacheInfo"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	  <xs:element name="GetMapTile">
	    <xs:complexType>
	      <xs:sequence>
		<xs:element name="MapName" type="xs:string" />
		<xs:element name="Level" type="xs:int" />
		<xs:element name="Row" type="xs:int" />
		<xs:element name="Column" type="xs:int" />
		<xs:element name="Format" type="xs:string" minOccurs="0" />
	      </xs:sequence>
	    </xs:complexType>
	  </xs:element>
	<xs:element name="GetMapTileResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:base64Binary"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="HasLayerCache">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="HasLayerCacheResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetLayerTile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
				<xs:element name="Level" type="xs:int"/>
				<xs:element name="Row" type="xs:int"/>
				<xs:element name="Column" type="xs:int"/>
				<xs:element name="Format" type="xs:string" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetLayerTileResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:base64Binary"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetVirtualCacheDirectory">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetVirtualCacheDirectoryResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="GetCacheName">
	    <xs:complexType>
	        <xs:sequence>
				<xs:element name="MapName" type="xs:string"/>
				<xs:element name="LayerID" type="xs:int"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetCacheNameResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetTileImageInfo">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="MapName" type="xs:string" />
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="GetTileImageInfoResponse">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="Result" type="TileImageInfo" />
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	<xs:element name="GetCacheControlInfo">
	  <xs:annotation>
	    <xs:documentation>Gets the cache control information for a given map.</xs:documentation>
	  </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetCacheControlInfoResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="CacheControlInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetServiceConfigurationInfo">
    <xs:complexType/>
  </xs:element>
  <xs:element name="GetServiceConfigurationInfoResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="PropertySet" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetCacheDescriptionInfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetCacheDescriptionInfoResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="CacheDescriptionInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRowCount">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRowCountResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="xs:int"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRowIDs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRowIDsResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfInt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="QueryFilter" type="QueryFilter"/>
        <xs:element name="QueryResultOptions" type="QueryResultOptions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryDataResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="QueryResult"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
      <xs:element name="QueryRelatedRecords">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="MapName" type="xs:string" />
            <xs:element name="SourceTableID" type="xs:int" />
            <xs:element name="SourceFIDSet" type="FIDSet" />
            <xs:element name="RelateDescription" type="RelateDescription" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="QueryRelatedRecordsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Result" type="QueryResult" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
  <xs:element name="QueryRelatedRecords2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="SourceFIDSet" type="FIDSet" />
        <xs:element name="RelateDescription" type="RelateDescription" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRelatedRecords2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="QueryResult" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryDataStatistics">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="StatisticsRequest" type="StatisticsRequest"/>        
        <xs:element name="QueryFilter" type="QueryFilter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryDataStatisticsResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="RecordSet"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  <xs:element name="GetCacheStorageInfo">
    <xs:annotation>
      <xs:documentation>Gets the cache storage information for a given map.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetCacheStorageInfoResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="CacheStorageInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRasterValue">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="SourceTableID" type="xs:int" />
        <xs:element name="RowIDs" type="ArrayOfInt" />
        <xs:element minOccurs="0" name="FieldName" type="xs:string" />
        <xs:element minOccurs="0" name="ImageType" type="ImageType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRasterValueResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfImageResult" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRasterValue2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="RowIDs" type="ArrayOfInt" />
        <xs:element minOccurs="0" name="FieldName" type="xs:string" />
        <xs:element minOccurs="0" name="ImageType" type="ImageType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryRasterValue2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfImageResult" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentInfos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="TableID" type="xs:int" />
        <xs:element name="RowIDs" type="ArrayOfInt" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentInfosResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfAttachmentInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentInfos2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="RowIDs" type="ArrayOfInt" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentInfos2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfAttachmentInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentData">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="TableID" type="xs:int" />
        <xs:element name="AttachmentIDs" type="ArrayOfInt" />
        <xs:element name="TransportType" type="esriTransportType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentDataResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfAttachmentData" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentData2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="AttachmentIDs" type="ArrayOfInt" />
        <xs:element name="TransportType" type="esriTransportType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryAttachmentData2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfAttachmentData" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryHTMLPopups">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="TableID" type="xs:int" />
        <xs:element name="RowIDs" type="ArrayOfInt" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryHTMLPopupsResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfString" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryHTMLPopups2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="RowIDs" type="ArrayOfInt" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="QueryHTMLPopups2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfString" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetDefaultLayerDrawingDescriptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="LayerIDs" type="ArrayOfInt" />
        <xs:element name="SymbolOutputOptions" type="ServerSymbolOutputOptions" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetDefaultLayerDrawingDescriptionsResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfLayerDrawingDescription" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetMapTableSubtypeInfos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="TableIDs" type="ArrayOfInt" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetMapTableSubtypeInfosResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfMapTableSubtypeInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetMapTableSubtypeInfos2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string" />
        <xs:element name="LayerDescriptions" type="ArrayOfLayerDescription" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetMapTableSubtypeInfos2Response">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ArrayOfMapTableSubtypeInfo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GenerateDataClasses">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MapName" type="xs:string"/>
        <xs:element name="MapTableDescription" type="MapTableDescription"/>
        <xs:element name="DataClassificationDef" type="DataClassificationDef"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GenerateDataClassesResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="FeatureRenderer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
