<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">        
	<xs:include schemaLocation="GeoDatabaseExtensions.xsd"/>
	<xs:include schemaLocation="Server.xsd"/>
	<xs:element name="GetServiceDescriptions">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetServiceDescriptionsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ServiceDescriptions" type="ArrayOfServiceDescription"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  <xs:element name="GetServiceDescriptionsEx">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FolderName" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetServiceDescriptionsExResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ServiceDescriptions" type="ArrayOfServiceDescription"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GetFolders">
    <xs:complexType/>      
  </xs:element>
  <xs:element name="GetFoldersResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FolderNames" type="ArrayOfString"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
	<xs:element name="GetMessageVersion">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetMessageVersionResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MessageVersion" type="esriArcGISVersion"/>
				<xs:element name="ProMessageVersion" type="esriArcGISVersion"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetMessageFormats">
		<xs:complexType/>
	</xs:element>
	<xs:element name="GetMessageFormatsResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MessageFormats" type="esriServiceCatalogMessageFormat"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
        <xs:element name="GetTokenServiceURL">
                <xs:complexType/>		
	</xs:element>
	<xs:element name="GetTokenServiceURLResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TokenServiceURL" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
        <xs:element name="RequiresTokens">
		<xs:complexType/>			
	</xs:element>
	<xs:element name="RequiresTokensResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
