Create view __aaSim_Search as 
SELECT [ParcelID]
      ,[property_use_cd]
      ,[PrimaryImprovement]
      ,[TotalArea]
      ,[finished_basement]
      ,[unfinished_basement]
      ,[Total_Basement]
      ,[YearBuilt]
  --    ,[Age]
      ,[class_cd]
    --  ,[class_subclass_cd]
      ,[Condition]
      ,[imprv_det_desc]
      ,[Style]
      ,[Roofing]
      ,[Heating]
      ,[ExtWall]
      ,[Bathrooms]
      ,[HalfBaths]
      ,[fireplace]
      ,[foundation]
      ,[fixture_count]
      ,[attached_garage]
      ,[detached_garage]
      ,[Carport]
      ,[Pole_building]    
      --,[OriginalSalePrice]
      --,[SaleDate]
      ,[TotalAcres]
      ,[land_sqft]
       ,[ava]
      ,[flood_zone]
      ,[school_district]
      ,[zoning]
      ,[XCoord]
      ,[YCoord]
  FROM [pacs_oltp].[dbo].[__aApprEst]
  where imprv_det_desc='main area'

GO

