create view _FLOOR_AREA_PERIM_MULTIPLIER_17 as 
SELECT [ID]
      ,[VALUATION_METHOD_ID]
      ,[MULTIPLIER_VALUE]
      ,[FLOOR_AREA_PERIMETER_RATIO]
      ,[GROUP_CODE]
  FROM [mvp_cost_3Q2016].[mvp].[FLOOR_AREA_PERIM_MULTIPLIER]

GO

