import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

import { appendLocalAgentEvent, terrafusionPath } from './eventLog.js';

export interface LocalAgentEnvCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface LocalAgentInitReport {
  createdAt: number;
  repoRoot: string;
  envChecks: LocalAgentEnvCheck[];
  cardCreated: boolean;
  cardPath: string;
  cardAlreadyExisted: boolean;
  nextCommands: string[];
  blockers: string[];
}

const STARTER_CARD = [
  '# Work Card: starter',
  '',
  '## Mode',
  '',
  'Plan',
  '',
  '## Task',
  '',
  'Describe your first bounded task here.',
  '',
  '## Why',
  '',
  'Replace this with the founder reason for the task.',
  '',
  '## Readiness',
  '',
  'R1 — starter plan card. Edit before locking.',
  '',
  '## Truth Posture',
  '',
  'plan-only; no writes; no commands outside proof gates.',
  '',
  '## Confidence',
  '',
  '0.5',
  '',
  '## Allowed Files',
  '',
  '- describe each allowed path here',
  '',
  '## Forbidden Files',
  '',
  '- .env',
  '- .env.*',
  '- secrets/**',
  '',
  '## Proof Gates',
  '',
  '- pnpm run test:local-agent',
  '',
  '## Success Criteria',
  '',
  '- describe what must be true to close',
  '',
  '## Risks',
  '',
  '- describe risks',
  '',
  '## Notes',
  '',
  '- Generated by `tf agent init`. Edit, then `tf agent lock-card "<task>"` to lock it.',
  '',
].join('\n');

export class LocalAgentFirstRun {
  constructor(private readonly repoRoot: string) {}

  run(): LocalAgentInitReport {
    const envChecks = this.checkEnvironment();
    const cardPath = terrafusionPath(this.repoRoot, 'current-work-card.md');
    const cardAlreadyExisted = existsSync(cardPath);
    let cardCreated = false;

    mkdirSync(terrafusionPath(this.repoRoot), { recursive: true });

    if (!cardAlreadyExisted) {
      writeFileSync(cardPath, STARTER_CARD, 'utf8');
      cardCreated = true;
    }

    const blockers = envChecks.filter(check => !check.ok).map(check => check.name);
    const nextCommands = this.recommendNext(cardAlreadyExisted);

    const report: LocalAgentInitReport = {
      createdAt: Math.floor(Date.now() / 1000),
      repoRoot: this.repoRoot,
      envChecks,
      cardCreated,
      cardPath,
      cardAlreadyExisted,
      nextCommands,
      blockers,
    };

    writeFileSync(
      terrafusionPath(this.repoRoot, 'init-report.json'),
      JSON.stringify(report, null, 2),
      'utf8',
    );

    appendLocalAgentEvent(this.repoRoot, 'local_agent_init', {
      cardCreated,
      cardAlreadyExisted,
      blockerCount: blockers.length,
      envCheckCount: envChecks.length,
    });

    return report;
  }

  private checkEnvironment(): LocalAgentEnvCheck[] {
    const checks: LocalAgentEnvCheck[] = [];

    const nodeVersion = process.versions.node;
    const major = Number.parseInt(nodeVersion.split('.')[0] ?? '0', 10);
    checks.push({
      name: 'node',
      ok: major >= 18,
      detail: major >= 18 ? `v${nodeVersion}` : `v${nodeVersion} (need >= 18)`,
    });

    checks.push(this.probeCommand('pnpm', '--version'));
    checks.push(this.probeCommand('git', '--version'));

    return checks;
  }

  private probeCommand(cmd: string, arg: string): LocalAgentEnvCheck {
    try {
      const out = execSync(`${cmd} ${arg}`, {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
        timeout: 5000,
        windowsHide: true,
      }).trim();
      return { name: cmd, ok: true, detail: out };
    } catch {
      return { name: cmd, ok: false, detail: `${cmd} not found on PATH` };
    }
  }

  private recommendNext(cardAlreadyExisted: boolean): string[] {
    if (cardAlreadyExisted) {
      return [
        'tf agent current-card',
        'tf agent next',
        'tf agent help-me',
      ];
    }
    return [
      'tf agent current-card',
      'tf agent lock-card "Describe your task"',
      'tf agent help-me',
    ];
  }
}

export function renderLocalAgentInitReport(report: LocalAgentInitReport): string {
  const lines: string[] = [];
  lines.push('TerraFusion Local Agent — first run');
  lines.push('');
  lines.push('Environment:');
  for (const check of report.envChecks) {
    const tag = check.ok ? '[ok]' : '[--]';
    lines.push(`  ${tag} ${check.name.padEnd(6)} ${check.detail}`);
  }
  lines.push('');
  lines.push(
    report.cardCreated
      ? `Starter work card written: ${report.cardPath}`
      : `Existing work card preserved: ${report.cardPath}`,
  );
  if (report.blockers.length > 0) {
    lines.push('');
    lines.push('Blockers:');
    for (const blocker of report.blockers) {
      lines.push(`  - ${blocker}`);
    }
  }
  lines.push('');
  lines.push('Next commands:');
  for (const cmd of report.nextCommands) {
    lines.push(`  ${cmd}`);
  }
  return lines.join('\n');
}
