// GENERATED - DO NOT EDIT
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocalAgentWorkCardFactory = exports.LocalAgentModelGateway = exports.renderLocalAgentReviewReport = exports.LocalAgentReviewMode = exports.renderLocalAgentExplainReport = exports.LocalAgentExplainMode = exports.createLineSplitter = exports.encodeFrame = exports.DAEMON_ERROR_CODES = exports.DAEMON_METHODS = exports.DAEMON_RECORD_VERSION = exports.renderDaemonStatusResult = exports.renderDaemonStopResult = exports.renderDaemonStartResult = exports.defaultDaemonRecordPath = exports.daemonStatus = exports.daemonStop = exports.daemonStart = exports.LocalAgentDaemonClient = exports.defaultDaemonSocketPath = exports.LocalAgentDaemon = exports.OpenAIAdapter = exports.ClaudeAdapter = exports.iterateSseEvents = exports.assertRemoteEnabled = exports.REMOTE_ENABLE_ENV = exports.OllamaAdapter = exports.AdapterRegistry = exports.FakeModelAdapter = exports.approximateTokenCount = exports.aggregateChatStream = exports.DEFAULT_DOC_TRUTH_FILES = exports.renderLocalAgentDocTruth = exports.LocalAgentDocTruth = exports.renderLocalAgentReleasePlan = exports.LocalAgentReleasePlan = exports.renderLocalAgentEvents = exports.parseEventsArgs = exports.LocalAgentEvents = exports.renderLocalAgentStatus = exports.LocalAgentStatus = exports.renderLocalAgentInitReport = exports.LocalAgentFirstRun = exports.renderLocalAgentDoctorResult = exports.LocalAgentDoctorMode = exports.LocalAgentToolRunner = exports.matchesGlob = exports.loadFounderLocalAgentPolicy = exports.LocalAgentPermissionPolicy = exports.LOCAL_AGENT_DECISIONS = void 0;
exports.AiProfileError = exports.DEFAULT_RUNBOOK_PATH = exports.DEFAULT_LOCAL_KB_PATH = exports.DEFAULT_AI_PROFILE = exports.AI_PROFILES = exports.AI_PROFILE_ENV = exports.renderLocalAgentReleaseRunbook = exports.LocalAgentReleaseRunbookError = exports.LocalAgentReleaseRunbookBuilder = exports.renderLocalAgentTagCommand = exports.LocalAgentTagCommandRunner = exports.LocalAgentTagCommandError = exports.renderLocalAgentReleaseApproval = exports.LocalAgentReleaseApprovalRunner = exports.LocalAgentReleaseApprovalError = exports.renderLocalAgentTagGate = exports.LocalAgentTagGateRunner = exports.LocalAgentTagGateError = exports.renderLocalAgentShipMvpReport = exports.LocalAgentShipMvpRunner = exports.renderLocalAgentReleaseFreezeCard = exports.LocalAgentReleaseFreezeError = exports.LocalAgentReleaseFreezeBuilder = exports.renderLocalAgentReleaseCheck = exports.LocalAgentReleaseCheckRunner = exports.renderLocalAgentProductManifest = exports.LocalAgentProductManifestBuilder = exports.renderLocalAgentDocsIndex = exports.LocalAgentDocsIndexBuilder = exports.renderLocalAgentReleaseNotes = exports.LocalAgentReleaseNotesBuilder = exports.renderLocalAgentControlCenterPreview = exports.LocalAgentControlCenterPreview = exports.renderLocalAgentControlCenterState = exports.LocalAgentControlCenterStateBuilder = exports.renderLocalAgentNextRecommendation = exports.LocalAgentHelpSystem = exports.renderLocalAgentCommandRegistry = exports.listLocalAgentCommands = exports.LocalAgentCommandRegistryBuilder = exports.LocalAgentFounderWizard = exports.renderLocalAgentSaveState = exports.LocalAgentSaveStateWriter = exports.renderLocalAgentFinalReport = exports.LocalAgentFinalizeRunner = exports.renderLocalAgentProofReport = exports.LocalAgentProofRunner = exports.LocalAgentPatchPreview = exports.LocalAgentCardLockStore = exports.renderLocalAgentWorkCard = void 0;
exports.isDiagnosticName = exports.isDiagnosticRefusal = exports.createLocalOpsDiagnostics = exports.LocalOpsDiagnostics = exports.READONLY_DIAGNOSTICS = exports.createLocalOpsKb = exports.LocalOpsKb = exports.KB_ALLOWED_ROOT_PREFIXES = exports.createRecordingLocalOpsTraceSink = exports.createJsonlLocalOpsTraceSink = exports.noopLocalOpsTraceSink = exports.createLocalOpsTrace = exports.LocalOpsTrace = exports.LOCALOPS_TRACE_SCHEMA_VERSION = exports.LOCALOPS_EVENT_TYPES = exports.isLocalOpsSuccess = exports.isLocalOpsProblem = exports.createLocalOpsProvider = exports.EXTERNAL_PROVIDER_IDS = exports.LOCAL_PROVIDER_IDS = exports.redactedAiProfileSummary = exports.resolveAiProfile = exports.isAiProfileName = void 0;
var policy_js_1 = require("./policy.js");
Object.defineProperty(exports, "LOCAL_AGENT_DECISIONS", { enumerable: true, get: function () { return policy_js_1.LOCAL_AGENT_DECISIONS; } });
Object.defineProperty(exports, "LocalAgentPermissionPolicy", { enumerable: true, get: function () { return policy_js_1.LocalAgentPermissionPolicy; } });
Object.defineProperty(exports, "loadFounderLocalAgentPolicy", { enumerable: true, get: function () { return policy_js_1.loadFounderLocalAgentPolicy; } });
Object.defineProperty(exports, "matchesGlob", { enumerable: true, get: function () { return policy_js_1.matchesGlob; } });
var toolRunner_js_1 = require("./toolRunner.js");
Object.defineProperty(exports, "LocalAgentToolRunner", { enumerable: true, get: function () { return toolRunner_js_1.LocalAgentToolRunner; } });
var doctorMode_js_1 = require("./doctorMode.js");
Object.defineProperty(exports, "LocalAgentDoctorMode", { enumerable: true, get: function () { return doctorMode_js_1.LocalAgentDoctorMode; } });
Object.defineProperty(exports, "renderLocalAgentDoctorResult", { enumerable: true, get: function () { return doctorMode_js_1.renderLocalAgentDoctorResult; } });
var firstRun_js_1 = require("./firstRun.js");
Object.defineProperty(exports, "LocalAgentFirstRun", { enumerable: true, get: function () { return firstRun_js_1.LocalAgentFirstRun; } });
Object.defineProperty(exports, "renderLocalAgentInitReport", { enumerable: true, get: function () { return firstRun_js_1.renderLocalAgentInitReport; } });
var status_js_1 = require("./status.js");
Object.defineProperty(exports, "LocalAgentStatus", { enumerable: true, get: function () { return status_js_1.LocalAgentStatus; } });
Object.defineProperty(exports, "renderLocalAgentStatus", { enumerable: true, get: function () { return status_js_1.renderLocalAgentStatus; } });
var events_js_1 = require("./events.js");
Object.defineProperty(exports, "LocalAgentEvents", { enumerable: true, get: function () { return events_js_1.LocalAgentEvents; } });
Object.defineProperty(exports, "parseEventsArgs", { enumerable: true, get: function () { return events_js_1.parseEventsArgs; } });
Object.defineProperty(exports, "renderLocalAgentEvents", { enumerable: true, get: function () { return events_js_1.renderLocalAgentEvents; } });
var releasePlan_js_1 = require("./releasePlan.js");
Object.defineProperty(exports, "LocalAgentReleasePlan", { enumerable: true, get: function () { return releasePlan_js_1.LocalAgentReleasePlan; } });
Object.defineProperty(exports, "renderLocalAgentReleasePlan", { enumerable: true, get: function () { return releasePlan_js_1.renderLocalAgentReleasePlan; } });
var docTruth_js_1 = require("./docTruth.js");
Object.defineProperty(exports, "LocalAgentDocTruth", { enumerable: true, get: function () { return docTruth_js_1.LocalAgentDocTruth; } });
Object.defineProperty(exports, "renderLocalAgentDocTruth", { enumerable: true, get: function () { return docTruth_js_1.renderLocalAgentDocTruth; } });
Object.defineProperty(exports, "DEFAULT_DOC_TRUTH_FILES", { enumerable: true, get: function () { return docTruth_js_1.DEFAULT_DOC_TRUTH_FILES; } });
var modelAdapter_js_1 = require("./modelAdapter.js");
Object.defineProperty(exports, "aggregateChatStream", { enumerable: true, get: function () { return modelAdapter_js_1.aggregateChatStream; } });
Object.defineProperty(exports, "approximateTokenCount", { enumerable: true, get: function () { return modelAdapter_js_1.approximateTokenCount; } });
var fakeAdapter_js_1 = require("./fakeAdapter.js");
Object.defineProperty(exports, "FakeModelAdapter", { enumerable: true, get: function () { return fakeAdapter_js_1.FakeModelAdapter; } });
var adapterRegistry_js_1 = require("./adapterRegistry.js");
Object.defineProperty(exports, "AdapterRegistry", { enumerable: true, get: function () { return adapterRegistry_js_1.AdapterRegistry; } });
var ollamaAdapter_js_1 = require("./ollamaAdapter.js");
Object.defineProperty(exports, "OllamaAdapter", { enumerable: true, get: function () { return ollamaAdapter_js_1.OllamaAdapter; } });
var remoteAdapter_js_1 = require("./remoteAdapter.js");
Object.defineProperty(exports, "REMOTE_ENABLE_ENV", { enumerable: true, get: function () { return remoteAdapter_js_1.REMOTE_ENABLE_ENV; } });
Object.defineProperty(exports, "assertRemoteEnabled", { enumerable: true, get: function () { return remoteAdapter_js_1.assertRemoteEnabled; } });
Object.defineProperty(exports, "iterateSseEvents", { enumerable: true, get: function () { return remoteAdapter_js_1.iterateSseEvents; } });
var claudeAdapter_js_1 = require("./claudeAdapter.js");
Object.defineProperty(exports, "ClaudeAdapter", { enumerable: true, get: function () { return claudeAdapter_js_1.ClaudeAdapter; } });
var openaiAdapter_js_1 = require("./openaiAdapter.js");
Object.defineProperty(exports, "OpenAIAdapter", { enumerable: true, get: function () { return openaiAdapter_js_1.OpenAIAdapter; } });
var daemon_js_1 = require("./daemon.js");
Object.defineProperty(exports, "LocalAgentDaemon", { enumerable: true, get: function () { return daemon_js_1.LocalAgentDaemon; } });
Object.defineProperty(exports, "defaultDaemonSocketPath", { enumerable: true, get: function () { return daemon_js_1.defaultDaemonSocketPath; } });
var daemonClient_js_1 = require("./daemonClient.js");
Object.defineProperty(exports, "LocalAgentDaemonClient", { enumerable: true, get: function () { return daemonClient_js_1.LocalAgentDaemonClient; } });
var daemonControl_js_1 = require("./daemonControl.js");
Object.defineProperty(exports, "daemonStart", { enumerable: true, get: function () { return daemonControl_js_1.daemonStart; } });
Object.defineProperty(exports, "daemonStop", { enumerable: true, get: function () { return daemonControl_js_1.daemonStop; } });
Object.defineProperty(exports, "daemonStatus", { enumerable: true, get: function () { return daemonControl_js_1.daemonStatus; } });
Object.defineProperty(exports, "defaultDaemonRecordPath", { enumerable: true, get: function () { return daemonControl_js_1.defaultDaemonRecordPath; } });
Object.defineProperty(exports, "renderDaemonStartResult", { enumerable: true, get: function () { return daemonControl_js_1.renderDaemonStartResult; } });
Object.defineProperty(exports, "renderDaemonStopResult", { enumerable: true, get: function () { return daemonControl_js_1.renderDaemonStopResult; } });
Object.defineProperty(exports, "renderDaemonStatusResult", { enumerable: true, get: function () { return daemonControl_js_1.renderDaemonStatusResult; } });
Object.defineProperty(exports, "DAEMON_RECORD_VERSION", { enumerable: true, get: function () { return daemonControl_js_1.DAEMON_RECORD_VERSION; } });
var daemonProtocol_js_1 = require("./daemonProtocol.js");
Object.defineProperty(exports, "DAEMON_METHODS", { enumerable: true, get: function () { return daemonProtocol_js_1.DAEMON_METHODS; } });
Object.defineProperty(exports, "DAEMON_ERROR_CODES", { enumerable: true, get: function () { return daemonProtocol_js_1.DAEMON_ERROR_CODES; } });
Object.defineProperty(exports, "encodeFrame", { enumerable: true, get: function () { return daemonProtocol_js_1.encodeFrame; } });
Object.defineProperty(exports, "createLineSplitter", { enumerable: true, get: function () { return daemonProtocol_js_1.createLineSplitter; } });
var explainMode_js_1 = require("./explainMode.js");
Object.defineProperty(exports, "LocalAgentExplainMode", { enumerable: true, get: function () { return explainMode_js_1.LocalAgentExplainMode; } });
Object.defineProperty(exports, "renderLocalAgentExplainReport", { enumerable: true, get: function () { return explainMode_js_1.renderLocalAgentExplainReport; } });
var reviewMode_js_1 = require("./reviewMode.js");
Object.defineProperty(exports, "LocalAgentReviewMode", { enumerable: true, get: function () { return reviewMode_js_1.LocalAgentReviewMode; } });
Object.defineProperty(exports, "renderLocalAgentReviewReport", { enumerable: true, get: function () { return reviewMode_js_1.renderLocalAgentReviewReport; } });
var modelGateway_js_1 = require("./modelGateway.js");
Object.defineProperty(exports, "LocalAgentModelGateway", { enumerable: true, get: function () { return modelGateway_js_1.LocalAgentModelGateway; } });
var workCard_js_1 = require("./workCard.js");
Object.defineProperty(exports, "LocalAgentWorkCardFactory", { enumerable: true, get: function () { return workCard_js_1.LocalAgentWorkCardFactory; } });
Object.defineProperty(exports, "renderLocalAgentWorkCard", { enumerable: true, get: function () { return workCard_js_1.renderLocalAgentWorkCard; } });
var cardLock_js_1 = require("./cardLock.js");
Object.defineProperty(exports, "LocalAgentCardLockStore", { enumerable: true, get: function () { return cardLock_js_1.LocalAgentCardLockStore; } });
var patchPreview_js_1 = require("./patchPreview.js");
Object.defineProperty(exports, "LocalAgentPatchPreview", { enumerable: true, get: function () { return patchPreview_js_1.LocalAgentPatchPreview; } });
var proof_js_1 = require("./proof.js");
Object.defineProperty(exports, "LocalAgentProofRunner", { enumerable: true, get: function () { return proof_js_1.LocalAgentProofRunner; } });
Object.defineProperty(exports, "renderLocalAgentProofReport", { enumerable: true, get: function () { return proof_js_1.renderLocalAgentProofReport; } });
var finalize_js_1 = require("./finalize.js");
Object.defineProperty(exports, "LocalAgentFinalizeRunner", { enumerable: true, get: function () { return finalize_js_1.LocalAgentFinalizeRunner; } });
Object.defineProperty(exports, "renderLocalAgentFinalReport", { enumerable: true, get: function () { return finalize_js_1.renderLocalAgentFinalReport; } });
var saveState_js_1 = require("./saveState.js");
Object.defineProperty(exports, "LocalAgentSaveStateWriter", { enumerable: true, get: function () { return saveState_js_1.LocalAgentSaveStateWriter; } });
Object.defineProperty(exports, "renderLocalAgentSaveState", { enumerable: true, get: function () { return saveState_js_1.renderLocalAgentSaveState; } });
var wizard_js_1 = require("./wizard.js");
Object.defineProperty(exports, "LocalAgentFounderWizard", { enumerable: true, get: function () { return wizard_js_1.LocalAgentFounderWizard; } });
var commandRegistry_js_1 = require("./commandRegistry.js");
Object.defineProperty(exports, "LocalAgentCommandRegistryBuilder", { enumerable: true, get: function () { return commandRegistry_js_1.LocalAgentCommandRegistryBuilder; } });
Object.defineProperty(exports, "listLocalAgentCommands", { enumerable: true, get: function () { return commandRegistry_js_1.listLocalAgentCommands; } });
Object.defineProperty(exports, "renderLocalAgentCommandRegistry", { enumerable: true, get: function () { return commandRegistry_js_1.renderLocalAgentCommandRegistry; } });
var help_js_1 = require("./help.js");
Object.defineProperty(exports, "LocalAgentHelpSystem", { enumerable: true, get: function () { return help_js_1.LocalAgentHelpSystem; } });
Object.defineProperty(exports, "renderLocalAgentNextRecommendation", { enumerable: true, get: function () { return help_js_1.renderLocalAgentNextRecommendation; } });
var controlCenter_js_1 = require("./controlCenter.js");
Object.defineProperty(exports, "LocalAgentControlCenterStateBuilder", { enumerable: true, get: function () { return controlCenter_js_1.LocalAgentControlCenterStateBuilder; } });
Object.defineProperty(exports, "renderLocalAgentControlCenterState", { enumerable: true, get: function () { return controlCenter_js_1.renderLocalAgentControlCenterState; } });
var controlCenterPreview_js_1 = require("./controlCenterPreview.js");
Object.defineProperty(exports, "LocalAgentControlCenterPreview", { enumerable: true, get: function () { return controlCenterPreview_js_1.LocalAgentControlCenterPreview; } });
Object.defineProperty(exports, "renderLocalAgentControlCenterPreview", { enumerable: true, get: function () { return controlCenterPreview_js_1.renderLocalAgentControlCenterPreview; } });
var releaseNotes_js_1 = require("./releaseNotes.js");
Object.defineProperty(exports, "LocalAgentReleaseNotesBuilder", { enumerable: true, get: function () { return releaseNotes_js_1.LocalAgentReleaseNotesBuilder; } });
Object.defineProperty(exports, "renderLocalAgentReleaseNotes", { enumerable: true, get: function () { return releaseNotes_js_1.renderLocalAgentReleaseNotes; } });
var docsIndex_js_1 = require("./docsIndex.js");
Object.defineProperty(exports, "LocalAgentDocsIndexBuilder", { enumerable: true, get: function () { return docsIndex_js_1.LocalAgentDocsIndexBuilder; } });
Object.defineProperty(exports, "renderLocalAgentDocsIndex", { enumerable: true, get: function () { return docsIndex_js_1.renderLocalAgentDocsIndex; } });
var productManifest_js_1 = require("./productManifest.js");
Object.defineProperty(exports, "LocalAgentProductManifestBuilder", { enumerable: true, get: function () { return productManifest_js_1.LocalAgentProductManifestBuilder; } });
Object.defineProperty(exports, "renderLocalAgentProductManifest", { enumerable: true, get: function () { return productManifest_js_1.renderLocalAgentProductManifest; } });
var releaseCheck_js_1 = require("./releaseCheck.js");
Object.defineProperty(exports, "LocalAgentReleaseCheckRunner", { enumerable: true, get: function () { return releaseCheck_js_1.LocalAgentReleaseCheckRunner; } });
Object.defineProperty(exports, "renderLocalAgentReleaseCheck", { enumerable: true, get: function () { return releaseCheck_js_1.renderLocalAgentReleaseCheck; } });
var releaseFreeze_js_1 = require("./releaseFreeze.js");
Object.defineProperty(exports, "LocalAgentReleaseFreezeBuilder", { enumerable: true, get: function () { return releaseFreeze_js_1.LocalAgentReleaseFreezeBuilder; } });
Object.defineProperty(exports, "LocalAgentReleaseFreezeError", { enumerable: true, get: function () { return releaseFreeze_js_1.LocalAgentReleaseFreezeError; } });
Object.defineProperty(exports, "renderLocalAgentReleaseFreezeCard", { enumerable: true, get: function () { return releaseFreeze_js_1.renderLocalAgentReleaseFreezeCard; } });
var shipMvp_js_1 = require("./shipMvp.js");
Object.defineProperty(exports, "LocalAgentShipMvpRunner", { enumerable: true, get: function () { return shipMvp_js_1.LocalAgentShipMvpRunner; } });
Object.defineProperty(exports, "renderLocalAgentShipMvpReport", { enumerable: true, get: function () { return shipMvp_js_1.renderLocalAgentShipMvpReport; } });
var tagGate_js_1 = require("./tagGate.js");
Object.defineProperty(exports, "LocalAgentTagGateError", { enumerable: true, get: function () { return tagGate_js_1.LocalAgentTagGateError; } });
Object.defineProperty(exports, "LocalAgentTagGateRunner", { enumerable: true, get: function () { return tagGate_js_1.LocalAgentTagGateRunner; } });
Object.defineProperty(exports, "renderLocalAgentTagGate", { enumerable: true, get: function () { return tagGate_js_1.renderLocalAgentTagGate; } });
var releaseApproval_js_1 = require("./releaseApproval.js");
Object.defineProperty(exports, "LocalAgentReleaseApprovalError", { enumerable: true, get: function () { return releaseApproval_js_1.LocalAgentReleaseApprovalError; } });
Object.defineProperty(exports, "LocalAgentReleaseApprovalRunner", { enumerable: true, get: function () { return releaseApproval_js_1.LocalAgentReleaseApprovalRunner; } });
Object.defineProperty(exports, "renderLocalAgentReleaseApproval", { enumerable: true, get: function () { return releaseApproval_js_1.renderLocalAgentReleaseApproval; } });
var tagCommand_js_1 = require("./tagCommand.js");
Object.defineProperty(exports, "LocalAgentTagCommandError", { enumerable: true, get: function () { return tagCommand_js_1.LocalAgentTagCommandError; } });
Object.defineProperty(exports, "LocalAgentTagCommandRunner", { enumerable: true, get: function () { return tagCommand_js_1.LocalAgentTagCommandRunner; } });
Object.defineProperty(exports, "renderLocalAgentTagCommand", { enumerable: true, get: function () { return tagCommand_js_1.renderLocalAgentTagCommand; } });
var releaseRunbook_js_1 = require("./releaseRunbook.js");
Object.defineProperty(exports, "LocalAgentReleaseRunbookBuilder", { enumerable: true, get: function () { return releaseRunbook_js_1.LocalAgentReleaseRunbookBuilder; } });
Object.defineProperty(exports, "LocalAgentReleaseRunbookError", { enumerable: true, get: function () { return releaseRunbook_js_1.LocalAgentReleaseRunbookError; } });
Object.defineProperty(exports, "renderLocalAgentReleaseRunbook", { enumerable: true, get: function () { return releaseRunbook_js_1.renderLocalAgentReleaseRunbook; } });
var aiProfile_js_1 = require("./aiProfile.js");
Object.defineProperty(exports, "AI_PROFILE_ENV", { enumerable: true, get: function () { return aiProfile_js_1.AI_PROFILE_ENV; } });
Object.defineProperty(exports, "AI_PROFILES", { enumerable: true, get: function () { return aiProfile_js_1.AI_PROFILES; } });
Object.defineProperty(exports, "DEFAULT_AI_PROFILE", { enumerable: true, get: function () { return aiProfile_js_1.DEFAULT_AI_PROFILE; } });
Object.defineProperty(exports, "DEFAULT_LOCAL_KB_PATH", { enumerable: true, get: function () { return aiProfile_js_1.DEFAULT_LOCAL_KB_PATH; } });
Object.defineProperty(exports, "DEFAULT_RUNBOOK_PATH", { enumerable: true, get: function () { return aiProfile_js_1.DEFAULT_RUNBOOK_PATH; } });
Object.defineProperty(exports, "AiProfileError", { enumerable: true, get: function () { return aiProfile_js_1.AiProfileError; } });
Object.defineProperty(exports, "isAiProfileName", { enumerable: true, get: function () { return aiProfile_js_1.isAiProfileName; } });
Object.defineProperty(exports, "resolveAiProfile", { enumerable: true, get: function () { return aiProfile_js_1.resolveAiProfile; } });
Object.defineProperty(exports, "redactedAiProfileSummary", { enumerable: true, get: function () { return aiProfile_js_1.redactedAiProfileSummary; } });
var localOpsProvider_js_1 = require("./localOpsProvider.js");
Object.defineProperty(exports, "LOCAL_PROVIDER_IDS", { enumerable: true, get: function () { return localOpsProvider_js_1.LOCAL_PROVIDER_IDS; } });
Object.defineProperty(exports, "EXTERNAL_PROVIDER_IDS", { enumerable: true, get: function () { return localOpsProvider_js_1.EXTERNAL_PROVIDER_IDS; } });
Object.defineProperty(exports, "createLocalOpsProvider", { enumerable: true, get: function () { return localOpsProvider_js_1.createLocalOpsProvider; } });
Object.defineProperty(exports, "isLocalOpsProblem", { enumerable: true, get: function () { return localOpsProvider_js_1.isLocalOpsProblem; } });
Object.defineProperty(exports, "isLocalOpsSuccess", { enumerable: true, get: function () { return localOpsProvider_js_1.isLocalOpsSuccess; } });
var localOpsTrace_js_1 = require("./localOpsTrace.js");
Object.defineProperty(exports, "LOCALOPS_EVENT_TYPES", { enumerable: true, get: function () { return localOpsTrace_js_1.LOCALOPS_EVENT_TYPES; } });
Object.defineProperty(exports, "LOCALOPS_TRACE_SCHEMA_VERSION", { enumerable: true, get: function () { return localOpsTrace_js_1.LOCALOPS_TRACE_SCHEMA_VERSION; } });
Object.defineProperty(exports, "LocalOpsTrace", { enumerable: true, get: function () { return localOpsTrace_js_1.LocalOpsTrace; } });
Object.defineProperty(exports, "createLocalOpsTrace", { enumerable: true, get: function () { return localOpsTrace_js_1.createLocalOpsTrace; } });
Object.defineProperty(exports, "noopLocalOpsTraceSink", { enumerable: true, get: function () { return localOpsTrace_js_1.noopLocalOpsTraceSink; } });
Object.defineProperty(exports, "createJsonlLocalOpsTraceSink", { enumerable: true, get: function () { return localOpsTrace_js_1.createJsonlLocalOpsTraceSink; } });
Object.defineProperty(exports, "createRecordingLocalOpsTraceSink", { enumerable: true, get: function () { return localOpsTrace_js_1.createRecordingLocalOpsTraceSink; } });
var localOpsKb_js_1 = require("./localOpsKb.js");
Object.defineProperty(exports, "KB_ALLOWED_ROOT_PREFIXES", { enumerable: true, get: function () { return localOpsKb_js_1.KB_ALLOWED_ROOT_PREFIXES; } });
Object.defineProperty(exports, "LocalOpsKb", { enumerable: true, get: function () { return localOpsKb_js_1.LocalOpsKb; } });
Object.defineProperty(exports, "createLocalOpsKb", { enumerable: true, get: function () { return localOpsKb_js_1.createLocalOpsKb; } });
var localOpsDiagnostics_js_1 = require("./localOpsDiagnostics.js");
Object.defineProperty(exports, "READONLY_DIAGNOSTICS", { enumerable: true, get: function () { return localOpsDiagnostics_js_1.READONLY_DIAGNOSTICS; } });
Object.defineProperty(exports, "LocalOpsDiagnostics", { enumerable: true, get: function () { return localOpsDiagnostics_js_1.LocalOpsDiagnostics; } });
Object.defineProperty(exports, "createLocalOpsDiagnostics", { enumerable: true, get: function () { return localOpsDiagnostics_js_1.createLocalOpsDiagnostics; } });
Object.defineProperty(exports, "isDiagnosticRefusal", { enumerable: true, get: function () { return localOpsDiagnostics_js_1.isDiagnosticRefusal; } });
Object.defineProperty(exports, "isDiagnosticName", { enumerable: true, get: function () { return localOpsDiagnostics_js_1.isDiagnosticName; } });
