import arcpy as ARCPY
import os
import pyarrow as PA
import pyarrow.compute as PC
import math


class SpatialSampling:
    """ Spatial Sampling Locations Class """
    def __init__(self):
        parameters = ARCPY.GetParameterInfo()

        self.study_area = parameters[0].valueAsText
        self.out_features = parameters[1].valueAsText
        self.sampling_method = parameters[2].valueAsText
        self.strata_id_field = parameters[3].valueAsText
        self.strata_count_method = parameters[4].valueAsText
        self.bin_shape = parameters[5].valueAsText
        self.bin_size = parameters[6].value
        self.h3_resolution = parameters[7].value
        self.num_sample = parameters[8].value
        self.num_samples_per_strata = parameters[9].valueAsText
        self.population_field = parameters[10].valueAsText
        self.geometry_type = parameters[11].valueAsText
        self.min_distance = parameters[12].valueAsText
        self.spatial_rel = parameters[13].valueAsText
        self.path = os.path.dirname(self.out_features)
        self.fname = os.path.basename(self.out_features)

    def _count_centroids(self, bin_area, extent):
        """ Count the number of centroids generated by the given number of bins """
        scratch_tesselation = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
        tessellation = ARCPY.management.GenerateTessellation(scratch_tesselation,
                                                             extent, 
                                                             self.bin_shape, 
                                                             bin_area)
        selected_polygons = ARCPY.management.SelectLayerByLocation(tessellation, 
                                                                   self.spatial_rel,  # "HAVE_THEIR_CENTER_IN", 
                                                                   extent)
        
        count = ARCPY.management.GetCount(selected_polygons)

        ARCPY.management.Delete(tessellation)
        ARCPY.management.Delete(selected_polygons)
        ARCPY.management.Delete(scratch_tesselation)

        return int(count[0])  # int(count.getOutput(0))
    
    def calculate_bin_area(self, feature_class, max_iter=10):
        fc_array = ARCPY.da.FeatureClassToNumPyArray(feature_class, ('Shape_Area'))
        study_area = fc_array['Shape_Area'].sum()

        init_bin_area = study_area / self.bin_size
        count = self._count_centroids(init_bin_area, feature_class)

        if count == self.bin_size:
            return init_bin_area, count
        
        init_diff = abs(self.bin_size - count)
        area_bound = 3 * init_bin_area * init_diff / self.bin_size

        low = init_bin_area
        high = init_bin_area

        if count < self.bin_size:
            low = init_bin_area - area_bound
            if low <= 0:
                low = init_bin_area / 5
        else:
            high = init_bin_area + area_bound

        best_area = -1
        min_diff = float('inf')
        iter_num = 0
        while iter_num < max_iter and low <= high:
            mid = low + (high - low) / 2
            count = self._count_centroids(mid, feature_class)

            if min_diff > abs(count - self.bin_size):
                min_diff = abs(count - self.bin_size)
                best_area = mid
                best_count = count

            if count == self.bin_size:
                return mid, count
            
            if count < self.bin_size:
                high = mid
            else:
                low = mid
                
            iter_num += 1

        count_check = self._count_centroids(low, feature_class)
        if abs(count_check - self.bin_size) < min_diff:
            best_area = low
            best_count = count_check

        if best_count != self.bin_size and self.sampling_method == "SYSTEMATIC":
            ARCPY.AddIDMessage("WARNING", 110547)

        return best_area, best_count

    def create_random_points(self, number_of_points_or_field, constraining_feature_class):
        ARCPY.management.CreateRandomPoints(out_path=self.path, out_name=self.fname, constraining_feature_class=constraining_feature_class,
                                            number_of_points_or_field=number_of_points_or_field,
                                            minimum_allowed_distance=self.min_distance,
                                            create_multipoint_output="POINT",
                                            multipoint_size=0)
        
        # ARCPY.AddWarning(ARCPY.GetMessages(1))
        if ARCPY.GetReturnCode(1) == 983:
            ARCPY.AddIDMessage("Warning", 110547)

    def create_sample_locations(self, dissolved_study_area):
        # Generate Tessellation with study area extent and shape type
        scratch_tesselation = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
        if self.bin_shape == "H3_HEXAGON":
            ARCPY.management.GenerateTessellation(Output_Feature_Class=scratch_tesselation, Extent=dissolved_study_area, Shape_Type=self.bin_shape,
                                                  Size=self.bin_size, H3_Resolution=self.h3_resolution)
        else:
            # if the count of bins is provided
            if isinstance(self.bin_size, int):
                bin_area, count = self.calculate_bin_area(dissolved_study_area, max_iter=max(10, math.log2(self.bin_size) + 1))
                self.bin_size = str(bin_area) + " Unknown"
                ARCPY.AddMessage(f"Bin size = {bin_area}")
                ARCPY.AddMessage(f"Number of samples = {count}")

            ARCPY.management.GenerateTessellation(Output_Feature_Class=scratch_tesselation, Extent=dissolved_study_area, Shape_Type=self.bin_shape,
                                                  Size=self.bin_size)

        # Select Tessellations that are within the study area polygons
        select_tesselations = ARCPY.management.SelectLayerByLocation(in_layer=scratch_tesselation,
                                               overlap_type=self.spatial_rel,  # "HAVE_THEIR_CENTER_IN",
                                               select_features=dissolved_study_area,
                                               search_distance=None,
                                               selection_type="NEW_SELECTION",
                                               invert_spatial_relationship="NOT_INVERT")

        output = ARCPY.management.CopyFeatures(select_tesselations)

        # Convert Selected polygon (tessellations) to points (centroid)
        if self.sampling_method == "SYSTEMATIC":
            if self.geometry_type == "POINT":
                ARCPY.management.FeatureToPoint(in_features=select_tesselations,
                                            out_feature_class=self.out_features,
                                            point_location="CENTROID")
            else: # Polygon
                ARCPY.management.CopyFeatures(select_tesselations, self.out_features)

        else: #self.samplingmethod == "CLUSTER"
            ### Check that selection is not empty. 
            selected_count = ARCPY.management.GetCount(select_tesselations)
            if selected_count[0] == "0":
                ARCPY.AddIDMessage("ERROR", 110544)
                raise SystemExit
            
            ARCPY.ga.SubsetFeatures(select_tesselations,self.out_features,
                                        size_of_training_dataset=self.num_sample,
                                        subset_size_units="ABSOLUTE_VALUE")
            
            output_count = ARCPY.management.GetCount(self.out_features)
            if int(output_count[0]) != self.num_sample:
                ARCPY.AddIDMessage("WARNING", 110547)

        ARCPY.management.Delete(scratch_tesselation)
        ARCPY.management.Delete(select_tesselations)
        ARCPY.management.Delete(output)

    def _calculate_proportion(self, table, field):
        """ Calculate the proportaion of the field/shape_area """
        field_total = PC.sum(table.column(field)).as_py()
        proportional_samples = PC.divide(PC.cast(table.column(field), PA.float32()), field_total)
        proportional_samples = PC.multiply(proportional_samples, int(self.num_sample))
        rounded_samples = PC.floor(proportional_samples)
        remainders = PC.subtract(proportional_samples, rounded_samples)
        total_rounded = PC.sum(rounded_samples).as_py()

        samples_left = int(self.num_sample - total_rounded)

        # Sort the remainders to allocate samples
        sorted_indices = PC.sort_indices(remainders, sort_keys=[("f0", "descending")])[:samples_left]

        # Convert the indices to numpy for manipulation
        sorted_indices = sorted_indices.to_numpy()
        rounded_samples_np = rounded_samples.to_numpy().copy()

        # increment the samples for indices with the largest remainders
        rounded_samples_np[sorted_indices] += 1

        updated_column = PA.array(rounded_samples_np, type=rounded_samples.type)
        updated_table = table.set_column(table.schema.get_field_index(field), field, updated_column)
        return updated_table
    
    def _check_table(self, table, field):
        """ Checks the table for zero field values """
        max_value = PA.compute.max(table.column(field)).as_py()
        if max_value <= 0:
            ARCPY.AddIDMessage("ERROR", 110544)
            raise SystemExit()
        
        zero_exist = False
        first_zero_index = PA.compute.index(table.column(field), 0).as_py()
        if first_zero_index != -1:
            zero_exist = True

        return not zero_exist

    def execute(self):
        #### Check if the input is raster ####
        desc = ARCPY.Describe(self.study_area)
        input_is_raster = False
        if desc.dataType == "RasterLayer" or desc.dataType == "RasterDataset":
            input_is_raster = True

        all_strata_used = True
            
        # Simple random sampling
        if self.sampling_method == "RANDOM":
            if input_is_raster:
                scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                with ARCPY.EnvManager(snapRaster=self.study_area):
                    ARCPY.conversion.RasterToPolygon(
                        in_raster=self.study_area,
                        out_polygon_features=scratch_polygon_from_raster,
                        simplify="NO_SIMPLIFY",
                        raster_field="Value",
                        create_multipart_features="MULTIPLE_OUTER_PART",
                        max_vertices_per_feature=None)
                self.study_area = scratch_polygon_from_raster
            output_dissolve = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
            ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=output_dissolve)
            self.create_random_points(self.num_sample, output_dissolve)
            ARCPY.management.Delete(output_dissolve)
   
        # Stratify by individual polygon
        elif self.sampling_method == "STRAT_POLY":

            local_copy = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
            ARCPY.conversion.ExportFeatures(
                in_features=self.study_area,
                out_features=local_copy)
            self.study_area = local_copy

            if self.strata_count_method == "EQUAL":
                self.create_random_points(self.num_samples_per_strata, self.study_area) #self.study_area
            elif self.strata_count_method == "PROP_AREA":
                #### Calculate the proportional area ####
                table = ARCPY.da.TableToArrowTable(self.study_area) # self.study_area
                if table.num_rows == 0:
                    ARCPY.AddIDMessage("Error", 110544)
                    ARCPY.management.Delete(local_copy)
                    raise SystemExit
                updated_table = self._calculate_proportion(table, 'Shape_Area')
                all_strata_used = self._check_table(updated_table, 'Shape_Area')

                self.create_random_points('Shape_Area', updated_table)
            elif self.strata_count_method == "FIELD":
                table = ARCPY.da.TableToArrowTable(self.study_area)
                min_value = PA.compute.min(table[self.population_field]).as_py()

                # check if null
                if min_value is None:
                    ARCPY.AddIDMessage("ERROR", 110544)
                    raise SystemExit()
                # Check if there are negative values
                elif min_value < 0:
                    ARCPY.AddIDMessage("ERROR", 110546)
                    raise SystemExit()

                all_strata_used = self._check_table(table, self.population_field)

                self.create_random_points(self.population_field, self.study_area)
            else: # self.strata_count_method == "PROP_FIELD"
                #### Calculate the proportional field ####

                table = ARCPY.da.TableToArrowTable(self.study_area)
                if table.num_rows == 0:
                    ARCPY.AddIDMessage("Error", 110544)
                    ARCPY.management.Delete(local_copy)
                    raise SystemExit
                updated_table = self._calculate_proportion(table, self.population_field)
                all_strata_used = self._check_table(updated_table, self.population_field)

                self.create_random_points(self.population_field, updated_table)

        # Systematic or clustered sampling
        elif self.sampling_method == "SYSTEMATIC" or self.sampling_method == "CLUSTER":
            if input_is_raster:
                scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                with ARCPY.EnvManager(snapRaster=self.study_area):
                    ARCPY.conversion.RasterToPolygon(
                        in_raster=self.study_area,
                        out_polygon_features=scratch_polygon_from_raster,
                        simplify="NO_SIMPLIFY",
                        raster_field="Value",
                        create_multipart_features="MULTIPLE_OUTER_PART",
                        max_vertices_per_feature=None)
                self.study_area = scratch_polygon_from_raster
            output_dissolve = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
            ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=output_dissolve)

            if ARCPY.management.GetCount(output_dissolve)[0] == '0':
                ARCPY.AddIDMessage("Error", 110544)
                raise SystemExit

            if self.sampling_method == "SYSTEMATIC" and self.geometry_type == "POINT":
                self.spatial_rel = "HAVE_THEIR_CENTER_IN"

            self.create_sample_locations(output_dissolve)
            ARCPY.management.Delete(output_dissolve)
   
        # Stratify by strata ID field
        elif self.sampling_method == "STRAT_ID":
            if self.strata_count_method == "EQUAL":
                if input_is_raster:
                    scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    with ARCPY.EnvManager(snapRaster=self.study_area):
                        ARCPY.conversion.RasterToPolygon(
                            in_raster=self.study_area,
                            out_polygon_features=scratch_polygon_from_raster,
                            simplify="NO_SIMPLIFY",
                            raster_field=self.strata_id_field,
                            create_multipart_features="MULTIPLE_OUTER_PART",
                            max_vertices_per_feature=None)
                    self.create_random_points(self.num_samples_per_strata, scratch_polygon_from_raster)
                else:
                    output_dissolve = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=output_dissolve, dissolve_field=self.strata_id_field)
                    self.create_random_points(self.num_samples_per_strata, output_dissolve)
                    ARCPY.management.Delete(output_dissolve)
                
            elif self.strata_count_method == "PROP_AREA":
                # Raster input
                if input_is_raster:
                    scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    with ARCPY.EnvManager(snapRaster=self.study_area):
                        ARCPY.conversion.RasterToPolygon(
                            in_raster=self.study_area,
                            out_polygon_features=scratch_polygon_from_raster,
                            simplify="NO_SIMPLIFY",
                            raster_field=self.strata_id_field,
                            create_multipart_features="MULTIPLE_OUTER_PART",
                            max_vertices_per_feature=None)
                    table = ARCPY.da.TableToArrowTable(scratch_polygon_from_raster) 
                # Polygon input
                else:
                    output_dissolve = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=output_dissolve, dissolve_field=self.strata_id_field)
                    table = ARCPY.da.TableToArrowTable(output_dissolve)
                    ARCPY.management.Delete(output_dissolve)

                if table.num_rows == 0:
                    ARCPY.AddIDMessage("Error", 110544)
                    raise SystemExit
                
                updated_table = self._calculate_proportion(table, 'Shape_Area')
                all_strata_used = self._check_table(updated_table, 'Shape_Area')

                self.create_random_points('Shape_Area', updated_table)
               
            elif self.strata_count_method == "FIELD":
                # Raster input
                if input_is_raster:
                    scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    # Convert raster to polygon by strata ID field
                    with ARCPY.EnvManager(snapRaster=self.study_area):
                        ARCPY.conversion.RasterToPolygon(
                            in_raster=self.study_area,
                            out_polygon_features=scratch_polygon_from_raster,
                            simplify="NO_SIMPLIFY",
                            raster_field=self.strata_id_field,
                            create_multipart_features="MULTIPLE_OUTER_PART",
                            max_vertices_per_feature=None
                            )
                    # Sum population field for all values of strata ID field
                    sum_stat_table= ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.Statistics(
                        in_table=self.study_area, # input raster study area
                        out_table=sum_stat_table,
                        statistics_fields=self.population_field+" SUM", # Sum the population field
                        case_field=self.strata_id_field
                        ) 
                    
                    # Join sum of population to polygons
                    join_field_name = self.strata_id_field
                    if join_field_name == "Value":
                        join_field_name = "gridcode"
                    ARCPY.management.JoinField(
                        in_data=scratch_polygon_from_raster,
                        in_field=join_field_name,
                        join_table=sum_stat_table,
                        join_field=self.strata_id_field,
                        fields="SUM_" + self.population_field)
                    
                    arrow_table = ARCPY.da.TableToArrowTable(sum_stat_table)
                    min_value = PA.compute.min(arrow_table["SUM_" + self.population_field]).as_py()

                    # check if null
                    if min_value is None:
                        ARCPY.AddIDMessage("ERROR", 110544)
                        raise SystemExit()
                    elif min_value < 0: # check for negative value
                        ARCPY.AddIDMessage("ERROR", 110546)
                        raise SystemExit()

                    all_strata_used = self._check_table(arrow_table, "SUM_" + self.population_field)

                    self.create_random_points("SUM_" + self.population_field, scratch_polygon_from_raster)
                    ARCPY.management.Delete(sum_stat_table)
                # Polygon input
                else:
                    output_dissolve = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=output_dissolve, dissolve_field=self.strata_id_field,statistics_fields=self.population_field+" SUM")

                    arrow_table = ARCPY.da.TableToArrowTable(output_dissolve)
                    min_value = PA.compute.min(arrow_table["SUM_" + self.population_field]).as_py()

                    # check if null
                    if min_value is None:
                        ARCPY.AddIDMessage("ERROR", 110544)
                        raise SystemExit()
                    elif min_value < 0: # check for negative value
                        ARCPY.AddIDMessage("ERROR", 110546)
                        raise SystemExit()

                    all_strata_used = self._check_table(arrow_table, "SUM_" + self.population_field)

                    self.create_random_points("SUM_"+self.population_field, output_dissolve)
                    ARCPY.management.Delete(output_dissolve)

            else: #self.strata_count_method == "PROP_FIELD":
                # Raster input
                if input_is_raster:
                    scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    # Convert raster to polygon by strata ID field
                    with ARCPY.EnvManager(snapRaster=self.study_area):
                        ARCPY.conversion.RasterToPolygon(
                            in_raster=self.study_area,
                            out_polygon_features=scratch_polygon_from_raster,
                            simplify="NO_SIMPLIFY",
                            raster_field=self.strata_id_field,
                            create_multipart_features="MULTIPLE_OUTER_PART",
                            max_vertices_per_feature=None
                            )
                    
                    # Sum population field for all values of strata ID field
                    sum_stat_table= ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.Statistics(
                        in_table=self.study_area, # input raster study area
                        out_table=sum_stat_table,
                        statistics_fields=self.population_field+" SUM", # Sum the population field
                        case_field=self.strata_id_field
                        ) 
                    
                    # Join sum of population to polygons
                    join_field_name = self.strata_id_field
                    if join_field_name == "Value":
                        join_field_name = "gridcode"
                    ARCPY.management.JoinField(
                        in_data=scratch_polygon_from_raster,
                        in_field=join_field_name,
                        join_table=sum_stat_table,
                        join_field=self.strata_id_field,
                        fields="SUM_" + self.population_field)
                    input_polygon = scratch_polygon_from_raster
                    ARCPY.management.Delete(sum_stat_table)
                else: # Polygon input
                    input_polygon = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
                    ARCPY.analysis.PairwiseDissolve(in_features=self.study_area, out_feature_class=input_polygon, dissolve_field=self.strata_id_field,statistics_fields=self.population_field+" SUM")
                    
                sum_pop_field = "SUM_"+self.population_field
                arrow_table = ARCPY.da.TableToArrowTable(input_polygon)
                ARCPY.management.Delete(input_polygon)

                if arrow_table.num_rows == 0:
                    ARCPY.AddIDMessage("Error", 110544)
                    raise SystemExit

                updated_table = self._calculate_proportion(arrow_table, sum_pop_field)
                all_strata_used = self._check_table(updated_table, sum_pop_field)
                self.create_random_points(sum_pop_field, updated_table)
                
        #Stratify by contiguous raster region
        else: #self.sampling_method == "STRAT_RAST":
            scratch_polygon_from_raster = ARCPY.CreateScratchName(workspace=ARCPY.env.scratchGDB)
            with ARCPY.EnvManager(snapRaster=self.study_area):
                ARCPY.conversion.RasterToPolygon(
                    in_raster=self.study_area,
                    out_polygon_features=scratch_polygon_from_raster,
                    simplify="NO_SIMPLIFY",
                    raster_field="Value",
                    create_multipart_features="SINGLE_OUTER_PART",
                    max_vertices_per_feature=None
                    )
            
            if ARCPY.management.GetCount(scratch_polygon_from_raster)[0] == '0':
                ARCPY.AddIDMessage("Error", 110544)
                ARCPY.management.Delete(scratch_polygon_from_raster)
                raise SystemExit
            
            if self.strata_count_method == "EQUAL":
                self.create_random_points(self.num_samples_per_strata, scratch_polygon_from_raster)
            else: # self.strata_count_method == "PROP_AREA"
                table = ARCPY.da.TableToArrowTable(scratch_polygon_from_raster)
                updated_table = self._calculate_proportion(table, 'Shape_Area')
                all_strata_used = self._check_table(updated_table, 'Shape_Area')
                self.create_random_points('Shape_Area', updated_table)
        
        if input_is_raster:
            ARCPY.management.Delete(scratch_polygon_from_raster)
        if self.sampling_method == "STRAT_POLY":
            ARCPY.management.Delete(local_copy)
        
        ### Check output is empty ###
        output_count = ARCPY.management.GetCount(self.out_features)
        if output_count[0] == "0":
            ARCPY.AddIDMessage("ERROR", 110544)
        elif not all_strata_used:
            ARCPY.AddIDMessage("WARNING", 110548)
        
        return


# run the script
if __name__ == '__main__':
    parameters = ARCPY.GetParameterInfo()

    sp_sample = SpatialSampling()
    sp_sample.execute()
