
version: "3.9"
services:
  golden-service:
    build: .
    image: terrafusion/grfe:latest
    ports:
      - "${TF_GOLDEN_RATIO_PORT:-8700}:8080"
    environment:
      - RUST_LOG=info
      - TF_GOLDEN_RATIO_PORT=${TF_GOLDEN_RATIO_PORT:-8700}
