apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: terrafusion-argocd
  namespace: argocd
spec:
  server:
    autoscale:
      enabled: true
      hpa:
        maxReplicas: 5
        minReplicas: 2
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: terrafusion-argocd-server
        targetCPUUtilizationPercentage: 50
    grpc:
      ingress:
        enabled: true
        ingressClassName: istio
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: GRPC
    host: argocd.terrafusion.local
    ingress:
      enabled: true
      ingressClassName: istio
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      tls: true
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    route:
      enabled: false
    service:
      type: ClusterIP
  dex:
    enabled: false
  ha:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 128Mi
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 128Mi
  repo:
    autoscale:
      enabled: true
      hpa:
        maxReplicas: 5
        minReplicas: 2
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: terrafusion-argocd-repo-server
        targetCPUUtilizationPercentage: 50
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
    sharding: {}
  applicationSet:
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  notifications:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 128Mi
  rbac:
    defaultPolicy: "role:readonly"
    policy: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      p, role:admin, certificates, *, *, allow
      p, role:admin, accounts, *, *, allow
      p, role:admin, gpgkeys, *, *, allow
      
      p, role:developer, applications, get, terrafusion/*, allow
      p, role:developer, applications, sync, terrafusion/*, allow
      p, role:developer, applications, override, terrafusion/*, allow
      p, role:developer, repositories, get, *, allow
      
      g, terrafusion:admin, role:admin
      g, terrafusion:developer, role:developer
    scopes: "[groups]"