/*
 * ═══════════════════════════════════════════════════════════════
 * SWARM COORDINATION RESULT DTO
 * TerraFusion.Consciousness - AI Swarm Coordination DTOs
 * Government. Transcended.
 * ═══════════════════════════════════════════════════════════════
 */

using System;
using System.Collections.Generic;

namespace TerraFusion.Consciousness.DTOs
{
    /// <summary>
    /// Swarm Coordination Result
    /// Result of coordinating AI agent swarm for multi-factor analysis
    /// </summary>
    public class SwarmCoordinationResult
    {
        /// <summary>
        /// Unique identifier for this coordination task
        /// </summary>
        public string TaskId { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Number of AI agents coordinated
        /// </summary>
        public int AgentCount { get; set; }

        /// <summary>
        /// Total coordination time
        /// </summary>
        public TimeSpan CoordinationTime { get; set; }

        /// <summary>
        /// Indicates if coordination was successful
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// Coordination results and insights from AI swarm
        /// </summary>
        public Dictionary<string, object> Results { get; set; } = new Dictionary<string, object>();

        /// <summary>
        /// AI insights generated by swarm
        /// </summary>
        public List<SwarmInsight> Insights { get; set; } = new List<SwarmInsight>();

        /// <summary>
        /// Swarm confidence score (0-1)
        /// </summary>
        public decimal ConfidenceScore { get; set; }

        /// <summary>
        /// Indicates if quantum optimization was applied
        /// </summary>
        public bool QuantumOptimizationApplied { get; set; }

        /// <summary>
        /// Quantum factor used (if optimization applied)
        /// </summary>
        public int QuantumFactor { get; set; }

        /// <summary>
        /// Coordination timestamp
        /// </summary>
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Error message if coordination failed
        /// </summary>
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// County identifier for this coordination
        /// </summary>
        public string CountyId { get; set; } = string.Empty;

        /// <summary>
        /// Task type that was coordinated
        /// </summary>
        public string TaskType { get; set; } = string.Empty;

        /// <summary>
        /// Agent specializations involved
        /// </summary>
        public List<string> AgentSpecializations { get; set; } = new List<string>();

        /// <summary>
        /// Coordination efficiency percentage
        /// </summary>
        public decimal CoordinationEfficiency { get; set; }

        /// <summary>
        /// Performance metrics for this coordination
        /// </summary>
        public SwarmPerformanceMetrics PerformanceMetrics { get; set; } = new SwarmPerformanceMetrics();
    }

    /// <summary>
    /// Swarm Insight Model
    /// Individual insight from AI agent swarm
    /// </summary>
    public class SwarmInsight
    {
        public string InsightType { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public decimal Impact { get; set; }
        public int AgentCount { get; set; }
        public decimal Confidence { get; set; }
        public string Severity { get; set; } = "Medium";
        public Dictionary<string, object> Data { get; set; } = new Dictionary<string, object>();
    }

    /// <summary>
    /// Swarm Performance Metrics
    /// Performance statistics for swarm coordination
    /// </summary>
    public class SwarmPerformanceMetrics
    {
        public TimeSpan AverageAgentResponseTime { get; set; }
        public decimal AgentSynchronizationScore { get; set; }
        public int TotalAgentInteractions { get; set; }
        public decimal ResourceUtilization { get; set; }
        public int FailedAgentCount { get; set; }
        public decimal SuccessRate { get; set; }
    }
}
