

create procedure PenpadGetTableIDs

as
	/*
		Returns the list of all columns in the
		database that are generated by a "next ID"
	*/
	select
		szTableName, szColumnName, szTableRef, szColumnRef
	from penpad_table_ids
	order by
		szTableName, szColumnName, szTableRef, szColumnRef

GO

