CREATE VIEW [dbo].[_property_vw]
AS
SELECT dbo.property.prop_id, dbo.property_val.prop_val_yr, 
    dbo.property_val.sup_num, dbo.property.prop_type_cd, 
    dbo.property.prop_create_dt, dbo.property.ref_id1, 
    dbo.property.ref_id2, dbo.property.geo_id, 
    dbo.property.prop_cmnt, dbo.property.prop_sic_cd, 
    dbo.property.dba_name, dbo.property.alt_dba_name, 
    dbo.property_val.last_appraiser_id, dbo.property.exmpt_reset, 
    dbo.property.gpm_irrig, dbo.property_val.last_appraisal_dt, 
    dbo.property_val.next_appraisal_dt, 
    dbo.property_val.next_appraisal_rsn, dbo.property.utilities, 
    dbo.property.topography, dbo.property.road_access, 
    dbo.property.other, dbo.property.zoning, dbo.property.remarks, 
    dbo.property_val.next_appraiser_id, dbo.property.state_cd, 
    dbo.property.mass_created_from, dbo.property_val.abs_subdv_cd, 
    dbo.property_val.hood_cd, dbo.property_val.block, 
    dbo.property_val.tract_or_lot, dbo.property_val.mbl_hm_park, 
    dbo.property_val.mbl_hm_space, dbo.property_val.auto_build_legal, 
    dbo.property_val.rgn_cd, dbo.property_val.subset_cd, 
    dbo.property_val.map_id, ----dbo.property_val.shared_pct, 
   ----- dbo.property_val.chg_notice, dbo.property_val.chg_notice_type, 
   ----- dbo.property_val.appraisal_errors, 
    dbo.property_val.last_appraisal_yr, 
    dbo.property_val.image_path, dbo.property_val.land_hstd_val, 
    dbo.property_val.land_non_hstd_val, 
    dbo.property_val.imprv_hstd_val, 
    dbo.property_val.imprv_non_hstd_val, 
    dbo.property_val.appraised_val, 
    dbo.property_val.assessed_val, dbo.property_val.market, 
    dbo.property_val.ag_use_val, dbo.property_val.ag_market, 
    dbo.property_val.ag_loss, dbo.property_val.ag_late_loss, 
    dbo.property_val.timber_78, dbo.property_val.timber_market, 
    dbo.property_val.timber_use, dbo.property_val.timber_loss, 
    dbo.property_val.timber_late_loss, 
    dbo.property_val.rendered_val, dbo.property_val.rendered_yr, 
    dbo.property_val.mineral_int_pct, 
    dbo.property_val.orig_appraised_val, 
    dbo.property_val.ten_percent_cap, 
    dbo.property_val.legal_desc, dbo.property_val.legal_desc_2, 
    dbo.property_val.eff_size_acres, 
    dbo.property_val.legal_acreage, dbo.property_val.vit_flag, 
    dbo.property_val.recalc_flag, 
    dbo.property_val.vit_declaration_filed_dt, 
    dbo.property_val.prev_sup_num, dbo.property_val.sup_cd, 
    dbo.property_val.sup_desc, dbo.property_val.sup_dt, 
    dbo.property_val.sup_action, 
    dbo.property_val.appr_company_id, 
    dbo.property_val.prop_inactive_dt, 
    dbo.property_val.hscap_qualify_yr, 
    dbo.property_val.hscap_override_prevhsval_flag, 
    dbo.property_val.hscap_prevhsval, 
    dbo.property_val.hscap_prevhsval_pacsuser, 
    dbo.property_val.hscap_prevhsval_date, 
    dbo.property_val.hscap_prevhsval_comment, 
    dbo.property_val.hscap_override_newhsval_flag, 
    dbo.property_val.hscap_newhsval, 
    dbo.property_val.hscap_newhsval_pacsuser, 
    dbo.property_val.hscap_newhsval_comment, 
    dbo.property_val.hscap_newhsval_date, 
    dbo.property_val.last_appraisal_yr AS Expr1, 
    dbo.property_val.oil_wells, dbo.property_val.irr_wells, 
    dbo.property_val.irr_acres, dbo.property_val.irr_capacity, 
    dbo.property_val.oil_wells_apply_adjust, 
    dbo.property_val.tif_land_val, dbo.property_val.tif_imprv_val, 
    dbo.property_val.tif_flag
FROM dbo.property INNER JOIN
    dbo.property_val ON 
    dbo.property.prop_id = dbo.property_val.prop_id

GO

