import { useState, useCallback } from 'react';

interface AICompletionRequest {
  code: string;
  language: string;
  context?: string;
  projectType?: string;
}

interface AICompletionResponse {
  suggestions: AICompletion[];
  confidence: number;
  processingTime: number;
}

interface AICompletion {
  label: string;
  insertText: string;
  documentation: string;
  confidence: number;
  filterText: string;
  additionalTextEdits?: any[];
  kind: 'function' | 'variable' | 'class' | 'module' | 'snippet' | 'keyword';
}

export const useAICompletion = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const getAICompletion = useCallback(
    async (
      code: string,
      language: string,
      context: string = 'TerraFusion Government Development'
    ): Promise<AICompletion[]> => {
      setIsLoading(true);
      setError(null);

      try {
        const response = await fetch('/api/ide/ai/completion', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${localStorage.getItem('terrafusion-token')}`,
          },
          body: JSON.stringify({
            code,
            language,
            context,
            aiAgents: 1008, // Use full AI swarm
            governmentCompliance: true,
            securityClearance: 'GOVERNMENT_APPROVED',
          } as AICompletionRequest),
        });

        if (!response.ok) {
          throw new Error(`AI completion failed: ${response.statusText}`);
        }

        const data: AICompletionResponse = await response.json();

        // Enhance completions with TerraFusion-specific intelligence
        const enhancedSuggestions = data.suggestions.map((suggestion) => ({
          ...suggestion,
          documentation: `${suggestion.documentation}\n\n🤖 Generated by TerraFusion AI Swarm (${data.confidence}% confidence)`,
          detail: `TerraFusion AI (${suggestion.confidence}% confidence)`,
        }));

        return enhancedSuggestions;
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown AI completion error';
        setError(errorMessage);
        console.error('AI Completion Error:', err);

        // Return fallback completions
        return getFallbackCompletions(language);
      } finally {
        setIsLoading(false);
      }
    },
    []
  );

  const getGovernmentAIAssistance = useCallback(
    async (
      selectedCode: string,
      language: string,
      assistanceType: 'explain' | 'optimize' | 'secure' | 'test' | 'document'
    ) => {
      setIsLoading(true);
      setError(null);

      try {
        const response = await fetch('/api/ide/ai/assist', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${localStorage.getItem('terrafusion-token')}`,
          },
          body: JSON.stringify({
            code: selectedCode,
            language,
            assistanceType,
            governmentStandards: ['FISMA', 'NIST', 'Section508'],
            aiSwarmSize: 1008,
          }),
        });

        if (!response.ok) {
          throw new Error(`AI assistance failed: ${response.statusText}`);
        }

        const assistance = await response.json();
        return assistance;
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown AI assistance error';
        setError(errorMessage);
        console.error('AI Assistance Error:', err);
        throw err;
      } finally {
        setIsLoading(false);
      }
    },
    []
  );

  const generateGovernmentBoilerplate = useCallback(
    async (
      templateType: 'controller' | 'service' | 'model' | 'test' | 'agent',
      language: string,
      options: {
        complianceLevel: 'RED' | 'YELLOW' | 'GREEN';
        auditRequired: boolean;
        securityFeatures: string[];
      }
    ) => {
      try {
        const response = await fetch('/api/ide/ai/generate', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${localStorage.getItem('terrafusion-token')}`,
          },
          body: JSON.stringify({
            templateType,
            language,
            options,
            governmentGrade: true,
            aiSwarmOptimization: true,
          }),
        });

        if (!response.ok) {
          throw new Error(`Code generation failed: ${response.statusText}`);
        }

        return await response.json();
      } catch (err) {
        console.error('Government Boilerplate Generation Error:', err);
        throw err;
      }
    },
    []
  );

  return {
    getAICompletion,
    getGovernmentAIAssistance,
    generateGovernmentBoilerplate,
    isLoading,
    error,
  };
};

// Fallback completions when AI service is unavailable
const getFallbackCompletions = (language: string): AICompletion[] => {
  const common: AICompletion[] = [
    {
      label: 'TerraFusion Logger',
      insertText: 'const logger = new TerraFusionLogger({ compliance: true });',
      documentation: 'Government-compliant logger with audit trail',
      confidence: 95,
      filterText: 'logger',
      kind: 'snippet',
    },
    {
      label: 'Security Context',
      insertText: 'const securityContext = await SecurityContext.getCurrent();',
      documentation: 'Get current security context with FISMA compliance',
      confidence: 90,
      filterText: 'security',
      kind: 'snippet',
    },
    {
      label: 'Audit Trail',
      insertText:
        'await auditService.log({ action: "${1:action}", user: user.id, timestamp: new Date() });',
      documentation: 'Log action for government audit requirements',
      confidence: 95,
      filterText: 'audit',
      kind: 'snippet',
    },
  ];

  switch (language) {
    case 'typescript':
    case 'javascript':
      return [
        ...common,
        {
          label: 'Government Component',
          insertText: [
            'interface ${1:ComponentName}Props {',
            '  complianceLevel: "RED" | "YELLOW" | "GREEN";',
            '  auditRequired?: boolean;',
            '}',
            '',
            'export const ${1:ComponentName}: React.FC<${1:ComponentName}Props> = ({',
            '  complianceLevel,',
            '  auditRequired = true',
            '}) => {',
            '  const { user } = useAuth();',
            '  const auditService = useAuditService();',
            '  ',
            '  useEffect(() => {',
            '    if (auditRequired) {',
            '      auditService.logAccess("${1:ComponentName}", user.id);',
            '    }',
            '  }, []);',
            '  ',
            '  return (',
            '    <div data-compliance={complianceLevel}>',
            '      ${2:// Component content}',
            '    </div>',
            '  );',
            '};',
          ].join('\n'),
          documentation: 'Government-compliant React component with audit logging',
          confidence: 90,
          filterText: 'component',
          kind: 'snippet',
        },
      ];

    case 'csharp':
      return [
        ...common,
        {
          label: 'Government API Controller',
          insertText: [
            '[Authorize(Roles = "GovernmentUser")]',
            '[ApiController]',
            '[Route("api/[controller]")]',
            'public class ${1:Controller}Controller : ControllerBase',
            '{',
            '    private readonly IAuditService _auditService;',
            '    private readonly ILogger<${1:Controller}Controller> _logger;',
            '    ',
            '    public ${1:Controller}Controller(',
            '        IAuditService auditService,',
            '        ILogger<${1:Controller}Controller> logger)',
            '    {',
            '        _auditService = auditService;',
            '        _logger = logger;',
            '    }',
            '    ',
            '    [HttpGet]',
            '    [ProducesResponseType(typeof(${2:ResponseType}), 200)]',
            '    public async Task<IActionResult> Get()',
            '    {',
            '        var auditContext = await _auditService.StartAudit();',
            '        try',
            '        {',
            '            ${3:// Implementation}',
            '            await _auditService.LogSuccess(auditContext);',
            '            return Ok();',
            '        }',
            '        catch (Exception ex)',
            '        {',
            '            await _auditService.LogError(auditContext, ex);',
            '            return StatusCode(500);',
            '        }',
            '    }',
            '}',
          ].join('\n'),
          documentation: 'FISMA-compliant API controller with audit logging',
          confidence: 95,
          filterText: 'controller',
          kind: 'snippet',
        },
      ];

    case 'python':
      return [
        ...common,
        {
          label: 'TerraFusion AI Agent',
          insertText: [
            'class ${1:AgentName}(TerraFusionAgent):',
            '    """Government-compliant AI agent with audit capabilities"""',
            '    ',
            '    def __init__(self, agent_id: str, security_clearance: str = "GREEN"):',
            '        super().__init__(agent_id)',
            '        self.security_clearance = security_clearance',
            '        self.audit_service = AuditService()',
            '        self.compliance_validator = ComplianceValidator()',
            '    ',
            '    async def execute_task(self, task: Task) -> TaskResult:',
            '        """Execute task with government compliance validation"""',
            '        await self.audit_service.log_task_start(task)',
            '        ',
            '        # Validate compliance before execution',
            '        compliance_check = await self.compliance_validator.validate(task)',
            '        if not compliance_check.is_compliant:',
            '            raise ComplianceError(compliance_check.violations)',
            '        ',
            '        try:',
            '            result = await self._process_task(task)',
            '            await self.audit_service.log_task_success(task, result)',
            '            return result',
            '        except Exception as e:',
            '            await self.audit_service.log_task_error(task, e)',
            '            raise',
            '    ',
            '    async def _process_task(self, task: Task) -> TaskResult:',
            '        """Override this method with agent-specific logic"""',
            '        ${2:pass}',
          ].join('\n'),
          documentation: 'Government-compliant AI agent with FISMA audit trail',
          confidence: 95,
          filterText: 'agent',
          kind: 'snippet',
        },
      ];

    case 'rust':
      return [
        ...common,
        {
          label: 'Government Service',
          insertText: [
            'use terrafusion_core::{AuditService, SecurityContext, ComplianceLevel};',
            'use tokio::sync::RwLock;',
            'use std::sync::Arc;',
            '',
            '#[derive(Debug, Clone)]',
            'pub struct ${1:ServiceName} {',
            '    audit_service: Arc<AuditService>,',
            '    security_context: Arc<RwLock<SecurityContext>>,',
            '    compliance_level: ComplianceLevel,',
            '}',
            '',
            'impl ${1:ServiceName} {',
            '    pub fn new(compliance_level: ComplianceLevel) -> Self {',
            '        Self {',
            '            audit_service: Arc::new(AuditService::new()),',
            '            security_context: Arc::new(RwLock::new(SecurityContext::new())),',
            '            compliance_level,',
            '        }',
            '    }',
            '    ',
            '    pub async fn execute_with_audit<F, T>(',
            '        &self,',
            '        operation: F,',
            '        context: &str,',
            '    ) -> Result<T, Box<dyn std::error::Error>>',
            '    where',
            '        F: FnOnce() -> Result<T, Box<dyn std::error::Error>>,',
            '    {',
            '        let audit_id = self.audit_service.start_audit(context).await?;',
            '        ',
            '        match operation() {',
            '            Ok(result) => {',
            '                self.audit_service.log_success(audit_id).await?;',
            '                Ok(result)',
            '            }',
            '            Err(e) => {',
            '                self.audit_service.log_error(audit_id, &e).await?;',
            '                Err(e)',
            '            }',
            '        }',
            '    }',
            '}',
          ].join('\n'),
          documentation: 'Government-compliant Rust service with audit logging',
          confidence: 90,
          filterText: 'service',
          kind: 'snippet',
        },
      ];

    default:
      return common;
  }
};
