global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@terrafusion.local'

route:
  group_by: ['alertname', 'component']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    - match:
        component: ai-swarm
      receiver: 'ai-swarm-alerts'
      continue: true
    - match:
        component: backend
      receiver: 'backend-alerts'
      continue: true

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/critical'
    email_configs:
      - to: 'admin@terrafusion.local'
        send_resolved: true

  - name: 'ai-swarm-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/ai-swarm'
    email_configs:
      - to: 'ai-team@terrafusion.local'
        send_resolved: true

  - name: 'backend-alerts'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/backend'
    email_configs:
      - to: 'devops@terrafusion.local'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']
