create view comm_bldg_pv as 
SELECT [lrsn] as prop_id
      ,[extension]
      ,[bldg_section]
      ,[last_update]
      ,[status]
      ,[pricing_key]
      ,[number_floors]
      ,[total_area]
      ,[party_walls]
      ,[sqft_rate1]
      ,[subtotal1]
      ,[plumb_value1]
      ,[spfeat_value1]
      ,[exfeat_value1]
      ,[base_value1]
      ,[grade]
      ,[reproduction_cost1]
      ,[bldg_flag1]
      ,[bldg_text1]
      ,[bldg_flag2]
      ,[misc_value]
      ,[misc_description]
      ,[bldg_int1]
      ,[bldg_int2]
      ,[eff_year]
      ,[roof_code1]
      ,[roof_pct1]
      ,[roof_code2]
      ,[roof_pct2]
      ,[roof_code3]
      ,[roof_pct3]
      ,[roof_code4]
      ,[roof_pct4]
      ,[roof_ins_pct]
      ,[wall_ins_pct]
      ,[number_units]
      ,[avg_unit_size]
      ,[improvement_id]
      ,[imp_line_flag]
      ,[sqft_rate3]
      ,[subtotal3]
      ,[plumb_value3]
      ,[spfeat_value3]
      ,[exfeat_value3]
      ,[base_value3]
      ,[reproduction_cost3]
      ,[mkt_bldg_type]
  FROM [cnv_src_benton_2_14_2017].[dbo].[comm_bldg]

GO

