
create view VerifyPersonalPropertyVal_vw
as
select 
	pv.prop_id  ,
	pv.prop_val_yr as year,
	pv.prop_val ,
	pv.chg_dt  ,
	pv.notice_mail_dt  ,
	pv.land_hstd_val ,
	pv.land_non_hstd_val ,
	pv.imprv_hstd_val ,
	pv.imprv_non_hstd_val ,
	pv.appraised_val ,
	pv.assessed_val ,
	pv.market ,
	pv.ag_use_val ,
	pv.ag_market ,
	pv.freeze_ceiling  ,
	pv.freeze_yr  ,
	pv.ag_loss ,
	pv.ag_late_loss ,
	pv.timber_78 ,
	pv.timber_market ,
	pv.timber_use ,
	pv.timber_loss ,
	pv.timber_late_loss ,
	pv.rendered_val ,
	pv.rendered_yr  ,
	pv.new_val ,
	pv.new_yr  ,
	pv.mineral_int_pct  ,
	pv.orig_appraised_val ,
	pv.ten_percent_cap ,
	pv.sup_num  ,
	pv.legal_desc  ,
	pv.legal_desc_2  ,
	pv.abated_pct  ,
	pv.abated_amt ,
	pv.abated_yr  ,
	pv.eff_size_acres  ,
	pv.shared_prop_val ,
	pv.shared_prop_cad_code  ,
	pv.legal_acreage  ,
	pv.vit_flag  ,
	pv.recalc_flag  ,
	pv.vit_declaration_filed_dt  ,
	pv.prev_sup_num  ,
	pv.sup_cd ,
	pv.sup_desc  ,
	pv.sup_dt  ,
	pv.sup_action  ,
	pv.appr_company_id  ,
	pv.prop_inactive_dt  ,
	pv.hscap_qualify_yr  ,
	pv.hscap_override_prevhsval_flag  ,
	pv.hscap_prevhsval ,
	pv.hscap_prevhsval_pacsuser ,
	pv.hscap_prevhsval_comment  ,
	pv.hscap_prevhsval_date  ,
	pv.hscap_override_newhsval_flag  ,
	pv.hscap_newhsval ,
	pv.hscap_newhsval_pacsuser ,
	pv.hscap_newhsval_comment  ,
	pv.hscap_newhsval_date  ,
	pv.last_appraisal_yr  ,
	pv.oil_wells ,
	pv.irr_wells ,
	pv.irr_acres  ,
	pv.irr_capacity ,
	pv.oil_well_apply_adjust  ,
	pv.oil_wells_apply_adjust  ,
	pv.tif_imprv_val ,
	pv.tif_land_val ,
	pv.tif_flag  ,
	pv.accept_create_id  ,
	pv.accept_create_dt  ,
	pv.abs_subdv_cd  ,
	pv.hood_cd  ,
	pv.block  ,
	pv.tract_or_lot  ,
	pv.mbl_hm_park  ,
	pv.mbl_hm_space  ,
	pv.rgn_cd  ,
	pv.subset_cd  ,
	pv.map_id  ,
	pv.auto_build_legal  ,
	pv.image_path  ,
	pv.hscap_prev_reappr_yr  ,
	pv.hscap_base_yr  ,
	pv.hscap_base_yr_override  ,
	pv.hscap_base_yr_pacsuser ,
	pv.hscap_base_yr_comment  ,
	pv.hscap_base_yr_date  ,
	pv.mapsco  ,
	pv.cost_value ,
	pv.income_value ,
	pv.shared_value ,
	pv.appr_method  ,
	pv.cost_land_hstd_val ,
	pv.cost_land_non_hstd_val ,
	pv.cost_imprv_hstd_val ,
	pv.cost_imprv_non_hstd_val ,
	pv.cost_market ,
	pv.cost_ag_use_val ,
	pv.cost_ag_market ,
	pv.cost_ag_loss ,
	pv.cost_timber_market ,
	pv.cost_timber_use ,
	pv.cost_timber_loss ,
	pv.income_land_hstd_val ,
	pv.income_land_non_hstd_val ,
	pv.income_imprv_hstd_val ,
	pv.income_imprv_non_hstd_val ,
	pv.income_market ,
	pv.income_ag_use_val ,
	pv.income_ag_market ,
	pv.income_ag_loss ,
	pv.income_timber_market ,
	pv.income_timber_use ,
	pv.income_timber_loss ,
	pv.shared_land_hstd_val ,
	pv.shared_land_non_hstd_val ,
	pv.shared_imprv_hstd_val ,
	pv.shared_imprv_non_hstd_val ,
	pv.shared_market ,
	pv.shared_ag_use_val ,
	pv.shared_ag_market ,
	pv.shared_ag_loss ,
	pv.shared_timber_market ,
	pv.shared_timber_use ,
	pv.shared_timber_loss ,
	pv.last_appraiser_id  ,
	pv.next_appraiser_id  ,
	pv.last_appraisal_dt  ,
	pv.next_appraisal_dt  ,
	pv.next_appraisal_rsn  ,
	pv.value_appraiser_id  ,
	pv.land_appraiser_id  ,
	pv.sub_market_cd  ,
	pv.property_use_cd  ,
	pv.visibility_access_cd  ,
	pv.last_pacs_user_id  ,
	pv.recalc_dt  ,
	pv.new_val_hs ,
	pv.new_val_nhs ,
	pv.new_val_p ,
	pv.owner_update_dt  ,
	pv.agent_update_dt  ,
	pv.penpad_comments  ,
	pv.last_actual_appraisal_dt  ,
	pv.last_owner_id  ,
	pv.cad_value_option  ,
	pv.condo_pct ,
	pv.reviewed_dt  ,
	pv.reviewed_appraiser  ,
	pv.arb_land_hstd_val ,
	pv.arb_land_non_hstd_val ,
	pv.arb_imprv_hstd_val ,
	pv.arb_imprv_non_hstd_val ,
	pv.arb_market ,
	pv.arb_ag_use_val ,
	pv.arb_ag_market ,
	pv.arb_timber_market ,
	pv.arb_timber_use ,
	pv.arb_timber_loss ,
	pv.shared_other_val,
	pv.udi_parent ,
	pv.udi_parent_prop_id  ,
	pv.udi_status ,
	pv.udi_child_legal_desc ,
	pv.image_id  ,
	pv.dist_land_hstd_val ,
	pv.dist_land_non_hstd_val  ,
	pv.dist_imprv_hstd_val ,
	pv.dist_imprv_non_hstd_val ,
	pv.dist_market ,
	pv.dist_ag_use_val ,
	pv.dist_ag_market ,
	pv.dist_timber_market ,
	pv.dist_timber_use ,
	pv.dist_timber_loss,
	0 as owner_id,
	0 as entity_id,
	'PP_AV_MV' as check_cd,
	0 as ic_ref_id
from property_val as pv with(nolock)

inner join property as p with(nolock) on
p.prop_id=pv.prop_id

where isnull(prop_type_cd,'') IN ('P', 'MN') 
and assessed_val <> market 
and prop_inactive_dt is null
and isnull(udi_parent,'')=''

GO

