from typing import Literal

from .base import *
from .gdb import *
from .nd import *
from .tn import *
from .un import *

DescribeDataTypes = Literal[
    "ArcInfoItem",
    "ArcInfoTable",
    "BIMFileWorkspace",
    "CadDrawingDataset",
    "CadFeatureClass",
    "CadastralFabric",
    "Coverage",
    "CoverageFeatureClass",
    "DbaseTable",
    "FeatureClass",
    "FeatureSet",
    "File",
    "Folder",
    "GALayer",
    "GDBFeatureClass",
    "GDBTable",
    "GeometricNetwork",
    "LasDataset",
    "Layer",
    "LocationReferencingDataset",
    "MapDocument",
    "MosaicDataset",
    "NALayer",
    "NetworkDataset",
    "ParcelFabric",
    "ProjectionFile",
    "RasterBand",
    "RasterCatalog",
    "RasterDataset",
    "RecordSet",
    "RelationshipClass",
    "RepresentationClass",
    "SDCFeatureClass",
    "SchematicDataset",
    "SchematicDiagram",
    "SchematicFolder",
    "ShapeFile",
    "TIN",
    "Table",
    "TableView",
    "TextFile",
    "Tool",
    "Toolbox",
    "Topology",
    "TraceNetwork",
    "UtilityNetwork",
    "VPFCoverage",
    "VPFFeatureClass",
    "VPFTable",
    "Workspace",
]
