// WARNING:
// This file is generated by a grunt build task.
// Do not modify it by hand.

/**
 * Messages from `node_modules/@arcgis/core/assets/esri/widgets/Legend/t9n/Legend_en.json`.
 */
export default interface LegendMessages {
  widgetLabel: string;
  points: string;
  lines: string;
  polygons: string;
  creatingLegend: string;
  noLegend: string;
  dotValue: string;
  currentObservations: string;
  previousObservations: string;
  high: string;
  low: string;
  esriMetersPerSecond: string;
  esriKilometersPerHour: string;
  esriKnots: string;
  esriFeetPerSecond: string;
  esriMilesPerHour: string;
  showNormField: string;
  showNormPct: string;
  showRatio: string;
  showRatioPercent: string;
  showRatioPercentTotal: string;
  band0: string;
  band1: string;
  band2: string;
  band3: string;
  red: string;
  green: string;
  blue: string;
  clusterCountTitle: string;
  previewAriaLabel: string;
  previewTemplateAriaLabel: string;
  previewColorRampAriaLabel: string;
  previewPieChartAriaLabel: string;
  previewRelationshipRampAriaLabel: string;
}
