{
 "title": "Database Metrics",
 "tags": [
  "terrafusion",
  "database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SQL Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqlalchemy_engine_Engine_info_total[5m])",
     "legendFormat": "SQL Queries"
    }
   ]
  },
  {
   "title": "Database Warning Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqlalchemy_engine_Engine_warning_total[5m])",
     "legendFormat": "SQL Warnings"
    }
   ]
  },
  {
   "title": "Database Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sqlalchemy_engine_Engine_error_total[5m])",
     "legendFormat": "SQL Errors"
    }
   ]
  },
  {
   "title": "Database Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(sqlalchemy_pool_size[5m]))",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum(rate(sqlalchemy_pool_checked_in[5m]))",
     "legendFormat": "Checked In"
    },
    {
     "expr": "sum(rate(sqlalchemy_pool_checked_out[5m]))",
     "legendFormat": "Checked Out"
    }
   ]
  }
 ]
}