// ═══════════════════════════════════════════════════════════════════════════════
// 🔴 PHASE 29: SystemGPT Atlas Real-Time Telemetry Models
// Live streaming DTOs for SSE-based health updates
// "Government. Transcended."
// ═══════════════════════════════════════════════════════════════════════════════

namespace TerraFusion.AI.Models;

/// <summary>
/// Phase 29: Batch event containing live telemetry for all counties.
/// Sent via SSE stream at configurable intervals.
/// </summary>
public sealed class SystemGptAtlasLiveEventDto
{
    /// <summary>Schema version for forward compatibility.</summary>
    public string Version { get; init; } = "1.0";

    /// <summary>Event type identifier for SSE routing.</summary>
    public string EventType { get; init; } = "atlas_county_batch";

    /// <summary>Server-side timestamp when this event was generated.</summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>Live telemetry for all counties in this batch.</summary>
    public IReadOnlyList<SystemGptAtlasLiveCountyEventDto> Counties { get; init; }
        = Array.Empty<SystemGptAtlasLiveCountyEventDto>();
}

/// <summary>
/// Phase 29: Live telemetry for a single county.
/// Includes real-time metrics and classified health state.
/// </summary>
public sealed class SystemGptAtlasLiveCountyEventDto
{
    /// <summary>County code (e.g., "benton", "yakima").</summary>
    public string CountyId { get; init; } = string.Empty;

    /// <summary>Computed health score (0.0 to 1.0).</summary>
    public double HealthScore { get; init; }

    /// <summary>
    /// Classified health state based on thresholds.
    /// One of: "healthy", "warning", "critical", "offline"
    /// </summary>
    public string HealthState { get; init; } = "healthy";

    /// <summary>Whether RAG index is active and serving queries.</summary>
    public bool RagActive { get; init; }

    /// <summary>Whether a guardrail was recently triggered.</summary>
    public bool GuardrailTriggered { get; init; }

    /// <summary>Current number of active requests being processed.</summary>
    public int ActiveRequests { get; init; }

    /// <summary>P95 latency in milliseconds over recent window.</summary>
    public double P95LatencyMs { get; init; }

    /// <summary>Error rate percentage over recent window.</summary>
    public double ErrorRatePercent { get; init; }

    /// <summary>
    /// Active alerts generated by threshold classification.
    /// Empty when all metrics are within healthy bounds.
    /// </summary>
    public IReadOnlyList<string> ActiveAlerts { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Phase 29: Configurable thresholds for health state classification.
/// Bound via IOptions&lt;SystemGptAtlasThresholds&gt;.
/// </summary>
public sealed class SystemGptAtlasThresholds
{
    /// <summary>Configuration section name for appsettings binding.</summary>
    public const string SectionName = "SystemGptAtlas:Thresholds";

    // ─────────────────────────────────────────────────────────────────────────
    // Health Score Thresholds
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Health score below this triggers Warning state.</summary>
    public double WarningHealthScore { get; set; } = 0.80;

    /// <summary>Health score below this triggers Critical state.</summary>
    public double CriticalHealthScore { get; set; } = 0.60;

    // ─────────────────────────────────────────────────────────────────────────
    // Error Rate Thresholds (%)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>Error rate above this triggers Warning state.</summary>
    public double WarningErrorRatePercent { get; set; } = 1.0;

    /// <summary>Error rate above this triggers Critical state.</summary>
    public double CriticalErrorRatePercent { get; set; } = 5.0;

    // ─────────────────────────────────────────────────────────────────────────
    // Latency Thresholds (ms)
    // ─────────────────────────────────────────────────────────────────────────

    /// <summary>P95 latency above this triggers Warning state.</summary>
    public double WarningP95Ms { get; set; } = 300;

    /// <summary>P95 latency above this triggers Critical state.</summary>
    public double CriticalP95Ms { get; set; } = 1000;
}

/// <summary>
/// Phase 29: Configuration options for the live streaming service.
/// </summary>
public sealed class SystemGptAtlasLiveOptions
{
    /// <summary>Configuration section name for appsettings binding.</summary>
    public const string SectionName = "SystemGptAtlas:Live";

    /// <summary>Interval between SSE events in milliseconds.</summary>
    public int IntervalMs { get; set; } = 1000;

    /// <summary>Maximum number of connection retries on error.</summary>
    public int MaxRetries { get; init; } = 5;

    /// <summary>Delay between retries in milliseconds.</summary>
    public int RetryDelayMs { get; init; } = 5000;
}

/// <summary>
/// Phase 29: Raw metrics from telemetry source before classification.
/// Internal type used between TelemetrySource and Classifier.
/// </summary>
public sealed class RawCountyMetrics
{
    public string CountyId { get; init; } = string.Empty;
    public double HealthScore { get; init; }
    public bool RagActive { get; init; }
    public bool GuardrailTriggered { get; init; }
    public int ActiveRequests { get; init; }
    public double P95LatencyMs { get; init; }
    public double ErrorRatePercent { get; init; }
}

/// <summary>
/// Phase 29: Result of health classification including state and alerts.
/// </summary>
public sealed class ClassificationResult
{
    /// <summary>
    /// Classified health state: "healthy", "warning", "critical", or "offline".
    /// </summary>
    public required string HealthState { get; init; }

    /// <summary>
    /// Generated alerts based on threshold violations.
    /// </summary>
    public required IReadOnlyList<string> ActiveAlerts { get; init; }
}
