<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TerraFusion.API/TerraFusion.API.csproj" />
    <ProjectReference Include="../TerraFusion.Core/TerraFusion.Core.csproj" />
    <ProjectReference Include="../TerraFusion.Data/TerraFusion.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Fixtures/" />
    <Folder Include="Mocks/" />
    <Folder Include="Unit/" />
    <Folder Include="Integration/" />
    <Folder Include="Acceptance/" />
  </ItemGroup>

</Project>
