import {
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  Clock,
  Copy,
  Download,
  Edit,
  FileText,
  Filter,
  HelpCircle,
  Info,
  Loader2,
  MoreVertical,
  Plus,
  RefreshCw,
  Search,
  Settings,
  SlidersHorizontal,
  Trash,
  User,
  X,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: FileText,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  add: Plus,
  trash: Trash,
  settings: Settings,
  alert: CircleAlert,
  info: Info,
  help: HelpCircle,
  user: User,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  edit: Edit,
  copy: Copy,
  download: Download,
  more: MoreVertical,
  search: Search,
  filter: Filter,
  sliders: SlidersHorizontal,
  refresh: RefreshCw,
  clock: Clock,
};