CREATE TABLE [dbo].[_james_imprv_20240611] (
    [prop_id]                               INT              NOT NULL,
    [prop_val_yr]                           NUMERIC (4)      NOT NULL,
    [imprv_id]                              INT              NOT NULL,
    [sup_num]                               INT              NOT NULL,
    [sale_id]                               INT              NOT NULL,
    [imprv_type_cd]                         CHAR (5)         NOT NULL,
    [imprv_sl_locked]                       CHAR (1)         NOT NULL,
    [primary_imprv]                         CHAR (1)         NULL,
    [imprv_state_cd]                        CHAR (5)         NOT NULL,
    [imprv_homesite]                        CHAR (1)         NULL,
    [imprv_desc]                            VARCHAR (255)    NULL,
    [imprv_val]                             NUMERIC (14)     NULL,
    [misc_cd]                               CHAR (5)         NULL,
    [imp_new_yr]                            NUMERIC (4)      NULL,
    [imp_new_val]                           NUMERIC (14)     NULL,
    [imp_new_val_override]                  CHAR (1)         NULL,
    [original_val]                          NUMERIC (14)     NULL,
    [base_val]                              NUMERIC (14)     NULL,
    [calc_val]                              NUMERIC (14)     NULL,
    [adjusted_val]                          NUMERIC (14)     NULL,
    [living_area_up]                        NUMERIC (14, 2)  NULL,
    [err_flag]                              CHAR (1)         NULL,
    [imprv_image_url]                       VARCHAR (50)     NULL,
    [imprv_cmnt]                            VARCHAR (1000)   NULL,
    [mbl_hm_make]                           VARCHAR (100)    NULL,
    [mbl_hm_model]                          VARCHAR (100)    NULL,
    [mbl_hm_sn]                             VARCHAR (100)    NULL,
    [mbl_hm_hud_num]                        VARCHAR (100)    NULL,
    [mbl_hm_title_num]                      VARCHAR (100)    NULL,
    [imp_new_pc]                            NUMERIC (14)     NULL,
    [flat_val]                              NUMERIC (14)     NULL,
    [value_type]                            CHAR (1)         NULL,
    [imprv_adj_amt]                         NUMERIC (14)     NULL,
    [imprv_adj_factor]                      NUMERIC (8, 6)   NULL,
    [imprv_mass_adj_factor]                 NUMERIC (8, 6)   NULL,
    [imprv_val_source]                      CHAR (1)         NULL,
    [economic_pct]                          NUMERIC (5, 2)   NULL,
    [physical_pct]                          NUMERIC (5, 2)   NULL,
    [functional_pct]                        NUMERIC (5, 2)   NULL,
    [economic_cmnt]                         VARCHAR (255)    NULL,
    [physical_cmnt]                         VARCHAR (255)    NULL,
    [functional_cmnt]                       VARCHAR (255)    NULL,
    [effective_yr_blt]                      NUMERIC (4)      NULL,
    [percent_complete]                      NUMERIC (5, 2)   NULL,
    [percent_complete_cmnt]                 VARCHAR (255)    NULL,
    [ref_id1]                               VARCHAR (50)     NULL,
    [num_imprv]                             INT              NULL,
    [mbl_hm_sn_2]                           VARCHAR (100)    NULL,
    [mbl_hm_sn_3]                           VARCHAR (100)    NULL,
    [mbl_hm_hud_num_2]                      VARCHAR (100)    NULL,
    [mbl_hm_hud_num_3]                      VARCHAR (100)    NULL,
    [stories]                               VARCHAR (5)      NOT NULL,
    [arb_val]                               NUMERIC (14)     NULL,
    [dep_pct]                               NUMERIC (5, 2)   NULL,
    [dep_cmnt]                              VARCHAR (255)    NULL,
    [dist_val]                              NUMERIC (14)     NOT NULL,
    [tsRowVersion]                          ROWVERSION       NOT NULL,
    [hs_pct]                                NUMERIC (13, 10) NULL,
    [hs_pct_override]                       BIT              NOT NULL,
    [primary_use_cd]                        VARCHAR (10)     NULL,
    [primary_use_override]                  BIT              NOT NULL,
    [secondary_use_cd]                      VARCHAR (10)     NULL,
    [secondary_use_override]                BIT              NOT NULL,
    [actual_year_built]                     NUMERIC (4)      NULL,
    [building_number]                       VARCHAR (6)      NULL,
    [building_name]                         VARCHAR (50)     NULL,
    [flat_value_comment]                    VARCHAR (3000)   NULL,
    [flat_value_user_id]                    INT              NULL,
    [flat_value_date]                       DATETIME         NULL,
    [building_id]                           INT              NULL,
    [permanent_crop_land_acres]             NUMERIC (14, 4)  NULL,
    [permanent_crop_land_acres_override]    BIT              NOT NULL,
    [permanent_crop_planted_acres]          NUMERIC (14, 4)  NULL,
    [permanent_crop_planted_acres_override] BIT              NOT NULL,
    [recalc_error_validate_flag]            BIT              NULL,
    [recalc_error_validate_date]            DATETIME         NULL,
    [recalc_error_validate_user_id]         INT              NULL,
    [income_val]                            NUMERIC (14)     NULL,
    [income_id]                             INT              NULL,
    [mktappr_val]                           NUMERIC (14)     NULL,
    [locked_val]                            NUMERIC (14)     NULL,
    [mbl_hm_year]                           NUMERIC (4)      NULL,
    [mbl_hm_tip_out]                        NUMERIC (10)     NULL
);


GO

