CREATE TABLE [dbo].[cnv_non_udi_pct_owner_prelim_pv_before] (
    [prop_id]                       INT              NOT NULL,
    [prop_val_yr]                   NUMERIC (4)      NOT NULL,
    [prop_val]                      NUMERIC (14)     NULL,
    [chg_dt]                        DATETIME         NULL,
    [notice_mail_dt]                DATETIME         NULL,
    [land_hstd_val]                 NUMERIC (14)     NULL,
    [land_non_hstd_val]             NUMERIC (14)     NULL,
    [imprv_hstd_val]                NUMERIC (14)     NULL,
    [imprv_non_hstd_val]            NUMERIC (14)     NULL,
    [appraised_val]                 NUMERIC (14)     NULL,
    [assessed_val]                  NUMERIC (14)     NULL,
    [market]                        NUMERIC (14)     NULL,
    [ag_use_val]                    NUMERIC (14)     NULL,
    [ag_market]                     NUMERIC (14)     NULL,
    [freeze_ceiling]                NUMERIC (14, 2)  NULL,
    [freeze_yr]                     NUMERIC (4)      NULL,
    [ag_loss]                       NUMERIC (14)     NULL,
    [ag_late_loss]                  NUMERIC (14)     NULL,
    [timber_78]                     NUMERIC (14)     NULL,
    [timber_market]                 NUMERIC (14)     NULL,
    [timber_use]                    NUMERIC (14)     NULL,
    [timber_loss]                   NUMERIC (14)     NULL,
    [timber_late_loss]              NUMERIC (14)     NULL,
    [rendered_val]                  NUMERIC (14)     NULL,
    [rendered_yr]                   NUMERIC (4)      NULL,
    [new_val]                       NUMERIC (14)     NULL,
    [new_yr]                        NUMERIC (4)      NULL,
    [mineral_int_pct]               NUMERIC (13, 10) NULL,
    [orig_appraised_val]            NUMERIC (14)     NULL,
    [ten_percent_cap]               NUMERIC (14)     NULL,
    [sup_num]                       INT              NOT NULL,
    [legal_desc]                    VARCHAR (255)    NULL,
    [legal_desc_2]                  VARCHAR (255)    NULL,
    [abated_pct]                    NUMERIC (8)      NULL,
    [abated_amt]                    NUMERIC (14)     NULL,
    [abated_yr]                     NUMERIC (5)      NULL,
    [eff_size_acres]                NUMERIC (14, 4)  NULL,
    [shared_prop_val]               NUMERIC (14)     NULL,
    [shared_prop_cad_code]          VARCHAR (5)      NULL,
    [legal_acreage]                 NUMERIC (14, 4)  NULL,
    [vit_flag]                      CHAR (1)         NULL,
    [recalc_flag]                   CHAR (1)         NULL,
    [vit_declaration_filed_dt]      DATETIME         NULL,
    [prev_sup_num]                  INT              NULL,
    [sup_cd]                        CHAR (10)        NULL,
    [sup_desc]                      VARCHAR (500)    NULL,
    [sup_dt]                        DATETIME         NULL,
    [sup_action]                    CHAR (1)         NULL,
    [appr_company_id]               INT              NULL,
    [prop_inactive_dt]              DATETIME         NULL,
    [hscap_qualify_yr]              NUMERIC (4)      NULL,
    [hscap_override_prevhsval_flag] CHAR (1)         NULL,
    [hscap_prevhsval]               NUMERIC (14)     NULL,
    [hscap_prevhsval_pacsuser]      NUMERIC (14)     NULL,
    [hscap_prevhsval_comment]       VARCHAR (255)    NULL,
    [hscap_prevhsval_date]          DATETIME         NULL,
    [hscap_override_newhsval_flag]  CHAR (1)         NULL,
    [hscap_newhsval]                NUMERIC (14)     NULL,
    [hscap_newhsval_pacsuser]       NUMERIC (14)     NULL,
    [hscap_newhsval_comment]        VARCHAR (255)    NULL,
    [hscap_newhsval_date]           DATETIME         NULL,
    [last_appraisal_yr]             NUMERIC (4)      NULL,
    [oil_wells]                     NUMERIC (14)     NULL,
    [irr_wells]                     NUMERIC (14)     NULL,
    [irr_acres]                     NUMERIC (14, 4)  NULL,
    [irr_capacity]                  NUMERIC (14)     NULL,
    [oil_well_apply_adjust]         CHAR (1)         NULL,
    [oil_wells_apply_adjust]        CHAR (1)         NULL,
    [tif_imprv_val]                 NUMERIC (14)     NULL,
    [tif_land_val]                  NUMERIC (14)     NULL,
    [tif_flag]                      CHAR (1)         NULL,
    [accept_create_id]              INT              NULL,
    [accept_create_dt]              DATETIME         NULL,
    [abs_subdv_cd]                  VARCHAR (10)     NULL,
    [hood_cd]                       VARCHAR (10)     NULL,
    [block]                         VARCHAR (50)     NULL,
    [tract_or_lot]                  VARCHAR (50)     NULL,
    [mbl_hm_park]                   VARCHAR (50)     NULL,
    [mbl_hm_space]                  VARCHAR (50)     NULL,
    [rgn_cd]                        VARCHAR (5)      NULL,
    [subset_cd]                     VARCHAR (5)      NULL,
    [map_id]                        VARCHAR (20)     NULL,
    [auto_build_legal]              VARCHAR (1)      NULL,
    [image_path]                    VARCHAR (255)    NULL,
    [hscap_prev_reappr_yr]          NUMERIC (4)      NULL,
    [hscap_base_yr]                 NUMERIC (4)      NULL,
    [hscap_base_yr_override]        CHAR (1)         NULL,
    [hscap_base_yr_pacsuser]        NUMERIC (14)     NULL,
    [hscap_base_yr_comment]         VARCHAR (255)    NULL,
    [hscap_base_yr_date]            DATETIME         NULL,
    [last_appraiser_id]             INT              NULL,
    [next_appraiser_id]             INT              NULL,
    [last_appraisal_dt]             DATETIME         NULL,
    [next_appraisal_dt]             DATETIME         NULL,
    [next_appraisal_rsn]            VARCHAR (500)    NULL,
    [value_appraiser_id]            INT              NULL,
    [land_appraiser_id]             INT              NULL,
    [mapsco]                        VARCHAR (20)     NULL,
    [cost_value]                    NUMERIC (14)     NULL,
    [income_value]                  NUMERIC (14)     NULL,
    [shared_value]                  NUMERIC (14)     NULL,
    [appr_method]                   CHAR (5)         NULL,
    [cost_land_hstd_val]            NUMERIC (14)     NULL,
    [cost_land_non_hstd_val]        NUMERIC (14)     NULL,
    [cost_imprv_hstd_val]           NUMERIC (14)     NULL,
    [cost_imprv_non_hstd_val]       NUMERIC (14)     NULL,
    [cost_market]                   NUMERIC (14)     NULL,
    [cost_ag_use_val]               NUMERIC (14)     NULL,
    [cost_ag_market]                NUMERIC (14)     NULL,
    [cost_ag_loss]                  NUMERIC (14)     NULL,
    [cost_timber_market]            NUMERIC (14)     NULL,
    [cost_timber_use]               NUMERIC (14)     NULL,
    [cost_timber_loss]              NUMERIC (14)     NULL,
    [income_land_hstd_val]          NUMERIC (14)     NULL,
    [income_land_non_hstd_val]      NUMERIC (14)     NULL,
    [income_imprv_hstd_val]         NUMERIC (14)     NULL,
    [income_imprv_non_hstd_val]     NUMERIC (14)     NULL,
    [income_market]                 NUMERIC (14)     NULL,
    [income_ag_use_val]             NUMERIC (14)     NULL,
    [income_ag_market]              NUMERIC (14)     NULL,
    [income_ag_loss]                NUMERIC (14)     NULL,
    [income_timber_market]          NUMERIC (14)     NULL,
    [income_timber_use]             NUMERIC (14)     NULL,
    [income_timber_loss]            NUMERIC (14)     NULL,
    [shared_land_hstd_val]          NUMERIC (14)     NULL,
    [shared_land_non_hstd_val]      NUMERIC (14)     NULL,
    [shared_imprv_hstd_val]         NUMERIC (14)     NULL,
    [shared_imprv_non_hstd_val]     NUMERIC (14)     NULL,
    [shared_market]                 NUMERIC (14)     NULL,
    [shared_ag_use_val]             NUMERIC (14)     NULL,
    [shared_ag_market]              NUMERIC (14)     NULL,
    [shared_ag_loss]                NUMERIC (14)     NULL,
    [shared_timber_market]          NUMERIC (14)     NULL,
    [shared_timber_use]             NUMERIC (14)     NULL,
    [shared_timber_loss]            NUMERIC (14)     NULL,
    [shared_other_val]              NUMERIC (14, 2)  NULL
);


GO

