CREATE TABLE [dbo].[ptd_sale_submission_export] (
    [export_id]                          INT          IDENTITY (1, 1) NOT NULL,
    [export_run_id]                      INT          NULL,
    [pacs_user_id]                       INT          NOT NULL,
    [chg_of_owner_id]                    INT          NOT NULL,
    [cad_code]                           CHAR (3)     NULL,
    [school_district_code]               VARCHAR (10) NULL,
    [comptrollers_category_code]         CHAR (2)     NULL,
    [account_number]                     CHAR (25)    NULL,
    [geo_id]                             CHAR (25)    NULL,
    [legal_description]                  CHAR (50)    NULL,
    [parcel_address]                     CHAR (50)    NULL,
    [parcel_zip_code]                    CHAR (5)     NULL,
    [sale_date]                          CHAR (10)    NULL,
    [sale_price]                         CHAR (12)    NULL,
    [deed_date]                          CHAR (10)    NULL,
    [deed_volume]                        CHAR (5)     NULL,
    [deed_page]                          CHAR (7)     NULL,
    [deed_number]                        CHAR (20)    NULL,
    [deed_type]                          CHAR (12)    NULL,
    [multiple_account_code]              CHAR (1)     NULL,
    [sale_price_apportioned]             CHAR (1)     NULL,
    [overlapping_property_indicator]     CHAR (1)     NULL,
    [totally_exempt_code]                CHAR (1)     NULL,
    [grantee_first_name]                 CHAR (50)    NULL,
    [grantee_last_name_or_business_name] CHAR (50)    NULL,
    [grantee_address_line_1]             CHAR (35)    NULL,
    [grantee_address_line_2]             CHAR (35)    NULL,
    [grantee_city]                       CHAR (24)    NULL,
    [grantee_state]                      CHAR (2)     NULL,
    [grantee_zip]                        CHAR (9)     NULL,
    [grantor_first_name]                 CHAR (50)    NULL,
    [grantor_last_name_or_business_name] CHAR (50)    NULL,
    [grantor_address_line_1]             CHAR (35)    NULL,
    [grantor_address_line_2]             CHAR (35)    NULL,
    [grantor_city]                       CHAR (24)    NULL,
    [grantor_state]                      CHAR (2)     NULL,
    [grantor_zip]                        CHAR (9)     NULL,
    [map_number]                         CHAR (25)    NULL,
    [cad_verification_source_code]       CHAR (3)     NULL,
    [validity_code]                      CHAR (1)     NULL,
    [confidential_code]                  CHAR (1)     NULL,
    [frozen_characteristics]             CHAR (1)     NULL,
    [certified_value_year]               CHAR (4)     NULL,
    [value_set_by_arb]                   CHAR (1)     NULL,
    [cad_value_land]                     CHAR (12)    NULL,
    [cad_value_improvement]              CHAR (12)    NULL,
    [cad_value_personal_property]        CHAR (12)    NULL,
    [total_cad_value]                    CHAR (12)    NULL,
    [square_footage_improvement]         CHAR (7)     NULL,
    [land_unit_type]                     CHAR (2)     NULL,
    [number_of_land_units]               CHAR (14)    NULL,
    [number_of_bedrooms]                 CHAR (1)     NULL,
    [number_of_bathrooms]                CHAR (5)     NULL,
    [cach]                               CHAR (1)     NULL,
    [year_built]                         CHAR (4)     NULL,
    [construction_type_class]            CHAR (10)    NULL,
    [number_of_stories]                  CHAR (6)     NULL,
    [subdivision_neighborhood]           CHAR (15)    NULL,
    [financing_code]                     CHAR (5)     NULL,
    [number_of_days_on_market]           CHAR (3)     NULL,
    [previous_cad_value_land]            CHAR (12)    NULL,
    [previous_cad_value_improvement]     CHAR (12)    NULL,
    [cad_comments_1]                     CHAR (50)    NULL,
    [cad_comments_2]                     CHAR (50)    NULL,
    [interest_rate]                      CHAR (5)     NULL,
    [number_of_years_financed]           CHAR (2)     NULL,
    [down_payment]                       CHAR (12)    NULL,
    CONSTRAINT [CPK_ptd_sale_submission_export] PRIMARY KEY NONCLUSTERED ([export_id] ASC) WITH (FILLFACTOR = 90)
);


GO

CREATE CLUSTERED INDEX [idx_pacs_user_id_chg_of_owner_id]
    ON [dbo].[ptd_sale_submission_export]([pacs_user_id] ASC, [chg_of_owner_id] ASC) WITH (FILLFACTOR = 90);


GO

