CREATE TABLE [dbo].[wa_tax_statement_owner_distribution_current_run] (
    [group_id]         INT             NOT NULL,
    [year]             NUMERIC (4)     NOT NULL,
    [run_id]           INT             NOT NULL,
    [owner_id]         INT             NOT NULL,
    [td_code01]        VARCHAR (10)    NULL,
    [td_desc01]        VARCHAR (60)    NULL,
    [td_full_total_01] NUMERIC (18, 2) NULL,
    [td_code02]        VARCHAR (10)    NULL,
    [td_desc02]        VARCHAR (60)    NULL,
    [td_full_total_02] NUMERIC (18, 2) NULL,
    [td_code03]        VARCHAR (10)    NULL,
    [td_desc03]        VARCHAR (60)    NULL,
    [td_full_total_03] NUMERIC (18, 2) NULL,
    [td_code04]        VARCHAR (10)    NULL,
    [td_desc04]        VARCHAR (60)    NULL,
    [td_full_total_04] NUMERIC (18, 2) NULL,
    [td_code05]        VARCHAR (10)    NULL,
    [td_desc05]        VARCHAR (60)    NULL,
    [td_full_total_05] NUMERIC (18, 2) NULL,
    [td_code06]        VARCHAR (10)    NULL,
    [td_desc06]        VARCHAR (60)    NULL,
    [td_full_total_06] NUMERIC (18, 2) NULL,
    [td_code07]        VARCHAR (10)    NULL,
    [td_desc07]        VARCHAR (60)    NULL,
    [td_full_total_07] NUMERIC (18, 2) NULL,
    [td_code08]        VARCHAR (10)    NULL,
    [td_desc08]        VARCHAR (60)    NULL,
    [td_full_total_08] NUMERIC (18, 2) NULL,
    [td_code09]        VARCHAR (10)    NULL,
    [td_desc09]        VARCHAR (60)    NULL,
    [td_full_total_09] NUMERIC (18, 2) NULL,
    [td_code10]        VARCHAR (10)    NULL,
    [td_desc10]        VARCHAR (60)    NULL,
    [td_full_total_10] NUMERIC (18, 2) NULL,
    [td_code11]        VARCHAR (10)    NULL,
    [td_desc11]        VARCHAR (60)    NULL,
    [td_full_total_11] NUMERIC (18, 2) NULL,
    [af_code01]        VARCHAR (10)    NULL,
    [af_desc01]        VARCHAR (60)    NULL,
    [af_full_total_01] NUMERIC (18, 2) NULL,
    [af_code02]        VARCHAR (10)    NULL,
    [af_desc02]        VARCHAR (60)    NULL,
    [af_full_total_02] NUMERIC (18, 2) NULL,
    [af_code03]        VARCHAR (10)    NULL,
    [af_desc03]        VARCHAR (60)    NULL,
    [af_full_total_03] NUMERIC (18, 2) NULL,
    [af_code04]        VARCHAR (10)    NULL,
    [af_desc04]        VARCHAR (60)    NULL,
    [af_full_total_04] NUMERIC (18, 2) NULL,
    [af_code05]        VARCHAR (10)    NULL,
    [af_desc05]        VARCHAR (60)    NULL,
    [af_full_total_05] NUMERIC (18, 2) NULL,
    [af_code06]        VARCHAR (10)    NULL,
    [af_desc06]        VARCHAR (60)    NULL,
    [af_full_total_06] NUMERIC (18, 2) NULL,
    [af_code07]        VARCHAR (10)    NULL,
    [af_desc07]        VARCHAR (60)    NULL,
    [af_full_total_07] NUMERIC (18, 2) NULL,
    CONSTRAINT [CPK_wa_tax_statement_owner_distribution_current_run] PRIMARY KEY CLUSTERED ([group_id] ASC, [year] ASC, [run_id] ASC, [owner_id] ASC)
);


GO

