
CREATE PROCEDURE CopyProtestsAndInquiriesFromUDIParentToProperty 
 	@parent_prop_id      	int,
	@parent_sup_num 	int,
	@parent_tax_yr      	numeric(4,0),
 	@dest_prop_id      	int,
	@dest_sup_num 		int,
	@dest_tax_yr      	numeric(4,0)
WITH RECOMPILE

AS

-- 01-10-05 	TrentN		Created 	Copies protests and inquiries to a property from a parent property and its children.

DECLARE @parent_udi_parent	varchar(5)
DECLARE @child_prop_id		int
DECLARE @child_sup_num		int
DECLARE @child_prop_val_yr	numeric(4,0)

SELECT 	@parent_udi_parent = IsNull(udi_parent, '')
FROM	property_val
WHERE	property_val.prop_id = @parent_prop_id AND
	property_val.sup_num = @parent_sup_num AND
	property_val.prop_val_yr = @parent_tax_yr

IF (@parent_udi_parent = 'T' OR @parent_udi_parent = 'D')
BEGIN
	INSERT INTO _arb_protest
	(
		prop_id,
		prop_val_yr,
		case_id,
		prot_create_dt,
		prot_complete_dt,
		prot_type,
		prot_status,
		prot_taxpayer_doc_requested,
		prot_taxpayer_doc_recorded_dt,
		prot_taxpayer_evidence_requested,
		prot_taxpayer_evidence_requested_dt,
		prot_taxpayer_evidence_delivered_dt,
		prot_taxpayer_evidence_staff,
		prot_taxpayer_additional_evidence,
		prot_taxpayer_evidence_waiver,
		prot_taxes_paid,
		prot_taxes_paid_verified_staff_id,
		prot_taxes_paid_verified_dt,
		prot_appraisal_staff,
		prot_comments,
		prot_affidavit_testimony_dt,
		prot_affidavit_testimony_by,
		prot_affidavit_testimony_received,
		docket_id,
		prot_assigned_panel,
		prot_arrived_dt,
		prot_hearing_rescheduled,
		prot_packet_printed_dt,
		prot_full_board_hearing,
		prot_hearing_appraisal_staff,
		prot_hearing_start_dt,
		prot_hearing_finished_dt,
		prot_hearing_recorder_id,
		prot_taxpayer_comments,
		prot_district_comments,
		prot_first_motion,
		prot_sustain_district_val,
		prot_first_motion_by,
		prot_first_motion_seconded_by,
		prot_first_motion_pass,
		prot_first_motion_decision_cd,
		prot_first_motion_decision_dt,
		prot_appraiser_assigned_val,
		prot_arb_assigned_val,
		prot_val_type,
		prot_arb_instructions,
		prot_second_motion,
		prot_second_motion_by,
		prot_second_motion_seconded_by,
		prot_second_motion_pass,
		prot_second_motion_decision_cd,
		prot_second_motion_decision_dt,
		prot_other_motion,
		prot_full_ratification_dt,
		begin_land_hstd_val,
		begin_land_non_hstd_val,
		begin_imprv_hstd_val,
		begin_imprv_non_hstd_val,
		begin_ag_use_val,
		begin_ag_market,
		begin_timber_use,
		begin_timber_market,
		begin_market,
		begin_appraised_val,
		begin_ten_percent_cap,
		begin_assessed_val,
		begin_rendered_val,
		begin_exemptions,
		begin_entities,
		begin_recalc_dt,
		final_land_hstd_val,
		final_land_non_hstd_val,
		final_imprv_hstd_val,
		final_imprv_non_hstd_val,
		final_ag_use_val,
		final_ag_market,
		final_timber_use,
		final_timber_market,
		final_market,
		final_appraised_val,
		final_ten_percent_cap,
		final_assessed_val,
		final_rendered_val,
		final_exemptions,
		final_entities,
		final_recalc_dt,
		bGridComplete,
		closed_pacs_user_id,
		bGenerateCompGrid,
		status_date_changed,
		status_changed_user_id,
		associated_inquiry,
		appraiser_meeting_id,
		appraiser_meeting_appraiser_id,
		appraiser_meeting_date_time,
		appraiser_meeting_appraiser_comments,
		appraiser_meeting_taxpayer_comments,
		prot_appr_meeting_arrived_dt,
		prot_appr_docket_id,
		case_prepared
	)
	SELECT	@dest_prop_id,
		@dest_tax_yr,
		case_id,
		prot_create_dt,
		prot_complete_dt,
		prot_type,
		prot_status,
		prot_taxpayer_doc_requested,
		prot_taxpayer_doc_recorded_dt,
		prot_taxpayer_evidence_requested,
		prot_taxpayer_evidence_requested_dt,
		prot_taxpayer_evidence_delivered_dt,
		prot_taxpayer_evidence_staff,
		prot_taxpayer_additional_evidence,
		prot_taxpayer_evidence_waiver,
		prot_taxes_paid,
		prot_taxes_paid_verified_staff_id,
		prot_taxes_paid_verified_dt,
		prot_appraisal_staff,
		prot_comments,
		prot_affidavit_testimony_dt,
		prot_affidavit_testimony_by,
		prot_affidavit_testimony_received,
		docket_id,
		prot_assigned_panel,
		prot_arrived_dt,
		prot_hearing_rescheduled,
		prot_packet_printed_dt,
		prot_full_board_hearing,
		prot_hearing_appraisal_staff,
		prot_hearing_start_dt,
		prot_hearing_finished_dt,
		prot_hearing_recorder_id,
		prot_taxpayer_comments,
		prot_district_comments,
		prot_first_motion,
		prot_sustain_district_val,
		prot_first_motion_by,
		prot_first_motion_seconded_by,
		prot_first_motion_pass,
		prot_first_motion_decision_cd,
		prot_first_motion_decision_dt,
		prot_appraiser_assigned_val,
		prot_arb_assigned_val,
		prot_val_type,
		prot_arb_instructions,
		prot_second_motion,
		prot_second_motion_by,
		prot_second_motion_seconded_by,
		prot_second_motion_pass,
		prot_second_motion_decision_cd,
		prot_second_motion_decision_dt,
		prot_other_motion,
		prot_full_ratification_dt,
		begin_land_hstd_val,
		begin_land_non_hstd_val,
		begin_imprv_hstd_val,
		begin_imprv_non_hstd_val,
		begin_ag_use_val,
		begin_ag_market,
		begin_timber_use,
		begin_timber_market,
		begin_market,
		begin_appraised_val,
		begin_ten_percent_cap,
		begin_assessed_val,
		begin_rendered_val,
		begin_exemptions,
		begin_entities,
		begin_recalc_dt,
		final_land_hstd_val,
		final_land_non_hstd_val,
		final_imprv_hstd_val,
		final_imprv_non_hstd_val,
		final_ag_use_val,
		final_ag_market,
		final_timber_use,
		final_timber_market,
		final_market,
		final_appraised_val,
		final_ten_percent_cap,
		final_assessed_val,
		final_rendered_val,
		final_exemptions,
		final_entities,
		final_recalc_dt,
		bGridComplete,
		closed_pacs_user_id,
		bGenerateCompGrid,
		status_date_changed,
		status_changed_user_id,
		associated_inquiry,
		appraiser_meeting_id,
		appraiser_meeting_appraiser_id,
		appraiser_meeting_date_time,
		appraiser_meeting_appraiser_comments,
		appraiser_meeting_taxpayer_comments,
		prot_appr_meeting_arrived_dt,
		prot_appr_docket_id,
		case_prepared
	FROM	_arb_protest
	WHERE	prop_id = @parent_prop_id AND
		prop_val_yr = @parent_tax_yr

	INSERT INTO _arb_protest_protest_by_assoc
	(
		prop_val_yr,
		appba.case_id,
		appba.prot_by_type,
		appba.prot_by_id,
		appba.prot_by_id_type,
		appba.primary_protester,
		appba.withdrew,
		appba.at_hearing,
		appba.prot_by_create_dt
	)
	SELECT	@dest_tax_yr,
		appba.case_id,
		appba.prot_by_type,
		appba.prot_by_id,
		appba.prot_by_id_type,
		appba.primary_protester,
		appba.withdrew,
		appba.at_hearing,
		appba.prot_by_create_dt
	FROM	_arb_protest
	INNER JOIN _arb_protest_protest_by_assoc as appba
		WITH (NOLOCK) 
		ON appba.case_id = _arb_protest.case_id
		AND appba.prop_val_yr = _arb_protest.prop_val_yr
		AND appba.primary_protester = 1
	WHERE	_arb_protest.prop_id = @parent_prop_id AND
		_arb_protest.prop_val_yr = @parent_tax_yr	
	
		
	INSERT INTO _arb_inquiry
	(
		prop_id,
		prop_val_yr,
		case_id,
		inq_create_dt,
		inq_complete_dt,
		inq_operator,
		inq_type,
		inq_status,
		inq_nature,
		inq_appraisal_staff,
		inq_appraisal_staff_dt,
		inq_support_staff,
		inq_support_staff_dt,
		inq_gis_staff,
		inq_gis_staff_dt,
		inq_field_check,
		inq_field_staff,
		inq_field_staff_dt,
		inq_field_check_completed_dt,
		inq_taxpayer_doc_requested,
		inq_taxpayer_doc_request_dt,
		inq_taxpayer_doc_expected_dt,
		inq_taxpayer_doc_received_dt,
		inq_taxpayer_doc_type,
		inq_value_agreement_amt,
		inq_value_agreement_mail_dt,
		inq_value_agreement_fax_dt,
		inq_value_agreement_received_dt,
		inq_by_type,
		inq_by_id,
		inq_by_id_type,
		inq_assigned_val,
		inq_assigned_reason_cd,
		inq_taxpayer_comments,
		inq_appraiser_comments,
		begin_land_hstd_val,
		begin_land_non_hstd_val,
		begin_imprv_hstd_val,
		begin_imprv_non_hstd_val,
		begin_ag_use_val,
		begin_ag_market,
		begin_timber_use,
		begin_timber_market,
		begin_market,
		begin_appraised_val,
		begin_ten_percent_cap,
		begin_assessed_val,
		begin_rendered_val,
		begin_exemptions,
		begin_entities,
		begin_recalc_dt	,
		final_land_hstd_val,
		final_land_non_hstd_val,
		final_imprv_hstd_val,
		final_imprv_non_hstd_val,
		final_ag_use_val,
		final_ag_market,
		final_timber_use,
		final_timber_market,
		final_market,
		final_appraised_val,
		final_ten_percent_cap,
		final_assessed_val,
		final_rendered_val,
		final_exemptions,
		final_entities,
		final_recalc_dt,
		bGridComplete,
		closed_pacs_user_id,
		bGenerateCompGrid,
		status_date_changed,
		status_changed_user_id,
		associated_protest,
		appraiser_meeting_id,
		appraiser_meeting_appraiser_id,
		appraiser_meeting_date_time,
		appraiser_meeting_appraiser_comments,
		appraiser_meeting_taxpayer_comments,
		inq_operator_comments
	)
	SELECT	@dest_prop_id,
		@dest_tax_yr,
		case_id,
		inq_create_dt,
		inq_complete_dt,
		inq_operator,
		inq_type,
		inq_status,
		inq_nature,
		inq_appraisal_staff,
		inq_appraisal_staff_dt,
		inq_support_staff,
		inq_support_staff_dt,
		inq_gis_staff,
		inq_gis_staff_dt,
		inq_field_check,
		inq_field_staff,
		inq_field_staff_dt,
		inq_field_check_completed_dt,
		inq_taxpayer_doc_requested,
		inq_taxpayer_doc_request_dt,
		inq_taxpayer_doc_expected_dt,
		inq_taxpayer_doc_received_dt,
		inq_taxpayer_doc_type,
		inq_value_agreement_amt,
		inq_value_agreement_mail_dt,
		inq_value_agreement_fax_dt,
		inq_value_agreement_received_dt,
		inq_by_type,
		inq_by_id,
		inq_by_id_type,
		inq_assigned_val,
		inq_assigned_reason_cd,
		inq_taxpayer_comments,
		inq_appraiser_comments,
		begin_land_hstd_val,
		begin_land_non_hstd_val,
		begin_imprv_hstd_val,
		begin_imprv_non_hstd_val,
		begin_ag_use_val,
		begin_ag_market,
		begin_timber_use,
		begin_timber_market,
		begin_market,
		begin_appraised_val,
		begin_ten_percent_cap,
		begin_assessed_val,
		begin_rendered_val,
		begin_exemptions,
		begin_entities,
		begin_recalc_dt	,
		final_land_hstd_val,
		final_land_non_hstd_val,
		final_imprv_hstd_val,
		final_imprv_non_hstd_val,
		final_ag_use_val,
		final_ag_market,
		final_timber_use,
		final_timber_market,
		final_market,
		final_appraised_val,
		final_ten_percent_cap,
		final_assessed_val,
		final_rendered_val,
		final_exemptions,
		final_entities,
		final_recalc_dt,
		bGridComplete,
		closed_pacs_user_id,
		bGenerateCompGrid,
		status_date_changed,
		status_changed_user_id,
		associated_protest,
		appraiser_meeting_id,
		appraiser_meeting_appraiser_id,
		appraiser_meeting_date_time,
		appraiser_meeting_appraiser_comments,
		appraiser_meeting_taxpayer_comments,
		inq_operator_comments
	FROM	_arb_inquiry
	WHERE	prop_id = @parent_prop_id AND
		prop_val_yr = @parent_tax_yr


	DECLARE child_property_cursor SCROLL CURSOR
	FOR	SELECT	property_val.prop_id, 
			property_val.sup_num, 
			property_val.prop_val_yr
		FROM	property_val
			JOIN property_val AS parent ON
					(IsNull(parent.udi_parent, '') = 'T' OR IsNull(parent.udi_parent, '') = 'D') AND
					property_val.udi_parent_prop_id = parent.prop_id AND
					property_val.sup_num = parent.sup_num AND
					property_val.prop_val_yr = parent.prop_val_yr AND
					parent.prop_id = @parent_prop_id AND
					parent.sup_num = @parent_sup_num AND
					parent.prop_val_yr = @parent_tax_yr
		WHERE	IsNull(property_val.udi_status, '') != 'S'
	
	OPEN child_property_cursor
	FETCH NEXT FROM child_property_cursor INTO
		@child_prop_id,
		@child_sup_num,
		@child_prop_val_yr

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF (@child_prop_id != @dest_prop_id)
		BEGIN
			INSERT INTO _arb_protest
			(
				prop_id,
				prop_val_yr,
				case_id,
				prot_create_dt,
				prot_complete_dt,
				prot_type,
				prot_status,
				prot_taxpayer_doc_requested,
				prot_taxpayer_doc_recorded_dt,
				prot_taxpayer_evidence_requested,
				prot_taxpayer_evidence_requested_dt,
				prot_taxpayer_evidence_delivered_dt,
				prot_taxpayer_evidence_staff,
				prot_taxpayer_additional_evidence,
				prot_taxpayer_evidence_waiver,
				prot_taxes_paid,
				prot_taxes_paid_verified_staff_id,
				prot_taxes_paid_verified_dt,
				prot_appraisal_staff,
				prot_comments,
				prot_affidavit_testimony_dt,
				prot_affidavit_testimony_by,
				prot_affidavit_testimony_received,
				docket_id,
				prot_assigned_panel,
				prot_arrived_dt,
				prot_hearing_rescheduled,
				prot_packet_printed_dt,
				prot_full_board_hearing,
				prot_hearing_appraisal_staff,
				prot_hearing_start_dt,
				prot_hearing_finished_dt,
				prot_hearing_recorder_id,
				prot_taxpayer_comments,
				prot_district_comments,
				prot_first_motion,
				prot_sustain_district_val,
				prot_first_motion_by,
				prot_first_motion_seconded_by,
				prot_first_motion_pass,
				prot_first_motion_decision_cd,
				prot_first_motion_decision_dt,
				prot_appraiser_assigned_val,
				prot_arb_assigned_val,
				prot_val_type,
				prot_arb_instructions,
				prot_second_motion,
				prot_second_motion_by,
				prot_second_motion_seconded_by,
				prot_second_motion_pass,
				prot_second_motion_decision_cd,
				prot_second_motion_decision_dt,
				prot_other_motion,
				prot_full_ratification_dt,
				begin_land_hstd_val,
				begin_land_non_hstd_val,
				begin_imprv_hstd_val,
				begin_imprv_non_hstd_val,
				begin_ag_use_val,
				begin_ag_market,
				begin_timber_use,
				begin_timber_market,
				begin_market,
				begin_appraised_val,
				begin_ten_percent_cap,
				begin_assessed_val,
				begin_rendered_val,
				begin_exemptions,
				begin_entities,
				begin_recalc_dt,
				final_land_hstd_val,
				final_land_non_hstd_val,
				final_imprv_hstd_val,
				final_imprv_non_hstd_val,
				final_ag_use_val,
				final_ag_market,
				final_timber_use,
				final_timber_market,
				final_market,
				final_appraised_val,
				final_ten_percent_cap,
				final_assessed_val,
				final_rendered_val,
				final_exemptions,
				final_entities,
				final_recalc_dt,
				bGridComplete,
				closed_pacs_user_id,
				bGenerateCompGrid,
				status_date_changed,
				status_changed_user_id,
				associated_inquiry,
				appraiser_meeting_id,
				appraiser_meeting_appraiser_id,
				appraiser_meeting_date_time,
				appraiser_meeting_appraiser_comments,
				appraiser_meeting_taxpayer_comments,
				prot_appr_meeting_arrived_dt,
				prot_appr_docket_id,
				case_prepared
			)
			SELECT	@dest_prop_id,
				@dest_tax_yr,
				_arb_protest.case_id,
				prot_create_dt,
				prot_complete_dt,
				prot_type,
				prot_status,
				prot_taxpayer_doc_requested,
				prot_taxpayer_doc_recorded_dt,
				prot_taxpayer_evidence_requested,
				prot_taxpayer_evidence_requested_dt,
				prot_taxpayer_evidence_delivered_dt,
				prot_taxpayer_evidence_staff,
				prot_taxpayer_additional_evidence,
				prot_taxpayer_evidence_waiver,
				prot_taxes_paid,
				prot_taxes_paid_verified_staff_id,
				prot_taxes_paid_verified_dt,
				prot_appraisal_staff,
				prot_comments,
				prot_affidavit_testimony_dt,
				prot_affidavit_testimony_by,
				prot_affidavit_testimony_received,
				docket_id,
				prot_assigned_panel,
				prot_arrived_dt,
				prot_hearing_rescheduled,
				prot_packet_printed_dt,
				prot_full_board_hearing,
				prot_hearing_appraisal_staff,
				prot_hearing_start_dt,
				prot_hearing_finished_dt,
				prot_hearing_recorder_id,
				prot_taxpayer_comments,
				prot_district_comments,
				prot_first_motion,
				prot_sustain_district_val,
				prot_first_motion_by,
				prot_first_motion_seconded_by,
				prot_first_motion_pass,
				prot_first_motion_decision_cd,
				prot_first_motion_decision_dt,
				prot_appraiser_assigned_val,
				prot_arb_assigned_val,
				prot_val_type,
				prot_arb_instructions,
				prot_second_motion,
				prot_second_motion_by,
				prot_second_motion_seconded_by,
				prot_second_motion_pass,
				prot_second_motion_decision_cd,
				prot_second_motion_decision_dt,
				prot_other_motion,
				prot_full_ratification_dt,
				begin_land_hstd_val,
				begin_land_non_hstd_val,
				begin_imprv_hstd_val,
				begin_imprv_non_hstd_val,
				begin_ag_use_val,
				begin_ag_market,
				begin_timber_use,
				begin_timber_market,
				begin_market,
				begin_appraised_val,
				begin_ten_percent_cap,
				begin_assessed_val,
				begin_rendered_val,
				begin_exemptions,
				begin_entities,
				begin_recalc_dt,
				final_land_hstd_val,
				final_land_non_hstd_val,
				final_imprv_hstd_val,
				final_imprv_non_hstd_val,
				final_ag_use_val,
				final_ag_market,
				final_timber_use,
				final_timber_market,
				final_market,
				final_appraised_val,
				final_ten_percent_cap,
				final_assessed_val,
				final_rendered_val,
				final_exemptions,
				final_entities,
				final_recalc_dt,
				bGridComplete,
				closed_pacs_user_id,
				bGenerateCompGrid,
				status_date_changed,
				status_changed_user_id,
				associated_inquiry,
				appraiser_meeting_id,
				appraiser_meeting_appraiser_id,
				appraiser_meeting_date_time,
				appraiser_meeting_appraiser_comments,
				appraiser_meeting_taxpayer_comments,
				prot_appr_meeting_arrived_dt,
				prot_appr_docket_id,
				case_prepared
			FROM	_arb_protest
			WHERE	prop_id = @child_prop_id AND
				prop_val_yr = @child_prop_val_yr

			INSERT INTO _arb_protest_protest_by_assoc
			(
				prop_val_yr,
				appba.case_id,
				appba.prot_by_type,
				appba.prot_by_id,
				appba.prot_by_id_type,
				appba.primary_protester,
				appba.withdrew,
				appba.at_hearing,
				appba.prot_by_create_dt
			)
			SELECT	@dest_tax_yr,
				appba.case_id,
				appba.prot_by_type,
				appba.prot_by_id,
				appba.prot_by_id_type,
				appba.primary_protester,
				appba.withdrew,
				appba.at_hearing,
				appba.prot_by_create_dt
			FROM	_arb_protest
			INNER JOIN _arb_protest_protest_by_assoc as appba
				WITH (NOLOCK) 
				ON appba.case_id = _arb_protest.case_id
				AND appba.prop_val_yr = _arb_protest.prop_val_yr
				AND appba.primary_protester = 1
			WHERE	_arb_protest.prop_id = @child_prop_id AND
				_arb_protest.prop_val_yr = @child_prop_val_yr
		
			INSERT INTO _arb_inquiry
			(
				prop_id,
				prop_val_yr,
				case_id,
				inq_create_dt,
				inq_complete_dt,
				inq_operator,
				inq_type,
				inq_status,
				inq_nature,
				inq_appraisal_staff,
				inq_appraisal_staff_dt,
				inq_support_staff,
				inq_support_staff_dt,
				inq_gis_staff,
				inq_gis_staff_dt,
				inq_field_check,
				inq_field_staff,
				inq_field_staff_dt,
				inq_field_check_completed_dt,
				inq_taxpayer_doc_requested,
				inq_taxpayer_doc_request_dt,
				inq_taxpayer_doc_expected_dt,
				inq_taxpayer_doc_received_dt,
				inq_taxpayer_doc_type,
				inq_value_agreement_amt,
				inq_value_agreement_mail_dt,
				inq_value_agreement_fax_dt,
				inq_value_agreement_received_dt,
				inq_by_type,
				inq_by_id,
				inq_by_id_type,
				inq_assigned_val,
				inq_assigned_reason_cd,
				inq_taxpayer_comments,
				inq_appraiser_comments,
				begin_land_hstd_val,
				begin_land_non_hstd_val,
				begin_imprv_hstd_val,
				begin_imprv_non_hstd_val,
				begin_ag_use_val,
				begin_ag_market,
				begin_timber_use,
				begin_timber_market,
				begin_market,
				begin_appraised_val,
				begin_ten_percent_cap,
				begin_assessed_val,
				begin_rendered_val,
				begin_exemptions,
				begin_entities,
				begin_recalc_dt	,
				final_land_hstd_val,
				final_land_non_hstd_val,
				final_imprv_hstd_val,
				final_imprv_non_hstd_val,
				final_ag_use_val,
				final_ag_market,
				final_timber_use,
				final_timber_market,
				final_market,
				final_appraised_val,
				final_ten_percent_cap,
				final_assessed_val,
				final_rendered_val,
				final_exemptions,
				final_entities,
				final_recalc_dt,
				bGridComplete,
				closed_pacs_user_id,
				bGenerateCompGrid,
				status_date_changed,
				status_changed_user_id,
				associated_protest,
				appraiser_meeting_id,
				appraiser_meeting_appraiser_id,
				appraiser_meeting_date_time,
				appraiser_meeting_appraiser_comments,
				appraiser_meeting_taxpayer_comments,
				inq_operator_comments
			)
			SELECT	@dest_prop_id,
				@dest_tax_yr,
				case_id,
				inq_create_dt,
				inq_complete_dt,
				inq_operator,
				inq_type,
				inq_status,
				inq_nature,
				inq_appraisal_staff,
				inq_appraisal_staff_dt,
				inq_support_staff,
				inq_support_staff_dt,
				inq_gis_staff,
				inq_gis_staff_dt,
				inq_field_check,
				inq_field_staff,
				inq_field_staff_dt,
				inq_field_check_completed_dt,
				inq_taxpayer_doc_requested,
				inq_taxpayer_doc_request_dt,
				inq_taxpayer_doc_expected_dt,
				inq_taxpayer_doc_received_dt,
				inq_taxpayer_doc_type,
				inq_value_agreement_amt,
				inq_value_agreement_mail_dt,
				inq_value_agreement_fax_dt,
				inq_value_agreement_received_dt,
				inq_by_type,
				inq_by_id,
				inq_by_id_type,
				inq_assigned_val,
				inq_assigned_reason_cd,
				inq_taxpayer_comments,
				inq_appraiser_comments,
				begin_land_hstd_val,
				begin_land_non_hstd_val,
				begin_imprv_hstd_val,
				begin_imprv_non_hstd_val,
				begin_ag_use_val,
				begin_ag_market,
				begin_timber_use,
				begin_timber_market,
				begin_market,
				begin_appraised_val,
				begin_ten_percent_cap,
				begin_assessed_val,
				begin_rendered_val,
				begin_exemptions,
				begin_entities,
				begin_recalc_dt	,
				final_land_hstd_val,
				final_land_non_hstd_val,
				final_imprv_hstd_val,
				final_imprv_non_hstd_val,
				final_ag_use_val,
				final_ag_market,
				final_timber_use,
				final_timber_market,
				final_market,
				final_appraised_val,
				final_ten_percent_cap,
				final_assessed_val,
				final_rendered_val,
				final_exemptions,
				final_entities,
				final_recalc_dt,
				bGridComplete,
				closed_pacs_user_id,
				bGenerateCompGrid,
				status_date_changed,
				status_changed_user_id,
				associated_protest,
				appraiser_meeting_id,
				appraiser_meeting_appraiser_id,
				appraiser_meeting_date_time,
				appraiser_meeting_appraiser_comments,
				appraiser_meeting_taxpayer_comments,
				inq_operator_comments
			FROM	_arb_inquiry
			WHERE	prop_id = @child_prop_id AND
				prop_val_yr = @child_prop_val_yr

		END

		FETCH NEXT FROM child_property_cursor INTO
			@child_prop_id,
			@child_sup_num,
			@child_prop_val_yr
	END

	CLOSE child_property_cursor
	DEALLOCATE child_property_cursor
END

GO

