
create procedure LayerCopyShared
	@lYear_From numeric(4,0),
	@lSupNum_From int,
	@lPropID_From int,
	@lYear_To numeric(4,0),
	@lSupNum_To int,
	@lPropID_To int

as

set nocount on

	insert dbo.shared_prop with(rowlock) (
		pacs_prop_id,
		shared_year,
		shared_cad_code,
		shared_prop_id,
		tape_run_dt,
		tape_load_dt,
		link_dt,
		deed_dt,
		situs_city,
		legal,
		map_id,
		prev_tax_unfrozen,
		owner_name,
		owner_addr,
		owner_state,
		owner_zip,
		ag_use,
		special_exmpt_entity_cd,
		situs_street_num,
		dv_exemption_amount,
		cad_name,
		exmpt,
		deed_volume,
		ref_id,
		prorated_qualify_dt,
		prorated_remove_dt,
		arb_hearing_dt,
		oa_qual_dt,
		owner_addr2,
		owner_city,
		prorated_exmpt_flg,
		productivity_code,
		oa_remove_dt,
		situs_zip,
		situs_state,
		prev_tax_due,
		special_exmpt_amt,
		arb_indicator,
		deed_page,
		special_exemption_cd,
		situs_street,
		dba_name,
		new_hs_value,
		owner_addr_line1,
		owner_addr_line2,
		owner_addr_line3,
		cad_sup_num,
		cad_sup_code,
		num_imprv_segs,
		imprv_ptd_code,
		imprv_class,
		num_land_segs,
		land_ptd_code,
		size_acres,
		mineral_ptd_code,
		personal_ptd_code,
		entities,
		freeze_transfer_flag,
		transfer_pct,
		imprv_hs_val,
		imprv_non_hs_val,
		land_hs,
		land_non_hs,
		ag_market,
		timber_use,
		timber_market,
		market,
		appraised_val,
		cad_ten_percent_cap,
		cad_assessed_val,
		arb_status,
		sales_dt,
		sales_price,
		appraiser,
		cad_sup_comment,
		exempt_prev_tax,
		exempt_prev_tax_unfrozen,
		ag_use_val,
		multi_owner,
		imp_new_value,
		land_new_value,
		run_id,
		sup_num,
		arb_dt,
		productivity_loss
	)
	select
		@lPropID_To,
		@lYear_To,
		shared_cad_code,
		shared_prop_id,
		tape_run_dt,
		tape_load_dt,
		link_dt,
		deed_dt,
		situs_city,
		legal,
		map_id,
		prev_tax_unfrozen,
		owner_name,
		owner_addr,
		owner_state,
		owner_zip,
		ag_use,
		special_exmpt_entity_cd,
		situs_street_num,
		dv_exemption_amount,
		cad_name,
		exmpt,
		deed_volume,
		ref_id,
		prorated_qualify_dt,
		prorated_remove_dt,
		arb_hearing_dt,
		oa_qual_dt,
		owner_addr2,
		owner_city,
		prorated_exmpt_flg,
		productivity_code,
		oa_remove_dt,
		situs_zip,
		situs_state,
		prev_tax_due,
		special_exmpt_amt,
		arb_indicator,
		deed_page,
		special_exemption_cd,
		situs_street,
		dba_name,
		new_hs_value,
		owner_addr_line1,
		owner_addr_line2,
		owner_addr_line3,
		cad_sup_num,
		cad_sup_code,
		num_imprv_segs,
		imprv_ptd_code,
		imprv_class,
		num_land_segs,
		land_ptd_code,
		size_acres,
		mineral_ptd_code,
		personal_ptd_code,
		entities,
		freeze_transfer_flag,
		transfer_pct,
		imprv_hs_val,
		imprv_non_hs_val,
		land_hs,
		land_non_hs,
		ag_market,
		timber_use,
		timber_market,
		market,
		appraised_val,
		cad_ten_percent_cap,
		cad_assessed_val,
		arb_status,
		sales_dt,
		sales_price,
		appraiser,
		cad_sup_comment,
		exempt_prev_tax,
		exempt_prev_tax_unfrozen,
		ag_use_val,
		multi_owner,
		imp_new_value,
		land_new_value,
		run_id,
		@lSupNum_To,
		arb_dt,
		productivity_loss
	from dbo.shared_prop as sp with(nolock)
	where
		sp.shared_year = @lYear_From and
		sp.sup_num = @lSupNum_From and
		sp.pacs_prop_id = @lPropID_From


	if ( @@rowcount = 0 )
	begin
		-- No shared_prop rows copied, so no shared_prop_value rows should exist
		return(0)
	end


	insert dbo.shared_prop_value with(rowlock) (
		pacs_prop_id,
		shared_prop_id,
		shared_year,
		shared_cad_code,
		shared_value_id,
		state_code,
		shared_value,
		acres,
		ag_use_code,
		record_type,
		land_type_code,
		homesite_flag,
		ag_use_value,
		sup_num,
		hs_pct
	)
	select
		@lPropID_To,
		shared_prop_id,
		@lYear_To,
		shared_cad_code,
		shared_value_id,
		state_code,
		shared_value,
		acres,
		ag_use_code,
		record_type,
		land_type_code,
		homesite_flag,
		ag_use_value,
		@lSupNum_To,
		hs_pct
	from dbo.shared_prop_value as spv with(nolock)
	where
		spv.shared_year = @lYear_From and
		spv.sup_num = @lSupNum_From and
		spv.pacs_prop_id = @lPropID_From


	return(0)

GO

