CREATE TABLE [dbo].[_swhite_reet_20231204] (
    [reet_id]                     INT              NOT NULL,
    [excise_number]               INT              NULL,
    [status_cd]                   VARCHAR (10)     NULL,
    [reet_type_cd]                VARCHAR (12)     NULL,
    [instrument_type_cd]          CHAR (10)        NULL,
    [completion_date]             DATETIME         NULL,
    [sale_date]                   DATETIME         NULL,
    [partial_sale]                BIT              NOT NULL,
    [acreage_transferred]         NUMERIC (25, 4)  NULL,
    [percent_transferred]         NUMERIC (13, 10) NULL,
    [base_excise_due]             NUMERIC (14, 2)  NULL,
    [excise_amount_paid]          NUMERIC (14, 2)  NULL,
    [base_escrow_due]             NUMERIC (14, 2)  NULL,
    [recording_number]            VARCHAR (50)     NULL,
    [recorded_date]               DATETIME         NULL,
    [recd_last_update_by_user_id] INT              NULL,
    [recd_last_update_date]       DATETIME         NULL,
    [volume]                      CHAR (20)        NULL,
    [page]                        CHAR (20)        NULL,
    [metes_and_bounds]            VARCHAR (5000)   NULL,
    [is_mobile_home_moving]       BIT              NOT NULL,
    [mobile_home_movement_cd]     VARCHAR (10)     NULL,
    [created_compensated_tax]     BIT              NOT NULL,
    [payment_id]                  INT              NULL,
    [sale_price]                  NUMERIC (11, 2)  NULL,
    [pers_prop_included]          BIT              NOT NULL,
    [pers_prop_val]               NUMERIC (11, 2)  NULL,
    [pers_prop_description]       VARCHAR (255)    NULL,
    [exemption_claimed]           BIT              NOT NULL,
    [wac_number_type_cd]          VARCHAR (32)     NULL,
    [wac_reason]                  VARCHAR (255)    NULL,
    [tax_area_id]                 INT              NULL,
    [urban_growth_cd]             VARCHAR (10)     NULL,
    [exemption_amount]            NUMERIC (11, 2)  NULL,
    [agency_id]                   DECIMAL (4)      NULL,
    [imp_manual_entry]            BIT              NULL,
    [imp_partial_sale]            BIT              NULL,
    [imp_continuance_flag]        BIT              NULL,
    [imp_historic_flag]           BIT              NULL,
    [imp_forestland_flag]         BIT              NULL,
    [imp_open_space_flag]         BIT              NULL,
    [imp_city]                    VARCHAR (150)    NULL,
    [imp_current_use_flag]        BIT              NULL,
    [imp_unique_identifier]       DECIMAL (10)     NULL,
    [export_date]                 DATETIME         NULL,
    [recalc_status]               BIT              NULL,
    [comment]                     VARCHAR (500)    NULL,
    [hidden]                      BIT              NULL,
    [imp_timber_ag_flag]          BIT              NULL,
    [imp_multiple_locations]      BIT              NULL,
    [combined_sale_price]         NUMERIC (11, 2)  NULL,
    [personal_property_deduct]    NUMERIC (11, 2)  NULL,
    [exemption_claimed_deduct]    NUMERIC (11, 2)  NULL
);


GO

