CREATE TABLE [dbo].[imprv_detail_rms_estimate] (
    [prop_val_yr]                          NUMERIC (4)     NOT NULL,
    [sup_num]                              INT             NOT NULL,
    [sale_id]                              INT             NOT NULL,
    [prop_id]                              INT             NOT NULL,
    [imprv_id]                             INT             NOT NULL,
    [imprv_det_id]                         INT             NOT NULL,
    [tsRowVersion]                         ROWVERSION      NOT NULL,
    [ZipCode]                              VARCHAR (6)     NOT NULL,
    [ConstTypeID]                          SMALLINT        NOT NULL,
    [TypeID]                               SMALLINT        NOT NULL,
    [StyleIDPrimary]                       SMALLINT        NOT NULL,
    [StylePctPrimary]                      NUMERIC (5, 2)  NOT NULL,
    [StyleIDSecondary]                     SMALLINT        NULL,
    [TotalArea]                            INT             NOT NULL,
    [Units]                                INT             NOT NULL,
    [QualityID]                            NUMERIC (3, 2)  NOT NULL,
    [ConditionID]                          NUMERIC (3, 2)  NOT NULL,
    [DepreciationID]                       INT             NOT NULL,
    [EffectiveYearBuilt]                   INT             NOT NULL,
    [PhysFunPct]                           NUMERIC (5, 2)  NOT NULL,
    [PhysFunAmt]                           INT             NOT NULL,
    [PhysicalPct]                          NUMERIC (5, 2)  NOT NULL,
    [PhysicalAmt]                          INT             NOT NULL,
    [FunctionalPct]                        NUMERIC (5, 2)  NOT NULL,
    [FunctionalAmt]                        INT             NOT NULL,
    [ExternalPct]                          NUMERIC (5, 2)  NOT NULL,
    [ExternalAmt]                          INT             NOT NULL,
    [ApplyPctToRCN]                        BIT             NOT NULL,
    [RoundingValue]                        INT             NOT NULL,
    [TypicalLife]                          INT             NOT NULL,
    [LocalMultiplier]                      NUMERIC (3, 2)  NOT NULL,
    [LocalMultiplierOverride]              BIT             NOT NULL,
    [LocalMultiplierAdj]                   NUMERIC (5, 2)  NOT NULL,
    [ArchitectFee]                         NUMERIC (5, 2)  NOT NULL,
    [ArchitectFeeOverride]                 BIT             NOT NULL,
    [ReportDate]                           DATETIME        NOT NULL,
    [ReportDateOverride]                   BIT             NOT NULL,
    [SingleLineBackDate]                   DATETIME        NOT NULL,
    [SingleLineBackDateOverride]           BIT             NOT NULL,
    [BaseDate]                             DATETIME        NOT NULL,
    [BaseDateOverride]                     BIT             NOT NULL,
    [EffectiveAgeAdj]                      NUMERIC (5, 2)  NOT NULL,
    [DepreciationPctAdj]                   NUMERIC (5, 2)  NOT NULL,
    [EnergyAdj_ZoneItemID]                 INT             NOT NULL,
    [EnergyAdj_ZoneItemIDOverride]         BIT             NOT NULL,
    [FoundationAdj_ZoneItemID]             INT             NOT NULL,
    [FoundationAdj_ZoneItemIDOverride]     BIT             NOT NULL,
    [HillsideAdj_ZoneItemID]               INT             NOT NULL,
    [HillsideAdj_ZoneItemIDOverride]       BIT             NOT NULL,
    [SeismicAdj_ZoneItemID]                INT             NOT NULL,
    [SeismicAdj_ZoneItemIDOverride]        BIT             NOT NULL,
    [WindAdj_ZoneItemID]                   INT             NOT NULL,
    [WindAdj_ZoneItemIDOverride]           BIT             NOT NULL,
    [StoryWallHeight]                      SMALLINT        NOT NULL,
    [StoryWallHeightOverride]              BIT             NOT NULL,
    [RegionalMultiplier]                   NUMERIC (3, 2)  NOT NULL,
    [CostMultiplier]                       NUMERIC (3, 2)  NOT NULL,
    [IndexMultiplier]                      NUMERIC (3, 2)  NOT NULL,
    [TotalMultiplier]                      NUMERIC (3, 2)  NOT NULL,
    [ExtWallFactor]                        NUMERIC (5, 4)  NOT NULL,
    [BaseCostUnitPrice]                    NUMERIC (14, 2) NOT NULL,
    [ZoneAdj_Energy]                       NUMERIC (5, 2)  NOT NULL,
    [ZoneAdj_Foundation]                   NUMERIC (5, 2)  NOT NULL,
    [ZoneAdj_Hillside]                     NUMERIC (5, 2)  NOT NULL,
    [ZoneAdj_Seismic]                      NUMERIC (5, 2)  NOT NULL,
    [ZoneAdj_Wind]                         NUMERIC (5, 2)  NOT NULL,
    [BaseLoss]                             INT             NOT NULL,
    [PhysFunLoss]                          INT             NOT NULL,
    [PhysLoss]                             INT             NOT NULL,
    [FunctionalLoss]                       INT             NOT NULL,
    [ExternalLoss]                         INT             NOT NULL,
    [EstimateValueRCN]                     INT             NOT NULL,
    [EstimateValueRCNLD]                   INT             NOT NULL,
    [DeprPct]                              NUMERIC (5, 2)  NOT NULL,
    [EstimateValueNonRoundedRCNLD]         INT             NOT NULL,
    [EstimateValueSingleLineBackDateRCNLD] INT             NOT NULL,
    [QualityIDLower]                       AS              (CONVERT([smallint],[QualityID]-[QualityID]%(1.0),0)),
    [QualityIDUpper]                       AS              (CONVERT([smallint],case when [QualityID]%(1.0)=(0.0) then [QualityID]-[QualityID]%(1.0) else ([QualityID]-[QualityID]%(1.0))+(1) end,0)),
    [ConditionIDLower]                     AS              (CONVERT([smallint],[ConditionID]-[ConditionID]%(1.0),0)),
    [ConditionIDUpper]                     AS              (CONVERT([smallint],case when [ConditionID]%(1.0)=(0.0) then [ConditionID]-[ConditionID]%(1.0) else ([ConditionID]-[ConditionID]%(1.0))+(1) end,0)),
    CONSTRAINT [CPK_imprv_detail_rms_estimate] PRIMARY KEY CLUSTERED ([prop_val_yr] ASC, [sup_num] ASC, [sale_id] ASC, [prop_id] ASC, [imprv_id] ASC, [imprv_det_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CCK_imprv_detail_rms_estimate_ConditionID] CHECK ([ConditionID]>=(1.00) AND [ConditionID]<=(6.00)),
    CONSTRAINT [CCK_imprv_detail_rms_estimate_Percentages] CHECK ([StylePctPrimary]>=(0) AND [StylePctPrimary]<=(100) AND [PhysicalPct]>=(0) AND [PhysicalPct]<=(100) AND [FunctionalPct]>=(0) AND [FunctionalPct]<=(100) AND [ExternalPct]>=(0) AND [ExternalPct]<=(100)),
    CONSTRAINT [CCK_imprv_detail_rms_estimate_QualityID] CHECK ([QualityID]>=(1.00) AND [QualityID]<=(6.00)),
    CONSTRAINT [CFK_imprv_detail_rms_estimate_prop_val_yr_sup_num_sale_id_prop_id_imprv_id_imprv_det_id] FOREIGN KEY ([prop_val_yr], [sup_num], [sale_id], [prop_id], [imprv_id], [imprv_det_id]) REFERENCES [dbo].[imprv_detail] ([prop_val_yr], [sup_num], [sale_id], [prop_id], [imprv_id], [imprv_det_id]) ON DELETE CASCADE
);


GO

