CREATE TABLE [dbo].[income_sm_improvement_level_detail] (
    [event_id]                     INT             NOT NULL,
    [seq_num]                      INT             NOT NULL,
    [sup_num]                      INT             NOT NULL,
    [income_id]                    INT             NOT NULL,
    [prop_id]                      INT             NOT NULL,
    [imprv_id]                     INT             NOT NULL,
    [imprv_det_id]                 INT             NOT NULL,
    [included]                     BIT             NOT NULL,
    [override]                     BIT             NOT NULL,
    [copied]                       BIT             NOT NULL,
    [imprv_det_type_cd]            VARCHAR (10)    NULL,
    [imprv_det_meth_cd]            VARCHAR (10)    NULL,
    [floor_number]                 NUMERIC (4)     NULL,
    [floor_number_override]        BIT             NOT NULL,
    [primary_use_cd]               VARCHAR (10)    NULL,
    [lease_class]                  VARCHAR (10)    NULL,
    [effective_year_built]         NUMERIC (4)     NULL,
    [gross_building_area]          NUMERIC (18, 1) NULL,
    [gross_building_area_override] BIT             NOT NULL,
    [load_factor]                  NUMERIC (3)     NULL,
    [load_factor_override]         BIT             NOT NULL,
    [net_rentable_area]            NUMERIC (18, 1) NULL,
    [net_rentable_area_override]   BIT             NOT NULL,
    [rent_rate]                    NUMERIC (14, 2) NULL,
    [rent_rate_override]           BIT             NOT NULL,
    [occupancy_pct]                NUMERIC (3)     NULL,
    [occupancy_pct_override]       BIT             NOT NULL,
    [collection_loss]              NUMERIC (5, 2)  NULL,
    [collection_loss_override]     BIT             NOT NULL,
    [reimbursed_expenses]          NUMERIC (14)    NULL,
    [reimbursed_expenses_override] BIT             NOT NULL,
    [secondary_income]             NUMERIC (14)    NULL,
    [secondary_income_override]    BIT             NOT NULL,
    [gross_potential_income]       NUMERIC (14)    NULL,
    [effective_gross_income]       NUMERIC (14)    NULL,
    [expense_ratio]                NUMERIC (5, 2)  NULL,
    [expense_ratio_override]       BIT             NOT NULL,
    [expense_per_sqft]             NUMERIC (14, 2) NULL,
    [expense_per_sqft_override]    BIT             NOT NULL,
    [expense_overall]              NUMERIC (14)    NULL,
    [expense_overall_override]     BIT             NOT NULL,
    [cap_rate]                     NUMERIC (7, 4)  NULL,
    [cap_rate_override]            BIT             NOT NULL,
    [tax_rate]                     NUMERIC (7, 4)  NULL,
    [tax_rate_override]            BIT             NOT NULL,
    [overall_rate]                 NUMERIC (7, 4)  NULL,
    [net_operating_income]         NUMERIC (14)    NULL,
    [value]                        NUMERIC (14)    NULL,
    [imprv_desc]                   VARCHAR (255)   NULL,
    CONSTRAINT [CPK_income_sm_improvement_level_detail] PRIMARY KEY CLUSTERED ([event_id] ASC, [seq_num] ASC),
    CONSTRAINT [CFK_income_sm_improvement_level_detail_event] FOREIGN KEY ([event_id]) REFERENCES [dbo].[event] ([event_id])
);


GO

