CREATE TABLE [dbo].[mineral_import_capitol] (
    [run_id]                                 INT             NULL,
    [client_number]                          VARCHAR (3)     NULL,
    [prop_type]                              VARCHAR (1)     NULL,
    [account_number]                         VARCHAR (19)    NULL,
    [interest]                               NUMERIC (13, 6) NULL,
    [exemption_code]                         VARCHAR (1)     NULL,
    [agent_code]                             VARCHAR (3)     NULL,
    [sptb_code]                              VARCHAR (2)     NULL,
    [desc1]                                  VARCHAR (37)    NULL,
    [desc2]                                  VARCHAR (37)    NULL,
    [desc3]                                  VARCHAR (37)    NULL,
    [acres]                                  NUMERIC (14, 3) NULL,
    [owner_name]                             VARCHAR (30)    NULL,
    [owner_name2]                            VARCHAR (30)    NULL,
    [owner_addr1]                            VARCHAR (30)    NULL,
    [owner_addr2]                            VARCHAR (30)    NULL,
    [city]                                   VARCHAR (16)    NULL,
    [state]                                  VARCHAR (2)     NULL,
    [zip_code1]                              VARCHAR (5)     NULL,
    [zip_code2]                              VARCHAR (4)     NULL,
    [last_appraised]                         VARCHAR (2)     NULL,
    [real_value]                             INT             NULL,
    [productivity_value]                     INT             NULL,
    [improvement_value]                      INT             NULL,
    [personal_value]                         INT             NULL,
    [old_real_value]                         INT             NULL,
    [old_prod_value]                         INT             NULL,
    [old_imps_value]                         INT             NULL,
    [old_pers_value]                         INT             NULL,
    [ent1_type]                              VARCHAR (1)     NULL,
    [ent1_code]                              VARCHAR (1)     NULL,
    [ent1_pc]                                NUMERIC (9, 4)  NULL,
    [ent1_prod_floor]                        INT             NULL,
    [ent2_type]                              VARCHAR (1)     NULL,
    [ent2_code]                              VARCHAR (1)     NULL,
    [ent2_pc]                                NUMERIC (9, 4)  NULL,
    [ent2_prod_floor]                        INT             NULL,
    [ent3_type]                              VARCHAR (1)     NULL,
    [ent3_code]                              VARCHAR (1)     NULL,
    [ent3_pc]                                NUMERIC (9, 4)  NULL,
    [ent3_prod_floor]                        INT             NULL,
    [ent4_type]                              VARCHAR (1)     NULL,
    [ent4_code]                              VARCHAR (1)     NULL,
    [ent4_pc]                                NUMERIC (9, 4)  NULL,
    [ent4_prod_floor]                        INT             NULL,
    [ent5_type]                              VARCHAR (1)     NULL,
    [ent5_code]                              VARCHAR (1)     NULL,
    [ent5_pc]                                NUMERIC (9, 4)  NULL,
    [ent5_prod_floor]                        INT             NULL,
    [ent6_type]                              VARCHAR (1)     NULL,
    [ent6_code]                              VARCHAR (1)     NULL,
    [ent6_pc]                                NUMERIC (9, 4)  NULL,
    [ent6_prod_floor]                        INT             NULL,
    [ent7_type]                              VARCHAR (1)     NULL,
    [ent7_code]                              VARCHAR (1)     NULL,
    [ent7_pc]                                NUMERIC (9, 4)  NULL,
    [ent7_prod_floor]                        INT             NULL,
    [ent8_type]                              VARCHAR (1)     NULL,
    [ent8_code]                              VARCHAR (1)     NULL,
    [ent8_pc]                                NUMERIC (9, 4)  NULL,
    [ent8_prod_floor]                        INT             NULL,
    [ent9_type]                              VARCHAR (1)     NULL,
    [ent9_code]                              VARCHAR (1)     NULL,
    [ent9_pc]                                NUMERIC (9, 4)  NULL,
    [ent9_prod_floor]                        INT             NULL,
    [ent10_type]                             VARCHAR (1)     NULL,
    [ent10_code]                             VARCHAR (1)     NULL,
    [ent10_pc]                               NUMERIC (9, 4)  NULL,
    [ent10_prod_floor]                       INT             NULL,
    [ent11_type]                             VARCHAR (1)     NULL,
    [ent11_code]                             VARCHAR (1)     NULL,
    [ent11_pc]                               NUMERIC (9, 4)  NULL,
    [ent11_prod_floor]                       INT             NULL,
    [ent12_type]                             VARCHAR (1)     NULL,
    [ent12_code]                             VARCHAR (1)     NULL,
    [ent12_pc]                               NUMERIC (9, 4)  NULL,
    [ent12_prod_floor]                       INT             NULL,
    [appr_dist_pc]                           NUMERIC (9, 4)  NULL,
    [century]                                VARCHAR (1)     NULL,
    [tax_year]                               VARCHAR (4)     NULL,
    [value_uncertify]                        VARCHAR (1)     NULL,
    [ag_use_flag]                            VARCHAR (3)     NULL,
    [exemption_pc]                           NUMERIC (5, 2)  NULL,
    [old_exemption_pc]                       NUMERIC (5, 2)  NULL,
    [mortgage_code]                          VARCHAR (3)     NULL,
    [owner_client_number]                    VARCHAR (3)     NULL,
    [owner_number]                           VARCHAR (6)     NULL,
    [do_client_number]                       VARCHAR (3)     NULL,
    [do_property_type]                       INT             NULL,
    [do_district_number]                     VARCHAR (2)     NULL,
    [do_lease_number]                        VARCHAR (6)     NULL,
    [do_tract_number]                        VARCHAR (3)     NULL,
    [minimum_value]                          INT             NULL,
    [min_value_drop_flag]                    VARCHAR (1)     NULL,
    [client_information]                     VARCHAR (37)    NULL,
    [reserved_space]                         VARCHAR (11)    NULL,
    [new_imprv_value]                        INT             NULL,
    [sptb_code_2]                            VARCHAR (2)     NULL,
    [sptb_code_3]                            VARCHAR (2)     NULL,
    [sptb_code_4]                            VARCHAR (2)     NULL,
    [sptb_code_5]                            VARCHAR (2)     NULL,
    [hs_land_value]                          INT             NULL,
    [hs_imprv_value]                         INT             NULL,
    [non_prod_value]                         INT             NULL,
    [old_hs_land]                            INT             NULL,
    [old_hs_imprv]                           INT             NULL,
    [old_non_prod_value]                     INT             NULL,
    [late_ag_penalty]                        VARCHAR (1)     NULL,
    [old_late_ag_penalty]                    VARCHAR (1)     NULL,
    [veteran_exemption]                      INT             NULL,
    [old_vet_exemption]                      INT             NULL,
    [frozen_tax_amount]                      NUMERIC (13, 2) NULL,
    [frozen_tax_year]                        VARCHAR (2)     NULL,
    [old_exemption_code]                     VARCHAR (1)     NULL,
    [rendered_flag]                          VARCHAR (1)     NULL,
    [ent_extraction_type]                    VARCHAR (1)     NULL,
    [ent_extraction_code]                    VARCHAR (1)     NULL,
    [geo_id]                                 VARCHAR (50)    NULL,
    [legal_desc]                             VARCHAR (255)   NULL,
    [converted_acres]                        AS              (convert(varchar(15),[acres])),
    [property_number]                        AS              (substring([account_number],1,12)),
    [property_number_first]                  AS              (substring([account_number],1,1)),
    [industrial_property_number]             AS              (case [prop_type] when '1' then '' when '3' then '' else (substring([account_number],7,6)) end),
    [industrial_account_owner_number]        AS              (case [prop_type] when '1' then '' when '3' then '' else (substring([account_number],1,6)) end),
    [rrc_district_designation]               AS              (case [prop_type] when '1' then (substring([account_number],2,2)) else '' end),
    [rrc_lease_number]                       AS              (case [prop_type] when '1' then (substring([account_number],4,6)) else '' end),
    [division_order_tract_number_1]          AS              (case [prop_type] when '1' then (substring([account_number],10,1)) else '' end),
    [division_order_tract_number]            AS              (case [prop_type] when '1' then (substring([account_number],10,3)) else '' end),
    [lease_id]                               AS              (case [prop_type] when '1' then (substring([account_number],5,8)) else '' end),
    [interest_type]                          AS              (case [prop_type] when '1' then (substring([account_number],13,1)) else '' end),
    [rrc_lease_number_4]                     AS              (case [prop_type] when '1' then (substring([account_number],4,4)) else '' end),
    [rrc_number]                             AS              (case [prop_type] when '1' then (substring([account_number],5,5)) else '' end),
    [rrc_lease_number_last_2]                AS              (case [prop_type] when '1' then (substring([account_number],8,2)) else '' end),
    [mineral_account_owner_number]           AS              (case [prop_type] when '1' then (substring([account_number],14,6)) else '' end),
    [mineral_account_owner_number_last_5]    AS              (case [prop_type] when '1' then (substring([account_number],15,5)) else '' end),
    [maximum_market]                         AS              ([real_value] + [improvement_value] + [personal_value]),
    [converted_prop_type_cd]                 AS              (case [prop_type] when '1' then 'MN' when '3' then 'MN' else 'P' end),
    [computed_owner_no]                      AS              ([owner_number] + '-' + case [prop_type] when '1' then '1' when '3' then '1' else '2' end + '-' + [owner_client_number]),
    [exmpt_type_cd]                          AS              (case [exemption_code] when 'E' then 'EX' when 'Z' then 'EX' when 'P' then 'PC' when 'A' then 'AB' when 'M' then 'EX366' when 'F' then 'FR' else '' end),
    [sp_value_type]                          AS              (case [exemption_code] when 'P' then 'A' when 'A' then 'A' when 'F' then 'A' else '' end),
    [sp_value_option]                        AS              (case [exemption_code] when 'P' then 'M' when 'A' then 'M' when 'F' then 'M' else '' end),
    [non_zero_division_order_tract_number]   AS              (case [prop_type] when '1' then (case (substring([account_number],10,3)) when '000' then '' else (substring([account_number],10,3)) end) else '' end),
    [industrial_account_owner_number_last_4] AS              (case [prop_type] when '1' then '' when '3' then '' else (substring([account_number],3,4)) end),
    [converted_interest]                     AS              (case when ([interest] >= 1.0) then (convert(varchar(19),[interest])) else (substring(convert(varchar(19),[interest]),charindex('.',convert(varchar(19),[interest])),19)) end)
);


GO

CREATE NONCLUSTERED INDEX [idx_run_id]
    ON [dbo].[mineral_import_capitol]([run_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_agent_code]
    ON [dbo].[mineral_import_capitol]([agent_code] ASC) WITH (FILLFACTOR = 90);


GO

