CREATE TABLE [dbo].[mineral_import_wardlaw] (
    [run_id]                  INT             NULL,
    [xref_id]                 VARCHAR (20)    NULL,
    [prop_type]               VARCHAR (1)     NULL,
    [ptd_code]                VARCHAR (2)     NULL,
    [ptd_sub_code]            VARCHAR (2)     NULL,
    [des]                     VARCHAR (200)   NULL,
    [owner_id]                VARCHAR (12)    NULL,
    [prop_id]                 VARCHAR (12)    NULL,
    [lease_id]                VARCHAR (6)     NULL,
    [lease_name]              VARCHAR (50)    NULL,
    [lease_operator]          VARCHAR (50)    NULL,
    [interest]                NUMERIC (9, 8)  NULL,
    [interest_type]           VARCHAR (1)     NULL,
    [notice_val]              NUMERIC (11)    NULL,
    [property_val]            NUMERIC (11)    NULL,
    [sort_zip]                VARCHAR (7)     NULL,
    [international]           VARCHAR (1)     NULL,
    [name_sort]               VARCHAR (50)    NULL,
    [addr1]                   VARCHAR (40)    NULL,
    [addr2]                   VARCHAR (40)    NULL,
    [addr3]                   VARCHAR (40)    NULL,
    [addr4]                   VARCHAR (40)    NULL,
    [addr5]                   VARCHAR (40)    NULL,
    [addr6]                   VARCHAR (40)    NULL,
    [entity_01]               VARCHAR (10)    NULL,
    [entity_02]               VARCHAR (10)    NULL,
    [entity_03]               VARCHAR (10)    NULL,
    [entity_04]               VARCHAR (10)    NULL,
    [entity_05]               VARCHAR (10)    NULL,
    [entity_06]               VARCHAR (10)    NULL,
    [entity_07]               VARCHAR (10)    NULL,
    [entity_08]               VARCHAR (10)    NULL,
    [entity_09]               VARCHAR (10)    NULL,
    [entity_10]               VARCHAR (10)    NULL,
    [entity_11]               VARCHAR (10)    NULL,
    [entity_12]               VARCHAR (10)    NULL,
    [appr_val_01]             NUMERIC (11)    NULL,
    [appr_val_02]             NUMERIC (11)    NULL,
    [appr_val_03]             NUMERIC (11)    NULL,
    [appr_val_04]             NUMERIC (11)    NULL,
    [appr_val_05]             NUMERIC (11)    NULL,
    [appr_val_06]             NUMERIC (11)    NULL,
    [appr_val_07]             NUMERIC (11)    NULL,
    [appr_val_08]             NUMERIC (11)    NULL,
    [appr_val_09]             NUMERIC (11)    NULL,
    [appr_val_10]             NUMERIC (11)    NULL,
    [appr_val_11]             NUMERIC (11)    NULL,
    [appr_val_12]             NUMERIC (11)    NULL,
    [hb_01]                   NUMERIC (11)    NULL,
    [hb_02]                   NUMERIC (11)    NULL,
    [hb_03]                   NUMERIC (11)    NULL,
    [hb_04]                   NUMERIC (11)    NULL,
    [hb_05]                   NUMERIC (11)    NULL,
    [hb_06]                   NUMERIC (11)    NULL,
    [hb_07]                   NUMERIC (11)    NULL,
    [hb_08]                   NUMERIC (11)    NULL,
    [hb_09]                   NUMERIC (11)    NULL,
    [hb_10]                   NUMERIC (11)    NULL,
    [hb_11]                   NUMERIC (11)    NULL,
    [hb_12]                   NUMERIC (11)    NULL,
    [dp_01]                   NUMERIC (11)    NULL,
    [dp_02]                   NUMERIC (11)    NULL,
    [dp_03]                   NUMERIC (11)    NULL,
    [dp_04]                   NUMERIC (11)    NULL,
    [dp_05]                   NUMERIC (11)    NULL,
    [dp_06]                   NUMERIC (11)    NULL,
    [dp_07]                   NUMERIC (11)    NULL,
    [dp_08]                   NUMERIC (11)    NULL,
    [dp_09]                   NUMERIC (11)    NULL,
    [dp_10]                   NUMERIC (11)    NULL,
    [dp_11]                   NUMERIC (11)    NULL,
    [dp_12]                   NUMERIC (11)    NULL,
    [te_01]                   NUMERIC (11)    NULL,
    [te_02]                   NUMERIC (11)    NULL,
    [te_03]                   NUMERIC (11)    NULL,
    [te_04]                   NUMERIC (11)    NULL,
    [te_05]                   NUMERIC (11)    NULL,
    [te_06]                   NUMERIC (11)    NULL,
    [te_07]                   NUMERIC (11)    NULL,
    [te_08]                   NUMERIC (11)    NULL,
    [te_09]                   NUMERIC (11)    NULL,
    [te_10]                   NUMERIC (11)    NULL,
    [te_11]                   NUMERIC (11)    NULL,
    [te_12]                   NUMERIC (11)    NULL,
    [taxable_01]              NUMERIC (11)    NULL,
    [taxable_02]              NUMERIC (11)    NULL,
    [taxable_03]              NUMERIC (11)    NULL,
    [taxable_04]              NUMERIC (11)    NULL,
    [taxable_05]              NUMERIC (11)    NULL,
    [taxable_06]              NUMERIC (11)    NULL,
    [taxable_07]              NUMERIC (11)    NULL,
    [taxable_08]              NUMERIC (11)    NULL,
    [taxable_09]              NUMERIC (11)    NULL,
    [taxable_10]              NUMERIC (11)    NULL,
    [taxable_11]              NUMERIC (11)    NULL,
    [taxable_12]              NUMERIC (11)    NULL,
    [pct_01]                  NUMERIC (11, 8) NULL,
    [pct_02]                  NUMERIC (11, 8) NULL,
    [pct_03]                  NUMERIC (11, 8) NULL,
    [pct_04]                  NUMERIC (11, 8) NULL,
    [pct_05]                  NUMERIC (11, 8) NULL,
    [pct_06]                  NUMERIC (11, 8) NULL,
    [pct_07]                  NUMERIC (11, 8) NULL,
    [pct_08]                  NUMERIC (11, 8) NULL,
    [pct_09]                  NUMERIC (11, 8) NULL,
    [pct_10]                  NUMERIC (11, 8) NULL,
    [pct_11]                  NUMERIC (11, 8) NULL,
    [pct_12]                  NUMERIC (11, 8) NULL,
    [geo_id]                  VARCHAR (50)    NULL,
    [legal_desc]              VARCHAR (255)   NULL,
    [converted_prop_type]     AS              (case [prop_type] when 'R' then 'MN' when 'P' then 'P' else 'MN' end),
    [converted_interest_type] AS              (case [interest_type] when 'R' then 'RI' when 'O' then 'OR' when 'W' then 'WI' else '0' end),
    [converted_interest]      AS              (case [prop_type] when 'R' then (convert(numeric(9,8),[interest])) else (convert(numeric(9,8),0.00000000)) end),
    [pc_01]                   NUMERIC (11)    NULL,
    [pc_02]                   NUMERIC (11)    NULL,
    [pc_03]                   NUMERIC (11)    NULL,
    [pc_04]                   NUMERIC (11)    NULL,
    [pc_05]                   NUMERIC (11)    NULL,
    [pc_06]                   NUMERIC (11)    NULL,
    [pc_07]                   NUMERIC (11)    NULL,
    [pc_08]                   NUMERIC (11)    NULL,
    [pc_09]                   NUMERIC (11)    NULL,
    [pc_10]                   NUMERIC (11)    NULL,
    [pc_11]                   NUMERIC (11)    NULL,
    [pc_12]                   NUMERIC (11)    NULL,
    [fr_01]                   NUMERIC (11)    NULL,
    [fr_02]                   NUMERIC (11)    NULL,
    [fr_03]                   NUMERIC (11)    NULL,
    [fr_04]                   NUMERIC (11)    NULL,
    [fr_05]                   NUMERIC (11)    NULL,
    [fr_06]                   NUMERIC (11)    NULL,
    [fr_07]                   NUMERIC (11)    NULL,
    [fr_08]                   NUMERIC (11)    NULL,
    [fr_09]                   NUMERIC (11)    NULL,
    [fr_10]                   NUMERIC (11)    NULL,
    [fr_11]                   NUMERIC (11)    NULL,
    [fr_12]                   NUMERIC (11)    NULL,
    [agent_code]              VARCHAR (6)     NULL,
    [rendered_date]           VARCHAR (10)    NULL
);


GO

CREATE NONCLUSTERED INDEX [idx_run_id]
    ON [dbo].[mineral_import_wardlaw]([run_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_agent_code]
    ON [dbo].[mineral_import_wardlaw]([agent_code] ASC) WITH (FILLFACTOR = 90);


GO

