CREATE TABLE [dbo].[sales_comp_score] (
    [criteria_id]         INT             NOT NULL,
    [criteria_id_type]    VARCHAR (5)     NOT NULL,
    [school_entity]       INT             NULL,
    [city_entity]         INT             NULL,
    [state_cd]            INT             NULL,
    [region_cd]           INT             NULL,
    [abs_subdv_cd]        INT             NULL,
    [hood_cd]             INT             NULL,
    [subset_cd]           INT             NULL,
    [map_id]              INT             NULL,
    [class_cd]            INT             NULL,
    [appr_val]            INT             NULL,
    [appr_val_per]        INT             NULL,
    [living_area]         INT             NULL,
    [living_area_per]     INT             NULL,
    [year_built]          INT             NULL,
    [year_built_per]      INT             NULL,
    [imprv_up]            INT             NULL,
    [imprv_up_per]        NUMERIC (14, 2) NULL,
    [imprv_add_val]       INT             NULL,
    [imprv_add_val_per]   INT             NULL,
    [land_type_cd]        INT             NULL,
    [land_size_acres]     INT             NULL,
    [land_size_acres_per] NUMERIC (14, 4) NULL,
    [land_size_sqft]      INT             NULL,
    [land_size_sqft_per]  INT             NULL,
    [land_size_ff]        INT             NULL,
    [land_size_ff_per]    INT             NULL,
    [land_size_lot]       INT             NULL,
    [land_up]             INT             NULL,
    [land_up_per]         NUMERIC (14, 2) NULL,
    [sale_type]           INT             NULL,
    [sale_date]           INT             NULL,
    [sale_date_per]       INT             NULL,
    [sale_price]          INT             NULL,
    [sale_price_per]      INT             NULL,
    [subclass_cd]         INT             NULL,
    CONSTRAINT [CPK_sales_comp_score] PRIMARY KEY CLUSTERED ([criteria_id] ASC, [criteria_id_type] ASC) WITH (FILLFACTOR = 100)
);


GO

