CREATE TABLE [dbo].[transfer_delq_tax] (
    [prop_id]          INT             NULL,
    [prop_type_cd]     CHAR (5)        NULL,
    [geo_id]           CHAR (50)       NULL,
    [owner_id]         INT             NULL,
    [owner_name]       CHAR (70)       NULL,
    [addr_line1]       CHAR (60)       NULL,
    [addr_line2]       CHAR (60)       NULL,
    [addr_line3]       CHAR (60)       NULL,
    [addr_city]        CHAR (50)       NULL,
    [addr_state]       CHAR (50)       NULL,
    [addr_zip]         CHAR (50)       NULL,
    [addr_country_cd]  CHAR (5)        NULL,
    [addr_deliverable] CHAR (1)        NULL,
    [legal_desc]       CHAR (255)      NULL,
    [freeze_yr]        CHAR (4)        NULL,
    [freeze_ceiling]   CHAR (16)       NULL,
    [bill_id]          INT             NULL,
    [entity_id]        INT             NULL,
    [entity_cd]        CHAR (5)        NULL,
    [entity_tax_yr]    CHAR (4)        NULL,
    [stmnt_id]         INT             NULL,
    [assessed_val]     NUMERIC (14)    NULL,
    [taxable_val]      NUMERIC (14)    NULL,
    [effective_due_dt] CHAR (25)       NULL,
    [base_mno]         NUMERIC (14, 2) NULL,
    [base_ins]         NUMERIC (14, 2) NULL,
    [base_mno_due]     NUMERIC (14, 2) NULL,
    [base_ins_due]     NUMERIC (14, 2) NULL,
    [adjustment_code]  CHAR (10)       NULL,
    [suit_num]         CHAR (50)       NULL,
    [bankruptcy_num]   CHAR (50)       NULL,
    [judgement_date]   CHAR (25)       NULL,
    [judge_from_yr]    CHAR (4)        NULL,
    [judge_to_yr]      CHAR (4)        NULL,
    [mortgage_lender]  CHAR (70)       NULL,
    [mortgage_acct_no] CHAR (50)       NULL,
    [deferral_begin]   CHAR (25)       NULL,
    [deferral_end]     CHAR (25)       NULL,
    [mh_lein_date]     CHAR (25)       NULL,
    [mh_release_date]  CHAR (25)       NULL,
    [lKey]             INT             IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CPK_transfer_delq_tax] PRIMARY KEY CLUSTERED ([lKey] ASC) WITH (FILLFACTOR = 100)
);


GO

