CREATE TABLE [dbo].[transfer_appraisal_info] (
    [prop_id]                         INT              NOT NULL,
    [prop_type_cd]                    VARCHAR (5)      NULL,
    [prop_val_yr]                     NUMERIC (4)      NOT NULL,
    [sup_num]                         INT              NOT NULL,
    [sup_action]                      VARCHAR (2)      NULL,
    [sup_cd]                          VARCHAR (10)     NULL,
    [sup_desc]                        VARCHAR (500)    NULL,
    [geo_id]                          VARCHAR (50)     NULL,
    [owner_id]                        INT              NOT NULL,
    [owner_name]                      VARCHAR (70)     NULL,
    [pct_ownership]                   NUMERIC (13, 10) NULL,
    [addr_line1]                      VARCHAR (60)     NULL,
    [addr_line2]                      VARCHAR (60)     NULL,
    [addr_line3]                      VARCHAR (60)     NULL,
    [addr_city]                       VARCHAR (50)     NULL,
    [addr_state]                      VARCHAR (50)     NULL,
    [addr_country]                    VARCHAR (5)      NULL,
    [addr_zip]                        VARCHAR (50)     NULL,
    [ml_deliverable]                  VARCHAR (1)      NULL,
    [situs_display]                   VARCHAR (150)    NULL,
    [legal_desc]                      VARCHAR (255)    NULL,
    [legal_desc2]                     VARCHAR (255)    NULL,
    [legal_acreage]                   NUMERIC (14, 4)  NULL,
    [abs_subdv_cd]                    VARCHAR (10)     NULL,
    [hood_cd]                         VARCHAR (10)     NULL,
    [block]                           VARCHAR (50)     NULL,
    [tract_or_lot]                    VARCHAR (50)     NULL,
    [land_hstd_val]                   NUMERIC (14)     NULL,
    [land_non_hstd_val]               NUMERIC (14)     NULL,
    [imprv_hstd_val]                  NUMERIC (14)     NULL,
    [imprv_non_hstd_val]              NUMERIC (14)     NULL,
    [ag_use_val]                      NUMERIC (14)     NULL,
    [ag_market]                       NUMERIC (14)     NULL,
    [timber_use]                      NUMERIC (14)     NULL,
    [timber_market]                   NUMERIC (14)     NULL,
    [appraised_val]                   NUMERIC (14)     NULL,
    [ten_percent_cap]                 NUMERIC (14)     NULL,
    [assessed_val]                    NUMERIC (14)     NULL,
    [freeze_yr]                       VARCHAR (4)      NULL,
    [freeze_ceiling]                  VARCHAR (16)     NULL,
    [arb_protest_flag]                VARCHAR (1)      NULL,
    [deed_num]                        INT              NULL,
    [deed_book_id]                    VARCHAR (20)     NULL,
    [deed_book_page]                  VARCHAR (20)     NULL,
    [deed_dt]                         VARCHAR (25)     NULL,
    [mortgage_co_id]                  INT              NULL,
    [mortgage_co_name]                VARCHAR (70)     NULL,
    [mortgage_acct_id]                VARCHAR (50)     NULL,
    [jan1_owner_id]                   INT              NULL,
    [jan1_owner_name]                 VARCHAR (70)     NULL,
    [jan1_addr_line1]                 VARCHAR (60)     NULL,
    [jan1_addr_line2]                 VARCHAR (60)     NULL,
    [jan1_addr_line3]                 VARCHAR (60)     NULL,
    [jan1_addr_city]                  VARCHAR (50)     NULL,
    [jan1_addr_state]                 VARCHAR (50)     NULL,
    [jan1_addr_country]               VARCHAR (5)      NULL,
    [jan1_addr_zip]                   VARCHAR (50)     NULL,
    [jan1_ml_deliverable]             VARCHAR (1)      NULL,
    [hs_exempt]                       VARCHAR (1)      NULL,
    [ov65_exempt]                     VARCHAR (1)      NULL,
    [ov65_prorate_begin]              VARCHAR (25)     NULL,
    [ov65_prorate_end]                VARCHAR (25)     NULL,
    [ov65s_exempt]                    VARCHAR (1)      NULL,
    [dp_exempt]                       VARCHAR (1)      NULL,
    [dv1_exempt]                      VARCHAR (1)      NULL,
    [dv1s_exempt]                     VARCHAR (1)      NULL,
    [dv2_exempt]                      VARCHAR (1)      NULL,
    [dv2s_exempt]                     VARCHAR (1)      NULL,
    [dv3_exempt]                      VARCHAR (1)      NULL,
    [dv3s_exempt]                     VARCHAR (1)      NULL,
    [dv4_exempt]                      VARCHAR (1)      NULL,
    [dv4s_exempt]                     VARCHAR (1)      NULL,
    [ex_exempt]                       VARCHAR (1)      NULL,
    [ex_prorate_begin]                VARCHAR (25)     NULL,
    [ex_prorate_end]                  VARCHAR (25)     NULL,
    [fz_exempt]                       VARCHAR (1)      NULL,
    [ab_exempt]                       VARCHAR (1)      NULL,
    [en_exempt]                       VARCHAR (1)      NULL,
    [fr_exempt]                       VARCHAR (1)      NULL,
    [ht_exempt]                       VARCHAR (1)      NULL,
    [pro_exempt]                      VARCHAR (1)      NULL,
    [pc_exempt]                       VARCHAR (1)      NULL,
    [so_exempt]                       VARCHAR (1)      NULL,
    [ex366_exempt]                    VARCHAR (1)      NULL,
    [ch_exempt]                       VARCHAR (1)      NULL,
    [imprv_state_cd]                  VARCHAR (10)     NULL,
    [land_state_cd]                   VARCHAR (10)     NULL,
    [personal_state_cd]               VARCHAR (10)     NULL,
    [mineral_state_cd]                VARCHAR (10)     NULL,
    [land_acres]                      NUMERIC (18, 4)  NULL,
    [entity_agent_id]                 INT              NULL,
    [entity_agent_name]               VARCHAR (70)     NULL,
    [entity_agent_addr_line1]         VARCHAR (60)     NULL,
    [entity_agent_addr_line2]         VARCHAR (60)     NULL,
    [entity_agent_addr_line3]         VARCHAR (60)     NULL,
    [entity_agent_city]               VARCHAR (50)     NULL,
    [entity_agent_state]              VARCHAR (50)     NULL,
    [entity_agent_zip]                VARCHAR (50)     NULL,
    [ca_agent_id]                     INT              NULL,
    [ca_agent_name]                   VARCHAR (70)     NULL,
    [ca_agent_addr_line1]             VARCHAR (60)     NULL,
    [ca_agent_addr_line2]             VARCHAR (60)     NULL,
    [ca_agent_addr_line3]             VARCHAR (60)     NULL,
    [ca_agent_city]                   VARCHAR (50)     NULL,
    [ca_agent_state]                  VARCHAR (50)     NULL,
    [ca_agent_zip]                    VARCHAR (50)     NULL,
    [arb_agent_id]                    INT              NULL,
    [arb_agent_name]                  VARCHAR (70)     NULL,
    [arb_agent_addr_line1]            VARCHAR (60)     NULL,
    [arb_agent_addr_line2]            VARCHAR (60)     NULL,
    [arb_agent_addr_line3]            VARCHAR (60)     NULL,
    [arb_agent_city]                  VARCHAR (50)     NULL,
    [arb_agent_state]                 VARCHAR (50)     NULL,
    [arb_agent_zip]                   VARCHAR (50)     NULL,
    [mineral_type_of_int]             VARCHAR (5)      NULL,
    [mineral_int_pct]                 NUMERIC (13, 10) NULL,
    [productivity_use_code]           VARCHAR (3)      NULL,
    [entities]                        VARCHAR (40)     NULL,
    [timber_78_market]                NUMERIC (14)     NULL,
    [ag_late_loss]                    NUMERIC (14)     NULL,
    [late_freeport_penalty]           NUMERIC (14)     NULL,
    [delivery_point]                  CHAR (2)         NULL,
    [carrier_route]                   CHAR (5)         NULL,
    [check_digit]                     CHAR (2)         NULL,
    [dba]                             VARCHAR (40)     NULL,
    [freeze_transfer_flag]            CHAR (1)         NULL,
    [previous_tax]                    NUMERIC (14)     NULL,
    [previous_tax_unfrozen]           NUMERIC (14)     NULL,
    [transfer_percentage]             NUMERIC (9, 6)   NULL,
    [market_value]                    NUMERIC (14)     NULL,
    [mh_label]                        CHAR (20)        NULL,
    [mh_serial]                       CHAR (20)        NULL,
    [mh_model]                        CHAR (20)        NULL,
    [jan1_confidential_flag]          CHAR (1)         NULL,
    [current_owner_confidential_flag] CHAR (1)         NULL,
    [confidential_name]               CHAR (70)        NULL,
    [ov65_deferral_date]              DATETIME         NULL,
    [dp_deferral_date]                DATETIME         NULL,
    CONSTRAINT [CPK_transfer_appraisal_info] PRIMARY KEY CLUSTERED ([prop_id] ASC, [prop_val_yr] ASC, [sup_num] ASC, [owner_id] ASC) WITH (FILLFACTOR = 100)
);


GO

