apiVersion: v1
kind: Secret
metadata:      
  name: {{ include "terrafusion-backend.fullname" . }}-secret
  labels:
    {{- include "terrafusion-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
