# TerraFusion County Security Policy Application Script
# Auto-generated by AI for CJIS Level 4 Compliance

param(
    [string]$InstallDir = "$env:ProgramFiles\TerraFusionPermit",
    [string]$LogPath = "$env:TEMP\TerraFusion_Security.log"
)

# Initialize logging
function Write-SecurityLog {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] [$Level] $Message"
    Add-Content -Path $LogPath -Value $logEntry
    Write-Host $logEntry
}

Write-SecurityLog "Starting TerraFusion County Security Policy Application"

try {
    # Set execution policy for security
    Write-SecurityLog "Configuring PowerShell execution policy"
    Set-ExecutionPolicy Restricted -Force -Scope LocalMachine
    
    # Configure Windows Firewall rules
    Write-SecurityLog "Configuring firewall rules for TerraFusion"
    
    # Allow TerraFusion database connections
    New-NetFirewallRule -DisplayName "TerraFusion Database" -Direction Inbound -Action Allow -Program "$InstallDir\pgsql\bin\postgres.exe" -Profile Domain,Private
    New-NetFirewallRule -DisplayName "TerraFusion HTTPS" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 443 -Profile Domain,Private
    New-NetFirewallRule -DisplayName "TerraFusion API" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3003 -Profile Domain,Private
    
    # Disable unnecessary network protocols
    Write-SecurityLog "Disabling insecure network protocols"
    Disable-NetAdapterBinding -Name "*" -ComponentID ms_tcpip6 -ErrorAction SilentlyContinue
    
    # Configure registry security settings
    Write-SecurityLog "Applying registry security policies"
    
    # Disable Local Account Token Filter Policy (CJIS requirement)
    reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 0 /f
    
    # Configure audit policies
    reg add "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" /v MaxSize /t REG_DWORD /d 0x6400000 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Security" /v Retention /t REG_DWORD /d 0 /f
    
    # Set password policies
    Write-SecurityLog "Configuring password policies"
    net accounts /minpwlen:12 /maxpwage:90 /minpwage:1 /uniquepw:12
    
    # Configure TerraFusion specific settings
    Write-SecurityLog "Configuring TerraFusion application settings"
    
    # Create TerraFusion registry entries
    reg add "HKLM\SOFTWARE\TerraFusion\Security" /v EncryptionLevel /t REG_SZ /d "AES-256-GCM" /f
    reg add "HKLM\SOFTWARE\TerraFusion\Security" /v AuditEnabled /t REG_DWORD /d 1 /f
    reg add "HKLM\SOFTWARE\TerraFusion\Security" /v SessionTimeout /t REG_DWORD /d 900 /f
    reg add "HKLM\SOFTWARE\TerraFusion\Security" /v ComplianceLevel /t REG_SZ /d "CJIS-Level-4" /f
    
    # Configure file permissions
    Write-SecurityLog "Setting secure file permissions"
    icacls "$InstallDir" /grant "Administrators:(OI)(CI)F" /grant "SYSTEM:(OI)(CI)F" /remove "Users" /T
    
    # Enable audit logging
    Write-SecurityLog "Enabling audit logging"
    auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable
    auditpol /set /category:"Privilege Use" /success:enable /failure:enable
    auditpol /set /category:"System" /success:enable /failure:enable
    
    # Configure TLS settings
    Write-SecurityLog "Configuring TLS security settings"
    
    # Disable TLS 1.0 and 1.1
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /t REG_DWORD /d 0 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server" /v Enabled /t REG_DWORD /d 0 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /t REG_DWORD /d 0 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server" /v Enabled /t REG_DWORD /d 0 /f
    
    # Enable TLS 1.2 and 1.3
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client" /v Enabled /t REG_DWORD /d 1 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server" /v Enabled /t REG_DWORD /d 1 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client" /v Enabled /t REG_DWORD /d 1 /f
    reg add "HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server" /v Enabled /t REG_DWORD /d 1 /f
    
    # Create scheduled task for maintenance
    Write-SecurityLog "Creating maintenance scheduled task"
    $action = New-ScheduledTaskAction -Execute "$InstallDir\maintenance\run_maintenance.exe"
    $trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Saturday -At 3:00AM
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount
    Register-ScheduledTask -TaskName "TerraFusion Maintenance" -Action $action -Trigger $trigger -Principal $principal
    
    # Set up Windows Event Log monitoring
    Write-SecurityLog "Configuring event log monitoring"
    wevtutil sl Security /ms:104857600
    wevtutil sl Application /ms:52428800
    wevtutil sl System /ms:52428800
    
    # Configure SMB security
    Write-SecurityLog "Securing SMB protocol"
    Set-SmbServerConfiguration -RequireSecuritySignature $true -EnableSecuritySignature $true -EncryptData $true -Force
    
    # Disable SMB v1
    Disable-WindowsOptionalFeature -Online -FeatureName smb1protocol -NoRestart
    
    Write-SecurityLog "TerraFusion County Security Policy Application completed successfully"
    
    # Create completion marker
    New-Item -Path "$InstallDir\security_applied.marker" -ItemType File -Force
    
} catch {
    Write-SecurityLog "ERROR: Security policy application failed: $($_.Exception.Message)" "ERROR"
    exit 1
}

Write-SecurityLog "Security policy application completed. System may require restart for all changes to take effect."