CREATE TABLE [import].[temptable__1439] (
    [PERMIT TYPE]   NVARCHAR (MAX) NULL,
    [PERMIT NUMBER] NVARCHAR (MAX) NULL,
    [ISSUE DATE]    NVARCHAR (MAX) NULL,
    [SITE ADDRESS]  NVARCHAR (MAX) NULL,
    [DESCRIPTION]   NVARCHAR (MAX) NULL,
    [VALUATION]     NVARCHAR (MAX) NULL,
    [PARCEL #]      NVARCHAR (MAX) NULL,
    [Column1]       NVARCHAR (MAX) NULL
);


GO

