
import os
from intel.utilities import DEBUG, Logger
from intel.utilities.ErrorHandlers import general_error_logger

class CADRGFileExtensions(object):

    _logger: Logger

    @general_error_logger
    def __init__(self):

        super().__init__()

        self._logger = Logger()
        self._logger.create_logger(self.__class__.__name__)
        if DEBUG:
            self._logger.debug(f"DEBUG is {DEBUG}")

        self._horizontal_geographic_zone: list[str] = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "j"]

        self._cadrg_ext_base = {"TLM_100K": ".sc",
                        "TLM_10K": ".su",
                        "TLM_200K": ".sr",
                        "TLM_24K": ".sq",
                        "TLM_250K": ".ss",
                        "TLM_25K": ".st",
                        "TLM_50K": ".sl",
                        "City Graphics": ".cg",
                        "City Graphics_10000": ".c1",
                        "City Graphics_10560": ".c2",
                        "City Graphics_11000": ".c3",
                        "City Graphics_11800": ".c4",
                        "City Graphics_12000": ".c5",
                        "City Graphics_12500": ".c6",
                        "City Graphics_12800": ".c7",
                        "City Graphics_14000": ".c8",
                        "City Graphics_14700": ".c9",
                        "City Graphics_15000": ".ca",
                        "City Graphics_15500": ".cb",
                        "City Graphics_16000": ".cc",
                        "City Graphics_16666": ".cd",
                        "City Graphics_17000": ".ce",
                        "City Graphics_17500": ".cf",
                        "City Graphics_18000": ".ch",
                        "City Graphics_20000": ".cj",
                        "City Graphics_21000": ".ck",
                        "City Graphics_21120": ".cl",
                        "City Graphics_22000": ".cn",
                        "City Graphics_23000": ".cp",
                        "City Graphics_25000": ".cq",
                        "City Graphics_26000": ".cr",
                        "City Graphics_35000": ".cs",
                        "City Graphics_36000": ".ct",
                        "Coastal Charts": ".co",
                        "Combat Charts": ".a6",
                        "Combat Charts": ".cm",
                        "Combat Charts_10000": ".a1",
                        "Combat Charts_100000": ".a4",
                        "Combat Charts_12500": ".a5",
                        "Combat Charts_25000": ".a2",
                        "Combat Charts_50000": ".a3",
                        "Global Navigation Charts": ".gn",
                        "Harbor and Approach Charts": ".ha",
                        "Helicopter Route Chart": ".vh",
                        "Helicopter Route Chart Inset": ".v1",
                        "Helicopter Route Chart Inset": ".v2",
                        "Helicopter Route Chart Inset": ".v3",
                        "Helicopter Route Chart Inset": ".v4",
                        "High Flying Chart": ".ow",
                        "IFR Enroute Area": ".y9",
                        "IFR Enroute Area": ".ya",
                        "IFR Enroute Area": ".yb",
                        "IFR Enroute Area": ".yc",
                        "IFR Enroute Area": ".yd",
                        "IFR Enroute Area": ".ye",
                        "IFR Enroute Area": ".yf",
                        "IFR Enroute Area": ".yi",
                        "IFR Enroute Area": ".yj",
                        "IFR Enroute Area": ".yz",
                        "IFR Enroute High": ".xd",
                        "IFR Enroute High": ".xe",
                        "IFR Enroute High": ".xf",
                        "IFR Enroute High": ".xg",
                        "IFR Enroute High": ".xh",
                        "IFR Enroute High": ".xi",
                        "IFR Enroute High": ".xj",
                        "IFR Enroute High": ".xk",
                        "IFR Enroute High/Low": ".z8",
                        "IFR Enroute High/Low": ".za",
                        "IFR Enroute High/Low": ".zb",
                        "IFR Enroute High/Low": ".zc",
                        "IFR Enroute High/Low": ".zd",
                        "IFR Enroute High/Low": ".ze",
                        "IFR Enroute High/Low": ".zf",
                        "IFR Enroute High/Low": ".zg",
                        "IFR Enroute High/Low": ".zh",
                        "IFR Enroute High/Low": ".zi",
                        "IFR Enroute High/Low": ".zj",
                        "IFR Enroute High/Low": ".zk",
                        "IFR Enroute High/Low": ".zt",
                        "IFR Enroute High/Low": ".zv",
                        "IFR Enroute High/Low": ".zz",
                        "IFR Enroute Low": ".wa",
                        "IFR Enroute Low": ".wb",
                        "IFR Enroute Low": ".wc",
                        "IFR Enroute Low": ".wd",
                        "IFR Enroute Low": ".we",
                        "IFR Enroute Low": ".wf",
                        "IFR Enroute Low": ".wg",
                        "IFR Enroute Low": ".wh",
                        "IFR Enroute Low": ".wi",
                        "IFR Enroute Low": ".wk",
                        "Image City Maps_10000": ".k2",
                        "Image City Maps_10560": ".k3",
                        "Image City Maps_12500": ".k7",
                        "Image City Maps_12800": ".k8",
                        "Image City Maps_15000": ".kb",
                        "Image City Maps_16666": ".ke",
                        "Image City Maps_21120": ".km",
                        "Image City Maps_25000": ".kr",
                        "Image City Maps_26000": ".ks",
                        "Image City Maps_36000": ".ku",
                        "Image City Maps_8000": ".k1",
                        "Jet Navigation Chart": ".jn",
                        "Joint Operations Graphic": ".jg",
                        "Joint Operations Graphic - Air": ".ja",
                        "Joint Operations Graphic - Radar": ".jr",
                        "Low Flying Chart - 1": ".l1",
                        "Low Flying Chart - 2": ".l2",
                        "Low Flying Chart - 3": ".l3",
                        "Low Flying Chart - 4": ".l4",
                        "Low Flying Chart - 5": ".l5",
                        "Low Flying Chart - Day": ".lf",
                        "Low Flying Chart - Night": ".ln",
                        "Military Installation Maps - 1": ".m1",
                        "Military Installation Maps - 2": ".m2",
                        "Military Installation Maps_100000": ".mj",
                        "Military Installation Maps_25000": ".mh",
                        "Military Installation Maps_50000": ".mi",
                        "Miscellaneous Maps and Charts": ".mm",
                        "Naval Range Operating Area Chart": ".oa",
                        "North Atlantic Route Chart": ".eg",
                        "Operational Navigation Chart": ".on",
                        "Operational Planning Graphic": ".jo",
                        "Range Charts": "r2",
                        "Range Charts": "r3",
                        "Range Charts": "r4",
                        "Range Charts": "r5",
                        "Riverine Map_100000": ".rw",
                        "Riverine Map_50000": ".rv",
                        "Russian General Staff Maps": ".rc",
                        "Russian General Staff Maps": ".rl",
                        "Russian General Staff Maps": ".rr",
                        "Series 200 Air Target Chart": ".at",
                        "Special Military Map - Overlay": ".p1",
                        "Special Military Map - Overlay": ".p5",
                        "Special Military Map - Overlay": ".p9",
                        "Special Military Map - Overlay": ".pd",
                        "Special Military Map - Overlay": ".ph",
                        "Special Military Map - Overlay": ".pl",
                        "Special Military Map - Overlay": ".pp",
                        "Special Military Map - Overlay": ".ps",
                        "Special Military Purpose": ".p2",
                        "Special Military Purpose": ".p3",
                        "Special Military Purpose": ".p4",
                        "Special Military Purpose": ".p6",
                        "Special Military Purpose": ".p7",
                        "Special Military Purpose": ".p8",
                        "Special Military Purpose": ".pa",
                        "Special Military Purpose": ".pb",
                        "Special Military Purpose": ".pc",
                        "Special Military Purpose": ".pe",
                        "Special Military Purpose": ".pf",
                        "Special Military Purpose": ".pg",
                        "Special Military Purpose": ".pi",
                        "Special Military Purpose": ".pj",
                        "Special Military Purpose": ".pk",
                        "Special Military Purpose": ".pm",
                        "Special Military Purpose": ".pn",
                        "Special Military Purpose": ".po",
                        "Special Military Purpose": ".pq",
                        "Special Military Purpose": ".pr",
                        "Special Military Purpose": ".pt",
                        "Special Military Purpose": ".pu",
                        "Special Military Purpose": ".pv",
                        "Tactical Pilotage Chart": ".tp",
                        "Topographic Line Map": ".uv",
                        "Topographic Line Map_10000": ".tu",
                        "Topographic Line Map_100000": ".tc",
                        "Topographic Line Map_200000": ".tr",
                        "Topographic Line Map_24000": ".tq",
                        "Topographic Line Map_25000": ".tt",
                        "Topographic Line Map_250000": ".ts",
                        "Topographic Line Map_50000": ".tl",
                        "Topographic Line Map Other_10000": ".uu",
                        "Topographic Line Map Other_100000": ".uc",
                        "Topographic Line Map Other_200000": ".ur",
                        "Topographic Line Map Other_25000": ".ut",
                        "Topographic Line Map Other_250000": ".us",
                        "Topographic Line Map Other_50000": ".ul",
                        "Transit Flying Chart - 1": ".f1",
                        "Transit Flying Chart - 2": ".f2",
                        "Transit Flying Chart - 3": ".f3",
                        "Transit Flying Chart - 4": ".f4",
                        "Transit Flying Chart - 5": ".f5",
                        "Transit Flying Chart - Day": ".tf",
                        "Transit Flying Chart - Night": ".tn",
                        "VFR Helicopter Route Chart": ".oh",
                        "VFR Sectional": ".es",
                        "VFR Sectional Insets": ".et",
                        "VFR Terminal Area Chart": ".vt",
                        "VFR Terminal Area Chart": "vu",
                        "Visual Navigation Chart": ".vn",
                        }

        self._cadrg_extensions: list[str] = []

        self._generateList()

    @property
    def fileExtensions(self) -> list[str]:
        return self._cadrg_extensions

    @general_error_logger
    def _generateList(self):

        for k, v in self._cadrg_ext_base.items():
            for zone in self._horizontal_geographic_zone:
                self._cadrg_extensions.append(f"{v}{zone}")
        return self._cadrg_extensions
