#!/usr/bin/env python3
"""Phase 4B Disposition: terra-forge-rebuild (114 assets).

Terminal classification for every asset. No asset remains pending.
Rubric: ported | declined | deferred-with-rationale.

Disposition rules:
  ported     — unique business logic, valuation math, calibration, regression,
               ETL/data-contract, irreplaceable integration, core schemas
  declined   — duplicate, obsolete, generated scaffolding, dead experiment,
               local tooling, secrets-contaminated, already-absorbed
  deferred   — depends on ADR-TBD-4/5, upstream not ported, security blocks,
               canonical home not yet decidable
"""
from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime, timezone

REPO_NAME = "terra-forge-rebuild"
NOW = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# ─── Disposition decisions for all 114 assets ──────────────────────────────

DISPOSITIONS: dict[str, dict] = {
    # ═══ REGRESSION / CALIBRATION MATH (core valuation logic) ═══
    "TFR-001": {
        "status": "ported",
        "disposition_reason": "Unique OLS regression solver with Gauss-Jordan inversion, t-distribution CDF, F-statistic. Core mass appraisal calibration math.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.regression.ols",
        "target_home": "backend/TerraFusion.AI/Regression/OlsSolver.cs",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "No secrets in source."},
    },
    "TFR-002": {
        "status": "ported",
        "disposition_reason": "Multiple regression engine with ANOVA, Cook's distance, VIF, Durbin-Watson, Q-Q diagnostic generation. Irreplaceable valuation math.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.regression.multiple",
        "target_home": "backend/TerraFusion.AI/Regression/MultipleRegressionEngine.cs",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-003": {
        "status": "ported",
        "disposition_reason": "Calibration orchestration hook: invokes regression per neighborhood, manages variable selection, emits change receipts. Core calibration behavior.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.calibration.run",
        "target_home": "backend/TerraFusion.AI/Calibration/CalibrationOrchestrator.cs",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ PACS SYNC CONTRACTS (irreplaceable integration logic) ═══
    "TFR-004": {
        "status": "ported",
        "disposition_reason": "PACS Benton County sync contract: identity doctrine, 6 sync product definitions, watermark tracking, PII redaction rules, delta strategies. Irreplaceable integration contract.",
        "parity_mode": "exact",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.contract",
        "target_home": "backend/TerraFusion.Core/Sync/Contracts/PacsBentonContract.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "PII redaction rules present — contract defines redaction, does not contain PII."},
    },
    "TFR-005": {
        "status": "ported",
        "disposition_reason": "PACS True Automation field mapping: column-level mappings from CIAPS schema. Irreplaceable integration reference.",
        "parity_mode": "exact",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.field_mapping",
        "target_home": "backend/TerraFusion.Core/Sync/Contracts/PacsFieldMappings.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-006": {
        "status": "ported",
        "disposition_reason": "PACS workflow mappings for appeals, permits, and exemption data flows. Irreplaceable integration reference.",
        "parity_mode": "exact",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.workflow_mapping",
        "target_home": "backend/TerraFusion.Core/Sync/Contracts/PacsWorkflowMappings.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-007": {
        "status": "ported",
        "disposition_reason": "PACS quality gates: IAAO-style integrity checks. Core data quality enforcement.",
        "parity_mode": "exact",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.quality_gates",
        "target_home": "backend/TerraFusion.Core/Sync/QualityGates/PacsQualityGates.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-008": {
        "status": "ported",
        "disposition_reason": "SQL Server query helpers: ROW_NUMBER() CTE generator for PostgreSQL compatibility. Required by PACS connector.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.sql_helpers",
        "target_home": "backend/TerraFusion.Data/Helpers/SqlServerHelpers.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ RATIO ANALYSIS / VEI / STATISTICS (unique valuation analytics) ═══
    "TFR-009": {
        "status": "ported",
        "disposition_reason": "VEI data hooks: study period management, assessment ratio tier grouping. Unique IAAO equity analysis logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei",
        "target_home": "frontend/src/services/forge/veiService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-010": {
        "status": "ported",
        "disposition_reason": "Ratio analysis hook: COD, PRD, PRB computation, tier medians, tier slopes. Core IAAO compliance math.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.ratio_analysis",
        "target_home": "frontend/src/services/forge/ratioAnalysisService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-011": {
        "status": "ported",
        "disposition_reason": "VEI Dashboard: full equity analysis UI with metric cards, tier plots, COD/PRD trends. Unique IAAO-grade visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.dashboard",
        "target_home": "frontend/src/pages/forge/statistics/VEIDashboard.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-012": {
        "status": "ported",
        "disposition_reason": "Tier ratio bar chart: visualizes median assessment ratios by value quartile. Unique statistical visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.tier_plot",
        "target_home": "frontend/src/pages/forge/statistics/charts/TierRatioPlot.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-013": {
        "status": "ported",
        "disposition_reason": "COD trend chart: displays Coefficient of Dispersion over time. IAAO compliance visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.cod_trend",
        "target_home": "frontend/src/pages/forge/statistics/charts/CODTrendChart.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-014": {
        "status": "ported",
        "disposition_reason": "PRD trend chart: displays Price-Related Differential over time. IAAO compliance visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.prd_trend",
        "target_home": "frontend/src/pages/forge/statistics/charts/PRDTrendChart.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-015": {
        "status": "ported",
        "disposition_reason": "VEI drilldown dialogs: COD drilldown, PRD drilldown, tier slope drilldown. Unique analytical depth.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.drilldown",
        "target_home": "frontend/src/pages/forge/statistics/drilldown/",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-016": {
        "status": "ported",
        "disposition_reason": "VEI metric cards, summary panel, export actions, skeleton, empty state, neighborhood filters. Unique statistical UI components.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.vei.ui",
        "target_home": "frontend/src/pages/forge/statistics/components/",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ SYNC ENGINE / SAGA / ETL (unique data pipeline logic) ═══
    "TFR-017": {
        "status": "ported",
        "disposition_reason": "Sync engine: delta detection (insert/update/delete), SAGA workflow runners. Core ETL data pipeline.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.engine",
        "target_home": "backend/TerraFusion.Core/Sync/SyncEngine.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-018": {
        "status": "ported",
        "disposition_reason": "SAGA orchestrator: multi-step workflow execution with compensation/rollback. Core ETL resilience pattern.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.saga",
        "target_home": "backend/TerraFusion.Core/Sync/SagaOrchestrator.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-019": {
        "status": "ported",
        "disposition_reason": "Contract-driven sync runtime: orchestrates PACS product extraction using contract definitions. Core ETL execution.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.runtime",
        "target_home": "backend/TerraFusion.Core/Sync/SyncRuntime.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-020": {
        "status": "ported",
        "disposition_reason": "Source lane registry: manages multiple data source connectors. Core multi-source ETL architecture.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.registry",
        "target_home": "backend/TerraFusion.Core/Sync/ConnectorRegistry.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-021": {
        "status": "ported",
        "disposition_reason": "Year doctrine discovery: detects how legacy CAMA systems represent assessment years. Irreplaceable PACS integration logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.year_doctrine",
        "target_home": "backend/TerraFusion.Core/Sync/YearDoctrine.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-022": {
        "status": "ported",
        "disposition_reason": "Read-only connector interface: universal contract for all data sources. Core integration architecture.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.connector_interface",
        "target_home": "backend/TerraFusion.Core/Sync/Connectors/IConnector.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-023": {
        "status": "ported",
        "disposition_reason": "PACS read-only SQL connector: SQL statement validator blocking write operations. Core PACS integration safety.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.pacs_connector",
        "target_home": "backend/TerraFusion.Core/Sync/Connectors/PacsConnector.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ VALUATION APPROACH LOGIC (cost, income, comp grid) ═══
    "TFR-024": {
        "status": "ported",
        "disposition_reason": "Cost schedule hooks: CRUD for cost schedules and depreciation tables, pure cost calculation functions. Core valuation math.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-valuation",
        "canonical_capability": "forge.valuation.cost_approach",
        "target_home": "frontend/src/services/forge/costApproachService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-025": {
        "status": "ported",
        "disposition_reason": "Income approach hook: cap rate, GRM calculation, NOI computation. Core valuation math. Complements canonical IncomeValuationPanel.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-valuation",
        "canonical_capability": "forge.valuation.income_approach",
        "target_home": "frontend/src/services/forge/incomeApproachService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-026": {
        "status": "ported",
        "disposition_reason": "Comp grid hook: fetches parcels by neighborhood with qualified sales and ratio data. Core comparable sales logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-valuation",
        "canonical_capability": "forge.valuation.comp_grid",
        "target_home": "frontend/src/services/forge/compGridService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ OS SHARED INFRASTRUCTURE (audit, write-lane, resilience) ═══
    "TFR-027": {
        "status": "ported",
        "disposition_reason": "TerraTrace audit event service: append-only event spine per ADR-0003. Core constitutional audit infrastructure.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.audit.trace",
        "target_home": "frontend/src/services/terraTrace.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-028": {
        "status": "ported",
        "disposition_reason": "Write-lane enforcement: constitutional matrix mapping domains to suite owners. Core governance infrastructure per ADR-0002.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.governance.write_lane",
        "target_home": "frontend/src/services/writeLane.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-029": {
        "status": "ported",
        "disposition_reason": "Circuit breaker: failure threshold, half-open recovery. Shared resilience pattern for all edge function calls.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.resilience.circuit_breaker",
        "target_home": "frontend/src/services/circuitBreaker.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-030": {
        "status": "ported",
        "disposition_reason": "PACS multi-table ETL processor: detects True Automation CSV table types from headers. Irreplaceable PACS import logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.etl.pacs_multi_table",
        "target_home": "backend/TerraFusion.Core/Sync/ETL/PacsMultiTableProcessor.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ SUITE SERVICE CORES (constitutional suite services) ═══
    "TFR-031": {
        "status": "ported",
        "disposition_reason": "Forge suite service: parcel characteristic updates with write-lane enforcement and TerraTrace audit. Core suite boundary implementation.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-valuation",
        "canonical_capability": "forge.service.core",
        "target_home": "frontend/src/services/suites/forgeService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-032": {
        "status": "ported",
        "disposition_reason": "Dais suite service: appeal status updates, permit/exemption workflow. Core Dais domain logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.service.core",
        "target_home": "frontend/src/services/suites/daisService.ts",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-033": {
        "status": "ported",
        "disposition_reason": "Atlas suite service: GIS feature/boundary upserts, layer management. Core Atlas domain logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "atlas-gis",
        "canonical_capability": "atlas.service.core",
        "target_home": "frontend/src/services/suites/atlasService.ts",
        "owner_suite": "TerraAtlas",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-034": {
        "status": "ported",
        "disposition_reason": "Dossier suite service: document management, narrative creation, packet assembly. Core Dossier domain logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dossier.service.core",
        "target_home": "frontend/src/services/suites/dossierService.ts",
        "owner_suite": "TerraDossier",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ EXPORT / INGEST / DATA SERVICES ═══
    "TFR-035": {
        "status": "ported",
        "disposition_reason": "Export service: CSV/JSON export generation for parcels, assessments, sales, appeals. Core data export capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.export.engine",
        "target_home": "frontend/src/services/exportService.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-036": {
        "status": "ported",
        "disposition_reason": "Ingest service: batch parcel insert/upsert with conflict handling for PACS import. Core ETL ingestion.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ingest.batch",
        "target_home": "backend/TerraFusion.Core/Sync/IngestService.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-037": {
        "status": "ported",
        "disposition_reason": "Metric catalog: single source of truth for every key number in the OS. Core governance/observability infrastructure.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.trust.metric_catalog",
        "target_home": "frontend/src/lib/metrics/metricCatalog.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ GOVERNANCE / NAVIGATION (scaffolding — superseded by canonical OS) ═══
    "TFR-038": {
        "status": "declined",
        "disposition_reason": "Information Architecture map: navigation config superseded by canonical OS module registry (generatedModules.ts, suiteRegistry.ts).",
        "parity_mode": "superseded",
        "replacement_ref": "frontend/src/config/generatedModules.ts",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-039": {
        "status": "ported",
        "disposition_reason": "Constitution guards: runtime navigation validation, stale module ID detection. Unique governance enforcement logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.governance.constitution_guards",
        "target_home": "frontend/src/lib/constitutionGuards.ts",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-040": {
        "status": "declined",
        "disposition_reason": "Mission constitution: registry of correction missions with scope/priority/SLA. Config scaffolding — no business logic, superseded by canonical OS governance.",
        "parity_mode": "superseded",
        "replacement_ref": "canonical OS governance layer",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ AVM / AI VALUATION (unique AI logic) ═══
    "TFR-041": {
        "status": "ported",
        "disposition_reason": "AVM training edge function: computes features, trains model, stores coefficients. Core AI valuation capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.avm.train",
        "target_home": "backend/TerraFusion.AI/AVM/AvmTrainingService.cs",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-042": {
        "status": "ported",
        "disposition_reason": "AI valuation edge function: LLM-powered property valuation analysis supporting multiple approaches. Unique AI capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.avm.ai_valuation",
        "target_home": "backend/TerraFusion.AI/AVM/AiValuationService.cs",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-043": {
        "status": "ported",
        "disposition_reason": "Defense narrative edge function: LLM-powered narrative generation for BOE defense. Unique Dais AI capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.narrative.defense",
        "target_home": "backend/TerraFusion.AI/Narratives/DefenseNarrativeService.cs",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ ADVANCED ANALYTICS / CALIBRATION HOOKS ═══
    "TFR-044": {
        "status": "ported",
        "disposition_reason": "Advanced analytics hooks: ratio trend sparklines, assessment value distribution, trend forecasting. Unique analytical depth.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.advanced_analytics",
        "target_home": "frontend/src/services/forge/advancedAnalyticsService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-045": {
        "status": "ported",
        "disposition_reason": "Segment discovery: factor importance analysis from regression coefficients, neighborhood segmentation. Core calibration capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-regression",
        "canonical_capability": "forge.calibration.segment_discovery",
        "target_home": "frontend/src/services/forge/segmentDiscoveryService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-046": {
        "status": "ported",
        "disposition_reason": "Data quality scoring engine: per-parcel completeness scoring with weighted field groups. Unique data quality logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.quality.scoring_engine",
        "target_home": "frontend/src/services/dataQualityScoring.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ DAIS WORKFLOW COMPONENTS ═══
    "TFR-047": {
        "status": "ported",
        "disposition_reason": "Field studio local store: IndexedDB-backed offline queue for field observations. Unique offline-first Dais capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.field.offline_store",
        "target_home": "frontend/src/services/fieldStore.ts",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ FORGE VALUATION UI COMPONENTS ═══
    "TFR-048": {
        "status": "ported",
        "disposition_reason": "Cost approach calculator: batch apply, depreciation curve editor, year-based. Core Forge valuation UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.cost_approach.ui",
        "target_home": "frontend/src/pages/workbench/tabs/forge/CostApproach.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-049": {
        "status": "ported",
        "disposition_reason": "Cost schedule editor: base cost per sqft by property class and quality grade. Core cost approach reference data UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.cost_schedule.ui",
        "target_home": "frontend/src/pages/workbench/tabs/forge/components/CostScheduleEditor.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-050": {
        "status": "ported",
        "disposition_reason": "Depreciation curve editor: age-based depreciation percentages. Core cost approach reference data UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.depreciation.ui",
        "target_home": "frontend/src/pages/workbench/tabs/forge/components/DepreciationCurveEditor.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-051": {
        "status": "ported",
        "disposition_reason": "Income approach calculator, batch income apply panel, income data manager. Core Forge valuation UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.income_approach.ui",
        "target_home": "frontend/src/pages/workbench/tabs/forge/IncomeApproach.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ REGRESSION UI ═══
    "TFR-052": {
        "status": "ported",
        "disposition_reason": "Regression control panel, calibration diagnostics, scatter plot, coefficient table. Core Forge regression UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.regression.ui",
        "target_home": "frontend/src/pages/forge/regression/RegressionControlPanel.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-053": {
        "status": "ported",
        "disposition_reason": "Regression studio dashboard: ANOVA panel, diagnostic plots, model comparison. Core Forge regression workspace.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.regression.studio",
        "target_home": "frontend/src/pages/forge/regression/RegressionStudio.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-054": {
        "status": "ported",
        "disposition_reason": "Regression diagnostic charts: Cook's distance, Q-Q plot, residual plot, leverage plot. Unique statistical visualizations.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.regression.diagnostic_charts",
        "target_home": "frontend/src/pages/forge/regression/charts/",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ DAIS WORKFLOW UI ═══
    "TFR-055": {
        "status": "ported",
        "disposition_reason": "Appeals workflow: creation, timeline, audit log, status transitions. Core TerraDais appeal management.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.workflow.appeals",
        "target_home": "frontend/src/pages/dais/AppealsWorkflow.tsx",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-056": {
        "status": "ported",
        "disposition_reason": "Permits workflow, exemptions workflow, notices panel, certification dashboard. Core TerraDais operational workflows.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.workflow.permits",
        "target_home": "frontend/src/pages/dais/WorkflowComponents.tsx",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ ATLAS GIS ═══
    "TFR-057": {
        "status": "ported",
        "disposition_reason": "GeoEquity map and dashboard: equity heatmap, parcel detail, GIS layers. Core Atlas spatial equity visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "atlas-gis",
        "canonical_capability": "atlas.equity.map",
        "target_home": "frontend/src/pages/atlas/GeoEquityDashboard.tsx",
        "owner_suite": "TerraAtlas",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ CALIBRATION UI ═══
    "TFR-058": {
        "status": "ported",
        "disposition_reason": "Segment revaluation dashboard: calibration, equity rebalancing. Core Forge calibration UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.calibration.segment_revaluation",
        "target_home": "frontend/src/pages/forge/calibration/SegmentRevaluationDashboard.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-059": {
        "status": "ported",
        "disposition_reason": "Segment discovery dashboard: factor importance, neighborhood heatmap, segment assignment. Core Forge analytical UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.calibration.segment_discovery.ui",
        "target_home": "frontend/src/pages/forge/calibration/SegmentDiscoveryDashboard.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ WORKBENCH (superseded by canonical) ═══
    "TFR-060": {
        "status": "declined",
        "disposition_reason": "Property workbench: parcel detail editor with suite tab navigation. Superseded by canonical PropertyWorkbench in terrafusion_os_1.0.",
        "parity_mode": "superseded",
        "replacement_ref": "frontend/src/pages/workbench/PropertyWorkbench.tsx",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ OS SHARED UTILITIES ═══
    "TFR-061": {
        "status": "ported",
        "disposition_reason": "Change receipt utility: generates immutable audit records. Core TerraTrace companion.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.audit.change_receipt",
        "target_home": "frontend/src/lib/changeReceipt.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-062": {
        "status": "declined",
        "disposition_reason": "Query invalidation utility: centralized cache invalidation helpers. Generic React Query utility — no unique business logic.",
        "parity_mode": "superseded",
        "replacement_ref": "standard TanStack Query invalidation patterns",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ MORE FORGE UI (AVM, anatomy, costforge) ═══
    "TFR-063": {
        "status": "ported",
        "disposition_reason": "AVM studio dashboard: AI valuation panel, feature engineering, model comparison. Core Forge AI valuation UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.avm.studio",
        "target_home": "frontend/src/pages/forge/avm/AVMStudio.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-064": {
        "status": "ported",
        "disposition_reason": "Valuation anatomy dashboard: 3D valuation canvas, valuation details panel. Unique visualization.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.anatomy",
        "target_home": "frontend/src/pages/forge/anatomy/ValuationAnatomy.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ MORE DAIS WORKFLOW ═══
    "TFR-065": {
        "status": "ported",
        "disposition_reason": "Roll readiness dashboard: certification pipeline, readiness scoring. Core TerraDais certification workflow.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.certification.readiness",
        "target_home": "frontend/src/pages/dais/RollReadiness.tsx",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ CANON SYNC/INGEST UI ═══
    "TFR-066": {
        "status": "ported",
        "disposition_reason": "Sync dashboard: conflict resolution queue, data source registry, SAGA runner UI. Core TerraCanon operational UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.dashboard",
        "target_home": "frontend/src/pages/canon/SyncDashboard.tsx",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-067": {
        "status": "ported",
        "disposition_reason": "IDS command center: ingest wizard, PACS multi-table import, inventory/quality/rollback panels. Core TerraCanon operational UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ids.command_center",
        "target_home": "frontend/src/pages/canon/IDSCommandCenter.tsx",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-068": {
        "status": "ported",
        "disposition_reason": "Parcel import wizard: column mapper, import preview, learning scoreboard. Unique data import UX.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ingest.import_wizard",
        "target_home": "frontend/src/pages/canon/ImportWizard.tsx",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-069": {
        "status": "ported",
        "disposition_reason": "Trust registry page, provenance badges, explainable wrapper. Core OS trust/governance UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.trust.registry",
        "target_home": "frontend/src/pages/shared/TrustRegistry.tsx",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ DAIS PROOF / DOSSIER ═══
    "TFR-070": {
        "status": "ported",
        "disposition_reason": "Defense packet generator, model receipt, TerraTrace activity feed. Core Dais proof assembly.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.proof.defense_packet",
        "target_home": "frontend/src/pages/dais/DefensePacket.tsx",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-071": {
        "status": "ported",
        "disposition_reason": "Dossier components: document upload, documents panel, narrative drafting, packet assembly. Core TerraDossier domain UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dossier.records.ui",
        "target_home": "frontend/src/pages/dossier/PacketAssembly.tsx",
        "owner_suite": "TerraDossier",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ SKETCH MODULE ═══
    "TFR-072": {
        "status": "ported",
        "disposition_reason": "Sketch module: measurement plan, plan trace, sketch builder. Unique parcel sketch capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.sketch.module",
        "target_home": "frontend/src/pages/forge/sketch/SketchModule.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-073": {
        "status": "ported",
        "disposition_reason": "Field studio dashboard and inspection panel. Core TerraDais field inspection management.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.field.studio",
        "target_home": "frontend/src/pages/dais/FieldStudio.tsx",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ DATABASE MIGRATIONS ═══
    "TFR-074": {
        "status": "ported",
        "disposition_reason": "Supabase migrations: 60+ migration files defining complete schema. Core schema reference for canonical EF Core migration.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.schema.migrations",
        "target_home": "docs/reference/supabase-schema/",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "Review for hardcoded connection strings."},
    },

    # ═══ TESTS (port alongside tested code) ═══
    "TFR-075": {
        "status": "ported",
        "disposition_reason": "PACS contract test: validates contract internal consistency. Test asset — ports alongside TFR-004.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.contract.test",
        "target_home": "backend/TerraFusion.API.Tests/Sync/PacsBentonContractTests.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-076": {
        "status": "ported",
        "disposition_reason": "Sync engine tests: validates delta detection, SAGA execution. Test asset — ports alongside TFR-017.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.engine.test",
        "target_home": "backend/TerraFusion.API.Tests/Sync/SyncEngineTests.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-077": {
        "status": "ported",
        "disposition_reason": "SAGA orchestrator tests: validates multi-step execution, compensation, rollback. Test asset — ports alongside TFR-018.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.saga.test",
        "target_home": "backend/TerraFusion.API.Tests/Sync/SagaOrchestratorTests.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-078": {
        "status": "ported",
        "disposition_reason": "TerraTrace test: validates audit event emission. Test asset — ports alongside TFR-027.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.audit.trace.test",
        "target_home": "frontend/tests/services/terraTrace.test.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-079": {
        "status": "ported",
        "disposition_reason": "Write lane test: validates domain ownership assertions. Test asset — ports alongside TFR-028.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.governance.write_lane.test",
        "target_home": "frontend/tests/services/writeLane.test.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-080": {
        "status": "ported",
        "disposition_reason": "Sync connector test: validates registry, connector capabilities, year doctrine. Test asset — ports alongside TFR-020/021.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.test",
        "target_home": "backend/TerraFusion.API.Tests/Sync/ConnectorTests.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ EDGE FUNCTION SHARED / ADMIN ═══
    "TFR-081": {
        "status": "ported",
        "disposition_reason": "Shared auth module for Supabase edge functions: JWT validation, county ID extraction. Irreplaceable auth pattern for edge function migration.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-admin",
        "canonical_capability": "os.auth.edge_functions",
        "target_home": "backend/TerraFusion.Security/Auth/EdgeFunctionAuth.cs",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "JWT secret handling must be reviewed during actual port."},
    },
    "TFR-082": {
        "status": "declined",
        "disposition_reason": "Shared error handling for Supabase edge functions: safe error responses. Generic utility — no unique business logic.",
        "parity_mode": "superseded",
        "replacement_ref": "standard .NET exception handling middleware",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ MORE EDGE FUNCTIONS ═══
    "TFR-083": {
        "status": "ported",
        "disposition_reason": "Draft notice edge function: generates assessment change notices for property owners. Core Dais notice-writing logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "dais-workflow",
        "canonical_capability": "dais.notices.draft",
        "target_home": "backend/TerraFusion.AI/Notices/DraftNoticeService.cs",
        "owner_suite": "TerraDais",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-084": {
        "status": "ported",
        "disposition_reason": "GIS parse edge function: processes GIS file uploads for spatial data ingestion. Core Atlas spatial ingest.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "atlas-gis",
        "canonical_capability": "atlas.gis.parse",
        "target_home": "backend/TerraFusion.Core/GIS/GisParseService.cs",
        "owner_suite": "TerraAtlas",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-085": {
        "status": "ported",
        "disposition_reason": "GIS sync/ArcGIS parcel sync/import/polygon ingest edge functions. Core Atlas spatial data pipeline.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "atlas-gis",
        "canonical_capability": "atlas.gis.sync",
        "target_home": "backend/TerraFusion.Core/GIS/GisSyncService.cs",
        "owner_suite": "TerraAtlas",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "ArcGIS service URLs may need credential review."},
    },
    "TFR-086": {
        "status": "ported",
        "disposition_reason": "Ingest process edge function: server-side data ingestion processing pipeline. Core Canon ingest.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ingest.process",
        "target_home": "backend/TerraFusion.Core/Sync/IngestProcessor.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-087": {
        "status": "declined",
        "disposition_reason": "System health edge function: generic health check endpoint. Superseded by canonical .NET health checks in TerraFusion.API.",
        "parity_mode": "superseded",
        "replacement_ref": "backend/TerraFusion.API health check middleware",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-088": {
        "status": "deferred-with-rationale",
        "disposition_reason": "TerraPilot chat edge function: AI chat assistant for assessor workflows. Placement depends on TerraGPT suite architecture which is not yet constitutionally scoped.",
        "parity_mode": "none",
        "replacement_ref": "none",
        "migration_batch": "",
        "canonical_capability": "os.pilot.chat",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "architectural",
        "unblock_condition": "TerraGPT suite architecture scoped and constitutional charter written",
        "decision_owner": "founder",
        "security_review": {"status": "pending", "remediation_note": "LLM API key handling must be reviewed."},
    },
    "TFR-089": {
        "status": "ported",
        "disposition_reason": "Assessor/statewide scrape edge functions: web scraping for assessor data collection. Unique ETL capability.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ingest.scrape",
        "target_home": "backend/TerraFusion.Core/Sync/Scrapers/AssessorScraper.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-090": {
        "status": "ported",
        "disposition_reason": "County setup edge function: initializes county configuration and initial data structures. Core multi-county onboarding logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-admin",
        "canonical_capability": "os.admin.county_setup",
        "target_home": "backend/TerraFusion.Core/Admin/CountySetupService.cs",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-091": {
        "status": "ported",
        "disposition_reason": "Schedule scrape edge function: manages scheduled web scraping jobs. Unique ETL scheduling logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.ingest.schedule_scrape",
        "target_home": "backend/TerraFusion.Core/Sync/Scrapers/ScrapingScheduler.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-092": {
        "status": "ported",
        "disposition_reason": "Historical ratio trend: multi-year ratio statistics and appeals-by-value-tier analysis. Unique IAAO time-series analytics.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.historical_trend",
        "target_home": "frontend/src/services/forge/historicalRatioService.ts",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ TYPES / SCHEMAS ═══
    "TFR-093": {
        "status": "declined",
        "disposition_reason": "Supabase client config and auto-generated TypeScript types. Generated scaffolding — will be regenerated from canonical EF Core schema.",
        "parity_mode": "superseded",
        "replacement_ref": "auto-generated from EF Core DbContext",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-094": {
        "status": "ported",
        "disposition_reason": "Parcel 360 types: comprehensive type definitions for trace events, write domains, suite operations. Core domain model reference.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.types.parcel360",
        "target_home": "frontend/src/types/parcel360.ts",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-095": {
        "status": "ported",
        "disposition_reason": "Sync types: type definitions for sync operations, delta records, saga execution. Core ETL type contract.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.types.sync",
        "target_home": "frontend/src/types/sync.ts",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ COSTFORGE (unique but needs review) ═══
    "TFR-096": {
        "status": "ported",
        "disposition_reason": "CostForge dashboard: quantum metrics grid, sacred balance panel. Unique cost approach visualization — may need UI rationalization but contains real cost model display logic.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.costforge.ui",
        "target_home": "frontend/src/pages/forge/cost/CostForgeDashboard.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ TOOLING / STYLING (no business logic) ═══
    "TFR-097": {
        "status": "declined",
        "disposition_reason": "SVG accessibility checker script. Local tooling — no business logic. Standard a11y tools are available.",
        "parity_mode": "none",
        "replacement_ref": "standard WCAG tooling (axe, lighthouse)",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-098": {
        "status": "declined",
        "disposition_reason": "3D color palette config. Styling config with no business logic. Design system is canonical in terrafusion_os_1.0.",
        "parity_mode": "superseded",
        "replacement_ref": "canonical design system in terrafusion_os_1.0",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ ADMIN / COUNTY MANAGEMENT ═══
    "TFR-099": {
        "status": "ported",
        "disposition_reason": "Admin dashboard: county switcher, data quality dashboard, security audit dashboard. Core OS Admin operational UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-admin",
        "canonical_capability": "os.admin.dashboard",
        "target_home": "frontend/src/pages/admin/AdminDashboard.tsx",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ MORE FORGE UI ═══
    "TFR-100": {
        "status": "ported",
        "disposition_reason": "Cost ratio analysis: compares cost approach values against sales ratios. Core Forge analytical component.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.cost_ratio",
        "target_home": "frontend/src/pages/forge/cost/CostRatioAnalysis.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-101": {
        "status": "ported",
        "disposition_reason": "Scenario mode: what-if analysis for valuation approaches. Unique Forge analytical tool.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.scenarios",
        "target_home": "frontend/src/pages/forge/scenarios/ScenarioMode.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-102": {
        "status": "ported",
        "disposition_reason": "Batch cost apply panel: applies cost approach values in bulk across neighborhoods. Core Forge batch operation.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.cost_batch",
        "target_home": "frontend/src/pages/forge/cost/BatchCostApplyPanel.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ SYNC CONNECTORS ═══
    "TFR-103": {
        "status": "ported",
        "disposition_reason": "ODBC connector stub: interface for legacy Access .mdb connectivity. Required for True Automation legacy support.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.odbc_connector",
        "target_home": "backend/TerraFusion.Core/Sync/Connectors/OdbcConnector.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "Connection string handling must be reviewed during port."},
    },
    "TFR-104": {
        "status": "ported",
        "disposition_reason": "SQL Server connector: read-only SQL Server connector for PACS direct access. Core PACS integration.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "canon-sync",
        "canonical_capability": "canon.sync.sqlserver_connector",
        "target_home": "backend/TerraFusion.Core/Sync/Connectors/SqlServerConnector.cs",
        "owner_suite": "TerraCanon",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": "SQL injection prevention must be verified during port."},
    },

    # ═══ ATLAS UI ═══
    "TFR-105": {
        "status": "ported",
        "disposition_reason": "Geometry health dashboard: parcel polygon linkage stats and spatial data quality monitoring. Core Atlas operational UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "atlas-gis",
        "canonical_capability": "atlas.geometry.health",
        "target_home": "frontend/src/pages/atlas/GeometryHealth.tsx",
        "owner_suite": "TerraAtlas",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ SHARED UI (export, watchlist) ═══
    "TFR-106": {
        "status": "ported",
        "disposition_reason": "Export center: UI for configurable dataset exports. Core shared data export UI.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.export.center",
        "target_home": "frontend/src/pages/shared/ExportCenter.tsx",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-107": {
        "status": "ported",
        "disposition_reason": "Parcel comparison panel: side-by-side comparison of characteristics and values. Unique Forge analytical tool.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-ui",
        "canonical_capability": "forge.valuation.comparison",
        "target_home": "frontend/src/pages/forge/comparison/ParcelComparison.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-108": {
        "status": "ported",
        "disposition_reason": "Watchlist panel: tracks parcels of interest for ongoing monitoring. Cross-suite shared workflow tool.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "os-shared",
        "canonical_capability": "os.watchlist.panel",
        "target_home": "frontend/src/pages/shared/WatchlistPanel.tsx",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ ONBOARDING / AUTH / TRUST MODE (scaffolding) ═══
    "TFR-109": {
        "status": "declined",
        "disposition_reason": "Onboarding wizard: initial setup UX flow. Not domain business logic — UX scaffolding. Canonical OS will have its own onboarding.",
        "parity_mode": "superseded",
        "replacement_ref": "canonical OS onboarding (future)",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-110": {
        "status": "declined",
        "disposition_reason": "Auth context with Supabase: authentication flow. Superseded by canonical .NET auth in TerraFusion.Security.",
        "parity_mode": "superseded",
        "replacement_ref": "backend/TerraFusion.Security/ + canonical frontend auth",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-111": {
        "status": "declined",
        "disposition_reason": "Trust mode context: beginner/power-user toggle. UX preference toggle with no domain logic.",
        "parity_mode": "none",
        "replacement_ref": "none",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ NAVIGATION / DASHBOARD (superseded by canonical shell) ═══
    "TFR-112": {
        "status": "declined",
        "disposition_reason": "Navigation components: sovereign header, sidebar, dock launcher. Superseded by canonical OS shell navigation.",
        "parity_mode": "superseded",
        "replacement_ref": "canonical OS shell in terrafusion_os_1.0",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "OS Admin",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
    "TFR-113": {
        "status": "declined",
        "disposition_reason": "Dashboard components: suite hub, command briefing, daily briefing. Superseded by canonical OS dashboard.",
        "parity_mode": "superseded",
        "replacement_ref": "canonical OS dashboard in terrafusion_os_1.0",
        "migration_batch": "",
        "canonical_capability": "",
        "target_home": "",
        "owner_suite": "Shared",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },

    # ═══ ANALYTICS DASHBOARD ═══
    "TFR-114": {
        "status": "ported",
        "disposition_reason": "Analytics dashboard: clustering panel, forecast panel, outlier detection. Unique Forge statistical workspace.",
        "parity_mode": "adapted",
        "replacement_ref": "none",
        "migration_batch": "forge-statistics",
        "canonical_capability": "forge.statistics.analytics_dashboard",
        "target_home": "frontend/src/pages/forge/statistics/AdvancedAnalytics.tsx",
        "owner_suite": "TerraForge",
        "blocker_type": "",
        "unblock_condition": "",
        "decision_owner": "founder",
        "security_review": {"status": "passed", "remediation_note": ""},
    },
}


def apply_dispositions(manifest_path: Path) -> None:
    """Apply terminal dispositions to terra-forge-rebuild assets in the manifest."""
    with manifest_path.open("r", encoding="utf-8") as f:
        manifest = json.load(f)

    # Find the repo
    repo = None
    for r in manifest["repos"]:
        if r["name"] == REPO_NAME:
            repo = r
            break

    if repo is None:
        raise RuntimeError(f"Repo {REPO_NAME} not found in manifest")

    # Add repo-level disposition timestamps
    repo["disposition_started_at"] = NOW
    repo["repo_status"] = "migration-in-progress"

    # Apply dispositions to each asset
    unmatched = []
    for asset in repo["assets"]:
        aid = asset["asset_id"]
        if aid not in DISPOSITIONS:
            unmatched.append(aid)
            continue

        d = DISPOSITIONS[aid]
        asset["status"] = d["status"]
        asset["disposition_rationale"] = d["disposition_reason"]
        asset["parity_mode"] = d["parity_mode"]
        asset["replacement_ref"] = d["replacement_ref"]
        asset["migration_batch"] = d["migration_batch"]
        asset["canonical_capability"] = d["canonical_capability"]
        asset["blocker_type"] = d.get("blocker_type", "")
        asset["unblock_condition"] = d.get("unblock_condition", "")
        asset["decision_owner"] = d.get("decision_owner", "founder")
        asset["security_review"] = d["security_review"]
        asset["updated_at"] = NOW

        # For ported assets, set target_home and owner_suite
        if d["status"] == "ported":
            asset["target_home"] = d["target_home"]
            asset["owner_suite"] = d["owner_suite"]
        elif d["status"] == "declined":
            # Keep original owner_suite for record, clear target_home
            asset["owner_suite"] = d.get("owner_suite", asset.get("owner_suite", ""))

    if unmatched:
        raise RuntimeError(f"Assets without disposition decisions: {unmatched}")

    # Check all assets have left pending
    still_pending = [a["asset_id"] for a in repo["assets"] if a["status"] == "pending"]
    if still_pending:
        raise RuntimeError(f"Assets still pending after disposition: {still_pending}")

    # Mark disposition complete
    repo["disposition_completed_at"] = NOW

    with manifest_path.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    # Print summary
    counts = {"ported": 0, "declined": 0, "deferred-with-rationale": 0}
    batch_counts: dict[str, int] = {}
    suite_counts: dict[str, int] = {}
    security_blocked = []

    for asset in repo["assets"]:
        s = asset["status"]
        counts[s] = counts.get(s, 0) + 1
        suite = asset.get("owner_suite", "Unassigned")
        suite_counts[suite] = suite_counts.get(suite, 0) + 1
        if s == "ported":
            batch = asset.get("migration_batch", "unassigned")
            batch_counts[batch] = batch_counts.get(batch, 0) + 1
        sec = asset.get("security_review", {})
        if sec.get("status") not in ("passed", "remediated"):
            security_blocked.append(asset["asset_id"])

    print(f"\n{'='*60}")
    print(f"TERRA-FORGE-REBUILD DISPOSITION COMPLETE")
    print(f"{'='*60}")
    print(f"Total assets: {len(repo['assets'])}")
    print(f"  ported:                  {counts.get('ported', 0)}")
    print(f"  declined:                {counts.get('declined', 0)}")
    print(f"  deferred-with-rationale: {counts.get('deferred-with-rationale', 0)}")
    print(f"\nBy migration batch:")
    for batch, count in sorted(batch_counts.items()):
        print(f"  {batch}: {count}")
    print(f"\nBy owner suite:")
    for suite, count in sorted(suite_counts.items()):
        print(f"  {suite}: {count}")
    print(f"\nSecurity-blocked assets: {len(security_blocked)}")
    for aid in security_blocked:
        print(f"  {aid}")

    # Print deferred rows
    deferred = [a for a in repo["assets"] if a["status"] == "deferred-with-rationale"]
    if deferred:
        print(f"\nDeferred assets ({len(deferred)}):")
        for a in deferred:
            print(f"  {a['asset_id']} | {a['source_path']}")
            print(f"    blocker: {a.get('blocker_type', 'N/A')}")
            print(f"    unblock: {a.get('unblock_condition', 'N/A')}")
            print(f"    owner:   {a.get('decision_owner', 'N/A')}")


if __name__ == "__main__":
    manifest_path = Path(__file__).resolve().parents[2] / "phase4b.manifest.json"
    apply_dispositions(manifest_path)
