

create procedure LayerCopyTablePropertyVal
	@lYear_From numeric(4,0),
	@lSupNum_From int,
	@lPropID_From int,
	@lYear_To numeric(4,0),
	@lSupNum_To int,
	@lPropID_To int,

	@szMethod varchar(23)
	/*
		Values:
			SUPPLEMENT		Supplement style pv copy
			CPTNP			CopyPropertyToNewProperty style pv copy
			CFYPL			Create future year property layer style pv copy
	*/
as

set nocount on

	if exists (
		select prop_val_yr
		from dbo.property_val with(nolock)
		where
			prop_val_yr = @lYear_To and
			sup_num = @lSupNum_To and
			prop_id = @lPropID_To
	)
	begin
		-- Row already exists

		-- All we need to is set certain fields on certain methods
		if ( @szMethod = 'SUPPLEMENT' )
		begin
			-- Comment from CreatePropertySupplementLayer
			/*
				we do this because the following situation has probably occurred.  The user accepted & created for this property, then they 
				decided that they needed to supplement it again, and in this case the particular supplement in question has not been accepted. In the
				past we would create a new layer, which would also create a new supplement group. Well this caused the users all kinds of problems. Now, instead of doing that
				we will just keep working with the existing supplement until they close it.
			*/
			update dbo.property_val with(rowlock)
			set
				accept_create_id = null,
				accept_create_dt = null
			where
				prop_val_yr = @lYear_To and
				sup_num = @lSupNum_To and
				prop_id = @lPropID_To and
				accept_create_dt is not null
		end

		-- Need not copy
		return(0)
	end

	if ( @szMethod = 'SUPPLEMENT' )
	begin
		insert dbo.property_val with(rowlock)
		(
			prop_id,
			sup_num,
			prev_sup_num,
			prop_val_yr,
			prop_val,
			vit_flag,
			chg_dt,
			notice_mail_dt,
			land_hstd_val,
			land_non_hstd_val,
			imprv_hstd_val,
			imprv_non_hstd_val,
			appraised_val,
			assessed_val,
			market,
			ag_use_val,
			ag_market,
			ag_loss,
			ag_late_loss,
			timber_78,
			timber_market,
			timber_use,
			timber_loss,
			timber_late_loss,
			rendered_val,
			rendered_yr,
			new_val,
			new_yr,
			mineral_int_pct,
			orig_appraised_val,
			ten_percent_cap,
			legal_desc,
			legal_desc_2,
			abated_pct,
			abated_amt,
			abated_yr,
			eff_size_acres,
			shared_prop_val,
			shared_prop_cad_code,
			legal_acreage,
			recalc_flag,
			vit_declaration_filed_dt,
			sup_cd,
			sup_desc,
			sup_dt,
			sup_action,
			freeze_ceiling,
			freeze_yr,
			prop_inactive_dt,
			appr_company_id,
			last_appraisal_yr,
			oil_wells,
			irr_wells,
			irr_acres,
			irr_capacity,
			oil_wells_apply_adjust,
			tif_land_val,
			tif_imprv_val,
			tif_flag,
			abs_subdv_cd,
			hood_cd,
			block,
			tract_or_lot,
			mbl_hm_park,
			mbl_hm_space,
			rgn_cd,
			subset_cd,
			map_id,
			auto_build_legal,
			image_path,
			mapsco,
			last_appraiser_id,
			next_appraiser_id,
			last_appraisal_dt,
			next_appraisal_dt,
			next_appraisal_rsn,
			value_appraiser_id,
			land_appraiser_id,
			cost_value,
			income_value,
			shared_value,
			appr_method,
			cost_land_hstd_val,
			cost_land_non_hstd_val,
			cost_imprv_hstd_val,
			cost_imprv_non_hstd_val,
			cost_market,
			cost_ag_use_val,
			cost_ag_market,
			cost_ag_loss,
			cost_timber_market,
			cost_timber_use,
			cost_timber_loss,
			income_land_hstd_val,
			income_land_non_hstd_val,
			income_imprv_hstd_val,
			income_imprv_non_hstd_val,
			income_market,
			income_ag_use_val,
			income_ag_market,
			income_ag_loss,
			income_timber_market,
			income_timber_use,
			income_timber_loss,
			shared_land_hstd_val,
			shared_land_non_hstd_val,
			shared_imprv_hstd_val,
			shared_imprv_non_hstd_val,
			shared_market,
			shared_ag_use_val,
			shared_ag_market,
			shared_ag_loss,
			shared_timber_market,
			shared_timber_use,
			shared_timber_loss,
			sub_market_cd,
			property_use_cd,
			visibility_access_cd,
			shared_other_val,
			reviewed_dt,
			reviewed_appraiser,
			arb_land_hstd_val,
			arb_land_non_hstd_val,
			arb_imprv_hstd_val,
			arb_imprv_non_hstd_val,
			arb_market,
			arb_ag_use_val,
			arb_ag_market,
			arb_timber_market,
			arb_timber_use,
			arb_timber_loss,
			udi_parent,
			udi_parent_prop_id,
			udi_status,
			udi_child_legal_desc,
			hscap_prev_reappr_yr,
			hscap_base_yr_override,
			hscap_override_newhsval_flag,
			condo_pct,
			last_pacs_user_id,
			dist_land_hstd_val,
			dist_land_non_hstd_val,
			dist_imprv_hstd_val,
			dist_imprv_non_hstd_val,
			dist_market,
			dist_ag_use_val,
			dist_ag_market,
			dist_timber_market,
			dist_timber_use,
			dist_timber_loss,
			last_arb_appr_method,
			agent_update_dt,
			cad_value_option,
			hscap_base_yr,
			hscap_base_yr_comment,
			hscap_base_yr_date,
			hscap_base_yr_pacsuser,
			hscap_newhsval,
			hscap_newhsval_comment,
			hscap_newhsval_date,
			hscap_newhsval_pacsuser,
			hscap_override_prevhsval_flag,
			hscap_prevhsval,
			hscap_prevhsval_comment,
			hscap_prevhsval_date,
			hscap_prevhsval_pacsuser,
			hscap_qualify_yr,
			image_id,
			last_actual_appraisal_dt,
			last_owner_id,
			oil_well_apply_adjust,
			owner_update_dt,
			penpad_comments,
			pp_sq_ft,
			pp_rentable_sq_ft_rate,
			secondary_use_cd,
			assessment_use_cd,
			state_district_cd,
			tax_area_mileage,
			total_mileage,
			dor_value,
			apply_miscellaneous_codes,
			book_page,
			sup_comment,
			change_of_value_form,
			sub_type,
			urban_growth_cd,
			cycle,
			cycle_override,
			pp_farm,
			pp_non_farm,
			ag_hs_use_val,
			ag_hs_mkt_val,
			ag_hs_loss,
			timber_hs_use_val,
			timber_hs_mkt_val,
			timber_hs_loss,
			cost_ag_hs_use_val,
			cost_ag_hs_mkt_val,
			cost_ag_hs_loss,
			cost_timber_hs_use_val,
			cost_timber_hs_mkt_val,
			cost_timber_hs_loss,
			shared_ag_hs_use_val,
			shared_ag_hs_mkt_val,
			shared_ag_hs_loss,
			shared_timber_hs_use_val,
			shared_timber_hs_mkt_val,
			shared_timber_hs_loss,
			arb_ag_hs_use_val,
			arb_ag_hs_mkt_val,
			arb_ag_hs_loss,
			arb_timber_hs_use_val,
			arb_timber_hs_mkt_val,
			arb_timber_hs_loss,
			dist_ag_hs_use_val,
			dist_ag_hs_mkt_val,
			dist_ag_hs_loss,
			dist_timber_hs_use_val,
			dist_timber_hs_mkt_val,
			dist_timber_hs_loss,
			new_val_imprv_hs,
			new_val_imprv_nhs,
			new_val_land_hs,
			new_val_land_nhs,
			new_val_hs,
			new_val_nhs,
			new_val_p,
			change_form_printed,
			exclude_change_of_value_form,
			gis_real_coord_x,
			gis_real_coord_y,
			prop_state,
			late_filing_penalty_pct,
			suppress_notice_prior_year_values,
			retain_notice_prior_year_value_setting,
			township_code,
			range_code,
			township_section,
			township_q_section,
			mktappr_market,
			mktappr_land_hstd_val,
			mktappr_land_non_hstd_val,
			mktappr_imprv_hstd_val,
			mktappr_imprv_non_hstd_val,
			mktappr_ag_use_val,
			mktappr_ag_market,
			mktappr_ag_loss,
			mktappr_timber_market,
			mktappr_timber_use,
			mktappr_timber_loss,
			mktappr_ag_hs_use_val,
			mktappr_ag_hs_mkt_val,
			mktappr_ag_hs_loss,
			mktappr_timber_hs_use_val,
			mktappr_timber_hs_mkt_val,
			mktappr_timber_hs_loss,
			sup_verified_user,
			sup_verified_date,
			ubi_number,
			tax_registration,
			business_start_dt,
			business_close_dt,
			business_sold_dt,
			prepared_by_id
		)
		select
			@lPropID_To,
			@lSupNum_To,
			case when @lSupNum_From < 0 then 0 else @lSupNum_From end,
			@lYear_To,
			pv.prop_val,
			pv.vit_flag,
			pv.chg_dt,
			pv.notice_mail_dt,
			pv.land_hstd_val,
			pv.land_non_hstd_val,
			pv.imprv_hstd_val,
			pv.imprv_non_hstd_val,
			pv.appraised_val,
			pv.assessed_val,
			pv.market,
			pv.ag_use_val,
			pv.ag_market,
			pv.ag_loss,
			pv.ag_late_loss,
			pv.timber_78,
			pv.timber_market,
			pv.timber_use,
			pv.timber_loss,
			pv.timber_late_loss,
			pv.rendered_val,
			pv.rendered_yr,
			pv.new_val,
			pv.new_yr,
			pv.mineral_int_pct,
			pv.orig_appraised_val,
			pv.ten_percent_cap,
			pv.legal_desc,
			pv.legal_desc_2,
			pv.abated_pct,
			pv.abated_amt,
			pv.abated_yr,
			pv.eff_size_acres,
			pv.shared_prop_val,
			pv.shared_prop_cad_code,
			pv.legal_acreage,
			'M',
			pv.vit_declaration_filed_dt,
			pv.sup_cd,
			pv.sup_desc,
			pv.sup_dt,
			pv.sup_action,
			pv.freeze_ceiling,
			pv.freeze_yr,
			pv.prop_inactive_dt,
			pv.appr_company_id,
			pv.last_appraisal_yr,
			pv.oil_wells,
			pv.irr_wells,
			pv.irr_acres,
			pv.irr_capacity,
			pv.oil_wells_apply_adjust,
			pv.tif_land_val,
			pv.tif_imprv_val,
			pv.tif_flag,
			case when abs_subdv.abs_subdv_yr is not null then pv.abs_subdv_cd else null end,
			case when nbhd.hood_yr is not null then pv.hood_cd else null end,
			pv.block,
			pv.tract_or_lot,
			pv.mbl_hm_park,
			pv.mbl_hm_space,
			pv.rgn_cd,
			pv.subset_cd,
			pv.map_id,
			pv.auto_build_legal,
			case when @lPropID_To = @lPropID_From then pv.image_path else null end,
			pv.mapsco,
			pv.last_appraiser_id,
			pv.next_appraiser_id,
			pv.last_appraisal_dt,
			pv.next_appraisal_dt,
			pv.next_appraisal_rsn,
			pv.value_appraiser_id,
			pv.land_appraiser_id,
			pv.cost_value,
			pv.income_value,
			pv.shared_value,
			pv.appr_method,
			pv.cost_land_hstd_val,
			pv.cost_land_non_hstd_val,
			pv.cost_imprv_hstd_val,
			pv.cost_imprv_non_hstd_val,
			pv.cost_market,
			pv.cost_ag_use_val,
			pv.cost_ag_market,
			pv.cost_ag_loss,
			pv.cost_timber_market,
			pv.cost_timber_use,
			pv.cost_timber_loss,
			pv.income_land_hstd_val,
			pv.income_land_non_hstd_val,
			pv.income_imprv_hstd_val,
			pv.income_imprv_non_hstd_val,
			pv.income_market,
			pv.income_ag_use_val,
			pv.income_ag_market,
			pv.income_ag_loss,
			pv.income_timber_market,
			pv.income_timber_use,
			pv.income_timber_loss,
			pv.shared_land_hstd_val,
			pv.shared_land_non_hstd_val,
			pv.shared_imprv_hstd_val,
			pv.shared_imprv_non_hstd_val,
			pv.shared_market,
			pv.shared_ag_use_val,
			pv.shared_ag_market,
			pv.shared_ag_loss,
			pv.shared_timber_market,
			pv.shared_timber_use,
			pv.shared_timber_loss,
			pv.sub_market_cd,
			pv.property_use_cd,
			pv.visibility_access_cd,
			pv.shared_other_val,
			pv.reviewed_dt,
			pv.reviewed_appraiser,
			pv.arb_land_hstd_val,
			pv.arb_land_non_hstd_val,
			pv.arb_imprv_hstd_val,
			pv.arb_imprv_non_hstd_val,
			pv.arb_market,
			pv.arb_ag_use_val,
			pv.arb_ag_market,
			pv.arb_timber_market,
			pv.arb_timber_use,
			pv.arb_timber_loss,
			pv.udi_parent,
			pv.udi_parent_prop_id,
			pv.udi_status,
			pv.udi_child_legal_desc,
			pv.hscap_prev_reappr_yr,
			pv.hscap_base_yr_override,
			pv.hscap_override_newhsval_flag,
			pv.condo_pct,
			pv.last_pacs_user_id,
			pv.dist_land_hstd_val,
			pv.dist_land_non_hstd_val,
			pv.dist_imprv_hstd_val,
			pv.dist_imprv_non_hstd_val,
			pv.dist_market,
			pv.dist_ag_use_val,
			pv.dist_ag_market,
			pv.dist_timber_market,
			pv.dist_timber_use,
			pv.dist_timber_loss,
			pv.last_arb_appr_method,
			pv.agent_update_dt,
			pv.cad_value_option,
			pv.hscap_base_yr,
			pv.hscap_base_yr_comment,
			pv.hscap_base_yr_date,
			pv.hscap_base_yr_pacsuser,
			pv.hscap_newhsval,
			pv.hscap_newhsval_comment,
			pv.hscap_newhsval_date,
			pv.hscap_newhsval_pacsuser,
			pv.hscap_override_prevhsval_flag,
			pv.hscap_prevhsval,
			pv.hscap_prevhsval_comment,
			pv.hscap_prevhsval_date,
			pv.hscap_prevhsval_pacsuser,
			pv.hscap_qualify_yr,
			pv.image_id,
			pv.last_actual_appraisal_dt,
			pv.last_owner_id,
			pv.oil_well_apply_adjust,
			pv.owner_update_dt,
			pv.penpad_comments,
			pv.pp_sq_ft,
			pv.pp_rentable_sq_ft_rate,
			pv.secondary_use_cd,
			pv.assessment_use_cd,
			pv.state_district_cd,
			pv.tax_area_mileage,
			pv.total_mileage,
			pv.dor_value,
			pv.apply_miscellaneous_codes,
			pv.book_page,
			pv.sup_comment,
			pv.change_of_value_form,
			pv.sub_type,
			pv.urban_growth_cd,
			pv.cycle,
			pv.cycle_override,
			pv.pp_farm,
			pv.pp_non_farm,
			pv.ag_hs_use_val,
			pv.ag_hs_mkt_val,
			pv.ag_hs_loss,
			pv.timber_hs_use_val,
			pv.timber_hs_mkt_val,
			pv.timber_hs_loss,
			pv.cost_ag_hs_use_val,
			pv.cost_ag_hs_mkt_val,
			pv.cost_ag_hs_loss,
			pv.cost_timber_hs_use_val,
			pv.cost_timber_hs_mkt_val,
			pv.cost_timber_hs_loss,
			pv.shared_ag_hs_use_val,
			pv.shared_ag_hs_mkt_val,
			pv.shared_ag_hs_loss,
			pv.shared_timber_hs_use_val,
			pv.shared_timber_hs_mkt_val,
			pv.shared_timber_hs_loss,
			pv.arb_ag_hs_use_val,
			pv.arb_ag_hs_mkt_val,
			pv.arb_ag_hs_loss,
			pv.arb_timber_hs_use_val,
			pv.arb_timber_hs_mkt_val,
			pv.arb_timber_hs_loss,
			pv.dist_ag_hs_use_val,
			pv.dist_ag_hs_mkt_val,
			pv.dist_ag_hs_loss,
			pv.dist_timber_hs_use_val,
			pv.dist_timber_hs_mkt_val,
			pv.dist_timber_hs_loss,
			pv.new_val_imprv_hs,
			pv.new_val_imprv_nhs,
			pv.new_val_land_hs,
			pv.new_val_land_nhs,
			case when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To then pv.new_val_hs else 0 end, --new_val_hs
			case when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To then pv.new_val_nhs else 0 end, --new_val_nhs
			case when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To then pv.new_val_p else 0 end, --new_val_p
			0, --change_form_printed
			case 
				when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To 
				then pv.exclude_change_of_value_form
				else 0
			end, --exclude_change_of_value_form
			pv.gis_real_coord_x,
			pv.gis_real_coord_y,
			pv.prop_state,
			case when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To then pv.late_filing_penalty_pct else null end, -- late_filing_penalty_pct
			case when @lPropID_From = @lPropID_To and pv.retain_notice_prior_year_value_setting = 1 then pv.suppress_notice_prior_year_values else 0 end,
			case when @lPropID_From = @lPropID_To then pv.retain_notice_prior_year_value_setting else 0 end,

			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_code else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code) and pv.range_code = (select range_code from prop_range where range_year = @lYear_To and range_code = pv.range_code)) then pv.range_code else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_section else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_q_section else null end,

			case when appr_method = 'G' then mktappr_market else 0 end,
			case when appr_method = 'G' then mktappr_land_hstd_val else 0 end,
			case when appr_method = 'G' then mktappr_land_non_hstd_val else 0 end,
			case when appr_method = 'G' then mktappr_imprv_hstd_val else 0 end,
			case when appr_method = 'G' then mktappr_imprv_non_hstd_val else 0 end,
			case when appr_method = 'G' then mktappr_ag_use_val else 0 end,
			case when appr_method = 'G' then mktappr_ag_market else 0 end,
			case when appr_method = 'G' then mktappr_ag_loss else 0 end,
			case when appr_method = 'G' then mktappr_timber_market else 0 end,
			case when appr_method = 'G' then mktappr_timber_use else 0 end,
			case when appr_method = 'G' then mktappr_timber_loss else 0 end,
			case when appr_method = 'G' then mktappr_ag_hs_use_val else 0 end,
			case when appr_method = 'G' then mktappr_ag_hs_mkt_val else 0 end,
			case when appr_method = 'G' then mktappr_ag_hs_loss else 0 end,
			case when appr_method = 'G' then mktappr_timber_hs_use_val else 0 end,
			case when appr_method = 'G' then mktappr_timber_hs_mkt_val else 0 end,
			case when appr_method = 'G' then mktappr_timber_hs_loss else 0 end,
			-- Preserve verification when moving from pending supplement to another
			case when @lSupNum_From = 32767 then sup_verified_user else null end,
			case when @lSupNum_From = 32767 then sup_verified_date else null end,
			ubi_number,
			tax_registration,
			business_start_dt,
			business_close_dt,
			business_sold_dt,

			-- Copy the prepared-by ID only when moving a property to
			-- another supplement in the same year
			case when @lPropID_From = @lPropID_To and @lYear_From = @lYear_To
				and @lSupNum_From > 0 and @lSupNum_To > 0 then pv.prepared_by_id
				else null end 

		from dbo.property_val as pv with(nolock)
		left outer join abs_subdv with(nolock) on
			abs_subdv.abs_subdv_yr = @lYear_To and
			abs_subdv.abs_subdv_cd = pv.abs_subdv_cd
		left outer join neighborhood as nbhd with(nolock) on
			nbhd.hood_yr = @lYear_To and
			nbhd.hood_cd = pv.hood_cd
		where
			prop_val_yr = @lYear_From and
			sup_num = @lSupNum_From and
			prop_id = @lPropID_From
	end
	else if ( @szMethod in ('CPTNP','CFYPL') )
	begin
		insert dbo.property_val with(rowlock)
		( 
			prop_id,
			prop_val_yr,
			prop_val,
			chg_dt,
			notice_mail_dt,
			land_hstd_val,
			land_non_hstd_val,
			imprv_hstd_val,
			imprv_non_hstd_val,
			appraised_val,
			assessed_val,
			market,
			ag_use_val,
			ag_market,
			freeze_ceiling,
			freeze_yr,
			ag_loss,
			ag_late_loss,
			timber_78,
			timber_market,
			timber_use,
			timber_loss,
			timber_late_loss,
			rendered_val,
			rendered_yr,
			new_val,
			new_yr,
			mineral_int_pct,
			orig_appraised_val,
			ten_percent_cap,
			sup_num,
			legal_desc,
			legal_desc_2,
			abated_pct,
			abated_amt,
			abated_yr,
			eff_size_acres,
			shared_prop_val,
			shared_prop_cad_code,
			legal_acreage,
			vit_flag,
			recalc_flag,
			vit_declaration_filed_dt,
			prev_sup_num,
			appr_company_id,
			prop_inactive_dt,
			hscap_qualify_yr,
			hscap_override_prevhsval_flag,
			hscap_prevhsval,
			hscap_prevhsval_pacsuser,
			hscap_prevhsval_comment,
			hscap_prevhsval_date,
			hscap_override_newhsval_flag,
			hscap_newhsval,
			hscap_newhsval_pacsuser,
			hscap_newhsval_comment,
			hscap_newhsval_date,
			last_appraisal_yr,
			oil_wells,
			irr_wells,
			irr_acres,
			irr_capacity,
			oil_wells_apply_adjust,
			tif_land_val,
			tif_imprv_val,
			tif_flag,
			accept_create_id,
			accept_create_dt,
			abs_subdv_cd,
			hood_cd,
			block,
			tract_or_lot,
			mbl_hm_park,
			mbl_hm_space,
			rgn_cd,
			subset_cd,
			map_id,
			auto_build_legal,
			image_path,
			hscap_prev_reappr_yr,
			hscap_base_yr,
			hscap_base_yr_override,
			hscap_base_yr_pacsuser,
			hscap_base_yr_comment,
			hscap_base_yr_date,
			mapsco,
			last_appraiser_id,
			next_appraiser_id,
			last_appraisal_dt,
			next_appraisal_dt,
			next_appraisal_rsn,
			value_appraiser_id,
			land_appraiser_id,
			cost_value,
			income_value,
			shared_value,
			appr_method,
			cost_land_hstd_val,
			cost_land_non_hstd_val,
			cost_imprv_hstd_val,
			cost_imprv_non_hstd_val,
			cost_market,
			cost_ag_use_val,
			cost_ag_market,
			cost_ag_loss,
			cost_timber_market,
			cost_timber_use,
			cost_timber_loss,
			income_land_hstd_val,
			income_land_non_hstd_val,
			income_imprv_hstd_val,
			income_imprv_non_hstd_val,
			income_market,
			income_ag_use_val,
			income_ag_market,
			income_ag_loss,
			income_timber_market,
			income_timber_use,
			income_timber_loss,
			shared_land_hstd_val,
			shared_land_non_hstd_val,
			shared_imprv_hstd_val,
			shared_imprv_non_hstd_val,
			shared_market,
			shared_ag_use_val,
			shared_ag_market,
			shared_ag_loss,
			shared_timber_market,
			shared_timber_use,
			shared_timber_loss,
			sub_market_cd, 
			property_use_cd, 
			visibility_access_cd,
			shared_other_val,
			reviewed_dt,
			reviewed_appraiser, 
			arb_land_hstd_val,
			arb_land_non_hstd_val,
			arb_imprv_hstd_val,
			arb_imprv_non_hstd_val,
			arb_market,
			arb_ag_use_val,
			arb_ag_market,
			arb_timber_market,
			arb_timber_use,
			arb_timber_loss,
			pp_sq_ft,
			pp_rentable_sq_ft_rate,
			dist_vit_val,

			dist_land_hstd_val,
			dist_land_non_hstd_val,
			dist_imprv_hstd_val,
			dist_imprv_non_hstd_val,
			dist_market,
			dist_ag_use_val,
			dist_ag_market,
			dist_timber_market,
			dist_timber_use,
			dist_timber_loss,
			condo_pct,

			last_pacs_user_id,
			udi_parent,
			udi_parent_prop_id,
			udi_status,
			image_id,
			last_arb_appr_method,
			
			secondary_use_cd,
			assessment_use_cd,
			state_district_cd,
			tax_area_mileage,
			total_mileage,
			dor_value,
			apply_miscellaneous_codes,
			book_page,
			sup_comment,
			change_of_value_form,
			sub_type,
			urban_growth_cd,
			cycle,
			cycle_override,
			pp_farm,
			pp_non_farm,
			ag_hs_use_val,
			ag_hs_mkt_val,
			ag_hs_loss,
			timber_hs_use_val,
			timber_hs_mkt_val,
			timber_hs_loss,
			cost_ag_hs_use_val,
			cost_ag_hs_mkt_val,
			cost_ag_hs_loss,
			cost_timber_hs_use_val,
			cost_timber_hs_mkt_val,
			cost_timber_hs_loss,
			shared_ag_hs_use_val,
			shared_ag_hs_mkt_val,
			shared_ag_hs_loss,
			shared_timber_hs_use_val,
			shared_timber_hs_mkt_val,
			shared_timber_hs_loss,
			arb_ag_hs_use_val,
			arb_ag_hs_mkt_val,
			arb_ag_hs_loss,
			arb_timber_hs_use_val,
			arb_timber_hs_mkt_val,
			arb_timber_hs_loss,
			dist_ag_hs_use_val,
			dist_ag_hs_mkt_val,
			dist_ag_hs_loss,
			dist_timber_hs_use_val,
			dist_timber_hs_mkt_val,
			dist_timber_hs_loss,
			new_val_imprv_hs,
			new_val_imprv_nhs,
			new_val_land_hs,
			new_val_land_nhs,
			change_form_printed,
			exclude_change_of_value_form,
			gis_real_coord_x,
			gis_real_coord_y,
			prop_state,
			late_filing_penalty_pct,
	
			township_code,
			range_code,
			township_section,
			township_q_section,
			
			mktappr_market,
			mktappr_land_hstd_val,
			mktappr_land_non_hstd_val,
			mktappr_imprv_hstd_val,
			mktappr_imprv_non_hstd_val,
			mktappr_ag_use_val,
			mktappr_ag_market,
			mktappr_ag_loss,
			mktappr_timber_market,
			mktappr_timber_use,
			mktappr_timber_loss,
			mktappr_ag_hs_use_val,
			mktappr_ag_hs_mkt_val,
			mktappr_ag_hs_loss,
			mktappr_timber_hs_use_val,
			mktappr_timber_hs_mkt_val,
			mktappr_timber_hs_loss,
			ubi_number,
			tax_registration,
			business_start_dt,
			business_close_dt,
			business_sold_dt
		)
		select
			@lPropID_To,
			@lYear_To,
			pv.prop_val,
			pv.chg_dt,
			pv.notice_mail_dt,
			pv.land_hstd_val,
			pv.land_non_hstd_val,
			pv.imprv_hstd_val,
			pv.imprv_non_hstd_val,
			pv.appraised_val,
			pv.assessed_val,
			pv.market,
			pv.ag_use_val,
			pv.ag_market,
			pv.freeze_ceiling,
			pv.freeze_yr,
			pv.ag_loss,
			0, --ag_late_loss
			pv.timber_78,
			pv.timber_market,
			pv.timber_use,
			pv.timber_loss,
			0, --timber_late_loss
			null, --rendered_val
			null, --rendered_yr
			pv.new_val,
			pv.new_yr,
			pv.mineral_int_pct,
			pv.orig_appraised_val,
			pv.ten_percent_cap,
			@lSupNum_To, --sup_num
			pv.legal_desc,
			pv.legal_desc_2,
			pv.abated_pct,
			pv.abated_amt,
			pv.abated_yr,
			pv.eff_size_acres,
			pv.shared_prop_val,
			pv.shared_prop_cad_code,
			pv.legal_acreage,
			pv.vit_flag,
			'M', --recalc_flag,
			pv.vit_declaration_filed_dt,
			0, --prev_sup_num
			pv.appr_company_id,
			pv.prop_inactive_dt,
			pv.hscap_qualify_yr,
			case when pv.hscap_override_prevhsval_flag = 'T' then 'F' else pv.hscap_override_prevhsval_flag end, --hscap_override_prevhsval_flag
			case when pv.hscap_override_prevhsval_flag = 'T' then 0 else pv.hscap_prevhsval end, --hscap_prevhsval
			case when pv.hscap_override_prevhsval_flag = 'T' then null else pv.hscap_prevhsval_pacsuser end, --hscap_prevhsval_pacsuser
			case when pv.hscap_override_prevhsval_flag = 'T' then null else pv.hscap_prevhsval_comment end, --hscap_prevhsval_comment
			case when pv.hscap_override_prevhsval_flag = 'T' then null else pv.hscap_prevhsval_date end, --hscap_prevhsval_date
			case when pv.hscap_override_newhsval_flag = 'T' then 'F' else pv.hscap_override_newhsval_flag end, --hscap_override_newhsval_flag
			case when pv.hscap_override_newhsval_flag = 'T' then 0 else pv.hscap_newhsval end, --hscap_newhsval
			case when pv.hscap_override_newhsval_flag = 'T' then null else pv.hscap_newhsval_pacsuser end, --hscap_newhsval_pacsuser
			case when pv.hscap_override_newhsval_flag = 'T' then null else pv.hscap_newhsval_comment end, --hscap_newhsval_comment
			case when pv.hscap_override_newhsval_flag = 'T' then null else pv.hscap_newhsval_date end, --hscap_newhsval_date
			pv.last_appraisal_yr,
			pv.oil_wells,
			pv.irr_wells,
			pv.irr_acres,
			pv.irr_capacity,
			pv.oil_wells_apply_adjust,
			pv.tif_land_val,
			pv.tif_imprv_val,
			pv.tif_flag,
			pv.accept_create_id,
			pv.accept_create_dt,
			case when abs_subdv.abs_subdv_yr is not null then pv.abs_subdv_cd else null end,
			case when nbhd.hood_yr is not null then pv.hood_cd else null end,
			pv.block,
			pv.tract_or_lot,
			pv.mbl_hm_park,
			pv.mbl_hm_space,
			pv.rgn_cd,
			pv.subset_cd,
			pv.map_id,
			pv.auto_build_legal,
			pv.image_path,
			case when pv.hscap_prev_reappr_yr is not null and pv.last_appraisal_yr is null then pv.hscap_prev_reappr_yr else pv.last_appraisal_yr end, --hscap_prev_reappr_yr
			case when pv.hscap_base_yr_override = 'T' then null else pv.hscap_base_yr end, --hscap_base_yr
			case when pv.hscap_base_yr_override = 'T' then 'F' else pv.hscap_base_yr_override end, --hscap_base_yr_override
			case when pv.hscap_base_yr_override = 'T' then null else pv.hscap_base_yr_pacsuser end, --hscap_base_yr_pacsuser
			case when pv.hscap_base_yr_override = 'T' then null else pv.hscap_base_yr_comment end, --hscap_base_yr_comment
			case when pv.hscap_base_yr_override = 'T' then null else pv.hscap_base_yr_date end, --hscap_base_yr_date
			pv.mapsco,
			pv.last_appraiser_id,
			pv.next_appraiser_id,
			pv.last_appraisal_dt,
			pv.next_appraisal_dt,
			pv.next_appraisal_rsn,
			pv.value_appraiser_id,
			pv.land_appraiser_id,
			pv.cost_value,
			pv.income_value,
			pv.shared_value,
			pv.appr_method,
			pv.cost_land_hstd_val,
			pv.cost_land_non_hstd_val,
			pv.cost_imprv_hstd_val,
			pv.cost_imprv_non_hstd_val,
			pv.cost_market,
			pv.cost_ag_use_val,
			pv.cost_ag_market,
			pv.cost_ag_loss,
			pv.cost_timber_market,
			pv.cost_timber_use,
			pv.cost_timber_loss,
			pv.income_land_hstd_val,
			pv.income_land_non_hstd_val,
			pv.income_imprv_hstd_val,
			pv.income_imprv_non_hstd_val,
			pv.income_market,
			pv.income_ag_use_val,
			pv.income_ag_market,
			pv.income_ag_loss,
			pv.income_timber_market,
			pv.income_timber_use,
			pv.income_timber_loss,
			pv.shared_land_hstd_val,
			pv.shared_land_non_hstd_val,
			pv.shared_imprv_hstd_val,
			pv.shared_imprv_non_hstd_val,
			pv.shared_market,
			pv.shared_ag_use_val,
			pv.shared_ag_market,
			pv.shared_ag_loss,
			pv.shared_timber_market,
			pv.shared_timber_use,
			pv.shared_timber_loss,
			pv.sub_market_cd, 
			pv.property_use_cd, 
			pv.visibility_access_cd,
			pv.shared_other_val,
			pv.reviewed_dt,
			pv.reviewed_appraiser, 
			pv.arb_land_hstd_val,
			pv.arb_land_non_hstd_val,
			pv.arb_imprv_hstd_val,
			pv.arb_imprv_non_hstd_val,
			pv.arb_market,
			pv.arb_ag_use_val,
			pv.arb_ag_market,
			pv.arb_timber_market,
			pv.arb_timber_use,
			pv.arb_timber_loss,
			pv.pp_sq_ft,
			pv.pp_rentable_sq_ft_rate,
			pv.dist_vit_val,

			case when @szMethod = 'CFYPL' then pv.dist_land_hstd_val else null end,
			case when @szMethod = 'CFYPL' then pv.dist_land_non_hstd_val else null end,
			case when @szMethod = 'CFYPL' then pv.dist_imprv_hstd_val else null end,
			case when @szMethod = 'CFYPL' then pv.dist_imprv_non_hstd_val else null end,
			case when @szMethod = 'CFYPL' then pv.dist_market else null end,
			case when @szMethod = 'CFYPL' then pv.dist_ag_use_val else null end,
			case when @szMethod = 'CFYPL' then pv.dist_ag_market else null end,
			case when @szMethod = 'CFYPL' then pv.dist_timber_market else null end,
			case when @szMethod = 'CFYPL' then pv.dist_timber_use else null end,
			case when @szMethod = 'CFYPL' then pv.dist_timber_loss else null end,
			case when @szMethod = 'CFYPL' then pv.condo_pct else null end,
			case when @szMethod = 'CFYPL' then pv.last_pacs_user_id else null end,
			case when @szMethod = 'CFYPL' then pv.udi_parent else null end,
			case when @szMethod = 'CFYPL' then pv.udi_parent_prop_id else null end,
			case when @szMethod = 'CFYPL' then pv.udi_status else null end,
			case when @szMethod = 'CFYPL' then pv.image_id else null end,
			case when @szMethod = 'CFYPL' then pv.last_arb_appr_method else null end,

			pv.secondary_use_cd,
			pv.assessment_use_cd,
			pv.state_district_cd,
			pv.tax_area_mileage,
			pv.total_mileage,
			pv.dor_value,
			pv.apply_miscellaneous_codes,
			pv.book_page,
			pv.sup_comment,
			pv.change_of_value_form,
			pv.sub_type,
			pv.urban_growth_cd,
			pv.cycle,
			pv.cycle_override,
			pv.pp_farm,
			pv.pp_non_farm,
			pv.ag_hs_use_val,
			pv.ag_hs_mkt_val,
			pv.ag_hs_loss,
			pv.timber_hs_use_val,
			pv.timber_hs_mkt_val,
			pv.timber_hs_loss,
			pv.cost_ag_hs_use_val,
			pv.cost_ag_hs_mkt_val,
			pv.cost_ag_hs_loss,
			pv.cost_timber_hs_use_val,
			pv.cost_timber_hs_mkt_val,
			pv.cost_timber_hs_loss,
			pv.shared_ag_hs_use_val,
			pv.shared_ag_hs_mkt_val,
			pv.shared_ag_hs_loss,
			pv.shared_timber_hs_use_val,
			pv.shared_timber_hs_mkt_val,
			pv.shared_timber_hs_loss,
			pv.arb_ag_hs_use_val,
			pv.arb_ag_hs_mkt_val,
			pv.arb_ag_hs_loss,
			pv.arb_timber_hs_use_val,
			pv.arb_timber_hs_mkt_val,
			pv.arb_timber_hs_loss,
			pv.dist_ag_hs_use_val,
			pv.dist_ag_hs_mkt_val,
			pv.dist_ag_hs_loss,
			pv.dist_timber_hs_use_val,
			pv.dist_timber_hs_mkt_val,
			pv.dist_timber_hs_loss,
			pv.new_val_imprv_hs,
			pv.new_val_imprv_nhs,
			pv.new_val_land_hs,
			pv.new_val_land_nhs,
			0, --change_form_printed
			case 
				when @lYear_From = @lYear_To and @lPropID_From = @lPropID_To 
				then pv.exclude_change_of_value_form
				else 0
			end, --exclude_change_of_value_form
			pv.gis_real_coord_x,
			pv.gis_real_coord_y,
			pv.prop_state,
			null, -- late_filing_penalty_pct

			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_code else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code) and pv.range_code = (select range_code from prop_range where range_year = @lYear_To and range_code = pv.range_code)) then pv.range_code else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_section else null end,
			case when (pv.township_code = (select township_code from township where township_year = @lYear_To and township_code = pv.township_code)) then pv.township_q_section else null end,

			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_market else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_land_hstd_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_land_non_hstd_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_imprv_hstd_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_imprv_non_hstd_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_use_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_market else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_loss else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_market else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_use else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_loss else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_hs_use_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_hs_mkt_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_ag_hs_loss else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_hs_use_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_hs_mkt_val else 0 end,
			case when @szMethod = 'CFYPL' and appr_method = 'G' then mktappr_timber_hs_loss else 0 end,
			ubi_number,
			tax_registration,
			business_start_dt,
			business_close_dt,
			business_sold_dt

		from dbo.property_val as pv with(nolock)
		left outer join abs_subdv with(nolock) on
			abs_subdv.abs_subdv_yr = @lYear_To and
			abs_subdv.abs_subdv_cd = pv.abs_subdv_cd
		left outer join neighborhood as nbhd with(nolock) on
			nbhd.hood_yr = @lYear_To and
			nbhd.hood_cd = pv.hood_cd
		where
			pv.prop_val_yr = @lYear_From and
			pv.sup_num = @lSupNum_From and
			pv.prop_id = @lPropID_From
	end
	else
	begin
		raiserror('LayerCopyTablePropertyVal - Unsupported value for szMethod parameter', 18, 1)
		return(-1)
	end
	
	-- Now copy the state specific property_val table
	declare @szRegion varchar(2)
	select @szRegion = szConfigValue
	from core_config with(nolock)
	where szGroup = 'SYSTEM' and szConfigName = 'REGION'
	
	declare @szSQL varchar(8000)
	set @szSQL = 'exec ' + @szRegion + 'LayerCopyTablePV ' +
		convert(varchar(12), @lYear_From) + ',' +
		convert(varchar(12), @lSupNum_From) + ',' +
		convert(varchar(12), @lPropID_From) + ',' +
		convert(varchar(12), @lYear_To) + ',' +
		convert(varchar(12), @lSupNum_To) + ',' +
		convert(varchar(12), @lPropID_To) + ',' +
		'''' + @szMethod + ''''
	exec(@szSQL)
	
	-- property_legal_description
	insert dbo.property_legal_description (
		prop_val_yr, sup_num, prop_id, metes_and_bounds
	)
	select
		@lYear_To, @lSupNum_To, @lPropID_To, metes_and_bounds
	from dbo.property_legal_description
	where
		prop_val_yr = @lYear_From and
		sup_num = @lSupNum_From and
		prop_id = @lPropID_From

	-- user_property_val
	exec dbo.LayerCopyUserTablePropertyVal 
		@lYear_From, @lSupNum_From, @lPropID_From,
		@lYear_To, @lSupNum_To, @lPropID_To
	
	return(0)

GO

