
create procedure RecalcRowUpdateIncome
	@lIncomeID int,
	@lYear numeric(4,0),
	@lSupNum int,

	@gba numeric(14,0),
	@nra numeric(14,0),
	@dc_la numeric(14,0),
	@dc_va numeric(14,0),
	@dc_be numeric(5,2),
	@dc_or numeric(5,2),
	@dc_vr numeric(5,2),
	@dc_larate numeric(14,2),
	@dc_varate numeric(14,2),
	@dc_li numeric(14,0),
	@dc_vi numeric(14,0),
	@dc_gpi numeric(14,0),
	@dc_gpivr numeric(5,2),
	@dc_gpivi numeric(14,0),
	@dc_gpiclr numeric(5,2),
	@dc_gpicli numeric(14,0),
	@dc_gpirer numeric(5,2),
	@dc_gpire numeric(14,0),
	@dc_gpisir numeric(5,2),
	@dc_gpisi numeric(14,0),
	@dc_egi numeric(14,0),
	@dc_expoei numeric(14,0),
	@dc_mgmtr numeric(5,2),
	@dc_mgmti numeric(14,0),
	@dc_rrr numeric(5,2),
	@dc_rri numeric(14,0),
	@dc_tir numeric(5,2),
	@dc_tii numeric(14,0),
	@dc_lcr numeric(5,2),
	@dc_lci numeric(14,0),
	@dc_exp numeric(14,0),
	@dc_noi numeric(14,0),
	@dc_capr numeric(5,2),
	@dc_capi numeric(14,0),
	@dc_ind numeric(14,0),
	@dc_gpirsf numeric(14,2),
	@dc_gpivrsf numeric(14,2),
	@dc_gpiclrsf numeric(14,2),
	@dc_gpirersf numeric(14,2),
	@dc_gpisirsf numeric(14,2),
	@dc_egirsf numeric(14,2),
	@dc_egipctrev numeric(5,2),
	@dc_expoersf numeric(14,2),
	@dc_exptaxrsf numeric(14,2),
	@dc_expmgmtrsf numeric(14,2),
	@dc_rrrsf numeric(14,2),
	@dc_exptirsf numeric(14,2),
	@dc_explcrsf numeric(14,2),
	@dc_exprsf numeric(14,2),
	@dc_exppctrev numeric(5,2),
	@dc_noirsf numeric(14,2),
	@dc_noipctrev numeric(5,2),
	@sch_la numeric(14,0),
	@sch_va numeric(14,0),
	@sch_be numeric(5,2),
	@sch_or numeric(5,2),
	@sch_vr numeric(5,2),
	@sch_larate numeric(14,2),
	@sch_varate numeric(14,2),
	@sch_li numeric(14,0),
	@sch_vi numeric(14,0),
	@sch_gpi numeric(14,0),
	@sch_gpivr numeric(5,2),
	@sch_gpivi numeric(14,0),
	@sch_gpiclr numeric(5,2),
	@sch_gpicli numeric(14,0),
	@sch_gpirer numeric(5,2),
	@sch_gpire numeric(14,0),
	@sch_gpisir numeric(5,2),
	@sch_gpisi numeric(14,0),
	@sch_egi numeric(14,0),
	@sch_expoei numeric(14,0),
	@sch_mgmtr numeric(5,2),
	@sch_mgmti numeric(14,0),
	@sch_rrr numeric(5,2),
	@sch_rri numeric(14,0),
	@sch_tir numeric(5,2),
	@sch_tii numeric(14,0),
	@sch_lcr numeric(5,2),
	@sch_lci numeric(14,0),
	@sch_exp numeric(14,0),
	@sch_noi numeric(14,0),
	@sch_capr numeric(5,2),
	@sch_capi numeric(14,0),
	@sch_ind numeric(14,0),
	@sch_gpirsf numeric(14,2),
	@sch_gpivrsf numeric(14,2),
	@sch_gpiclrsf numeric(14,2),
	@sch_gpirersf numeric(14,2),
	@sch_gpisirsf numeric(14,2),
	@sch_egirsf numeric(14,2),
	@sch_egipctrev numeric(5,2),
	@sch_expoersf numeric(14,2),
	@sch_exptaxrsf numeric(14,2),
	@sch_expmgmtrsf numeric(14,2),
	@sch_rrrsf numeric(14,2),
	@sch_exptirsf numeric(14,2),
	@sch_explcrsf numeric(14,2),
	@sch_exprsf numeric(14,2),
	@sch_exppctrev numeric(5,2),
	@sch_noirsf numeric(14,2),
	@sch_noipctrev numeric(5,2),
	@pf_la numeric(14,0),
	@pf_va numeric(14,0),
	@pf_be numeric(5,2),
	@pf_or numeric(5,2),
	@pf_vr numeric(5,2),
	@pf_larate numeric(14,2),
	@pf_varate numeric(14,2),
	@pf_li numeric(14,0),
	@pf_vi numeric(14,0),
	@pf_gpi numeric(14,0),
	@pf_gpivr numeric(5,2),
	@pf_gpivi numeric(14,0),
	@pf_gpiclr numeric(5,2),
	@pf_gpicli numeric(14,0),
	@pf_gpirer numeric(5,2),
	@pf_gpire numeric(14,0),
	@pf_gpisir numeric(5,2),
	@pf_gpisi numeric(14,0),
	@pf_egi numeric(14,0),
	@pf_expoei numeric(14,0),
	@pf_mgmtr numeric(5,2),
	@pf_mgmti numeric(14,0),
	@pf_rrr numeric(5,2),
	@pf_rri numeric(14,0),
	@pf_tir numeric(5,2),
	@pf_tii numeric(14,0),
	@pf_lcr numeric(5,2),
	@pf_lci numeric(14,0),
	@pf_exp numeric(14,0),
	@pf_noi numeric(14,0),
	@pf_capr numeric(5,2),
	@pf_capi numeric(14,0),
	@pf_ind numeric(14,0),
	@pf_gpirsf numeric(14,2),
	@pf_gpivrsf numeric(14,2),
	@pf_gpiclrsf numeric(14,2),
	@pf_gpirersf numeric(14,2),
	@pf_gpisirsf numeric(14,2),
	@pf_egirsf numeric(14,2),
	@pf_egipctrev numeric(5,2),
	@pf_expoersf numeric(14,2),
	@pf_exptaxrsf numeric(14,2),
	@pf_expmgmtrsf numeric(14,2),
	@pf_rrrsf numeric(14,2),
	@pf_exptirsf numeric(14,2),
	@pf_explcrsf numeric(14,2),
	@pf_exprsf numeric(14,2),
	@pf_exppctrev numeric(5,2),
	@pf_noirsf numeric(14,2),
	@pf_noipctrev numeric(5,2),

	@income_value numeric(14,0),

	@recalc_flag char(1),

	@dc_tax numeric(14,0),
	@sch_tax numeric(14,0),
	@pf_tax numeric(14,0),

	@land_ratio numeric(14,5),
	@land_size numeric(18,4),
	@land_excess_value numeric(14,0),

	@lu_rent_loss_area numeric(14,0),
	@lu_rent_sf numeric(14,2),
	@lu_rent_num_year numeric(5,2),
	@lu_rent_total numeric(14,0),

	@lu_lease_pct numeric(5,2),
	@lu_lease_total numeric(14,0),

	@lu_tfo_sf numeric(14,2),
	@lu_tfo_total numeric(14,0),
	@lu_disc_rate numeric(5,2),
	@lu_num_year numeric(5,2),
	@lu_cost numeric(14,0),

	@dc_ind_rsf numeric(14,2),
	@sch_ind_rsf numeric(14,2),
	@pf_ind_rsf numeric(14,2),

	@dc_ind_runit numeric(14,2),
	@sch_ind_runit numeric(14,2),
	@pf_ind_runit numeric(14,2),

	@dc_ocr_runit numeric(14,2),
	@sch_ocr_runit numeric(14,2),
	@pf_ocr_runit numeric(14,2),

	@num_units numeric(14,0),

	@non_income_land_value numeric(14,0),
	@other_land_value numeric(14,0),
	@schil_indicated_land_value numeric(14,0),
	@non_income_imprv_value numeric(14,0),
	@non_income_land_imps_value numeric(14,0),
	@schil_indicated_imprv_value numeric(14,0),
	@schil_method_value numeric(14,0),
	@num_designated_units int,
	@gba_designated_units numeric(18,1),
	@schil_base_indicated_value numeric(14,0),
	@schil_indicated_value numeric(14,0),
	@sch_base_indicated_value numeric(14,0),
	@pf_base_indicated_value numeric(14,0),
	@dc_base_indicated_value numeric(14,0),
	@bOverrideSCHTax bit,
	@DCimprv numeric(14,0),
	@SCHimprv numeric(14,0),
	@PFimprv numeric(14,0)
	
as

set nocount on

	update income with(rowlock)
	set
		gba = @gba,
		nra = @nra,
		dc_la = @dc_la,
		dc_va = @dc_va,
		dc_be = @dc_be,
		dc_or = @dc_or,
		dc_vr = @dc_vr,
		dc_larate = @dc_larate,
		dc_varate = @dc_varate,
		dc_li = @dc_li,
		dc_vi = @dc_vi,
		dc_gpi = @dc_gpi,
		dc_gpivr = @dc_gpivr,
		dc_gpivi = @dc_gpivi,
		dc_gpiclr = @dc_gpiclr,
		dc_gpicli = @dc_gpicli,
		dc_gpirer = @dc_gpirer,
		dc_gpire = @dc_gpire,
		dc_gpisir = @dc_gpisir,
		dc_gpisi = @dc_gpisi,
		dc_egi = @dc_egi,
		dc_expoei = @dc_expoei,
		dc_mgmtr = @dc_mgmtr,
		dc_mgmti = @dc_mgmti,
		dc_rrr = @dc_rrr,
		dc_rri = @dc_rri,
		dc_tir = @dc_tir,
		dc_tii = @dc_tii,
		dc_lcr = @dc_lcr,
		dc_lci = @dc_lci,
		dc_exp = @dc_exp,
		dc_noi = @dc_noi,
		dc_capr = @dc_capr,
		dc_capi = @dc_capi,
		dc_ind = @dc_ind,
		dc_gpirsf = @dc_gpirsf,
		dc_gpivrsf = @dc_gpivrsf,
		dc_gpiclrsf = @dc_gpiclrsf,
		dc_gpirersf = @dc_gpirersf,
		dc_gpisirsf = @dc_gpisirsf,
		dc_egirsf = @dc_egirsf,
		dc_egipctrev = @dc_egipctrev,
		dc_expoersf = @dc_expoersf,
		dc_exptaxrsf = @dc_exptaxrsf,
		dc_expmgmtrsf = @dc_expmgmtrsf,
		dc_rrrsf = @dc_rrrsf,
		dc_exptirsf = @dc_exptirsf,
		dc_explcrsf = @dc_explcrsf,
		dc_exprsf = @dc_exprsf,
		dc_exppctrev = @dc_exppctrev,
		dc_noirsf = @dc_noirsf,
		dc_noipctrev = @dc_noipctrev,
		sch_la = @sch_la,
		sch_va = @sch_va,
		sch_be = @sch_be,
		sch_or = @sch_or,
		sch_vr = @sch_vr,
		sch_larate = @sch_larate,
		sch_varate = @sch_varate,
		sch_li = @sch_li,
		sch_vi = @sch_vi,
		sch_gpi = @sch_gpi,
		sch_gpivr = @sch_gpivr,
		sch_gpivi = @sch_gpivi,
		sch_gpiclr = @sch_gpiclr,
		sch_gpicli = @sch_gpicli,
		sch_gpirer = @sch_gpirer,
		sch_gpire = @sch_gpire,
		sch_gpisir = @sch_gpisir,
		sch_gpisi = @sch_gpisi,
		sch_egi = @sch_egi,
		sch_expoei = @sch_expoei,
		sch_mgmtr = @sch_mgmtr,
		sch_mgmti = @sch_mgmti,
		sch_rrr = @sch_rrr,
		sch_rri = @sch_rri,
		sch_tir = @sch_tir,
		sch_tii = @sch_tii,
		sch_lcr = @sch_lcr,
		sch_lci = @sch_lci,
		sch_exp = @sch_exp,
		sch_noi = @sch_noi,
		sch_capr = @sch_capr,
		sch_capi = @sch_capi,
		sch_ind = @sch_ind,
		sch_gpirsf = @sch_gpirsf,
		sch_gpivrsf = @sch_gpivrsf,
		sch_gpiclrsf = @sch_gpiclrsf,
		sch_gpirersf = @sch_gpirersf,
		sch_gpisirsf = @sch_gpisirsf,
		sch_egirsf = @sch_egirsf,
		sch_egipctrev = @sch_egipctrev,
		sch_expoersf = @sch_expoersf,
		sch_exptaxrsf = @sch_exptaxrsf,
		sch_expmgmtrsf = @sch_expmgmtrsf,
		sch_rrrsf = @sch_rrrsf,
		sch_exptirsf = @sch_exptirsf,
		sch_explcrsf = @sch_explcrsf,
		sch_exprsf = @sch_exprsf,
		sch_exppctrev = @sch_exppctrev,
		sch_noirsf = @sch_noirsf,
		sch_noipctrev = @sch_noipctrev,
		pf_la = @pf_la,
		pf_va = @pf_va,
		pf_be = @pf_be,
		pf_or = @pf_or,
		pf_vr = @pf_vr,
		pf_larate = @pf_larate,
		pf_varate = @pf_varate,
		pf_li = @pf_li,
		pf_vi = @pf_vi,
		pf_gpi = @pf_gpi,
		pf_gpivr = @pf_gpivr,
		pf_gpivi = @pf_gpivi,
		pf_gpiclr = @pf_gpiclr,
		pf_gpicli = @pf_gpicli,
		pf_gpirer = @pf_gpirer,
		pf_gpire = @pf_gpire,
		pf_gpisir = @pf_gpisir,
		pf_gpisi = @pf_gpisi,
		pf_egi = @pf_egi,
		pf_expoei = @pf_expoei,
		pf_mgmtr = @pf_mgmtr,
		pf_mgmti = @pf_mgmti,
		pf_rrr = @pf_rrr,
		pf_rri = @pf_rri,
		pf_tir = @pf_tir,
		pf_tii = @pf_tii,
		pf_lcr = @pf_lcr,
		pf_lci = @pf_lci,
		pf_exp = @pf_exp,
		pf_noi = @pf_noi,
		pf_capr = @pf_capr,
		pf_capi = @pf_capi,
		pf_ind = @pf_ind,
		pf_gpirsf = @pf_gpirsf,
		pf_gpivrsf = @pf_gpivrsf,
		pf_gpiclrsf = @pf_gpiclrsf,
		pf_gpirersf = @pf_gpirersf,
		pf_gpisirsf = @pf_gpisirsf,
		pf_egirsf = @pf_egirsf,
		pf_egipctrev = @pf_egipctrev,
		pf_expoersf = @pf_expoersf,
		pf_exptaxrsf = @pf_exptaxrsf,
		pf_expmgmtrsf = @pf_expmgmtrsf,
		pf_rrrsf = @pf_rrrsf,
		pf_exptirsf = @pf_exptirsf,
		pf_explcrsf = @pf_explcrsf,
		pf_exprsf = @pf_exprsf,
		pf_exppctrev = @pf_exppctrev,
		pf_noirsf = @pf_noirsf,
		pf_noipctrev = @pf_noipctrev,
		income_value = @income_value,
		recalc_flag = @recalc_flag,
		dc_tax = @dc_tax,
		sch_tax = @sch_tax,
		pf_tax = @pf_tax,
		land_ratio = @land_ratio,
		land_size = @land_size,
		land_excess_value = @land_excess_value,
		lu_rent_loss_area = @lu_rent_loss_area,
		lu_rent_sf = @lu_rent_sf,
		lu_rent_num_year = @lu_rent_num_year,
		lu_rent_total = @lu_rent_total,
		lu_lease_pct = @lu_lease_pct,
		lu_lease_total = @lu_lease_total,
		lu_tfo_sf = @lu_tfo_sf,
		lu_tfo_total = @lu_tfo_total,
		lu_disc_rate = @lu_disc_rate,
		lu_num_year = @lu_num_year,
		lu_cost = @lu_cost,
		dc_ind_rsf = @dc_ind_rsf,
		sch_ind_rsf = @sch_ind_rsf,
		pf_ind_rsf = @pf_ind_rsf,
		dc_ind_runit = @dc_ind_runit,
		sch_ind_runit = @sch_ind_runit,
		pf_ind_runit = @pf_ind_runit,
		dc_ocr_runit = @dc_ocr_runit,
		sch_ocr_runit = @sch_ocr_runit,
		pf_ocr_runit = @pf_ocr_runit,
		num_units = @num_units,
		non_income_land_value = @non_income_land_value,
		other_land_value = @other_land_value,
		schil_indicated_land_value = @schil_indicated_land_value,
		non_income_imprv_value = @non_income_imprv_value,
		non_income_land_imps_value = @non_income_land_imps_value,
		schil_indicated_imprv_value = @schil_indicated_imprv_value,
		schil_method_value = @schil_method_value,
		num_designated_units = @num_designated_units,
		gba_designated_units = @gba_designated_units,
		schil_base_indicated_value = @schil_base_indicated_value,
		schil_indicated_value = @schil_indicated_value,
		sch_base_indicated_value = @sch_base_indicated_value,
		pf_base_indicated_value = @pf_base_indicated_value,
		dc_base_indicated_value = @dc_base_indicated_value,
		override_sch_tax = case @bOverrideSCHTax when 1 then 'T' else 'F' end,
		DC_indicated_imprv_value = @DCimprv,
		SCH_indicated_imprv_value = @SCHimprv,
		PF_indicated_imprv_value = @PFimprv
	where
		income_id = @lIncomeID and
		income_yr = @lYear and
		sup_num = @lSupNum

GO

