<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0">
	<xs:include schemaLocation="NetworkAnalyst.xsd"/>
		
	<xs:element name="GetNALayerNames">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LayerType" type="esriNAServerLayerType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetNALayerNamesResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="ArrayOfString"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetNetworkDescription">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NALayerName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetNetworkDescriptionResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="NAServerNetworkDescription"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSolverParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NALayerName" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSolverParametersResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="NAServerSolverParams"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Solve">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SolverParams" type="NAServerSolverParams"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SolveResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="NAServerSolverResults"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSolverParameters2">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NALayerName" type="xs:string"/>
				<xs:element name="LayerToken" type="xs:string"/>
				<xs:element name="PopulateNAClasses" type="xs:boolean"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="GetSolverParameters2Response">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Result" type="NAServerSolverParams"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
