<?xml version="1.0"?>
<xs:schema xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Carto.xsd" />
  <xs:simpleType name="esriNAServerLayerType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNAServerRouteLayer" />
      <xs:enumeration value="esriNAServerClosestFacilityLayer" />
      <xs:enumeration value="esriNAServerServiceAreaLayer" />
      <xs:enumeration value="esriNAServerODCostMatrixLayer" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriDirectionsOutputType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriDOTStandard" />
      <xs:enumeration value="esriDOTComplete" />
      <xs:enumeration value="esriDOTCompleteNoEvents" />
      <xs:enumeration value="esriDOTInstructionsOnly" />
      <xs:enumeration value="esriDOTSummaryOnly" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriDirectionsStringType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriDSTGeneral" />
      <xs:enumeration value="esriDSTDepart" />
      <xs:enumeration value="esriDSTArrive" />
      <xs:enumeration value="esriDSTLength" />
      <xs:enumeration value="esriDSTTime" />
      <xs:enumeration value="esriDSTSummary" />
      <xs:enumeration value="esriDSTTimeWindow" />
      <xs:enumeration value="esriDSTViolationTime" />
      <xs:enumeration value="esriDSTWaitTime" />
      <xs:enumeration value="esriDSTServiceTime" />
      <xs:enumeration value="esriDSTEstimatedArrivalTime" />
      <xs:enumeration value="esriDSTCumulativeLength" />
      <xs:enumeration value="esriDSTStreetName" />
      <xs:enumeration value="esriDSTAltName" />
      <xs:enumeration value="esriDSTBranch" />
      <xs:enumeration value="esriDSTToward" />
      <xs:enumeration value="esriDSTCrossStreet" />
      <xs:enumeration value="esriDSTExit" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriDirectionsManeuverType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriDMTUnknown" />
      <xs:enumeration value="esriDMTStop" />
      <xs:enumeration value="esriDMTStraight" />
      <xs:enumeration value="esriDMTBearLeft" />
      <xs:enumeration value="esriDMTBearRight" />
      <xs:enumeration value="esriDMTTurnLeft" />
      <xs:enumeration value="esriDMTTurnRight" />
      <xs:enumeration value="esriDMTSharpLeft" />
      <xs:enumeration value="esriDMTSharpRight" />
      <xs:enumeration value="esriDMTUTurn" />
      <xs:enumeration value="esriDMTFerry" />
      <xs:enumeration value="esriDMTRoundabout" />
      <xs:enumeration value="esriDMTHighwayMerge" />
      <xs:enumeration value="esriDMTHighwayExit" />
      <xs:enumeration value="esriDMTHighwayChange" />
      <xs:enumeration value="esriDMTForkCenter" />
      <xs:enumeration value="esriDMTForkLeft" />
      <xs:enumeration value="esriDMTForkRight" />
      <xs:enumeration value="esriDMTDepart" />
      <xs:enumeration value="esriDMTTripItem" />
      <xs:enumeration value="esriDMTEndOfFerry" />
      <xs:enumeration value="esriDMTRampRight" />
      <xs:enumeration value="esriDMTRampLeft" />
      <xs:enumeration value="esriDMTTurnLeftRight" />
      <xs:enumeration value="esriDMTTurnRightLeft" />
      <xs:enumeration value="esriDMTTurnRightRight" />
      <xs:enumeration value="esriDMTTurnLeftLeft" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriNAOutputLineType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNAOutputLineNone" />
      <xs:enumeration value="esriNAOutputLineStraight" />
      <xs:enumeration value="esriNAOutputLineTrueShape" />
      <xs:enumeration value="esriNAOutputLineTrueShapeWithMeasure" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriNAOutputPolygonType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNAOutputPolygonNone" />
      <xs:enumeration value="esriNAOutputPolygonSimplified" />
      <xs:enumeration value="esriNAOutputPolygonDetailed" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriNATravelDirection">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNATravelDirectionFromFacility" />
      <xs:enumeration value="esriNATravelDirectionToFacility" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriNAODCostMatrixType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNAODCostMatrixNone" />
      <xs:enumeration value="esriNAODCostMatrixFull" />
      <xs:enumeration value="esriNAODCostMatrixUpdate" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriNATimeOfDayUsage">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriNATimeOfDayNotUsed" />
      <xs:enumeration value="esriNATimeOfDayUseAsStartTime" />
      <xs:enumeration value="esriNATimeOfDayUseAsEndTime" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NAServerNetworkAttribute">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Units" type="esriNetworkAttributeUnits" />
      <xs:element name="DataType" type="esriNetworkAttributeDataType" />
      <xs:element name="UsageType" type="esriNetworkAttributeUsageType" />
      <xs:element minOccurs="0" name="ParameterNames" type="ArrayOfString" />
      <xs:element minOccurs="0" name="RestrictionUsageParameterName" type="xs:string" />
	  <xs:element minOccurs="0" name="TrafficSupport" type="esriNetworkTrafficSupport" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAServerNetworkAttribute">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAServerNetworkAttribute" type="NAServerNetworkAttribute" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerNetworkSource">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="ID" type="xs:int" />
      <xs:element name="SourceType" type="esriNetworkSourceType" />
      <xs:element name="ElementType" type="esriNetworkElementType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAServerNetworkSource">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAServerNetworkSource" type="NAServerNetworkSource" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerTravelMode">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="ItemID" type="xs:string" />
      <xs:element name="ImpedanceAttributeName" type="xs:string" />
      <xs:element name="TimeAttributeName" type="xs:string" />
      <xs:element name="DistanceAttributeName" type="xs:string" />
      <xs:element name="RestrictionAttributeNames" type="ArrayOfString" />
      <xs:element name="AttributeParameterValues" type="ArrayOfNAAttributeParameterValue" />
      <xs:element name="UseHierarchy" type="xs:boolean" />
      <xs:element name="RestrictUTurns" type="esriNetworkForwardStarBacktrack" />
      <xs:element name="OutputGeometryPrecision" type="xs:anyType" />
      <xs:element name="OutputGeometryPrecisionUnits" type="esriUnits" />
      <xs:element minOccurs="0" name="Type" type="xs:string" />
      <xs:element minOccurs="0" name="Description" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAServerTravelMode">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAServerTravelMode" type="NAServerTravelMode" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerNetworkDescription">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element minOccurs="0" name="NetworkAttributes" type="ArrayOfNAServerNetworkAttribute" />
      <xs:element minOccurs="0" name="NetworkSources" type="ArrayOfNAServerNetworkSource" />
      <xs:element minOccurs="0" name="NetworkDirections" type="NAServerNetworkDirections" />
      <xs:element minOccurs="0" name="BuildTime" type="xs:dateTime" />
      <xs:element minOccurs="0" name="State" type="esriNetworkDatasetState" />
      <xs:element minOccurs="0" name="ElevationModel" type="esriNetworkElevationModel" />
      <xs:element minOccurs="0" name="TravelModes" type="ArrayOfNAServerTravelMode" />
      <xs:element minOccurs="0" name="DefaultTravelMode" type="xs:string" />
      <xs:element minOccurs="0" name="TrafficSupport" type="esriNetworkTrafficSupport" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerNetworkDirections">
    <xs:sequence>
      <xs:element minOccurs="0" name="AvailableStyleNames" type="ArrayOfString" />
      <xs:element minOccurs="0" name="SupportedLanguages" type="ArrayOfString" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAClassCandidateFieldMap">
    <xs:sequence>
      <xs:element name="NAClassName" type="xs:string" />
      <xs:element minOccurs="0" name="CandidateFieldMaps" type="ArrayOfNACandidateFieldMap" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAClassCandidateFieldMap">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAClassCandidateFieldMap" type="NAClassCandidateFieldMap" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NACandidateFieldMap">
    <xs:sequence>
      <xs:element name="FieldName" type="xs:string" />
      <xs:element minOccurs="0" name="DefaultValue" type="xs:anyType" />
      <xs:element minOccurs="0" name="CandidateFieldNames" type="ArrayOfString" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNACandidateFieldMap">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NACandidateFieldMap" type="NACandidateFieldMap" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerLocations" abstract="true">
    <xs:sequence>    
      <xs:element minOccurs="0" name="DoNotLocateOnRestrictedElements" type="xs:boolean">
        <xs:annotation>
          <xs:documentation>Indicates if restricted network elements should be considered when finding network locations.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerPropertySets">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerLocations">
        <xs:sequence>
          <xs:element name="PropertySets" type="ArrayOfPropertySet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerRecordSet">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerLocations">
        <xs:sequence>
          <xs:element name="RecordSet" type="RecordSet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerDataLayer">
    <xs:annotation>
      <xs:documentation>A container that references a data layer containing network locations.</xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerLocations">
        <xs:sequence>
          <xs:element name="DataLayerName" type="xs:string">
            <xs:annotation>
              <xs:documentation>The name of the layer in the map.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="QueryFilter" type="QueryFilter">
            <xs:annotation>
              <xs:documentation>The query filter.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAAttributeParameterValue">
    <xs:sequence>
      <xs:element name="AttributeName" type="xs:string" />
      <xs:element name="ParameterName" type="xs:string" />
      <xs:element name="VarType" type="xs:long" />
      <xs:element minOccurs="0" name="Value" nillable="true" type="xs:anyType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAAttributeParameterValue">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAAttributeParameterValue" type="NAAttributeParameterValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerSolverParams" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" name="NALayerName" type="xs:string" />
      <xs:element name="SnapTolerance" type="xs:double" />
      <xs:element name="MaxSnapTolerance" type="xs:double" />
      <xs:element name="SnapToleranceUnits" type="esriUnits" />
      <xs:element name="NAClassCandidateFieldMaps" type="ArrayOfNAClassCandidateFieldMap" />
      <xs:element name="ReturnMap" type="xs:boolean" />
      <xs:element minOccurs="0" name="MapDescription" type="MapDescription" />
      <xs:element minOccurs="0" name="ImageDescription" type="ImageDescription" />
      <xs:element minOccurs="0" name="OutputSpatialReference" type="SpatialReference" />
      <xs:element name="ReturnGeometriesAsBinary" type="xs:boolean" />
      <xs:element minOccurs="0" name="AccumulateAttributeNames" type="ArrayOfString" />
      <xs:element name="ImpedanceAttributeName" type="xs:string" />
      <xs:element name="IgnoreInvalidLocations" type="xs:boolean" />
      <xs:element name="RestrictUTurns" type="esriNetworkForwardStarBacktrack" />
      <xs:element minOccurs="0" name="RestrictionAttributeNames" type="ArrayOfString" />
      <xs:element name="UseHierarchy" type="xs:boolean" />
      <xs:element minOccurs="0" name="HierarchyAttributeName" type="xs:string" />
      <xs:element name="HierarchyLevelCount" type="xs:int" />
      <xs:element minOccurs="0" name="HierarchyMaxValues" type="ArrayOfInt" />
      <xs:element minOccurs="0" name="HierarchyNumTransitions" type="ArrayOfInt" />
      <xs:element name="ResetHierarchyRangesOnBind" type="xs:boolean" />
      <xs:element minOccurs="0" name="AttributeParameterValues" type="ArrayOfNAAttributeParameterValue" />
      <xs:element minOccurs="0" name="OutputGeometryPrecision" type="xs:anyType">
        <xs:annotation>
          <xs:documentation>Specifies the precision of the output geometry after generalization.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="OutputGeometryPrecisionUnits" type="esriUnits">
        <xs:annotation>
          <xs:documentation>Specifies the units of the output geometry precision.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ReturnPartialResultsOnError" type="xs:boolean" />
      <xs:element minOccurs="0" name="SaveLayerOnServer" type="xs:boolean" />
      <xs:element minOccurs="0" name="LayerToken" type="xs:string" />
      <xs:element minOccurs="0" name="TravelMode" type="xs:string" />
      <xs:element minOccurs="0" name="TravelModeObject" type="NAServerTravelMode" />
      <xs:element minOccurs="0" name="Overrides" type="PropertySet" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerRouteParams">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverParams">
        <xs:sequence>
          <xs:element minOccurs="0" name="Stops" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Barriers" type="NAServerLocations" />
          <xs:element name="ReturnRouteGeometries" type="xs:boolean" />
          <xs:element name="ReturnRoutes" type="xs:boolean" />
          <xs:element name="ReturnStops" type="xs:boolean" />
          <xs:element name="ReturnBarriers" type="xs:boolean" />
          <xs:element name="ReturnDirections" type="xs:boolean" />
          <xs:element name="DirectionsLanguage" type="xs:string" />
          <xs:element name="DirectionsLengthUnits" type="esriNetworkAttributeUnits" />
          <xs:element name="DirectionsTimeAttributeName" type="xs:string" />
          <xs:element name="FindBestSequence" type="xs:boolean" />
          <xs:element name="PreserveFirstStop" type="xs:boolean" />
          <xs:element name="PreserveLastStop" type="xs:boolean" />
          <xs:element name="UseTimeWindows" type="xs:boolean" />
          <xs:element name="CreateTraversalResult" type="xs:boolean" />
          <xs:element name="OutputLines" type="esriNAOutputLineType" />
          <xs:element name="UseStartTime" type="xs:boolean" />
          <xs:element name="StartTime" type="xs:dateTime" />
          <xs:element name="ReturnCompactDirections" type="xs:boolean" />
          <xs:element minOccurs="0" name="DirectionsOutputType" type="esriDirectionsOutputType" />
          <xs:element minOccurs="0" name="DirectionsStyleName" type="xs:string" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="ReturnPolygonBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="ReturnPolylineBarriers" type="xs:boolean" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerClosestFacilityParams">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverParams">
        <xs:sequence>
          <xs:element minOccurs="0" name="Facilities" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Incidents" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Barriers" type="NAServerLocations" />
          <xs:element name="ReturnCFRouteGeometries" type="xs:boolean" />
          <xs:element name="ReturnCFRoutes" type="xs:boolean" />
          <xs:element name="ReturnFacilities" type="xs:boolean" />
          <xs:element name="ReturnIncidents" type="xs:boolean" />
          <xs:element name="ReturnBarriers" type="xs:boolean" />
          <xs:element name="ReturnDirections" type="xs:boolean" />
          <xs:element name="DirectionsLanguage" type="xs:string" />
          <xs:element name="DirectionsLengthUnits" type="esriNetworkAttributeUnits" />
          <xs:element name="DirectionsTimeAttributeName" type="xs:string" />
          <xs:element name="DefaultTargetFacilityCount" type="xs:int" />
          <xs:element minOccurs="0" name="DefaultCutoff" type="xs:anyType" />
          <xs:element name="TravelDirection" type="esriNATravelDirection" />
          <xs:element name="CreateTraversalResult" type="xs:boolean" />
          <xs:element name="OutputLines" type="esriNAOutputLineType" />
          <xs:element name="ReturnCompactDirections" type="xs:boolean" />
          <xs:element minOccurs="0" name="DirectionsOutputType" type="esriDirectionsOutputType" />
          <xs:element minOccurs="0" name="DirectionsStyleName" type="xs:string" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="ReturnPolygonBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="ReturnPolylineBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="TimeOfDay" type="xs:dateTime" />
          <xs:element minOccurs="0" name="TimeOfDayUsage" type="esriNATimeOfDayUsage" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerServiceAreaParams">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverParams">
        <xs:sequence>
          <xs:element minOccurs="0" name="Facilities" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Barriers" type="NAServerLocations" />
          <xs:element name="ReturnSALineGeometries" type="xs:boolean" />
          <xs:element name="ReturnSALines" type="xs:boolean" />
          <xs:element name="ReturnSAPolygonGeometries" type="xs:boolean" />
          <xs:element name="ReturnSAPolygons" type="xs:boolean" />
          <xs:element name="ReturnFacilities" type="xs:boolean" />
          <xs:element name="ReturnBarriers" type="xs:boolean" />
          <xs:element name="TravelDirection" type="esriNATravelDirection" />
          <xs:element name="DefaultBreaks" type="ArrayOfDouble" />
          <xs:element name="SplitPolygonsAtBreaks" type="xs:boolean" />
          <xs:element name="MergeSimilarPolygonRanges" type="xs:boolean" />
          <xs:element name="ExcludeSourcesFromPolygons" type="ArrayOfString" />
          <xs:element name="SplitLinesAtBreaks" type="xs:boolean" />
          <xs:element name="OverlapLines" type="xs:boolean" />
          <xs:element name="OutputPolygons" type="esriNAOutputPolygonType" />
          <xs:element name="OutputLines" type="esriNAOutputLineType" />
          <xs:element name="IncludeSourceInformationOnLines" type="xs:boolean" />
          <xs:element name="OverlapPolygons" type="xs:boolean" />
          <xs:element name="TrimOuterPolygon" type="xs:boolean" />
          <xs:element name="TrimPolygonDistance" type="xs:double" />
          <xs:element name="TrimPolygonDistanceUnits" type="esriUnits" />
          <xs:element name="CreateTraversalResult" type="xs:boolean" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="ReturnPolygonBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="ReturnPolylineBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="TimeOfDay" type="xs:dateTime" />
          <xs:element minOccurs="0" name="TimeOfDayUsage" type="esriNATimeOfDayUsage" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerODCostMatrixParams">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverParams">
        <xs:sequence>
          <xs:element minOccurs="0" name="Origins" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Destinations" type="NAServerLocations" />
          <xs:element minOccurs="0" name="Barriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="NAServerLocations" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="NAServerLocations" />
          <xs:element name="ReturnODLines" type="xs:boolean" />
          <xs:element name="ReturnODMatrix" type="xs:boolean" />
          <xs:element name="ReturnOrigins" type="xs:boolean" />
          <xs:element name="ReturnDestinations" type="xs:boolean" />
          <xs:element name="ReturnBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="ReturnPolygonBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="ReturnPolylineBarriers" type="xs:boolean" />
          <xs:element minOccurs="0" name="DefaultCutoff" type="xs:anyType" />
          <xs:element minOccurs="0" name="DefaultTargetDestinationCount" type="xs:anyType" />
          <xs:element name="OutputLines" type="esriNAOutputLineType" />
          <xs:element name="MatrixResultType" type="esriNAODCostMatrixType" />
          <xs:element name="PopulateODLines" type="xs:boolean" />
          <xs:element minOccurs="0" name="TimeOfDay" type="xs:dateTime" />
          <xs:element minOccurs="0" name="TimeOfDayUsage" type="esriNATimeOfDayUsage" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerSolverResults" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" name="MapImage" type="MapImage" />
      <xs:element minOccurs="0" name="SolveMessages" type="GPMessages" />
      <xs:element minOccurs="0" name="SolveErrorCode" type="xs:int" />
      <xs:element minOccurs="0" name="LayerToken" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAServerRouteResults">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverResults">
        <xs:sequence>
          <xs:element minOccurs="0" name="TotalImpedances" type="ArrayOfDouble" />
          <xs:element minOccurs="0" name="RouteGeometries" type="ArrayOfPolyline" />
          <xs:element minOccurs="0" name="Routes" type="RecordSet" />
          <xs:element minOccurs="0" name="Stops" type="RecordSet" />
          <xs:element minOccurs="0" name="Barriers" type="RecordSet" />
          <xs:element minOccurs="0" name="Directions" type="ArrayOfNAStreetDirections" />
          <xs:element minOccurs="0" name="CompactDirections" type="ArrayOfNACompactStreetDirections" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="RecordSet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerClosestFacilityResults">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverResults">
        <xs:sequence>
          <xs:element minOccurs="0" name="TotalImpedances" type="ArrayOfDouble" />
          <xs:element minOccurs="0" name="CFRouteGeometries" type="ArrayOfPolyline" />
          <xs:element minOccurs="0" name="CFRoutes" type="RecordSet" />
          <xs:element minOccurs="0" name="Facilities" type="RecordSet" />
          <xs:element minOccurs="0" name="Incidents" type="RecordSet" />
          <xs:element minOccurs="0" name="Barriers" type="RecordSet" />
          <xs:element minOccurs="0" name="Directions" type="ArrayOfNAStreetDirections" />
          <xs:element minOccurs="0" name="CompactDirections" type="ArrayOfNACompactStreetDirections" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="RecordSet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerServiceAreaResults">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverResults">
        <xs:sequence>
          <xs:element minOccurs="0" name="SALineGeometries" type="ArrayOfPolyline" />
          <xs:element minOccurs="0" name="SALines" type="RecordSet" />
          <xs:element minOccurs="0" name="SAPolygonGeometries" type="ArrayOfPolygon" />
          <xs:element minOccurs="0" name="SAPolygons" type="RecordSet" />
          <xs:element minOccurs="0" name="Facilities" type="RecordSet" />
          <xs:element minOccurs="0" name="Barriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="RecordSet" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAServerODCostMatrixResults">
    <xs:complexContent mixed="false">
      <xs:extension base="NAServerSolverResults">
        <xs:sequence>
          <xs:element minOccurs="0" name="ODLines" type="RecordSet" />
          <xs:element minOccurs="0" name="Origins" type="RecordSet" />
          <xs:element minOccurs="0" name="Destinations" type="RecordSet" />
          <xs:element minOccurs="0" name="Barriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolygonBarriers" type="RecordSet" />
          <xs:element minOccurs="0" name="PolylineBarriers" type="RecordSet" />
          <xs:element minOccurs="0" name="OriginOIDIndex" type="ArrayOfInt" />
          <xs:element minOccurs="0" name="DestinationOIDIndex" type="ArrayOfInt" />
          <xs:element minOccurs="0" name="CostAttributeNameIndex" type="ArrayOfString" />
          <xs:element minOccurs="0" name="ODMatrix" type="xs:base64Binary" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="NAStreetDirections">
    <xs:sequence>
      <xs:element name="RouteID" type="xs:int" />
      <xs:element name="RouteName" type="xs:string" />
      <xs:element name="Summary" type="NAStreetDirection" />
      <xs:element name="Directions" type="ArrayOfNAStreetDirection" />
      <xs:element name="StopNames" type="ArrayOfString" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAStreetDirection">
    <xs:sequence>
      <xs:element name="DriveTime" type="xs:double" />
      <xs:element name="Envelope" type="Envelope" />
      <xs:element name="Length" type="xs:double" />
      <xs:element name="ManeuverPoint" type="Point" />
      <xs:element name="Time" type="xs:double" />
      <xs:element name="Strings" type="ArrayOfString" />
      <xs:element name="StringTypes" type="ArrayOfDirectionsStringType" />
      <xs:element name="CumulativeLength" type="xs:double" />
      <xs:element name="EstimatedArrivalTime" type="xs:dateTime" />
      <xs:element name="ManeuverType" type="esriDirectionsManeuverType" />
      <xs:element name="TurnAngle" type="xs:double" />
      <xs:element name="DepartBearing" type="xs:double" />
      <xs:element name="GeneralBearing" type="xs:double" />
      <xs:element minOccurs="0" name="Events" type="ArrayOfNAStreetDirectionEvent" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAStreetDirections">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAStreetDirections" type="NAStreetDirections" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAStreetDirection">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAStreetDirection" type="NAStreetDirection" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfDirectionsStringType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="DirectionsStringType" type="esriDirectionsStringType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NACompactStreetDirections">
    <xs:sequence>
      <xs:element name="RouteID" type="xs:int" />
      <xs:element name="RouteName" type="xs:string" />
      <xs:element name="Summary" type="NACompactStreetDirectionSummary" />
      <xs:element name="Directions" type="ArrayOfNACompactStreetDirection" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NACompactStreetDirection">
    <xs:sequence>
      <xs:element name="Length" type="xs:double" />
      <xs:element name="Time" type="xs:double" />
      <xs:element name="Text" type="xs:string" />
      <xs:element name="CompressedGeometry" type="xs:string" />
      <xs:element name="ETA" type="xs:dateTime" />
      <xs:element name="ManeuverType" type="esriDirectionsManeuverType" />
      <xs:element name="TurnAngle" type="xs:double" />
      <xs:element name="DepartBearing" type="xs:double" />
      <xs:element name="GeneralBearing" type="xs:double" />
      <xs:element minOccurs="0" name="Events" type="ArrayOfNAStreetDirectionEvent" />
      <xs:element minOccurs="0" name="Strings" type="ArrayOfString" />
      <xs:element minOccurs="0" name="StringTypes" type="ArrayOfDirectionsStringType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNACompactStreetDirections">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NACompactStreetDirections" type="NACompactStreetDirections" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNACompactStreetDirection">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NACompactStreetDirection" type="NACompactStreetDirection" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NACompactStreetDirectionSummary">
    <xs:sequence>
      <xs:element name="TotalLength" type="xs:double" />
      <xs:element name="TotalTime" type="xs:double" />
      <xs:element name="TotalDriveTime" type="xs:double" />
      <xs:element name="Envelope" type="Envelope" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NAStreetDirectionEvent">
    <xs:sequence>
      <xs:element name="ETA" type="xs:dateTime" />
      <xs:element name="Point" type="Point" />
      <xs:element name="Strings" type="ArrayOfString" />
      <xs:element name="StringTypes" type="ArrayOfDirectionsStringType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfNAStreetDirectionEvent">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="NAStreetDirectionEvent" type="NAStreetDirectionEvent" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
