-- Create databases for PACS Server-Benton
IF DB_ID('pacs_oltp') IS NULL CREATE DATABASE [pacs_oltp];
IF DB_ID('PACS_Training') IS NULL CREATE DATABASE [PACS_Training];
IF DB_ID('TA_AppSvr') IS NULL CREATE DATABASE [TA_AppSvr];
IF DB_ID('CIAPS') IS NULL CREATE DATABASE [CIAPS];
IF DB_ID('Web_Internet_Benton') IS NULL CREATE DATABASE [Web_Internet_Benton];
IF DB_ID('SSISDB') IS NULL CREATE DATABASE [SSISDB];

-- Basic settings (can be refined per environment)
ALTER DATABASE [pacs_oltp] SET RECOVERY SIMPLE;
ALTER DATABASE [PACS_Training] SET RECOVERY SIMPLE;
ALTER DATABASE [TA_AppSvr] SET RECOVERY SIMPLE;
ALTER DATABASE [CIAPS] SET RECOVERY SIMPLE;
ALTER DATABASE [Web_Internet_Benton] SET RECOVERY SIMPLE;
ALTER DATABASE [SSISDB] SET RECOVERY SIMPLE;

