import React from 'react';
import App from './App';
import {Zap, Activity, Shield, Globe} from 'lucide-react';

interface BrandedAppProps {className?: string;}

export const BrandedApp: React.FC<BrandedAppProps>= ({className}) => {
  return (<div className={`terrafusion-branded-app terra-flow-app ${className || ''}`}>{/* TerraFusion Header */}<div className="terrafusion-header bg-gradient-to-r from-blue-900 via-purple-900 to-indigo-900 text-white py-3 px-6"><div className="max-w-7xl mx-auto flex items-center justify-between"><div className="flex items-center gap-3"><div className="p-2 bg-white/20 rounded-lg backdrop-blur-sm"><Zap className="w-6 h-6 text-white" /></div><div><h1 className="text-xl font-bold">TerraFusion OS</h1><span className="text-blue-200 text-sm font-medium">Terra Flow Module</span></div></div><div className="flex items-center gap-6 text-sm"><div className="flex items-center gap-2"><Activity className="w-4 h-4 text-green-400" /><span className="text-green-300">System Active</span></div><div className="text-blue-200">|</div><div className="flex items-center gap-2"><Shield className="w-4 h-4 text-purple-400" /><span className="text-purple-300">Secure</span></div><div className="text-blue-200">|</div><div className="flex items-center gap-2"><Globe className="w-4 h-4 text-cyan-400" /><span className="text-cyan-300">Connected</span></div></div></div></div>{/* Main Terra Flow Application */}<div className="terra-flow-main"><App /></div>{/* TerraFusion Footer */}<div className="terrafusion-footer bg-gray-900 text-gray-300 py-4 px-6"><div className="max-w-7xl mx-auto"><div className="flex items-center justify-between text-sm"><div className="flex items-center gap-6"><span>© 2025 TerraFusion OS</span><span className="text-gray-500">|</span><span>Terra Flow v2.0.0</span><span className="text-gray-500">|</span><span>MIT PhD-Level Architecture</span></div><div className="system-status flex items-center gap-4"><div className="flex items-center gap-2"><div className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></div><span className="text-green-400">Online</span></div><span className="text-gray-500">|</span><div className="flex items-center gap-2"><div className="w-2 h-2 bg-blue-400 rounded-full"></div><span className="text-blue-400">Optimized</span></div><span className="text-gray-500">|</span><div className="flex items-center gap-2"><div className="w-2 h-2 bg-purple-400 rounded-full"></div><span className="text-purple-400">Enhanced</span></div></div></div></div></div></div>
  );
};

export default BrandedApp;
