CREATE TABLE [dbo].[__property_exemption_dor_sams_20230224] (
    [prop_id]                     INT            NOT NULL,
    [owner_id]                    INT            NOT NULL,
    [exmpt_tax_yr]                NUMERIC (4)    NOT NULL,
    [owner_tax_yr]                NUMERIC (4)    NOT NULL,
    [prop_type_cd]                CHAR (5)       NOT NULL,
    [exmpt_type_cd]               VARCHAR (10)   NOT NULL,
    [applicant_nm]                VARCHAR (70)   NULL,
    [birth_dt]                    DATETIME       NULL,
    [spouse_birth_dt]             DATETIME       NULL,
    [prop_exmpt_dl_num]           VARCHAR (20)   NULL,
    [prop_exmpt_ss_num]           VARCHAR (11)   NULL,
    [effective_dt]                DATETIME       NULL,
    [termination_dt]              DATETIME       NULL,
    [apply_pct_owner]             NUMERIC (5, 2) NULL,
    [sup_num]                     INT            NOT NULL,
    [effective_tax_yr]            NUMERIC (4)    NULL,
    [qualify_yr]                  NUMERIC (4)    NULL,
    [sp_date_approved]            DATETIME       NULL,
    [sp_expiration_date]          DATETIME       NULL,
    [sp_comment]                  VARCHAR (5000) NULL,
    [sp_value_type]               CHAR (1)       NULL,
    [sp_value_option]             CHAR (1)       NULL,
    [absent_flag]                 BIT            NULL,
    [absent_expiration_date]      DATETIME       NULL,
    [absent_comment]              VARCHAR (255)  NULL,
    [deferral_date]               DATETIME       NULL,
    [apply_local_option_pct_only] CHAR (1)       NULL,
    [apply_no_exemption_amount]   BIT            NULL,
    [exmpt_subtype_cd]            VARCHAR (10)   NULL,
    [exemption_pct]               NUMERIC (5, 2) NULL,
    [combined_disp_income]        NUMERIC (14)   NULL,
    [exempt_qualify_cd]           VARCHAR (10)   NULL,
    [review_request_date]         DATETIME       NULL,
    [review_status_cd]            VARCHAR (10)   NULL,
    [review_last_year]            NUMERIC (4)    NULL,
    [dor_value_type]              CHAR (1)       NULL,
    [dor_exmpt_amount]            NUMERIC (12)   NULL,
    [dor_exmpt_percent]           NUMERIC (9, 6) NULL
);


GO

