CREATE TABLE [dbo].[_bs_ratio_cd_2022] (
    [chg_of_owner_id]          INT             NOT NULL,
    [sl_ratio]                 NUMERIC (5, 2)  NULL,
    [sl_financing_cd]          CHAR (5)        NULL,
    [sl_ratio_type_cd]         CHAR (5)        NULL,
    [sl_adj_cd]                CHAR (5)        NULL,
    [sl_type_cd]               CHAR (5)        NULL,
    [sl_state_cd]              CHAR (5)        NULL,
    [sl_class_cd]              CHAR (10)       NULL,
    [sl_land_type_cd]          CHAR (10)       NULL,
    [sl_price]                 NUMERIC (14)    NULL,
    [sl_dt]                    DATETIME        NULL,
    [adjusted_sl_price]        NUMERIC (14)    NULL,
    [realtor]                  VARCHAR (30)    NULL,
    [finance_comment]          VARCHAR (50)    NULL,
    [amt_down]                 NUMERIC (18)    NULL,
    [amt_financed]             NUMERIC (18)    NULL,
    [interest_rate]            NUMERIC (14, 3) NULL,
    [finance_yrs]              NUMERIC (4, 1)  NULL,
    [suppress_on_ratio_rpt_cd] CHAR (5)        NULL,
    [suppress_on_ratio_rsn]    VARCHAR (30)    NULL,
    [sl_adj_sl_pct]            NUMERIC (8, 4)  NULL,
    [sl_adj_sl_amt]            NUMERIC (14)    NULL,
    [sl_adj_rsn]               VARCHAR (50)    NULL,
    [sl_comment]               VARCHAR (500)   NULL,
    [sl_yr_blt]                NUMERIC (4)     NULL,
    [sl_living_area]           NUMERIC (14)    NULL,
    [sl_imprv_unit_price]      NUMERIC (14, 2) NULL,
    [sl_land_sqft]             NUMERIC (18, 2) NULL,
    [sl_land_acres]            NUMERIC (18, 4) NULL,
    [sl_land_front_feet]       NUMERIC (18, 2) NULL,
    [sl_land_depth]            NUMERIC (18, 2) NULL,
    [sl_land_unit_price]       NUMERIC (14, 2) NULL,
    [sl_school_id]             INT             NULL,
    [sl_city_id]               INT             NULL,
    [sl_qualifier]             VARCHAR (10)    NULL,
    [include_no_calc]          CHAR (1)        NULL,
    [sl_ratio_cd]              CHAR (5)        NULL,
    [import_dt]                DATETIME        NULL,
    [include_reason]           VARCHAR (30)    NULL,
    [sales_exclude_calc_cd]    VARCHAR (10)    NULL,
    [amt_financed_2]           NUMERIC (18)    NULL,
    [interest_rate_2]          NUMERIC (14, 2) NULL,
    [finance_yrs_2]            NUMERIC (4, 1)  NULL,
    [sl_sub_class_cd]          VARCHAR (10)    NULL,
    [sl_imprv_type_cd]         VARCHAR (5)     NULL,
    [confidential_sale]        CHAR (1)        NULL,
    [frozen_characteristics]   CHAR (1)        NULL,
    [num_days_on_market]       NUMERIC (4)     NULL,
    [sl_exported_flag]         CHAR (1)        NULL,
    [land_only_sale]           BIT             NULL,
    [monthly_income]           NUMERIC (14)    NULL,
    [annual_income]            NUMERIC (14)    NULL,
    [sl_ratio_cd_reason]       VARCHAR (100)   NULL,
    [continue_current_use]     BIT             NULL,
    [sl_county_ratio_cd]       VARCHAR (10)    NULL,
    [primary_use_cd]           VARCHAR (10)    NULL,
    [secondary_use_cd]         VARCHAR (10)    NULL,
    [listing_price]            NUMERIC (14)    NULL,
    [listing_dt]               DATETIME        NULL,
    [pers_prop_val]            NUMERIC (14)    NULL,
    [exemption_amount]         NUMERIC (14)    NULL,
    [wac_cd]                   VARCHAR (32)    NULL
);


GO

