CREATE TABLE [dbo].[_steve_pers_prop_seg_20231023] (
    [prop_id]                INT             NOT NULL,
    [prop_val_yr]            NUMERIC (4)     NOT NULL,
    [sup_num]                INT             NOT NULL,
    [pp_seg_id]              INT             NOT NULL,
    [sale_id]                INT             NULL,
    [pp_sched_cd]            CHAR (10)       NULL,
    [pp_table_meth_cd]       CHAR (5)        NULL,
    [pp_type_cd]             CHAR (10)       NULL,
    [pp_class_cd]            CHAR (5)        NULL,
    [pp_density_cd]          CHAR (5)        NULL,
    [pp_adj_cd]              CHAR (5)        NULL,
    [pp_area]                NUMERIC (12)    NULL,
    [pp_unit_count]          NUMERIC (16, 4) NULL,
    [pp_yr_aquired]          NUMERIC (4)     NULL,
    [pp_dep_method]          CHAR (5)        NULL,
    [pp_pct_good]            NUMERIC (5, 2)  NULL,
    [pp_orig_cost]           NUMERIC (14)    NULL,
    [pp_economic_pct]        NUMERIC (5, 2)  NULL,
    [pp_physical_pct]        NUMERIC (5, 2)  NULL,
    [pp_flat_val]            NUMERIC (14)    NULL,
    [pp_rendered_val]        NUMERIC (14)    NULL,
    [pp_prior_yr_val]        NUMERIC (14)    NULL,
    [pp_last_notice_val]     NUMERIC (14)    NULL,
    [pp_method_val]          NUMERIC (14)    NULL,
    [pp_appraised_val]       NUMERIC (14)    NULL,
    [pp_appraise_meth]       CHAR (5)        NULL,
    [pp_new_val]             NUMERIC (14)    NULL,
    [pp_new_val_yr]          NUMERIC (4)     NULL,
    [pp_mkt_val]             NUMERIC (14)    NULL,
    [pp_comment]             VARCHAR (500)   NULL,
    [pp_unit_price]          NUMERIC (14, 2) NULL,
    [pp_qual_cd]             CHAR (5)        NULL,
    [pp_description]         VARCHAR (255)   NULL,
    [pp_sic_cd]              VARCHAR (10)    NULL,
    [pp_mkt_val_cd]          CHAR (5)        NULL,
    [pp_state_cd]            CHAR (5)        NULL,
    [pp_deprec_type_cd]      CHAR (10)       NULL,
    [pp_deprec_deprec_cd]    CHAR (10)       NULL,
    [pp_deprec_override]     CHAR (1)        NULL,
    [pp_deprec_pct]          NUMERIC (5, 2)  NULL,
    [pp_active_flag]         CHAR (1)        NULL,
    [pp_make]                VARCHAR (10)    NULL,
    [pp_model]               VARCHAR (10)    NULL,
    [pp_vin]                 VARCHAR (30)    NULL,
    [pp_matching_status]     VARCHAR (10)    NULL,
    [pp_matching_dt]         DATETIME        NULL,
    [pp_year]                NUMERIC (4)     NULL,
    [pp_license]             VARCHAR (10)    NULL,
    [pp_condition_cd]        VARCHAR (10)    NULL,
    [arb_val]                NUMERIC (14)    NULL,
    [pp_special_val]         NUMERIC (14)    NULL,
    [pp_subseg_val]          NUMERIC (14)    NULL,
    [sp_method]              CHAR (1)        NULL,
    [sp_per_unit_val]        NUMERIC (14, 2) NULL,
    [sp_per_area_val]        NUMERIC (14, 2) NULL,
    [sp_units_area_number]   NUMERIC (14)    NULL,
    [dist_val]               NUMERIC (14)    NOT NULL,
    [tsRowVersion]           ROWVERSION      NOT NULL,
    [pp_new_val_override]    BIT             NOT NULL,
    [pp_new_val_yr_override] BIT             NOT NULL,
    [pp_new_segment]         BIT             NOT NULL,
    [farm_asset]             BIT             NOT NULL,
    [locked_val]             NUMERIC (14)    NULL
);


GO

