CREATE TABLE [dbo].[building_permit_tidemark_full_import] (
    [run_id]                       INT             NOT NULL,
    [record_id]                    INT             NOT NULL,
    [permit_number]                VARCHAR (30)    NULL,
    [permit_status]                VARCHAR (5)     NULL,
    [issue_date]                   DATETIME        NULL,
    [complete_date]                DATETIME        NULL,
    [street_num]                   VARCHAR (15)    NULL,
    [street_prefix]                VARCHAR (10)    NULL,
    [street_sub_num]               VARCHAR (5)     NULL,
    [street_name]                  VARCHAR (50)    NULL,
    [street_suffix]                VARCHAR (10)    NULL,
    [street_unit_type]             VARCHAR (15)    NULL,
    [street_unit]                  VARCHAR (15)    NULL,
    [building_number]              VARCHAR (15)    NULL,
    [city]                         VARCHAR (50)    NULL,
    [subdivision]                  VARCHAR (50)    NULL,
    [plat]                         VARCHAR (4)     NULL,
    [block]                        VARCHAR (4)     NULL,
    [lot]                          VARCHAR (50)    NULL,
    [res_comm]                     CHAR (1)        NULL,
    [permit_value]                 NUMERIC (14)    NULL,
    [area]                         NUMERIC (9)     NULL,
    [dimension_1]                  VARCHAR (10)    NULL,
    [dimension_2]                  VARCHAR (10)    NULL,
    [dimension_3]                  VARCHAR (10)    NULL,
    [num_floors]                   INT             NULL,
    [num_units]                    INT             NULL,
    [comments]                     VARCHAR (512)   NULL,
    [sub_type_cd]                  VARCHAR (5)     NULL,
    [sub_type_desc]                VARCHAR (50)    NULL,
    [building_inspect_request]     CHAR (1)        NULL,
    [elec_inspect_requested]       CHAR (1)        NULL,
    [mechanical_inspect_requested] CHAR (1)        NULL,
    [plumb_inspect_requested]      CHAR (1)        NULL,
    [issued_to]                    VARCHAR (50)    NULL,
    [owner_phone]                  VARCHAR (16)    NULL,
    [builder]                      VARCHAR (50)    NULL,
    [builder_phone]                VARCHAR (16)    NULL,
    [old_permit_number]            VARCHAR (30)    NULL,
    [place_id]                     NUMERIC (9)     NULL,
    [tidemark_id]                  VARCHAR (15)    NULL,
    [limit_date]                   DATETIME        NULL,
    [calculated_value]             NUMERIC (14)    NULL,
    [active]                       CHAR (1)        NULL,
    [last_change_date]             DATETIME        NULL,
    [case_name]                    VARCHAR (30)    NULL,
    [project_number]               VARCHAR (15)    NULL,
    [project_name]                 VARCHAR (30)    NULL,
    [total_acreage]                NUMERIC (18, 4) NULL,
    [primary_zoning]               VARCHAR (20)    NULL,
    [secondary_zoning]             VARCHAR (20)    NULL,
    [legal]                        VARCHAR (255)   NULL,
    [property_id]                  VARCHAR (12)    NULL,
    [geo_id]                       VARCHAR (25)    NULL,
    [case_description]             VARCHAR (255)   NULL,
    [issuer]                       VARCHAR (30)    NULL,
    [work_type_cd]                 VARCHAR (10)    NULL,
    [worksheet_type]               VARCHAR (10)    NULL,
    CONSTRAINT [CPK_building_permit_tidemark_full_import] PRIMARY KEY CLUSTERED ([run_id] ASC, [record_id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [CFK_building_permit_tidemark_full_import_run_id] FOREIGN KEY ([run_id]) REFERENCES [dbo].[import_building_permit] ([run_id])
);


GO

