CREATE TABLE [dbo].[effective_tax_rate] (
    [tax_yr]                                DECIMAL (4)     NOT NULL,
    [entity_id]                             INT             NOT NULL,
    [py_total_taxable_value]                DECIMAL (14)    NULL,
    [py_taxable_value_ov65]                 DECIMAL (14)    NULL,
    [py_prelim_adj_taxable_value]           DECIMAL (14)    NULL,
    [py_tax_rate]                           DECIMAL (8, 6)  NULL,
    [py_original_arb_values]                DECIMAL (14)    NULL,
    [py_resulting_values]                   DECIMAL (14)    NULL,
    [py_arb_value_loss]                     DECIMAL (14)    NULL,
    [py_adj_taxable_value_court_ordered]    DECIMAL (14)    NULL,
    [py_deannexed_value]                    DECIMAL (14)    NULL,
    [py_new_absolute_exemption_loss]        DECIMAL (14)    NULL,
    [py_new_partial_exemption_loss]         DECIMAL (14)    NULL,
    [py_new_exemption_loss]                 DECIMAL (14)    NULL,
    [py_new_ag_market_value]                DECIMAL (14)    NULL,
    [cy_new_ag_value]                       DECIMAL (14)    NULL,
    [cy_new_ag_loss]                        DECIMAL (14)    NULL,
    [total_adj_value_loss]                  DECIMAL (14)    NULL,
    [py_adj_taxable_value]                  DECIMAL (14)    NULL,
    [py_adj_taxes]                          DECIMAL (14)    NULL,
    [tax_refunded]                          DECIMAL (14)    NULL,
    [py_adj_taxes_w_refunds]                DECIMAL (14)    NULL,
    [cy_certified_values]                   DECIMAL (14)    NULL,
    [cy_rolling_stock]                      DECIMAL (14)    NULL,
    [cy_new_pollution_control]              DECIMAL (14)    NULL,
    [cy_taxable_values]                     DECIMAL (14)    NULL,
    [cy_taxable_values_under_protest]       DECIMAL (14)    NULL,
    [cy_taxable_value_ov65]                 DECIMAL (14)    NULL,
    [cy_total_taxable_value]                DECIMAL (14)    NULL,
    [cy_annexed_valued]                     DECIMAL (14)    NULL,
    [cy_new_value]                          DECIMAL (14)    NULL,
    [cy_adjustments]                        DECIMAL (14)    NULL,
    [cy_adj_taxable_value]                  DECIMAL (14)    NULL,
    [cy_effective_tax_rate]                 DECIMAL (14, 6) NULL,
    [cy_county_tax_rate]                    DECIMAL (14, 6) NULL,
    [rb_py_m_n_o_tax_rate]                  DECIMAL (14, 6) NULL,
    [rb_py_adj_taxable_value]               DECIMAL (14)    NULL,
    [rb_27a]                                DECIMAL (14)    NULL,
    [rb_py_m_n_o_taxes]                     DECIMAL (14)    NULL,
    [rb_py_m_n_o_sales_tax]                 DECIMAL (14)    NULL,
    [rb_county_criminal_justice_mandate]    DECIMAL (14)    NULL,
    [rb_transferring_function]              DECIMAL (14)    NULL,
    [rb_py_taxes_refunded]                  DECIMAL (14)    NULL,
    [rb_py_m_n_o_taxes_total]               DECIMAL (14)    NULL,
    [rb_cy_m_n_o_component]                 DECIMAL (14)    NULL,
    [rb_cy_adj_taxable_value]               DECIMAL (14)    NULL,
    [rb_cy_taxable_value_certified]         DECIMAL (14)    NULL,
    [rb_cy_taxable_value_under_protest]     DECIMAL (14)    NULL,
    [rb_cy_taxable_value_ov65]              DECIMAL (14)    NULL,
    [rb_cy_taxable_value]                   DECIMAL (14)    NULL,
    [rb_cy_tax_increment_fund]              DECIMAL (14)    NULL,
    [rb_29c]                                DECIMAL (14)    NULL,
    [rb_cy_m_n_o_tax_rate]                  DECIMAL (14, 6) NULL,
    [rb_cy_rollback_m_n_o_tax_rate]         DECIMAL (14, 6) NULL,
    [rb_cy_taxes_paid_with_sales_tax]       DECIMAL (14)    NULL,
    [rb_py_excess_debt_collections]         DECIMAL (14)    NULL,
    [rb_cy_adjusted_debt]                   DECIMAL (14)    NULL,
    [rb_cy_anticipated_collection_rate]     DECIMAL (14, 2) NULL,
    [rb_cy_debt_adjusted_for_collections]   DECIMAL (14)    NULL,
    [rb_cy_total_taxable_value]             DECIMAL (14)    NULL,
    [rb_cy_debt_tax_rate]                   DECIMAL (14, 6) NULL,
    [rb_cy_rollback_tax_rate]               DECIMAL (14, 6) NULL,
    [rb_cy_county_rollback_tax_rate]        DECIMAL (14, 6) NULL,
    [ast_sales_tax_estimate]                DECIMAL (14)    NULL,
    [ast_estimated_sales_tax_revenue]       DECIMAL (14)    NULL,
    [ast_cy_total_taxable_value]            DECIMAL (14)    NULL,
    [ast_sales_tax_adjustment_rate]         DECIMAL (14, 6) NULL,
    [ast_cy_effective_tax_rate_unadj_sales] DECIMAL (14, 6) NULL,
    [ast_cy_effective_tax_rate_adj_sales]   DECIMAL (14, 6) NULL,
    [ast_cy_rollback_tax_rate_unadj_sales]  DECIMAL (14, 6) NULL,
    [ast_cy_rollback_tax_rate_adj_sales]    DECIMAL (14, 6) NULL,
    [pc_expenses_tnrcc]                     DECIMAL (14)    NULL,
    [pc_cy_total_taxable_value]             DECIMAL (14)    NULL,
    [pc_add_rate_pollution]                 DECIMAL (14, 6) NULL,
    [pc_cy_rollback_tax_rate_adj_pollution] DECIMAL (14, 6) NULL,
    [ihc_expenses_ihc]                      DECIMAL (14)    NULL,
    [ihc_cy_total_taxable_value]            DECIMAL (14)    NULL,
    [ihc_add_rate_ihc]                      DECIMAL (14, 6) NULL,
    [ihc_cy_rollback_tax_rate_adj_ihc]      DECIMAL (14, 6) NULL,
    CONSTRAINT [CPK_effective_tax_rate] PRIMARY KEY CLUSTERED ([tax_yr] ASC, [entity_id] ASC) WITH (FILLFACTOR = 100)
);


GO

