CREATE TABLE [dbo].[imprv_rows_02212019] (
    [prop_id]                INT              NOT NULL,
    [prop_val_yr]            NUMERIC (4)      NOT NULL,
    [imprv_id]               INT              NOT NULL,
    [sup_num]                INT              NOT NULL,
    [sale_id]                INT              NOT NULL,
    [imprv_type_cd]          VARCHAR (5)      NULL,
    [imprv_state_cd]         VARCHAR (5)      NULL,
    [imprv_homesite]         VARCHAR (1)      NULL,
    [imprv_desc]             VARCHAR (255)    NULL,
    [imprv_val]              NUMERIC (14)     NULL,
    [imp_new_val]            NUMERIC (14)     NULL,
    [imp_new_val_override]   VARCHAR (1)      NULL,
    [adjusted_val]           NUMERIC (14)     NULL,
    [imprv_cmnt]             VARCHAR (1000)   NULL,
    [mbl_hm_make]            VARCHAR (100)    NULL,
    [mbl_hm_model]           VARCHAR (100)    NULL,
    [mbl_hm_sn]              VARCHAR (100)    NULL,
    [mbl_hm_hud_num]         VARCHAR (100)    NULL,
    [mbl_hm_title_num]       VARCHAR (100)    NULL,
    [flat_val]               NUMERIC (14)     NULL,
    [imprv_val_source]       VARCHAR (1)      NULL,
    [economic_pct]           NUMERIC (5, 2)   NULL,
    [physical_pct]           NUMERIC (5, 2)   NULL,
    [functional_pct]         NUMERIC (5, 2)   NULL,
    [economic_cmnt]          VARCHAR (255)    NULL,
    [physical_cmnt]          VARCHAR (255)    NULL,
    [functional_cmnt]        VARCHAR (255)    NULL,
    [effective_yr_blt]       NUMERIC (4)      NULL,
    [percent_complete]       NUMERIC (5, 2)   NULL,
    [percent_complete_cmnt]  VARCHAR (255)    NULL,
    [num_imprv]              INT              NULL,
    [mbl_hm_sn_2]            VARCHAR (100)    NULL,
    [mbl_hm_sn_3]            VARCHAR (100)    NULL,
    [mbl_hm_hud_num_2]       VARCHAR (100)    NULL,
    [mbl_hm_hud_num_3]       VARCHAR (100)    NULL,
    [stories]                VARCHAR (5)      NULL,
    [dep_pct]                NUMERIC (5, 2)   NULL,
    [dep_cmnt]               VARCHAR (255)    NULL,
    [hs_pct]                 NUMERIC (13, 10) NULL,
    [hs_pct_override]        BIT              NOT NULL,
    [primary_use_cd]         VARCHAR (10)     NULL,
    [primary_use_override]   BIT              NOT NULL,
    [secondary_use_cd]       VARCHAR (10)     NULL,
    [secondary_use_override] BIT              NOT NULL,
    [actual_year_built]      NUMERIC (4)      NULL,
    [building_number]        VARCHAR (6)      NULL,
    [building_name]          VARCHAR (50)     NULL,
    [flat_value_comment]     VARCHAR (3000)   NULL,
    [flat_value_user_id]     INT              NULL,
    [flat_value_date]        DATETIME         NULL,
    [mbl_hm_year]            NUMERIC (4)      NULL,
    [mbl_hm_tip_out]         NUMERIC (10)     NULL,
    [custom_imp_new_val]     NUMERIC (14)     NULL,
    [custom_imprv_sketch]    VARBINARY (MAX)  NULL,
    [custom_imprv_desc]      VARCHAR (255)    NULL,
    [row_num]                INT              IDENTITY (1, 1) NOT NULL
);


GO

