CREATE TABLE [dbo].[property_val_rows_temp] (
    [prop_id]                       INT              NOT NULL,
    [prop_val_yr]                   NUMERIC (4)      NOT NULL,
    [sup_num]                       INT              NOT NULL,
    [cost_value]                    NUMERIC (14)     NULL,
    [cost_land]                     NUMERIC (17)     NULL,
    [cost_imprv]                    NUMERIC (15)     NULL,
    [cost_value_by_living_area]     NUMERIC (29, 15) NULL,
    [income_value]                  NUMERIC (14)     NULL,
    [income_land]                   NUMERIC (17)     NULL,
    [income_imprv]                  NUMERIC (15)     NULL,
    [income_value_by_living_area]   NUMERIC (29, 15) NULL,
    [arb_market]                    NUMERIC (14)     NULL,
    [arb_land]                      NUMERIC (17)     NULL,
    [arb_imprv]                     NUMERIC (15)     NULL,
    [arb_market_by_living_area]     NUMERIC (29, 15) NULL,
    [dist_market]                   NUMERIC (14)     NULL,
    [dist_land]                     NUMERIC (17)     NULL,
    [dist_imprv]                    NUMERIC (15)     NULL,
    [dist_market_by_livig_area]     NUMERIC (29, 15) NULL,
    [mktappr_market]                NUMERIC (14)     NULL,
    [mktappr_land]                  NUMERIC (17)     NULL,
    [mktappr_imprv]                 NUMERIC (15)     NULL,
    [mktappr_market_by_living_area] NUMERIC (29, 15) NULL,
    [imprv_hstd_val]                NUMERIC (14)     NULL,
    [imprv_non_hstd_val]            NUMERIC (14)     NULL,
    [land_hstd_val]                 NUMERIC (14)     NULL,
    [land_non_hstd_val]             NUMERIC (14)     NULL,
    [ag_use_val]                    NUMERIC (14)     NULL,
    [ag_market]                     NUMERIC (14)     NULL,
    [timber_use]                    NUMERIC (14)     NULL,
    [timber_market]                 NUMERIC (14)     NULL,
    [market]                        NUMERIC (14)     NULL,
    [prod_loss]                     NUMERIC (17)     NULL,
    [appraised_val]                 NUMERIC (14)     NULL,
    [ten_percent_cap]               NUMERIC (14)     NULL,
    [assessed_val]                  NUMERIC (14)     NULL,
    [appr_method]                   VARCHAR (5)      NULL,
    [exemptions]                    VARCHAR (100)    NULL,
    [property_group_codes]          VARCHAR (200)    NULL,
    [hood_cd]                       VARCHAR (10)     NULL,
    [subset_cd]                     VARCHAR (5)      NULL,
    [subset_desc]                   VARCHAR (58)     NULL,
    [sub_market_cd]                 VARCHAR (10)     NULL,
    [legal_desc]                    VARCHAR (255)    NULL,
    [legal_desc_2]                  VARCHAR (255)    NULL,
    [legal_acreage]                 NUMERIC (14, 4)  NULL,
    [mapsco]                        VARCHAR (20)     NULL,
    [map_id]                        VARCHAR (20)     NULL,
    [abs_subdv_cd]                  VARCHAR (10)     NULL,
    [abs_subdv_desc]                VARCHAR (73)     NULL,
    [rgn_cd]                        VARCHAR (5)      NULL,
    [region_desc]                   VARCHAR (58)     NULL,
    [property_use_cd]               VARCHAR (10)     NULL,
    [secondary_use_cd]              VARCHAR (10)     NULL,
    [sub_type]                      VARCHAR (5)      NULL,
    [eff_size_acres]                NUMERIC (14, 4)  NULL,
    [last_appraiser_id]             INT              NULL,
    [last_appraisal_dt]             DATETIME         NULL,
    [last_appraisal_yr]             NUMERIC (4)      NULL,
    [appraiser_nm]                  VARCHAR (40)     NULL,
    [appraiser_full_name]           VARCHAR (75)     NULL,
    [next_appraisal_dt]             DATETIME         NULL,
    [next_appraisal_rsn]            VARCHAR (500)    NULL,
    [has_locked_values]             BIT              NOT NULL,
    [cycle]                         INT              NULL,
    [file_as_name]                  VARCHAR (70)     NULL,
    [imprv_count]                   INT              NULL,
    [custom_property_sketch]        VARBINARY (MAX)  NULL,
    [row_num]                       INT              IDENTITY (1, 1) NOT NULL
);


GO

CREATE CLUSTERED INDEX [idx_property_val_rows_temp]
    ON [dbo].[property_val_rows_temp]([row_num] ASC);


GO

