

create procedure CompSalesCopySalesCompPrint
	@lPacsUserID int
as

set nocount on

	delete sales_comp_print with(rowlock)
	where
		pacs_user_id = @lPacsUserID

	insert sales_comp_print
	(
		pacs_user_id,
		prop_id,
		year,
		geo_id,
		owner,
		situs,
		school,
		city,
		state_cd,
		region,
		abs_subdv,
		hood,
		subset,
		map_id,
		imprv_class,
		living_area,
		year_built,
		imprv_up,
		imprv_val,
		imprv_add_val,
		land_type,
		land_sqft,
		land_front_feet,
		land_acres,
		land_lot,
		land_size,
		land_up,
		land_val,
		land_val_per_area,
		land_sale_val_per_area,
		appraised_val,
		appraised_val_per_sqft,
		sale_type,
		sale_date,
		sale_price,
		sale_price_per_sqft,
		sale_ratio,
		score,
		print_flag,
		sequence_num,
		situs_street,
		improv_desc_two,
		improv_desc_three,
		item_desc,
/*
		report_id,
		valuation_method,
		comm_lb_ratio,
		comm_eff_year,
		comm_current_mkt_val,
		comm_current_market_per_sqft,
		comm_lease_up_cost,
		comm_excess_land,
		comm_stablized_noi_per_sqft,
		comm_cap_rate,
		comm_stablized_market,
		comm_stablized_market_per_sqft,
		comm_NRA,
		comm_land_sqft,
		comm_land_value_sqft,
		comm_land_value,
		comm_NOIRSF,
		comm_personal_property,
		comm_income_value,
		comm_GBA,
		comm_GPIRSF,
		comm_EGIRSF,
		comm_VR,    
		comm_EXPRSF 
*/
		report_id,
		imprv_sub_class,
		imprv_type_cd
	)
	select
		@lPacsUserID,
		prop_id,
		year,
		geo_id,
		owner,
		situs,
		school,
		city,
		state_cd,
		region,
		abs_subdv,
		hood,
		subset,
		map_id,
		imprv_class,
		living_area,
		year_built,
		imprv_up,
		imprv_val,
		imprv_add_val,
		land_type,
		land_sqft,
		land_front_feet,
		land_acres,
		land_lot,
		land_size,
		land_up,
		land_val,
		land_val_per_area,
		land_sale_val_per_area,
		appraised_val,
		appraised_val_per_sqft,
		sale_type,
		sale_date,
		sale_price,
		sale_price_per_sqft,
		sale_ratio,
		score,
		print_flag,
		sequence_num,
		situs_street,
		improv_desc_two,
		improv_desc_three,
		item_desc,
/*
		report_id,
		valuation_method,
		comm_lb_ratio,
		comm_eff_year,
		comm_current_mkt_val,
		comm_current_market_per_sqft,
		comm_lease_up_cost,
		comm_excess_land,
		comm_stablized_noi_per_sqft,
		comm_cap_rate,
		comm_stablized_market,
		comm_stablized_market_per_sqft,
		comm_NRA,
		comm_land_sqft,
		comm_land_value_sqft,
		comm_land_value,
		comm_NOIRSF,
		comm_personal_property,
		comm_income_value,
		comm_GBA,
		comm_GPIRSF,
		comm_EGIRSF,
		comm_VR,    
		comm_EXPRSF 
*/
		report_id,
		imprv_sub_class,
		imprv_type_cd
	from #sales_comp_print with(nolock)

set nocount off

GO

