CREATE TABLE [dbo].[comp_sales_config] (
    [main_area_adj_pct_factor]               REAL           NOT NULL,
    [time_adj_pct_factor]                    REAL           NOT NULL,
    [fPctBuildingArea]                       REAL           NOT NULL,
    [fPctLandArea]                           REAL           NOT NULL,
    [fPctBusinessValue]                      REAL           NOT NULL,
    [lNumCompsResidential]                   INT            NOT NULL,
    [lNumCompsCorp]                          INT            NOT NULL,
    [szGridNameARBInquiry]                   VARCHAR (64)   NOT NULL,
    [szGridNameARBProtest]                   VARCHAR (64)   NOT NULL,
    [lYear]                                  NUMERIC (4)    NOT NULL,
    [lnum_res_list]                          INT            NOT NULL,
    [lnum_com_list]                          INT            NOT NULL,
    [flbratio_low]                           REAL           NOT NULL,
    [flbratio_high]                          REAL           NOT NULL,
    [lnum_land_sales_list]                   INT            NOT NULL,
    [lnum_res_equity_list]                   INT            NOT NULL,
    [lnum_com_equity_list]                   INT            NOT NULL,
    [lNumCompsResidentialEquity]             INT            NOT NULL,
    [lNumCompsCorpEquity]                    INT            NOT NULL,
    [fMktLeveler]                            REAL           NULL,
    [bUseEffYearBltAdj]                      BIT            NULL,
    [bUsePctGoodAdj]                         BIT            NULL,
    [bMoveMAAdjOutOfSegments]                BIT            NULL,
    [bAdjSegmentsWithStraitCalc]             BIT            NULL,
    [bAdjSegmentsWithMktLevelerCalc]         BIT            NULL,
    [bAdjustClassWithUnitPrice]              BIT            NULL,
    [bStaticDefaultResidentialSales]         BIT            NULL,
    [bStaticDefaultResidentialEquity]        BIT            NULL,
    [bStaticDefaultCorpSales]                BIT            NULL,
    [bStaticDefaultCorpEquity]               BIT            NULL,
    [bSearchIncludeChild]                    BIT            NULL,
    [bSearchIncludeParent]                   BIT            NULL,
    [bSearchIncludeDeleted]                  BIT            NULL,
    [bAdjustHighValueImprov]                 BIT            NULL,
    [bExcludeIncompleteProps]                BIT            NULL,
    [bUseImprovTypeInclusion]                BIT            NULL,
    [bForceScoreBase100]                     BIT            NULL,
    [bClassAdjRCNEqualize]                   BIT            NULL,
    [bUseHighValueImprovClass]               BIT            NULL,
    [bUseHighValueImprovSubClass]            BIT            NULL,
    [bUseHighValueImprovArea]                BIT            NULL,
    [bAdj_URAR_MA]                           BIT            NULL,
    [bMultiImpAdjUsesDetailRCNLDSum]         BIT            NULL,
    [bMultiImpAdjTimesSysMAAdjFactor]        BIT            NULL,
    [lBaseYearMonthsSinceSale]               NUMERIC (4)    NULL,
    [bUseResidentialMarketModifier]          BIT            NOT NULL,
    [bUseResidentialMarketModifierWeighting] BIT            NOT NULL,
    [bUseResidentialScoringWeighting]        BIT            NOT NULL,
    [bUseLandMarketModifier]                 BIT            NOT NULL,
    [bUseLandMarketModifierWeighting]        BIT            NOT NULL,
    [bUseLandScoringWeighting]               BIT            NOT NULL,
    [bFeaturesValue]                         BIT            NULL,
    [time_adj_pct_residential]               NUMERIC (7, 4) NULL,
    [time_adj_pct_commercial]                NUMERIC (7, 4) NULL,
    [time_adj_pct_land]                      NUMERIC (7, 4) NULL,
    [bSimpleMAAdj]                           BIT            NOT NULL,
    [market_approach_value_option]           VARCHAR (4)    NOT NULL,
    [market_approach_calc_option]            VARCHAR (24)   NOT NULL,
    CONSTRAINT [CPK_comp_sales_config] PRIMARY KEY CLUSTERED ([lYear] ASC) WITH (FILLFACTOR = 100)
);


GO

