#!/usr/bin/env node
/**
 * tf-slice.mjs - TerraFusion Slice Automation
 *
 * Creates atomized slice branches from the main codebase.
 * Each slice isolates a specific concern for reviewable PRs.
 *
 * Usage:
 *   pnpm tf:slice <n>           # Create slice N branch with marker
 *   pnpm tf:slice <n> --ship    # Create and ship slice N
 *   pnpm tf:slice list          # List all slice definitions
 *
 * Solo-Dev Mode: The TerraFusion Way.
 */

import { execSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

// ═══════════════════════════════════════════════════════════════════════════════
// SLICE DEFINITIONS - Add new slices here
// ═══════════════════════════════════════════════════════════════════════════════
const SLICES = {
  1: {
    name: 'ci-gates',
    branch: 'phase4b/slice-1-ci-gates',
    scope: 'ci(gates)',
    description: 'CI workflow + spec gates infrastructure',
    paths: [
      '.github/workflows/**',
      'tools/spec-gates/**',
      'scripts/spec-gates/**',
      'tools/registry/**',
    ],
    markerPath: '.github/SLICE_1_CI_GATES.md',
  },
  2: {
    name: 'policy-contracts',
    branch: 'phase4b/slice-2-policy-contracts',
    scope: 'policy(contracts)',
    description: 'Telemetry + health policy schemas',
    paths: ['policy/contracts/**'],
    markerPath: 'policy/contracts/SLICE_2_POLICY_CONTRACTS.md',
  },
  3: {
    name: 'backend-telemetry',
    branch: 'phase4b/slice-3-backend-telemetry',
    scope: 'feat(api)',
    description: 'Agent telemetry + system health API endpoints',
    paths: [
      'backend/src/TerraFusion.API/Controllers/Telemetry*',
      'backend/src/TerraFusion.API/Controllers/System*',
      'backend/src/TerraFusion.API/Models/Telemetry/**',
      'backend/tests/**/Telemetry*',
    ],
    markerPath: 'backend/src/TerraFusion.API/SLICE_3_BACKEND_TELEMETRY.md',
  },
  4: {
    name: 'os-shell-sentinel',
    branch: 'phase4b/slice-4-os-shell-sentinel',
    scope: 'feat(sentinel)',
    description: 'OS Shell sentinel store + IPC layer',
    paths: [
      'frontend/apps/os-shell/src/sentinel/**',
      'frontend/apps/os-shell/src/ipc/**',
      'frontend/apps/os-shell/src/lib/api*',
    ],
    markerPath: 'frontend/apps/os-shell/src/sentinel/SLICE_4_SENTINEL.md',
  },
  5: {
    name: 'ui-ambient',
    branch: 'phase4b/slice-5-ui-ambient',
    scope: 'feat(ui)',
    description: 'Ambient UI compositor + toast notifications',
    paths: [
      'frontend/apps/os-shell/src/components/ambient/**',
      'frontend/apps/os-shell/src/components/ui/toast*',
    ],
    markerPath: 'frontend/apps/os-shell/src/components/ambient/SLICE_5_AMBIENT.md',
  },
  6: {
    name: 'app-manifests',
    branch: 'phase4b/slice-6-app-manifests',
    scope: 'feat(apps)',
    description: 'Application module manifests',
    paths: ['applications/*/terrafusion.app.json', 'applications/*/manifest.json'],
    markerPath: 'applications/SLICE_6_APP_MANIFESTS.md',
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════
function run(cmd, opts = {}) {
  const { silent = false, ignoreError = false } = opts;
  if (!silent) console.log(`> ${cmd}`);
  try {
    return execSync(cmd, { encoding: 'utf8', stdio: silent ? 'pipe' : 'inherit' });
  } catch (e) {
    if (!ignoreError) throw e;
    return '';
  }
}

function getCurrentBranch() {
  return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf8' }).trim();
}

function branchExists(branch) {
  try {
    execSync(`git rev-parse --verify ${branch}`, { encoding: 'utf8', stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

function createSliceMarker(slice) {
  const markerDir = path.dirname(slice.markerPath);
  if (!fs.existsSync(markerDir)) {
    fs.mkdirSync(markerDir, { recursive: true });
  }

  const content = `# Slice ${Object.keys(SLICES).find((k) => SLICES[k] === slice)}: ${slice.name}

## Scope

${slice.description}

## Files Included

\`\`\`
${slice.paths.join('\n')}
\`\`\`

## Branch

\`${slice.branch}\`

---

*Auto-generated by tf:slice - Phase 4B Atomization*
`;

  fs.writeFileSync(slice.markerPath, content);
  console.log(`✅ Created marker: ${slice.markerPath}`);
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMMANDS
// ═══════════════════════════════════════════════════════════════════════════════
function listSlices() {
  console.log('\n📋 TerraFusion Slice Definitions\n');
  console.log('┌─────┬────────────────────────┬─────────────────────────────────────────────┐');
  console.log('│ #   │ Name                   │ Description                                 │');
  console.log('├─────┼────────────────────────┼─────────────────────────────────────────────┤');
  for (const [n, s] of Object.entries(SLICES)) {
    const name = s.name.padEnd(22);
    const desc = s.description.slice(0, 43).padEnd(43);
    console.log(`│ ${n}   │ ${name} │ ${desc} │`);
  }
  console.log('└─────┴────────────────────────┴─────────────────────────────────────────────┘\n');
  console.log('Usage: pnpm tf:slice <n> [--ship]');
}

function createSlice(n, ship = false) {
  const slice = SLICES[n];
  if (!slice) {
    console.error(`❌ Unknown slice: ${n}`);
    console.log('Use: pnpm tf:slice list');
    process.exit(1);
  }

  console.log(`\n🔪 Creating Slice ${n}: ${slice.name}`);
  console.log(`   Branch: ${slice.branch}`);
  console.log(`   Scope: ${slice.scope}`);
  console.log('');

  // Ensure on main
  const current = getCurrentBranch();
  if (current !== 'main') {
    console.log('📌 Switching to main...');
    run('git switch main');
    run('git pull origin main --ff-only', { ignoreError: true });
  }

  // Check if branch exists
  if (branchExists(slice.branch)) {
    console.log(`⚠️  Branch ${slice.branch} already exists.`);
    console.log('   Checking out existing branch...');
    run(`git switch ${slice.branch}`);
  } else {
    console.log(`🌿 Creating branch: ${slice.branch}`);
    run(`git switch -c ${slice.branch}`);

    // Create marker file
    createSliceMarker(slice);

    // Commit
    const commitMsg = `${slice.scope}: slice ${n} review anchor - ${slice.description}`;
    run(`git add ${slice.markerPath}`);
    run(`git commit -m "${commitMsg}"`);
  }

  if (ship) {
    console.log('\n🚀 Shipping slice...');
    run('pnpm tf:ship --fast');
  } else {
    console.log(`\n✅ Slice ${n} ready.`);
    console.log('   To ship: pnpm tf:ship --fast');
    console.log('   Or: pnpm tf:slice ' + n + ' --ship');
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════════
const args = process.argv.slice(2);

if (args.length === 0 || args[0] === 'list' || args[0] === '-h' || args[0] === '--help') {
  listSlices();
  process.exit(0);
}

const sliceNum = parseInt(args[0], 10);
const ship = args.includes('--ship');

if (isNaN(sliceNum)) {
  console.error(`❌ Invalid slice number: ${args[0]}`);
  listSlices();
  process.exit(1);
}

createSlice(sliceNum, ship);
