# COPYRIGHT 2013-2024 ESRI
#
# TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
# Unpublished material - all rights reserved under the
# Copyright Laws of the United States.
#
# For additional information, contact:
# Environmental Systems Research Institute, Inc.
# Attn: Contracts Dept
# 380 New York Street
# Redlands, California, USA 92373
#
# email: contracts@esri.com
r"""The Indoor Positioning toolbox contains tools to create an ArcGIS IPS
Information Model, which enables indoor surveys with the ArcGIS IPS
Setup app, processing of survey data, and indoor positioning. The
toolbox also includes the Quality Assessment toolset that contains
tools to evaluate the performance of an ArcGIS IPS deployment."""
from __future__ import annotations

__all__ = [
    "ComputePositioningQuality",
    "CreateIPSDataModel",
    "CreateIPSQualityDataset",
    "EnableIndoorPositioning",
    "GenerateIndoorPositioningDataset",
    "GenerateIndoorPositioningFile",
    "GenerateIndoorPositioningFileWithoutSurvey",
    "ShareIndoorPositioningDataService",
]
__alias__ = "indoorpositioning"
from arcpy.geoprocessing._base import gptooldoc, gp, gp_fixargs
from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Literal
    from arcpy import RecordSet, FeatureSet
    from arcpy._mp import Layer, Table
    from arcpy.typing.gp import Result, Result1, Result2, Result3


# Tools
@gptooldoc("CreateIPSDataModel_indoorpositioning", None)
def CreateIPSDataModel(
    target_workspace=None,
    coordinate_system=None,
    setup_indoors_model_for_ips: Literal["SETUP_INDOORS_MODEL", "NO_SETUP_INDOORS_MODEL"] | None = None,
) -> Result1[str]:
    """CreateIPSDataModel_indoorpositioning(target_workspace, coordinate_system, {setup_indoors_model_for_ips})

       Creates an IPS Data Model containing the following components:

    INPUTS:
     target_workspace (Workspace):
         The file or enterprise geodatabase where the IPS Data Model will be
         created.
     coordinate_system (Coordinate System):
         The spatial reference that will be used for the output IPS Data Model.
         The default is WGS84.
     setup_indoors_model_for_ips {Boolean}:
         Specifies whether an Indoors Information Model containing the feature
         classes-Sites, Facilities, Levels, Units, Details, Pathways. and Floor
         Transitions-will be created and configured.SETUP_INDOORS_MODEL-An
         Indoors Information Model and feature classes
         will be created and configured.NO_SETUP_INDOORS_MODEL-An Indoors
         Information Model and feature
         classes will not be created and configured. This is the default."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.CreateIPSDataModel_indoorpositioning(
                *gp_fixargs((target_workspace, coordinate_system, setup_indoors_model_for_ips), True)
            )
        )
        return retval
    except Exception as e:
        raise e


@gptooldoc("GenerateIndoorPositioningDataset_indoorpositioning", None)
def GenerateIndoorPositioningDataset(
    target_ips_positioning_datasets=None,
    dataset_name=None,
    generation_method: Literal["SURVEY_BASED", "SURVEY_LESS"] | None = None,
    in_levels=None,
    in_ips_recordings=None,
    in_beacons=None,
    in_ips_areas=None,
    in_walls=None,
    update_existing: Literal["UPDATE_EXISTING", "NO_UPDATE_EXISTING"] | None = None,
    existing_dataset=None,
) -> Result1[str | Table]:
    """GenerateIndoorPositioningDataset_indoorpositioning(target_ips_positioning_datasets, dataset_name, generation_method, in_levels, {in_ips_recordings}, {in_beacons}, {in_ips_areas}, {in_walls}, {update_existing}, {existing_dataset})

       Generates an Indoor Positioning Dataset for an existing ArcGIS IPS
       installation. You can use a survey-based or survey-less method to
       generate the dataset.

    INPUTS:
     target_ips_positioning_datasets (Feature Layer):
         The feature class where the generated Indoor Positioning Dataset will
         be stored.
     dataset_name (String):
         The name of the output Indoor Positioning Dataset. The output
         dataset name must be unique in thefield of the
         Target IPS Positioning feature class. Dataset Name
     generation_method (String):
         Specifies the method that will be used to generate the Indoor
         Positioning Dataset.SURVEY_BASED-The dataset will be generated by
         processing IPS
         Recordings.SURVEY_LESS-The dataset will be generated by simulating the
         Bluetooth
         signal propagation through the indoor environment.
     in_levels (Feature Layer):
         The polygon features representing Level footprints within the
         facilities.
     in_ips_recordings {Feature Layer}:
         The feature class or feature service that contains IPS Setup survey
         recordings.This parameter is required when the generation_method
         parameter is set
         to SURVEY_BASED.
     in_beacons {Feature Layer}:
         The point features representing the position and settings of Bluetooth
         beacons deployed in the indoor environment.This parameter is required
         when the generation_method parameter is set
         to SURVEY_LESS.
     in_ips_areas {Feature Layer}:
         The polygon features representing the area where the Indoor
         Positioning Dataset will be generated.This parameter is required when
         the generation_method parameter is set
         to SURVEY_LESS.
     in_walls {Feature Layer}:
         The polygon features representing the physical extent of walls.This
         parameter is required when the generation_method parameter is set
         to SURVEY_LESS.
     update_existing {Boolean}:
         Specifies whether an Indoor Positioning Dataset will be created by
         combining an existing dataset and the tool inputs. This parameter is
         only valid if the generation_method parameter is set to
         SURVEY_BASED.UPDATE_EXISTING-An Indoor Positioning Dataset will be
         created using
         the existing dataset and the tool inputs.NO_UPDATE_EXISTING-A new
         Indoor Positioning Dataset will be created.
         This is the default.
     existing_dataset {String}:
         The name of an existing dataset contained in the Target IPS
         Positioning Datasets. The parameter value must be the name of an
         existing Indoor Positioning Dataset contained in the Target IPS
         Positioning Datasets. The data contained in this dataset will be used
         in conjunction with the tool inputs to generate an updated version of
         the existing dataset. This parameter is only used in combination with
         the update_existing parameter."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.GenerateIndoorPositioningDataset_indoorpositioning(
                *gp_fixargs(
                    (
                        target_ips_positioning_datasets,
                        dataset_name,
                        generation_method,
                        in_levels,
                        in_ips_recordings,
                        in_beacons,
                        in_ips_areas,
                        in_walls,
                        update_existing,
                        existing_dataset,
                    ),
                    True,
                )
            )
        )
        return retval
    except Exception as e:
        raise e


@gptooldoc("ShareIndoorPositioningDataService_indoorpositioning", None)
def ShareIndoorPositioningDataService(
    in_ips_datasets=None,
    ips_dataset_name=None,
    title=None,
    summary=None,
    tags=None,
    folder: Literal[
        "cursor_perf32",
        "for_pynit_TestFeatureServiceSanity",
        "Survey-Connect with the arcpy team!",
        "Survey-Upgrade python environment user survey",
    ]
    | None = None,
    sharing_level: Literal["OWNER", "ORGANIZATION", "EVERYONE"] | None = None,
    group_sharing: list[Literal["BBPT", "Analysis Team", "Charts Team"]]
    | Literal["BBPT", "Analysis Team", "Charts Team"]
    | str
    | None = None,
    update_existing: Literal["UPDATE_EXISTING", "NO_UPDATE_EXISTING"] | None = None,
) -> Result2[str, str]:
    """ShareIndoorPositioningDataService_indoorpositioning(in_ips_datasets, ips_dataset_name, title, {summary}, {tags}, {folder}, {sharing_level}, {group_sharing;group_sharing...}, {update_existing})

       Publishes an Indoor Positioning Data Service to ArcGIS Enterprise or
       ArcGIS Online. An Indoor Positioning Data Service contains the data
       required for enabling indoor positioning. It is used by the
       IndoorsLocationDataSource objects of the ArcGIS Maps SDKs to compute
       an estimated position.

    INPUTS:
     in_ips_datasets (Feature Layer):
         The feature class from the ArcGIS IPS Data Model containing one
         feature per Indoor Positioning Dataset.
     ips_dataset_name (String):
         The name of the Indoor Positioning Dataset. Options will be a list of
         dataset names derived from the in_ips_datasets parameter value.
     title (String):
         The title of the Indoor Positioning Data Service.
     summary {String}:
         A short description for the Indoor Positioning Data Service.
     tags {String}:
         The keywords or terms that describe the Indoor Positioning Data
         Service. Separate multiple tags with a comma.
     folder {String}:
         The name of an existing folder on the portal where the Indoor
         Positioning Data Service will be stored.
     sharing_level {String}:
         Specifies the sharing permissions that will be used for the
         service.OWNER-Only the owner of the Indoor Positioning Data Service
         will have
         access. This is the default.ORGANIZATION-All members of the
         organization will have access.EVERYONE-Everyone, including people
         outside the organization, will
         have access.
     group_sharing {String}:
         The groups with which the Indoor Positioning Data Service will be
         shared. You can select multiple values from the groups to which you
         belong.
     update_existing {Boolean}:
         Specifies whether an existing Indoor Positioning Data Service will be
         overwritten.UPDATE_EXISTING-An existing Indoor Positioning Data
         Service will be
         overwritten.NO_UPDATE_EXISTING-An existing Indoor Positioning Data
         Service will
         not be overwritten, and a new service will be shared. This is the
         default."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.ShareIndoorPositioningDataService_indoorpositioning(
                *gp_fixargs(
                    (
                        in_ips_datasets,
                        ips_dataset_name,
                        title,
                        summary,
                        tags,
                        folder,
                        sharing_level,
                        group_sharing,
                        update_existing,
                    ),
                    True,
                )
            )
        )
        return retval
    except Exception as e:
        raise e


# Classic toolset
@gptooldoc("EnableIndoorPositioning_indoorpositioning", None)
def EnableIndoorPositioning(
    in_workspace=None,
) -> Result:
    """EnableIndoorPositioning_indoorpositioning(in_workspace)

       Creates the feature classes and table necessary for storing ArcGIS IPS
       data in an existing geodatabase.

    INPUTS:
     in_workspace (Workspace):
         The geodatabase where the ArcGIS IPS table and feature classes will be
         created. It can be a file or enterprise geodatabase."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.EnableIndoorPositioning_indoorpositioning(*gp_fixargs((in_workspace,), True))
        )
        return retval
    except Exception as e:
        raise e


@gptooldoc("GenerateIndoorPositioningFile_indoorpositioning", None)
def GenerateIndoorPositioningFile(
    in_ips_recordings=None,
    target_ips_positioning=None,
    in_ips_transitions=None,
    in_ips_comment=None,
) -> Result1[str]:
    """GenerateIndoorPositioningFile_indoorpositioning(in_ips_recordings, target_ips_positioning, {in_ips_transitions}, {in_ips_comment})

       Generates a positioning file from ArcGIS IPS Setup survey recordings.

    INPUTS:
     in_ips_recordings (Feature Layer):
         The feature class or feature service that contains IPS Setup survey
         recordings.
     target_ips_positioning (Table View):
         The table or feature service where the generated IPS positioning file
         will be stored.
     in_ips_transitions {Feature Layer}:
         The line feature class that contains the,, andfields that
         define facility entrances and exits. These are used by ArcGIS IPS to
         improve indoor and outdoor localization and switching. Thefield for
         entrances and exits must contain a value of 7 to be used by this tool.
         TRANSITION_TYPEVERTICAL_ORDER_FROMVERTICAL_ORDER_TOTRANSITION_TYPE
     in_ips_comment {String}:
         The text that will be used to populate thefield of the
         positioning file entry in the target_ips_positioning value.
         Comment"""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.GenerateIndoorPositioningFile_indoorpositioning(
                *gp_fixargs((in_ips_recordings, target_ips_positioning, in_ips_transitions, in_ips_comment), True)
            )
        )
        return retval
    except Exception as e:
        raise e


@gptooldoc("GenerateIndoorPositioningFileWithoutSurvey_indoorpositioning", None)
def GenerateIndoorPositioningFileWithoutSurvey(
    target_positioning_table=None,
    in_beacon_features=None,
    in_ips_area_features=None,
    in_wall_features=None,
    in_facility_features=None,
    in_level_features=None,
    in_ips_transition_features=None,
    in_comment=None,
) -> Result1[str]:
    """GenerateIndoorPositioningFileWithoutSurvey_indoorpositioning(target_positioning_table, in_beacon_features, in_ips_area_features, in_wall_features, in_facility_features, in_level_features, {in_ips_transition_features}, {in_comment})

       Generates a positioning file from beacon and floor plan data by
       simulating Bluetooth signal propagation through the indoor
       environment.

    INPUTS:
     target_positioning_table (Table View):
         The table where the generated positioning file will be stored as an
         attachment.
     in_beacon_features (Feature Layer):
         The point features representing the position and settings of Bluetooth
         beacons deployed in the indoor environment.
     in_ips_area_features (Feature Layer):
         The polygon features representing the area where the positioning data
         will be generated.
     in_wall_features (Feature Layer):
         The polygon features representing the physical extent of walls in and
         around the indoor positioning area.
     in_facility_features (Feature Layer):
         The polygon features representing Facilities footprints.
     in_level_features (Feature Layer):
         The polygon features representing Level footprints within the
         facilities.
     in_ips_transition_features {Feature Layer}:
         The line features representing entrance or exit transitions.
     in_comment {String}:
         A text comment that will be associated with the output positioning
         file."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.GenerateIndoorPositioningFileWithoutSurvey_indoorpositioning(
                *gp_fixargs(
                    (
                        target_positioning_table,
                        in_beacon_features,
                        in_ips_area_features,
                        in_wall_features,
                        in_facility_features,
                        in_level_features,
                        in_ips_transition_features,
                        in_comment,
                    ),
                    True,
                )
            )
        )
        return retval
    except Exception as e:
        raise e


# Quality Assessment toolset
@gptooldoc("ComputePositioningQuality_indoorpositioning", None)
def ComputePositioningQuality(
    target_ips_quality_dataset=None,
    in_ips_recordings_features=None,
    in_sight_blocking_details_features=None,
) -> Result3[str, str, str]:
    """ComputePositioningQuality_indoorpositioning(target_ips_quality_dataset, in_ips_recordings_features, {in_sight_blocking_details_features})

       Populates an IPS Quality dataset generated by the Create IPS Quality
       Dataset tool.

    INPUTS:
     target_ips_quality_dataset (Dataset):
         The IPS Quality dataset generated by the Create IPS Quality Dataset
         tool that will be populated.
     in_ips_recordings_features (Feature Layer):
         The IPS Recordings feature layer that contains recordings collected
         using the ArcGIS IPS Setup app.
     in_sight_blocking_details_features {Feature Layer}:
         Details features from an Indoors dataset representing obstacles for
         line-of-sight calculation. It is recommended that you only use
         meaningful features, such as features that represent walls."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.ComputePositioningQuality_indoorpositioning(
                *gp_fixargs(
                    (target_ips_quality_dataset, in_ips_recordings_features, in_sight_blocking_details_features), True
                )
            )
        )
        return retval
    except Exception as e:
        raise e


@gptooldoc("CreateIPSQualityDataset_indoorpositioning", None)
def CreateIPSQualityDataset(
    target_workspace=None,
    coordinate_system=None,
    out_dataset_name=None,
) -> Result3[str, str, str]:
    """CreateIPSQualityDataset_indoorpositioning(target_workspace, coordinate_system, out_dataset_name)

       Creates a dataset that can be used to assess the quality of an ArcGIS
       IPS deployment.

    INPUTS:
     target_workspace (Workspace):
         The geodatabase where the IPS Quality dataset will be created. The
         value can be a file or an enterprise geodatabase.
     coordinate_system (Coordinate System):
         The spatial reference that will be used for the output IPS Quality
         dataset. The default is WGS84. You can specify the spatial reference
         in several ways, including the following:Reference a feature class or
         feature dataset with the spatial
         reference you want to apply, such as
         C:/workspace/myproject.gdb/IPS_Recordings.Use a SpatialReference
         object.Use the well-known text (WKT) string of a spatial reference.
         One way
         to determine the WKT of a spatial reference is to export a
         SpatialReference object to a string using the exportToString method.
     out_dataset_name (String):
         The name of the dataset that will be created. The default is
         IPS_Quality."""
    from arcpy.geoprocessing._base import gp, gp_fixargs
    from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject

    try:
        retval = convertArcObjectToPythonObject(
            gp.CreateIPSQualityDataset_indoorpositioning(
                *gp_fixargs((target_workspace, coordinate_system, out_dataset_name), True)
            )
        )
        return retval
    except Exception as e:
        raise e


# End of generated toolbox code
del gptooldoc, gp, gp_fixargs, convertArcObjectToPythonObject, annotations, TYPE_CHECKING
