CREATE TABLE [dbo].[_michelleo_pv_20240503] (
    [prop_id]                                INT              NOT NULL,
    [prop_val_yr]                            NUMERIC (4)      NOT NULL,
    [prop_val]                               NUMERIC (14)     NULL,
    [chg_dt]                                 DATETIME         NULL,
    [notice_mail_dt]                         DATETIME         NULL,
    [land_hstd_val]                          NUMERIC (14)     NULL,
    [land_non_hstd_val]                      NUMERIC (14)     NULL,
    [imprv_hstd_val]                         NUMERIC (14)     NULL,
    [imprv_non_hstd_val]                     NUMERIC (14)     NULL,
    [appraised_val]                          NUMERIC (14)     NULL,
    [assessed_val]                           NUMERIC (14)     NULL,
    [market]                                 NUMERIC (14)     NULL,
    [ag_use_val]                             NUMERIC (14)     NULL,
    [ag_market]                              NUMERIC (14)     NULL,
    [freeze_ceiling]                         NUMERIC (14, 2)  NULL,
    [freeze_yr]                              NUMERIC (4)      NULL,
    [ag_loss]                                NUMERIC (14)     NULL,
    [ag_late_loss]                           NUMERIC (14)     NULL,
    [timber_78]                              NUMERIC (14)     NULL,
    [timber_market]                          NUMERIC (14)     NULL,
    [timber_use]                             NUMERIC (14)     NULL,
    [timber_loss]                            NUMERIC (14)     NULL,
    [timber_late_loss]                       NUMERIC (14)     NULL,
    [rendered_val]                           NUMERIC (14)     NULL,
    [rendered_yr]                            NUMERIC (4)      NULL,
    [new_val]                                NUMERIC (14)     NULL,
    [new_yr]                                 NUMERIC (4)      NULL,
    [mineral_int_pct]                        NUMERIC (13, 10) NULL,
    [orig_appraised_val]                     NUMERIC (14)     NULL,
    [ten_percent_cap]                        NUMERIC (14)     NULL,
    [sup_num]                                INT              NOT NULL,
    [legal_desc]                             VARCHAR (255)    NULL,
    [legal_desc_2]                           VARCHAR (255)    NULL,
    [abated_pct]                             NUMERIC (8)      NULL,
    [abated_amt]                             NUMERIC (14)     NULL,
    [abated_yr]                              NUMERIC (5)      NULL,
    [eff_size_acres]                         NUMERIC (14, 4)  NULL,
    [shared_prop_val]                        NUMERIC (14)     NULL,
    [shared_prop_cad_code]                   VARCHAR (5)      NULL,
    [legal_acreage]                          NUMERIC (14, 4)  NULL,
    [vit_flag]                               CHAR (1)         NULL,
    [recalc_flag]                            CHAR (1)         NULL,
    [vit_declaration_filed_dt]               DATETIME         NULL,
    [prev_sup_num]                           INT              NULL,
    [sup_cd]                                 CHAR (10)        NULL,
    [sup_desc]                               VARCHAR (500)    NULL,
    [sup_dt]                                 DATETIME         NULL,
    [sup_action]                             CHAR (1)         NULL,
    [appr_company_id]                        INT              NULL,
    [prop_inactive_dt]                       DATETIME         NULL,
    [hscap_qualify_yr]                       NUMERIC (4)      NULL,
    [hscap_override_prevhsval_flag]          CHAR (1)         NULL,
    [hscap_prevhsval]                        NUMERIC (14)     NULL,
    [hscap_prevhsval_pacsuser]               NUMERIC (14)     NULL,
    [hscap_prevhsval_comment]                VARCHAR (255)    NULL,
    [hscap_prevhsval_date]                   DATETIME         NULL,
    [hscap_override_newhsval_flag]           CHAR (1)         NULL,
    [hscap_newhsval]                         NUMERIC (14)     NULL,
    [hscap_newhsval_pacsuser]                NUMERIC (14)     NULL,
    [hscap_newhsval_comment]                 VARCHAR (255)    NULL,
    [hscap_newhsval_date]                    DATETIME         NULL,
    [last_appraisal_yr]                      NUMERIC (4)      NULL,
    [oil_wells]                              NUMERIC (14)     NULL,
    [irr_wells]                              NUMERIC (14)     NULL,
    [irr_acres]                              NUMERIC (14, 4)  NULL,
    [irr_capacity]                           NUMERIC (14)     NULL,
    [oil_well_apply_adjust]                  CHAR (1)         NULL,
    [oil_wells_apply_adjust]                 CHAR (1)         NULL,
    [tif_imprv_val]                          NUMERIC (14)     NULL,
    [tif_land_val]                           NUMERIC (14)     NULL,
    [tif_flag]                               CHAR (1)         NULL,
    [accept_create_id]                       INT              NULL,
    [accept_create_dt]                       DATETIME         NULL,
    [abs_subdv_cd]                           VARCHAR (10)     NULL,
    [hood_cd]                                VARCHAR (10)     NULL,
    [block]                                  VARCHAR (50)     NULL,
    [tract_or_lot]                           VARCHAR (50)     NULL,
    [mbl_hm_park]                            VARCHAR (50)     NULL,
    [mbl_hm_space]                           VARCHAR (50)     NULL,
    [rgn_cd]                                 VARCHAR (5)      NULL,
    [subset_cd]                              VARCHAR (5)      NULL,
    [map_id]                                 VARCHAR (20)     NULL,
    [auto_build_legal]                       VARCHAR (1)      NULL,
    [image_path]                             VARCHAR (255)    NULL,
    [hscap_prev_reappr_yr]                   NUMERIC (4)      NULL,
    [hscap_base_yr]                          NUMERIC (4)      NULL,
    [hscap_base_yr_override]                 CHAR (1)         NULL,
    [hscap_base_yr_pacsuser]                 NUMERIC (14)     NULL,
    [hscap_base_yr_comment]                  VARCHAR (255)    NULL,
    [hscap_base_yr_date]                     DATETIME         NULL,
    [mapsco]                                 VARCHAR (20)     NULL,
    [cost_value]                             NUMERIC (14)     NULL,
    [income_value]                           NUMERIC (14)     NULL,
    [shared_value]                           NUMERIC (14)     NULL,
    [appr_method]                            CHAR (5)         NULL,
    [cost_land_hstd_val]                     NUMERIC (14)     NULL,
    [cost_land_non_hstd_val]                 NUMERIC (14)     NULL,
    [cost_imprv_hstd_val]                    NUMERIC (14)     NULL,
    [cost_imprv_non_hstd_val]                NUMERIC (14)     NULL,
    [cost_market]                            NUMERIC (14)     NULL,
    [cost_ag_use_val]                        NUMERIC (14)     NULL,
    [cost_ag_market]                         NUMERIC (14)     NULL,
    [cost_ag_loss]                           NUMERIC (14)     NULL,
    [cost_timber_market]                     NUMERIC (14)     NULL,
    [cost_timber_use]                        NUMERIC (14)     NULL,
    [cost_timber_loss]                       NUMERIC (14)     NULL,
    [income_land_hstd_val]                   NUMERIC (14)     NULL,
    [income_land_non_hstd_val]               NUMERIC (14)     NULL,
    [income_imprv_hstd_val]                  NUMERIC (14)     NULL,
    [income_imprv_non_hstd_val]              NUMERIC (14)     NULL,
    [income_market]                          NUMERIC (14)     NULL,
    [income_ag_use_val]                      NUMERIC (14)     NULL,
    [income_ag_market]                       NUMERIC (14)     NULL,
    [income_ag_loss]                         NUMERIC (14)     NULL,
    [income_timber_market]                   NUMERIC (14)     NULL,
    [income_timber_use]                      NUMERIC (14)     NULL,
    [income_timber_loss]                     NUMERIC (14)     NULL,
    [shared_land_hstd_val]                   NUMERIC (14)     NULL,
    [shared_land_non_hstd_val]               NUMERIC (14)     NULL,
    [shared_imprv_hstd_val]                  NUMERIC (14)     NULL,
    [shared_imprv_non_hstd_val]              NUMERIC (14)     NULL,
    [shared_market]                          NUMERIC (14)     NULL,
    [shared_ag_use_val]                      NUMERIC (14)     NULL,
    [shared_ag_market]                       NUMERIC (14)     NULL,
    [shared_ag_loss]                         NUMERIC (14)     NULL,
    [shared_timber_market]                   NUMERIC (14)     NULL,
    [shared_timber_use]                      NUMERIC (14)     NULL,
    [shared_timber_loss]                     NUMERIC (14)     NULL,
    [last_appraiser_id]                      INT              NULL,
    [next_appraiser_id]                      INT              NULL,
    [last_appraisal_dt]                      DATETIME         NULL,
    [next_appraisal_dt]                      DATETIME         NULL,
    [next_appraisal_rsn]                     VARCHAR (500)    NULL,
    [value_appraiser_id]                     INT              NULL,
    [land_appraiser_id]                      INT              NULL,
    [sub_market_cd]                          VARCHAR (10)     NULL,
    [property_use_cd]                        VARCHAR (10)     NULL,
    [visibility_access_cd]                   VARCHAR (10)     NULL,
    [last_pacs_user_id]                      INT              NULL,
    [recalc_dt]                              DATETIME         NULL,
    [new_val_hs]                             NUMERIC (14)     NULL,
    [new_val_nhs]                            NUMERIC (14)     NULL,
    [new_val_p]                              NUMERIC (14)     NULL,
    [owner_update_dt]                        DATETIME         NULL,
    [agent_update_dt]                        DATETIME         NULL,
    [penpad_comments]                        VARCHAR (256)    NULL,
    [last_actual_appraisal_dt]               DATETIME         NULL,
    [last_owner_id]                          INT              NULL,
    [cad_value_option]                       VARCHAR (5)      NULL,
    [condo_pct]                              NUMERIC (13, 10) NULL,
    [reviewed_dt]                            SMALLDATETIME    NULL,
    [reviewed_appraiser]                     INT              NULL,
    [arb_land_hstd_val]                      NUMERIC (14)     NULL,
    [arb_land_non_hstd_val]                  NUMERIC (14)     NULL,
    [arb_imprv_hstd_val]                     NUMERIC (14)     NULL,
    [arb_imprv_non_hstd_val]                 NUMERIC (14)     NULL,
    [arb_market]                             NUMERIC (14)     NULL,
    [arb_ag_use_val]                         NUMERIC (14)     NULL,
    [arb_ag_market]                          NUMERIC (14)     NULL,
    [arb_timber_market]                      NUMERIC (14)     NULL,
    [arb_timber_use]                         NUMERIC (14)     NULL,
    [arb_timber_loss]                        NUMERIC (14)     NULL,
    [shared_other_val]                       NUMERIC (14, 2)  NULL,
    [udi_parent]                             CHAR (1)         NULL,
    [udi_parent_prop_id]                     INT              NULL,
    [udi_status]                             VARCHAR (5)      NULL,
    [udi_child_legal_desc]                   BIT              NULL,
    [image_id]                               INT              NULL,
    [dist_land_hstd_val]                     NUMERIC (14)     NULL,
    [dist_land_non_hstd_val]                 NUMERIC (14)     NULL,
    [dist_imprv_hstd_val]                    NUMERIC (14)     NULL,
    [dist_imprv_non_hstd_val]                NUMERIC (14)     NULL,
    [dist_market]                            NUMERIC (14)     NULL,
    [dist_ag_use_val]                        NUMERIC (14)     NULL,
    [dist_ag_market]                         NUMERIC (14)     NULL,
    [dist_timber_market]                     NUMERIC (14)     NULL,
    [dist_timber_use]                        NUMERIC (14)     NULL,
    [dist_timber_loss]                       NUMERIC (14)     NULL,
    [tsRowVersion]                           ROWVERSION       NOT NULL,
    [last_arb_appr_method]                   CHAR (5)         NULL,
    [udi_original_property_id]               INT              NULL,
    [pp_sq_ft]                               NUMERIC (14, 4)  NULL,
    [pp_rentable_sq_ft_rate]                 NUMERIC (14, 4)  NULL,
    [dist_vit_val]                           NUMERIC (18)     NULL,
    [secondary_use_cd]                       VARCHAR (10)     NULL,
    [assessment_use_cd]                      VARCHAR (10)     NULL,
    [state_district_cd]                      VARCHAR (25)     NULL,
    [tax_area_mileage]                       NUMERIC (9, 2)   NULL,
    [total_mileage]                          NUMERIC (9, 2)   NULL,
    [dor_value]                              NUMERIC (15, 2)  NULL,
    [apply_miscellaneous_codes]              BIT              NULL,
    [book_page]                              VARCHAR (10)     NULL,
    [sup_comment]                            VARCHAR (3000)   NULL,
    [change_of_value_form]                   BIT              NULL,
    [sub_type]                               VARCHAR (5)      NULL,
    [urban_growth_cd]                        VARCHAR (10)     NULL,
    [cycle]                                  INT              NULL,
    [cycle_override]                         BIT              NULL,
    [pp_farm]                                NUMERIC (14)     NULL,
    [pp_non_farm]                            NUMERIC (14)     NULL,
    [ag_hs_use_val]                          NUMERIC (14)     NULL,
    [ag_hs_mkt_val]                          NUMERIC (14)     NULL,
    [ag_hs_loss]                             NUMERIC (14)     NULL,
    [timber_hs_use_val]                      NUMERIC (14)     NULL,
    [timber_hs_mkt_val]                      NUMERIC (14)     NULL,
    [timber_hs_loss]                         NUMERIC (14)     NULL,
    [cost_ag_hs_use_val]                     NUMERIC (14)     NULL,
    [cost_ag_hs_mkt_val]                     NUMERIC (14)     NULL,
    [cost_ag_hs_loss]                        NUMERIC (14)     NULL,
    [cost_timber_hs_use_val]                 NUMERIC (14)     NULL,
    [cost_timber_hs_mkt_val]                 NUMERIC (14)     NULL,
    [cost_timber_hs_loss]                    NUMERIC (14)     NULL,
    [shared_ag_hs_use_val]                   NUMERIC (14)     NULL,
    [shared_ag_hs_mkt_val]                   NUMERIC (14)     NULL,
    [shared_ag_hs_loss]                      NUMERIC (14)     NULL,
    [shared_timber_hs_use_val]               NUMERIC (14)     NULL,
    [shared_timber_hs_mkt_val]               NUMERIC (14)     NULL,
    [shared_timber_hs_loss]                  NUMERIC (14)     NULL,
    [arb_ag_hs_use_val]                      NUMERIC (14)     NULL,
    [arb_ag_hs_mkt_val]                      NUMERIC (14)     NULL,
    [arb_ag_hs_loss]                         NUMERIC (14)     NULL,
    [arb_timber_hs_use_val]                  NUMERIC (14)     NULL,
    [arb_timber_hs_mkt_val]                  NUMERIC (14)     NULL,
    [arb_timber_hs_loss]                     NUMERIC (14)     NULL,
    [dist_ag_hs_use_val]                     NUMERIC (14)     NULL,
    [dist_ag_hs_mkt_val]                     NUMERIC (14)     NULL,
    [dist_ag_hs_loss]                        NUMERIC (14)     NULL,
    [dist_timber_hs_use_val]                 NUMERIC (14)     NULL,
    [dist_timber_hs_mkt_val]                 NUMERIC (14)     NULL,
    [dist_timber_hs_loss]                    NUMERIC (14)     NULL,
    [sup_verified_user]                      INT              NULL,
    [new_val_imprv_hs]                       NUMERIC (14)     NULL,
    [new_val_imprv_nhs]                      NUMERIC (14)     NULL,
    [new_val_land_hs]                        NUMERIC (14)     NULL,
    [new_val_land_nhs]                       NUMERIC (14)     NULL,
    [sup_verified_date]                      DATETIME         NULL,
    [change_form_printed]                    BIT              NULL,
    [exclude_change_of_value_form]           BIT              NULL,
    [gis_real_coord_x]                       NUMERIC (17, 9)  NULL,
    [gis_real_coord_y]                       NUMERIC (17, 9)  NULL,
    [late_filing_penalty_pct]                NUMERIC (5, 2)   NULL,
    [fraud_penalty_pct]                      NUMERIC (5, 2)   NULL,
    [prop_state]                             CHAR (1)         NULL,
    [imprv_val]                              NUMERIC (15)     NULL,
    [remodel_val_curr_yr]                    NUMERIC (14)     NULL,
    [collections_only]                       BIT              NOT NULL,
    [suppress_notice_prior_year_values]      BIT              NOT NULL,
    [retain_notice_prior_year_value_setting] BIT              NOT NULL,
    [township_code]                          VARCHAR (20)     NULL,
    [township_section]                       VARCHAR (50)     NULL,
    [township_q_section]                     VARCHAR (50)     NULL,
    [range_code]                             VARCHAR (20)     NULL,
    [non_taxed_mkt_val]                      NUMERIC (14)     NULL,
    [mktappr_market]                         NUMERIC (14)     NULL,
    [mktappr_imprv_hstd_val]                 NUMERIC (14)     NULL,
    [mktappr_imprv_non_hstd_val]             NUMERIC (14)     NULL,
    [mktappr_land_hstd_val]                  NUMERIC (14)     NULL,
    [mktappr_land_non_hstd_val]              NUMERIC (14)     NULL,
    [mktappr_ag_use_val]                     NUMERIC (14)     NULL,
    [mktappr_ag_market]                      NUMERIC (14)     NULL,
    [mktappr_ag_loss]                        NUMERIC (14)     NULL,
    [mktappr_timber_use]                     NUMERIC (14)     NULL,
    [mktappr_timber_market]                  NUMERIC (14)     NULL,
    [mktappr_timber_loss]                    NUMERIC (14)     NULL,
    [mktappr_ag_hs_use_val]                  NUMERIC (14)     NULL,
    [mktappr_ag_hs_mkt_val]                  NUMERIC (14)     NULL,
    [mktappr_ag_hs_loss]                     NUMERIC (14)     NULL,
    [mktappr_timber_hs_use_val]              NUMERIC (14)     NULL,
    [mktappr_timber_hs_mkt_val]              NUMERIC (14)     NULL,
    [mktappr_timber_hs_loss]                 NUMERIC (14)     NULL,
    [prepared_by_id]                         INT              NULL,
    [ubi_number]                             VARCHAR (50)     NULL,
    [tax_registration]                       VARCHAR (50)     NULL,
    [business_start_dt]                      DATETIME         NULL,
    [business_close_dt]                      DATETIME         NULL,
    [business_sold_dt]                       DATETIME         NULL,
    [has_locked_values]                      BIT              NOT NULL
);


GO

