CREATE TABLE [dbo].[appr_notice_prop_list] (
    [notice_yr]                       NUMERIC (4)     NOT NULL,
    [notice_num]                      INT             NOT NULL,
    [prop_id]                         INT             NOT NULL,
    [owner_id]                        INT             NOT NULL,
    [sup_num]                         INT             NOT NULL,
    [sup_yr]                          NUMERIC (4)     NOT NULL,
    [notice_owner_name]               VARCHAR (70)    NULL,
    [notice_owner_id]                 INT             NOT NULL,
    [all_real]                        CHAR (1)        NULL,
    [all_personal]                    CHAR (1)        NULL,
    [all_mineral]                     CHAR (1)        NULL,
    [all_mobile]                      CHAR (1)        NULL,
    [all_auto]                        CHAR (1)        NULL,
    [all_shared]                      CHAR (1)        NULL,
    [value_inc_19a]                   CHAR (1)        NULL,
    [value_decr_19a]                  CHAR (1)        NULL,
    [code_x19a]                       CHAR (1)        NULL,
    [code_x19ac]                      CHAR (1)        NULL,
    [rend_19a]                        CHAR (1)        NULL,
    [rend_19a_ar]                     CHAR (1)        NULL,
    [last_appr_yr_19i]                CHAR (1)        NULL,
    [last_owner_change_19i]           CHAR (1)        NULL,
    [code_x19i]                       CHAR (1)        NULL,
    [code_x19ic]                      CHAR (1)        NULL,
    [code_fn]                         CHAR (1)        NULL,
    [value_new_prop_19a]              CHAR (1)        NULL,
    [an_assessed_val]                 NUMERIC (14)    NULL,
    [an_market_val]                   NUMERIC (14)    NULL,
    [file_as_name]                    VARCHAR (70)    NULL,
    [pct_ownership]                   NUMERIC (5, 2)  NULL,
    [apply_pct_exemptions]            CHAR (1)        NULL,
    [addr_line1]                      VARCHAR (60)    NULL,
    [addr_line2]                      VARCHAR (60)    NULL,
    [addr_line3]                      VARCHAR (60)    NULL,
    [addr_city]                       VARCHAR (50)    NULL,
    [addr_state]                      VARCHAR (50)    NULL,
    [addr_zip]                        VARCHAR (50)    NULL,
    [addr_country]                    VARCHAR (5)     NULL,
    [an_imprv_hstd_val]               NUMERIC (14)    NULL,
    [an_land_hstd_val]                NUMERIC (14)    NULL,
    [an_ag_land_mkt_val]              NUMERIC (14)    NULL,
    [an_ag_land_use_val]              NUMERIC (14)    NULL,
    [an_imprv_non_hstd_val]           NUMERIC (14)    NULL,
    [an_land_non_hstd_val]            NUMERIC (14)    NULL,
    [an_appraised_val]                NUMERIC (14)    NULL,
    [an_ag_market]                    NUMERIC (14)    NULL,
    [an_timber_market]                NUMERIC (18)    NULL,
    [an_timber_use]                   NUMERIC (14)    NULL,
    [an_ten_percent_cap]              NUMERIC (14)    NULL,
    [an_prev_imprv_hstd_val]          NUMERIC (14)    NULL,
    [an_prev_land_hstd_val]           NUMERIC (14)    NULL,
    [an_prev_ag_land_mkt_val]         NUMERIC (14)    NULL,
    [an_prev_ag_land_use_val]         NUMERIC (14)    NULL,
    [an_prev_imprv_non_hstd_val]      NUMERIC (14)    NULL,
    [an_prev_land_non_hstd_val]       NUMERIC (14)    NULL,
    [an_prev_ag_market_val]           NUMERIC (14)    NULL,
    [an_prev_timber_market_val]       NUMERIC (14)    NULL,
    [an_prev_appraised_val]           NUMERIC (14)    NULL,
    [an_prev_assessed_val]            NUMERIC (14)    NULL,
    [an_prev_market_val]              NUMERIC (14)    NULL,
    [an_prev_ten_percent_cap]         NUMERIC (14)    NULL,
    [an_prev_timber_use]              NUMERIC (14)    NULL,
    [an_prev_yr]                      NUMERIC (4)     NULL,
    [prop_type_cd]                    CHAR (5)        NULL,
    [geo_id]                          VARCHAR (50)    NULL,
    [legal_desc]                      VARCHAR (255)   NULL,
    [legal_desc_2]                    VARCHAR (255)   NULL,
    [legal_acreage]                   NUMERIC (14, 4) NULL,
    [dba_name]                        VARCHAR (50)    NULL,
    [situs_display]                   VARCHAR (255)   NULL,
    [last_appraiser_id]               INT             NULL,
    [last_appraiser_nm]               VARCHAR (40)    NULL,
    [agent_copy]                      CHAR (1)        NULL,
    [delete_flag]                     CHAR (1)        NULL,
    [exp_addr_line1]                  VARCHAR (70)    NULL,
    [exp_addr_line2]                  VARCHAR (70)    NULL,
    [exp_addr_line3]                  VARCHAR (70)    NULL,
    [exp_addr_line4]                  VARCHAR (70)    NULL,
    [exp_addr_line5]                  VARCHAR (70)    NULL,
    [exp_addr_line6]                  VARCHAR (70)    NULL,
    [export_run]                      INT             NULL,
    [sys_addr_line1]                  VARCHAR (50)    NULL,
    [sys_addr_line2]                  VARCHAR (50)    NULL,
    [sys_addr_line3]                  VARCHAR (50)    NULL,
    [sys_addr_city]                   VARCHAR (50)    NULL,
    [sys_addr_state]                  CHAR (2)        NULL,
    [sys_addr_zip]                    VARCHAR (50)    NULL,
    [sys_phone_num]                   VARCHAR (20)    NULL,
    [sys_fax_num]                     VARCHAR (20)    NULL,
    [exemption]                       VARCHAR (100)   NULL,
    [sys_chief_appraiser]             VARCHAR (50)    NULL,
    [addr_deliverable]                VARCHAR (1)     NULL,
    [situs_num]                       VARCHAR (10)    NULL,
    [situs_street_prefx]              VARCHAR (10)    NULL,
    [situs_street]                    VARCHAR (50)    NULL,
    [situs_street_sufix]              VARCHAR (10)    NULL,
    [situs_city]                      VARCHAR (30)    NULL,
    [situs_state]                     CHAR (2)        NULL,
    [situs_zip]                       VARCHAR (10)    NULL,
    [zip]                             VARCHAR (5)     NULL,
    [cass]                            VARCHAR (4)     NULL,
    [route]                           VARCHAR (2)     NULL,
    [zip_4_2]                         VARCHAR (14)    NULL,
    [prev_exemption]                  VARCHAR (100)   NULL,
    [ref_id1]                         VARCHAR (50)    NULL,
    [ref_id2]                         VARCHAR (50)    NULL,
    [special_group_id]                INT             NULL,
    [timber_78]                       NUMERIC (14)    NULL,
    [an_5yr]                          NUMERIC (4)     NULL,
    [an_5yr_assessed_val]             NUMERIC (14)    NULL,
    [an_5yr_assessed_val_pct_change]  NUMERIC (16, 2) NULL,
    [an_pers_prop_mineral_value]      NUMERIC (14)    NULL,
    [an_prev_pers_prop_mineral_value] NUMERIC (14)    NULL,
    [percent_type]                    VARCHAR (5)     NULL,
    [code_list]                       CHAR (1)        NULL,
    [is_international]                BIT             NULL,
    CONSTRAINT [CPK_appr_notice_prop_list] PRIMARY KEY CLUSTERED ([notice_yr] ASC, [notice_num] ASC, [prop_id] ASC, [sup_yr] ASC, [sup_num] ASC, [owner_id] ASC, [notice_owner_id] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [CFK_appr_notice_prop_list_notice_yr_notice_num] FOREIGN KEY ([notice_yr], [notice_num]) REFERENCES [dbo].[appr_notice_selection_criteria] ([notice_yr], [notice_num])
);


GO

CREATE NONCLUSTERED INDEX [idx_prop_id]
    ON [dbo].[appr_notice_prop_list]([prop_id] ASC) WITH (FILLFACTOR = 90);


GO

