CREATE TABLE [dbo].[ptd_mt_state_report] (
    [entity_id]                             INT              NOT NULL,
    [year]                                  NUMERIC (4)      NOT NULL,
    [as_of_sup_num]                         INT              NOT NULL,
    [date]                                  DATETIME         NULL,
    [market_val]                            NUMERIC (14)     NULL,
    [exempt_val]                            NUMERIC (14)     NULL,
    [hs_state_loss_count]                   NUMERIC (14)     NULL,
    [hs_state_loss_amt]                     NUMERIC (14)     NULL,
    [fmfc_hs_state_loss_count]              NUMERIC (14)     NULL,
    [fmfc_hs_state_loss_amt]                NUMERIC (14)     NULL,
    [ov65_state_loss_count]                 NUMERIC (14)     NULL,
    [dp_state_loss_count]                   NUMERIC (14)     NULL,
    [ov65_dp_state_loss_amt]                NUMERIC (14)     NULL,
    [ov65_local_option_loss_count]          NUMERIC (14)     NULL,
    [dp_local_option_loss_count]            NUMERIC (14)     NULL,
    [ov65_dp_local_option_loss_amt]         NUMERIC (14)     NULL,
    [fmfc_dp_local_option_loss_count]       NUMERIC (14)     NULL,
    [fmfc_ov65_local_option_loss_count]     NUMERIC (14)     NULL,
    [fmfc_ov65_dp_local_option_loss_amt]    NUMERIC (14)     NULL,
    [hs_local_option_loss_pct]              NUMERIC (14)     NULL,
    [hs_local_option_loss_count]            NUMERIC (14)     NULL,
    [hs_local_option_loss_amt]              NUMERIC (14)     NULL,
    [dv_loss_count]                         NUMERIC (14)     NULL,
    [dv_loss_amt]                           NUMERIC (14)     NULL,
    [fmfc_dv_loss_count]                    NUMERIC (14)     NULL,
    [fmfc_dv_loss_amt]                      NUMERIC (14)     NULL,
    [freeport_loss_count]                   NUMERIC (14)     NULL,
    [freeport_loss_amt]                     NUMERIC (14)     NULL,
    [pollutioncontrol_loss_count]           NUMERIC (14)     NULL,
    [pollutioncontrol_loss_amt]             NUMERIC (14)     NULL,
    [waterconservation_loss_count]          NUMERIC (14)     NULL,
    [waterconservation_loss_amt]            NUMERIC (14)     NULL,
    [productivity_acres]                    NUMERIC (14, 4)  NULL,
    [productivity_value_loss]               NUMERIC (14)     NULL,
    [abatement_loss_count]                  NUMERIC (14)     NULL,
    [abatement_loss]                        NUMERIC (14)     NULL,
    [taxincrement_loss_count]               NUMERIC (14)     NULL,
    [taxincrement_loss]                     NUMERIC (14)     NULL,
    [other_loss]                            NUMERIC (14)     NULL,
    [historical_loss_count]                 NUMERIC (14)     NULL,
    [historical_loss]                       NUMERIC (14)     NULL,
    [hs_cap_loss]                           NUMERIC (14)     NULL,
    [school_freeze_loss]                    NUMERIC (14)     NULL,
    [fmfc_taxable_val]                      NUMERIC (14)     NULL,
    [taxable_val]                           NUMERIC (14)     NULL,
    [m_n_o_tax_rate]                        NUMERIC (13, 10) NULL,
    [i_n_s_tax_rate]                        NUMERIC (13, 10) NULL,
    [total_tax_rate]                        NUMERIC (13, 10) NULL,
    [fmfc_m_n_o_tax_rate]                   NUMERIC (13, 10) NULL,
    [fmfc_i_n_s_tax_rate]                   NUMERIC (13, 10) NULL,
    [fmfc_tax_rate]                         NUMERIC (13, 10) NULL,
    [general_fund_m_n_o_tax_rate]           NUMERIC (13, 10) NULL,
    [general_fund_i_n_s_tax_rate]           NUMERIC (13, 10) NULL,
    [general_fund_tax_rate]                 NUMERIC (13, 10) NULL,
    [road_bridge_m_n_o_tax_rate]            NUMERIC (13, 10) NULL,
    [road_bridge_i_n_s_tax_rate]            NUMERIC (13, 10) NULL,
    [road_bridge_tax_rate]                  NUMERIC (13, 10) NULL,
    [actual_tax_levy]                       NUMERIC (14, 2)  NULL,
    [actual_fmfc_tax_levy]                  NUMERIC (14, 2)  NULL,
    [actual_general_fund_tax_levy]          NUMERIC (14, 2)  NULL,
    [actual_road_bridge_tax_levy]           NUMERIC (14, 2)  NULL,
    [hs_cap_appraised_val]                  NUMERIC (14)     NULL,
    [hs_cap_assessed_val]                   NUMERIC (14)     NULL,
    [total_appraised_value_with_abatements] NUMERIC (14)     NULL,
    [total_taxable_value_with_abatements]   NUMERIC (14)     NULL,
    [levy_lost_to_tax_deferral_of_ov65]     NUMERIC (14)     NULL,
    [taxes_paid_into_tif]                   NUMERIC (14, 2)  NULL,
    [levy_lost_to_abatements]               NUMERIC (14, 2)  NULL,
    [abatement_appraised_before_may311993]  NUMERIC (14, 2)  NULL,
    [abatement_taxable_before_may311993]    NUMERIC (14, 2)  NULL,
    [abatement_appraised_after_may311993]   NUMERIC (14, 2)  NULL,
    [abatement_taxable_after_may311993]     NUMERIC (14, 2)  NULL,
    [payments_into_tif]                     NUMERIC (14, 2)  NULL,
    [other_loss_count]                      NUMERIC (14)     NULL,
    [certified_market_value]                NUMERIC (14)     NULL,
    [uncertified_market_value]              NUMERIC (14)     NULL,
    [industrial_exemptions]                 NUMERIC (14)     NULL,
    [dataset_id]                            BIGINT           NOT NULL,
    [eco_loss_amt]                          NUMERIC (14)     NULL,
    [eco_loss_count]                        NUMERIC (14)     NULL,
    [chodo_lowpop_loss_amt]                 NUMERIC (14)     NULL,
    [chodo_lowpop_loss_count]               NUMERIC (14)     NULL,
    [chodo_highpop_loss_amt]                NUMERIC (14)     NULL,
    [chodo_highpop_loss_count]              NUMERIC (14)     NULL,
    [hs_before_exemptions]                  NUMERIC (14)     NULL,
    CONSTRAINT [CPK_ptd_mt_state_report] PRIMARY KEY CLUSTERED ([dataset_id] ASC, [entity_id] ASC, [year] ASC, [as_of_sup_num] ASC) WITH (FILLFACTOR = 100)
);


GO

