CREATE TABLE [dbo].[transfer_mt_appraisal_entity_info] (
    [prop_id]                    INT          NOT NULL,
    [prop_val_yr]                NUMERIC (4)  NOT NULL,
    [sup_num]                    INT          NOT NULL,
    [owner_id]                   INT          NOT NULL,
    [entity_id]                  INT          NOT NULL,
    [entity_cd]                  CHAR (10)    NULL,
    [entity_name]                CHAR (50)    NULL,
    [entity_prop_id]             CHAR (50)    NULL,
    [reserverd1]                 VARCHAR (15) NULL,
    [assessed_val]               NUMERIC (14) NULL,
    [taxable_val]                NUMERIC (14) NULL,
    [ab_amt]                     NUMERIC (14) NULL,
    [en_amt]                     NUMERIC (14) NULL,
    [fr_amt]                     NUMERIC (14) NULL,
    [ht_amt]                     NUMERIC (14) NULL,
    [pro_amt]                    NUMERIC (14) NULL,
    [pc_amt]                     NUMERIC (14) NULL,
    [so_amt]                     NUMERIC (14) NULL,
    [ex366_amt]                  NUMERIC (14) NULL,
    [hs_amt]                     NUMERIC (14) NULL,
    [ov65_amt]                   NUMERIC (14) NULL,
    [dp_amt]                     NUMERIC (14) NULL,
    [dv_amt]                     NUMERIC (14) NULL,
    [ex_amt]                     NUMERIC (14) NULL,
    [ch_amt]                     NUMERIC (14) NULL,
    [market_value]               NUMERIC (14) NULL,
    [appraised_value]            NUMERIC (14) NULL,
    [hs_cap]                     NUMERIC (14) NULL,
    [ag_late_loss]               NUMERIC (14) NULL,
    [freeport_late_loss]         NUMERIC (14) NULL,
    [hs_state_amt]               NUMERIC (14) NULL,
    [hs_local_amt]               NUMERIC (14) NULL,
    [land_hstd_val]              NUMERIC (14) NULL,
    [land_non_hstd_val]          NUMERIC (14) NULL,
    [imprv_hstd_val]             NUMERIC (14) NULL,
    [imprv_non_hstd_val]         NUMERIC (14) NULL,
    [ag_use_val]                 NUMERIC (14) NULL,
    [ag_market_val]              NUMERIC (14) NULL,
    [tim_use_val]                NUMERIC (14) NULL,
    [tim_market_val]             NUMERIC (14) NULL,
    [partial_entity]             CHAR (1)     NULL,
    [freeze_yr]                  NUMERIC (4)  NULL,
    [freeze_ceiling]             NUMERIC (15) NULL,
    [freeze_transfer_flag]       CHAR (1)     NULL,
    [freeze_transfer_date]       VARCHAR (25) NULL,
    [freeze_previous_tax]        NUMERIC (15) NULL,
    [freeze_transfer_percentage] NUMERIC (9)  NULL,
    [lve_amt]                    NUMERIC (15) NULL
);


GO

