"""---------------------------------------------------------------------------
Name:              FindNearest.py
Purpose:           Finds one or more nearest features based on straight line,
                   driving time, or driving distance.
Author:            Esri Inc.
Created:           5/29/2013
Copyright:   (c)   Esri, Inc. 2013
ArcGIS Version:    10.2
---------------------------------------------------------------------------"""

#core libraries
import json
import time
import re
import sys
import locale
import os
import collections
import copy
import operator
import fnmatch

#Internal libraries
import arcpy
import hostedgp as agolgp
import aolutils
import popup
import rendererUtils
import networkanalysis
from CreateRouteLayers import create_route_layers


#Constants
INFINITY = sys.maxsize
PCS_WKID = 102100
#dict is unit and constant to covert to that unit from meter
DISTANCE_CONVERSION = {"Miles" : 0.00062,
                       "Kilometers" : 0.001,
                       "Yards": 1.09361,
                       "Feet": 3.28084,
                       "NauticalMiles": 0.00054}
DEFAULT_DISTANCE_FIELDS = ("Kilometers", "Miles")
OUT_WORKSPACE = "in_memory"
#OUT_WORKSPACE = arcpy.env.scratchGDB
TASK_NAME = "FindNearest"
RESTRICTIONS_PARAMETER_INDEX = 14
POINT_SHAPE_TYPES = ("point", "esrigeometrypoint")
TIME_BASED_MEASUREMENT_METHODS = ("DRIVINGTIME", "TRUCKINGTIME", "WALKINGTIME")
LEGACY_TRAVEL_MODE_NAMES = ("DRIVINGTIME", "DRIVINGDISTANCE", "WALKINGTIME",
                            "WALKINGDISTANCE", "TRUCKINGTIME", "TRUCKINGDISTANCE")

ROUTE_LAYER_ITEM_ID_FIELD_NAME = "RouteLayerItemID"
ROUTE_LAYER_ITEM_URL_FIELD_NAME = "RouteLayerItemURL"

ERROR_CODES = {
    100031 : "The number of nearest locations to find can not be greater than {max}.",
    100032 : "The number of features in {analysisLayer} is zero.",
    100033 : "The number of features in {nearLayer} is zero.",
    100036 : "The {analysisLayer} layer must have a point geometry type when using {measurementType} as the measurement type.",
    100037 : "The {nearLayer} layer must have a point geometry type when using {measurementType} as the measurement type.",
    100038 : "The search cutoff cannot be less than zero.",
    100040:  "The number of features in {inputLayer} can not be greater than {max}.",
    100145: "The following travel mode is invalid: {travelMode}",
    100217: "Failed to save the result as route layers since the analysis did not produce any routes.", 
    100218: "Including route layers is not valid when measurementType is StraightLine.",  
    100223: "Including route layers is not supported when requesting feature collection output.",
    #100104: "The features in {analysisLayer} are not within the data coverage area. See availability at {url}.",
    100258: "The distance between any inputs must be less than {mileValue} miles ({kmValue} kilometers) when walking.",
    100259: "No nearest locations were found from input locations. Check if the search range is appropriate for your analysis.",
    100263: "{barrierType} cannot be specified when measurementType is StraightLine.",
    100291: "Failed to publish analysis results as a feature collection because one of the output layers has more than 9,999 features. To keep all features, save your result as a feature layer."
}
#Store the mapping between error codes generated by GP tools to the error codes that are reported by the service
#SYSTEM_CODES_TO_ERROR_CODES = {
#    30137: 100100,
#    }
#global variable that is modified inside def nearest_using_network
is_measurement_method_time_based = False

def project_features(input_features, output_sr, output_features, force_copy=False):
    '''project features to the specified output sr. If the input features are already in the output_sr
    return the input_features unless force_copy is true'''
    start_time = time.time()
    existing_out_sr = arcpy.env.outputCoordinateSystem
    try:
        input_features_desc = arcpy.Describe(input_features)
        input_features_sr = input_features_desc.spatialReference
        if input_features_sr.name.lower() == output_sr.name.lower() and force_copy == False:
            arcpy.AddMessage("Skip projecting {0} as it already has {1} spatial reference".format(input_features,
                                                                                                  output_sr.name))
            output_features = input_features
        else:
            arcpy.env.outputCoordinateSystem = output_sr
            if force_copy:
                arcpy.AddMessage("Copying {0} to {1}".format(input_features, output_features))
            else:
                arcpy.AddMessage("Converting SpatialReference for {0} to {1}".format(input_features_desc.name,
                                                                                     output_sr.name)) 
            arcpy.management.CopyFeatures(input_features, output_features)
            
        
    except Exception as ex:
        raise
    finally:
        arcpy.env.outputCoordinateSystem = existing_out_sr
    if force_copy:
        aolutils.AddTimerMessage(start_time, "Copied features")
    else:    
        aolutils.AddTimerMessage(start_time, "Projected features")
    return output_features

def select_nearest_features(input_features, input_join_field, join_table, join_table_name,
                            output_join_field, output_features):
    '''Creates a new feature class containing only the features from the input feature class that are
    within the join feature class'''
    
    input_features_layer = "InputFeaturesLayer"
    arcpy.management.MakeFeatureLayer(input_features, input_features_layer,workspace=OUT_WORKSPACE)
    arcpy.management.AddJoin(input_features_layer, input_join_field, join_table, output_join_field)
    where_clause = "{0}.{1} IS NOT NULL".format(join_table_name, output_join_field)
    arcpy.management.SelectLayerByAttribute(input_features_layer, "NEW_SELECTION", where_clause)
    arcpy.management.RemoveJoin(input_features_layer, join_table_name)
    arcpy.management.CopyFeatures(input_features_layer, output_features)
    arcpy.management.SelectLayerByAttribute(input_features_layer, "CLEAR_SELECTION")
    return output_features

def create_copy_with_oidfield(input_features, input_features_name, input_features_desc, id_field_name):
    '''Creates the copy of input features that contain all the fields from input features including the OID
    field. '''
    
    input_features_oid_field = input_features_desc.oidFieldName
    input_features_field_names = [fld.name for fld in input_features_desc.fields]
    id_field_name = networkanalysis.get_unique_field_name(id_field_name, input_features_field_names)
    input_features_copy_name = arcpy.ValidateTableName(input_features_name, OUT_WORKSPACE)
    input_features_copy = arcpy.CreateUniqueName(input_features_copy_name, OUT_WORKSPACE)
    input_features_copy_name = os.path.basename(input_features_copy)
    input_features_copy_fms = arcpy.FieldMappings()
    input_features_copy_fm = arcpy.FieldMap()
    input_features_copy_fms.addTable(input_features)
    input_features_copy_fm.addInputField(input_features, input_features_oid_field)
    output_fld = input_features_copy_fm.outputField
    output_fld.name = id_field_name
    output_fld.type = "LONG"
    output_fld.aliasName = id_field_name
    input_features_copy_fm.outputField = output_fld
    input_features_copy_fms.addFieldMap(input_features_copy_fm)

    # Check for well known fields and if present map the well known field as the Name field
    name_field = networkanalysis.check_well_known_fields(input_features_desc)
    if name_field:
        arcpy.AddMessage("Mapping {} field from {} as Name field".format(name_field.name, input_features_name))
        wnf_fm_index = input_features_copy_fms.findFieldMapIndex(name_field.name)
        if wnf_fm_index != -1:
            wnf_fm = input_features_copy_fms.getFieldMap(wnf_fm_index)
            output_fld = wnf_fm.outputField
            output_fld.name = "Name"
            output_fld.type = "TEXT"
            output_fld.aliasName = name_field.aliasName
            wnf_fm.outputField = output_fld
            input_features_copy_fms.replaceFieldMap(wnf_fm_index, wnf_fm)

    arcpy.conversion.FeatureClassToFeatureClass(input_features, OUT_WORKSPACE,
                                                input_features_copy_name,
                                                field_mapping=input_features_copy_fms)
    return input_features_copy, id_field_name

def create_copy_with_oidfield_alt(input_features, input_features_name):
    '''Creates the copy of input features that contain all the fields from input features including the OID
    field. '''
    
    input_features_copy_name = arcpy.ValidateTableName(input_features_name + "Copy", OUT_WORKSPACE)
    input_features_copy = arcpy.CreateUniqueName(input_features_copy_name, OUT_WORKSPACE)
    #input_features_copy_name = os.path.basename(input_features_copy)
    fs = arcpy.FeatureSet()
    fs.load(input_features)
    fs.save(input_features_copy)
    arcpy.AddMessage("Copied {0} as {1}".format(input_features, input_features_copy))
    return input_features_copy

def nearest_using_straight_line(analysis_layer_prop_set, near_locations_layer_prop_set, max_count, search_cutoff,
                                search_cutoff_units, out_near_locations_layer_name, out_connecting_lines_layer_name):
    '''Finds nearest features using straight line distance'''

    #There is no route data when measurement type is straight line. So route data is always None from this function.
    #This is done to ensure that a three value tuple is always returned from this function.
    out_route_data = ""


    start_time = time.time()
    func_start = start_time

    #Assign variables from prop sets
    analysis_layer, analysis_layer_name, analysis_layer_desc, analysis_layer_name_orig, analysis_layer_orig_fid_field_name = analysis_layer_prop_set
    near_locations_layer, near_locations_layer_name, near_locations_layer_desc, near_locations_layer_name_orig, near_locations_layer_orig_fid_field_name = near_locations_layer_prop_set
    
    #Determine if the analysis layer is same as near layer are identical.
    input_layers_identical = True if analysis_layer_desc.catalogPath == near_locations_layer_desc.catalogPath else False
    
    arcpy.AddMessage("inputLayer same as nearLayer? {0}".format(input_layers_identical))
    
    #Store the original layer names in case we need to project the inputs and change the names
    analysis_layer_orig_name = analysis_layer_name
    near_locations_layer_orig_name = near_locations_layer_name
    search_radius = "{0} {1}".format(search_cutoff, search_cutoff_units.replace(" ", ""))

    straight_line_descriptor = "Total_"
    straight_line_descriptor_title_case = "Straight Line Distance ({0})"

    #dict is field name: field alias
    straight_line_dist_field_names = {
        straight_line_descriptor + "Kilometers": straight_line_descriptor_title_case.format("Kilometers"),
        straight_line_descriptor + "Miles": straight_line_descriptor_title_case.format("Miles")
    }
    search_cutoff_unit_field_name =  "{0}{1}".format(straight_line_descriptor, search_cutoff_units.replace(" ", ""))
    if not search_cutoff_unit_field_name in straight_line_dist_field_names:
        straight_line_dist_field_names[search_cutoff_unit_field_name] = straight_line_descriptor_title_case.format(search_cutoff_units)
    out_connecting_lines_layer_system_field_names = ["From_ID", "To_ID", "NearRank"] +  list(straight_line_dist_field_names.keys())
    out_connecting_lines_layer_system_field_names_lower = [name.lower() for name in out_connecting_lines_layer_system_field_names]

    out_near_locations_layer = os.path.join(OUT_WORKSPACE, out_near_locations_layer_name)
    out_connecting_lines_layer = os.path.join(OUT_WORKSPACE, out_connecting_lines_layer_name)    
    out_connecting_lines_table_name = out_connecting_lines_layer_name + "Table"
    out_connecting_lines_table = os.path.join(OUT_WORKSPACE, out_connecting_lines_table_name)
    out_connecting_lines_table_view = out_connecting_lines_layer_name + "TableView"

    try:
        start_time = time.time()
        #Describe the layer and store some properties that we need to use later
        ###analysis_layer_desc = arcpy.Describe(analysis_layer)
        analysis_layer_oid_field_name = analysis_layer_desc.OIDFieldName
        analysis_layer_sr = analysis_layer_desc.spatialReference
        ###near_locations_layer_desc = arcpy.Describe(near_locations_layer)
        near_locations_layer_oid_field_name = near_locations_layer_desc.OIDFieldName
        near_locations_layer_sr = near_locations_layer_desc.spatialReference
        #pcs_sr = arcpy.SpatialReference(PCS_WKID)
        arcpy.AddMessage("Analysis layer SR: {0}".format(analysis_layer_sr.name))
        arcpy.AddMessage("Near locations layer SR: {0}".format(near_locations_layer_sr.name))
                 
        #Execute the generate near table tool
        arcpy.analysis.GenerateNearTable(analysis_layer, near_locations_layer, out_connecting_lines_table,
                                         search_radius, True, False,False, max_count, "GEODESIC")
        aolutils.AddTimerMessage(start_time, "Completed Generate Near Table tool")
        
        #If generate near table output is empty, the just return emoty outputs
        out_connecting_lines_table_row_count = int(arcpy.management.GetCount(out_connecting_lines_table).getOutput(0))
        if out_connecting_lines_table_row_count == 0:
            arcpy.AddMessage("Got empty table as output from Generate Near Table")
            aolutils.AddErrorCode(100259, ERROR_CODES[100259])
            raise arcpy.ExecuteError
            # arcpy.management.CreateFeatureclass(OUT_WORKSPACE, out_near_locations_layer_name,
            #                                     near_locations_layer_desc.shapeType,
            #                                     spatial_reference=near_locations_layer_sr)
            # arcpy.management.CreateFeatureclass(OUT_WORKSPACE, out_connecting_lines_layer_name, "POLYLINE",
            #                                     spatial_reference=analysis_layer_sr)
                              
            # return out_near_locations_layer, out_connecting_lines_layer, out_route_data
        
        #Generate Near Table now populates a NEAR_RANK field. So rename the NEAR_RANK field as NearRank
        #with an alias of "Near Rank"
        #Add the NearRank field which will be calculated later
        #arcpy.management.AddField(out_connecting_lines_table, "NearRank", "LONG", field_alias="Near Rank")
        arcpy.management.AlterField(out_connecting_lines_table, "NEAR_RANK", "NearRank", "Near Rank")
        out_connecting_lines_table_desc = arcpy.Describe(out_connecting_lines_table)
        
        ##Derive the out_near_locations_layer from the gnt table using AddJoin
        select_nearest_features(near_locations_layer, near_locations_layer_oid_field_name, out_connecting_lines_table,
                                out_connecting_lines_table_name, "NEAR_FID", out_near_locations_layer)
        aolutils.AddTimerMessage(start_time, "Using Add Join Created nearest locations at {0}".format(out_near_locations_layer))

        #Derive the out_connecting_lines_layer from the gnt table

        #Join analysis_layer based on IN_FID and OBJECTID fields
        arcpy.management.MakeTableView(out_connecting_lines_table, out_connecting_lines_table_view, workspace=OUT_WORKSPACE)
        arcpy.management.AddJoin(out_connecting_lines_table_view, "IN_FID", analysis_layer, analysis_layer_oid_field_name)

        #Join near_locations_layer based on NEAR_FID and OBJECTID fields
        if not input_layers_identical:
            arcpy.management.AddJoin(out_connecting_lines_table_view, "{0}.NEAR_FID".format(out_connecting_lines_table_name),
                                     near_locations_layer, near_locations_layer_oid_field_name)

        #Get the field names for out_connecting_lines_layer
        out_connecting_lines_table_view_desc = arcpy.Describe(out_connecting_lines_table_view)
        out_connecting_lines_table_view_fields = out_connecting_lines_table_view_desc.fields
        #Dict contains old_field_name:(new_field_name, field_object)
        out_connecting_lines_layer_fields = collections.OrderedDict()
        out_connecting_lines_layer_field_names = []
        rename_field_names = {
            "{}.IN_FID".format(out_connecting_lines_table_name): out_connecting_lines_layer_system_field_names[0],
            "{}.NEAR_FID".format(out_connecting_lines_table_name): out_connecting_lines_layer_system_field_names[1],
            "{}.NearRank".format(out_connecting_lines_table_name) : out_connecting_lines_layer_system_field_names[2],
            "{}.NEAR_DIST".format(out_connecting_lines_table_name):  straight_line_descriptor + "Meters"
        }
        remove_field_names = ("{0}.{1}".format(out_connecting_lines_table_name, out_connecting_lines_table_desc.OIDFieldName),
                              "{0}.{1}".format(analysis_layer_name, analysis_layer_oid_field_name),
                              "{0}.{1}".format(near_locations_layer_name, near_locations_layer_oid_field_name),
                              "{0}.Shape_Length".format(analysis_layer_name),
                              "{0}.Shape_Length".format(near_locations_layer_name),
                              "{0}.Shape_Area".format(analysis_layer_name),
                              "{0}.Shape_Area".format(near_locations_layer_name),
                              "{0}.FROM_X".format(out_connecting_lines_table_name),
                              "{0}.FROM_Y".format(out_connecting_lines_table_name),
                              "{0}.NEAR_X".format(out_connecting_lines_table_name),
                              "{0}.NEAR_Y".format(out_connecting_lines_table_name),
                              )
        for fld in out_connecting_lines_table_view_fields:
            fld_name = fld.name
            if fld_name in rename_field_names:
                new_field_name = rename_field_names[fld_name]

            elif fld_name in remove_field_names:
                continue
            else:
                new_field_name = fld_name.replace(analysis_layer_name, "From").replace(near_locations_layer_name, "To")
                new_field_name = new_field_name.replace(".", "_")
                if new_field_name.lower() in out_connecting_lines_layer_system_field_names_lower:
                    new_field_name = new_field_name + "_Orig"
            out_connecting_lines_layer_fields[fld_name] = (new_field_name, fld)
        #Create the new out_connecting_lines_layer with all the fields
        #When using the GEODESIC method with GenerateNearTable, the FROM_X, FROM_Y, NEAR_X, NEAR_Y
        #fields in output table are always in WGS84 SR and NEAR_DIST field in meters.
        #If both analysis layer and near layer are in PCS, NEAR_DIST is in the units of analysis layer
        out_connecting_lines_layer_sr = arcpy.SpatialReference(4326)
        arcpy.management.CreateFeatureclass(OUT_WORKSPACE, out_connecting_lines_layer_name, "POLYLINE", 
                                            spatial_reference=out_connecting_lines_layer_sr)
        for fld in out_connecting_lines_layer_fields:
            fld_name, fld_object = out_connecting_lines_layer_fields[fld]
            #Create good field alias. use <layer name>: <orig field name>
            if fld_name.startswith("From_"):
                fld_alias = fld_name.replace("From_", analysis_layer_orig_name + ": ")
            elif fld_name.startswith("To_"):
                fld_alias = fld_name.replace("To_", near_locations_layer_orig_name + ": ")
            elif fld_name.startswith(straight_line_descriptor):
                fld_alias = straight_line_descriptor_title_case.format(fld_name.split("_")[-1])
            elif fld_name == "NearRank":
                fld_alias = "Near Rank"
            else:
                fld_alias = fld_name
            fld_name = arcpy.ValidateFieldName(fld_name, OUT_WORKSPACE)
            arcpy.management.AddField(out_connecting_lines_layer, fld_name, fld_object.type, fld_object.precision,
                                      fld_object.scale, fld_object.length, fld_alias)
            out_connecting_lines_layer_field_names.append(fld_name)

        #Insert features into out_connecting_lines_layer
        insert_cursor_fields = out_connecting_lines_layer_field_names + ["SHAPE@"]
        coords_field_names = ["{0}.{1}".format(out_connecting_lines_table_name, f) for f in ("FROM_X", "FROM_Y", "NEAR_X", "NEAR_Y")]
        search_cursor_fields = list(out_connecting_lines_layer_fields.keys()) + coords_field_names
        #Get the index for orig_fid fields so that they can be used to recalculate from_id and to_id fields
        from_orig_fid_field = "From_{}".format(analysis_layer_orig_fid_field_name)
        to_orig_fid_field = "To_{}".format(near_locations_layer_orig_fid_field_name)
        index_from_orig_fid_field = -1
        index_to_orig_fid_field = -1
        if from_orig_fid_field in insert_cursor_fields:
            index_from_orig_fid_field = insert_cursor_fields.index(from_orig_fid_field)
        if to_orig_fid_field in insert_cursor_fields:
            index_to_orig_fid_field = insert_cursor_fields.index(to_orig_fid_field)
        recalc_id_fields = False if index_from_orig_fid_field == -1 or index_to_orig_fid_field == -1 else True 
        
        #point_array = arcpy.Array()
        #If both analysis layer and near layer is in PCS, NEAR_DIST field is in the units of
        #analysis layer else it is in meters
        meter_dist_conversion_factor = 1.0
        if analysis_layer_sr.type.lower() == "projected" and near_locations_layer_sr.type.lower() == "projected":
            if hasattr(analysis_layer_sr, "metersPerUnit"):
                meter_dist_conversion_factor = analysis_layer_sr.metersPerUnit
        zero_length_line = [arcpy.Point(0, 0), arcpy.Point(0, 0)]
        #rank_seq = 1
        #unique_from_fids = []
        with arcpy.da.InsertCursor(out_connecting_lines_layer, insert_cursor_fields) as out_lines_cursor:
            with arcpy.da.SearchCursor(out_connecting_lines_table_view, search_cursor_fields) as conn_lines_table_view_cursor:
                #Sort based on IN_FID and NEAR_DIST fields
                #for row in sorted(conn_lines_table_view_cursor, key=operator.itemgetter(0,2)):
                for row in conn_lines_table_view_cursor:
                    #Get all fields except the last four which contains coords
                    output_row = list(row[0:-4])
                    ##Calculate the NearRank
                    #if output_row[0] in unique_from_fids:
                        #rank_seq += 1
                    #else:
                        #rank_seq = 1
                        #unique_from_fids.append(output_row[0])
                    #output_row[3] = rank_seq
                    near_dist = output_row[2]
                    if near_dist > 0:
                        # Convert NEAR_DIST field from spatial reference linear units to meters
                        # output_row[2] = near_dist * meter_dist_conversion_factor
                        # Since using GEODESIC with GenerateNearTable, NEAR_DIST is always in meters.
                        output_row[2] = near_dist
                        point_list = [arcpy.Point(row[-4], row[-3]), arcpy.Point(row[-2], row[-1])]
                        simple_line_shape = arcpy.Polyline(arcpy.Array(point_list),
                                                           out_connecting_lines_layer_sr)
                        #densify longer lines so that they look like curved geodesic lines
                        #use 1% of total line length as the densification tolerance
                        if near_dist > 1609000:  # 1,000 miles.
                            line_shape = simple_line_shape.densify("GEODESIC", near_dist * 0.01, 1)
                        else:
                            line_shape = simple_line_shape
                    else:
                        #Create a zero distance line if distance is zero
                        #point_list = zero_length_line
                        line_shape = arcpy.Polyline(arcpy.Array(zero_length_line),
                                                    out_connecting_lines_layer_sr)
                    output_row.append(line_shape)
                    #Calculate From_ID and To_ID based on ORIG_FID fields
                    if recalc_id_fields:
                        output_row[0] = output_row[index_from_orig_fid_field]
                        output_row[1] = output_row[index_to_orig_fid_field]
                    
                    #arcpy.AddMessage(u"Fields: {0}\nRow: {1}".format(insert_cursor_fields, output_row))
                    out_lines_cursor.insertRow(output_row)
        
        #Drop the ORIG_FID fields
        if recalc_id_fields:
            arcpy.management.DeleteField(out_connecting_lines_layer, (from_orig_fid_field, to_orig_fid_field))

        #Add the straight line distance fields
        for dist_field in straight_line_dist_field_names:
            if not dist_field in out_connecting_lines_layer_field_names:
                dist_field_units = dist_field.split("_")[-1]
                if dist_field_units == search_cutoff_units:
                    arcpy.management.AddField(out_connecting_lines_layer, dist_field, "DOUBLE",
                                              field_alias=straight_line_dist_field_names[dist_field])
                    out_connecting_lines_layer_field_names.append(dist_field)
                    conversion_factor = DISTANCE_CONVERSION.get(dist_field_units, 1)
                    arcpy.management.CalculateField(out_connecting_lines_layer, dist_field, 
                                                    "!{0}Meters! * {1}".format(straight_line_descriptor,
                                                                                conversion_factor), "PYTHON_9.3")
        #Delete the meter field, if search cutoff units is not meters
        if search_cutoff_units.upper() != "METERS":
            delete_field_name = straight_line_descriptor + "Meters"
            arcpy.management.DeleteField(out_connecting_lines_layer, delete_field_name)
            if delete_field_name in out_connecting_lines_layer_field_names:
                out_connecting_lines_layer_field_names.remove(delete_field_name)
            
        #for f in arcpy.ListFields(out_connecting_lines_layer):
            #arcpy.AddMessage("name: '{0}', alias: '{1}'".format(f.name, f.aliasName))

        aolutils.AddTimerMessage(start_time, "Created connecting lines layer at {0}".format(out_connecting_lines_layer))

    except Exception as ex:
        out_near_locations_layer = ""
        out_connecting_lines_layer = ""
        raise
        #arcpy.AddError(str(ex))        
    func_completion_time = round(time.time() - func_start,2)
    arcpy.AddMessage("Total time to run nearest_using_straight_line function: {0} seconds".format(func_completion_time))     
    return out_near_locations_layer, out_connecting_lines_layer, out_route_data

def nearest_using_network(analysis_layer_prop_set, near_locations_layer_prop_set, measurement_method,
                          max_count, search_cutoff, search_cutoff_units, time_of_day,
                          out_near_locations_layer_name, out_connecting_lines_layer_name,
                          time_zone_for_time_of_day="GeoLocal", include_route_layers=False, point_barrier_layer=None,
                          line_barrier_layer=None, polygon_barrier_layer=None):
    '''Finds nearest using network travel time or distances.'''
    start_time = time.time()
    func_start = start_time
    
    analysis_layer, analysis_layer_name, analysis_layer_desc, analysis_layer_name_orig, analysis_layer_orig_fid_field_name = analysis_layer_prop_set
    near_locations_layer, near_locations_layer_name, near_locations_layer_desc, near_locations_layer_name_orig, near_locations_layer_orig_fid_field_name = near_locations_layer_prop_set
    temp_out_connecting_lines_layer_name = out_connecting_lines_layer_name + "Temp"
    orig_search_cutoff_units = search_cutoff_units
    measurement_method_upper = measurement_method.upper()
    global is_measurement_method_time_based
    global travel_mode_name

    travel_mode_types = {
        "DRIVINGTIME" : "Driving",
        "DRIVINGDISTANCE" : "Driving",
        "WALKINGTIME" : "Walking",
        "WALKINGDISTANCE" : "Walking",
        "TRUCKINGTIME" : "Trucking",
        "TRUCKINGDISTANCE" : "Trucking",
        "AUTOMOBILE" : "Driving",
        "TRUCK" : "Trucking",
        "WALK" : "Walking",
        "OTHER" : "Travel",
        }
    travel_mode_type = "Travel"
    travel_mode_dict = {}
    #is_measurement_method_time_based = False
    #Determine the mode type based on travel mode type keyword and whether the mode is time or distance based.
    
    if measurement_method_upper in travel_mode_types:
        #travel_mode_type = travel_mode_types[measurement_method_upper]
        measurement_method = travel_mode_types[measurement_method_upper]
        if measurement_method_upper in TIME_BASED_MEASUREMENT_METHODS:
            is_measurement_method_time_based = True
            travel_mode_name = "{0} Time".format(measurement_method)
        else:
            is_measurement_method_time_based = False
            travel_mode_name = "{0} Distance".format(measurement_method)
    else:
        travel_mode_dict = json.loads(measurement_method)
        #travel_mode_type = travel_mode_dict.get("type", "Travel")
        #travel_mode_type = travel_mode_types.get(travel_mode_type, travel_mode_type)
        travel_mode_name = travel_mode_dict.get("name", "Travel Mode")
        if travel_mode_dict["impedanceAttributeName"] == travel_mode_dict["timeAttributeName"]:
            is_measurement_method_time_based = True

    
    try:
        service_result = None
        save_route_data = False
        populate_directions = False
        solve_succeeded = False
        out_route_data = ""
        directions_language = "en"
        out_near_locations_layer = os.path.join(OUT_WORKSPACE, out_near_locations_layer_name)
        temp_out_connecting_lines_layer = os.path.join(OUT_WORKSPACE, temp_out_connecting_lines_layer_name)
        out_connecting_lines_layer = os.path.join(OUT_WORKSPACE, out_connecting_lines_layer_name)
        near_locations_layer_oid_field_name = near_locations_layer_desc.oidFieldName
        near_locations_layer_desc_name = near_locations_layer_desc.name.replace(".", "_")
        analysis_layer_oid_field_name = analysis_layer_desc.oidFieldName
        analysis_layer_desc_name = analysis_layer_desc.name.replace(".", "_")
        
        long_facility_id_field_name = "FacilityOID"
        long_incident_id_field_name = "IncidentOID"
        
        
        #Determine if the analysis layer is same as near layer are identical.
        input_layers_identical = True if analysis_layer_desc.catalogPath == near_locations_layer_desc.catalogPath else False
        arcpy.AddMessage("inputLayer same as nearLayer? {0}".format(input_layers_identical))

        #If using DrivingTime, WalkingTime or TruckingTime search_cutoff_units is always Minutes
        if is_measurement_method_time_based:
            search_cutoff_units = "Minutes"
        else:
            #due to bug in FindClosestFacilities, only Miles is working
            #So convert search cutoff to Miles
            if orig_search_cutoff_units != "Miles":
                search_cutoff_units = "Miles"
                METER_TO_MILE = 0.00062
                search_cutoff = search_cutoff * METER_TO_MILE / DISTANCE_CONVERSION.get(orig_search_cutoff_units, 1)

        #Get the URL to the async closest facility service
        tbx = aolutils.getRemoteToolbox(hostedgp, "asyncClosestFacility")
        arcpy.AddMessage("Adding remote toolbox {0}".format(tbx))
        time_zone_keywords = {"GeoLocal" : "Geographically Local",
                                  "UTC": "UTC"}
        #Check if we are saving route data
        if include_route_layers:
            save_route_data = True
            populate_directions = True
            directions_language = networkanalysis.get_user_culture(hostedgp)
            arcpy.AddMessage("Directions language: {0}".format(directions_language))        
        task_params = [analysis_layer, near_locations_layer, search_cutoff_units, "", max_count,
                       search_cutoff, "", "", time_of_day, "", "", point_barrier_layer.layer, line_barrier_layer.layer,
                       polygon_barrier_layer.layer, "", "", "", "", populate_directions, directions_language, "", "",
                       time_zone_keywords[time_zone_for_time_of_day], measurement_method,
                       "", "", "", save_route_data]
        ignore_error_codes = (30119,30120)
        try:
            service_result = networkanalysis.call_async_gp_service(tbx, "FindClosestFacilities", task_params,
                                                                ignore_error_codes, (RESTRICTIONS_PARAMETER_INDEX,))
        except arcpy.ExecuteError as ex:
            try:
                remote_msgs = ex.args[0] if ex.args else ""
                if remote_msgs:
                    if 30145 in remote_msgs:
                        # We should be here only when working with ArcGIS Online service which always has a walking limit
                        msg_code = 100258
                        walking_limit = tool_limits.get("maximumGeodesicDistanceWhenWalking", 27)
                        walking_limit_unit = tool_limits.get("maximumGeodesicDistanceUnitsWhenWalking", "Miles")
                        msg_params = {
                            "mileValue": networkanalysis.convert_units(walking_limit, walking_limit_unit, "Miles"),
                            "kmValue": networkanalysis.convert_units(walking_limit, walking_limit_unit, "Kilometers"),
                        }
                        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code], msg_params)
                        raise arcpy.ExecuteError
                    if 30212 in remote_msgs:
                        msg_code = 100259
                        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code])
                        raise arcpy.ExecuteError
                    if 30095 in remote_msgs:
                        # Barrier limit exceeded
                        msg_code = 0
                        for msg_txt in remote_msgs[30095]:
                            if "PolygonBarriers" in msg_txt:
                                msg_code = 100267
                                limit = 2000
                                break
                            elif "PolylineBarriers" in msg_txt:
                                msg_code = 100266
                                limit = 500
                                break
                            elif "Barriers" in msg_txt:
                                msg_code = 100265
                                limit = 250
                                break
                        if msg_code:
                            msg = networkanalysis.NetworkAnalysisTool.ERROR_CODES[msg_code]
                            aolutils.AddErrorCode(msg_code, msg, {"limit": limit})
                            raise arcpy.ExecuteError
                else:
                    raise
            except Exception:
                raise
        
        #Reset the timer as the callAsyncGPService handles its own timing
        start_time = time.time()
        
        if service_result.getOutput(2).lower() == 'true':
            solve_succeeded = True

        if save_route_data:
            if solve_succeeded:
                out_route_data = service_result.getOutput(5)
            else:
                #Raise a warning since no route data is generated when there is no solution.
                msg_code = 100217
                aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code], warning=True)
        
        arcpy.management.CopyFeatures(service_result.getOutput(0), temp_out_connecting_lines_layer)
        start_time = aolutils.AddTimerMessage(start_time, "Saved the results from remote tool")

        ##Post process results
     
        select_nearest_features(near_locations_layer, near_locations_layer_oid_field_name,
                                temp_out_connecting_lines_layer, temp_out_connecting_lines_layer_name,
                                long_facility_id_field_name, out_near_locations_layer)
        start_time = aolutils.AddTimerMessage(start_time,
                                              "Created nearest layer as {0}".format(out_near_locations_layer))

        # Add new RouteLayerItemID and RouteLayerItemURL fields that are populated after route layers are created.
        arcpy.management.AddField(temp_out_connecting_lines_layer, ROUTE_LAYER_ITEM_ID_FIELD_NAME, "TEXT",
                                  field_length=50, field_alias="Route Layer Item ID")
        arcpy.management.AddField(temp_out_connecting_lines_layer, ROUTE_LAYER_ITEM_URL_FIELD_NAME, "TEXT",
                                  field_length=256, field_alias="Route Layer Item")

        #join the analysis layer and near layer to conn lines
        temp_out_connecting_lines_join_layer = temp_out_connecting_lines_layer + "Join"
        arcpy.management.MakeFeatureLayer(temp_out_connecting_lines_layer,
                                          temp_out_connecting_lines_join_layer, workspace=OUT_WORKSPACE)
        arcpy.management.AddJoin(temp_out_connecting_lines_join_layer, long_incident_id_field_name,
                                 analysis_layer, analysis_layer_oid_field_name)
        if not input_layers_identical:
            arcpy.management.AddJoin(temp_out_connecting_lines_join_layer,
                                     "{0}.{1}".format(temp_out_connecting_lines_layer_name, 
                                                      long_facility_id_field_name),
                                     near_locations_layer, near_locations_layer_oid_field_name)
        
        #Transfer all the attributes from the analysis layer and near locations layer to the connecting lines layer
        conn_lines_fms = arcpy.FieldMappings()
        conn_lines_fms.addTable(temp_out_connecting_lines_join_layer)      
        
        #prepare the fields we want to always remove and fields we want to rename based on measurement
        #method
        cflines_rename_fields = {
            long_incident_id_field_name: ("From_ID","{0}: ID".format(analysis_layer_name_orig)),
            long_facility_id_field_name: ("To_ID", "{0}: ID".format(near_locations_layer_name_orig)),
            "FacilityRank": ("NearRank", "Near Rank"),
            "Name" : ("RouteName", "Route Name"),
        }        
        fields_to_remove = ["FacilityID", "IncidentID", "FacilityCurbApproach", "IncidentCurbApproach", "Shape_Length"]
        
        if is_measurement_method_time_based:
            cflines_rename_fields["Total_Minutes"] = ("Total_Minutes",
                                                      "Minimum {0} Time (Minutes)".format(travel_mode_type))
            org_units = aolutils.getUnits(hostedgp,False)
            if org_units.lower() == "miles":
                fields_to_remove.append("Total_Kilometers")
                cflines_rename_fields["Total_Miles"] = ("Total_Miles",
                                                      "{0} Distance (Miles)".format(travel_mode_type))
            else:
                fields_to_remove.append("Total_Miles")
                cflines_rename_fields["Total_Kilometers"] = ("Total_Kilometers",
                                                      "{0} Distance (Kilometers)".format(travel_mode_type))
        else:
            cflines_rename_fields["Total_Minutes"] = ("Total_Minutes",
                                                      "{0} Time (Minutes)".format(travel_mode_type))
            #fields_to_remove.append("Total_Minutes")
            if orig_search_cutoff_units == "Miles":
                cflines_rename_fields["Total_Miles"] = ("Total_Miles",
                                                        "Minimum {0} Distance (Miles)".format(travel_mode_type))
                fields_to_remove.append("Total_Kilometers")
            else:
                cflines_rename_fields["Total_Kilometers"] = ("Total_Kilometers",
                                                             "Minimum {0} Distance (Kilometers)".format(travel_mode_type))
                fields_to_remove.append("Total_Miles")
            
        #Remove the fields from fields_to_remove in the field mappings
        for fld in fields_to_remove:
            fld_index = conn_lines_fms.findFieldMapIndex(fld)
            if fld_index != -1:
                #arcpy.AddMessage(u"Removing field: {0}".format(fld))
                conn_lines_fms.removeFieldMap(fld_index)
                
        
        #Rename the fields that we know always exists on CF lines
        for fld in cflines_rename_fields:
            fld_index = conn_lines_fms.findFieldMapIndex(fld)
            if fld_index != -1:
                #arcpy.AddMessage(u"Renaming field: {0}".format(fld))
                fm = conn_lines_fms.getFieldMap(fld_index)
                out_fld = fm.outputField
                out_fld.name = cflines_rename_fields[fld][0]
                out_fld.aliasName = cflines_rename_fields[fld][1]
                fm.outputField = out_fld
                conn_lines_fms.replaceFieldMap(fld_index, fm)
        
        #Rename the fields from analysis and near layers
        nl_lyr_table_qual = near_locations_layer_desc_name + "."
        a_lyr_table_qual = analysis_layer_desc_name + "."

        for out_fld_index, fm in enumerate(conn_lines_fms):
            out_fld = fm.outputField
            qual_fld_name = fm.getInputFieldName(0)
            fld_name = out_fld.name
            fld_alias = out_fld.aliasName          
            #All fields from near layer are renamed as To_<orig name>
            if qual_fld_name.startswith(nl_lyr_table_qual):
                new_fld_name = "To_" + fld_name
                if new_fld_name == "To_ID":
                    new_fld_name = new_fld_name + "_Orig"
                new_fld_alias = "{0}: {1}".format(near_locations_layer_name_orig,
                                                  fld_alias.replace(near_locations_layer_desc_name + "_", ""))
                out_fld.name = new_fld_name
                out_fld.aliasName = new_fld_alias
                fm.outputField = out_fld
                conn_lines_fms.replaceFieldMap(out_fld_index, fm)
            #All fields from analysis layer are renamed as From_<orig name>
            elif qual_fld_name.startswith(a_lyr_table_qual):
                new_fld_name = "From_" + fld_name
                if new_fld_name == "From_ID":
                    new_fld_name = new_fld_name + "_Orig"
                fld_alias.replace(analysis_layer_desc_name, "")
                #If table name is in the alias, remove it
                new_fld_alias = "{0}: {1}".format(analysis_layer_name_orig,
                                                  fld_alias.replace(analysis_layer_desc_name + "_", ""))
                out_fld.name = new_fld_name
                out_fld.aliasName = new_fld_alias
                fm.outputField = out_fld
                conn_lines_fms.replaceFieldMap(out_fld_index, fm)                 
    
        arcpy.conversion.FeatureClassToFeatureClass(temp_out_connecting_lines_join_layer, OUT_WORKSPACE,
                                                    out_connecting_lines_layer_name, 
                                                    field_mapping=conn_lines_fms)
        
        #Modify and Delete fields on connecting lines layer
        from_orig_fid_field_name = "From_{}".format(analysis_layer_orig_fid_field_name)
        to_orig_fid_field_name = "To_{}".format(near_locations_layer_orig_fid_field_name)
        update_cursor_fields = ["From_ID", from_orig_fid_field_name, "To_ID", to_orig_fid_field_name]
        out_conn_lines_delete_fields = [from_orig_fid_field_name, to_orig_fid_field_name,
                                        "From_{}".format(analysis_layer_desc.oidFieldName),
                                        "To_{}".format(near_locations_layer_desc.oidFieldName)
                                        ]

        non_standard_cutoff_units = False
        #Check if we need to add additional field for distance based on the cutoff units
        if not is_measurement_method_time_based:
            if not orig_search_cutoff_units in DEFAULT_DISTANCE_FIELDS:
                non_standard_cutoff_units = True
                new_fld_name = "Total_{0}".format(orig_search_cutoff_units.replace(" ", ""))
                new_fld_alias = "Minimum {0} Distance ({1})".format(travel_mode_type, orig_search_cutoff_units)
                arcpy.management.AddField(out_connecting_lines_layer, new_fld_name, "DOUBLE",
                                          field_alias=new_fld_alias)
                distance_km_field_name = "Total_Kilometers"
                update_cursor_fields += [new_fld_name, distance_km_field_name]
                #Delete the distance field in kilometers
                out_conn_lines_delete_fields.append(distance_km_field_name)

        #Recalculate From_ID and To_ID fields based on ORIG_FID fields
        with arcpy.da.UpdateCursor(out_connecting_lines_layer, update_cursor_fields) as conn_lines_cursor:
            for row in conn_lines_cursor:
                row[0] = row[1]
                row[2] = row[3]
                if non_standard_cutoff_units:
                    row[-2] = row[-1] * 1000 * DISTANCE_CONVERSION.get(orig_search_cutoff_units, 1)
                conn_lines_cursor.updateRow(row)
        arcpy.management.DeleteField(out_connecting_lines_layer, out_conn_lines_delete_fields)
                
        start_time = aolutils.AddTimerMessage(start_time,
                                              "Created connecting lines layer at {0}".format(out_connecting_lines_layer))

    except Exception as ex:
        out_near_locations_layer = ""
        out_connecting_lines_layer = ""
        raise
    func_completion_time = round(time.time() - func_start,2)
    arcpy.AddMessage("Total time to run nearest_using_network function: {0} seconds".format(func_completion_time)) 
    return out_near_locations_layer, out_connecting_lines_layer, out_route_data

def find_nearest(hosted_analysis_layer, hosted_near_locations_layer, measurement_method, max_count,
                 search_cutoff, search_cutoff_units, time_of_day, context,
                 time_zone_for_time_of_day="GeoLocal", limit_checker_service_available=True,
                 include_route_layers=False, point_barrier_layer=None, line_barrier_layer=None,
                 polygon_barrier_layer=None):
    '''Main execution'''

    global analysis_layer_count
    global near_locations_layer_count
    global tool_limits

    #Get the tool limits from routing utlities service if available in the portal. Default is the limits imposed
    #by online services
    AGOL_MAX_COUNT_PER_LOCATION= 100
    AGOL_MAX_ANALYSIS_FEATURES = 5000
    AGOL_MAX_NEAR_FEATURES = 5000
    if limit_checker_service_available:
        # Straight line case can be run without routing priviledge. Use AGOL limits if routing priviledge is not available
        if measurement_method == "StraightLine" and not aolutils.checkPrivilege(networkanalysis.NETWORK_ANALYSIS_PRIVILEGE, hostedgp):
            arcpy.AddMessage("Cannot determine limits using the routingUtilities service as the user does not have the network analysis privilege. Using ArcGIS Online limits")
            MAX_ANALYSIS_FEATURES = AGOL_MAX_ANALYSIS_FEATURES
            MAX_NEAR_FEATURES = AGOL_MAX_NEAR_FEATURES
            MAX_COUNT_PER_LOCATION = AGOL_MAX_COUNT_PER_LOCATION
        else:
            # routing_utils_tbx = aolutils.getRemoteToolbox(hostedgp, "routingUtilities")
            routing_utils_tbx = aolutils.getHelperServicesUrl(hostedgp, "routingUtilities")
            arcpy.AddMessage("Getting tool limits from {0}".format(routing_utils_tbx))
            tool_limits = networkanalysis.get_tool_limits(routing_utils_tbx, "asyncClosestFacility", "FindClosestFacilities")
            # arcpy.AddMessage(f"tool limits: {tool_limits}")
            if "maximumIncidents" in tool_limits:
                max_incidents = tool_limits["maximumIncidents"]
                if max_incidents is None:
                    MAX_ANALYSIS_FEATURES = INFINITY
                else:
                    MAX_ANALYSIS_FEATURES = max_incidents
            if "maximumFacilities" in tool_limits:
                max_facilities = tool_limits["maximumFacilities"]
                if max_facilities is None:
                    MAX_NEAR_FEATURES = INFINITY
                else:
                    MAX_NEAR_FEATURES = max_facilities
            if "maximumFacilitiesToFind" in tool_limits:
                max_facilities_to_find = tool_limits["maximumFacilitiesToFind"]
                if max_facilities_to_find is None:
                    MAX_COUNT_PER_LOCATION = INFINITY
                else:
                    MAX_COUNT_PER_LOCATION = max_facilities_to_find
    else:
        #Set infinite limits for straight line case as routingUtilities helper service may not be available for on-prem portals
        if measurement_method == "StraightLine":
            arcpy.AddMessage("Setting infinite limits as measurement method is line distance and routingUtilities helper service is not available")
            MAX_COUNT_PER_LOCATION= INFINITY
            MAX_ANALYSIS_FEATURES = INFINITY
            MAX_NEAR_FEATURES = INFINITY

    arcpy.AddMessage("Max analysis features: {0}".format(MAX_ANALYSIS_FEATURES))
    arcpy.AddMessage("Max near features: {0}".format(MAX_NEAR_FEATURES))
    arcpy.AddMessage("Max count per location: {0}".format(MAX_COUNT_PER_LOCATION))
    
    # Initiate start time
    start_time = time.time()
    func_start = start_time
    

    #Outputs
    empty_outputs = ("", "")
    out_near_locations_layer_name = "NearestLocations"
    out_connecting_lines_layer_name = "ConnectingLines"    

    #If max_count_per_locations exceeds the max supported, quit
    if max_count > MAX_COUNT_PER_LOCATION:
        msg_code = 100031
        msg_params = {"max" : MAX_COUNT_PER_LOCATION}
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
        raise arcpy.ExecuteError
    
    #If search_cutoff is less than zero fail.
    if search_cutoff < 0:
        aolutils.AddErrorCode(100038, ERROR_CODES[100038])
        raise arcpy.ExecuteError

    #Fail if measurement method is straight and requesting Route Layers
    if measurement_method == "StraightLine" and include_route_layers:
        msg_code = 100218
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code])
        raise arcpy.ExecuteError
    
    analysis_layer = hosted_analysis_layer.name
    analysis_layer_name_orig = hosted_analysis_layer.layername
    if not analysis_layer_name_orig:
        analysis_layer_name_orig = "Analysis Layer"
    near_locations_layer = hosted_near_locations_layer.name
    near_locations_layer_name_orig = hosted_near_locations_layer.layername
    if not near_locations_layer_name_orig:
        near_locations_layer_name_orig = "Near Layer"
    
    #paramsDict used with AddErrorCode
    analysis_layer_param_dict = {"analysisLayer" : analysis_layer_name_orig}
    near_layer_param_dict = {"nearLayer" : near_locations_layer_name_orig}    

    #Describe the inputs
    analysis_layer_desc = arcpy.Describe(analysis_layer)
    near_locations_layer_desc = arcpy.Describe(near_locations_layer)
    #arcpy.AddMessage(u"Near Def query: {0}".format(near_locations_layer_desc.whereClause)) 
    
    #validation checks specific to network analysis measurement methods
    if measurement_method != "StraightLine":
        #Fail if the measurement method is not a valid travel mode JSON or one of the predefined measurement methods
        #DrivingTime, DrivingDistance, WalkingTime, WalkingDistance, TruckingTime, TruckingDistance
        tm_name = ""
        try:
            travel_mode_object = networkanalysis.get_travel_mode_from_json(measurement_method)
            tm_name = travel_mode_object.name
        except (ValueError, TypeError) as ex:
            if measurement_method.upper() in LEGACY_TRAVEL_MODE_NAMES:
                tm_name = measurement_method
            else:
                aolutils.AddErrorCode(100145, ERROR_CODES[100145], {"travelMode": measurement_method})
                raise arcpy.ExecuteError
                
         
        #Fail if shape type is polyline or polygon when using network based measurement types
        if not (hosted_analysis_layer.shapeType.lower() in POINT_SHAPE_TYPES):
            msg_code = 100036
            msg_params = dict(analysis_layer_param_dict)
            msg_params["measurementType"] = tm_name
            aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
            raise arcpy.ExecuteError
        
        if not (hosted_near_locations_layer.shapeType.lower() in POINT_SHAPE_TYPES):
            msg_code = 100037
            msg_params = dict(near_layer_param_dict)
            msg_params["measurementType"] = tm_name
            aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
            raise arcpy.ExecuteError
        
        # Check shape type for barriers
        if point_barrier_layer.count:
            if not point_barrier_layer.describe.shapeType.lower() in networkanalysis.POINT_SHAPE_TYPES:
                msg_params = dict(inputLayer=point_barrier_layer.name, shapeType="point")
                msg_code = 100264
                msg = networkanalysis.NetworkAnalysisTool.ERROR_CODES[msg_code].format(**msg_params)
                aolutils.AddErrorCode(msg_code, msg, msg_params)
                raise arcpy.ExecuteError
        if line_barrier_layer.count:
            if not line_barrier_layer.describe.shapeType.lower() in networkanalysis.LINE_SHAPE_TYPES:
                msg_params = dict(inputLayer=line_barrier_layer.name, shapeType="line")
                msg_code = 100264
                msg = networkanalysis.NetworkAnalysisTool.ERROR_CODES[msg_code].format(**msg_params)
                aolutils.AddErrorCode(msg_code, msg, msg_params)
                raise arcpy.ExecuteError
        if polygon_barrier_layer.count:
            if not polygon_barrier_layer.describe.shapeType.lower() in networkanalysis.POLYGON_SHAPE_TYPES:
                msg_params = dict(inputLayer=polygon_barrier_layer.name, shapeType="polygon")
                msg_code = 100264
                msg = networkanalysis.NetworkAnalysisTool.ERROR_CODES[msg_code].format(**msg_params)
                aolutils.AddErrorCode(msg_code, msg, msg_params)
                raise arcpy.ExecuteError
    else:
        # Fail if using barriers with line distance
        for barrier_layer, barrier_type in ((point_barrier_layer, "pointBarrierLayer"),
                                            (line_barrier_layer, "lineBarrierLayer"),
                                            (polygon_barrier_layer, "polygonBarrierLayer")):
            if getattr(barrier_layer, "count"):
                msg_params = dict(barrierType=barrier_type)
                msg_code = 100263
                msg = ERROR_CODES[msg_code].format(**msg_params)
                aolutils.AddErrorCode(msg_code, msg, msg_params)
                raise arcpy.ExecuteError

    #make copies of input layer and analysis layers to get rid of any def queries on layers.
    #For straight line case making copies give us proper feature layers that work consistently with arcpy. Directly
    #using hostedlayer has issues with AddJoin where the field names in join output cannot be read properly.
    if analysis_layer_name_orig:
        analysis_layer_name = arcpy.ValidateTableName(analysis_layer_name_orig, OUT_WORKSPACE)
    else:
        analysis_layer_name = "Copy"
    #analysis_fc = project_features(analysis_layer, analysis_layer_desc.spatialReference,
    #                               arcpy.CreateUniqueName(analysis_layer_name, OUT_WORKSPACE),
    #                               force_copy=True)
    analysis_fc, analysis_fc_orig_fid_field_name = create_copy_with_oidfield(analysis_layer, analysis_layer_name,
                                                                             analysis_layer_desc, "ORIG_FID")

    analysis_layer = os.path.basename(analysis_fc)
    arcpy.management.MakeFeatureLayer(analysis_fc, analysis_layer)
    analysis_layer_desc = arcpy.Describe(analysis_layer)

    if near_locations_layer_name_orig:
        near_locations_layer_name = arcpy.ValidateTableName(near_locations_layer_name_orig, OUT_WORKSPACE)
    else:
        near_locations_layer_name = "Copy"
        
    #near_locations_fc = project_features(near_locations_layer, near_locations_layer_desc.spatialReference,
    #                                     arcpy.CreateUniqueName(near_locations_layer_name, OUT_WORKSPACE),
    #                                     force_copy=True)
    near_locations_fc, near_locations_fc_orig_fid_field_name = create_copy_with_oidfield(near_locations_layer,
                                                                                         near_locations_layer_name,
                                                                                         near_locations_layer_desc,
                                                                                         "ORIG_FID")
    near_locations_layer = os.path.basename(near_locations_fc)
    arcpy.management.MakeFeatureLayer(near_locations_fc, near_locations_layer)
    near_locations_layer_desc = arcpy.Describe(near_locations_layer)
        
    #Pass around a tuple of multiple values instead of bloating the number of arguments passed to the function
    #if we pass each layer property as a seperate argument.
    analysis_layer_prop_set = (analysis_layer, analysis_layer_name, analysis_layer_desc, analysis_layer_name_orig,
                               analysis_fc_orig_fid_field_name)
    near_locations_layer_prop_set = (near_locations_layer, near_locations_layer_name, near_locations_layer_desc,
                                     near_locations_layer_name_orig, near_locations_fc_orig_fid_field_name)
           
    start_time = aolutils.AddTimerMessage(start_time, "Read input layers")
    
    #Set the extent to None for other processing
    orig_extent = arcpy.env.extent
    arcpy.env.extent = None
    
    #If count on any of input layers is greater than MAX_INPUT_FEATURES, quit
    if analysis_layer_count > MAX_ANALYSIS_FEATURES:
        msg_code = 100040
        msg_params = {
            "inputLayer": analysis_layer_name_orig,
            "max": MAX_ANALYSIS_FEATURES,
        }
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
        raise arcpy.ExecuteError
    if near_locations_layer_count > MAX_NEAR_FEATURES:
        msg_code = 100040
        msg_params = {
            "inputLayer": near_locations_layer_name_orig,
            "max": MAX_NEAR_FEATURES,
        }
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
        raise arcpy.ExecuteError

    #if we don't have at least one feature in analysis layer and one in near layer, quit
    if analysis_layer_count < 1:
        msg_code = 100032
        msg_params = dict(analysis_layer_param_dict)
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
        raise arcpy.ExecuteError
    if near_locations_layer_count < 1:
        msg_code = 100033
        msg_params = dict(near_layer_param_dict)
        aolutils.AddErrorCode(msg_code, ERROR_CODES[msg_code].format(**msg_params), msg_params)
        raise arcpy.ExecuteError

    #set the output coordinate system to near locations layer if not set
    if arcpy.env.outputCoordinateSystem:
        arcpy.AddMessage("outSR is specified. So outputs will be created in {0}".format(arcpy.env.outputCoordinateSystem.name))
    else:
        out_sr = near_locations_layer_desc.spatialReference
        arcpy.AddMessage("outSR is not specified. So outputs will be created in spatial reference of near layer which is {0}".format(out_sr.name))
        arcpy.env.outputCoordinateSystem = out_sr
    #find nearest based on measurement method
    if measurement_method == "StraightLine":
        outputs = nearest_using_straight_line(analysis_layer_prop_set, near_locations_layer_prop_set,
                                              max_count, search_cutoff, search_cutoff_units,
                                              out_near_locations_layer_name,
                                              out_connecting_lines_layer_name)
    else:
        outputs = nearest_using_network(analysis_layer_prop_set, near_locations_layer_prop_set,
                                        measurement_method, max_count, search_cutoff,
                                        search_cutoff_units, time_of_day,
                                        out_near_locations_layer_name, 
                                        out_connecting_lines_layer_name, time_zone_for_time_of_day, include_route_layers,
                                        point_barrier_layer, line_barrier_layer, polygon_barrier_layer)

    #Project outputs if arcpy.env.OutputCoordinateSystem is set
    output_sr = arcpy.env.outputCoordinateSystem
    if output_sr:
        out_near_locations_layer_proj = arcpy.CreateUniqueName(out_near_locations_layer_name + "Projected",
                                                               OUT_WORKSPACE)
        out_near_locations_layer_proj = project_features(outputs[0], output_sr, out_near_locations_layer_proj)
        out_connecting_lines_layer_proj = arcpy.CreateUniqueName(out_connecting_lines_layer_name + "Projected", OUT_WORKSPACE)
        out_connecting_lines_layer_proj = project_features(outputs[1], output_sr, out_connecting_lines_layer_proj)
        outputs = (out_near_locations_layer_proj, out_connecting_lines_layer_proj, outputs[2])
    
    #Reset the extent
    arcpy.env.extent = orig_extent
    return outputs

def save_outputs(hostedgp, tool_outputs, output_hosted_name, measurement_method="StraightLine",
                 search_cutoff_units="Miles", is_measurement_method_time_based=False, travel_mode_name="Line Distance",
                 include_route_layers=False, time_of_day=None):
    '''Save the nearest layer and connecting lines layer as a feature service or feature collection or route layers
    startTime is the time elapsed for computations done before running this tool.
    It is modified as other computations are performed. 
    beginTime is time at the beginning of any computation and is used to measure
    total time elapsed using final startTime.
    '''
    func_start = time.time()

    if include_route_layers:
        #Save results as route layers
        output_items = create_route_layers(hostedgp, tool_outputs[2])
        #Calculate RouteLayerItemID and RouteLayerItemURL fields on routes layer in the feature output
        #Get the route layer item id for each route name.
        route_layer_items = output_items.get("items", {})
        if route_layer_items:
            route_layer_item_ids = {v["routeName"]: (k, v["url"]) for k,v in route_layer_items.items()}
            with arcpy.da.UpdateCursor(tool_outputs[1], ("RouteName", ROUTE_LAYER_ITEM_ID_FIELD_NAME, 
                                                         ROUTE_LAYER_ITEM_URL_FIELD_NAME)) as cursor:
                for row in cursor:
                    if row[0] in route_layer_item_ids:
                        row[1] = route_layer_item_ids[row[0]][0] #routeName
                        row[2] = route_layer_item_ids[row[0]][1] #url
                        cursor.updateRow(row)


        arcpy.SetParameterAsText(13, json.dumps(output_items))

    with networkanalysis.LogExecutionTime("Created result symbology"):
        #measurement_method for StraightLine is being converted as the distance field in connecting lines
        #is called StraightLineDistance_units and not StraightLine_Units
        if measurement_method == "StraightLine":
            measurement_method = "StraightLineDistance"
        
        #is_measurement_method_time_based = True if measurement_method in TIME_BASED_MEASUREMENT_METHODS else False
        out_nearest_layer, out_connecting_lines_layer = tool_outputs[0:2]
        out_nearest_layer_name = "Nearest Features"
        out_connecting_lines_layer_name = "Connecting Lines"

        #describe the outputs
        desc_out_nearest_layer = arcpy.Describe(out_nearest_layer)
        desc_out_connecting_lines_layer = arcpy.Describe(out_connecting_lines_layer)

        #Symbology for outputs. Insert the apporiate base_symbol based on shape type of output
        polygon_base_symbol = {
            "type": "esriSFS",
            "style": "esriSFSSolid",
            "color": [223, 0, 235,255],
            "outline": {
                "type": "esriSLS",
                "style": "esriSLSSolid",
                "color": [0, 0, 0, 255],
                "width": 1.0
                }
            }        
        line_base_symbol = {
            "type" : "esriSLS",
            "style": "esriSLSSolid",
            "color": [223, 0, 235,255],
            "width" : 4.0,
            "outline": {
                "type": "esriSLS",
                "style": "esriSLSSolid",
                "color": [0, 0, 0, 255],
                "width": 1.0
                }         
            }
        point_base_symbol = {
            "type":"esriSMS",
            "style":"esriSMSCircle",
            "color":[223, 0, 235,255],
            "size":5.0,
            "outline": {
                "color":[0,0,0,255],
                "width":1.0
                }
            }
        nearest_layer_symbol = {
            "point" : point_base_symbol,
            "polyline": line_base_symbol,
            "polygon" : polygon_base_symbol
            }
        #Create drawing info for outputs
        drawing_info_nearest_layer = {
            #"name": "NearestLayer",
            "renderer" : {
                "type": "simple",
                "symbol" : nearest_layer_symbol.get(desc_out_nearest_layer.shapeType.lower()),
                },
            }
        drawing_info_connecting_lines_layer = {
            "renderer": {
                "type": "simple",
                "symbol": {
                    "type": "esriSLS",
                    "style": "esriSLSSolid",
                    "color": [223, 0, 235, 255],
                    "width" : 4.0
                    }
                },
            "transparency" : 50,
            }
        #Create popups
        #Hide ORIG_FID field if present
        nearest_layer_hide_fields = None
        nearest_layer_field_names = [fld.name for fld in desc_out_nearest_layer.fields]
        if "ORIG_FID" in nearest_layer_field_names:
            nearest_layer_hide_fields = ["ORIG_FID"]
        nearest_layer_popup = popup.feature_layer_popup(desc_out_nearest_layer,
                                                        "Summary of {} ({})".format(out_nearest_layer_name,
                                                                                        travel_mode_name),
                                                        hide_fields=nearest_layer_hide_fields)
        #Make sure NearRank field is the first field.
        #Move the To_ID field to be next to all other To_ fields
        #Move the Total_Units fields to be one after another and after NearRank field
        conn_lines_field_names = [fld.name for fld in desc_out_connecting_lines_layer.fields]
        from_field_names = fnmatch.filter(conn_lines_field_names,"From_*")
        total_field_names = fnmatch.filter(conn_lines_field_names,"Total_*")
        conn_lines_move_fields = [("NearRank", desc_out_connecting_lines_layer.OIDFieldName), 
                                    ("To_ID", from_field_names[-1])]
        #Make sure the minimum Total_Units is before the total distance fields
        total_fields_after = "NearRank"
        if measurement_method == "StraightLineDistance":
            total_fields_after = "NearRank"
        elif is_measurement_method_time_based:
            total_fields_after = "Total_Minutes"
            conn_lines_move_fields.append(("Total_Minutes", "NearRank"))
            total_field_names.remove("Total_Minutes")
        else:
            total_fields_after = "NearRank"
            conn_lines_move_fields.append(("From_ID", "Total_Minutes"))
            total_field_names.remove("Total_Minutes")

        #Make sure the RouteLAyerItemURL field is before the FromID field
        if include_route_layers:
            conn_lines_move_fields.append(("From_ID", ROUTE_LAYER_ITEM_URL_FIELD_NAME))

        for fld in total_field_names:
            conn_lines_move_fields.append((fld, total_fields_after))
  
        conn_lines_field_names = networkanalysis.update_field_display_order(conn_lines_field_names,
                                                                            conn_lines_move_fields)
        #Hide the RouteLayerItemID and RouteLayerItemURL fields if present and if they have null values
        #If they have values, only hide RouteLayerItemID field
        conn_lines_hide_fields = []
        if time_of_day:
            conn_lines_hide_fields += ["StartTime", "EndTime"]
        else:
            conn_lines_hide_fields += ["StartTime", "EndTime", "StartTimeUTC", "EndTimeUTC"]
        if include_route_layers:
            conn_lines_hide_fields.append(ROUTE_LAYER_ITEM_ID_FIELD_NAME)
        else:
            if ROUTE_LAYER_ITEM_ID_FIELD_NAME in conn_lines_field_names:
                conn_lines_hide_fields.append(ROUTE_LAYER_ITEM_ID_FIELD_NAME)
            if ROUTE_LAYER_ITEM_URL_FIELD_NAME in conn_lines_field_names:
                conn_lines_hide_fields.append(ROUTE_LAYER_ITEM_URL_FIELD_NAME)
        connecting_lines_popup = popup.feature_layer_popup(desc_out_connecting_lines_layer,
                                                            "Summary of {} ({})".format(out_connecting_lines_layer_name,
                                                                                        travel_mode_name),
                                                            field_names_display_order=conn_lines_field_names,
                                                            hide_fields=conn_lines_hide_fields)
        # Update the labels for StartTimeUTC and EndTimeUTC fields to "Start Time" and "End Time"
        if time_of_day:
            for field_info in connecting_lines_popup.get("fieldInfos", []):
                field_name = field_info.get("fieldName", "")
                if field_name in ("StartTimeUTC", "EndTimeUTC"):
                    field_info["label"] = field_name.rstrip("UTC").replace("Time", " Time")

        #Creating one to many relationship between nearest features and connecting lines.
        ##Not sure what sort of relationship is needed.

        #Create output descriptions for the output layers
        out_description_nearest_layer = aolutils.getOutDescription(out_nearest_layer_name, 0,
                                                                    drawing_info_nearest_layer, nearest_layer_popup)
        out_description_connecting_lines_layer = aolutils.getOutDescription(out_connecting_lines_layer_name, 1,
                                                                            drawing_info_connecting_lines_layer,
                                                                            connecting_lines_popup)
        #Created output hosted feature service or the feature collection
        ##Check if ProcessFeatureOutput works if all features in connecting lines layers have zero length. 
        res = aolutils.HostedToolResult(output_hosted_name)
        res.addHostedOutput(desc_out_nearest_layer, out_description_nearest_layer, 14)
        res.addHostedOutput(desc_out_connecting_lines_layer, out_description_connecting_lines_layer, 15)
    
    res.generateHostedResult(hostedgp, time.time())

    func_completion_time = round(time.time() - func_start, 2)
    arcpy.AddMessage("Total time to run save_output function: {0} seconds".format(func_completion_time))
        
def all_features_zero_length(input_features):
    '''Check if all features in the feature class have zero length. If yes return True else false'''
    
    return_value = True
    
    with arcpy.da.SearchCursor(input_features, "SHAPE@LENGTH") as cursor:
        for row in cursor:
            if row[0] > 0:
                return_value = False
                break
    
    return return_value
        
if __name__ == "__main__":
    
    hostedgp = None
    start_time = time.time()
    begin_time = start_time
    tool_limits = {}
    try:
        hostedgp = agolgp.HostedGP(9, 8)
        output_hosted_name = hostedgp.GetOutputName(8)
        # check credits balance
        aolutils.checkForCredits(TASK_NAME)
        #check publishing privilege
        aolutils.checkPublishingPrivilege(hostedgp, output_hosted_name)
        
        #Get the input parameters
        hosted_analysis_layer, analysis_layer_count = aolutils.getHostedLayerX(hostedgp, "analysisLayer", 0,
                                                                               use_as_soap_input=True)
        hosted_near_locations_layer, near_locations_layer_count = aolutils.getHostedLayerX(hostedgp, "nearLayer", 1,
                                                                                           use_as_soap_input=True)
        start_time = aolutils.AddTimerMessage(start_time,  "Read hosted input")
        arcpy.AddMessage("analysis layer count: {}".format(analysis_layer_count))
        arcpy.AddMessage("near layer count: {}".format(near_locations_layer_count))  
        #For straight line, ensure we can support keyword in any case.
        measurement_method = arcpy.GetParameterAsText(2)
        if measurement_method.upper() == "STRAIGHTLINE":
            measurement_method = "StraightLine"

        str_max_count = arcpy.GetParameterAsText(3)
        str_search_cutoff = arcpy.GetParameterAsText(4)
        search_cutoff_units = arcpy.GetParameterAsText(5)
        time_of_day = arcpy.GetParameter(6)
        time_zone_for_time_of_day = arcpy.GetParameterAsText(7)
        
        context = arcpy.GetParameterAsText(9)
        include_route_layers = arcpy.GetParameter(10)

        point_barrier_layer, point_barrier_count = aolutils.getHostedLayerX(hostedgp, "pointBarrierLayer", 11, False,
                                                                            use_as_soap_input=True)
        line_barrier_layer, line_barrier_count = aolutils.getHostedLayerX(hostedgp, "lineBarrierLayer", 12, False,
                                                                          use_as_soap_input=True)
        polygon_barrier_layer, polygon_barrier_count = aolutils.getHostedLayerX(hostedgp, "polygonBarrierLayer", 13,
                                                                                False, use_as_soap_input=True)
        # Do not pass barrier layer if their count is zero. For example, there might not be any barrier features within
        # the map extent and in this case the barrier layer has all the barrier features which is not what we want to
        # use in the analysis.
        point_barrier_layer = point_barrier_layer if point_barrier_count else None
        line_barrier_layer = line_barrier_layer if line_barrier_count else None
        polygon_barrier_layer = polygon_barrier_layer if polygon_barrier_count else None
        point_barrier_layer = networkanalysis.LayerInfo(point_barrier_layer)
        line_barrier_layer = networkanalysis.LayerInfo(line_barrier_layer)
        polygon_barrier_layer = networkanalysis.LayerInfo(polygon_barrier_layer)

        #convert max_count and search_cutoff to a number
        #For max count we currently support only 100.
        search_cutoff = networkanalysis.str_to_float(str_search_cutoff) if str_search_cutoff else INFINITY
        max_count = networkanalysis.str_to_float(str_max_count) if str_max_count else INFINITY

        #Check if the user has premium:user:networkanalysis privilege
        if measurement_method != "StraightLine":
            if not aolutils.checkPrivilege(networkanalysis.NETWORK_ANALYSIS_PRIVILEGE, hostedgp):
                aolutils.AddErrorCode(100111, networkanalysis.ERROR_CODES.get(100111, ""))
                raise arcpy.ExecuteError

            #Fail if including route layers and requesting feature collection output
            if include_route_layers and not output_hosted_name.createService:
                aolutils.AddErrorCode(100223, ERROR_CODES.get(100223, ""))
                raise arcpy.ExecuteError
            
            if not output_hosted_name.createService:
                if max_count != INFINITY:
                    num_routes = min(max_count, near_locations_layer_count) * analysis_layer_count
                else:
                    num_routes = min(near_locations_layer_count, 100) * analysis_layer_count
                if num_routes > 9999:
                    aolutils.AddErrorCode(100291, ERROR_CODES[100291])
                    raise arcpy.ExecuteError
        elif not output_hosted_name.createService:
            if (near_locations_layer_count + analysis_layer_count) > 9999:
                aolutils.AddErrorCode(100291, ERROR_CODES[100291])
                raise arcpy.ExecuteError

        #update search cutoff units based on the user profile if search cutoff units are not specified
        if not search_cutoff_units:
            search_cutoff_units = aolutils.getUnits(hostedgp, False)

        #Determine if routingUtilities is available to check service limits
        helper_services = json.loads(hostedgp.GetHelperServices())
        limit_checker_service_available = True if "routingUtilities" in helper_services else False
        
        #Call the find nearest function
        #Travel_mode_name is set inside the function
        travel_mode_name = "Line Distance"

        outputs = find_nearest(hosted_analysis_layer,hosted_near_locations_layer, measurement_method, max_count,
                               search_cutoff, search_cutoff_units, time_of_day, context, time_zone_for_time_of_day,
                               limit_checker_service_available, include_route_layers, point_barrier_layer,
                               line_barrier_layer, polygon_barrier_layer)

        ##Save outputs as a feature collection or a feature service
        #if all(outputs):
        #    save_outputs(hostedgp, hosted_near_locations_layer, outputs, output_hosted_name)
        #else:
        #    arcpy.SetParameter(10, "")
        #    arcpy.SetParameter(11, "")
        save_outputs(hostedgp, outputs, output_hosted_name, measurement_method, search_cutoff_units,
                     is_measurement_method_time_based, travel_mode_name, include_route_layers, time_of_day)

        #Reset the timer as find_nearest and save_outputs function do their own timing.
        start_time = time.time()
        #report metering info
        analysis_layer_shape_type = hosted_analysis_layer.shapeType
        near_locations_layer_shape_type = hosted_near_locations_layer.shapeType
        #Custom travel mode has a value of 0
        measurement_method_values = {
            "STRAIGHTLINE" : 1,
            "DRIVINGTIME" : 2,
            "DRIVINGDISTANCE" : 3,
            "TRUCKINGTIME" : 4,
            "TRUCKINGDISTANCE" : 5,
            "WALKINGTIME" : 6,
            "WALKINGDISTANCE" : 7,
        }
        search_cutoff_units_values = {
            "Miles" : 1,
            "Yards" : 2,
            "Feet" : 3,
            "Meters" : 4,
            "Kilometers" : 5,
            "NauticalMiles": 6
        }
        #numObjects is the total count of features in analysisLayer and nearLayer after extent filter is applied
        num_objects = analysis_layer_count + near_locations_layer_count
        #cost_units is 0 if using driving time or driving distance as the metering is done on remote server
        cost_units = 0.001 if measurement_method == "StraightLine" else 0
        output_return_type = 2 if output_hosted_name.createService else 1
        time_of_day_value = time.mktime(time_of_day.timetuple()) * 1000 if time_of_day else None
        values = [
            aolutils.GetShapeTypeCode(analysis_layer_shape_type),
            analysis_layer_count,
            aolutils.GetShapeTypeCode(near_locations_layer_shape_type),
            near_locations_layer_count,
            measurement_method_values.get(measurement_method.upper(),0),
            max_count,
            search_cutoff,
            search_cutoff_units_values.get(search_cutoff_units,0),
            time_of_day_value,
            output_return_type,
            int(include_route_layers)
        ]
        aolutils.LogUsageMetering(TASK_NAME, num_objects, cost_units, begin_time, values)
        start_time = aolutils.AddTimerMessage(start_time, "Completed metering")
        #report cost
        paramsDict = {
            "analysisLayer":{
                "count": analysis_layer_count,
                "shapeType":analysis_layer_shape_type
                },
            "nearLayer":{
                "count": near_locations_layer_count,
                "shapeType":near_locations_layer_shape_type
                },
            "measurementType": measurement_method if measurement_method.upper() in measurement_method_values else "CUSTOM",
            "maxCount": max_count,
            "searchCutoff" : search_cutoff,
            "searchCutoffUnits" : search_cutoff_units,
            "timeOfDay": time_of_day_value,
            "includeRouteLayers": include_route_layers,
        }
        aolutils.reportParamsForCost(hostedgp, TASK_NAME, paramsDict)
        start_time = aolutils.AddTimerMessage(start_time, "Completed cost reporting")

    except arcpy.ExecuteError as ex:
        aolutils.AddExecuteErrors(TASK_NAME, list(ERROR_CODES.keys()))

    except SystemExit as ex:
        #Will be raised when the script is being cancelled.
        arcpy.AddMessage("No outputs as script was canceled")

    except Exception as err:
        import traceback
        import sys
        msgs = traceback.format_exception(*sys.exc_info())[1:]
        for msg in msgs:
            arcpy.AddMessage(msg.strip())
        aolutils.AddExceptionError(TASK_NAME, err)
    finally:
        if hostedgp:
            hostedgp.Cleanup()
            aolutils.AddTimerMessage(start_time, "Performed cleanup")

