export const ApplicationExamples = () =>{const examples = [
    {
      title: 'Government Portal',
      description: 'County government portal loading screen',
      content: (<div className="bg-tf-space-black rounded-2xl p-8 text-center border-2 border-primary/30 relative overflow-hidden"><div className="absolute inset-0 bg-tf-gradient-glow opacity-20" /><div className="relative z-10"><div className="w-20 h-20 bg-tf-gradient-primary rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-tf-glow"><span className="text-2xl font-arial-black font-black text-primary-foreground">TF</span></div><h3 className="text-2xl font-bold text-white mb-2">TerraFusion</h3><p className="text-muted-foreground mb-1">Infrastructure Intelligence, Infinite Scale</p><p className="text-primary text-sm">Government. Simplified.</p></div></div>),},
    {title: 'Staff Authentication',
      description: 'Government employee login interface',
      content: (<div className="bg-tf-space-black rounded-2xl p-8 text-center border-2 border-primary/30"><div className="w-16 h-16 bg-tf-gradient-primary rounded-xl flex items-center justify-center mx-auto mb-6"><span className="text-xl font-arial-black font-black text-primary-foreground">TF</span></div><h3 className="text-xl font-semibold text-white mb-2">County Staff Portal</h3><p className="text-muted-foreground text-sm mb-6">Welcome to Government. Transcended.</p><button className="w-full py-3 px-6 bg-tf-gradient-primary text-primary-foreground rounded-xl font-semibold hover:shadow-tf-glow transition-all">Sign In with TerraFusion</button></div>),},
    {
      title: 'County Operations Dashboard',
      description: 'Municipal management and workflow platform',
      content: (<div className="bg-tf-space-black rounded-2xl p-6 border-2 border-primary/30"><div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 bg-tf-gradient-primary rounded-xl flex items-center justify-center"><span className="text-lg font-arial-black font-black text-primary-foreground">TF</span></div><div><h3 className="text-lg font-semibold text-white">County Operations</h3><p className="text-sm text-muted-foreground">Tactical Municipal Excellence</p></div></div><div className="flex gap-2 flex-wrap">{['Property', 'Permits', 'Tax', 'GIS', 'Workflows'].map(tag => (<span
                key={tag}
                className="px-3 py-1 bg-primary/20 text-primary text-xs rounded-full border border-primary/30"
              >{tag}</span>))}</div></div>),
    },
    {title: 'Government Website',
      description: 'Official county website navigation',
      content: (<div className="bg-tf-gradient-primary rounded-2xl p-4 border border-primary/30"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-primary-foreground/20 rounded-xl flex items-center justify-center backdrop-blur-sm"><span className="text-sm font-arial-black font-black text-primary-foreground">TF</span></div><div><span className="text-primary-foreground font-semibold">County Government</span><div className="text-xs text-primary-foreground/80">Government. Simplified.</div></div></div><div className="flex gap-4 text-sm text-primary-foreground/80"><span>Services</span><span>Permits</span><span>Portal</span></div></div></div>),},
    {title: 'Government Business Cards',
      description: 'Official county staff materials',
      content: (<div className="bg-tf-dark-bg rounded-2xl p-6 border border-primary/50"><div className="flex items-start justify-between mb-4"><div className="w-12 h-12 bg-tf-gradient-primary rounded-lg flex items-center justify-center"><span className="text-lg font-arial-black font-black text-primary-foreground">TF</span></div><div className="text-right"><div className="text-xs text-muted-foreground">county.gov</div></div></div><div><h4 className="text-white font-semibold">Jane Smith</h4><p className="text-sm text-muted-foreground">County Administrator</p><p className="text-xs text-primary mt-2">jane@county.gov</p></div></div>),},
    {title: 'Official Government Social',
      description: 'County social media and communications',
      content: (<div className="bg-tf-space-black rounded-2xl p-6 text-center border border-primary/30"><div className="w-16 h-16 bg-tf-gradient-primary rounded-full flex items-center justify-center mx-auto mb-4 shadow-tf-glow"><span className="text-xl font-arial-black font-black text-primary-foreground">TF</span></div><div className="text-white font-semibold mb-1">@CountyGov</div><div className="text-xs text-muted-foreground mb-2">Government. Transcended.</div><div className="flex justify-center gap-4 mt-4 text-xs text-muted-foreground"><span>12K Citizens</span><span>24/7 Service</span></div></div>),},
  ];

  return (<section className="py-20"><div className="container mx-auto px-4"><div className="flex items-center mb-12"><div className="w-2 h-16 bg-tf-gradient-primary rounded-full shadow-tf-cyan mr-6" /><h2 className="text-5xl font-bold text-white">Real Application Examples</h2></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{examples.map((example, index) => (<div key={index} className="tf-card rounded-3xl p-8 group"><h3 className="text-xl font-semibold text-white mb-3">{example.title}</h3><p className="text-muted-foreground text-sm mb-6">{example.description}</p><div className="transition-transform duration-300 group-hover:scale-105">{example.content}</div></div>))}</div>{/* Usage Guidelines */}<div className="mt-16 tf-card rounded-3xl p-10"><h3 className="text-2xl font-bold text-white mb-8 text-center">Implementation Guidelines</h3><div className="grid grid-cols-1 lg:grid-cols-2 gap-8"><div><h4 className="text-lg font-semibold text-primary mb-4">Logo Placement</h4><ul className="space-y-3 text-muted-foreground"><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Maintain minimum clear space of 0.5x logo width on all sides</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Use appropriate variant based on background contrast</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Never stretch, skew, or rotate the logo</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Ensure logo remains readable at minimum size of 24px</li></ul></div><div><h4 className="text-lg font-semibold text-primary mb-4">Brand Consistency</h4><ul className="space-y-3 text-muted-foreground"><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Always use official color values for brand elements</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Apply consistent spacing and typography hierarchy</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Use Inter font family for all brand communications</li><li className="flex items-start"><span className="text-primary mr-3 mt-1 text-xs">▶</span>Include "AI That Understands Land" tagline when appropriate</li></ul></div></div></div></div></section>
  );
};
