CREATE TABLE [dbo].[pacs_system] (
    [id]                                         INT             NOT NULL,
    [tax_yr]                                     NUMERIC (4)     NOT NULL,
    [appr_yr]                                    NUMERIC (4)     NULL,
    [system_type]                                CHAR (1)        NULL,
    [rounding_factor]                            NUMERIC (4)     NULL,
    [rounding_income_factor]                     NUMERIC (4)     NULL,
    [receipt_copies]                             INT             NULL,
    [first_yr_to_supp]                           NUMERIC (4)     NULL,
    [validator_line_one]                         VARCHAR (50)    NULL,
    [validator_line_two]                         VARCHAR (50)    NULL,
    [validator_line_three]                       VARCHAR (50)    NULL,
    [validator_line_four]                        VARCHAR (50)    NULL,
    [validator_line_seven]                       VARCHAR (50)    NULL,
    [validator_line_eight]                       VARCHAR (50)    NULL,
    [validator_line_nine]                        VARCHAR (50)    NULL,
    [geo_id_display_option]                      CHAR (1)        NULL,
    [phone_num]                                  VARCHAR (20)    NULL,
    [fax_num]                                    VARCHAR (20)    NULL,
    [version]                                    VARCHAR (20)    NULL,
    [oil_well_adj_acres]                         NUMERIC (14, 4) NULL,
    [apply_land_mass_factor]                     CHAR (1)        NULL,
    [apply_imprv_mass_factor]                    CHAR (1)        NULL,
    [distribution_path]                          VARCHAR (100)   NULL,
    [pacsappr_version]                           VARCHAR (100)   NULL,
    [pacscol_version]                            VARCHAR (100)   NULL,
    [confidential_file_as_name]                  VARCHAR (70)    NULL,
    [confidential_first_name]                    VARCHAR (30)    NULL,
    [confidential_last_name]                     VARCHAR (30)    NULL,
    [begin_close_dt]                             DATETIME        NULL,
    [starting_check_num]                         INT             NULL,
    [gis_viewer]                                 CHAR (1)        NULL,
    [gis_viewer_display_labels]                  CHAR (1)        NULL,
    [appr_card_type]                             VARCHAR (15)    NULL,
    [letter_path]                                VARCHAR (255)   NULL,
    [label_printer_name]                         VARCHAR (255)   NULL,
    [face_map_path]                              VARCHAR (255)   NULL,
    [face_map_field]                             VARCHAR (50)    NOT NULL,
    [cold_location]                              VARCHAR (255)   NULL,
    [sl_type]                                    CHAR (5)        NULL,
    [sl_ratio_type]                              CHAR (5)        NULL,
    [sl_finance_type]                            CHAR (5)        NULL,
    [sl_conf_source]                             VARCHAR (30)    NULL,
    [lease_flag]                                 BIT             NOT NULL,
    [factor_flag]                                CHAR (1)        NULL,
    [client_name]                                VARCHAR (20)    NULL,
    [inq_print_letter_id]                        INT             NULL,
    [heat_ac_code_attribute_id]                  INT             NOT NULL,
    [penpad_password]                            VARCHAR (32)    NULL,
    [export_path]                                VARCHAR (255)   NULL,
    [future_yr]                                  NUMERIC (4)     NULL,
    [shared_cad_valuation]                       CHAR (1)        NULL,
    [street_default]                             CHAR (1)        NULL,
    [pp_waive_penalty_percent]                   NUMERIC (5, 2)  NULL,
    [pp_waive_amount_threshold]                  NUMERIC (14, 2) NULL,
    [so_type]                                    CHAR (10)       NULL,
    [so_method]                                  CHAR (5)        NULL,
    [so_class]                                   CHAR (10)       NULL,
    [sales_ratio_report_ui_mode]                 INT             NULL,
    [pro_notice_hearing_letter_single]           INT             NULL,
    [pro_notice_hearing_letter_multi]            INT             NULL,
    [pro_arb_certified_mailer_agent]             INT             NULL,
    [pro_arb_certified_mailer_owner]             INT             NULL,
    [pro_warn_more_protests_opened]              CHAR (1)        NULL,
    [arb_mass_prop_entry_def_search]             INT             NULL,
    [sketch_default_font]                        INT             NULL,
    [sketch_separator_type]                      CHAR (1)        NULL,
    [sketch_center_label]                        CHAR (1)        NULL,
    [sketch_show_area]                           CHAR (1)        NULL,
    [duplicate_col_warn]                         VARCHAR (100)   NULL,
    [print_appr_card_barcode]                    CHAR (1)        NULL,
    [print_appr_card_sketch]                     CHAR (1)        NULL,
    [sketch_font_name]                           VARCHAR (50)    NULL,
    [sketch_auto_pointer]                        CHAR (1)        NULL,
    [set_actual_taxes]                           CHAR (5)        NULL,
    [pp_rendition_penalty_cad_fee_pct]           NUMERIC (5, 2)  NOT NULL,
    [pp_rendition_penalty_letter]                VARCHAR (100)   NULL,
    [use_app_role]                               BIT             NULL,
    [show_pc_good_field]                         CHAR (1)        NULL,
    [cert_roll_rpt_print_refId2]                 CHAR (1)        NULL,
    [bpp_default_segment]                        CHAR (2)        NULL,
    [display_location_id]                        CHAR (2)        NULL,
    [hswiz_set_homesite]                         BIT             NULL,
    [hswiz_sup_cd]                               VARCHAR (10)    NULL,
    [hswiz_sup_desc]                             VARCHAR (500)   NULL,
    [use_penpad_sketch]                          CHAR (1)        NULL,
    [pp_rendition_wizard_delete_prev_yr]         CHAR (1)        NULL,
    [pp_rend_format]                             CHAR (1)        NULL,
    [store_adj_detail_area]                      BIT             NULL,
    [hswiz_update_app_name_enabled]              VARCHAR (1)     NULL,
    [hswiz_update_app_name_setting]              VARCHAR (1)     NULL,
    [bpp_assetmgr_sort]                          VARCHAR (1)     NULL,
    [warn_arb_prot_save]                         CHAR (1)        NULL,
    [display_agent_warning]                      CHAR (1)        NULL,
    [print_inactive_building_permits]            CHAR (1)        NULL,
    [use_timber_78_values]                       BIT             NULL,
    [arb_warn_more_open_protests_on_open]        CHAR (1)        NULL,
    [default_appr_notice_form]                   VARCHAR (25)    NULL,
    [heat_only_code_attribute_id]                INT             NULL,
    [cool_only_code_attribute_id]                INT             NULL,
    [ptd_sale_submission_export_map_number_as]   VARCHAR (25)    NULL,
    [num_bathrooms_code_attribute_id]            INT             NULL,
    [num_bedrooms_code_attribute_id]             INT             NULL,
    [mineral_import_format_file_path]            VARCHAR (255)   NULL,
    [default_tax_statement_form]                 VARCHAR (15)    NULL,
    [default_inquiry_create_year]                NUMERIC (4)     NULL,
    [default_inquiry_search_year]                NUMERIC (4)     NULL,
    [default_protest_create_year]                NUMERIC (4)     NULL,
    [default_protest_search_year]                NUMERIC (4)     NULL,
    [default_arb_system_override]                BIT             NOT NULL,
    [override_ownership_wiz_reset_exemption]     BIT             NULL,
    [auto_add_ov65]                              CHAR (1)        NULL,
    [auto_add_ov65_ignore_reset_exemptions]      BIT             NULL,
    [default_arb_system_inquiry_override]        BIT             NOT NULL,
    [default_arb_system_protest_override]        BIT             NOT NULL,
    [nbhd_cost_calibration_default_target_ratio] NUMERIC (14, 4) NOT NULL,
    [pp_rendition_print_column_format]           BIT             NOT NULL,
    [owner_transfer_do_reset_exemptions_logic]   BIT             NOT NULL,
    [owner_transfer_set_inactivate_agent]        BIT             NOT NULL,
    [supplement_reason_required]                 BIT             NOT NULL,
    [postpone_duedate]                           BIT             NOT NULL,
    CONSTRAINT [CPK_pacs_system] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 90)
);


GO

