import dataclasses
import re
from typing import TYPE_CHECKING, Union, Type

from openpyxl.cell import WriteOnlyCell
from openpyxl.styles import Font, Color
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

from .._logging import get_logger
from ..common import *
from ..conversion.helper import ValueWrapper

logger = get_logger(__name__)

if TYPE_CHECKING:
    from ..conversion.helper import Base, BaseCollection, Collection
    from enum import Enum
    from openpyxl.worksheet._write_only import WriteOnlyWorksheet

__all__ = [
    "Row",
    "Sheet",
    "Book",
    "cell_width",
]

BOLD = Font(bold=True)
NUM_HYPERLINKS = 10_000  # Hook to stop creating hyperlinks per sheet.
PREFIX = "Excel"

# The pixel widths of the ASCII codes, scaled by 256.
# This was programmatically generated by writing each character to Excel and using the "autofit" functionality.
# fmt: off
CHR_WIDTHS = (
    256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256,
    256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256,
    109, 182, 219, 256, 256, 402, 365, 109, 182, 182, 256, 256, 146, 182, 146, 219,
    256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 146, 146, 256, 256, 256, 256,
    475, 329, 292, 292, 329, 256, 256, 329, 329, 146, 182, 292, 219, 438, 365, 365,
    292, 365, 292, 256, 256, 329, 329, 475, 292, 256, 256, 182, 219, 182, 256, 256,
    146, 256, 292, 219, 292, 292, 182, 256, 292, 146, 146, 256, 146, 438, 292, 292,
    292, 292, 182, 219, 182, 292, 256, 402, 256, 256, 219, 182, 256, 182, 256,
)
# fmt: on
MAX_COL_WIDTH = 255  # Maximum column width in Excel


def cell_width(value: str) -> int:
    """Approximates the width of the cell"""
    scale = 256

    if len(value) >= MAX_COL_WIDTH:
        return MAX_COL_WIDTH

    cutoff = MAX_COL_WIDTH * scale
    width = scale * 2  # padding
    for o in map(ord, value):
        if o > 126:
            width += 384  # Default if not ASCII. 384 / 256 => 1.5
        else:
            width += CHR_WIDTHS[o]

        if width >= cutoff:
            break

    return min(MAX_COL_WIDTH, width // scale)


@dataclasses.dataclass
class Hyperlink:
    ref: str = "A1"
    sheet: str = None

    def add_hyperlink(self, cell, **kwargs):
        # Excel only support ~2^16 hyperlinks, so users cannot opt in to more.
        if len(cell.parent._hyperlinks) >= min(NUM_HYPERLINKS, 65_530):
            return

        sheet = self.sheet or cell.parent.title
        cell.hyperlink = f"#{sheet!r}!{self.ref}"

        # Blue with underline, looks like a clickable link.
        cell.font = Font(underline="single", color=Color(rgb="000000FF"), **kwargs)

    @classmethod
    def from_row_col(cls, sheet: str, row: int, col: int):
        return cls(f"{get_column_letter(col)}{row}", sheet)


class Cell:
    def __init__(
        self,
        value=None,
        font: Font = None,
        hyperlink: Hyperlink = None,
        number_format: str = None,
    ):
        self.value = value
        self.font = font
        self.hyperlink = hyperlink
        self.number_format = number_format

    def __repr__(self):
        return f"<Cell {self.value}>"

    def __str__(self):
        return str(self.value)


class Row:
    def __init__(self, values=None, is_header: bool = False):
        self.values = list(values or [])
        self.size = len(values) if values else 0
        self.is_header = is_header

        self.row_num: int = -1

    def __repr__(self):
        return f"<Row {self.row_num} ({self.size})>"

    def as_row(self, sheet):
        for val in self.values:
            if isinstance(val, Cell):
                cell = WriteOnlyCell(sheet, val.value)
                if font := val.font:
                    cell.font = font
                if hyper := val.hyperlink:
                    hyper.add_hyperlink(cell, bold=cell.font.bold)
                if num_format := val.number_format:
                    cell.number_format = num_format

                yield cell
            else:
                yield val


@dataclasses.dataclass
class TableRef:
    name: str
    start: int
    length: int
    width: int
    end: int = dataclasses.field(init=False)

    def __post_init__(self):
        self.end = self.start + self.length

    def ref(self) -> str:
        return f"A{self.start}:{get_column_letter(self.width)}{self.end}"

    def as_table(self, sheet: "Sheet"):
        """Converts reference to openpyxl Table"""
        from openpyxl.worksheet.table import Table, TableStyleInfo

        table = Table(
            displayName=self.name,
            ref=self.ref(),
            tableStyleInfo=TableStyleInfo(name="TableStyleLight1", showRowStripes=True),
        )
        # Required for write only worksheets.
        table._initialise_columns()
        for column, val in zip(table.tableColumns, sheet.rows[self.start - 1].values):
            column.name = val

        return table


class Sheet:
    ORDER = "Geodatabase Order"
    KEY = "Key"
    VALUE = "Value"

    def __init__(self, name: str, display: str = None):
        self.display = display or name
        self.name = self._validate_name(name)
        self.rows: list[Row] = []
        self.total: int = 0
        self.widest: int = 0

        self.tables: list[TableRef] = []
        self.enumerations: dict[Type["Enum"], list[str]] = {}

    @staticmethod
    def _validate_name(name: str) -> str:
        """Makes name a valid Excel sheet name"""
        import re

        clean = re.sub(r"[^0-9a-z]+", "_", name, flags=re.IGNORECASE).strip("_")
        if clean.casefold() == "history":
            return f"{clean}_1"
        if len(clean) > 31:
            clean = re.sub(r"[aeiou]", "", clean)
        return clean[:31]

    def __repr__(self):
        return f"<Sheet {self.name!r}>"

    def get_column_dimensions(self):
        width_array = [0] * self.widest
        for row in self.rows:
            # Header rows get extra width to account for the filter dropdown.
            extra_width = 2 if row.is_header else 0
            for i, val in enumerate(row.values):
                width_array[i] = max(width_array[i], cell_width(str(val)) + extra_width)

        for i, width in enumerate(width_array, 1):
            yield get_column_letter(i), min(width, 100)

    def add_rows(self, *rows: Row):
        """Adds rows to sheet"""
        for row in rows:
            self.total += 1
            row.row_num = self.total
            self.widest = max(self.widest, len(row.values))
        self.rows.extend(rows)

    def add_empty_rows(self, num: int):
        self.add_rows(*(Row() for _ in range(num)))

    def add_collection(
        self,
        table: Union["Base", "Collection"],
        transpose: bool = False,
        add_order: bool = True,
        nav_link: int = None,
        add_label: bool = True,
    ):
        """Adds collection contents to sheet and creates Excel Table"""
        from ..conversion.helper import BaseCollection, MockCollection

        if not isinstance(table, (BaseCollection, MockCollection)):
            table = BaseCollection(table.__class__, [table])

        if transpose:
            header = [self.KEY, self.VALUE]
        else:
            header = table.header
            if add_order:
                header = [*header, self.ORDER]

        if add_label:
            if table.link:
                label = ValueWrapper(table.class_name(), anchor=table.link)
            else:
                label = Cell(table.class_name(), font=BOLD)
            self.add_rows(Row([label]))
        else:
            label = None

        self.add_rows(
            Row(header, is_header=True),
        )
        if label and nav_link is not None:
            # Overwrite the placeholder and link between them.
            self.rows[nav_link] = Row([nav := Cell(table.class_name(), font=BOLD)])
            label.hyperlink = Hyperlink(ref=f"A{nav_link + 1}")  # Offset 1 for TOC
            nav.hyperlink = Hyperlink(ref=f"A{self.total}")

        rows = table.to_list()
        row_count = len(rows)

        # Replace any non character with underscore.
        clean = re.sub(r"[^a-z0-9]+", "_", f"{table.class_name()} {self.name}", flags=re.IGNORECASE).strip("_")
        self.tables.append(ref := TableRef(clean, start=self.total, length=max(row_count, 1), width=len(header)))

        # Add to the running list of enumerations.
        if isinstance(table, BaseCollection):
            for col_idx, h in enumerate(table.cls.HEADER, 1):
                if h.enum:
                    col = get_column_letter(col_idx)
                    self.enumerations.setdefault(h.enum, []).append(f"{col}{ref.start + 1}:{col}{ref.end}")

        if not rows:
            self.add_empty_rows(2)  # 1 for the virtual table and 1 for padding
            return

        if transpose:
            if len(table.header) != row_count:
                rows = rows[0]
            for row in zip(table.header, rows):
                self.add_rows(Row(row))
        else:
            for i, row in enumerate(rows, 1):
                if add_order:
                    row = [*row, i]
                self.add_rows(Row(row))

        self.add_empty_rows(1)


class Book:
    TOC = "TOC"
    LOOKUP = "_Lookup"

    def __init__(self):
        from openpyxl import Workbook

        self.book: Workbook = Workbook(write_only=True)

        self.sheet_lookup: dict[str, Sheet] = {}

    def create_sheet(self, name: str, display: str = None, add_toc: bool = True) -> Sheet:
        sheet = Sheet(name, display)
        if add_toc:
            sheet.add_rows(Row([Cell(self.TOC, hyperlink=Hyperlink(sheet=self.TOC))]))
        self.sheet_lookup[name] = sheet
        return sheet

    def _build_anchors(self):
        # Walk all cells to extract "anchors". These become hyperlink targets.
        anchors = {}
        for sheet_name, sheet in self.sheet_lookup.items():
            anchors[((sheet_name, None),)] = (sheet_name, 1, 1)
            for row in sheet.rows:
                for j, val in enumerate(row.values, 1):
                    if not isinstance(val, ValueWrapper):
                        continue

                    if anchor := val.anchor:
                        # If the anchor only has a single level, then we redirect it to 1,1
                        if len(anchor) == 1:
                            rc = 1, 1
                        else:
                            rc = row.row_num, j
                        anchors[tuple(map(lower_link, anchor))] = sheet.name, *rc

        return anchors

    def enrich_cells(self):
        """Creates hyperlinks between cells"""
        anchors = self._build_anchors()

        for sheet in self.sheet_lookup.values():
            for row in sheet.rows:
                for i, val in enumerate(row.values):
                    if isinstance(val, ValueWrapper):
                        # Replace ValueWrapper with Cell.
                        row.values[i] = (
                            cell := Cell(
                                val.value,
                                number_format=val.format,
                            )
                        )

                        if (link := val.link) and (ref := anchors.get(tuple(map(lower_link, link)))):
                            cell.hyperlink = Hyperlink.from_row_col(*ref)

    def create_lookup_sheet(self) -> dict[Type["Enum"], DataValidation]:
        """Converts enums to DataValidation"""
        from itertools import zip_longest

        unique_enums = set()
        for sheet in self.sheet_lookup.values():
            unique_enums.update(sheet.enumerations)

        if not unique_enums:
            return {}

        sheet: WriteOnlyWorksheet = self.book.create_sheet(self.LOOKUP)
        sheet.sheet_state = "hidden"

        # Sort for determinism and transpose so that lookups are vertical.
        all_enums = sorted(unique_enums, key=lambda f: f.__name__)
        sheet.append(e.__name__ for e in all_enums)
        for row in zip_longest(*([e.value for e in enum] for enum in all_enums), fillvalue=None):
            sheet.append(row)

        # Create DataValidation for each enum.
        lookup = {}
        for col_idx, enum in enumerate(all_enums, 1):
            col = get_column_letter(col_idx)
            dv = DataValidation(
                type="list",
                formula1=f"{self.LOOKUP!r}!${col}${2}:${col}${len(enum) + 1}",
                showErrorMessage=False,
                showInputMessage=False,
                showDropDown=False,  # False here actually means to show the dropdown
            )
            lookup[enum] = dv

        return lookup

    def save(self, path):
        from copy import deepcopy
        import warnings

        validation = self.create_lookup_sheet()
        self.enrich_cells()

        with logger.timing(function=PREFIX, code="WritingSheets"):
            for sheet in self.sheet_lookup.values():
                with logger.timing(sheet.name, function=PREFIX, code="WritingSheet"):
                    worksheet: "WriteOnlyWorksheet" = self.book.create_sheet(sheet.name)

                    for enum, refs in sheet.enumerations.items():
                        worksheet.data_validations.append(dv := deepcopy(validation[enum]))
                        for ref in refs:
                            dv.add(ref)

                    for col, width in sheet.get_column_dimensions():
                        worksheet.column_dimensions[col].width = width

                    for row in sheet.rows:
                        worksheet.append(row.as_row(worksheet))

                    if sheet.tables:
                        with warnings.catch_warnings():  # openpyxl always warns about column initialization.
                            warnings.simplefilter(action="ignore", category=UserWarning)
                            for ref in sheet.tables:
                                worksheet.add_table(ref.as_table(sheet))

                    worksheet.close()  # Free resources

        with logger.timing(function=PREFIX, code="SavingWorkbook"):
            self.book.save(path)
