import {TerraFusionHero} from '@/components/TerraFusionHero';
import {LogoShowcase} from '@/components/LogoShowcase';
import {ColorPalette} from '@/components/ColorPalette';
import {BrandPillars} from '@/components/BrandPillars';
import {ApplicationExamples} from '@/components/ApplicationExamples';
import {DownloadSection} from '@/components/DownloadSection';
import {MessagingGuidelines} from '@/components/MessagingGuidelines';

const Index = () =>{
  return (<div className="min-h-screen">{/* Navigation */}<nav className="relative z-50 border-b border-primary/20 bg-tf-space-black/90 backdrop-blur-sm"><div className="container mx-auto px-4 py-4"><div className="flex items-center justify-between"><div className="flex items-center gap-4"><div className="w-10 h-10 bg-tf-gradient-primary rounded-xl flex items-center justify-center shadow-tf-cyan"><span className="text-sm font-arial-black font-black text-primary-foreground">TF</span></div><div><h1 className="text-white font-semibold">TerraFusion Brand Kit</h1><p className="text-xs text-muted-foreground">Government Infrastructure Intelligence</p></div></div><div className="hidden md:flex items-center gap-6 text-sm text-muted-foreground"><a href="#logos" className="hover:text-primary transition-colors">Logos</a><a href="#pillars" className="hover:text-primary transition-colors">Brand Pillars</a><a href="#messaging" className="hover:text-primary transition-colors">Messaging</a><a href="#colors" className="hover:text-primary transition-colors">Colors</a><a href="#examples" className="hover:text-primary transition-colors">Examples</a><a href="#download" className="hover:text-primary transition-colors">Download</a></div></div></div></nav>{/* Hero Section */}<TerraFusionHero />{/* Excellence Banner */}<div className="bg-tf-gradient-primary text-primary-foreground py-3 text-center font-semibold text-sm relative overflow-hidden"><div className="absolute inset-0 bg-tf-gradient-glow opacity-30" /><div className="relative z-10">🏛️ Tactical Municipal Excellence • Infrastructure Intelligence, Infinite Scale</div></div>{/* Logo System */}<div id="logos"><LogoShowcase /></div>{/* Brand Pillars */}<div id="pillars"><BrandPillars /></div>{/* Messaging Guidelines */}<div id="messaging"><MessagingGuidelines /></div>{/* Color Palette */}<div id="colors"><ColorPalette /></div>{/* Application Examples */}<div id="examples"><ApplicationExamples /></div>{/* Download Section */}<div id="download"><DownloadSection /></div>{/* Footer */}<footer className="bg-tf-space-black py-12 border-t border-primary/20"><div className="container mx-auto px-4 text-center"><div className="flex justify-center mb-6"><div className="w-16 h-16 bg-tf-gradient-primary rounded-2xl flex items-center justify-center shadow-tf-glow"><span className="text-2xl font-arial-black font-black text-primary-foreground">TF</span></div></div><h3 className="text-2xl font-bold text-white mb-2">TerraFusion</h3><p className="text-muted-foreground mb-2">Infrastructure Intelligence, Infinite Scale</p><p className="text-primary text-sm mb-6">Government. Simplified.</p><div className="flex justify-center gap-8 text-sm text-muted-foreground mb-8"><a href="#" className="hover:text-primary transition-colors">Brand Guidelines</a><a href="#" className="hover:text-primary transition-colors">Government Assets</a><a href="#" className="hover:text-primary transition-colors">Municipal Support</a><a
              href="mailto:support@terrafusion.ai"
              className="hover:text-primary transition-colors"
            >Contact Team</a></div><div className="text-xs text-muted-foreground">© 2024 TerraFusion. Infrastructure Intelligence for Government. All brand assets are
            proprietary and protected.</div></div></footer></div>
  );
};

export default Index;
