CREATE TABLE [dbo].[AppraisalExportBalanceSheet] (
    [source]              VARCHAR (6)  NOT NULL,
    [entity_id]           INT          NOT NULL,
    [prop_count]          NUMERIC (38) NULL,
    [land_hstd_val]       NUMERIC (38) NULL,
    [land_non_hstd_val]   NUMERIC (38) NULL,
    [imprv_hstd_val]      NUMERIC (38) NULL,
    [imprv_non_hstd_val]  NUMERIC (38) NULL,
    [personal_prop_count] NUMERIC (38) NULL,
    [personal_val]        NUMERIC (38) NULL,
    [mineral_prop_count]  NUMERIC (38) NULL,
    [mineral_val]         NUMERIC (38) NULL,
    [auto_prop_count]     NUMERIC (38) NULL,
    [auto_val]            NUMERIC (38) NULL,
    [ag_market]           NUMERIC (38) NULL,
    [timber_market]       NUMERIC (38) NULL,
    [ag_use]              NUMERIC (38) NULL,
    [timber_use]          NUMERIC (38) NULL,
    [hs_count]            INT          NOT NULL,
    [hs_local_amt]        NUMERIC (14) NULL,
    [hs_state_amt]        NUMERIC (14) NULL,
    [dv_count]            INT          NOT NULL,
    [dv_amt]              NUMERIC (14) NULL,
    [dp_count]            INT          NOT NULL,
    [dp_amt]              NUMERIC (14) NULL,
    [ex_count]            INT          NOT NULL,
    [ex_amt]              NUMERIC (14) NULL,
    [ov65_count]          INT          NOT NULL,
    [ov65_amt]            NUMERIC (14) NULL,
    [ab_count]            INT          NOT NULL,
    [ab_amt]              NUMERIC (14) NULL,
    [fr_count]            INT          NOT NULL,
    [fr_amt]              NUMERIC (14) NULL,
    [pc_count]            INT          NOT NULL,
    [pc_amt]              NUMERIC (14) NULL,
    [ex366_count]         INT          NOT NULL,
    [ex366_amt]           NUMERIC (14) NULL,
    [ht_count]            INT          NOT NULL,
    [ht_amt]              NUMERIC (14) NULL,
    [so_count]            INT          NOT NULL,
    [so_amt]              NUMERIC (14) NULL,
    [ch_count]            INT          NOT NULL,
    [ch_amt]              NUMERIC (14) NULL,
    [dataset_id]          BIGINT       NOT NULL
);


GO

