CREATE TABLE [dbo].[appr_notice_selection_criteria] (
    [notice_yr]                      NUMERIC (4)  NOT NULL,
    [notice_num]                     INT          NOT NULL,
    [create_dt]                      DATETIME     NULL,
    [print_dt]                       DATETIME     NULL,
    [created_by]                     INT          NULL,
    [printed_by]                     INT          NULL,
    [use_19a]                        CHAR (1)     NULL,
    [use_19i]                        CHAR (1)     NULL,
    [real_option]                    CHAR (1)     NULL,
    [personal_option]                CHAR (1)     NULL,
    [mineral_option]                 CHAR (1)     NULL,
    [mobile_option]                  CHAR (1)     NULL,
    [auto_option]                    CHAR (1)     NULL,
    [shared_prop_option]             CHAR (1)     NULL,
    [use_mkt_19a]                    CHAR (1)     NULL,
    [use_assd_19a]                   CHAR (1)     NULL,
    [use_value_inc_greater_than_19a] CHAR (1)     NULL,
    [value_inc_greater_than_19a]     NUMERIC (14) NULL,
    [use_value_decr_less_than_19a]   CHAR (1)     NULL,
    [value_decr_less_than_19a]       NUMERIC (14) NULL,
    [use_include_code_19a]           CHAR (1)     NULL,
    [use_include_code_19ac]          CHAR (1)     NULL,
    [use_exclude_code_X19a]          CHAR (1)     NULL,
    [use_include_props_w_rend_19a]   CHAR (1)     NULL,
    [rend_19a_option]                CHAR (5)     NULL,
    [use_new_prop_19a]               CHAR (1)     NULL,
    [use_last_appr_year_19i]         CHAR (1)     NULL,
    [last_appr_year_19i]             NUMERIC (4)  NULL,
    [use_last_owner_change_19i]      CHAR (1)     NULL,
    [last_owner_change_date_19i]     DATETIME     NULL,
    [use_include_code_19i]           CHAR (1)     NULL,
    [use_include_code_19ic]          CHAR (1)     NULL,
    [use_exclude_code_X19i]          CHAR (1)     NULL,
    [notice_line1]                   VARCHAR (60) NULL,
    [notice_line2]                   VARCHAR (60) NULL,
    [notice_line3]                   VARCHAR (60) NULL,
    [arb_hearing_dt]                 DATETIME     NULL,
    [arb_protest_due_dt]             DATETIME     NULL,
    [arb_location]                   VARCHAR (45) NULL,
    [print_prop_id_19a]              CHAR (1)     NULL,
    [print_prior_year_19a]           CHAR (1)     NULL,
    [print_appraiser_19a]            CHAR (1)     NULL,
    [print_tax_due_19a]              CHAR (1)     NULL,
    [print_land_imprv_19i]           CHAR (1)     NULL,
    [print_freeze_19i]               CHAR (1)     NULL,
    [print_prior_year_19i]           CHAR (1)     NULL,
    [print_appraiser_19i]            CHAR (1)     NULL,
    [sup_num]                        INT          NULL,
    [sup_yr]                         NUMERIC (4)  NULL,
    [print_hs_cap_value_19a]         CHAR (1)     NULL,
    [print_freeze_year_19a]          CHAR (1)     NULL,
    [print_id_type_19a]              INT          NULL,
    [use_special_group_selection]    CHAR (1)     NULL,
    [print_electronic_notices]       CHAR (1)     NULL,
    [use_group_codes_list]           CHAR (1)     NULL,
    CONSTRAINT [CPK_appr_notice_selection_criteria] PRIMARY KEY CLUSTERED ([notice_yr] ASC, [notice_num] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [CFK_appr_notice_selection_criteria_notice_yr] FOREIGN KEY ([notice_yr]) REFERENCES [dbo].[appr_notice_config_maint] ([notice_yr])
);


GO

