CREATE TABLE [dbo].[state_reviewer_export] (
    [pacs_user_id]            INT           NOT NULL,
    [isd_cd]                  VARCHAR (5)   NULL,
    [cad_account_number]      VARCHAR (12)  NULL,
    [state_category_code]     VARCHAR (5)   NULL,
    [sale_price]              VARCHAR (40)  NULL,
    [sale_date]               VARCHAR (10)  NULL,
    [sl_class_cd]             VARCHAR (10)  NULL,
    [sl_type_cd]              VARCHAR (5)   NULL,
    [sl_sqft]                 VARCHAR (40)  NULL,
    [sl_land_acres]           VARCHAR (40)  NULL,
    [deed_date]               VARCHAR (10)  NULL,
    [deed_volume]             VARCHAR (20)  NULL,
    [deed_page]               VARCHAR (20)  NULL,
    [deed_number]             VARCHAR (12)  NULL,
    [deed_type]               VARCHAR (5)   NULL,
    [grantee]                 VARCHAR (70)  NULL,
    [grantee_address_line_1]  VARCHAR (60)  NULL,
    [grantee_address_line_2]  VARCHAR (60)  NULL,
    [grantee_address_line_3]  VARCHAR (60)  NULL,
    [grantee_address_city]    VARCHAR (50)  NULL,
    [grantee_address_state]   VARCHAR (50)  NULL,
    [grantee_address_zip]     VARCHAR (50)  NULL,
    [grantee_address_country] VARCHAR (5)   NULL,
    [grantor]                 VARCHAR (70)  NULL,
    [grantor_address_line_1]  VARCHAR (60)  NULL,
    [grantor_address_line_2]  VARCHAR (60)  NULL,
    [grantor_address_line_3]  VARCHAR (60)  NULL,
    [grantor_address_city]    VARCHAR (50)  NULL,
    [grantor_address_state]   VARCHAR (50)  NULL,
    [grantor_address_zip]     VARCHAR (50)  NULL,
    [grantor_address_country] VARCHAR (5)   NULL,
    [legal_description]       VARCHAR (255) NULL,
    [situs]                   VARCHAR (255) NULL,
    [comments]                VARCHAR (500) NULL,
    [land_market_val]         VARCHAR (50)  NULL,
    [imprv_market_val]        VARCHAR (50)  NULL,
    [pers_prop_val]           VARCHAR (50)  NULL,
    [market_val]              VARCHAR (50)  NULL,
    [blg_age]                 VARCHAR (4)   NULL,
    [blg_condition]           VARCHAR (5)   NULL,
    [abs_subdv_cd]            VARCHAR (10)  NULL,
    [map_id]                  VARCHAR (20)  NULL,
    [arb_set_value]           VARCHAR (1)   NULL,
    [partial_complete]        VARCHAR (1)   NULL,
    [lKey]                    INT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [CPK_state_reviewer_export] PRIMARY KEY CLUSTERED ([lKey] ASC) WITH (FILLFACTOR = 100)
);


GO

