CREATE TABLE [dbo].[transfer_appraisal_info_totals] (
    [entity_id]           INT          NOT NULL,
    [entity_cd]           CHAR (5)     NULL,
    [entity_name]         CHAR (70)    NULL,
    [land_hstd_val]       NUMERIC (14) NULL,
    [land_non_hstd_val]   NUMERIC (14) NULL,
    [imprv_hstd_val]      NUMERIC (14) NULL,
    [imprv_non_hstd_val]  NUMERIC (14) NULL,
    [ag_use_val]          NUMERIC (14) NULL,
    [tim_use_val]         NUMERIC (14) NULL,
    [ag_market_val]       NUMERIC (14) NULL,
    [tim_market_val]      NUMERIC (14) NULL,
    [taxable_val]         NUMERIC (14) NULL,
    [mineral_val]         NUMERIC (14) NULL,
    [personal_val]        NUMERIC (14) NULL,
    [auto_val]            NUMERIC (14) NULL,
    [real_mobile_val]     NUMERIC (14) NULL,
    [num_real_mobile]     INT          NULL,
    [num_personal]        INT          NULL,
    [num_mineral]         INT          NULL,
    [num_auto]            INT          NULL,
    [num_records]         INT          NULL,
    [market_value]        NUMERIC (14) NULL,
    [hs_cap_count]        INT          NULL,
    [hs_cap]              NUMERIC (14) NULL,
    [hs_count]            INT          NULL,
    [hs_local_amt]        NUMERIC (14) NULL,
    [hs_state_amt]        NUMERIC (14) NULL,
    [ov65_count]          INT          NULL,
    [ov65_amt]            NUMERIC (14) NULL,
    [dp_count]            INT          NULL,
    [dp_amt]              NUMERIC (14) NULL,
    [dv_count]            INT          NULL,
    [dv_amt]              NUMERIC (14) NULL,
    [ab_count]            INT          NULL,
    [ab_amt]              NUMERIC (14) NULL,
    [fr_count]            INT          NULL,
    [fr_amt]              NUMERIC (14) NULL,
    [pc_count]            INT          NULL,
    [pc_amt]              NUMERIC (14) NULL,
    [ex366_count]         INT          NULL,
    [ex366_amt]           NUMERIC (14) NULL,
    [ht_count]            INT          NULL,
    [ht_amt]              NUMERIC (14) NULL,
    [so_count]            INT          NULL,
    [so_amt]              NUMERIC (14) NULL,
    [ex_count]            INT          NULL,
    [ex_amt]              NUMERIC (14) NULL,
    [ch_count]            INT          NULL,
    [ch_amt]              NUMERIC (14) NULL,
    [ag_late_count]       INT          NULL,
    [ag_late_loss]        NUMERIC (14) NULL,
    [freeport_late_count] INT          NULL,
    [freeport_late_loss]  NUMERIC (14) NULL,
    CONSTRAINT [CPK_transfer_appraisal_info_totals] PRIMARY KEY CLUSTERED ([entity_id] ASC) WITH (FILLFACTOR = 100)
);


GO

