#!/bin/bash
# TerraFusion OS 1.0 - Workspace Environment Setup (Bash/WSL)
# Auto-generated from .workspace.env by set-workspace-env.ps1
# Created: 2025-10-10 09:12:25

# Load environment variables
export TERRAFUSION_AI_MODELS="/mnt/c/users/bsval/terrafusion_os_1.0/backend/ai-models"
export TERRAFUSION_TESTS="/mnt/c/users/bsval/terrafusion_os_1.0/tests"
export TERRAFUSION_LOG_LEVEL="info"
export TERRAFUSION_DOCS="/mnt/c/users/bsval/terrafusion_os_1.0/docs"
export TERRAFUSION_COS="/mnt/c/users/bsval/terrafusion_os_1.0/terrafusion-cos"
export TERRAFUSION_PRO_PLUS="/mnt/c/users/bsval/terrafusion_os_1.0/modules/terrafusion-pro-plus"
export TERRAFUSION_AI_SWARM="/mnt/c/users/bsval/terrafusion_os_1.0/backend/ai-swarm"
export TERRAFUSION_BUILD_TEMP="/mnt/c/users/bsval/terrafusion_os_1.0/.build-temp"
export TERRAFUSION_PATH_SYSTEM_CREATED="2025-10-10"
export TERRAFUSION_NAV_GUIDE="/mnt/c/users/bsval/terrafusion_os_1.0/workspace_navigation_guide.md"
export TERRAFUSION_WATCH="true"
export TERRAFUSION_COMPLETION_SUMMARY="/mnt/c/users/bsval/terrafusion_os_1.0/master_completion_summary.md"
export TERRAFUSION_SCRIPTS="/mnt/c/users/bsval/terrafusion_os_1.0/scripts"
export TERRAFUSION_PATH_SYSTEM_VERSION="1.0.0"
export TERRAFUSION_ROOT="/mnt/c/users/bsval/terrafusion_os_1.0"
export TERRAFUSION_INTEGRATION_TESTS="/mnt/c/users/bsval/terrafusion_os_1.0/tests/integration"
export TERRAFUSION_DEMO="/mnt/c/users/bsval/terrafusion_os_1.0/src/terrafusion-v0-demo"
export TERRAFUSION_WORKSPACE_MAP="/mnt/c/users/bsval/terrafusion_os_1.0/.workspace-map.json"
export TERRAFUSION_VALIDATION="/mnt/c/users/bsval/terrafusion_os_1.0/validation_reports"
export TERRAFUSION_ACTIVE_SYSTEMS="/mnt/c/users/bsval/terrafusion_os_1.0/active_systems.md"
export TERRAFUSION_COMPONENT_REGISTRY="/mnt/c/users/bsval/terrafusion_os_1.0/component-registry.json"
export TERRAFUSION_API_PORT="5000"
export TERRAFUSION_GIS_PORT="3002"
export TERRAFUSION_PRIME_VIEW="/mnt/c/users/bsval/terrafusion_os_1.0/modules/terrafusion-prime-view"
export TERRAFUSION_AI_COMPANION="/mnt/c/users/bsval/terrafusion_os_1.0/ai-workspace-companion"
export TERRAFUSION_DEMO_PORT="3000"
export TERRAFUSION_DEPLOY_SCRIPTS="/mnt/c/users/bsval/terrafusion_os_1.0/deploy"
export TERRAFUSION_MARKETPLACE_PORT="3003"
export TERRAFUSION_PLAYWRIGHT_STATES="/mnt/c/users/bsval/terrafusion_os_1.0/tests/e2e/states"
export TERRAFUSION_POSTGRES_DATA="/mnt/c/users/bsval/terrafusion_os_1.0/postgres"
export TERRAFUSION_API="/mnt/c/users/bsval/terrafusion_os_1.0/backend/terrafusion.api"
export TERRAFUSION_API_UNIFIED="/mnt/c/users/bsval/terrafusion_os_1.0/backend/api-unified"
export TERRAFUSION_ENV="development"
export TERRAFUSION_DIST="/mnt/c/users/bsval/terrafusion_os_1.0/dist"
export TERRAFUSION_PRO_PLUS_PORT="3005"
export TERRAFUSION_GIS="/mnt/c/users/bsval/terrafusion_os_1.0/src/terrafusion-gis"
export TERRAFUSION_DATA="/mnt/c/users/bsval/terrafusion_os_1.0/data"
export TERRAFUSION_E2E_TESTS="/mnt/c/users/bsval/terrafusion_os_1.0/tests/e2e"
export TERRAFUSION_UNIT_TESTS="/mnt/c/users/bsval/terrafusion_os_1.0/tests/unit"
export TERRAFUSION_BENTON_CONFIG="/mnt/c/users/bsval/terrafusion_os_1.0/benton-county-config.json"
export TERRAFUSION_TEST_RESULTS="/mnt/c/users/bsval/terrafusion_os_1.0/tests/test-results"
export NODE_ENV="development"
export TERRAFUSION_NODE_MODULES="/mnt/c/users/bsval/terrafusion_os_1.0/node_modules"
export TERRAFUSION_PATH_SYSTEM_UPDATED="2025-10-10"
export TERRAFUSION_DEBUG="true"
export TERRAFUSION_OWNER="bsval"
export TERRAFUSION_AI_SWARM_COMMANDER="/mnt/c/users/bsval/terrafusion_os_1.0/.ai-swarm-supreme-commander"
export TERRAFUSION_AI_AGENT_CONFIG="/mnt/c/users/bsval/terrafusion_os_1.0/ai-agent-training-config-v2.json"
export TERRAFUSION_COVERAGE="/mnt/c/users/bsval/terrafusion_os_1.0/coverage"
export TERRAFUSION_PRIME_VIEW_PORT="3004"
export TERRAFUSION_AI_SWARM_CONFIG="/mnt/c/users/bsval/terrafusion_os_1.0/ai-swarm-config.json"
export TERRAFUSION_CORE="/mnt/c/users/bsval/terrafusion_os_1.0/backend/terrafusion.core"
export TERRAFUSION_AI_CORE="/mnt/c/users/bsval/terrafusion_os_1.0/.ai"
export TERRAFUSION_ANALYTICS_DB="/mnt/c/users/bsval/terrafusion_os_1.0/analytics.db"
export TERRAFUSION_MCP_CORE="/mnt/c/users/bsval/terrafusion_os_1.0/backend/mcp-core"
export TERRAFUSION_MARKETPLACE="/mnt/c/users/bsval/terrafusion_os_1.0/backend/terrafusion.marketplace"
export TERRAFUSION_SRC="/mnt/c/users/bsval/terrafusion_os_1.0/src"
export TERRAFUSION_FRONTEND="/mnt/c/users/bsval/terrafusion_os_1.0/frontend"
export TERRAFUSION_INFRASTRUCTURE="/mnt/c/users/bsval/terrafusion_os_1.0/backend/terrafusion.infrastructure"
export TERRAFUSION_DASHBOARD_PORT="3001"
export TERRAFUSION_DASHBOARD="/mnt/c/users/bsval/terrafusion_os_1.0/src/terrafusion-dashboard"
export TERRAFUSION_ARCH_DOCS="/mnt/c/users/bsval/terrafusion_os_1.0/docs/architecture"
export TERRAFUSION_VERSION="1.0.0"
export TERRAFUSION_VALIDATION_REPORT="/mnt/c/users/bsval/terrafusion_os_1.0/week_2_validation_report.md"
export TERRAFUSION_BACKEND="/mnt/c/users/bsval/terrafusion_os_1.0/backend"
export TERRAFUSION_API_DOCS="/mnt/c/users/bsval/terrafusion_os_1.0/docs/api"
export TERRAFUSION_SHARED="/mnt/c/users/bsval/terrafusion_os_1.0/terrafusion-shared"
export TERRAFUSION_DESIGN="/mnt/c/users/bsval/terrafusion_os_1.0/design-sync"
export TERRAFUSION_MODULES="/mnt/c/users/bsval/terrafusion_os_1.0/modules"

# Print success message
echo "✅ TerraFusion OS environment variables loaded for Bash/WSL"
echo "📂 Workspace root: $TERRAFUSION_ROOT"
echo ""
echo "Use 'source scripts/set-workspace-env.sh' to load these variables in your shell"
