#!/usr/bin/env python3
"""
SpecLock → OPA Rego Generator (Nuclear Mode)

Structured spec_data_path:
  { "policy": { "routes": [ { method, path, allow_roles: [...] } ] } }

Output:
  security/policies/generated/<lock-id>.rego

Usage:
  python scripts/speclock-opa-gen.py --lock tf.api.foo --out security/policies/generated/tf.api.foo.rego
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

INDEX = Path("docs/spec-lock/INDEX.json")


def _load_json(p: Path) -> Dict[str, Any]:
    return json.loads(p.read_text(encoding="utf-8"))


def _find_lock(lock_id: str) -> Dict[str, Any]:
    idx = _load_json(INDEX)
    for lock in idx.get("locks", []):
        if isinstance(lock, dict) and str(lock.get("id", "")).strip() == lock_id:
            return lock
    raise SystemExit(f"Lock not found: {lock_id}")


def main() -> int:
    print("")
    print("═══════════════════════════════════════════════════════════════")
    print("  TerraFusion SpecLock → OPA Rego Generator")
    print("═══════════════════════════════════════════════════════════════")
    print("")

    ap = argparse.ArgumentParser(description="Generate OPA rego from SpecLock policy rules")
    ap.add_argument("--lock", required=True, help="SpecLock ID")
    ap.add_argument("--out", required=True, help="Output .rego file path")
    ap.add_argument("--package", default="terrafusion.speclock", help="Rego package name")
    args = ap.parse_args()

    if not INDEX.exists():
        print(f"❌ Missing {INDEX}")
        return 1

    try:
        lock = _find_lock(args.lock)
    except SystemExit as e:
        print(f"❌ {e}")
        return 1

    print(f"Lock: {args.lock}")
    print(f"Output: {args.out}")
    print(f"Package: {args.package}")
    print("")

    sdp = str(lock.get("spec_data_path", "") or "").strip()
    if not sdp:
        print("❌ spec_data_path required for OPA policy generation")
        return 1

    sdp_path = Path(sdp)
    if not sdp_path.exists():
        print(f"❌ spec_data_path missing: {sdp}")
        return 1

    print(f"ℹ️  Using spec_data_path: {sdp}")

    try:
        data = _load_json(sdp_path)
    except Exception as e:
        print(f"❌ Failed to parse spec_data_path: {e}")
        return 1

    pol = data.get("policy")
    if not isinstance(pol, dict):
        print("❌ spec_data_path must include { policy: {...} }")
        return 1

    routes = pol.get("routes", [])
    if not isinstance(routes, list):
        routes = []

    # Deterministic output: sort by method+path
    def sort_key(r: Any) -> str:
        if not isinstance(r, dict):
            return ""
        return f"{r.get('method', '')} {r.get('path', '')}"

    routes = sorted([r for r in routes if isinstance(r, dict)], key=sort_key)

    lines: List[str] = []
    lines.append("# GENERATED FILE — do not hand-edit.")
    lines.append(f"# Source lock: {args.lock}")
    lines.append(f"# Generated by: speclock-opa-gen.py")
    lines.append("")
    lines.append(f"package {args.package}")
    lines.append("")
    lines.append("default allow = false")
    lines.append("")
    lines.append("# Input example:")
    lines.append("# { \"method\": \"GET\", \"path\": \"/api/...\", \"roles\": [\"ops\"] }")
    lines.append("")

    rule_count = 0
    for r in routes:
        method = str(r.get("method", "")).strip().upper()
        path = str(r.get("path", "")).strip()
        allow_roles = r.get("allow_roles", [])
        if not method or not path or not isinstance(allow_roles, list):
            continue
        allow_roles = sorted([str(x) for x in allow_roles if str(x).strip()])

        lines.append("allow {")
        lines.append(f'  input.method == "{method}"')
        lines.append(f'  input.path == "{path}"')
        if allow_roles:
            # Any role in input.roles must match allow list
            lines.append("  some r")
            lines.append("  r := input.roles[_]")
            roles_set = ", ".join([json.dumps(x) for x in allow_roles])
            lines.append(f"  r in {{{roles_set}}}")
        lines.append("}")
        lines.append("")
        rule_count += 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print(f"  Rules: {rule_count}")
    print("")
    print(f"✅ Wrote OPA policy: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
