#!/usr/bin/env python3
"""
SpecLock → TypeScript SDK Generator (Nuclear Mode)

Generates TypeScript types from structured spec_data_path:
  { "api": { "dtos": { "Name": { "field": "string|number|boolean|..."} } } }

Output (deterministic):
  sdk/generated/<lock-id>.types.ts

Usage:
  python scripts/speclock-sdk-gen-ts.py --lock tf.api.foo --out sdk/generated/tf.api.foo.types.ts
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict

INDEX = Path("docs/spec-lock/INDEX.json")


def _load_json(p: Path) -> Dict[str, Any]:
    return json.loads(p.read_text(encoding="utf-8"))


def _find_lock(lock_id: str) -> Dict[str, Any]:
    idx = _load_json(INDEX)
    for lock in idx.get("locks", []):
        if isinstance(lock, dict) and str(lock.get("id", "")).strip() == lock_id:
            return lock
    raise SystemExit(f"Lock not found: {lock_id}")


def _ts_type(t: str) -> str:
    """Map spec type to TypeScript type."""
    m = {
        "string": "string",
        "number": "number",
        "boolean": "boolean",
        "guid": "string",
        "iso8601": "string",
        "any": "any",
        "object": "Record<string, unknown>",
        "array": "unknown[]"
    }
    return m.get(t.lower(), "unknown")


def main() -> int:
    print("")
    print("═══════════════════════════════════════════════════════════════")
    print("  TerraFusion SpecLock → TypeScript SDK Generator")
    print("═══════════════════════════════════════════════════════════════")
    print("")

    ap = argparse.ArgumentParser(description="Generate TS types from SpecLock structured DTO definitions")
    ap.add_argument("--lock", required=True, help="SpecLock ID")
    ap.add_argument("--out", required=True, help="Output .ts file path")
    args = ap.parse_args()

    if not INDEX.exists():
        print(f"❌ Missing {INDEX}")
        return 1

    try:
        lock = _find_lock(args.lock)
    except SystemExit as e:
        print(f"❌ {e}")
        return 1

    print(f"Lock: {args.lock}")
    print(f"Output: {args.out}")
    print("")

    sdp = str(lock.get("spec_data_path", "") or "").strip()
    if not sdp:
        print("❌ spec_data_path required for SDK generation")
        return 1

    sdp_path = Path(sdp)
    if not sdp_path.exists():
        print(f"❌ spec_data_path missing: {sdp}")
        return 1

    print(f"ℹ️  Using spec_data_path: {sdp}")

    try:
        data = _load_json(sdp_path)
    except Exception as e:
        print(f"❌ Failed to parse spec_data_path: {e}")
        return 1

    api = data.get("api")
    if not isinstance(api, dict):
        print("❌ spec_data_path must include { api: {...} }")
        return 1

    dtos = api.get("dtos")
    if not isinstance(dtos, dict):
        print("❌ api.dtos must be an object")
        return 1

    lines = []
    lines.append("// GENERATED FILE — do not hand-edit.")
    lines.append(f"// Source lock: {args.lock}")
    lines.append(f"// Generated by: speclock-sdk-gen-ts.py")
    lines.append("")

    for name in sorted(dtos.keys()):
        shape = dtos[name]
        if not isinstance(shape, dict):
            continue
        lines.append(f"export type {name} = {{")
        for field in sorted(shape.keys()):
            t = _ts_type(str(shape[field]))
            lines.append(f"  {field}: {t};")
        lines.append("};")
        lines.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print(f"  Types: {len(dtos)}")
    print("")
    print(f"✅ Wrote TS SDK: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
