#!/usr/bin/env python3
"""
SpecLock → C# DTO Generator (Nuclear Mode)

Generates DTO record types from structured spec_data_path:
  { "api": { "dtos": { "Name": { "field": "string|number|boolean|guid|iso8601" } } } }

Output:
  backend/Generated/SpecLock/<lock-id>.Dtos.g.cs

Usage:
  python scripts/speclock-sdk-gen-cs.py --lock tf.api.foo --out backend/Generated/SpecLock/tf.api.foo.Dtos.g.cs
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict

INDEX = Path("docs/spec-lock/INDEX.json")


def _load_json(p: Path) -> Dict[str, Any]:
    return json.loads(p.read_text(encoding="utf-8"))


def _find_lock(lock_id: str) -> Dict[str, Any]:
    idx = _load_json(INDEX)
    for lock in idx.get("locks", []):
        if isinstance(lock, dict) and str(lock.get("id", "")).strip() == lock_id:
            return lock
    raise SystemExit(f"Lock not found: {lock_id}")


def _cs_type(t: str) -> str:
    """Map spec type to C# type."""
    m = {
        "string": "string",
        "number": "double",
        "boolean": "bool",
        "guid": "Guid",
        "iso8601": "DateTimeOffset",
        "any": "object",
        "object": "Dictionary<string, object>",
        "array": "List<object>"
    }
    return m.get(t.lower(), "object")


def _safe_ident(s: str) -> str:
    """Make string a valid C# identifier."""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", s)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def _pascal_case(s: str) -> str:
    """Convert to PascalCase."""
    parts = re.split(r"[_\-\s]+", s)
    return "".join(p.capitalize() for p in parts if p)


def main() -> int:
    print("")
    print("═══════════════════════════════════════════════════════════════")
    print("  TerraFusion SpecLock → C# DTO Generator")
    print("═══════════════════════════════════════════════════════════════")
    print("")

    ap = argparse.ArgumentParser(description="Generate C# DTOs from SpecLock structured definitions")
    ap.add_argument("--lock", required=True, help="SpecLock ID")
    ap.add_argument("--out", required=True, help="Output .cs file path")
    ap.add_argument("--namespace", default="TerraFusion.Generated.SpecLock", help="C# namespace")
    args = ap.parse_args()

    if not INDEX.exists():
        print(f"❌ Missing {INDEX}")
        return 1

    try:
        lock = _find_lock(args.lock)
    except SystemExit as e:
        print(f"❌ {e}")
        return 1

    print(f"Lock: {args.lock}")
    print(f"Output: {args.out}")
    print(f"Namespace: {args.namespace}")
    print("")

    sdp = str(lock.get("spec_data_path", "") or "").strip()
    if not sdp:
        print("❌ spec_data_path required for SDK generation")
        return 1

    sdp_path = Path(sdp)
    if not sdp_path.exists():
        print(f"❌ spec_data_path missing: {sdp}")
        return 1

    print(f"ℹ️  Using spec_data_path: {sdp}")

    try:
        data = _load_json(sdp_path)
    except Exception as e:
        print(f"❌ Failed to parse spec_data_path: {e}")
        return 1

    api = data.get("api")
    if not isinstance(api, dict):
        print("❌ spec_data_path must include { api: {...} }")
        return 1

    dtos = api.get("dtos")
    if not isinstance(dtos, dict):
        print("❌ api.dtos must be an object")
        return 1

    lines = []
    lines.append("// <auto-generated />")
    lines.append(f"// Source lock: {args.lock}")
    lines.append("// Generated by: speclock-sdk-gen-cs.py")
    lines.append("")
    lines.append("using System;")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append(f"namespace {args.namespace};")
    lines.append("")

    for name in sorted(dtos.keys()):
        shape = dtos[name]
        if not isinstance(shape, dict):
            continue
        cs_name = _safe_ident(_pascal_case(name))
        lines.append(f"public sealed record {cs_name}(")
        fields = []
        for field in sorted(shape.keys()):
            cs_field = _pascal_case(_safe_ident(field))
            t = _cs_type(str(shape[field]))
            fields.append(f"    {t} {cs_field}")
        lines.append(",\n".join(fields))
        lines.append(");")
        lines.append("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print(f"  Records: {len(dtos)}")
    print("")
    print(f"✅ Wrote C# DTOs: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
