#!/usr/bin/env python3
"""
TerraFusion Workspace Infrastructure Builder
Creates missing directories and initializes project structure for all 57 workspaces
"""

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Set
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class WorkspaceInfrastructureBuilder:
    def __init__(self, root_path: str):
        self.root_path = Path(root_path)
        self.analysis_file = self.root_path / "workspace_analysis_results.json"
        self.created_dirs = set()
        self.created_files = []
        
    def load_analysis_results(self) -> Dict:
        """Load the workspace analysis results"""
        if not self.analysis_file.exists():
            logger.error(f"Analysis file not found: {self.analysis_file}")
            logger.info("Please run workspace_health_analyzer.py first")
            return {}
            
        with open(self.analysis_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def create_directory_safely(self, dir_path: Path) -> bool:
        """Create directory if it doesn't exist"""
        try:
            if not dir_path.exists():
                dir_path.mkdir(parents=True, exist_ok=True)
                self.created_dirs.add(str(dir_path))
                logger.info(f"✅ Created directory: {dir_path.relative_to(self.root_path)}")
                return True
            else:
                logger.debug(f"📁 Directory already exists: {dir_path.relative_to(self.root_path)}")
                return False
        except Exception as e:
            logger.error(f"❌ Failed to create directory {dir_path}: {e}")
            return False
    
    def create_basic_file(self, file_path: Path, content: str) -> bool:
        """Create a basic file with content"""
        try:
            if not file_path.exists():
                file_path.parent.mkdir(parents=True, exist_ok=True)
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
                self.created_files.append(str(file_path))
                logger.info(f"📄 Created file: {file_path.relative_to(self.root_path)}")
                return True
            return False
        except Exception as e:
            logger.error(f"❌ Failed to create file {file_path}: {e}")
            return False
    
    def fix_missing_directories(self, workspace_details: Dict) -> int:
        """Fix all missing directories from workspace analysis"""
        total_created = 0
        
        for workspace_name, details in workspace_details.items():
            if details.get('status') == 'critical' and 'missing_folders' in details:
                logger.info(f"🔧 Fixing workspace: {workspace_name}")
                
                for missing_folder in details['missing_folders']:
                    # Convert relative path to absolute
                    folder_path = self.root_path / missing_folder.lstrip("../")
                    
                    if self.create_directory_safely(folder_path):
                        total_created += 1
                        
                        # Create appropriate content based on folder type
                        self.initialize_directory_content(folder_path, missing_folder)
        
        return total_created
    
    def initialize_directory_content(self, dir_path: Path, original_path: str):
        """Initialize appropriate content for different directory types"""
        dir_name = dir_path.name.lower()
        
        # Tests directories
        if 'test' in dir_name:
            self.create_test_structure(dir_path, original_path)
        
        # Docs directories  
        elif 'doc' in dir_name:
            self.create_docs_structure(dir_path, original_path)
        
        # Frontend/marketplace directories
        elif 'frontend' in original_path or 'marketplace' in original_path:
            self.create_frontend_structure(dir_path, original_path)
        
        # Backend directories
        elif 'backend' in original_path:
            self.create_backend_structure(dir_path, original_path)
        
        # Platform directories
        elif 'platform' in original_path:
            self.create_platform_structure(dir_path, original_path)
    
    def create_test_structure(self, dir_path: Path, original_path: str):
        """Create basic test structure"""
        # Create README
        readme_content = f"""# Test Directory: {dir_path.name}

This directory contains tests for the TerraFusion workspace.

## Structure
- `unit/` - Unit tests
- `integration/` - Integration tests  
- `e2e/` - End-to-end tests

## Usage
Run tests with your preferred testing framework.

Generated by TerraFusion Workspace Infrastructure Builder
"""
        self.create_basic_file(dir_path / "README.md", readme_content)
        
        # Create test subdirectories
        for subdir in ['unit', 'integration', 'e2e']:
            self.create_directory_safely(dir_path / subdir)
    
    def create_docs_structure(self, dir_path: Path, original_path: str):
        """Create basic documentation structure"""
        readme_content = f"""# Documentation: {dir_path.name}

Documentation for the TerraFusion workspace component.

## Contents
- `README.md` - This file
- `setup.md` - Setup instructions
- `usage.md` - Usage guide
- `api.md` - API documentation

Generated by TerraFusion Workspace Infrastructure Builder
"""
        self.create_basic_file(dir_path / "README.md", readme_content)
        
        # Create basic doc files
        setup_content = f"""# Setup Guide

## Prerequisites
- Ensure development environment is properly configured
- Follow TerraFusion development guidelines

## Installation
Refer to workspace-specific installation instructions.
"""
        self.create_basic_file(dir_path / "setup.md", setup_content)
    
    def create_frontend_structure(self, dir_path: Path, original_path: str):
        """Create frontend project structure"""
        # Create package.json if this looks like a Node.js project
        if not (dir_path / "package.json").exists():
            package_json = {
                "name": f"terrafusion-{dir_path.name}",
                "version": "1.0.0",
                "description": f"TerraFusion {dir_path.name} component",
                "main": "index.js",
                "scripts": {
                    "dev": "echo 'Add your dev command here'",
                    "build": "echo 'Add your build command here'",
                    "test": "echo 'Add your test command here'"
                },
                "dependencies": {},
                "devDependencies": {}
            }
            
            self.create_basic_file(dir_path / "package.json", json.dumps(package_json, indent=2))
        
        # Create basic README
        readme_content = f"""# TerraFusion {dir_path.name}

Frontend component for TerraFusion government services platform.

## Development
```bash
npm install
npm run dev
```

Generated by TerraFusion Workspace Infrastructure Builder
"""
        self.create_basic_file(dir_path / "README.md", readme_content)
        
        # Create src directory
        self.create_directory_safely(dir_path / "src")
    
    def create_backend_structure(self, dir_path: Path, original_path: str):
        """Create backend project structure"""
        readme_content = f"""# TerraFusion {dir_path.name} Backend

Backend component for TerraFusion government services platform.

## Development
Refer to workspace-specific backend setup instructions.

Generated by TerraFusion Workspace Infrastructure Builder
"""
        self.create_basic_file(dir_path / "README.md", readme_content)
    
    def create_platform_structure(self, dir_path: Path, original_path: str):
        """Create platform component structure"""
        readme_content = f"""# TerraFusion Platform: {dir_path.name}

Platform component for TerraFusion government services infrastructure.

## Purpose
Core platform functionality and shared services.

Generated by TerraFusion Workspace Infrastructure Builder
"""
        self.create_basic_file(dir_path / "README.md", readme_content)
    
    def create_workspace_specific_configs(self):
        """Create workspace-specific configuration files"""
        # This would create specific configs for each workspace type
        # For now, we'll focus on the directory structure
        pass
    
    def generate_build_report(self) -> str:
        """Generate a report of what was created"""
        report = []
        report.append("🌍 TERRAFUSION WORKSPACE INFRASTRUCTURE BUILD REPORT")
        report.append("=" * 60)
        report.append(f"📁 Directories Created: {len(self.created_dirs)}")
        report.append(f"📄 Files Created: {len(self.created_files)}")
        report.append("")
        
        if self.created_dirs:
            report.append("📁 NEW DIRECTORIES:")
            for dir_path in sorted(self.created_dirs):
                rel_path = Path(dir_path).relative_to(self.root_path)
                report.append(f"  ✅ {rel_path}")
            report.append("")
        
        if self.created_files:
            report.append("📄 NEW FILES:")
            for file_path in sorted(self.created_files):
                rel_path = Path(file_path).relative_to(self.root_path)
                report.append(f"  📄 {rel_path}")
        
        return "\\n".join(report)
    
    def build_infrastructure(self) -> bool:
        """Main method to build all missing infrastructure"""
        logger.info("🚀 Starting TerraFusion Workspace Infrastructure Build...")
        
        # Load analysis results
        analysis = self.load_analysis_results()
        if not analysis:
            return False
        
        workspace_details = analysis.get('workspace_details', {})
        if not workspace_details:
            logger.error("No workspace details found in analysis")
            return False
        
        # Fix missing directories
        created_count = self.fix_missing_directories(workspace_details)
        
        # Create workspace-specific configs
        self.create_workspace_specific_configs()
        
        logger.info(f"✅ Infrastructure build complete! Created {created_count} directories")
        
        # Generate and display report
        report = self.generate_build_report()
        print(report)
        
        return True

def main():
    if len(sys.argv) > 1:
        root_path = sys.argv[1]
    else:
        root_path = r"C:\\Users\\bsval\\terrafusion_os_1.0"

    builder = WorkspaceInfrastructureBuilder(root_path)
    
    success = builder.build_infrastructure()
    
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())