<?xml version="1.0"?>
<xs:schema xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="System.xsd" />
  <xs:include schemaLocation="Geometry.xsd" />
  <xs:complexType name="Color" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" name="UseWindowsDithering" type="xs:boolean" />
      <xs:element minOccurs="0" name="AlphaValue" type="xs:unsignedByte">
        <xs:annotation>
          <xs:documentation>The Alpha Blending value. (0 for transparent, 255 for opaque).</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GrayColor">
    <xs:complexContent mixed="false">
      <xs:extension base="Color">
        <xs:sequence>
          <xs:element name="GrayLevel" type="xs:unsignedByte" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RgbColor">
    <xs:complexContent mixed="false">
      <xs:extension base="Color">
        <xs:sequence>
          <xs:element name="Red" type="xs:unsignedByte" />
          <xs:element name="Green" type="xs:unsignedByte" />
          <xs:element name="Blue" type="xs:unsignedByte" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="CmykColor">
    <xs:complexContent mixed="false">
      <xs:extension base="Color">
        <xs:sequence>
          <xs:element name="Cyan" type="xs:unsignedByte" />
          <xs:element name="Magenta" type="xs:unsignedByte" />
          <xs:element name="Yellow" type="xs:unsignedByte" />
          <xs:element name="Black" type="xs:unsignedByte" />
          <xs:element name="Overprint" type="xs:boolean" />
          <xs:element name="IsSpot" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>Indicates if the color is a spot color.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="SpotDescription" type="xs:string" />
          <xs:element name="SpotPercent" type="xs:short">
            <xs:annotation>
              <xs:documentation>The saturation of the spot plate.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="HlsColor">
    <xs:complexContent mixed="false">
      <xs:extension base="Color">
        <xs:sequence>
          <xs:element name="Hue" type="xs:short" />
          <xs:element name="Lightness" type="xs:unsignedByte" />
          <xs:element name="Saturation" type="xs:unsignedByte" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="HsvColor">
    <xs:complexContent mixed="false">
      <xs:extension base="Color">
        <xs:sequence>
          <xs:element name="Hue" type="xs:short" />
          <xs:element name="Saturation" type="xs:unsignedByte" />
          <xs:element name="Value" type="xs:unsignedByte" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Symbol" abstract="true">
    <xs:sequence />
  </xs:complexType>
  <xs:simpleType name="esriSimpleFillStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSFSSolid" />
      <xs:enumeration value="esriSFSNull" />
      <xs:enumeration value="esriSFSHorizontal" />
      <xs:enumeration value="esriSFSVertical" />
      <xs:enumeration value="esriSFSForwardDiagonal" />
      <xs:enumeration value="esriSFSBackwardDiagonal" />
      <xs:enumeration value="esriSFSCross" />
      <xs:enumeration value="esriSFSDiagonalCross" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriSimpleLineStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSLSSolid" />
      <xs:enumeration value="esriSLSDash" />
      <xs:enumeration value="esriSLSDot" />
      <xs:enumeration value="esriSLSDashDot"/>
      <xs:enumeration value="esriSLSDashDotDot" />
      <xs:enumeration value="esriSLSNull" />
      <xs:enumeration value="esriSLSInsideFrame" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriSimpleMarkerStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriSMSCircle" />
      <xs:enumeration value="esriSMSSquare" />
      <xs:enumeration value="esriSMSCross" />
      <xs:enumeration value="esriSMSX" />
      <xs:enumeration value="esriSMSDiamond" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriTextHorizontalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriTHALeft" />
      <xs:enumeration value="esriTHACenter" />
      <xs:enumeration value="esriTHARight" />
      <xs:enumeration value="esriTHAFull" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriTextVerticalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriTVATop" />
      <xs:enumeration value="esriTVACenter" />
      <xs:enumeration value="esriTVABaseline" />
      <xs:enumeration value="esriTVABottom" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriTextPosition">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriTPNormal" />
      <xs:enumeration value="esriTPSuperscript" />
      <xs:enumeration value="esriTPSubscript" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriTextCase">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriTCNormal" />
      <xs:enumeration value="esriTCLowercase" />
      <xs:enumeration value="esriTCAllCaps" />
      <xs:enumeration value="esriTCSmallCaps" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriTextDirection">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriTDHorizontal" />
      <xs:enumeration value="esriTDAngle" />
      <xs:enumeration value="esriTDVertical" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriMaskStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriMSNone" />
      <xs:enumeration value="esriMSHalo" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriBalloonCalloutStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriBCSRectangle" />
      <xs:enumeration value="esriBCSRoundedRectangle" />
      <xs:enumeration value="esriBCSOval" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriLineCalloutStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriLCSBase" />
      <xs:enumeration value="esriLCSMidpoint" />
      <xs:enumeration value="esriLCSThreePoint" />
      <xs:enumeration value="esriLCSFourPoint" />
      <xs:enumeration value="esriLCSUnderline" />
      <xs:enumeration value="esriLCSCustom" />
      <xs:enumeration value="esriLCSCircularCW" />
      <xs:enumeration value="esriLCSCircularCCW" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SimpleFillSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="FillSymbol">
        <xs:sequence>
          <xs:element name="Style" type="esriSimpleFillStyle" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimpleLineSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="LineSymbol">
        <xs:sequence>
          <xs:element name="Style" type="esriSimpleLineStyle" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimpleMarkerSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="MarkerSymbol">
        <xs:sequence>
          <xs:element name="Outline" type="xs:boolean" />
          <xs:element name="OutlineSize" type="xs:double" />
          <xs:element name="OutlineColor" type="Color" />
          <xs:element name="Style" type="esriSimpleMarkerStyle" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="esriFontStyle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="normal" />
      <xs:enumeration value="italic" />
      <xs:enumeration value="oblique" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriFontWeight">
    <xs:restriction base="xs:string">
      <xs:enumeration value="normal" />
      <xs:enumeration value="bold" />
      <xs:enumeration value="bolder" />
      <xs:enumeration value="lighter" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriFontDecoration">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none" />
      <xs:enumeration value="underline" />
      <xs:enumeration value="line-through" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriSimpleTextVerticalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top" />
      <xs:enumeration value="middle" />
      <xs:enumeration value="baseline" />
      <xs:enumeration value="bottom" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriSimpleTextHorizontalAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="left" />
      <xs:enumeration value="center" />
      <xs:enumeration value="right" />
      <xs:enumeration value="justified" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SimpleTextSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="Color" type="Color">
            <xs:annotation>
              <xs:documentation>Text color."</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="BackgroundColor" type="Color" />
          <xs:element minOccurs="0" name="OutlineColor" type="Color" />
          <xs:element minOccurs="0" name="VerticalAlignment" type="esriSimpleTextVerticalAlignment">
            <xs:annotation>
              <xs:documentation>Vertical alignment style.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="HorizontalAlignment" type="esriSimpleTextHorizontalAlignment">
            <xs:annotation>
              <xs:documentation>Horizontal alignment style.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" default="false" name="RightToLeft" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>Indicates if the text is drawn from right to left.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" default="0.0" name="Angle" type="xs:double">
            <xs:annotation>
              <xs:documentation>Text baseline angle.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" default="0.0" name="XOffset" type="xs:double" />
          <xs:element minOccurs="0" default="0.0" name="YOffset" type="xs:double" />
          <xs:element minOccurs="0" name="Size" type="xs:double">
            <xs:annotation>
              <xs:documentation>Text size.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontFamilyName" type="xs:string">
            <xs:annotation>
              <xs:documentation>The name of the font family.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontStyle" type="esriFontStyle">
            <xs:annotation>
              <xs:documentation>The font style.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontWeight" type="esriFontWeight">
            <xs:annotation>
              <xs:documentation>
                The boldness or weight of the font.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontDecoration" type="esriFontDecoration" />
          <xs:element minOccurs="0" name="OutlineWidth" type="xs:double" />
          <xs:element minOccurs="0" name="Kerning" type="xs:boolean" />
          <xs:element minOccurs="0" name="MaskStyle" type="esriMaskStyle" />
          <xs:element minOccurs="0" name="MaskSize" type="xs:int" />
          <xs:element minOccurs="0" name="MaskSymbol" type="Symbol" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TextSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="Color" type="Color">
            <xs:annotation>
              <xs:documentation>Text color."</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="BreakCharIndex" type="xs:int">
            <xs:annotation>
              <xs:documentation>Character to be interpreted as text line end.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="VerticalAlignment" type="esriTextVerticalAlignment">
            <xs:annotation>
              <xs:documentation>Vertical alignment style.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="HorizontalAlignment" type="esriTextHorizontalAlignment">
            <xs:annotation>
              <xs:documentation>Horizontal alignment style.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Clip" type="xs:boolean" />
          <xs:element name="RightToLeft" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>Indicates if the text is drawn from right to left.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Angle" type="xs:double">
            <xs:annotation>
              <xs:documentation>Text baseline angle.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="XOffset" type="xs:double" />
          <xs:element name="YOffset" type="xs:double" />
          <xs:element minOccurs="0" name="ShadowColor" type="Color" />
          <xs:element name="ShadowXOffset" type="xs:double" />
          <xs:element name="ShadowYOffset" type="xs:double" />
          <xs:element name="TextPosition" type="esriTextPosition">
            <xs:annotation>
              <xs:documentation>The text position.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="TextCase" type="esriTextCase">
            <xs:annotation>
              <xs:documentation>The text case.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="CharacterSpacing" type="xs:double" />
          <xs:element default="100.0" name="CharacterWidth" type="xs:double" />
          <xs:element default="100.0" name="WordSpacing" type="xs:double" />
          <xs:element name="Kerning" type="xs:boolean" />
          <xs:element name="Leading" type="xs:double" />
          <xs:element name="TextDirection" type="esriTextDirection">
            <xs:annotation>
              <xs:documentation>The text direction.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="FlipAngle" type="xs:double" />
          <xs:element name="TypeSetting" type="xs:boolean" />
          <xs:element minOccurs="0" name="TextPathClass" type="xs:string">
            <xs:annotation>
              <xs:documentation>Path of text baseline.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FillSymbol" type="Symbol" />
          <xs:element name="Text" type="xs:string">
            <xs:annotation>
              <xs:documentation>Text to draw.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Size" type="xs:double">
            <xs:annotation>
              <xs:documentation>Text size.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="MaskStyle" type="esriMaskStyle" />
          <xs:element name="MaskSize" type="xs:double" />
          <xs:element minOccurs="0" name="MaskSymbol" type="Symbol" />
          <xs:element minOccurs="0" name="FontName" type="xs:string">
            <xs:annotation>
              <xs:documentation>The name of the font family.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontItalic" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>Indicates whether the font is italicized.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontUnderline" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>Indicates whether the font is underlined.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontStrikethrough" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates whether the font is strikethrough.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontWeight" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                The boldness or weight of the font.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontCharset" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                The character set used in the font, such as ANSI_CHARSET, DEFAULT_CHARSET, or SYMBOL_CHARSET.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontSizeHi" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                Point size of the font expressed in a 64-bit CY variable whose upper 32-bits contains the integer point size.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontSizeLo" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                Point size of the font expressed in a 64-bit CY variable whose lower 32-bits contains the fractional point size.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="TextParserClass" type="xs:string">
            <xs:annotation>
              <xs:documentation>Text Parser Class ID</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="CharacterMarkerSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="CartographicMarkerSymbol">
        <xs:sequence>
          <xs:element name="CharacterIndex" type="xs:int" />
          <xs:element minOccurs="0" name="FontName" type="xs:string">
            <xs:annotation>
              <xs:documentation>
                The name of the font family.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontItalic" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates whether the font is italicized.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontUnderline" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates whether the font is underlined.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontStrikethrough" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates whether the font is strikethrough.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontWeight" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                The boldness or weight of the font.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontCharset" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                The character set used in the font, such as ANSI_CHARSET, DEFAULT_CHARSET, or SYMBOL_CHARSET.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontSizeHi" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                Point size of the font expressed in a 64-bit CY variable whose upper 32-bits contains the integer point size.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FontSizeLo" type="xs:int">
            <xs:annotation>
              <xs:documentation>
                Point size of the font expressed in a 64-bit CY variable whose lower 32-bits contains the fractional point size.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="PictureMarkerSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="CartographicMarkerSymbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="BgColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Background color of the picture for 1 bit images.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="BitmapTransColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Color within bitmap indicating transparency.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="Picture" type="xs:base64Binary" />
          <xs:element minOccurs="0" name="PictureUri" type="xs:string" />
          <xs:element minOccurs="0" name="Width" type="xs:double" />
          <xs:element minOccurs="0" name="FgColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Foreground color of the picture for 1 bit images.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="Swap1BitColor" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates if foreground and background colors are swapped on 1 Bit Images Only.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="PictureFillSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="FillSymbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="Picture" type="xs:base64Binary" />
          <xs:element minOccurs="0" name="PictureUri" type="xs:string" />
          <xs:element minOccurs="0" name="Width" type="xs:double" />
          <xs:element minOccurs="0" name="Height" type="xs:double" />
          <xs:element minOccurs="0" name="BgColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Fill background color.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="FgColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Fill foreground color.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="BitmapTransColor" type="Color">
            <xs:annotation>
              <xs:documentation>
                Color within bitmap indicating transparency.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="XSeparation" type="xs:double" />
          <xs:element minOccurs="0" name="YSeparation" type="xs:double" />
          <xs:element minOccurs="0" name="Swap1BitColor" type="xs:boolean">
            <xs:annotation>
              <xs:documentation>
                Indicates if the foreground and background colors are swapped on 1 Bit Images Only.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="Angle" type="xs:double" />
          <xs:element minOccurs="0" name="XOffset" type="xs:double" />
          <xs:element minOccurs="0" name="YOffset" type="xs:double" />
          <xs:element minOccurs="0" default="1.0" name="XScale" type="xs:double" />
          <xs:element minOccurs="0" default="1.0" name="YScale" type="xs:double" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BalloonCallout">
    <xs:complexContent mixed="false">
      <xs:extension base="Callout" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LineCallout">
    <xs:complexContent mixed="false">
      <xs:extension base="Callout">
        <xs:sequence />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MarkerTextBackground">
    <xs:complexContent mixed="false">
      <xs:extension base="TextBackground">
        <xs:sequence>
          <xs:element name="Scale" type="xs:boolean" />
          <xs:element minOccurs="0" name="Symbol" type="Symbol" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SimpleLineCallout">
    <xs:complexContent mixed="false">
      <xs:extension base="Callout">
        <xs:sequence>
          <xs:element name="AutoSnap" type="xs:boolean" />
          <xs:element minOccurs="0" name="LineGeometry" type="Geometry" />
          <xs:element minOccurs="0" name="LineSymbol" type="Symbol" />
          <xs:element minOccurs="0" name="FgColor" type="Color" />
          <xs:element minOccurs="0" name="Swap1BitColor" type="xs:boolean" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="FillSymbol" abstract="true">
    <xs:annotation>
      <xs:documentation>
        Fill Sybmol Properties.
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="Color" type="Color">
            <xs:annotation>
              <xs:documentation>
                Fill color.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="Outline" type="LineSymbol">
            <xs:annotation>
              <xs:documentation>
                Line symbol of fill outline.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="LineSymbol" abstract="true">
    <xs:annotation>
      <xs:documentation>
        Line Symbol properties.
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="Color" type="Color">
            <xs:annotation>
              <xs:documentation>
                Line symbol color.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Width" type="xs:double">
            <xs:annotation>
              <xs:documentation>
                Line symbol width.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MarkerSymbol" abstract="true">
    <xs:annotation>
      <xs:documentation>
        Marker Symbol Properties.
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element name="Angle" type="xs:double">
            <xs:annotation>
              <xs:documentation>
                Marker symbol angle.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element minOccurs="0" name="Color" type="Color">
            <xs:annotation>
              <xs:documentation>
                Marker symbol color.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Size" type="xs:double">
            <xs:annotation>
              <xs:documentation>
                Marker symbol size.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="XOffset" type="xs:double">
            <xs:annotation>
              <xs:documentation>
                Symbol X-axis offset from point location.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="YOffset" type="xs:double">
            <xs:annotation>
              <xs:documentation>
                Symbol Y-axis offset from point location.
              </xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TextBackground" abstract="true">
  </xs:complexType>
  <xs:complexType name="CartographicMarkerSymbol" abstract="true">
    <xs:annotation>
      <xs:documentation>
        Cartographic marker symbol properties.
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="MarkerSymbol">
        <xs:sequence>
          <xs:element default="1.0" name="XScale" type="xs:double" />
          <xs:element default="1.0" name="YScale" type="xs:double" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="Callout" abstract="true">
    <xs:complexContent mixed="false">
      <xs:extension base="TextBackground">
        <xs:sequence>
          <xs:element minOccurs="0" name="AnchorPoint" type="Point" />
          <xs:element name="LeaderTolerance" type="xs:double" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XMLBinarySymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="Symbol">
        <xs:sequence>
          <xs:element name="Data" type="XMLPersistedObject" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="XMLBinaryFillSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="FillSymbol">
        <xs:sequence>
          <xs:element name="Data" type="XMLPersistedObject" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfColor">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Color" type="Color" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ColorRamp" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" name="Name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfColorRamp">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ColorRamp" type="ColorRamp" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AlgorithmicColorRamp">
    <xs:complexContent mixed="false">
      <xs:extension base="ColorRamp">
        <xs:sequence>
          <xs:element minOccurs="0" name="Algorithm" type="xs:string" />
          <xs:element minOccurs="0" name="FromColor" type="HsvColor" />
          <xs:element minOccurs="0" name="ToColor" type="HsvColor" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="RandomColorRamp">
    <xs:complexContent mixed="false">
      <xs:extension base="ColorRamp">
        <xs:sequence>
          <xs:element minOccurs="0" name="NumColors" type="xs:int" />
          <xs:element minOccurs="0" name="UseSeed" type="xs:boolean" />
          <xs:element minOccurs="0" name="Seed" type="xs:int" />
          <xs:element minOccurs="0" name="MinValue" type="xs:short" />
          <xs:element minOccurs="0" name="MaxValue" type="xs:short" />
          <xs:element minOccurs="0" name="MinSaturation" type="xs:short" />
          <xs:element minOccurs="0" name="MaxSaturation" type="xs:short" />
          <xs:element minOccurs="0" name="StartHue" type="xs:short" />
          <xs:element minOccurs="0" name="EndHue" type="xs:short" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="PresetColorRamp">
    <xs:complexContent mixed="false">
      <xs:extension base="ColorRamp">
        <xs:sequence>
          <xs:element minOccurs="0" name="NumColors" type="xs:int" />
          <xs:element minOccurs="0" name="PresetSize" type="xs:int" />
          <xs:element minOccurs="0" name="Colors" type="ArrayOfColor" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="MultiPartColorRamp">
    <xs:complexContent mixed="false">
      <xs:extension base="ColorRamp">
        <xs:sequence>
          <xs:element minOccurs="0" name="NumColorRamps" type="xs:int" />
          <xs:element minOccurs="0" name="ColorRamps" type="ArrayOfColorRamp" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfGraphicAttribute">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GraphicAttribute" type="GraphicAttribute" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GraphicAttribute">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Value" type="xs:anyType" />
      <xs:element minOccurs="0" name="FieldName" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RepresentationRule">
    <xs:sequence>
      <xs:element minOccurs="0" name="GeometricEffects" type="ArrayOfGeometricEffect" />
      <xs:element name="Layers" type="ArrayOfBasicSymbol" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfBasicSymbol">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="BasicSymbol" type="BasicSymbol" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="BasicSymbol" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" name="GeometricEffects" type="ArrayOfGeometricEffect" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="BasicFillSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="BasicSymbol">
        <xs:sequence>
          <xs:element name="Pattern" type="RepresentationComponent" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BasicLineSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="BasicSymbol">
        <xs:sequence>
          <xs:element name="Stroke" type="RepresentationComponent" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="BasicMarkerSymbol">
    <xs:complexContent mixed="false">
      <xs:extension base="BasicSymbol">
        <xs:sequence>
          <xs:element minOccurs="0" name="ID" type="xs:int" />
          <xs:element name="GraphicAttributes" type="ArrayOfGraphicAttribute" />
          <xs:element name="MarkerPlacement" type="RepresentationComponent" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfGeometricEffect">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GeometricEffect" type="RepresentationComponent" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RepresentationComponent">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element minOccurs="0" name="ID" type="xs:int" />
      <xs:element name="GraphicAttributes" type="ArrayOfGraphicAttribute" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RepresentationMarker">
    <xs:sequence>
      <xs:element name="MarkerComponents" type="ArrayOfMarkerComponent" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfMarkerComponent">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="MarkerComponent" type="MarkerComponent" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MarkerComponent">
    <xs:sequence>
      <xs:element name="Geometry" type="Geometry" />
      <xs:element name="Rule" type="RepresentationRule" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
