<?xml version="1.0"?>
<xs:schema xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="GeoDatabaseDistributed.xsd" />
  <xs:include schemaLocation="NetworkAnalyst.xsd" />
  <xs:complexType name="DECadastralFabric">
    <xs:complexContent mixed="false">
      <xs:extension base="DEGeoDataset">
        <xs:sequence>
          <xs:element name="ConfigurationKeyword" type="xs:string" />
          <xs:element name="DefaultAccuracy" type="xs:int" />
          <xs:element name="CadastralFieldEditsCollection" type="ArrayOfCadastralFieldEdits" />
          <xs:element name="UseDefaultAccuracies" type="xs:boolean" minOccurs="0"  />
          <xs:element name="CompiledAccuracy" type="xs:int" minOccurs="0"  />
          <xs:element name="BufferDistanceForAdjustment" type="xs:double" minOccurs="0"  />
          <xs:element name="CadastralFabricType" type="xs:int" minOccurs="0"  />
          <xs:element name="SurrogateVersion" type="xs:string" minOccurs="0"  />
          <xs:element name="Version" type="xs:int" minOccurs="0" />
          <xs:element name="MaximumShiftThreshold" type="xs:double" minOccurs="0" />
          <xs:element name="MultiGenerationEditing" type="xs:boolean" minOccurs="0" />
          <xs:element name="MultiLevelReconcile" type="xs:boolean" minOccurs="0" />
          <xs:element name="PinAdjustmentBoundary" type="xs:boolean" minOccurs="0" />
          <xs:element name="PinPointsWithinBoundary" type="xs:boolean" minOccurs="0" />
          <xs:element name="MinorVersion" type="xs:int" minOccurs="0" />
          <xs:element name="WriteAdjustmentVectors" type="xs:boolean" minOccurs="0" />
          <xs:element name="SysTableFieldDomainMap" type="Names" minOccurs="0" />
          <xs:element name ="ArrayOfPropertySet" type="ArrayOfPropertySet" minOccurs="0" />
          <xs:element name ="PropsUserDefined" type ="PropertySet" minOccurs="0" />
          <xs:element name ="PropsImporterLoading" type ="PropertySet" minOccurs="0" />
          <xs:element name ="PropsCoordTolerances" type ="PropertySet" minOccurs="0" />
          <xs:element name ="PropsEditSettings" type ="PropertySet" minOccurs="0" />
          <xs:element name ="PropsCatalogDataset" type ="PropertySet" minOccurs="0" />          
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfCadastralFieldEdits">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="CadastralFieldEdits" type="CadastralFieldEdits" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CadastralFieldEdits">
    <xs:sequence>
      <xs:element name="CadastralTableName" type="xs:string" />
      <xs:element name="ExtendedAttributeFields" type="Fields" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TerrainMembership">
    <xs:complexContent>
      <xs:extension base="ControllerMembership">
        <xs:sequence>
          <xs:element name="TerrainName" type="xs:string" />        
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="TerrainDataSource">
    <xs:sequence>
      <xs:element name="FeatureClassID" type="xs:int" />
      <xs:element name="FeatureClassName" type="xs:string" />
      <xs:element name="GroupID" type="xs:int" />
      <xs:element name="SourceStatus" type="xs:int" />
      <xs:element name="SourceType" type="xs:int" />
      <xs:element name="SurfaceFeatureType" type="xs:int" />
      <xs:element name="IsBase" type="xs:boolean" />
      <xs:element name="ApplyToOverview" type="xs:boolean" />
      <xs:element name="AutoGeneralize" type="xs:boolean" />
      <xs:element name="ResolutionLowerBound" type="xs:double" />
      <xs:element name="ResolutionUpperBound" type="xs:double" />
      <xs:element name="SourceName" type="xs:string" />
      <xs:element name="HeightField" type="xs:string" />
      <xs:element name="TagValueField" type="xs:string" />
      <xs:element name="ReservedFields" type="ArrayOfString" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TerrainPyramidLevelZTol">
    <xs:sequence>
      <xs:element name="PyramidLevelStatus" type="xs:int" />
      <xs:element name="PointCount" type="xs:int" />
      <xs:element name="MaxScale" type="xs:int" />
      <xs:element name="Resolution" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TerrainPyramidLevelWindowSize">
    <xs:sequence>
      <xs:element name="PyramidLevelStatus" type="xs:int" />
      <xs:element name="PointCount" type="xs:int" />
      <xs:element name="MaxScale" type="xs:int" />
      <xs:element name="Resolution" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfTerrainDataSource">
    <xs:sequence>
      <xs:element name="TerrainDataSource" type="TerrainDataSource" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfTerrainPyramidLevelZTol">
    <xs:sequence>
      <xs:element name="TerrainPyramidLevelZTol" type="TerrainPyramidLevelZTol" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfTerrainPyramidLevelWindowSize">
    <xs:sequence>
      <xs:element name="TerrainPyramidLevelWindowSize" type="TerrainPyramidLevelWindowSize" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DETerrain">
    <xs:complexContent>
      <xs:extension base="DEGeoDataset">
        <xs:sequence>
          <xs:element name="FeatureDatasetName" type="xs:string"/>
          <xs:element name="PyramidType" type="xs:int" />
          <xs:element name="WindowSizeMethod" type="xs:int" />
          <xs:element name="WindowSizeZThreshold" type="xs:int" />
          <xs:element name="WindowSizeZThresholdStrategy" type="xs:int" />
          <xs:element name="TileSize" type="xs:int" />
          <xs:element name="MaxShapeSize" type="xs:int" />
          <xs:element name="MaxOverviewSize" type="xs:int" />
          <xs:element name="ConfigurationKeyword" type="xs:string" />
          <xs:element name="TerrainDataSources" type="ArrayOfTerrainDataSource" />
          <xs:element name="TerrainPyramidLevelZTols" type="ArrayOfTerrainPyramidLevelZTol" minOccurs="0" />
          <xs:element name="TerrainPyramidLevelWindowSizes" type="ArrayOfTerrainPyramidLevelWindowSize" minOccurs="0" />
          </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>
