<?xml version="1.0"?>
<xs:schema xmlns="http://www.esri.com/schemas/ArcGIS/3.4.0" targetNamespace="http://www.esri.com/schemas/ArcGIS/3.4.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Carto.xsd" />
  <xs:complexType name="GlobeLayerInfo">
    <xs:sequence>
      <xs:element name="LayerID" type="xs:int" />
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element name="Visible" type="xs:boolean" />
      <xs:element name="LayerType" type="xs:string" />
      <xs:element minOccurs="0" name="Extent" type="Envelope" />
      <xs:element minOccurs="0" name="Fields" type="Fields" />
      <xs:element name="DisplayField" type="xs:string" />
      <xs:element name="Transparency" type="xs:int" />
      <xs:element name="IsComposite" type="xs:boolean" />
      <xs:element name="IsGroup" type="xs:boolean" />
      <xs:element name="ParentLayerID" type="xs:int" />
      <xs:element name="DataType" type="esriGlobeDataType" />
      <xs:element name="MaxDistance" type="xs:decimal" />
      <xs:element name="MinDistance" type="xs:decimal" />
      <xs:element name="PerTileVisibility" type="xs:boolean" />
      <xs:element name="Use16BitsColor" type="xs:boolean" />
      <xs:element name="Use16BitsElevation" type="xs:boolean" />
      <xs:element name="LossyCompression" type="xs:boolean" />
      <xs:element name="CompressionQuality" type="xs:int" />
      <xs:element name="HasOIDs" type="xs:boolean" />
      <xs:element name="Scale3DSymbols" type="xs:boolean" />
      <xs:element name="Priority" type="xs:int" />
      <xs:element name="FloatingOrder" type="xs:int" />
      <xs:element name="SamplingMode" type="esriGlobeImageSamplingMode" />
      <xs:element name="MinCellSize" type="xs:decimal" />
      <xs:element name="Rasterized" type="xs:boolean" />
      <xs:element name="MetersPerPoint" type="xs:decimal" />
      <xs:element name="Extruded" type="xs:boolean" />
      <xs:element name="FeatureLOD" type="xs:int" />
      <xs:element name="ConsolidatedParent" type="xs:boolean" />
      <xs:element name="CatalogCrossoverLOD" type="xs:int" />
      <xs:element name="BaseID" type="xs:int" />
      <xs:element name="BaseOption" type="esriGlobeLayerBaseOption" />
      <xs:element name="ElevationExpression" type="xs:string" />
      <xs:element name="Offset" type="xs:decimal" />
      <xs:element name="ZFactor" type="xs:decimal" />
      <xs:element name="HasElevation" type="xs:boolean" />
      <xs:element name="UseElevation" type="xs:boolean" />
      <xs:element name="ExtrusionType" type="esriExtrusionType" />
      <xs:element name="ExtrusionExpression" type="xs:string" />
      <xs:element name="Illuminate" type="xs:boolean" />
      <xs:element name="Smooth" type="xs:boolean" />
      <xs:element name="CullMode" type="esri3DFaceCulling" />
      <xs:element minOccurs="0" name="GraphicsLayer" type="GlobeGraphicsLayer" />
      <xs:element name="CopyrightText" type="xs:string" />
      <xs:element minOccurs="0" name="MinLOD" type="xs:int">
        <xs:annotation>
          <xs:documentation>The minimum LOD of the Layer.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="MaxLOD" type="xs:int">
        <xs:annotation>
          <xs:documentation>The minimum LOD of the Layer.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RasterTileSize" type="xs:int">
        <xs:annotation>
          <xs:documentation>Rasterized vector tile size.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RasterTileLogSize" type="xs:int">
        <xs:annotation>
          <xs:documentation>Rasterized vector logarithm tile size.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TextureDownsamplingFactor" type="xs:double">
        <xs:annotation>
          <xs:documentation>The texture down-sampling factor for textured multipatches.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TextureCompressionType" type="xs:int">
        <xs:annotation>
          <xs:documentation>The current texture compression type.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TextureDisplayType" type="xs:int">
      <xs:annotation>
        <xs:documentation>The current texture display type.</xs:documentation>
      </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfGlobeLayerInfo">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GlobeLayerInfo" type="GlobeLayerInfo" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GlobeLegendInfo">
    <xs:sequence>
      <xs:element name="LayerID" type="xs:int" />
      <xs:element name="Name" type="xs:string" />
      <xs:element minOccurs="0" name="LegendGroups" type="ArrayOfLegendGroup" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfGlobeLegendInfo">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GlobeLegendInfo" type="GlobeLegendInfo" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GlobeServerIdentifyResult">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="ObjectID" type="xs:int" />
      <xs:element minOccurs="0" name="Shape" type="Geometry" />
      <xs:element minOccurs="0" name="Properties" type="PropertySet" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfGlobeServerIdentifyResult">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GlobeServerIdentifyResult" type="GlobeServerIdentifyResult" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GlobeServerFindResult">
    <xs:sequence>
      <xs:element name="Value" type="xs:string" />
      <xs:element name="FieldName" type="xs:string" />
      <xs:element name="ObjectID" type="xs:int" />
      <xs:element minOccurs="0" name="Shape" type="Geometry" />
      <xs:element minOccurs="0" name="Properties" type="PropertySet" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfGlobeServerFindResult">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GlobeServerFindResult" type="GlobeServerFindResult" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="esriGlobeDataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriGlobeDataInvalid" />
      <xs:enumeration value="esriGlobeDataTexture" />
      <xs:enumeration value="esriGlobeDataElevation" />
      <xs:enumeration value="esriGlobeDataVector" />
      <xs:enumeration value="esriGlobeDataText" />
      <xs:enumeration value="esriGlobeDataObject" />
      <xs:enumeration value="esriGlobeDataPoint" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriGlobeImageSamplingMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriGlobeImageSamplingNearest" />
      <xs:enumeration value="esriGlobeImageSamplingSmooth" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriGlobeLayerBaseOption">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriGlobeLayerBaseGlobe" />
      <xs:enumeration value="esriGlobeLayerBaseExpression" />
      <xs:enumeration value="esriGlobeLayerBaseLayer" />
      <xs:enumeration value="esriGlobeLayerBaseSelf" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esriExtrusionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriExtrusionNone" />
      <xs:enumeration value="esriExtrusionMinZ" />
      <xs:enumeration value="esriExtrusionMaxZ" />
      <xs:enumeration value="esriExtrusionBase" />
      <xs:enumeration value="esriExtrusionAbsolute" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="esri3DFaceCulling">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriFaceCullingNone" />
      <xs:enumeration value="esriFaceCullingFront" />
      <xs:enumeration value="esriFaceCullingBack" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ArrayOfGlobeGraphicsElementProps">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="GlobeGraphicsElementProps" type="GlobeGraphicsElementProperties" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GlobeGraphicsLayer">
    <xs:sequence>
      <xs:element name="UseAssocLayer" type="xs:boolean" />
      <xs:element minOccurs="0" name="AssocLayerName" type="xs:string" />
      <xs:element name="Hide" type="xs:boolean" />
      <xs:element name="Elements" type="ArrayOfGraphicElement" />
      <xs:element name="ElementProperties" type="ArrayOfGlobeGraphicsElementProps" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="esriGlobeGraphicsOrientation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="esriGlobeGraphicsOrientationDefault" />
      <xs:enumeration value="esriGlobeGraphicsOrientationBillboard" />
      <xs:enumeration value="esriGlobeGraphicsOrientationLocal" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="GlobeGraphicsElementProperties">
    <xs:sequence>
      <xs:element name="ElementSelected" type="xs:boolean" />
      <xs:element name="ElementIlluminate" type="xs:boolean" />
      <xs:element name="ElementFixedSize" type="xs:boolean" />
      <xs:element name="ElementOrientation" type="esriGlobeGraphicsOrientation" />
      <xs:element name="ElementRasterized" type="xs:boolean" />
      <xs:element name="ElementDraped" type="xs:boolean" />
      <xs:element name="ElementDrapeMaxRes" type="xs:boolean" />
      <xs:element name="ElementZOffset" type="xs:double" />
      <xs:element name="ElementDensDist" type="xs:double" />
      <xs:element name="ElementCallout" type="xs:boolean" />
      <xs:element name="ElementCallOffX" type="xs:double" />
      <xs:element name="ElementCallOffY" type="xs:double" />
      <xs:element name="ElementCallOffZ" type="xs:double" />
      <xs:element name="ElementCallLineR" type="xs:unsignedByte" />
      <xs:element name="ElementCallLineG" type="xs:unsignedByte" />
      <xs:element name="ElementCallLineB" type="xs:unsignedByte" />
      <xs:element name="ElementCallLineA" type="xs:unsignedByte" />
      <xs:element name="ElementCallWidth" type="xs:double" />
      <xs:element name="ElementTransformed" type="xs:boolean" />
      <xs:element name="ElementTransX" type="xs:double" />
      <xs:element name="ElementTransY" type="xs:double" />
      <xs:element name="ElementTransZ" type="xs:double" />
      <xs:element name="ElementScaleX" type="xs:double" />
      <xs:element name="ElementScaleY" type="xs:double" />
      <xs:element name="ElementScaleZ" type="xs:double" />
      <xs:element name="ElementRotateX" type="xs:double" />
      <xs:element name="ElementRotateY" type="xs:double" />
      <xs:element name="ElementRotateZ" type="xs:double" />
      <xs:element name="ElementGroup" type="xs:boolean" />
      <xs:element name="ElementDrapeDone" type="xs:boolean" />
      <xs:element name="ElementCallPosX" type="xs:double" />
      <xs:element name="ElementCallPosY" type="xs:double" />
      <xs:element name="ElementCallPosZ" type="xs:double" />
      <xs:element name="ElementImmediate" type="xs:boolean" />
      <xs:element name="ElementPosX" type="xs:double" />
      <xs:element name="ElementPosY" type="xs:double" />
      <xs:element name="ElementPosZ" type="xs:double" />
      <xs:element name="ElementPosLon" type="xs:double" />
      <xs:element name="ElementPosLat" type="xs:double" />
      <xs:element name="ElementPosAlt" type="xs:double" />
      <xs:element name="ElementHasOwnScale" type="xs:boolean" />
      <xs:element name="ElementOwnScale" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
