__all__ = [
    "_BaseArcObject",
    "_ObjectWithoutInitCall",
    "passthrough_attr",
    "pass_parameterized_attr",
    "FromScriptingArcObject",
]

from typing import Any

class _ArcobjectPassthrough:
    def __getattr__(self, attr: str) -> Any: ...
    def __setattr__(self, attr: str, val: Any) -> None: ...
    def __delattr__(self, attr: str) -> None: ...

class _BaseArcObject:
    _arc_object: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __cmp__(self, other: Any) -> bool: ...

class _ObjectWithoutInitCall:
    @classmethod
    def __from_scripting_arc_object__(cls, wrap_object: Any) -> Any: ...

class _ObjectWithoutInitCallWrapper:
    @classmethod
    def __from_scripting_arc_object__(cls, wrap_object: Any) -> Any: ...

def passthrough_attr(attr_name: str, readonly: bool = False, doc: str | None = None) -> Any: ...
def pass_parameterized_attr(attr_name: str, *args, **kwargs) -> Any: ...
def FromScriptingArcObject(cls: Any, obj: Any) -> Any: ...
