//>>built
var Panorama=function(){this.degToRad=function(b){return 0.0174533*b};this.radToDeg=function(b){return 57.2958*b};this.clamp=function(b,c,d){return Math.min(Math.max(b,c),d)};this.init=function(b,c){function d(b){b.preventDefault();a.isUserInteracting=!0;a.isMouseDown=!0;a.isInertiaMove=!1;var c=b.clientY||b.touches[0].clientY;a.onMouseDownMouseX=b.clientX||b.touches[0].clientX;a.onMouseDownMouseY=c;a.onMouseDownLon=a.lon;a.onMouseDownLat=a.lat}function e(b){b.preventDefault();a.isMouseDown&&(a.timeLastMouseMove=
new Date);if(!0===a.isUserInteracting){var c=b.clientY||b.touches[0].clientY;a.lon=0.1*(a.onMouseDownMouseX-(b.clientX||b.touches[0].clientX))+a.onMouseDownLon;a.lat=0.1*(c-a.onMouseDownMouseY)+a.onMouseDownLat}}function f(){a.inertiaStartLon=a.lon;a.inertiaStartLat=a.lat;a.deltaLon=a.lon-a.onMouseDownLon;a.deltaLat=a.lat-a.onMouseDownLat;a.isUserInteracting=!1;a.isMouseDown=!1;50>new Date-a.timeLastMouseMove&&(a.isInertiaMove=!0)}var a=this;this.canvas=b;this.isUserInteracting=!1;this.theta=this.phi=
this.onMouseDownLat=this.lat=this.onMouseDownLon=this.lon=this.onMouseDownMouseY=this.onMouseDownMouseX=0;this.isInertiaMove=!1;this.inertiaStartLat=this.inertiaStartLon=this.deltaLat=this.deltaLon=0;this.camera=new THREE.PerspectiveCamera(75,this.canvas.width/this.canvas.height,1,1100);this.camera.target=new THREE.Vector3(0,0,0);this.scene=new THREE.Scene;var k=new THREE.SphereBufferGeometry(500,60,40);k.scale(-1,1,1);var g=new THREE.Texture,h=new Image;h.onload=function(){g.image=h;g.needsUpdate=
!0};h.src=c;var l=new THREE.MeshBasicMaterial({map:g});mesh=new THREE.Mesh(k,l);this.scene.add(mesh);this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:!0});this.renderer.setClearColor(16777215,1);this.renderer.setPixelRatio(window.devicePixelRatio);this.renderer.setSize(this.canvas.width,this.canvas.height);this.canvas.addEventListener("mousedown",d,!1);this.canvas.addEventListener("mousemove",e,!1);this.canvas.addEventListener("mouseup",f,!1);document.addEventListener("mouseup",
f,!1);this.canvas.addEventListener("wheel",function(b){b.preventDefault();a.camera.fov=a.clamp(a.camera.fov+0.05*b.deltaY,10,75);a.camera.updateProjectionMatrix()},!1);this.canvas.addEventListener("touchstart",d,!1);this.canvas.addEventListener("touchmove",e,!1);this.canvas.addEventListener("touchend",f,!1);document.addEventListener("touchend",f,!1)};this.dispose=function(){this.canvas.removeEventListener("mousedown",onPointerStart,!1);this.canvas.removeEventListener("mousemove",onPointerMove,!1);
this.canvas.removeEventListener("mouseup",onPointerUp,!1);document.removeEventListener("mouseup",onPointerUp,!1);this.canvas.removeEventListener("wheel",onDocumentMouseWheel,!1);this.canvas.removeEventListener("touchstart",onPointerStart,!1);this.canvas.removeEventListener("touchmove",onPointerMove,!1);this.canvas.removeEventListener("touchend",onPointerUp,!1);document.removeEventListener("touchend",onPointerUp,!1)};this.render=function(){if(this.isInertiaMove){var b=1-Math.abs(this.lon-this.inertiaStartLon)/
Math.abs(this.deltaLon),c=1-Math.abs(this.lat-this.inertiaStartLat)/Math.abs(this.deltaLat),d=this.lon+this.deltaLon*0.1*b,e=this.lat+this.deltaLat*0.1*c;isNaN(d)||isNaN(e)||isNaN(b)||isNaN(c)||Math.abs(d-this.inertiaStartLon)>Math.abs(this.deltaLon)&&Math.abs(e-this.inertiaStartLat)>Math.abs(this.deltaLat)||85<e||-85>e?this.isInertiaMove=!1:(this.lon=d,this.lat=e)}if(isNaN(this.lon)||isNaN(this.lat))this.lat=this.lon=0,this.isInertiaMove=!1;this.lat=Math.max(-85,Math.min(85,this.lat));this.phi=this.degToRad(90-
this.lat);this.theta=this.degToRad(this.lon);this.camera.target.x=500*Math.sin(this.phi)*Math.cos(this.theta);this.camera.target.y=500*Math.cos(this.phi);this.camera.target.z=500*Math.sin(this.phi)*Math.sin(this.theta);this.camera.lookAt(this.camera.target);b=this.canvas.width;c=this.canvas.height;if(this.renderer.width!=b||this.render.height!=c)this.renderer.setSize(b,c),this.camera.aspect=b/c,this.camera.updateProjectionMatrix();this.renderer.render(this.scene,this.camera)}};
//@ sourceMappingURL=Panorama.js.map