from datetime import date, datetime, time

from typing import TypeAlias, Literal

# Type Aliases
NumericType: TypeAlias = int | float
DateType: TypeAlias = datetime | date | time
ValueType: TypeAlias = str | NumericType | DateType

# Literals

TrueFalse: TypeAlias = Literal[
    "TRUE",
    "FALSE"
]

MinMax: TypeAlias = Literal[
    "MINOF",
    "MAXOF",
]

CellSizeProjectionMethod: TypeAlias = Literal[
    "CONVERT_UNITS",
    "PRESERVE_RESOLUTION",
    "CENTER_OF_EXTENT",
]

CoincidentPoints: TypeAlias = Literal[
    "MEAN",
    "REMOVE_ALL",
    "MIN",
    "MAX",
    "INCLUDE_ALL",
]

NoData: TypeAlias = Literal[
    "NONE",
    "MAXIMUM",
    "MINIMUM",
    "MAP_UP",
    "MAP_DOWN",
    "PROMOTION",
]

ZMFlag: TypeAlias = Literal[
    "Same As Input",
    "Enabled",
    "Disabled",
]

CellAlignment: TypeAlias = Literal[
    "DEFAULT",
    "ALIGN_WITH_PROCESSING_EXTENT",
    "ALIGN_WITH_INPUT",
]

ProcessorType: TypeAlias = Literal[
    "CPU",
    "GPU",
]

ResamplingMethod: TypeAlias = Literal[
    "NEAREST",
    "BILINEAR",
    "CUBIC",
]

TransferDomains: TypeAlias = Literal[
    "NOT_TRANSFER_DOMAINS",
    "TRANSFER_DOMAINS"
]

Qualified: TypeAlias = Literal[
    "QUALIFIED",
    "UNQUALIFIED"
]

TinSaveVersion: TypeAlias = Literal[
    "CURRENT",
    "PRE_10.0"
]

TimeZones: TypeAlias = Literal[
    "AUS_CENTRAL_STANDARD_TIME",
    "AUS_EASTERN_STANDARD_TIME",
    "AFGHANISTAN_STANDARD_TIME",
    "ALASKAN_STANDARD_TIME",
    "ALEUTIAN_STANDARD_TIME",
    "ALTAI_STANDARD_TIME",
    "ARAB_STANDARD_TIME",
    "ARABIAN_STANDARD_TIME",
    "ARABIC_STANDARD_TIME",
    "ARGENTINA_STANDARD_TIME",
    "ASTRAKHAN_STANDARD_TIME",
    "ATLANTIC_STANDARD_TIME",
    "AUS_CENTRAL_W._STANDARD_TIME",
    "AZERBAIJAN_STANDARD_TIME",
    "AZORES_STANDARD_TIME",
    "BAHIA_STANDARD_TIME",
    "BANGLADESH_STANDARD_TIME",
    "BELARUS_STANDARD_TIME",
    "BOUGAINVILLE_STANDARD_TIME",
    "CANADA_CENTRAL_STANDARD_TIME",
    "CAPE_VERDE_STANDARD_TIME",
    "CAUCASUS_STANDARD_TIME",
    "CEN._AUSTRALIA_STANDARD_TIME",
    "CENTRAL_AMERICA_STANDARD_TIME",
    "CENTRAL_ASIA_STANDARD_TIME",
    "CENTRAL_BRAZILIAN_STANDARD_TIME",
    "CENTRAL_EUROPE_STANDARD_TIME",
    "CENTRAL_EUROPEAN_STANDARD_TIME",
    "CENTRAL_PACIFIC_STANDARD_TIME",
    "CENTRAL_STANDARD_TIME",
    "CENTRAL_STANDARD_TIME_(MEXICO)",
    "CHATHAM_ISLANDS_STANDARD_TIME",
    "CHINA_STANDARD_TIME",
    "CUBA_STANDARD_TIME",
    "DATELINE_STANDARD_TIME",
    "E._AFRICA_STANDARD_TIME",
    "E._AUSTRALIA_STANDARD_TIME",
    "E._EUROPE_STANDARD_TIME",
    "E._SOUTH_AMERICA_STANDARD_TIME",
    "EASTER_ISLAND_STANDARD_TIME",
    "EASTERN_STANDARD_TIME",
    "EASTERN_STANDARD_TIME_(MEXICO)",
    "EGYPT_STANDARD_TIME",
    "EKATERINBURG_STANDARD_TIME",
    "FLE_STANDARD_TIME",
    "FIJI_STANDARD_TIME",
    "GMT_STANDARD_TIME",
    "GTB_STANDARD_TIME",
    "GEORGIAN_STANDARD_TIME",
    "GREENLAND_STANDARD_TIME",
    "GREENWICH_STANDARD_TIME",
    "HAITI_STANDARD_TIME",
    "HAWAIIAN_STANDARD_TIME",
    "INDIA_STANDARD_TIME",
    "IRAN_STANDARD_TIME",
    "ISRAEL_STANDARD_TIME",
    "JORDAN_STANDARD_TIME",
    "KALININGRAD_STANDARD_TIME",
    "KAMCHATKA_STANDARD_TIME",
    "KOREA_STANDARD_TIME",
    "LIBYA_STANDARD_TIME",
    "LINE_ISLANDS_STANDARD_TIME",
    "LORD_HOWE_STANDARD_TIME",
    "MAGADAN_STANDARD_TIME",
    "MAGALLANES_STANDARD_TIME",
    "MARQUESAS_STANDARD_TIME",
    "MAURITIUS_STANDARD_TIME",
    "MID-ATLANTIC_STANDARD_TIME",
    "MIDDLE_EAST_STANDARD_TIME",
    "MONTEVIDEO_STANDARD_TIME",
    "MOROCCO_STANDARD_TIME",
    "MOUNTAIN_STANDARD_TIME",
    "MOUNTAIN_STANDARD_TIME_(MEXICO)",
    "MYANMAR_STANDARD_TIME",
    "N._CENTRAL_ASIA_STANDARD_TIME",
    "NAMIBIA_STANDARD_TIME",
    "NEPAL_STANDARD_TIME",
    "NEW_ZEALAND_STANDARD_TIME",
    "NEWFOUNDLAND_STANDARD_TIME",
    "NORFOLK_STANDARD_TIME",
    "NORTH_ASIA_EAST_STANDARD_TIME",
    "NORTH_ASIA_STANDARD_TIME",
    "NORTH_KOREA_STANDARD_TIME",
    "OMSK_STANDARD_TIME",
    "PACIFIC_SA_STANDARD_TIME",
    "PACIFIC_STANDARD_TIME",
    "PACIFIC_STANDARD_TIME_(MEXICO)",
    "PAKISTAN_STANDARD_TIME",
    "PARAGUAY_STANDARD_TIME",
    "QYZYLORDA_STANDARD_TIME",
    "ROMANCE_STANDARD_TIME",
    "RUSSIA_TIME_ZONE_10",
    "RUSSIA_TIME_ZONE_11",
    "RUSSIA_TIME_ZONE_3",
    "RUSSIAN_STANDARD_TIME",
    "SA_EASTERN_STANDARD_TIME",
    "SA_PACIFIC_STANDARD_TIME",
    "SA_WESTERN_STANDARD_TIME",
    "SE_ASIA_STANDARD_TIME",
    "SAINT_PIERRE_STANDARD_TIME",
    "SAKHALIN_STANDARD_TIME",
    "SAMOA_STANDARD_TIME",
    "SAO_TOME_STANDARD_TIME",
    "SARATOV_STANDARD_TIME",
    "SINGAPORE_STANDARD_TIME",
    "SOUTH_AFRICA_STANDARD_TIME",
    "SOUTH_SUDAN_STANDARD_TIME",
    "SRI_LANKA_STANDARD_TIME",
    "SUDAN_STANDARD_TIME",
    "SYRIA_STANDARD_TIME",
    "TAIPEI_STANDARD_TIME",
    "TASMANIA_STANDARD_TIME",
    "TOCANTINS_STANDARD_TIME",
    "TOKYO_STANDARD_TIME",
    "TOMSK_STANDARD_TIME",
    "TONGA_STANDARD_TIME",
    "TRANSBAIKAL_STANDARD_TIME",
    "TURKEY_STANDARD_TIME",
    "TURKS_AND_CAICOS_STANDARD_TIME",
    "US_EASTERN_STANDARD_TIME",
    "US_MOUNTAIN_STANDARD_TIME",
    "UTC",
    "UTC+12",
    "UTC+13",
    "UTC-02",
    "UTC-08",
    "UTC-09",
    "UTC-11",
    "ULAANBAATAR_STANDARD_TIME",
    "VENEZUELA_STANDARD_TIME",
    "VLADIVOSTOK_STANDARD_TIME",
    "VOLGOGRAD_STANDARD_TIME",
    "W._AUSTRALIA_STANDARD_TIME",
    "W._CENTRAL_AFRICA_STANDARD_TIME",
    "W._EUROPE_STANDARD_TIME",
    "W._MONGOLIA_STANDARD_TIME",
    "WEST_ASIA_STANDARD_TIME",
    "WEST_BANK_STANDARD_TIME",
    "WEST_PACIFIC_STANDARD_TIME",
    "YAKUTSK_STANDARD_TIME",
    "YUKON_STANDARD_TIME"
]