// =============================================================================
// SpecLock Manifest Models (GOD-TIER)
// =============================================================================
// DTOs for parsing the manifest.json generated by scripts/speclock-manifest.py.
// These are immutable records - runtime invariants, not domain models.
// Includes time-locked validity window (nbf/exp) for GOD-TIER enforcement.
// =============================================================================

using System.Text.Json.Serialization;

namespace TerraFusion.API.Services.SpecLock;

/// <summary>
/// Root manifest document produced by speclock-manifest.py.
/// Contains sha256 hashes for all SpecLock artifacts.
/// GOD-TIER: Includes time-locked validity window (nbf/exp).
/// </summary>
public sealed record SpecLockManifest(
    [property: JsonPropertyName("version")] string Version,
    [property: JsonPropertyName("generated_at")] string GeneratedAt,
    [property: JsonPropertyName("nbf")] string? NotBefore,
    [property: JsonPropertyName("exp")] string? ExpiresAt,
    [property: JsonPropertyName("index_path")] string IndexPath,
    [property: JsonPropertyName("index_sha256")] string IndexSha256,
    [property: JsonPropertyName("lock_count")] int LockCount,
    [property: JsonPropertyName("locks")] IReadOnlyList<SpecLockEntry> Locks
);

/// <summary>
/// Individual lock entry with artifact hashes.
/// </summary>
public sealed record SpecLockEntry(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("surface")] string Surface,
    [property: JsonPropertyName("project")] string Project,
    [property: JsonPropertyName("spec_version")] string SpecVersion,
    [property: JsonPropertyName("spec_path")] string SpecPath,
    [property: JsonPropertyName("spec_sha256")] string? SpecSha256,
    [property: JsonPropertyName("spec_data_path")] string SpecDataPath,
    [property: JsonPropertyName("spec_data_sha256")] string? SpecDataSha256,
    [property: JsonPropertyName("generated_artifacts")] IReadOnlyList<SpecLockGeneratedArtifact> GeneratedArtifacts
);

/// <summary>
/// Generated artifact with sha256 hash for drift detection.
/// </summary>
public sealed record SpecLockGeneratedArtifact(
    [property: JsonPropertyName("path")] string Path,
    [property: JsonPropertyName("sha256")] string? Sha256
);
