import tempfile

import arcpy
import ips.ComputePositioningQuality.utils as cpq_u
import ips.GenerateIndoorPositioningFile.utils as gipf_u
import ips.const as c
import ips.utils as u
import ips.validation as v


class ComputePositioningQuality(object):

    def __init__(self):
        """Define the tool (tool name is the name of the class)."""
        self.label = "Compute Positioning Quality"
        self.description = (
            '''Populates an IPS Quality dataset generated by the tool 
            Create IPS Quality Dataset.'''
        )

        # self.canRunInBackground = False
        self.helpContext = 78020002

    def execute(self):
        """main function"""

        parameters = arcpy.GetParameterInfo()
        target_ips_quality_dataset = parameters[0]
        in_ips_recordings_features = parameters[1]
        in_sight_blocking_details_features = parameters[2]  # optional

        try:
            # if there are pending edits in a fgdb/egdb raise error
            if arcpy.IsBeingEdited(target_ips_quality_dataset.value):
                raise v.PendingEditsError

            # Check if the IPS Quality Recordings FC has attachment table
            if not v.has_attachments(
                    table=in_ips_recordings_features.value):
                raise v.AttachmentTableError(
                    table=in_ips_recordings_features.value)

            dataset_path = target_ips_quality_dataset.valueAsText

            reference_positions_fc_path = \
                u.get_fc_path(
                    dataset_path=dataset_path,
                    feature_class_name=c.MODEL_QUALITY_31.REFERENCE_POSITIONS.NAME,
                    feature_class_type='Point'
                )
            computed_positions_fc_path = \
                u.get_fc_path(
                    dataset_path=dataset_path,
                    feature_class_name=c.MODEL_QUALITY_31.COMPUTED_POSITIONS.NAME,
                    feature_class_type='Point'
                )

            # TODO: Validation check: IPS Quality dataset contains proper
            #  classes. Better check by Schema not by name

            # from Python 3.10 on we can call cleanup
            # and ignore exceptions for tempdirs
            # this patch can be replaced by using tempdir parameter
            # ignore_errors from 3.10 on
            tempfile.TemporaryDirectory.cleanup = \
                gipf_u.cleanup_patch
            with tempfile.TemporaryDirectory() as tmp_dir:
                cpq_u.compute_positioning_quality(
                    reference_positions_fc=reference_positions_fc_path,
                    computed_positions_fc=computed_positions_fc_path,
                    in_ips_recordings_features=in_ips_recordings_features.valueAsText,
                    in_sight_blocking_details_features=in_sight_blocking_details_features,
                    data_dir=tmp_dir)

        except v.AttachmentTableError as e:
            if str(e.table) == str(in_ips_recordings_features.value):
                # recordings FC has no attachment table
                arcpy.AddIDMessage("ERROR", 250031)
            else:
                # (generic) table/FC has no attachment table
                arcpy.AddIDMessage("ERROR", 1179)
        except v.NoValidRecordings:
            arcpy.AddIDMessage("ERROR", 250042, c.DISPLAY_NAME_CPQ_RECORDINGS)
        except v.PendingEditsError:
            arcpy.AddIDMessage("ERROR", 130144)
        except Exception as any_error:
            print(any_error)
            arcpy.AddIDMessage("ERROR", 999998)
            arcpy.AddError(any_error)

        return


if __name__ == "__main__":
    ComputePositioningQuality().execute()
