CREATE TABLE [dbo].[application_export] (
    [pacs_user_id]          INT           NOT NULL,
    [app_type]              VARCHAR (5)   NULL,
    [sa_addr_line1]         VARCHAR (50)  NULL,
    [sa_addr_line2]         VARCHAR (50)  NULL,
    [sa_addr_line3]         VARCHAR (50)  NULL,
    [sa_city]               VARCHAR (50)  NULL,
    [sa_state]              VARCHAR (2)   NULL,
    [sa_zip]                VARCHAR (50)  NULL,
    [sa_phone_num]          VARCHAR (25)  NULL,
    [sa_phone_num2]         VARCHAR (25)  NULL,
    [sa_fax_num]            VARCHAR (25)  NULL,
    [sa_url]                VARCHAR (50)  NULL,
    [owner_name]            VARCHAR (70)  NULL,
    [addr_line1]            VARCHAR (60)  NULL,
    [addr_line2]            VARCHAR (60)  NULL,
    [addr_line3]            VARCHAR (60)  NULL,
    [addr_city]             VARCHAR (50)  NULL,
    [addr_state]            VARCHAR (2)   NULL,
    [addr_country_cd]       VARCHAR (5)   NULL,
    [addr_zip]              VARCHAR (50)  NULL,
    [geo_id]                VARCHAR (50)  NULL,
    [prop_id]               VARCHAR (25)  NULL,
    [owner_id]              VARCHAR (25)  NULL,
    [prop_type_cd]          VARCHAR (5)   NULL,
    [legal_desc]            VARCHAR (255) NULL,
    [situs]                 VARCHAR (130) NULL,
    [entities]              VARCHAR (50)  NULL,
    [exemptions]            VARCHAR (50)  NULL,
    [prop_val_yr]           VARCHAR (4)   NULL,
    [barcode]               VARCHAR (100) NULL,
    [school_cd]             VARCHAR (5)   NULL,
    [appraiser_nm]          VARCHAR (40)  NULL,
    [dba_name]              VARCHAR (50)  NULL,
    [agent_id]              VARCHAR (25)  NULL,
    [agent_name]            VARCHAR (70)  NULL,
    [agent_addr_line1]      VARCHAR (60)  NULL,
    [agent_addr_line2]      VARCHAR (60)  NULL,
    [agent_addr_line3]      VARCHAR (60)  NULL,
    [agent_addr_city]       VARCHAR (50)  NULL,
    [agent_addr_state]      VARCHAR (2)   NULL,
    [agent_addr_country_cd] VARCHAR (5)   NULL,
    [agent_addr_zip]        VARCHAR (50)  NULL,
    [market]                NUMERIC (14)  NULL,
    [prop_sic_cd]           CHAR (5)      NULL,
    [state_cd]              CHAR (5)      NULL
);


GO

