CREATE TABLE [dbo].[arb_listing] (
    [pacs_user_id]     INT              NULL,
    [case_id]          INT              NULL,
    [appr_year]        NUMERIC (4)      NULL,
    [prop_id]          INT              NULL,
    [sup_num]          INT              NULL,
    [owner_id]         INT              NULL,
    [pct_ownership]    NUMERIC (13, 10) NULL,
    [geo_id]           VARCHAR (50)     NULL,
    [prop_type_cd]     VARCHAR (5)      NULL,
    [legal_desc]       VARCHAR (255)    NULL,
    [situs]            VARCHAR (255)    NULL,
    [entities]         VARCHAR (50)     NULL,
    [exemption]        VARCHAR (50)     NULL,
    [arb_board_cd]     VARCHAR (10)     NULL,
    [arb_hearing_date] DATETIME         NULL,
    [taxpayer_comment] VARCHAR (1024)   NULL,
    [prev_other]       NUMERIC (14)     NULL,
    [prev_ag_mkt]      NUMERIC (14)     NULL,
    [prev_ag_use]      NUMERIC (14)     NULL,
    [prev_land]        NUMERIC (14)     NULL,
    [prev_imprv]       NUMERIC (14)     NULL,
    [prev_appraised]   NUMERIC (14)     NULL,
    [prev_cap]         NUMERIC (14)     NULL,
    [prev_assessed]    NUMERIC (14)     NULL,
    [curr_other]       NUMERIC (14)     NULL,
    [curr_ag_mkt]      NUMERIC (14)     NULL,
    [curr_ag_use]      NUMERIC (14)     NULL,
    [curr_land]        NUMERIC (14)     NULL,
    [curr_imprv]       NUMERIC (14)     NULL,
    [curr_appraised]   NUMERIC (14)     NULL,
    [curr_cap]         NUMERIC (14)     NULL,
    [curr_assessed]    NUMERIC (14)     NULL,
    [diff_other]       NUMERIC (14)     NULL,
    [diff_ag_mkt]      NUMERIC (14)     NULL,
    [diff_ag_use]      NUMERIC (14)     NULL,
    [diff_land]        NUMERIC (14)     NULL,
    [diff_imprv]       NUMERIC (14)     NULL,
    [diff_appraised]   NUMERIC (14)     NULL,
    [diff_cap]         NUMERIC (14)     NULL,
    [diff_assessed]    NUMERIC (14)     NULL,
    [inquiry_type_cd]  CHAR (10)        NULL
);


GO

