CREATE TABLE [dbo].[collections_property_cv] (
    [prop_id]            INT              NOT NULL,
    [owner_id]           INT              NOT NULL,
    [prop_val_yr]        NUMERIC (4)      NOT NULL,
    [pp_seg_id]          INT              NOT NULL,
    [imprv_hstd_val]     NUMERIC (14)     NULL,
    [imprv_non_hstd_val] NUMERIC (14)     NULL,
    [land_hstd_val]      NUMERIC (14)     NULL,
    [land_non_hstd_val]  NUMERIC (14)     NULL,
    [ag_use_val]         NUMERIC (14)     NULL,
    [ag_market]          NUMERIC (14)     NULL,
    [ag_loss]            NUMERIC (14)     NULL,
    [personal_val]       NUMERIC (14)     NULL,
    [market]             NUMERIC (14)     NULL,
    [appraised_val]      NUMERIC (14)     NULL,
    [hs_cap_loss]        NUMERIC (14)     NULL,
    [assessed_val]       NUMERIC (14)     NULL,
    [abs_subdv_cd]       CHAR (10)        NULL,
    [block]              VARCHAR (50)     NULL,
    [tract_or_lot]       VARCHAR (50)     NULL,
    [legal_acreage]      NUMERIC (14, 4)  NULL,
    [mortgage_acct_id]   VARCHAR (50)     NULL,
    [freeze_ceiling]     NUMERIC (14, 2)  NULL,
    [freeze_yr]          NUMERIC (4)      NULL,
    [prop_sic_cd]        CHAR (5)         NULL,
    [field_cd]           VARCHAR (20)     NULL,
    [mineral_zone]       VARCHAR (20)     NULL,
    [rr_comm_num]        VARCHAR (20)     NULL,
    [lease_id]           VARCHAR (20)     NULL,
    [lease_nm]           VARCHAR (50)     NULL,
    [opr]                VARCHAR (30)     NULL,
    [type_of_int]        CHAR (5)         NULL,
    [well_type]          VARCHAR (20)     NULL,
    [geo_info]           VARCHAR (50)     NULL,
    [barrels_per_day]    NUMERIC (18)     NULL,
    [mineral_int_pct]    NUMERIC (13, 10) NULL,
    [new_val]            NUMERIC (14)     NULL,
    [geo_id]             VARCHAR (50)     NULL,
    [legal_desc]         VARCHAR (255)    NULL,
    [source]             VARCHAR (30)     NULL,
    [prop_create_dt]     DATETIME         NULL,
    [prop_type_cd]       CHAR (5)         NULL,
    [state_cd]           CHAR (5)         NULL,
    [seq_no]             CHAR (5)         NULL,
    [ref_id1]            VARCHAR (30)     NULL,
    [ref_id2]            VARCHAR (30)     NULL,
    [last_appraisal_yr]  NUMERIC (4)      NULL,
    [situs_street]       VARCHAR (50)     NULL,
    CONSTRAINT [CPK_collections_property_cv] PRIMARY KEY NONCLUSTERED ([prop_id] ASC, [owner_id] ASC, [prop_val_yr] ASC, [pp_seg_id] ASC) WITH (FILLFACTOR = 90)
);


GO

