CREATE TABLE [dbo].[curr_delq_grandtotals] (
    [pacs_user_id]                   INT             NOT NULL,
    [curr_gt_mno]                    NUMERIC (14, 2) NOT NULL,
    [curr_gt_ins]                    NUMERIC (14, 2) NOT NULL,
    [curr_gt_disc_mno]               NUMERIC (14, 2) NOT NULL,
    [curr_gt_disc_ins]               NUMERIC (14, 2) NOT NULL,
    [curr_gt_pen_mno]                NUMERIC (14, 2) NOT NULL,
    [curr_gt_pen_ins]                NUMERIC (14, 2) NOT NULL,
    [curr_gt_int_mno]                NUMERIC (14, 2) NOT NULL,
    [curr_gt_int_ins]                NUMERIC (14, 2) NOT NULL,
    [curr_gt_total_mno_taxes]        NUMERIC (14, 2) NOT NULL,
    [curr_gt_total_ins_taxes]        NUMERIC (14, 2) NOT NULL,
    [curr_gt_att_fees]               NUMERIC (14, 2) NOT NULL,
    [curr_gt_other_fees]             NUMERIC (14, 2) NOT NULL,
    [curr_gt_total_paid]             NUMERIC (14, 2) NOT NULL,
    [curr_gt_over]                   NUMERIC (14, 2) NOT NULL,
    [curr_gt_under]                  NUMERIC (14, 2) NOT NULL,
    [curr_gt_total_collected]        NUMERIC (14, 2) NOT NULL,
    [curr_gt_net_collected]          NUMERIC (14, 2) NULL,
    [delq_gt_mno]                    NUMERIC (14, 2) NOT NULL,
    [delq_gt_ins]                    NUMERIC (14, 2) NOT NULL,
    [delq_gt_disc_mno]               NUMERIC (14, 2) NOT NULL,
    [delq_gt_disc_ins]               NUMERIC (14, 2) NOT NULL,
    [delq_gt_pen_mno]                NUMERIC (14, 2) NOT NULL,
    [delq_gt_pen_ins]                NUMERIC (14, 2) NOT NULL,
    [delq_gt_int_mno]                NUMERIC (14, 2) NOT NULL,
    [delq_gt_int_ins]                NUMERIC (14, 2) NOT NULL,
    [delq_gt_total_mno_taxes]        NUMERIC (14, 2) NOT NULL,
    [delq_gt_total_ins_taxes]        NUMERIC (14, 2) NOT NULL,
    [delq_gt_att_fees]               NUMERIC (14, 2) NOT NULL,
    [delq_gt_other_fees]             NUMERIC (14, 2) NOT NULL,
    [delq_gt_total_paid]             NUMERIC (14, 2) NOT NULL,
    [delq_gt_over]                   NUMERIC (14, 2) NOT NULL,
    [delq_gt_under]                  NUMERIC (14, 2) NOT NULL,
    [delq_gt_total_collected]        NUMERIC (14, 2) NOT NULL,
    [delq_gt_net_collected]          NUMERIC (14, 2) NULL,
    [total_gt_mno]                   NUMERIC (14, 2) NOT NULL,
    [total_gt_ins]                   NUMERIC (14, 2) NOT NULL,
    [total_gt_disc_mno]              NUMERIC (14, 2) NOT NULL,
    [total_gt_disc_ins]              NUMERIC (14, 2) NOT NULL,
    [total_gt_pen_mno]               NUMERIC (14, 2) NOT NULL,
    [total_gt_pen_ins]               NUMERIC (14, 2) NOT NULL,
    [total_gt_int_mno]               NUMERIC (14, 2) NOT NULL,
    [total_gt_int_ins]               NUMERIC (14, 2) NOT NULL,
    [total_gt_total_mno_taxes]       NUMERIC (14, 2) NOT NULL,
    [total_gt_total_ins_taxes]       NUMERIC (14, 2) NOT NULL,
    [total_gt_att_fees]              NUMERIC (14, 2) NOT NULL,
    [total_gt_other_fees]            NUMERIC (14, 2) NOT NULL,
    [total_gt_total_paid]            NUMERIC (14, 2) NOT NULL,
    [total_gt_over]                  NUMERIC (14, 2) NOT NULL,
    [total_gt_under]                 NUMERIC (14, 2) NOT NULL,
    [total_gt_total_collected]       NUMERIC (14, 2) NOT NULL,
    [total_gt_net_collected]         NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_mno]       NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_ins]       NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_pen_mno]   NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_pen_ins]   NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_int_mno]   NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_int_ins]   NUMERIC (14, 2) NULL,
    [curr_gt_refunds_paid_atty_fee]  NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_mno]       NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_ins]       NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_pen_mno]   NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_pen_ins]   NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_int_mno]   NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_int_ins]   NUMERIC (14, 2) NULL,
    [delq_gt_refunds_paid_atty_fee]  NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_mno]      NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_ins]      NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_pen_mno]  NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_pen_ins]  NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_int_mno]  NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_int_ins]  NUMERIC (14, 2) NULL,
    [total_gt_refunds_paid_atty_fee] NUMERIC (14, 2) NULL,
    [curr_gt_db_mno]                 NUMERIC (14, 2) NULL,
    [curr_gt_db_ins]                 NUMERIC (14, 2) NULL,
    [curr_gt_db_pen_mno]             NUMERIC (14, 2) NULL,
    [curr_gt_db_pen_ins]             NUMERIC (14, 2) NULL,
    [curr_gt_db_int_mno]             NUMERIC (14, 2) NULL,
    [curr_gt_db_int_ins]             NUMERIC (14, 2) NULL,
    [curr_gt_db_atty_fee]            NUMERIC (14, 2) NULL,
    [delq_gt_db_mno]                 NUMERIC (14, 2) NULL,
    [delq_gt_db_ins]                 NUMERIC (14, 2) NULL,
    [delq_gt_db_pen_mno]             NUMERIC (14, 2) NULL,
    [delq_gt_db_pen_ins]             NUMERIC (14, 2) NULL,
    [delq_gt_db_int_mno]             NUMERIC (14, 2) NULL,
    [delq_gt_db_int_ins]             NUMERIC (14, 2) NULL,
    [delq_gt_db_atty_fee]            NUMERIC (14, 2) NULL,
    [total_gt_db_mno]                NUMERIC (14, 2) NULL,
    [total_gt_db_ins]                NUMERIC (14, 2) NULL,
    [total_gt_db_pen_mno]            NUMERIC (14, 2) NULL,
    [total_gt_db_pen_ins]            NUMERIC (14, 2) NULL,
    [total_gt_db_int_mno]            NUMERIC (14, 2) NULL,
    [total_gt_db_int_ins]            NUMERIC (14, 2) NULL,
    [total_gt_db_atty_fee]           NUMERIC (14, 2) NULL,
    CONSTRAINT [CPK_curr_delq_grandtotals] PRIMARY KEY CLUSTERED ([pacs_user_id] ASC) WITH (FILLFACTOR = 100)
);


GO

