CREATE TABLE [dbo].[lease] (
    [lease_id]                   VARCHAR (20)    NOT NULL,
    [lease_yr]                   INT             NOT NULL,
    [rev_num]                    INT             NOT NULL,
    [lease_name]                 VARCHAR (50)    NULL,
    [operator]                   VARCHAR (30)    NULL,
    [rrc_number]                 VARCHAR (20)    NULL,
    [field_id]                   VARCHAR (20)    NULL,
    [abstract]                   VARCHAR (20)    NULL,
    [geo_info]                   VARCHAR (50)    NULL,
    [well_type]                  VARCHAR (20)    NULL,
    [state_cd]                   VARCHAR (10)    NULL,
    [gatherer_cd]                VARCHAR (20)    NULL,
    [prior_yr_ri]                NUMERIC (14)    NULL,
    [prior_yr_wi]                NUMERIC (14)    NULL,
    [lease_dt]                   DATETIME        NULL,
    [participation_pct]          NUMERIC (14, 6) NULL,
    [zero_value]                 NUMERIC (14)    NULL,
    [comment]                    VARCHAR (255)   NULL,
    [last_change_dt]             DATETIME        NULL,
    [value_distrib_dt]           DATETIME        NULL,
    [legal_rebuild_dt]           DATETIME        NULL,
    [lease_inactive_dt]          DATETIME        NULL,
    [create_dt]                  DATETIME        NULL,
    [rev_comment]                VARCHAR (255)   NULL,
    [sup_cd]                     VARCHAR (10)    NULL,
    [sup_desc]                   VARCHAR (500)   NULL,
    [sup_group_id]               INT             NULL,
    [sup_num]                    INT             NULL,
    [appraiser_id]               INT             NULL,
    [prior_yr_1_8]               NUMERIC (14)    NULL,
    [prior_yr_7_8]               NUMERIC (14)    NULL,
    [curr_yr_values_are_1_8_7_8] BIT             NULL,
    [curr_yr_value_ri_1_8]       NUMERIC (14)    NULL,
    [curr_yr_value_wi_7_8]       NUMERIC (14)    NULL,
    CONSTRAINT [CPK_lease] PRIMARY KEY CLUSTERED ([lease_id] ASC, [lease_yr] ASC, [rev_num] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CFK_lease_appraiser_id] FOREIGN KEY ([appraiser_id]) REFERENCES [dbo].[appraiser] ([appraiser_id]),
    CONSTRAINT [CFK_lease_field_id] FOREIGN KEY ([field_id]) REFERENCES [dbo].[lease_field_code] ([field_id]),
    CONSTRAINT [CFK_lease_gatherer_cd] FOREIGN KEY ([gatherer_cd]) REFERENCES [dbo].[lease_gatherer_code] ([gatherer_cd])
);


GO

