CREATE TABLE [dbo].[mineral_import_pritchard_abbott] (
    [run_id]                     INT             NULL,
    [job]                        VARCHAR (7)     NULL,
    [rendered_code]              VARCHAR (1)     NULL,
    [prop_type]                  VARCHAR (1)     NULL,
    [interest_type]              VARCHAR (1)     NULL,
    [year_lease_started]         VARCHAR (4)     NULL,
    [protest_p]                  VARCHAR (1)     NULL,
    [state_cd]                   VARCHAR (3)     NULL,
    [agent_number]               VARCHAR (3)     NULL,
    [sort_code]                  VARCHAR (1)     NULL,
    [decimal_interest]           NUMERIC (13, 6) NULL,
    [lease_name]                 VARCHAR (30)    NULL,
    [oper_name]                  VARCHAR (20)    NULL,
    [desc1]                      VARCHAR (30)    NULL,
    [desc2]                      VARCHAR (30)    NULL,
    [owner_name]                 VARCHAR (30)    NULL,
    [in_care_of]                 VARCHAR (30)    NULL,
    [street_addr]                VARCHAR (30)    NULL,
    [city]                       VARCHAR (17)    NULL,
    [state]                      VARCHAR (3)     NULL,
    [zip]                        VARCHAR (10)    NULL,
    [rrc]                        VARCHAR (20)    NULL,
    [ent1]                       VARCHAR (2)     NULL,
    [ent2]                       VARCHAR (2)     NULL,
    [ent3]                       VARCHAR (2)     NULL,
    [ent4]                       VARCHAR (2)     NULL,
    [ent5]                       VARCHAR (2)     NULL,
    [ent6]                       VARCHAR (2)     NULL,
    [ent7]                       VARCHAR (2)     NULL,
    [ent8]                       VARCHAR (2)     NULL,
    [ent9]                       VARCHAR (2)     NULL,
    [ent10]                      VARCHAR (2)     NULL,
    [ent11]                      VARCHAR (2)     NULL,
    [ent12]                      VARCHAR (2)     NULL,
    [ent1_taxable]               NUMERIC (15)    NULL,
    [ent2_taxable]               NUMERIC (15)    NULL,
    [ent3_taxable]               NUMERIC (15)    NULL,
    [ent4_taxable]               NUMERIC (15)    NULL,
    [ent5_taxable]               NUMERIC (15)    NULL,
    [ent6_taxable]               NUMERIC (15)    NULL,
    [ent7_taxable]               NUMERIC (15)    NULL,
    [ent8_taxable]               NUMERIC (15)    NULL,
    [ent9_taxable]               NUMERIC (15)    NULL,
    [ent10_taxable]              NUMERIC (15)    NULL,
    [ent11_taxable]              NUMERIC (15)    NULL,
    [ent12_taxable]              NUMERIC (15)    NULL,
    [ent1_market]                NUMERIC (15)    NULL,
    [ent2_market]                NUMERIC (15)    NULL,
    [ent3_market]                NUMERIC (15)    NULL,
    [ent4_market]                NUMERIC (15)    NULL,
    [ent5_market]                NUMERIC (15)    NULL,
    [ent6_market]                NUMERIC (15)    NULL,
    [ent7_market]                NUMERIC (15)    NULL,
    [ent8_market]                NUMERIC (15)    NULL,
    [ent9_market]                NUMERIC (15)    NULL,
    [ent10_market]               NUMERIC (15)    NULL,
    [ent11_market]               NUMERIC (15)    NULL,
    [ent12_market]               NUMERIC (15)    NULL,
    [acres]                      NUMERIC (12, 3) NULL,
    [owner_number]               VARCHAR (7)     NULL,
    [lease_number]               VARCHAR (7)     NULL,
    [absolute_ex]                VARCHAR (1)     NULL,
    [ent1_minex]                 VARCHAR (1)     NULL,
    [ent2_minex]                 VARCHAR (1)     NULL,
    [ent3_minex]                 VARCHAR (1)     NULL,
    [ent4_minex]                 VARCHAR (1)     NULL,
    [ent5_minex]                 VARCHAR (1)     NULL,
    [ent6_minex]                 VARCHAR (1)     NULL,
    [ent7_minex]                 VARCHAR (1)     NULL,
    [ent8_minex]                 VARCHAR (1)     NULL,
    [ent9_minex]                 VARCHAR (1)     NULL,
    [ent10_minex]                VARCHAR (1)     NULL,
    [ent11_minex]                VARCHAR (1)     NULL,
    [ent12_minex]                VARCHAR (1)     NULL,
    [geo_number]                 VARCHAR (25)    NULL,
    [pollution_control]          NUMERIC (15)    NULL,
    [ent1_minpa]                 VARCHAR (1)     NULL,
    [ent2_minpa]                 VARCHAR (1)     NULL,
    [ent3_minpa]                 VARCHAR (1)     NULL,
    [ent4_minpa]                 VARCHAR (1)     NULL,
    [ent5_minpa]                 VARCHAR (1)     NULL,
    [ent6_minpa]                 VARCHAR (1)     NULL,
    [ent7_minpa]                 VARCHAR (1)     NULL,
    [ent8_minpa]                 VARCHAR (1)     NULL,
    [ent9_minpa]                 VARCHAR (1)     NULL,
    [ent10_minpa]                VARCHAR (1)     NULL,
    [ent11_minpa]                VARCHAR (1)     NULL,
    [ent12_minpa]                VARCHAR (1)     NULL,
    [account_number]             VARCHAR (7)     NULL,
    [account_seq]                VARCHAR (7)     NULL,
    [prev_account_number]        VARCHAR (7)     NULL,
    [prev_account_seq]           VARCHAR (7)     NULL,
    [geo_id]                     VARCHAR (50)    NULL,
    [legal_desc]                 VARCHAR (255)   NULL,
    [value]                      NUMERIC (14)    NULL,
    [converted_decimal_interest] AS              (case when ([decimal_interest] > 0.0) then (convert(varchar(14),[decimal_interest])) else '' end),
    [xref_id]                    AS              ([lease_number] + '-' + [owner_number] + '-' + case [interest_type] when '1' then 'RI' when '2' then 'OR' when '3' then 'OP' when '4' then 'WI' when '5' then 'RA' else '0' end),
    [converted_interest_type]    AS              (case [interest_type] when '1' then 'RI' when '2' then 'OR' when '3' then 'OP' when '4' then 'WI' when '5' then 'RA' else '0' end),
    [ref_id1]                    AS              ([lease_number] + case [interest_type] when '1' then 'RI' when '2' then 'OR' when '3' then 'OP' when '4' then 'WI' when '5' then 'RA' else '0' end + [owner_number]),
    [ent1_exmpt_type_cd]         AS              (case when (rtrim([ent1]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent1_minex] end),
    [ent2_exmpt_type_cd]         AS              (case when (rtrim([ent2]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent2_minex] end),
    [ent3_exmpt_type_cd]         AS              (case when (rtrim([ent3]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent3_minex] end),
    [ent4_exmpt_type_cd]         AS              (case when (rtrim([ent4]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent4_minex] end),
    [ent5_exmpt_type_cd]         AS              (case when (rtrim([ent5]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent5_minex] end),
    [ent6_exmpt_type_cd]         AS              (case when (rtrim([ent6]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent6_minex] end),
    [ent7_exmpt_type_cd]         AS              (case when (rtrim([ent7]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent7_minex] end),
    [ent8_exmpt_type_cd]         AS              (case when (rtrim([ent8]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent8_minex] end),
    [ent9_exmpt_type_cd]         AS              (case when (rtrim([ent9]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent9_minex] end),
    [ent10_exmpt_type_cd]        AS              (case when (rtrim([ent10]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent10_minex] end),
    [ent11_exmpt_type_cd]        AS              (case when (rtrim([ent11]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent11_minex] end),
    [ent12_exmpt_type_cd]        AS              (case when (rtrim([ent12]) = '') then '' when (rtrim([absolute_ex]) <> '') then [absolute_ex] else [ent12_minex] end),
    [lease_number_2]             AS              (left([lease_number],2)),
    [lease_number_2_3]           AS              (substring([lease_number],2,2)),
    [lease_number_last_4]        AS              (substring([lease_number],4,4)),
    [owner_number_last_6]        AS              (substring([owner_number],2,6)),
    [privacy_code]               VARCHAR (1)     NULL,
    [compliance_code]            VARCHAR (2)     NULL,
    [converted_prop_type]        AS              (case [prop_type] when '1' then 'MN' when '2' then 'MN' when '3' then 'P' else 'MN' end),
    [lease_number_4]             AS              (left([lease_number],4)),
    [lease_number_last_2]        AS              (substring([lease_number],6,2)),
    [owner_number_last_5]        AS              (substring([owner_number],3,5)),
    [converted_interest_type_1]  AS              (case [interest_type] when '1' then 'R' when '2' then 'O' when '3' then 'O' when '4' then 'W' when '5' then 'R' else '0' end),
    [rrc_lease]                  AS              (case when ([prop_type] = 1) then (replace(right(rtrim([rrc]),6),' ',0)) else '' end),
    [rrc_lease_4]                AS              (case when ([prop_type] = 1) then (left(replace(right(rtrim([rrc]),6),' ',0),4)) else '' end),
    [rrc_lease_last_2]           AS              (case when ([prop_type] = 1) then (substring(replace(right(rtrim([rrc]),6),' ',0),5,2)) else '' end)
);


GO

CREATE NONCLUSTERED INDEX [idx_run_id]
    ON [dbo].[mineral_import_pritchard_abbott]([run_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_agent_number]
    ON [dbo].[mineral_import_pritchard_abbott]([agent_number] ASC) WITH (FILLFACTOR = 90);


GO

