CREATE TABLE [dbo].[T3] (
    [OBJECTID]                        INT              IDENTITY (1, 1) NOT NULL,
    [Shape]                           [sys].[geometry] NULL,
    [F3_Parcel_ID]                    NVARCHAR (15)    NULL,
    [F3_Prop_ID]                      INT              NULL,
    [F3_CENTROID_X]                   NUMERIC (38, 8)  NULL,
    [F3_CENTROID_Y]                   NUMERIC (38, 8)  NULL,
    [F3_Image]                        NVARCHAR (100)   NULL,
    [F3_Sketch]                       NVARCHAR (50)    NULL,
    [F3_owner_name]                   NVARCHAR (70)    NULL,
    [F3_prop_id_1]                    INT              NULL,
    [F3_geo_id]                       NVARCHAR (50)    NULL,
    [F3_legal_desc]                   NVARCHAR (254)   NULL,
    [F3_owner_addr]                   NVARCHAR (254)   NULL,
    [F3_situs_addr]                   NVARCHAR (173)   NULL,
    [F3_tax_code_a]                   NVARCHAR (23)    NULL,
    [F3_ImpVal]                       NUMERIC (38, 8)  NULL,
    [F3_LandVal]                      NUMERIC (38, 8)  NULL,
    [F3_MarketValu]                   NUMERIC (38, 8)  NULL,
    [F3_appraised_]                   NUMERIC (38, 8)  NULL,
    [F3_ag_use_val]                   NUMERIC (38, 8)  NULL,
    [F3_neighborho]                   NVARCHAR (100)   NULL,
    [F3_neighbor_1]                   NVARCHAR (10)    NULL,
    [F3_legal_acre]                   NUMERIC (38, 8)  NULL,
    [F3_land_sqft]                    NUMERIC (38, 8)  NULL,
    [F3_year_blt]                     INT              NULL,
    [F3_primary_us]                   NVARCHAR (10)    NULL,
    [F3_cycle]                        INT              NULL,
    [F3_Base_Corre]                   NVARCHAR (20)    NULL,
    [F3_DocNumber]                    NVARCHAR (254)   NULL,
    [F3_ImagePar]                     NVARCHAR (50)    NULL,
    [F3_SketchPar]                    NVARCHAR (50)    NULL,
    [F3_Shape__Are]                   NUMERIC (38, 8)  NULL,
    [F3_Shape__Len]                   NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_ParcelID]         INT              NULL,
    [Join_Tabel_csv_MapNumber]        NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_prop_id]          INT              NULL,
    [Join_Tabel_csv_situs_display]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_abs_subdv_desc]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_neighborhood]     INT              NULL,
    [Join_Tabel_csv_subset]           INT              NULL,
    [Join_Tabel_csv_reval]            INT              NULL,
    [Join_Tabel_csv_owner_name]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_tax_area]         NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_tax_area_id]      INT              NULL,
    [Join_Tabel_csv_tca]              NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_property_use_cd]  INT              NULL,
    [Join_Tabel_csv_prop_type_cd]     NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_property_use_des] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_PrimaryImproveme] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_state_cd]   INT              NULL,
    [Join_Tabel_csv_stories]          NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_num_imprv]        INT              NULL,
    [Join_Tabel_csv_TotalArea]        INT              NULL,
    [Join_Tabel_csv_finished_basemen] INT              NULL,
    [Join_Tabel_csv_unfinished_basem] INT              NULL,
    [Join_Tabel_csv_Total_Basement]   INT              NULL,
    [Join_Tabel_csv_YearBuilt]        INT              NULL,
    [Join_Tabel_csv_Age]              INT              NULL,
    [Join_Tabel_csv_class_cd]         INT              NULL,
    [Join_Tabel_csv_class_subclass_c] INT              NULL,
    [Join_Tabel_csv_Condition]        INT              NULL,
    [Join_Tabel_csv_imprv_det_desc]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Style]            NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Roofing]          NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Heating]          NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_ExtWall]          NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Bathrooms]        INT              NULL,
    [Join_Tabel_csv_HalfBaths]        INT              NULL,
    [Join_Tabel_csv_fireplace]        INT              NULL,
    [Join_Tabel_csv_foundation]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_fixture_count]    INT              NULL,
    [Join_Tabel_csv_fixture_Cost]     INT              NULL,
    [Join_Tabel_csv_fireplace_cost]   INT              NULL,
    [Join_Tabel_csv_Solar_Panels]     INT              NULL,
    [Join_Tabel_csv_attached_garage]  INT              NULL,
    [Join_Tabel_csv_detached_garage]  INT              NULL,
    [Join_Tabel_csv_Carport]          INT              NULL,
    [Join_Tabel_csv_Pole_building]    INT              NULL,
    [Join_Tabel_csv_sketch_area]      NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_calc_area]        NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_SPPSF]            NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_PPSF]             NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_BPPSF]            NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_Imprv_AdjVal]     INT              NULL,
    [Join_Tabel_csv_Current_unit_pri] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_flat_value]       INT              NULL,
    [Join_Tabel_csv_new_val]          INT              NULL,
    [Join_Tabel_csv_imprv_detail_new] INT              NULL,
    [Join_Tabel_csv_new_value_flag]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Land_UnitVal]     NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_ag_use_val]       INT              NULL,
    [Join_Tabel_csv_Previous_ag_use_] INT              NULL,
    [Join_Tabel_csv_Depr_RCN]         INT              NULL,
    [Join_Tabel_csv_RCN]              INT              NULL,
    [Join_Tabel_csv_imprv_det_cost_u] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_imprv_det_ms_uni] INT              NULL,
    [Join_Tabel_csv_adj_physical_pct] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_adj_economic_pct] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_adj_functional_p] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_adj_factor]       INT              NULL,
    [Join_Tabel_csv_yr_new]           INT              NULL,
    [Join_Tabel_csv_effective_year]   INT              NULL,
    [Join_Tabel_csv_use_up_for_pct_o] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_stories_multipli] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_det_adj_fa] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_load_factor]      INT              NULL,
    [Join_Tabel_csv_imprv_det_adj_va] INT              NULL,
    [Join_Tabel_csv_dep_pct_override] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_physical_pct_ove] INT              NULL,
    [Join_Tabel_csv_functional_pct_o] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_economic_pct_ove] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_size_adj_pct]     INT              NULL,
    [Join_Tabel_csv_size_adj_pct_ove] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_adj_amt]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_adj_desc]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_adj_method] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_mprv_adj_pc]      NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_adj_seq]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_imprv_adj_type_c] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_mass_adj_factor]  NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_recalc_error_fla] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_TotalMarketValue] INT              NULL,
    [Join_Tabel_csv_PreviousMarket]   INT              NULL,
    [Join_Tabel_csv_ImpVal]           INT              NULL,
    [Join_Tabel_csv_ImpVal_before]    INT              NULL,
    [Join_Tabel_csv_ImpVal_source]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_LandVal]          INT              NULL,
    [Join_Tabel_csv_LandVal_before]   INT              NULL,
    [Join_Tabel_csv_LandVal_source]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Land_State_cd]    INT              NULL,
    [Join_Tabel_csv_totalacres]       NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_land_sqft]        NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_current_ratio]    NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_excise_number]    INT              NULL,
    [Join_Tabel_csv_deed_type_cd]     NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_adjustedSalepric] INT              NULL,
    [Join_Tabel_csv_OriginalSalePric] INT              NULL,
    [Join_Tabel_csv_SaleDate]         NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_class_cd_at_sale] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_Imprv_unit_price] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_unit_price_diff]  NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_Land_unit_price_] NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_sl_ratio_type_cd] INT              NULL,
    [Join_Tabel_csv_sl_county_ratio_] INT              NULL,
    [Join_Tabel_csv_land_only_sale]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_recorded_dt]      DATETIME2 (7)    NULL,
    [Join_Tabel_csv_sale_comment]     NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_continue_current] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_ava]              NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_flood_zone]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_school_district]  NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_zoning]           NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_percent_complete] INT              NULL,
    [Join_Tabel_csv_permit_status]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_permit_complete_] DATETIME2 (7)    NULL,
    [Join_Tabel_csv_active_permits]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_permit_issue_dat] DATETIME2 (7)    NULL,
    [Join_Tabel_csv_permit_num]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_permit_desc]      NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_permit_cmnt]      NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_next_appraiser]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_last_appraiser]   NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_last_appraisal_d] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_gain_loss]        INT              NULL,
    [Join_Tabel_csv_pct_chg]          NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_imprv_gain_loss]  INT              NULL,
    [Join_Tabel_csv_land_gain_loss]   INT              NULL,
    [Join_Tabel_csv_Imprv_pct_chg]    NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_land_pct_chg]     NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_sl_Land_pct]      NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_sl_Imprv_pct]     NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_primary_situs]    NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_num]        NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_street_pre] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_street]     NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_street_suf] NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_unit]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_city]       NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_state]      NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_situs_zip]        NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_building_num]     NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_sub_num]          NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_img_path]         NVARCHAR (MAX)   NULL,
    [Join_Tabel_csv_XCoord]           NUMERIC (38, 8)  NULL,
    [Join_Tabel_csv_YCoord]           NUMERIC (38, 8)  NULL,
    PRIMARY KEY CLUSTERED ([OBJECTID] ASC)
);


GO

