CREATE TABLE [dbo].[transfer_tax_stmnt_entity_totals] (
    [levy_group_id]      INT              NOT NULL,
    [levy_group_yr]      INT              NOT NULL,
    [levy_run_id]        INT              NOT NULL,
    [sup_num]            INT              NULL,
    [stmnt_id]           INT              NOT NULL,
    [entity_1_id]        INT              NULL,
    [entity_1_name]      VARCHAR (70)     NULL,
    [entity_1_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_1_taxable]   NUMERIC (14)     NULL,
    [entity_1_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_2_id]        INT              NULL,
    [entity_2_name]      VARCHAR (70)     NULL,
    [entity_2_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_2_taxable]   NUMERIC (14)     NULL,
    [entity_2_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_3_id]        INT              NULL,
    [entity_3_name]      VARCHAR (70)     NULL,
    [entity_3_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_3_taxable]   NUMERIC (14)     NULL,
    [entity_3_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_4_id]        INT              NULL,
    [entity_4_name]      VARCHAR (70)     NULL,
    [entity_4_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_4_taxable]   NUMERIC (14)     NULL,
    [entity_4_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_5_id]        INT              NULL,
    [entity_5_name]      VARCHAR (70)     NULL,
    [entity_5_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_5_taxable]   NUMERIC (14)     NULL,
    [entity_5_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_6_id]        INT              NULL,
    [entity_6_name]      VARCHAR (70)     NULL,
    [entity_6_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_6_taxable]   NUMERIC (14)     NULL,
    [entity_6_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_7_id]        INT              NULL,
    [entity_7_name]      VARCHAR (70)     NULL,
    [entity_7_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_7_taxable]   NUMERIC (14)     NULL,
    [entity_7_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_8_id]        INT              NULL,
    [entity_8_name]      VARCHAR (70)     NULL,
    [entity_8_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_8_taxable]   NUMERIC (14)     NULL,
    [entity_8_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_9_id]        INT              NULL,
    [entity_9_name]      VARCHAR (70)     NULL,
    [entity_9_tax_amt]   NUMERIC (14, 2)  NULL,
    [entity_9_taxable]   NUMERIC (14)     NULL,
    [entity_9_tax_rate]  NUMERIC (13, 10) NULL,
    [entity_10_id]       INT              NULL,
    [entity_10_name]     VARCHAR (70)     NULL,
    [entity_10_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_10_taxable]  NUMERIC (14)     NULL,
    [entity_10_tax_rate] NUMERIC (13, 10) NULL,
    [entity_11_id]       INT              NULL,
    [entity_11_name]     VARCHAR (70)     NULL,
    [entity_11_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_11_taxable]  NUMERIC (14)     NULL,
    [entity_11_tax_rate] NUMERIC (13, 10) NULL,
    [entity_12_id]       INT              NULL,
    [entity_12_name]     VARCHAR (70)     NULL,
    [entity_12_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_12_taxable]  NUMERIC (14)     NULL,
    [entity_12_tax_rate] NUMERIC (13, 10) NULL,
    [entity_13_id]       INT              NULL,
    [entity_13_name]     VARCHAR (70)     NULL,
    [entity_13_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_13_taxable]  NUMERIC (14)     NULL,
    [entity_13_tax_rate] NUMERIC (13, 10) NULL,
    [entity_14_id]       INT              NULL,
    [entity_14_name]     VARCHAR (70)     NULL,
    [entity_14_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_14_taxable]  NUMERIC (14)     NULL,
    [entity_14_tax_rate] NUMERIC (13, 10) NULL,
    [entity_15_id]       INT              NULL,
    [entity_15_name]     VARCHAR (70)     NULL,
    [entity_15_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_15_taxable]  NUMERIC (14)     NULL,
    [entity_15_tax_rate] NUMERIC (13, 10) NULL,
    [entity_16_id]       INT              NULL,
    [entity_16_name]     VARCHAR (70)     NULL,
    [entity_16_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_16_taxable]  NUMERIC (14)     NULL,
    [entity_16_tax_rate] NUMERIC (13, 10) NULL,
    [entity_17_id]       INT              NULL,
    [entity_17_name]     VARCHAR (70)     NULL,
    [entity_17_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_17_taxable]  NUMERIC (14)     NULL,
    [entity_17_tax_rate] NUMERIC (13, 10) NULL,
    [entity_18_id]       INT              NULL,
    [entity_18_name]     VARCHAR (70)     NULL,
    [entity_18_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_18_taxable]  NUMERIC (14)     NULL,
    [entity_18_tax_rate] NUMERIC (13, 10) NULL,
    [entity_19_id]       INT              NULL,
    [entity_19_name]     VARCHAR (70)     NULL,
    [entity_19_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_19_taxable]  NUMERIC (14)     NULL,
    [entity_19_tax_rate] NUMERIC (13, 10) NULL,
    [entity_20_id]       INT              NULL,
    [entity_20_name]     VARCHAR (70)     NULL,
    [entity_20_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_20_taxable]  NUMERIC (14)     NULL,
    [entity_20_tax_rate] NUMERIC (13, 10) NULL,
    [entity_21_id]       INT              NULL,
    [entity_21_name]     VARCHAR (70)     NULL,
    [entity_21_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_21_taxable]  NUMERIC (14)     NULL,
    [entity_21_tax_rate] NUMERIC (13, 10) NULL,
    [entity_22_id]       INT              NULL,
    [entity_22_name]     VARCHAR (70)     NULL,
    [entity_22_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_22_taxable]  NUMERIC (14)     NULL,
    [entity_22_tax_rate] NUMERIC (13, 10) NULL,
    [entity_23_id]       INT              NULL,
    [entity_23_name]     VARCHAR (70)     NULL,
    [entity_23_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_23_taxable]  NUMERIC (14)     NULL,
    [entity_23_tax_rate] NUMERIC (13, 10) NULL,
    [entity_24_id]       INT              NULL,
    [entity_24_name]     VARCHAR (70)     NULL,
    [entity_24_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_24_taxable]  NUMERIC (14)     NULL,
    [entity_24_tax_rate] NUMERIC (13, 10) NULL,
    [entity_25_id]       INT              NULL,
    [entity_25_name]     VARCHAR (70)     NULL,
    [entity_25_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_25_taxable]  NUMERIC (14)     NULL,
    [entity_25_tax_rate] NUMERIC (13, 10) NULL,
    [entity_26_id]       INT              NULL,
    [entity_26_name]     VARCHAR (70)     NULL,
    [entity_26_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_26_taxable]  NUMERIC (14)     NULL,
    [entity_26_tax_rate] NUMERIC (13, 10) NULL,
    [entity_27_id]       INT              NULL,
    [entity_27_name]     VARCHAR (70)     NULL,
    [entity_27_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_27_taxable]  NUMERIC (14)     NULL,
    [entity_27_tax_rate] NUMERIC (13, 10) NULL,
    [entity_28_id]       INT              NULL,
    [entity_28_name]     VARCHAR (70)     NULL,
    [entity_28_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_28_taxable]  NUMERIC (14)     NULL,
    [entity_28_tax_rate] NUMERIC (13, 10) NULL,
    [entity_29_id]       INT              NULL,
    [entity_29_name]     VARCHAR (70)     NULL,
    [entity_29_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_29_taxable]  NUMERIC (14)     NULL,
    [entity_29_tax_rate] NUMERIC (13, 10) NULL,
    [entity_30_id]       INT              NULL,
    [entity_30_name]     VARCHAR (70)     NULL,
    [entity_30_tax_amt]  NUMERIC (14, 2)  NULL,
    [entity_30_taxable]  NUMERIC (14)     NULL,
    [entity_30_tax_rate] NUMERIC (13, 10) NULL,
    [oct_tax_due]        NUMERIC (14, 2)  NULL,
    [nov_tax_due]        NUMERIC (14, 2)  NULL,
    [dec_tax_due]        NUMERIC (14, 2)  NULL,
    [jan_tax_due]        NUMERIC (14, 2)  NULL,
    [feb_tax_due]        NUMERIC (14, 2)  NULL,
    [mar_tax_due]        NUMERIC (14, 2)  NULL,
    [apr_tax_due]        NUMERIC (14, 2)  NULL,
    [may_tax_due]        NUMERIC (14, 2)  NULL,
    [june_tax_due]       NUMERIC (14, 2)  NULL,
    [oct_pi_due]         NUMERIC (14, 2)  NULL,
    [nov_pi_due]         NUMERIC (14, 2)  NULL,
    [dec_pi_due]         NUMERIC (14, 2)  NULL,
    [jan_pi_due]         NUMERIC (14, 2)  NULL,
    [feb_pi_due]         NUMERIC (14, 2)  NULL,
    [mar_pi_due]         NUMERIC (14, 2)  NULL,
    [apr_pi_due]         NUMERIC (14, 2)  NULL,
    [may_pi_due]         NUMERIC (14, 2)  NULL,
    [june_pi_due]        NUMERIC (14, 2)  NULL,
    [taxes_saved]        NUMERIC (14, 2)  NULL,
    CONSTRAINT [CPK_transfer_tax_stmnt_entity_totals] PRIMARY KEY CLUSTERED ([levy_group_id] ASC, [levy_group_yr] ASC, [levy_run_id] ASC, [stmnt_id] ASC) WITH (FILLFACTOR = 100)
);


GO

