create view __aID_Unit_Price_Comm as 
select * from 
(SELECT  prop_id,
    prop_val_yr,
     imprv_det_type_cd

      ,--[imprv_det_val]
	  [unit_price]
	  --[imprv_det_area]
  FROM [pacs_oltp].[dbo].[imprv_detail]
 where prop_val_yr=(select appr_yr from pacs_system)--Change if you want soecific years
  )     as basedata
  pivot (
  --sum([imprv_det_area]
  sum([unit_price]
  --sum[imprv_det_val]
  )
  for imprv_det_type_cd
  in ([ANCHOR    ]
,[APART     ]
,[APARTRES  ]
,[ASPH      ]
,[AUDITORM  ]
,[AUTOSERV  ]
,[AUTOSHOW  ]
,[Balcony   ]
,[BANK      ]
,[BANQUET   ]
,[BOATD     ]
,[BOWL      ]
,[BRDCAST   ]
,[Canopy    ]
,[CanopyI   ]
,[CanopyL   ]
,[CASINO    ]
,[C-BSMTFIN ]
,[C-BSMTFWPF]
,[C-BSMTSFIN]
,[C-BSMTUFIN]
,[CHURCH    ]
,[CHURCHWSS ]
,[CINEMA    ]
,[CLUB      ]
,[CLUBHSE   ]
,[CMPTRCTR  ]
,[COLCLASS  ]
,[COLDSTOR  ]
,[COLLEGE   ]
,[COMMCTR   ]
,[COMPOOL   ]
,[COMSHOP   ]
,[CONC      ]
,[CONVENTN  ]
,[Conveyor  ]
,[CONVHOSP  ]
,[CONVMRKT  ]
,[CWAUTO    ]
,[CWDRVTH   ]
,[CWSLFSRV  ]
,[DAYCARE   ]
,[Deck      ]
,[DENTAL    ]
,[DISCOUNT  ]
,[DRIVERNG  ]
,[DRUGS     ]
,[DRYER     ]
,[ELEMSCH   ]
,[FASTFDMS  ]
,[FENCECL   ]
,[FENCEM    ]
,[FENCESPLT ]
,[FENCEVNL  ]
,[FENCEW    ]
,[FERTSTG   ]
,[FIRESTAF  ]
,[FIREVOL   ]
,[FITNESS   ]
,[FLATHOUSE ]
,[FLWSHP    ]
,[FRATRNL   ]
,[GCSTG     ]
,[GENOFF    ]
,[GENRET    ]
,[GOLFCRSE  ]
,[GOVTBLDG  ]
,[GRAINEL   ]
,[GRNHSCOM  ]
,[GRNHSHOOP ]
,[GRNHSSH   ]
,[GRPCARE   ]
,[HANGAR    ]
,[HANGARS   ]
,[HANGART   ]
,[HEALTH    ]
,[HIGHSCHL  ]
,[HMFG      ]
,[HOMEELDY  ]
,[HOSPITAL  ]
,[HOTEL FS  ]
,[HOTEL LS  ]
,[ICERINK   ]
,[INDFLEX   ]
,[INDSHELL  ]
,[INTENNIS  ]
,[KENNEL    ]
,[LAB       ]
,[LAMPPOST  ]
,[LCOMBLDG  ]
,[LCOMQNST  ]
,[LCOMSHED  ]
,[LCOMSHLT  ]
,[LGHTPOLE  ]
,[LIBRARY   ]
,[LMFG      ]
,[MARINA    ]
,[MARKET    ]
,[MEDOFF    ]
,[MEGAWHSD  ]
,[MEZZFD    ]
,[MEZZFO    ]
,[MEZZLCU   ]
,[MEZZSF    ]
,[MEZZUF    ]
,[MHPARK    ]
,[MIDDLSCH  ]
,[MINGOLF   ]
,[MINILUBE  ]
,[MINIMART  ]
,[MORTUARY  ]
,[MOTEL     ]
,[MULTRESA  ]
,[MULTRESS  ]
,[MUSEUM    ]
,[MWRHSE    ]
,[NBHSHOP   ]
,[PARK LVL  ]
,[PARKGAR   ]
,[RAILROAD  ]
,[REC ENC   ]
,[REGSHOP   ]
,[RELOCLASS ]
,[RELOOFFICE]
,[RESDEV    ]
,[RESGAR    ]
,[RESGARA   ]
,[RESSF     ]
,[RESTROOM  ]
,[RESTURNT  ]
,[RVPARK    ]
,[SCALES    ]
,[SCALESRR  ]
,[SCHCLASS  ]
,[SCHGYM    ]
,[SERVGAR   ]
,[SHDOFF    ]
,[SHED      ]
,[SKATING   ]
,[SNACK     ]
,[Spa       ]
,[STABLE    ]
,[STORGAR   ]
,[SUPRMRKT  ]
,[SURGCTR   ]
,[TANKAG    ]
,[TANKHP    ]
,[TANKUFS   ]
,[TAVERN    ]
,[THEATRE   ]
,[VacDbl    ]
,[VacSngl   ]
,[VEHICLECHG]
,[VETHOSP   ]
,[WALLS     ]
,[WATERSLIDE]
,[WHSEDISC  ]
,[WHSEDIST  ]
,[WHSEFOOD  ]
,[WHSESTOR  ]
,[WHSSHOW   ]
)) as pivottable

GO

