create view __pers_prop_description as 
SELECT  [prop_id]
      ,[prop_val_yr]
      ,[BUSINESS EQUIPMENT] as BUSINESS_EQUIPMENT
      ,[SUPPLIES -TOOLS]as SUPPLIES_TOOLS
      ,[INFORMATION ONLY] as INFORMATION_ONLY
      ,[LEASED] as Leased
      ,[BPP EQUPMEMT] as BPP_EQUPMEMT
      ,[IMFORMATION ONLY]as IMFORMATION_ONLY
      ,[INDUSTRIAL M&E] as INDUSTRIAL_M_E
      ,[BUSINESBPS EQUIPMENT] as BUSINESBPS_EQUIPMENT
      ,[BPP EQUIPMENT] as BPP_EQUIPMENT
      ,[BUSINESS EQUIPMEBPNT] as BUSINESS_EQUIPMEBPNT
      ,[AG MACHINER126792Y & EQUIPMENT] as AG_MACHINER126792Y_EQUIPMENT
      ,[B]
      ,[BUSINESS PERSONAL PROPERTY] as BUSINESS_PERSONAL_PROPERTY
      ,[SUPPLIES MONTHLY AVG]as  SUPPLIES_MONTHLY_AVG
      ,[BUSISNESS EQUIPMENT] as BUSISNESS_EQUIPMENT
      ,[BPP EQUIPTMENT] as BPP_EQUIPTMENT
      ,[BPP EQUPIMENT] as BPP_EQUPIMENT
      ,[BPP EQUIPIMENT]as BPP_EQUIPIMENT
      ,[AGA MACHINERY & EQUIPMENT]as AGA_MACHINERY_EQUIPMENT
      ,[BUSINESS EQUI0PMENT] as BUSINESS_EQUI0PMENT
      ,[1+]
      ,[SU]
      ,[BPP EQUIMPMENT]
      ,[AG MACHINERY & EQUIPMENT]
      ,[TITLE PLANTS]
      ,[BP]
      ,[06.5]as zero_six_five
      ,[BPP EQUIMENT] as BPP_EQUIMENT
      ,[SUPPLIES - SPARE PARTS] as SUPPLIES_SPARE_PARTS
      ,[Conversion type code]as Conversion_type_code
      ,[BPP EQUIPMENT0] as BPP_EQUIPMENT0
      ,[S]
      ,[SUPPLIES - FUEL]as SUPPLIES_FUEL
      ,[BPP EQUPMENT]as BPP_EQUPMENT
      ,[AG M&E]as AG_M_E
      ,[SUPPLIES]
      ,[INFORMATION]
      ,[BOATHOUSES]
  FROM [pacs_oltp].[dbo].[__PP_seg_PP_desc_pivot]

GO

