create view board_of_eq_current as 
SELECT[pacs_user_id]
      ,[case_id]
      ,[prop_val_yr]
      ,[prop_id]
      ,[sup_num]
      ,[owner_id]
      ,[pct_ownership]
      ,[geo_id]
      ,[prop_type_cd]
      ,[legal_desc]
      ,[situs]
      ,[entities]
      ,[exemption]
      ,[prot_taxpayer_comments]
      ,[prev_other]
      ,[prev_ag_mkt]
      ,[prev_ag_use]
      ,[prev_land]
      ,[prev_imprv]
      ,[prev_appraised]
      ,[prev_cap]
      ,[prev_assessed]
      ,[curr_other]
      ,[curr_ag_mkt]
      ,[curr_ag_use]
      ,[curr_land]
      ,[curr_imprv]
      ,[curr_appraised]
      ,[curr_cap]
      ,[curr_assessed]
      ,[diff_other]
      ,[diff_ag_mkt]
      ,[diff_ag_use]
      ,[diff_land]
      ,[diff_imprv]
      ,[diff_appraised]
      ,[diff_cap]
      ,[diff_assessed]
      ,[prot_assigned_panel]
      ,[docket_start_date_time]
      ,[prot_type]
      ,[prot_status]
      ,[meeting_appraiser_nm]
      ,[prev_market]
      ,[curr_market]
      ,[diff_market]
      ,[property_use_cd]
  FROM [pacs_oltp].[dbo].[_arb_protest_listing]
  where prop_val_yr=(select appr_yr-1 from pacs_system)

GO

