create view comm_floors_pv as 
SELECT [lrsn] as prop_id
      ,[extension]
      ,[bldg_section]
      ,[floor_id]
      ,[floor_number]
      ,[last_update]
      ,[status]
      ,[base_area]
      ,[eff_perimeter]
      ,[par]
      ,[comm_floor_int1]
      ,[comm_floor_int2]
      ,[comm_floor_flag1]
      ,[comm_floor_int3]
      ,[comm_floor_flag2]
      ,[comm_floor_int4]
      ,[comm_floor_flag3]
      ,[comm_floor_int5]
      ,[comm_floor_flag4]
      ,[comm_floor_int6]
      ,[comm_floor_flag5]
      ,[comm_floor_int7]
      ,[comm_floor_flag6]
      ,[comm_floor_int8]
      ,[comm_floor_flag7]
      ,[comm_floor_int9]
      ,[tot_sprkld_area]
      ,[eff_year]
      ,[improvement_id]
      ,[imp_line_flag]
      ,[comm_floor_text1]
  FROM [cnv_src_benton_2_14_2017].[dbo].[comm_floors]

GO

