create view income_computation_proval as
SELECT  [lrsn] as prop_id
      ,[income_group]
      ,[prop_type]
      ,[property_class]
      ,[eff_year]
      ,[year_group]
      ,[rent_class]
      ,[gfa]
      ,[nla]
      ,[size_group]
      ,[unit_of_measure]
      ,[units]
      ,[unit_rate]
      ,[gpi]
      ,[vac_pct]
      ,[vac_amt]
      ,[egi]
      ,[expense_type]
      ,[expense_rate]
      ,[expenses]
      ,[noi]
      ,[overall_rate]
      ,[value]
      ,[unit_value]
      ,[calc_date]
      ,[calc_uid]
      ,[status]
      ,[msn]
      ,[neighborhood]
      ,[date_cert]
      ,[ic_seq_no]
      ,[df1]
      ,[df2]
      ,[char10a]
      ,[char10b]
  FROM [cnv_src_benton_2_14_2017].[dbo].[income_computation_bak]

GO

