create view propval_income_breakdown as
SELECT  [lrsn] as prop_id
      ,[income_year]
      ,[use_group]
      ,[seq_no]
      ,[township_number]
      ,[rec_name]
      ,[business_name]
      ,[addr1]
      ,[addr2]
      ,[phone]
      ,[lease_type]
      ,[prop_type]
      ,[prop_subtype]
      ,[factor]
      ,[lease_term]
      ,[annual]
      ,[fixed_rent]
      ,[subsidized]
      ,[base_rent]
      ,[overage]
      ,[asking]
      ,[area]
      ,[sfprice]
      ,[units]
      ,[unit_price]
      ,[total]
      ,[baths]
      ,[memo_seq_no]
      ,[eff_date]
      ,[lease_begins]
      ,[lease_ends]
  FROM [cnv_src_benton_2_14_2017].[dbo].[ibreakdown]

GO

