"""-----------------------------------------------------------------------------
Name:           aiutils.py
Purpose:        Helper methods for raster analysis deep learning scripts
Author:         Esri Inc.
Created:        1/25/2024
Copyright:      (c)   Esri, Inc. 2024
ArcGIS Version: 11.3
-----------------------------------------------------------------------------"""
import json
import os

import arcpy

import rasterutils

# Metadata format of deep learning training data (image chips)
CYCLEGAN = "CycleGAN"
CHANGE_DETECTION = 'ChangeDetection'

# Deep learning training data folder files
MAP_TXT = "map.txt"
STATS_TXT = "stats.txt"
ACCUMULATED_STATS_JSON = "esri_accumulated_stats.json"
MODEL_DEFINITION_EMD = "esri_model_definition.emd"


def check_image_chips_files(folder_path: str) -> bool:
    """
    Check if a folder contains all image chips files

    A folder that contains map.txt, stats.txt, esri_accumulated_stats.json,
    esri_model_definition.emd indicate it is a valid image chips folder, or
    a subfolder of image chips folder in CycleGAN or ChangeDetection metadata
    formats.

    :param folder_path(str): The path of the folder to be validated if it is a
    output folder generated by Export Training Data For Deep Learning tool.
    :return (bool): Return true if the folder is a valid image chips folder;
    otherwise False.
    """
    try:
        chip_file_list = [
            MAP_TXT,
            STATS_TXT,
            ACCUMULATED_STATS_JSON,
            MODEL_DEFINITION_EMD
        ]

        # strip trailing forward slash
        folder_path = folder_path.rstrip("/")

        file_list = arcpy.gp.command(
            f"ListDatastore '{folder_path}' '{','.join(chip_file_list)}'")

        # Check if all 4 files exist under the directory to determine whether
        # it is a image chips folder
        return all(map(file_list.__contains__, chip_file_list))
    except Exception:
        return False


def get_image_chips_metadata(folder_path: str) -> dict:
    """
    Get the image chips metadata of an image chips folder.

    This function transfer esri_accumulated_stats.json to the scratch folder,
    read data in the JSON, and return the data. The data being read are
    TileSizeX, TileSizeY, NumTiles, and MetaDataMode.

    :param folder_path(str): The path of the folder which this function tries
    to get the image chips metadata
    :return (dict): The metadata read from the JSON, return in JSON format.
    Example return: 
    {
        "/rasterStores/MyRasterStore/imageChips123/": {
            "TileSizeX": 256,
            "TileSizeY": 256,
            "NumTiles": 384,
            "MetaDataMode": "PASCAL_VOC_rectangles"
        }
    }
    """
    try:
        folder_path_rstripped = folder_path.rstrip("/")
        folder_basename = os.path.basename(folder_path_rstripped)
        # Step 1. Transfer esri_accumulated_stats.json from datastpre to the scratch folder
        datastore_json_path = os.path.join(
            folder_path_rstripped,
            ACCUMULATED_STATS_JSON
        )
        destination_path = os.path.join(
            arcpy.env.scratchFolder,
            folder_basename
        )
        scratch_json_path = os.path.join(destination_path, ACCUMULATED_STATS_JSON)
        if os.path.exists(scratch_json_path):
            # Remove existed JSON in the scratch folder to prevent file name collision
            os.remove(scratch_json_path)

        # TransferFiles gp command does not take raster store and file share datastore path
        # Convert datastore path to actual path in those cases
        if datastore_json_path.startswith("/rasterStores") or datastore_json_path.startswith("/fileShares"):
            datastore_json_path = rasterutils._lookupdatastorepath(datastore_json_path)

        trasfer_file_message = arcpy.gp.command(
            f"TransferFiles '{datastore_json_path}' '{destination_path}'")
        if "Failed to transfer files" in trasfer_file_message:
            # TransferFiles gp command throws "Failed to transfer files" string
            # in its return when it fails to complete the job. Use the text to
            # check if TransferFiles command succeeds.
            return {}
    except Exception:
        return {}

    try:
        # Step 2. Read target metadata
        with open(scratch_json_path, "r") as json_file:
            stats_data = json.load(json_file)

        image_chips_metadata = {}
        image_chips_metadata["TileSizeX"] = stats_data.get("TileSizeX")
        image_chips_metadata["TileSizeY"] = stats_data.get("TileSizeY")
        image_chips_metadata["NumTiles"] = stats_data.get("NumTiles")
        image_chips_metadata["MetaDataMode"] = stats_data.get("MetaDataMode")
        return image_chips_metadata
    except Exception:
        return {}


def check_image_chips_folder_structure(folder_path: str) -> str:
    """
    Identify if a folder is a CycleGAN or ChangeDetection image chips folder.

    These two metadata formats has special image chips folder structure that
    needs extra actions to get esri_accumulated_stats.json

    :param folder_path (str): The path of the folder to be checked
    :return (str): Return CycleGAN or ChangeDetection if the folder structure
    matches these two metadata format output image chips folder structure.
    Otherwise return null string.
    """
    try:
        folder_path = folder_path.rstrip("/")
        file_list = arcpy.gp.command(f"ListDatastore '{folder_path}'")

        # Case 1: CycleGAN
        cyclegan_folders = ("A", "B")
        if all(map(file_list.__contains__, cyclegan_folders)):
            return CYCLEGAN

        # Case 2: ChangeDetection
        change_detection_folders = ("images_after", "images_before", "labels")
        if all(map(file_list.__contains__, change_detection_folders)):
            return CHANGE_DETECTION

        # Case 3: All other cases
        return ""
    except Exception:
        # If folder structure check fails, assume the folder structure is not
        # CycleGAN or ChangeDetection.
        return ""
