CREATE TABLE [dbo].[_arb_protest_listing] (
    [pacs_user_id]           INT              NOT NULL,
    [case_id]                INT              NOT NULL,
    [prop_val_yr]            NUMERIC (4)      NOT NULL,
    [prop_id]                INT              NOT NULL,
    [sup_num]                INT              NOT NULL,
    [owner_id]               INT              NOT NULL,
    [pct_ownership]          NUMERIC (13, 10) NULL,
    [geo_id]                 VARCHAR (50)     NULL,
    [prop_type_cd]           VARCHAR (5)      NULL,
    [legal_desc]             VARCHAR (255)    NULL,
    [situs]                  VARCHAR (255)    NULL,
    [entities]               VARCHAR (50)     NULL,
    [exemption]              VARCHAR (50)     NULL,
    [prot_taxpayer_comments] VARCHAR (1024)   NULL,
    [prev_other]             NUMERIC (14)     NULL,
    [prev_ag_mkt]            NUMERIC (14)     NULL,
    [prev_ag_use]            NUMERIC (14)     NULL,
    [prev_land]              NUMERIC (14)     NULL,
    [prev_imprv]             NUMERIC (14)     NULL,
    [prev_appraised]         NUMERIC (14)     NULL,
    [prev_cap]               NUMERIC (14)     NULL,
    [prev_assessed]          NUMERIC (14)     NULL,
    [curr_other]             NUMERIC (14)     NULL,
    [curr_ag_mkt]            NUMERIC (14)     NULL,
    [curr_ag_use]            NUMERIC (14)     NULL,
    [curr_land]              NUMERIC (14)     NULL,
    [curr_imprv]             NUMERIC (14)     NULL,
    [curr_appraised]         NUMERIC (14)     NULL,
    [curr_cap]               NUMERIC (14)     NULL,
    [curr_assessed]          NUMERIC (14)     NULL,
    [diff_other]             NUMERIC (14)     NULL,
    [diff_ag_mkt]            NUMERIC (14)     NULL,
    [diff_ag_use]            NUMERIC (14)     NULL,
    [diff_land]              NUMERIC (14)     NULL,
    [diff_imprv]             NUMERIC (14)     NULL,
    [diff_appraised]         NUMERIC (14)     NULL,
    [diff_cap]               NUMERIC (14)     NULL,
    [diff_assessed]          NUMERIC (14)     NULL,
    [prot_assigned_panel]    VARCHAR (10)     NULL,
    [docket_start_date_time] DATETIME         NULL,
    [prot_type]              VARCHAR (10)     NULL,
    [prot_status]            VARCHAR (10)     NULL,
    [meeting_appraiser_nm]   VARCHAR (40)     NULL,
    [prev_market]            NUMERIC (18)     NULL,
    [curr_market]            NUMERIC (18)     NULL,
    [diff_market]            NUMERIC (18)     NULL,
    [property_use_cd]        VARCHAR (10)     NULL,
    CONSTRAINT [CPK__arb_protest_listing] PRIMARY KEY CLUSTERED ([pacs_user_id] ASC, [prop_id] ASC, [prop_val_yr] ASC, [sup_num] ASC, [owner_id] ASC, [case_id] ASC) WITH (FILLFACTOR = 100)
);


GO

