CREATE TABLE [dbo].[deed_import_detail] (
    [batch_id]               INT           NOT NULL,
    [deed_num]               VARCHAR (50)  NOT NULL,
    [RecordID]               VARCHAR (50)  NULL,
    [deed_vol]               VARCHAR (50)  NULL,
    [deed_pg]                VARCHAR (50)  NULL,
    [deed_type_cd]           VARCHAR (50)  NULL,
    [deed_ex_date]           DATETIME      NULL,
    [deed_rec_date]          DATETIME      NULL,
    [grantor_last_name]      VARCHAR (50)  NULL,
    [grantor_first_name]     VARCHAR (50)  NULL,
    [grantor_full_name]      VARCHAR (50)  NULL,
    [grantor_addr1]          VARCHAR (50)  NULL,
    [grantor_addr2]          VARCHAR (50)  NULL,
    [grantor_addr3]          VARCHAR (50)  NULL,
    [grantor_city]           VARCHAR (50)  NULL,
    [grantor_state]          VARCHAR (50)  NULL,
    [grantor_zip]            VARCHAR (50)  NULL,
    [grantee_last_name]      VARCHAR (50)  NULL,
    [grantee_first_name]     VARCHAR (50)  NULL,
    [grantee_full_name]      VARCHAR (50)  NULL,
    [grantee_addr1]          VARCHAR (50)  NULL,
    [grantee_addr2]          VARCHAR (50)  NULL,
    [grantee_addr3]          VARCHAR (50)  NULL,
    [grantee_city]           VARCHAR (50)  NULL,
    [grantee_state]          VARCHAR (50)  NULL,
    [grantee_zip]            VARCHAR (50)  NULL,
    [legal_ncb]              VARCHAR (50)  NULL,
    [legal_lot_num]          VARCHAR (50)  NULL,
    [legal_block_num]        VARCHAR (50)  NULL,
    [legal_subdv]            VARCHAR (50)  NULL,
    [deed_consideration]     VARCHAR (255) NULL,
    [processed]              VARCHAR (1)   NULL,
    [document_no]            VARCHAR (255) NULL,
    [image_id]               VARCHAR (255) NULL,
    [image_filename]         VARCHAR (255) NULL,
    [multiple_records_found] BIT           NULL,
    [grantor_id]             INT           NULL,
    [grantee_id]             INT           NULL,
    [prop_id]                INT           NULL,
    [sales_id]               INT           NULL,
    CONSTRAINT [CPK_deed_import_detail] PRIMARY KEY CLUSTERED ([batch_id] ASC, [deed_num] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CFK_deed_import_detail_batch_id] FOREIGN KEY ([batch_id]) REFERENCES [dbo].[deed_import_batch] ([batch_id])
);


GO

