CREATE TABLE [dbo].[import_shared_prop_detail] (
    [lRunId]                  INT             NOT NULL,
    [lRecordId]               INT             NOT NULL,
    [szSendingId]             VARCHAR (35)    NOT NULL,
    [szReceivingId]           VARCHAR (35)    NULL,
    [szVendorCode]            VARCHAR (20)    NULL,
    [szYear]                  VARCHAR (5)     NULL,
    [szSupplement]            VARCHAR (12)    NULL,
    [szSupCd]                 VARCHAR (10)    NULL,
    [szSupComment]            VARCHAR (100)   NULL,
    [szGeoId]                 VARCHAR (50)    NULL,
    [szLegalDescription]      VARCHAR (200)   NULL,
    [szOwnerName]             VARCHAR (70)    NULL,
    [szAddress1]              VARCHAR (60)    NULL,
    [szAddress2]              VARCHAR (60)    NULL,
    [szAddress3]              VARCHAR (60)    NULL,
    [szCity]                  VARCHAR (50)    NULL,
    [szState]                 VARCHAR (50)    NULL,
    [szZip]                   VARCHAR (50)    NULL,
    [szSitusNumber]           VARCHAR (10)    NULL,
    [szSitusStreet]           VARCHAR (50)    NULL,
    [szSitusCity]             VARCHAR (30)    NULL,
    [szSitusState]            VARCHAR (2)     NULL,
    [szSitusZip]              VARCHAR (10)    NULL,
    [szARBIndicator]          VARCHAR (1)     NULL,
    [szARBDate]               VARCHAR (10)    NULL,
    [szARBStatus]             VARCHAR (5)     NULL,
    [fLandHS]                 NUMERIC (14)    NULL,
    [fLandNHS]                NUMERIC (14)    NULL,
    [fAgUse]                  NUMERIC (14)    NULL,
    [fAgMarket]               NUMERIC (14)    NULL,
    [fAgLoss]                 NUMERIC (14)    NULL,
    [fTimberUse]              NUMERIC (14)    NULL,
    [fTimberMarket]           NUMERIC (14)    NULL,
    [fTimberLoss]             NUMERIC (14)    NULL,
    [fImpHS]                  NUMERIC (14)    NULL,
    [fImpNHS]                 NUMERIC (14)    NULL,
    [fMarket]                 NUMERIC (14)    NULL,
    [fAppraised]              NUMERIC (14)    NULL,
    [fTenPercentCap]          NUMERIC (14)    NULL,
    [fAssessed]               NUMERIC (14)    NULL,
    [fImpNewValue]            NUMERIC (14)    NULL,
    [fLandNewValue]           NUMERIC (14)    NULL,
    [szProductivityCode]      VARCHAR (10)    NULL,
    [fAcreage]                NUMERIC (18, 4) NULL,
    [fAcreageLandHomesite]    NUMERIC (18, 4) NULL,
    [fAcreageLandNonHomesite] NUMERIC (18, 4) NULL,
    [fAcreageAgriculture]     NUMERIC (18, 4) NULL,
    [fAcreageTimber]          NUMERIC (18, 4) NULL,
    [szMapId]                 VARCHAR (25)    NULL,
    [szImprvHSStateCd]        VARCHAR (10)    NULL,
    [szImprvNHSStateCd]       VARCHAR (10)    NULL,
    [szLandHSStateCd]         VARCHAR (10)    NULL,
    [szLandNHSStateCd]        VARCHAR (10)    NULL,
    [szLandAgStateCd]         VARCHAR (10)    NULL,
    [szLandTimberStateCd]     VARCHAR (10)    NULL,
    [szPersonalStateCd]       VARCHAR (10)    NULL,
    [szMineralStateCd]        VARCHAR (10)    NULL,
    [szAutoStateCd]           VARCHAR (10)    NULL,
    [szImprvClass]            VARCHAR (10)    NULL,
    [szPTDLandType]           VARCHAR (10)    NULL,
    [szAppraiser]             VARCHAR (10)    NULL,
    [fSalePrice]              NUMERIC (14)    NULL,
    [szSaleDate]              VARCHAR (25)    NULL,
    [szDeedVolume]            VARCHAR (20)    NULL,
    [szDeedDate]              VARCHAR (25)    NULL,
    [szDeedPage]              VARCHAR (20)    NULL,
    [szExemptions]            VARCHAR (50)    NULL,
    [szEntities]              VARCHAR (50)    NULL,
    [szDBA]                   VARCHAR (50)    NULL,
    [szMultiOwner]            VARCHAR (1)     NULL,
    [szExportDate]            VARCHAR (10)    NULL,
    CONSTRAINT [CPK_import_shared_prop_detail] PRIMARY KEY CLUSTERED ([lRunId] ASC, [lRecordId] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CFK_import_shared_prop_detail_lRunId] FOREIGN KEY ([lRunId]) REFERENCES [dbo].[import_shared_prop] ([lRunId])
);


GO

