CREATE TABLE [dbo].[imprv_detail_rows_temp] (
    [prop_id]                    INT             NOT NULL,
    [prop_val_yr]                NUMERIC (4)     NOT NULL,
    [imprv_id]                   INT             NOT NULL,
    [imprv_det_id]               INT             NOT NULL,
    [sup_num]                    INT             NOT NULL,
    [sale_id]                    INT             NOT NULL,
    [imprv_det_class_cd]         VARCHAR (10)    NULL,
    [imprv_det_meth_cd]          VARCHAR (5)     NULL,
    [imprv_det_type_cd]          VARCHAR (10)    NULL,
    [seq_num]                    INT             NULL,
    [imprv_det_val]              NUMERIC (18)    NULL,
    [imprv_det_val_source]       VARCHAR (1)     NULL,
    [imprv_det_desc]             VARCHAR (100)   NULL,
    [imprv_det_area]             NUMERIC (18, 1) NULL,
    [imprv_det_area_type]        VARCHAR (1)     NULL,
    [condition_cd]               VARCHAR (5)     NULL,
    [cubic_area]                 NUMERIC (18, 1) NULL,
    [calc_area]                  NUMERIC (18, 1) NULL,
    [sketch_area]                NUMERIC (18, 1) NULL,
    [override_area]              VARCHAR (1)     NULL,
    [override_cubic_area]        VARCHAR (1)     NULL,
    [override_perimeter]         VARCHAR (1)     NULL,
    [perimeter]                  NUMERIC (18, 1) NULL,
    [length]                     NUMERIC (18, 1) NULL,
    [width]                      NUMERIC (18, 1) NULL,
    [height]                     NUMERIC (18, 1) NULL,
    [unit_price]                 NUMERIC (14, 2) NULL,
    [yr_built]                   NUMERIC (4)     NULL,
    [depreciation_yr]            NUMERIC (4)     NULL,
    [depreciation_yr_override]   VARCHAR (1)     NULL,
    [imprv_det_adj_val]          NUMERIC (14)    NULL,
    [imprv_det_flat_val]         NUMERIC (14)    NULL,
    [economic_pct]               NUMERIC (5, 2)  NULL,
    [physical_pct]               NUMERIC (5, 2)  NULL,
    [functional_pct]             NUMERIC (5, 2)  NULL,
    [economic_pct_override]      VARCHAR (1)     NULL,
    [physical_pct_override]      VARCHAR (1)     NULL,
    [functional_pct_override]    VARCHAR (1)     NULL,
    [economic_cmnt]              VARCHAR (255)   NULL,
    [physical_cmnt]              VARCHAR (255)   NULL,
    [functional_cmnt]            VARCHAR (255)   NULL,
    [percent_complete]           NUMERIC (5, 2)  NULL,
    [percent_complete_override]  VARCHAR (1)     NULL,
    [percent_complete_cmnt]      VARCHAR (255)   NULL,
    [new_value_flag]             VARCHAR (1)     NULL,
    [new_value]                  NUMERIC (14)    NULL,
    [new_value_override]         VARCHAR (1)     NULL,
    [use_up_for_pct_base]        VARCHAR (1)     NULL,
    [dep_pct]                    NUMERIC (5, 2)  NULL,
    [dep_pct_override]           VARCHAR (1)     NULL,
    [imprv_det_sub_class_cd]     VARCHAR (10)    NULL,
    [num_units]                  INT             NULL,
    [num_stories]                INT             NULL,
    [stories_multiplier]         BIT             NULL,
    [lease_class]                VARCHAR (10)    NULL,
    [actual_year_built_override] BIT             NOT NULL,
    [flat_value_comment]         VARCHAR (3000)  NULL,
    [flat_value_user_id]         INT             NULL,
    [flat_value_date]            DATETIME        NULL,
    [floor_number]               NUMERIC (4)     NULL,
    [load_factor]                NUMERIC (3)     NULL,
    [net_rentable_area]          NUMERIC (18)    NULL,
    [imprv_det_cost_unit_price]  NUMERIC (14, 2) NULL,
    [custom_calc_area_display]   INT             NULL,
    [custom_perimeter_display]   INT             NULL,
    [custom_imprv_detail_sketch] VARBINARY (MAX) NULL,
    [row_num]                    INT             IDENTITY (1, 1) NOT NULL
);


GO

CREATE CLUSTERED INDEX [idx_imprv_detail_rows_temp]
    ON [dbo].[imprv_detail_rows_temp]([row_num] ASC);


GO

