CREATE TABLE [dbo].[PARCEL_PACS] (
    [geo_id]            VARCHAR (30)   NULL,
    [prop_id]           INT            NULL,
    [prop_val_yr]       INT            NULL,
    [sup_num]           INT            NULL,
    [Owner_ID]          INT            NULL,
    [File_As_Name]      VARCHAR (70)   NULL,
    [Last_Name]         VARCHAR (30)   NULL,
    [First_Name]        VARCHAR (30)   NULL,
    [Addr_Line1]        VARCHAR (60)   NULL,
    [Addr_Line2]        VARCHAR (60)   NULL,
    [Addr_Line3]        VARCHAR (60)   NULL,
    [Addr_City]         VARCHAR (50)   NULL,
    [Addr_State]        VARCHAR (50)   NULL,
    [Addr_Zip]          VARCHAR (10)   NULL,
    [Use_Code]          VARCHAR (4)    NULL,
    [Use_Desc]          VARCHAR (72)   NULL,
    [Use_Code_2]        VARCHAR (4)    NULL,
    [Use_Desc_2]        VARCHAR (72)   NULL,
    [State_Code]        VARCHAR (2)    NULL,
    [Tax_Code]          VARCHAR (23)   NULL,
    [School_Dist]       VARCHAR (24)   NULL,
    [Fire_Dist]         VARCHAR (17)   NULL,
    [Planning_Area]     VARCHAR (40)   NULL,
    [Ttl_Acres]         DECIMAL (7, 2) NULL,
    [Legal_Desc]        VARCHAR (150)  NULL,
    [Cycle]             INT            NULL,
    [Hood_Code]         VARCHAR (10)   NULL,
    [Hood_Desc]         VARCHAR (100)  NULL,
    [Subdv_Code]        VARCHAR (10)   NULL,
    [Subdv_Desc]        VARCHAR (100)  NULL,
    [Region_Code]       VARCHAR (10)   NULL,
    [Region_Desc]       VARCHAR (100)  NULL,
    [Township]          VARCHAR (3)    NULL,
    [Range]             VARCHAR (3)    NULL,
    [Section]           VARCHAR (2)    NULL,
    [Qtr_Section]       VARCHAR (5)    NULL,
    [Tax_Status]        VARCHAR (12)   NULL,
    [Situs_Addr]        VARCHAR (100)  NULL,
    [Situs_City]        VARCHAR (30)   NULL,
    [Situs_Zip]         VARCHAR (10)   NULL,
    [Sewer_Flag]        CHAR (1)       NULL,
    [FPtrl_Flag]        CHAR (1)       NULL,
    [FPtrl_Acres]       DECIMAL (7, 2) NULL,
    [CWtr_Flag]         CHAR (1)       NULL,
    [Weed_Flag]         CHAR (1)       NULL,
    [PLDrn_Flag]        CHAR (1)       NULL,
    [OSS_Flag]          CHAR (1)       NULL,
    [OSS_Count]         INT            NULL,
    [CertifiedFMV_Year] INT            NULL,
    [CFMV_Imps]         NUMERIC (14)   NULL,
    [CFMV_Land]         NUMERIC (14)   NULL,
    [CFMV_Total]        NUMERIC (14)   NULL,
    [WorkingFMV_Year]   INT            NULL,
    [WFMV_Imps]         NUMERIC (14)   NULL,
    [WFMV_Land]         NUMERIC (14)   NULL,
    [WFMV_Total]        NUMERIC (14)   NULL,
    [Notes]             VARCHAR (1000) NULL,
    [Sale_Reet]         INT            NULL,
    [Sale_Deed]         VARCHAR (10)   NULL,
    [Sale_Price]        NUMERIC (14)   NULL,
    [Sale_Date]         DATETIME       NULL,
    [Sale_Multi]        CHAR (1)       NOT NULL,
    [Sale_RCode]        VARCHAR (5)    NULL,
    [Sale_RDesc]        VARCHAR (100)  NULL,
    [Attr_Sewer]        VARCHAR (50)   NULL,
    [Attr_Drainage]     VARCHAR (50)   NULL,
    [Attr_Bank]         VARCHAR (50)   NULL,
    [Attr_View1]        VARCHAR (50)   NULL,
    [Attr_View2]        VARCHAR (50)   NULL,
    [Attr_Zoning1]      VARCHAR (100)  NULL,
    [Attr_Zoning2]      VARCHAR (100)  NULL,
    [Attr_Zoning3]      VARCHAR (100)  NULL,
    [InActive_Date]     DATETIME       NULL,
    [PACSWeb_Year]      INT            NULL,
    [Down_Date]         DATETIME       NULL
);


GO

