CREATE TABLE [dbo].[profile_sale_stats] (
    [run_id]                                  INT             NOT NULL,
    [detail_id]                               INT             NOT NULL,
    [imprv_ct]                                INT             NULL,
    [imprv_max_ma]                            NUMERIC (14)    NULL,
    [imprv_min_ma]                            NUMERIC (14)    NULL,
    [imprv_avg_ma]                            NUMERIC (14)    NULL,
    [imprv_mid_ma]                            NUMERIC (14)    NULL,
    [imprv_cod_ma]                            NUMERIC (18, 5) NULL,
    [imprv_cov_ma]                            NUMERIC (18, 5) NULL,
    [imprv_max_mkt]                           NUMERIC (14)    NULL,
    [imprv_min_mkt]                           NUMERIC (14)    NULL,
    [imprv_avg_mkt]                           NUMERIC (14)    NULL,
    [imprv_mid_mkt]                           NUMERIC (14)    NULL,
    [imprv_cod_mkt]                           NUMERIC (18, 5) NULL,
    [imprv_cov_mkt]                           NUMERIC (18, 5) NULL,
    [imprv_max_land_pct]                      NUMERIC (5, 4)  NULL,
    [imprv_min_land_pct]                      NUMERIC (5, 4)  NULL,
    [imprv_avg_land_pct]                      NUMERIC (5, 4)  NULL,
    [imprv_mid_land_pct]                      NUMERIC (5, 4)  NULL,
    [imprv_cod_land_pct]                      NUMERIC (18, 5) NULL,
    [imprv_cov_land_pct]                      NUMERIC (18, 5) NULL,
    [imprv_max_mkt_pct]                       NUMERIC (14, 2) NULL,
    [imprv_min_mkt_pct]                       NUMERIC (14, 2) NULL,
    [imprv_avg_mkt_pct]                       NUMERIC (14, 2) NULL,
    [imprv_mid_mkt_pct]                       NUMERIC (14, 2) NULL,
    [imprv_cod_mkt_pct]                       NUMERIC (18, 5) NULL,
    [imprv_cov_mkt_pct]                       NUMERIC (18, 5) NULL,
    [land_sqft_ct]                            INT             NULL,
    [land_max_sqft]                           NUMERIC (18, 2) NULL,
    [land_min_sqft]                           NUMERIC (18, 2) NULL,
    [land_avg_sqft]                           NUMERIC (18, 2) NULL,
    [land_mid_sqft]                           NUMERIC (18, 2) NULL,
    [land_cod_sqft]                           NUMERIC (18, 5) NULL,
    [land_cov_sqft]                           NUMERIC (18, 5) NULL,
    [land_max_mkt_sqft]                       NUMERIC (14)    NULL,
    [land_min_mkt_sqft]                       NUMERIC (14)    NULL,
    [land_avg_mkt_sqft]                       NUMERIC (14)    NULL,
    [land_mid_mkt_sqft]                       NUMERIC (14)    NULL,
    [land_cod_mkt_sqft]                       NUMERIC (18, 5) NULL,
    [land_cov_mkt_sqft]                       NUMERIC (18, 5) NULL,
    [land_max_mkt_sqft_pct]                   NUMERIC (14, 2) NULL,
    [land_min_mkt_sqft_pct]                   NUMERIC (14, 2) NULL,
    [land_avg_mkt_sqft_pct]                   NUMERIC (14, 2) NULL,
    [land_mid_mkt_sqft_pct]                   NUMERIC (14, 2) NULL,
    [land_cod_mkt_sqft_pct]                   NUMERIC (18, 5) NULL,
    [land_cov_mkt_sqft_pct]                   NUMERIC (18, 5) NULL,
    [sale_imprv_ct]                           INT             NULL,
    [sale_price_imprv_max]                    NUMERIC (14)    NULL,
    [sale_price_imprv_min]                    NUMERIC (14)    NULL,
    [sale_price_imprv_avg]                    NUMERIC (14)    NULL,
    [sale_price_imprv_mid]                    NUMERIC (14)    NULL,
    [sale_price_imprv_cod]                    NUMERIC (18, 5) NULL,
    [sale_price_imprv_cov]                    NUMERIC (18, 5) NULL,
    [sale_price_max_pct]                      NUMERIC (18, 2) NULL,
    [sale_price_min_pct]                      NUMERIC (18, 2) NULL,
    [sale_price_avg_pct]                      NUMERIC (18, 2) NULL,
    [sale_price_mid_pct]                      NUMERIC (18, 2) NULL,
    [sale_price_cod_pct]                      NUMERIC (18, 5) NULL,
    [sale_price_cov_pct]                      NUMERIC (18, 5) NULL,
    [sale_price_w_sale_ct_pct]                INT             NULL,
    [sale_price_w_sale_max_pct]               NUMERIC (18, 2) NULL,
    [sale_price_w_sale_min_pct]               NUMERIC (18, 2) NULL,
    [sale_price_w_sale_avg_pct]               NUMERIC (18, 2) NULL,
    [sale_price_w_sale_mid_pct]               NUMERIC (18, 2) NULL,
    [sale_price_w_sale_cod_pct]               NUMERIC (18, 5) NULL,
    [sale_price_w_sale_cov_pct]               NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_ct]               INT             NULL,
    [sale_price_imprv_ratio_max]              NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_min]              NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_avg]              NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_mid]              NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_cod]              NUMERIC (18, 5) NULL,
    [sale_price_imprv_ratio_cov]              NUMERIC (18, 5) NULL,
    [sale_land_sqft_ct]                       INT             NULL,
    [sale_price_land_mkt_sqft_max]            NUMERIC (14)    NULL,
    [sale_price_land_mkt_sqft_min]            NUMERIC (14)    NULL,
    [sale_price_land_mkt_sqft_avg]            NUMERIC (14)    NULL,
    [sale_price_land_mkt_sqft_mid]            NUMERIC (14)    NULL,
    [sale_price_land_mkt_sqft_cod]            NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_sqft_cov]            NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_sqft_pct_max]        NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_pct_min]        NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_pct_avg]        NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_pct_mid]        NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_pct_cod]        NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_sqft_pct_cov]        NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_sqft_w_sale_ct]      INT             NULL,
    [sale_price_land_mkt_sqft_w_sale_max_pct] NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_w_sale_min_pct] NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_w_sale_avg_pct] NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_w_sale_mid_pct] NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_sqft_w_sale_cod_pct] NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_sqft_w_sale_cov_pct] NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_ct]           INT             NULL,
    [sale_price_land_ratio_sqft_max]          NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_min]          NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_avg]          NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_mid]          NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_cod]          NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_sqft_cov]          NUMERIC (18, 5) NULL,
    [land_lot_ct]                             INT             NULL,
    [land_max_lot]                            NUMERIC (18, 2) NULL,
    [land_min_lot]                            NUMERIC (18, 2) NULL,
    [land_avg_lot]                            NUMERIC (18, 2) NULL,
    [land_mid_lot]                            NUMERIC (18, 2) NULL,
    [land_cod_lot]                            NUMERIC (18, 5) NULL,
    [land_cov_lot]                            NUMERIC (18, 5) NULL,
    [land_max_mkt_lot]                        NUMERIC (14)    NULL,
    [land_min_mkt_lot]                        NUMERIC (14)    NULL,
    [land_avg_mkt_lot]                        NUMERIC (14)    NULL,
    [land_mid_mkt_lot]                        NUMERIC (14)    NULL,
    [land_cod_mkt_lot]                        NUMERIC (18, 5) NULL,
    [land_cov_mkt_lot]                        NUMERIC (18, 5) NULL,
    [land_max_mkt_lot_pct]                    NUMERIC (14, 2) NULL,
    [land_min_mkt_lot_pct]                    NUMERIC (14, 2) NULL,
    [land_avg_mkt_lot_pct]                    NUMERIC (14, 2) NULL,
    [land_mid_mkt_lot_pct]                    NUMERIC (14, 2) NULL,
    [land_cod_mkt_lot_pct]                    NUMERIC (18, 5) NULL,
    [land_cov_mkt_lot_pct]                    NUMERIC (18, 5) NULL,
    [sale_land_lot_ct]                        INT             NULL,
    [sale_price_land_mkt_lot_max]             NUMERIC (14)    NULL,
    [sale_price_land_mkt_lot_min]             NUMERIC (14)    NULL,
    [sale_price_land_mkt_lot_avg]             NUMERIC (14)    NULL,
    [sale_price_land_mkt_lot_mid]             NUMERIC (14)    NULL,
    [sale_price_land_mkt_lot_cod]             NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_cov]             NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_max]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_min]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_avg]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_mid]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_cod]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_pct_cov]         NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_w_sale_ct]       INT             NULL,
    [sale_price_land_mkt_lot_w_sale_max_pct]  NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_lot_w_sale_min_pct]  NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_lot_w_sale_avg_pct]  NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_lot_w_sale_mid_pct]  NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_lot_w_sale_cod_pct]  NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_lot_w_sale_cov_pct]  NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_ct]            INT             NULL,
    [sale_price_land_ratio_lot_max]           NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_min]           NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_avg]           NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_mid]           NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_cod]           NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_lot_cov]           NUMERIC (18, 5) NULL,
    [land_ff_ct]                              INT             NULL,
    [land_max_ff]                             NUMERIC (18, 2) NULL,
    [land_min_ff]                             NUMERIC (18, 2) NULL,
    [land_avg_ff]                             NUMERIC (18, 2) NULL,
    [land_mid_ff]                             NUMERIC (18, 2) NULL,
    [land_cod_ff]                             NUMERIC (18, 5) NULL,
    [land_cov_ff]                             NUMERIC (18, 5) NULL,
    [land_max_mkt_ff]                         NUMERIC (14)    NULL,
    [land_min_mkt_ff]                         NUMERIC (14)    NULL,
    [land_avg_mkt_ff]                         NUMERIC (14)    NULL,
    [land_mid_mkt_ff]                         NUMERIC (14)    NULL,
    [land_cod_mkt_ff]                         NUMERIC (18, 5) NULL,
    [land_cov_mkt_ff]                         NUMERIC (18, 5) NULL,
    [land_max_mkt_ff_pct]                     NUMERIC (14, 2) NULL,
    [land_min_mkt_ff_pct]                     NUMERIC (14, 2) NULL,
    [land_avg_mkt_ff_pct]                     NUMERIC (14, 2) NULL,
    [land_mid_mkt_ff_pct]                     NUMERIC (14, 2) NULL,
    [land_cod_mkt_ff_pct]                     NUMERIC (18, 5) NULL,
    [land_cov_mkt_ff_pct]                     NUMERIC (18, 5) NULL,
    [sale_land_ff_ct]                         INT             NULL,
    [sale_price_land_mkt_ff_max]              NUMERIC (14)    NULL,
    [sale_price_land_mkt_ff_min]              NUMERIC (14)    NULL,
    [sale_price_land_mkt_ff_avg]              NUMERIC (14)    NULL,
    [sale_price_land_mkt_ff_mid]              NUMERIC (14)    NULL,
    [sale_price_land_mkt_ff_cod]              NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_cov]              NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_max]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_min]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_avg]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_mid]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_cod]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_pct_cov]          NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_w_sale_ct]        INT             NULL,
    [sale_price_land_mkt_ff_w_sale_max_pct]   NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_ff_w_sale_min_pct]   NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_ff_w_sale_avg_pct]   NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_ff_w_sale_mid_pct]   NUMERIC (18, 2) NULL,
    [sale_price_land_mkt_ff_w_sale_cod_pct]   NUMERIC (18, 5) NULL,
    [sale_price_land_mkt_ff_w_sale_cov_pct]   NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_ct]             INT             NULL,
    [sale_price_land_ratio_ff_max]            NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_min]            NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_avg]            NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_mid]            NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_cod]            NUMERIC (18, 5) NULL,
    [sale_price_land_ratio_ff_cov]            NUMERIC (18, 5) NULL,
    [sale_gim_ct]                             INT             NULL,
    [sale_gim_monthly_max]                    NUMERIC (18, 2) NULL,
    [sale_gim_monthly_min]                    NUMERIC (18, 2) NULL,
    [sale_gim_monthly_avg]                    NUMERIC (18, 2) NULL,
    [sale_gim_monthly_mid]                    NUMERIC (18, 2) NULL,
    [sale_gim_monthly_cod]                    NUMERIC (18, 5) NULL,
    [sale_gim_monthly_cov]                    NUMERIC (18, 5) NULL,
    [sale_gim_annual_max]                     NUMERIC (18, 2) NULL,
    [sale_gim_annual_min]                     NUMERIC (18, 2) NULL,
    [sale_gim_annual_avg]                     NUMERIC (18, 2) NULL,
    [sale_gim_annual_mid]                     NUMERIC (18, 2) NULL,
    [sale_gim_annual_cod]                     NUMERIC (18, 5) NULL,
    [sale_gim_annual_cov]                     NUMERIC (18, 5) NULL,
    CONSTRAINT [CPK_profile_sale_stats] PRIMARY KEY CLUSTERED ([run_id] ASC, [detail_id] ASC) WITH (FILLFACTOR = 100)
);


GO

