CREATE TABLE [dbo].[sales_ratio_report] (
    [dataset_id]                  INT             NOT NULL,
    [row_id]                      INT             IDENTITY (1, 1) NOT NULL,
    [chg_of_owner_id]             INT             NOT NULL,
    [sort1]                       VARCHAR (100)   NOT NULL,
    [sort2]                       VARCHAR (100)   NOT NULL,
    [sort3]                       VARCHAR (100)   NOT NULL,
    [sort4]                       VARCHAR (100)   NOT NULL,
    [sort1_desc]                  VARCHAR (100)   NULL,
    [sort2_desc]                  VARCHAR (100)   NULL,
    [sort3_desc]                  VARCHAR (100)   NULL,
    [sort4_desc]                  VARCHAR (100)   NULL,
    [summary1]                    CHAR (1)        NULL,
    [summary2]                    CHAR (1)        NULL,
    [summary3]                    CHAR (1)        NULL,
    [summary4]                    CHAR (1)        NULL,
    [state_cd]                    CHAR (5)        NULL,
    [school_id]                   INT             NULL,
    [school_cd]                   CHAR (5)        NULL,
    [city_id]                     INT             NULL,
    [city_cd]                     CHAR (5)        NULL,
    [dimensions]                  VARCHAR (80)    NULL,
    [imprv_class]                 CHAR (10)       NULL,
    [actual_yr_built]             NUMERIC (4)     NULL,
    [eff_yr_built]                NUMERIC (4)     NULL,
    [living_area_sqft]            NUMERIC (18, 1) NULL,
    [land_type_cd]                CHAR (10)       NULL,
    [appraised_val]               NUMERIC (14)    NULL,
    [land_val]                    NUMERIC (14)    NULL,
    [imprv_val]                   NUMERIC (14)    NULL,
    [appraiser_id]                INT             NULL,
    [geo_id]                      VARCHAR (50)    NULL,
    [map_id]                      VARCHAR (20)    NULL,
    [dba_name]                    VARCHAR (50)    NULL,
    [prop_use_cd]                 VARCHAR (10)    NULL,
    [imprv_sub_class]             VARCHAR (10)    NULL,
    [condition_cd]                VARCHAR (5)     NULL,
    [heat_ac_cd]                  VARCHAR (75)    NULL,
    [additive_val]                NUMERIC (14)    NULL,
    [percent_complete]            NUMERIC (5, 2)  NULL,
    [sub_market_cd]               VARCHAR (10)    NULL,
    [land_total_sqft]             NUMERIC (18, 2) NULL,
    [land_total_acres]            NUMERIC (18, 4) NULL,
    [lbratio]                     NUMERIC (14, 5) NULL,
    [vac_pct]                     NUMERIC (5, 2)  NULL,
    [cap_rate]                    NUMERIC (5, 2)  NULL,
    [gba]                         NUMERIC (14)    NULL,
    [gba_sqft]                    NUMERIC (14, 2) NULL,
    [nra]                         NUMERIC (14)    NULL,
    [nra_sqft]                    NUMERIC (14, 2) NULL,
    [buyer_name]                  VARCHAR (70)    NULL,
    [seller_name]                 VARCHAR (70)    NULL,
    [sale_dt]                     DATETIME        NULL,
    [confirmed_source]            VARCHAR (30)    NULL,
    [confirmed_by]                VARCHAR (30)    NULL,
    [confirmed_dt]                DATETIME        NULL,
    [deed_dt]                     DATETIME        NULL,
    [deed_num]                    VARCHAR (50)    NULL,
    [deed_book_id]                CHAR (20)       NULL,
    [deed_book_page]              CHAR (20)       NULL,
    [deed_comment]                VARCHAR (500)   NULL,
    [sl_comment]                  VARCHAR (500)   NULL,
    [sl_price]                    NUMERIC (14)    NULL,
    [sl_adj_price]                NUMERIC (14)    NULL,
    [sl_type_cd]                  CHAR (5)        NULL,
    [sl_ratio_cd]                 CHAR (5)        NULL,
    [sl_adj_reason]               VARCHAR (50)    NULL,
    [sl_county_ratio_cd]          VARCHAR (10)    NULL,
    [include_no_calc]             CHAR (1)        NULL,
    [include_reason]              VARCHAR (30)    NULL,
    [supress_detail]              CHAR (1)        NULL,
    [true_sl_price]               NUMERIC (14)    NULL,
    [appr_avg_price_per_sqft]     NUMERIC (14, 2) NULL,
    [sale_avg_price_per_sqft]     NUMERIC (14, 2) NULL,
    [sales_ratio]                 NUMERIC (14, 5) NULL,
    [prop_ratio]                  NUMERIC (14, 5) NULL,
    [land_ratio]                  NUMERIC (14, 5) NULL,
    [land_market_ratio]           NUMERIC (14, 5) NULL,
    [sort1_temp_avg_dev]          NUMERIC (14, 4) NULL,
    [sort1_temp_median]           NUMERIC (14, 4) NULL,
    [sort1_temp_avg]              NUMERIC (14, 4) NULL,
    [sort1_temp_cod]              NUMERIC (14, 4) NULL,
    [sort1_temp_pop_var]          NUMERIC (18, 4) NULL,
    [sort1_temp_stdev]            NUMERIC (14, 4) NULL,
    [sort1_temp_prd]              NUMERIC (14, 4) NULL,
    [sort1_temp_wt_mean]          NUMERIC (14, 4) NULL,
    [sort1_temp_min]              NUMERIC (14, 4) NULL,
    [sort1_temp_max]              NUMERIC (14, 4) NULL,
    [sort1_temp_mean]             NUMERIC (14, 4) NULL,
    [sort1_land_ratio_mean]       NUMERIC (14, 5) NULL,
    [sort1_land_ratio_median]     NUMERIC (14, 5) NULL,
    [sort1_land_mkt_ratio_mean]   NUMERIC (14, 5) NULL,
    [sort1_land_mkt_ratio_median] NUMERIC (14, 5) NULL,
    [sort1_market_median]         NUMERIC (14)    NULL,
    [sort1_sale_price_median]     NUMERIC (14)    NULL,
    [sort2_temp_avg_dev]          NUMERIC (14, 4) NULL,
    [sort2_temp_median]           NUMERIC (14, 4) NULL,
    [sort2_temp_avg]              NUMERIC (14, 4) NULL,
    [sort2_temp_cod]              NUMERIC (14, 4) NULL,
    [sort2_temp_pop_var]          NUMERIC (14, 4) NULL,
    [sort2_temp_stdev]            NUMERIC (14, 4) NULL,
    [sort2_temp_prd]              NUMERIC (14, 4) NULL,
    [sort2_temp_wt_mean]          NUMERIC (14, 4) NULL,
    [sort2_temp_min]              NUMERIC (14, 4) NULL,
    [sort2_temp_max]              NUMERIC (14, 4) NULL,
    [sort2_temp_mean]             NUMERIC (14, 4) NULL,
    [sort2_land_ratio_mean]       NUMERIC (14, 5) NULL,
    [sort2_land_ratio_median]     NUMERIC (14, 5) NULL,
    [sort2_land_mkt_ratio_mean]   NUMERIC (14, 5) NULL,
    [sort2_land_mkt_ratio_median] NUMERIC (14, 5) NULL,
    [sort2_market_median]         NUMERIC (14)    NULL,
    [sort2_sale_price_median]     NUMERIC (14)    NULL,
    [sort3_temp_avg_dev]          NUMERIC (14, 4) NULL,
    [sort3_temp_median]           NUMERIC (14, 4) NULL,
    [sort3_temp_avg]              NUMERIC (14, 4) NULL,
    [sort3_temp_cod]              NUMERIC (14, 4) NULL,
    [sort3_temp_pop_var]          NUMERIC (14, 4) NULL,
    [sort3_temp_stdev]            NUMERIC (14, 4) NULL,
    [sort3_temp_prd]              NUMERIC (14, 4) NULL,
    [sort3_temp_wt_mean]          NUMERIC (14, 4) NULL,
    [sort3_temp_min]              NUMERIC (14, 4) NULL,
    [sort3_temp_max]              NUMERIC (14, 4) NULL,
    [sort3_temp_mean]             NUMERIC (14, 4) NULL,
    [sort3_land_ratio_mean]       NUMERIC (14, 5) NULL,
    [sort3_land_ratio_median]     NUMERIC (14, 5) NULL,
    [sort3_land_mkt_ratio_mean]   NUMERIC (14, 5) NULL,
    [sort3_land_mkt_ratio_median] NUMERIC (14, 5) NULL,
    [sort3_market_median]         NUMERIC (14)    NULL,
    [sort3_sale_price_median]     NUMERIC (14)    NULL,
    [sort4_temp_avg_dev]          NUMERIC (14, 4) NULL,
    [sort4_temp_median]           NUMERIC (14, 4) NULL,
    [sort4_temp_avg]              NUMERIC (14, 4) NULL,
    [sort4_temp_cod]              NUMERIC (14, 4) NULL,
    [sort4_temp_pop_var]          NUMERIC (14, 4) NULL,
    [sort4_temp_stdev]            NUMERIC (14, 4) NULL,
    [sort4_temp_prd]              NUMERIC (14, 4) NULL,
    [sort4_temp_wt_mean]          NUMERIC (14, 4) NULL,
    [sort4_temp_min]              NUMERIC (14, 4) NULL,
    [sort4_temp_max]              NUMERIC (14, 4) NULL,
    [sort4_temp_mean]             NUMERIC (14, 4) NULL,
    [sort4_land_ratio_mean]       NUMERIC (14, 5) NULL,
    [sort4_land_ratio_median]     NUMERIC (14, 5) NULL,
    [sort4_land_mkt_ratio_mean]   NUMERIC (14, 5) NULL,
    [sort4_land_mkt_ratio_median] NUMERIC (14, 5) NULL,
    [sort4_market_median]         NUMERIC (14)    NULL,
    [sort4_sale_price_median]     NUMERIC (14)    NULL,
    [temp_avg_dev]                NUMERIC (14, 4) NULL,
    [temp_median]                 NUMERIC (14, 4) NULL,
    [temp_avg]                    NUMERIC (14, 4) NULL,
    [temp_cod]                    NUMERIC (14, 4) NULL,
    [temp_pop_var]                NUMERIC (18, 4) NULL,
    [temp_stdev]                  NUMERIC (14, 4) NULL,
    [temp_prd]                    NUMERIC (14, 4) NULL,
    [temp_wt_mean]                NUMERIC (14, 4) NULL,
    [temp_min]                    NUMERIC (14, 4) NULL,
    [temp_max]                    NUMERIC (14, 4) NULL,
    [temp_mean]                   NUMERIC (14, 4) NULL,
    [land_ratio_mean]             NUMERIC (14, 5) NULL,
    [land_ratio_median]           NUMERIC (14, 5) NULL,
    [land_mkt_ratio_mean]         NUMERIC (14, 5) NULL,
    [land_mkt_ratio_median]       NUMERIC (14, 5) NULL,
    [market_median]               NUMERIC (14)    NULL,
    [sale_price_median]           NUMERIC (14)    NULL,
    [temp_subdivision_cd]         CHAR (10)       NULL,
    [temp_subset_cd]              CHAR (5)        NULL,
    [temp_region_cd]              CHAR (5)        NULL,
    [temp_hood_cd]                CHAR (10)       NULL,
    [excise_number]               INT             NULL,
    [sl_ratio_cd_reason]          VARCHAR (100)   NULL,
    CONSTRAINT [CPK_sales_ratio_report] PRIMARY KEY CLUSTERED ([dataset_id] ASC, [row_id] ASC) WITH (FILLFACTOR = 100)
);


GO

