CREATE TABLE [dbo].[sales_ratio_report_property] (
    [dataset_id]       INT             NOT NULL,
    [row_id]           INT             IDENTITY (1, 1) NOT NULL,
    [chg_of_owner_id]  INT             NOT NULL,
    [prop_id]          INT             NOT NULL,
    [sup_num]          INT             NULL,
    [prop_val_yr]      NUMERIC (4)     NULL,
    [prop_type_cd]     CHAR (5)        NULL,
    [legal_desc]       VARCHAR (255)   NULL,
    [situs_location]   VARCHAR (255)   NULL,
    [eff_size_acres]   NUMERIC (14, 4) NULL,
    [legal_acreage]    NUMERIC (14, 4) NULL,
    [subdivision_cd]   CHAR (10)       NULL,
    [hood_cd]          CHAR (10)       NULL,
    [subset_cd]        CHAR (5)        NULL,
    [region_cd]        CHAR (5)        NULL,
    [geo_id]           VARCHAR (50)    NULL,
    [land_value]       NUMERIC (14)    NULL,
    [market_value]     NUMERIC (14)    NULL,
    [living_area_sqft] NUMERIC (18, 4) NULL,
    [appraiser_nm]     VARCHAR (40)    NULL,
    [dor_use_code]     VARCHAR (10)    NULL,
    [imprv_val_1]      NUMERIC (14)    NULL,
    [imprv_desc_1]     VARCHAR (255)   NULL,
    [imprv_val_2]      NUMERIC (14)    NULL,
    [imprv_desc_2]     VARCHAR (255)   NULL,
    [imprv_val_3]      NUMERIC (14)    NULL,
    [imprv_desc_3]     VARCHAR (255)   NULL,
    [econ_pct]         NUMERIC (5, 2)  NULL,
    [phy_pct]          NUMERIC (5, 2)  NULL,
    [func_pct]         NUMERIC (5, 2)  NULL,
    [map_id]           VARCHAR (20)    NULL,
    [prop_inactive_dt] DATETIME        NULL,
    [base_dep]         NUMERIC (5, 2)  NULL,
    [as_imprv_pct]     NUMERIC (5, 2)  NULL,
    [as_land_pct]      NUMERIC (5, 2)  NULL,
    [hood_imprv_pct]   NUMERIC (5, 2)  NULL,
    [hood_land_pct]    NUMERIC (5, 2)  NULL,
    CONSTRAINT [CPK_sales_ratio_report_property] PRIMARY KEY CLUSTERED ([dataset_id] ASC, [row_id] ASC) WITH (FILLFACTOR = 100)
);


GO

