CREATE TABLE [dbo].[transfer_tax_stmnt] (
    [levy_group_id]                  INT              NULL,
    [levy_group_yr]                  NUMERIC (4)      NULL,
    [levy_run_id]                    INT              NULL,
    [prop_type_cd]                   CHAR (5)         NULL,
    [prop_id]                        INT              NULL,
    [owner_id]                       INT              NULL,
    [sup_num]                        INT              NULL,
    [sup_tax_yr]                     NUMERIC (4)      NULL,
    [stmnt_id]                       INT              NULL,
    [pct_ownership]                  NUMERIC (13, 10) NULL,
    [geo_id]                         CHAR (50)        NULL,
    [sa_addr_line1]                  CHAR (60)        NULL,
    [sa_addr_line2]                  CHAR (60)        NULL,
    [sa_addr_line3]                  CHAR (60)        NULL,
    [sa_city]                        CHAR (50)        NULL,
    [sa_state]                       CHAR (50)        NULL,
    [sa_zip]                         CHAR (50)        NULL,
    [sa_fax]                         CHAR (20)        NULL,
    [sa_phone]                       CHAR (20)        NULL,
    [agent_copy]                     CHAR (1)         NULL,
    [agent_id]                       INT              NULL,
    [mortgage_copy]                  CHAR (1)         NULL,
    [owner_name]                     CHAR (70)        NULL,
    [owner_addr_line1]               CHAR (60)        NULL,
    [owner_addr_line2]               CHAR (60)        NULL,
    [owner_addr_line3]               CHAR (60)        NULL,
    [owner_addr_city]                CHAR (50)        NULL,
    [owner_addr_state]               CHAR (50)        NULL,
    [owner_addr_zip]                 CHAR (50)        NULL,
    [owner_addr_country]             CHAR (5)         NULL,
    [owner_addr_deliverable]         CHAR (10)        NULL,
    [mail_to_type]                   CHAR (1)         NULL,
    [mail_to_id]                     INT              NOT NULL,
    [mail_to_name]                   CHAR (70)        NULL,
    [mail_to_addr_line1]             CHAR (60)        NULL,
    [mail_to_addr_line2]             CHAR (60)        NULL,
    [mail_to_addr_line3]             CHAR (60)        NULL,
    [mail_to_addr_city]              CHAR (50)        NULL,
    [mail_to_addr_state]             CHAR (50)        NULL,
    [mail_to_addr_zip]               CHAR (50)        NULL,
    [mail_to_addr_country]           CHAR (5)         NULL,
    [mail_to_addr_deliverable]       CHAR (1)         NULL,
    [legal_desc]                     CHAR (255)       NULL,
    [legal_acreage]                  NUMERIC (14, 4)  NULL,
    [vit_flag]                       CHAR (1)         NULL,
    [primary_situs]                  CHAR (1)         NULL,
    [situs_num]                      CHAR (15)        NULL,
    [situs_street_prefx]             CHAR (10)        NULL,
    [situs_street]                   CHAR (50)        NULL,
    [situs_street_sufix]             CHAR (10)        NULL,
    [situs_unit]                     CHAR (5)         NULL,
    [situs_city]                     CHAR (30)        NULL,
    [situs_state]                    CHAR (2)         NULL,
    [situs_zip]                      CHAR (10)        NULL,
    [situs_display]                  CHAR (150)       NULL,
    [imprv_hstd_val]                 NUMERIC (14)     NULL,
    [imprv_non_hstd_val]             NUMERIC (14)     NULL,
    [land_hstd_val]                  NUMERIC (14)     NULL,
    [land_non_hstd_val]              NUMERIC (14)     NULL,
    [ag_market]                      NUMERIC (14)     NULL,
    [ag_use]                         NUMERIC (14)     NULL,
    [tim_market]                     NUMERIC (14)     NULL,
    [tim_use]                        NUMERIC (14)     NULL,
    [ten_percent_cap]                NUMERIC (14)     NULL,
    [assessed_val]                   NUMERIC (14)     NULL,
    [appraised_val]                  NUMERIC (14)     NULL,
    [mortgage_id]                    INT              NULL,
    [mortgage_desc]                  CHAR (70)        NULL,
    [mortgage_acct]                  CHAR (50)        NULL,
    [entity_1_id]                    INT              NULL,
    [entity_1_cd]                    CHAR (10)        NULL,
    [entity_1_name]                  CHAR (70)        NULL,
    [entity_1_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_1_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_1_assessed]              NUMERIC (14)     NULL,
    [entity_1_taxable]               NUMERIC (14)     NULL,
    [entity_1_hs_amt]                NUMERIC (14)     NULL,
    [entity_1_dv_amt]                NUMERIC (14)     NULL,
    [entity_1_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_1_other_amt]             NUMERIC (14)     NULL,
    [entity_1_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_2_id]                    INT              NULL,
    [entity_2_cd]                    CHAR (10)        NULL,
    [entity_2_name]                  CHAR (70)        NULL,
    [entity_2_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_2_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_2_assessed]              NUMERIC (14)     NULL,
    [entity_2_taxable]               NUMERIC (14)     NULL,
    [entity_2_hs_amt]                NUMERIC (14)     NULL,
    [entity_2_dv_amt]                NUMERIC (14)     NULL,
    [entity_2_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_2_other_amt]             NUMERIC (14)     NULL,
    [entity_2_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_3_id]                    INT              NULL,
    [entity_3_cd]                    CHAR (10)        NULL,
    [entity_3_name]                  CHAR (70)        NULL,
    [entity_3_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_3_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_3_assessed]              NUMERIC (14)     NULL,
    [entity_3_taxable]               NUMERIC (14)     NULL,
    [entity_3_hs_amt]                NUMERIC (14)     NULL,
    [entity_3_dv_amt]                NUMERIC (14)     NULL,
    [entity_3_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_3_other_amt]             NUMERIC (14)     NULL,
    [entity_3_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_4_id]                    INT              NULL,
    [entity_4_cd]                    CHAR (10)        NULL,
    [entity_4_name]                  CHAR (70)        NULL,
    [entity_4_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_4_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_4_assessed]              NUMERIC (14)     NULL,
    [entity_4_taxable]               NUMERIC (14)     NULL,
    [entity_4_hs_amt]                NUMERIC (14)     NULL,
    [entity_4_dv_amt]                NUMERIC (14)     NULL,
    [entity_4_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_4_other_amt]             NUMERIC (14)     NULL,
    [entity_4_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_5_id]                    INT              NULL,
    [entity_5_cd]                    CHAR (10)        NULL,
    [entity_5_name]                  CHAR (70)        NULL,
    [entity_5_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_5_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_5_assessed]              NUMERIC (14)     NULL,
    [entity_5_taxable]               NUMERIC (14)     NULL,
    [entity_5_hs_amt]                NUMERIC (14)     NULL,
    [entity_5_dv_amt]                NUMERIC (14)     NULL,
    [entity_5_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_5_other_amt]             NUMERIC (14)     NULL,
    [entity_5_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_6_id]                    INT              NULL,
    [entity_6_cd]                    CHAR (10)        NULL,
    [entity_6_name]                  CHAR (70)        NULL,
    [entity_6_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_6_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_6_assessed]              NUMERIC (14)     NULL,
    [entity_6_taxable]               NUMERIC (14)     NULL,
    [entity_6_hs_amt]                NUMERIC (14)     NULL,
    [entity_6_dv_amt]                NUMERIC (14)     NULL,
    [entity_6_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_6_other_amt]             NUMERIC (14)     NULL,
    [entity_6_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_7_id]                    INT              NULL,
    [entity_7_cd]                    CHAR (10)        NULL,
    [entity_7_name]                  CHAR (70)        NULL,
    [entity_7_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_7_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_7_assessed]              NUMERIC (14)     NULL,
    [entity_7_taxable]               NUMERIC (14)     NULL,
    [entity_7_hs_amt]                NUMERIC (14)     NULL,
    [entity_7_dv_amt]                NUMERIC (14)     NULL,
    [entity_7_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_7_other_amt]             NUMERIC (14)     NULL,
    [entity_7_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_8_id]                    INT              NULL,
    [entity_8_cd]                    CHAR (10)        NULL,
    [entity_8_name]                  CHAR (70)        NULL,
    [entity_8_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_8_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_8_assessed]              NUMERIC (14)     NULL,
    [entity_8_taxable]               NUMERIC (14)     NULL,
    [entity_8_hs_amt]                NUMERIC (14)     NULL,
    [entity_8_dv_amt]                NUMERIC (14)     NULL,
    [entity_8_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_8_other_amt]             NUMERIC (14)     NULL,
    [entity_8_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_9_id]                    INT              NULL,
    [entity_9_cd]                    CHAR (10)        NULL,
    [entity_9_name]                  CHAR (70)        NULL,
    [entity_9_tax_rate]              NUMERIC (13, 10) NULL,
    [entity_9_prop_pct]              NUMERIC (13, 10) NULL,
    [entity_9_assessed]              NUMERIC (14)     NULL,
    [entity_9_taxable]               NUMERIC (14)     NULL,
    [entity_9_hs_amt]                NUMERIC (14)     NULL,
    [entity_9_dv_amt]                NUMERIC (14)     NULL,
    [entity_9_ov65dp_amt]            NUMERIC (14)     NULL,
    [entity_9_other_amt]             NUMERIC (14)     NULL,
    [entity_9_tax_amt]               NUMERIC (14, 2)  NULL,
    [entity_10_id]                   INT              NULL,
    [entity_10_cd]                   CHAR (10)        NULL,
    [entity_10_name]                 CHAR (70)        NULL,
    [entity_10_tax_rate]             NUMERIC (13, 10) NULL,
    [entity_10_prop_pct]             NUMERIC (13, 10) NULL,
    [entity_10_assessed]             NUMERIC (14)     NULL,
    [entity_10_taxable]              NUMERIC (14)     NULL,
    [entity_10_hs_amt]               NUMERIC (14)     NULL,
    [entity_10_dv_amt]               NUMERIC (14)     NULL,
    [entity_10_ov65dp_amt]           NUMERIC (14)     NULL,
    [entity_10_other_amt]            NUMERIC (14)     NULL,
    [entity_10_tax_amt]              NUMERIC (14, 2)  NULL,
    [total_taxes_due]                NUMERIC (14, 2)  NULL,
    [oct_tax_due]                    NUMERIC (14, 2)  NULL,
    [oct_pi_due]                     NUMERIC (14, 2)  NULL,
    [nov_tax_due]                    NUMERIC (14, 2)  NULL,
    [nov_pi_due]                     NUMERIC (14, 2)  NULL,
    [dec_tax_due]                    NUMERIC (14, 2)  NULL,
    [dec_pi_due]                     NUMERIC (14, 2)  NULL,
    [jan_tax_due]                    NUMERIC (14, 2)  NULL,
    [jan_pi_due]                     NUMERIC (14, 2)  NULL,
    [feb_tax_due]                    NUMERIC (14, 2)  NULL,
    [feb_pi_due]                     NUMERIC (14, 2)  NULL,
    [mar_tax_due]                    NUMERIC (14, 2)  NULL,
    [mar_pi_due]                     NUMERIC (14, 2)  NULL,
    [apr_tax_due]                    NUMERIC (14, 2)  NULL,
    [apr_pi_due]                     NUMERIC (14, 2)  NULL,
    [may_tax_due]                    NUMERIC (14, 2)  NULL,
    [may_pi_due]                     NUMERIC (14, 2)  NULL,
    [june_tax_due]                   NUMERIC (14, 2)  NULL,
    [june_pi_due]                    NUMERIC (14, 2)  NULL,
    [july_tax_due]                   NUMERIC (14, 2)  NULL,
    [july_pi_due]                    NUMERIC (14, 2)  NULL,
    [taxes_saved]                    NUMERIC (14, 2)  NULL,
    [exemptions]                     CHAR (150)       NULL,
    [ov65]                           CHAR (1)         NULL,
    [type_of_int]                    CHAR (5)         NULL,
    [mineral_int_pct]                NUMERIC (13, 10) NULL,
    [event_id]                       INT              NULL,
    [oct_actual_date]                DATETIME         NULL,
    [nov_actual_date]                DATETIME         NULL,
    [dec_actual_date]                DATETIME         NULL,
    [jan_actual_date]                DATETIME         NULL,
    [feb_actual_date]                DATETIME         NULL,
    [mar_actual_date]                DATETIME         NULL,
    [apr_actual_date]                DATETIME         NULL,
    [may_actual_date]                DATETIME         NULL,
    [june_actual_date]               DATETIME         NULL,
    [july_actual_date]               DATETIME         NULL,
    [tax_saved_city]                 NUMERIC (14, 2)  NULL,
    [tax_saved_county]               NUMERIC (14, 2)  NULL,
    [entity_1_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_1_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_1_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_2_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_2_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_2_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_3_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_3_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_3_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_4_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_4_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_4_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_5_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_5_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_5_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_6_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_6_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_6_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_7_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_7_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_7_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_8_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_8_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_8_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_9_oct_due]               NUMERIC (14, 2)  NULL,
    [entity_9_nov_due]               NUMERIC (14, 2)  NULL,
    [entity_9_dec_due]               NUMERIC (14, 2)  NULL,
    [entity_10_oct_due]              NUMERIC (14, 2)  NULL,
    [entity_10_nov_due]              NUMERIC (14, 2)  NULL,
    [entity_10_dec_due]              NUMERIC (14, 2)  NULL,
    [entity_1_discount]              CHAR (1)         NULL,
    [entity_2_discount]              CHAR (1)         NULL,
    [entity_3_discount]              CHAR (1)         NULL,
    [entity_4_discount]              CHAR (1)         NULL,
    [entity_5_discount]              CHAR (1)         NULL,
    [entity_6_discount]              CHAR (1)         NULL,
    [entity_7_discount]              CHAR (1)         NULL,
    [entity_8_discount]              CHAR (1)         NULL,
    [entity_9_discount]              CHAR (1)         NULL,
    [entity_10_discount]             CHAR (1)         NULL,
    [entity_1_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_2_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_3_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_4_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_5_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_6_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_7_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_8_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_9_jan_due]               NUMERIC (14, 2)  NULL,
    [entity_10_jan_due]              NUMERIC (14, 2)  NULL,
    [q1_due]                         NUMERIC (14, 2)  NULL,
    [q2_due]                         NUMERIC (14, 2)  NULL,
    [q3_due]                         NUMERIC (14, 2)  NULL,
    [q4_due]                         NUMERIC (14, 2)  NULL,
    [taxserver_id]                   INT              NULL,
    [taxserver_copy]                 CHAR (1)         NULL,
    [show_freeze]                    CHAR (1)         NULL,
    [h1_due]                         NUMERIC (14, 2)  NULL,
    [h2_due]                         NUMERIC (14, 2)  NULL,
    [lKey]                           INT              IDENTITY (1, 1) NOT NULL,
    [entity_1_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_1_freeze_yr]             CHAR (4)         NULL,
    [entity_1_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_2_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_2_freeze_yr]             CHAR (4)         NULL,
    [entity_2_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_3_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_3_freeze_yr]             CHAR (4)         NULL,
    [entity_3_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_4_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_4_freeze_yr]             CHAR (4)         NULL,
    [entity_4_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_5_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_5_freeze_yr]             CHAR (4)         NULL,
    [entity_5_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_6_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_6_freeze_yr]             CHAR (4)         NULL,
    [entity_6_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_7_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_7_freeze_yr]             CHAR (4)         NULL,
    [entity_7_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_8_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_8_freeze_yr]             CHAR (4)         NULL,
    [entity_8_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_9_freeze_exmpt_type_cd]  CHAR (5)         NULL,
    [entity_9_freeze_yr]             CHAR (4)         NULL,
    [entity_9_freeze_ceiling]        VARCHAR (14)     NULL,
    [entity_10_freeze_exmpt_type_cd] CHAR (5)         NULL,
    [entity_10_freeze_yr]            CHAR (4)         NULL,
    [entity_10_freeze_ceiling]       VARCHAR (14)     NULL,
    [delq_tax]                       CHAR (1)         NULL,
    [escrow_bal]                     CHAR (1)         NULL,
    [owner_addr_is_international]    BIT              CONSTRAINT [CDF_transfer_tax_stmnt_owner_addr_is_international] DEFAULT (0) NOT NULL,
    [mail_to_addr_is_international]  BIT              CONSTRAINT [CDF_transfer_tax_stmnt_mail_to_addr_is_international] DEFAULT (0) NOT NULL,
    CONSTRAINT [CPK_transfer_tax_stmnt] PRIMARY KEY CLUSTERED ([lKey] ASC) WITH (FILLFACTOR = 100)
);


GO

CREATE NONCLUSTERED INDEX [idx_levy_group_yr]
    ON [dbo].[transfer_tax_stmnt]([levy_group_yr] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_sup_tax_yr]
    ON [dbo].[transfer_tax_stmnt]([sup_tax_yr] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_prop_id]
    ON [dbo].[transfer_tax_stmnt]([prop_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_levy_group_id_levy_group_yr_levy_run_id_prop_type_cd_prop_id_owner_id_sup_num_sup_tax_yr_stmnt_id]
    ON [dbo].[transfer_tax_stmnt]([levy_group_id] ASC, [levy_group_yr] ASC, [levy_run_id] ASC, [prop_type_cd] ASC, [prop_id] ASC, [owner_id] ASC, [sup_num] ASC, [sup_tax_yr] ASC, [stmnt_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_stmnt_id]
    ON [dbo].[transfer_tax_stmnt]([stmnt_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_owner_id]
    ON [dbo].[transfer_tax_stmnt]([owner_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_levy_run_id]
    ON [dbo].[transfer_tax_stmnt]([levy_run_id] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_sup_num]
    ON [dbo].[transfer_tax_stmnt]([sup_num] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_prop_type_cd]
    ON [dbo].[transfer_tax_stmnt]([prop_type_cd] ASC) WITH (FILLFACTOR = 90);


GO

CREATE NONCLUSTERED INDEX [idx_event_id]
    ON [dbo].[transfer_tax_stmnt]([event_id] ASC) WITH (FILLFACTOR = 90);


GO

