CREATE TABLE [dbo].[validation_totals] (
    [validation_id]          INT              NOT NULL,
    [entity_id]              INT              NOT NULL,
    [prop_val_yr]            NUMERIC (4)      NOT NULL,
    [pacs_user_id]           INT              NOT NULL,
    [date_time]              DATETIME         NULL,
    [arb_status]             VARCHAR (1)      NOT NULL,
    [prop_count]             NUMERIC (14)     NULL,
    [land_hstd_val]          NUMERIC (14)     NULL,
    [land_non_hstd_val]      NUMERIC (14)     NULL,
    [imprv_hstd_val]         NUMERIC (14)     NULL,
    [imprv_non_hstd_val]     NUMERIC (14)     NULL,
    [personal_prop_count]    NUMERIC (14)     NULL,
    [personal_val]           NUMERIC (14)     NULL,
    [mineral_prop_count]     NUMERIC (14)     NULL,
    [mineral_val]            NUMERIC (14)     NULL,
    [auto_prop_count]        NUMERIC (14)     NULL,
    [auto_val]               NUMERIC (14)     NULL,
    [ag_market]              NUMERIC (14)     NULL,
    [timber_market]          NUMERIC (14)     NULL,
    [ag_use]                 NUMERIC (14)     NULL,
    [timber_use]             NUMERIC (14)     NULL,
    [productivity_loss]      NUMERIC (14)     NULL,
    [ag_market_ex]           NUMERIC (14)     NULL,
    [timber_market_ex]       NUMERIC (14)     NULL,
    [ag_use_ex]              NUMERIC (14)     NULL,
    [timber_use_ex]          NUMERIC (14)     NULL,
    [productivity_loss_ex]   NUMERIC (14)     NULL,
    [ten_percent_cap]        NUMERIC (14)     NULL,
    [total_exemption_amount] NUMERIC (14)     NULL,
    [tax_rate]               NUMERIC (13, 10) NULL,
    [tax_increment_loss]     NUMERIC (14)     NULL,
    [levy_amount]            NUMERIC (14)     NULL,
    [weed_taxable_acres]     NUMERIC (14, 4)  NULL,
    [tnt_export_id]          INT              NOT NULL,
    [sup_num]                INT              CONSTRAINT [CDF_validation_totals_sup_num] DEFAULT (0) NOT NULL,
    [market_val]             NUMERIC (14)     NULL,
    [appraised_val]          NUMERIC (14)     NULL,
    [assessed_val]           NUMERIC (14)     NULL,
    [taxable_val]            NUMERIC (14)     NULL,
    CONSTRAINT [CPK_validation_totals] PRIMARY KEY CLUSTERED ([validation_id] ASC, [pacs_user_id] ASC, [entity_id] ASC, [prop_val_yr] ASC, [arb_status] ASC, [tnt_export_id] ASC, [sup_num] ASC) WITH (FILLFACTOR = 100)
);


GO

