import datetime
from types import ModuleType

from typing import Callable, Any, NamedTuple, Iterable, Iterator

__all__ = [
    "inProcess",
    "noisy",
    "logcall",
    "ArgAdaptor",
    "listofnamedtuples",
    "getstartingpage",
    "fetchautocomplete",
    "py3_syntax_report",
]

class user(NamedTuple):
    ClientName: str
    ConnectionTime: datetime.datetime
    ID: int
    IsDirectConnection: bool
    Name: str

def inProcess() -> bool: ...
def noisy() -> None: ...
def logcall() -> None: ...

class ArgAdaptor:
    __args__: dict[str, Any]

    @classmethod
    def maskargs(cls, fn: Callable): ...
    @classmethod
    def maskmethods(cls, otherclass: type) -> None: ...

class RASTER_SENTINEL:
    __esri_toolinfo__: list[str]

def _mergelines(lines: list[str], newline: str) -> list[str]: ...
def _fixedwhitespace(whitespacestring: str | list[str]) -> str: ...
def _get_lines_with_prototype(doc_string: str) -> list[str]: ...
def reformat_doc_string(
    obj_tokens: list[str],
    object_of_interest: Any,
    object_parent: ModuleType | None = None,
) -> str: ...
def fixdocstring(
    object_to_fetch: str,
    _builtins: dict[str, Any],
    _globals: dict[str, Any],
    _locals: dict[str, Any],
) -> str: ...
def _pick_names(part: str, name_list: Iterable[str]) -> list[str]: ...
def find_autocomplete_candidates(
    code: str, string_index: int, var_dict: dict[str, Any]
) -> Iterator[dict[str, str]]: ...
def _fetchvar(varname: str, var_dict: dict[str, Any]) -> tuple[list[str], Any]: ...
def in_index(string_index: int, start: int, end: int) -> int: ...
def call_ranges(code: str, string_index: int) -> list[tuple[Any]]: ...
def function_call_in_context(code: str, string_index: int, var_dict: dict[str, Any]) -> tuple[Any]: ...
def split_call_string(call_string: str) -> Iterator[str]: ...
def arg_index_for_call_string(call_string: str) -> tuple[Any]: ...
def parse_spec(call_prototype: str) -> dict[Any, Any]: ...
def values_for_dropdown_function(args: str) -> tuple[Any]: ...
def get_index_and_argvals_for_dropdown_call(call_string: str, index: int) -> tuple[Any]: ...
def tool_popup_items(found_item: Any, call_str: str, start_index: int) -> Iterator[dict[str, str]]: ...
def _fix_paraminfo_item(param_info_string: str) -> tuple[Any] | None: ...
def tool_item_items(found_item: Any, call_str: str, start_index: int) -> Iterator[dict[str, str]]: ...
def _fixline(line: str) -> Iterator[str]: ...
def _textwrap(text: str) -> str: ...
def help_tip(
    call_str: str,
    call_index: int,
    obj_tokens: list[str],
    found_item: Any,
    start_index: int,
) -> tuple[str, list[Any]]: ...
def find_autocomplete_xml(code: str, string_index: int, var_dict: dict[str, Any]) -> str | None: ...
def fetchautocomplete(code: str, string_index: int) -> str | None: ...
def listofnamedtuples(list_of_dicts: list[dict], tuple_name: str = "") -> list[NamedTuple]: ...
def getstartingpage(page_range_string: str) -> int: ...
def get_all_fix_names() -> list[str]: ...
def code_to_python_3(code_block: str, filename: str) -> str: ...
def code_diff_report(python_source: str, new_source: str, filename: str) -> str: ...
def py3_syntax_report(python_source: str, filename: str = "<script>") -> str: ...
