name: grfe-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        working-directory: monorepo-scaffolding
        run: |
          cargo --version
          cargo build --workspace --locked --verbose
      - name: Test
        working-directory: monorepo-scaffolding
        run: cargo test --workspace --locked --verbose
